- .gitignore
- build/build.xml
- src/org/zaproxy/zap/extension/codedx/CodeDxExtension.java
- src/org/zaproxy/zap/extension/codedx/ExtensionAlertHttp.java
- src/org/zaproxy/zap/extension/codedx/ReportLastScanHttp.java
- src/org/zaproxy/zap/extension/codedx/ZapAddOn.xml
- src/org/zaproxy/zap/extension/codedx/resources/Messages.properties
This extension adds an alternate XML reporter to the Report dropdown that includes http request and response data, to support the data needs of [Code Dx](http://codedx.com/)
> add plugin for codedx reports

- src/org/zaproxy/zap/extension/advreport/AlertDetailsPanel.java
- src/org/zaproxy/zap/extension/advreport/AlertsPanel.java
- src/org/zaproxy/zap/extension/advreport/ExtensionAdvReport.java
- src/org/zaproxy/zap/extension/advreport/OptionDialog.java
- src/org/zaproxy/zap/extension/advreport/ReportLastScan.java
- src/org/zaproxy/zap/extension/advreport/ScopePanel.java
- src/org/zaproxy/zap/extension/advreport/ZapAddOn.xml
- src/org/zaproxy/zap/extension/advreport/files/xml/mergeAlertitems.xml.xsl
- src/org/zaproxy/zap/extension/advreport/files/xml/report.concise.html.xsl
- src/org/zaproxy/zap/extension/advreport/files/xml/report.separated.html.xsl
- src/org/zaproxy/zap/extension/advreport/files/xml/report.traditional.html.xsl
Added options to include or not Description, Other Info, Solution, Reference, CWE Id, WASC Id into a report.  Now more information can be added: Request header, Request body, Response header, Response body.
Changed layout of the report and fixed some bugs in concise report xsl where description and name of report were not showing.  Fixed logic in concise reports to group by site_name+alert_name, not just alert_name.
> Added options to select Alert Attributes for advreport alpha extension

- src/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScanner.java
CWE-614: Sensitive Cookie in HTTPS Session Without 'Secure' Attribute
> Add CWE id for 'Secure' attribute in cookies

- src/org/zaproxy/zap/extension/soap/WSDLCustomParser.java
- src/org/zaproxy/zap/extension/soap/ZapAddOn.xml
This is the continuation of a previous pull request: https://github.com/zaproxy/zap-extensions/pull/30
I have fixed most of the things indicated there. However, no solution comes to my mind about preserving the fix when reopening sessions without making modifications outside the plugin.
> [Alpha extension] SOAP Scanner fix: operations with the same location were overwritten in the sites tree.

- src/org/zaproxy/zap/extension/bruteforce/BruteForcePanel.java
- src/org/zaproxy/zap/extension/bruteforce/ZapAddOn.xml
- src/org/zaproxy/zap/extension/bruteforce/resources/Messages.properties
This is the simplest solution possible. The `Manager` class already have a method called `getTotatDone` which the `BruteForcePanel` already listen to. Although, this is not ideal that's how it currently works. 
As part of #559 I would like to refactor this behavior to use something unblocking, but this might take a long time and I thought that would be better to have something simple and working now then improve afterwards. Please, let me know your thoughts
> #1873 - adding num requests to brute force panel

- src/org/zaproxy/zap/extension/ascanrulesBeta/ExtensionAscanRulesBeta.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/XXEPlugin.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
Change ExtensionAscanRulesBeta to take care to install and uninstall the
API used by XXEPlugin. The API is (created and) installed when required
by the XXEPlugin, and removed when the add-on is uninstalled.
Change XXEPlugin to no longer create and install the API but obtain it
from ExtensionAscanRulesBeta.
Fix zaproxy/zaproxy#1972 - Resource leak while uninstalling "Active
scanner rules (beta)" add-on
> ascanrulesBeta: remove XXE API when the add-on is uninstalled

- src/org/zaproxy/zap/extension/ascanrules/BufferOverflow.java
- src/org/zaproxy/zap/extension/ascanrules/FormatString.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
I added code to dump out of Format String and Buffer Overflow if it detects a server error before running the scanner.  I also upgraded the exception handling.  Two commits are used.  One for each scanner.
> Minimized False Positives in Format String and Buffer Overflow

- src/org/zaproxy/zap/extension/diff/ZapAddOn.xml
- src/org/zaproxy/zap/extension/diff/ZapDiffRowGenerator.java
Change ZapDiffRowGenerator to not add the break line tags to the
resultant diff by disabling the word wrapping (which was not effectively
working), word wrapping should be done by the view component.
Fix zaproxy/zaproxy#1571 - Diffs contain superfluous "\<br>" tags.
> diff: do not add line break tags to the resultant diff

- src/org/zaproxy/zap/extension/advreport/AlertDetailsPanel.java
- src/org/zaproxy/zap/extension/advreport/AlertsPanel.java
- src/org/zaproxy/zap/extension/advreport/ExtensionAdvReport.java
- src/org/zaproxy/zap/extension/advreport/OptionDialog.java
- src/org/zaproxy/zap/extension/advreport/ScopePanel.java
To avoid repetition across multiple panels, moved 'Cancel' and 'Generate HTML' buttons under the class ExtensionAdvReport.java
> advreport: consolidated cancel and generate buttons under one class

- src/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
Change Base64Disclosure scanner to not use the variable "viewstatexml"
when raising informational alerts when a (plain) Base64 hash is found,
the variable "viewstatexml" is null in those cases (i.e. hash does not
represent a ViewState).
Also, remove redundant null check when raising the informational alert
(the variable "base64evidence" is non-null at that point).
Fix zaproxy/zaproxy#2037 - NullPointerException when passive scanning
with "Base64 Disclosure"
> Fix NullPointerException when scanning with Base64Disclosure

- src/org/zaproxy/zap/extension/ascanrulesAlpha/TestUserAgent.java
- src/org/zaproxy/zap/extension/domxss/TestDomXSS.java
- src/org/zaproxy/zap/extension/domxss/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ImageLocationScanner.java
Assign the new IDs as specified in the alerts.xml file:
- 10049 -> 10103, Image Location Scanner
- 10050 -> 10104, TestUserAgent
- 40025 -> 40026, Cross site scripting (DOM)
(reference: zaproxy/zaproxy#2006)
Update the changes and bump version in ZapAddOn.xml, were applicable.
> Fix duplicated IDs in active and passive scanners

- src/org/zaproxy/zap/extension/pscanrulesBeta/InsecureAuthenticationScan.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
Assign the new ID as specified in the alerts.xml file:
- 40017 -> 10105, Weak Authentication Method
(reference: zaproxy/zaproxy#2006)
Update the changes and bump version in ZapAddOn.xml.
> pscanrulesBeta: fix duplicated scanner ID of Weak Authentication Method

- src/org/zaproxy/zap/extension/diff/ExtensionDiff.java
- src/org/zaproxy/zap/extension/diff/ZapAddOn.xml
Change ExtensionDiff to close (dispose) the dialogue when unloading the
extension (done when uninstalling the add-on). Otherwise the dialogue
will remain open preventing the classes/add-on from being GC'ed, sooner.
Update the changes in ZapAddOn.xml.
> diff: automatically close the diff dialogue when uninstalling the add-on

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/DefaultStringPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
Change DefaultStringPayloadGeneratorUI to correctly call the method
String.split so that the empty strings are preserved. Also change to not
validate that the text area is non empty to allow the use of just one
empty string.
Remove info/validation strings no longer used from Messages.properties
file.
Fix zaproxy/zaproxy#1948 - Unable to add empty string payloads for
fuzzer
> fuzz: correctly produce empty string payloads in fuzzer dialogue

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
Add the missing resource string "fuzz.activeActionPrefix", used to
inform of the fuzz processes still running when closing ZAP.
> fuzz: fix MissingResourceException when closing ZAP while fuzzing

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/payloads/generator/ScriptStringPayloadGeneratorAdapter.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/ScriptStringPayloadGeneratorAdapterUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
Fixes, touching the same classes, related to payload generator scripts:
- Fix selection of the script in modify dialogue;
- zaproxy/zaproxy#1881 - Fuzzer Add-on Progress Bar stuck at 100%
- zaproxy/zaproxy#1887 - Number of payloads not shown for script
payload generator
> fuzz: issues with payload generator scripts

- src/org/zaproxy/zap/extension/fuzz/AbstractFuzzer.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
Change AbstractFuzzer to just create 3 times (1/3 being consumed) the
number of tasks as available threads (so that the consumer threads do
not wait for new tasks, but also do not create all tasks at once).
Fix zaproxy/zaproxy#2051 - Improve Fuzzer memory usage
> fuzz: create enough tasks to keep available threads busy, but no more

- src/org/zaproxy/zap/extension/fuzz/AbstractFuzzer.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
Change AbstractFuzzer class to create the tasks with incremental delay
so that all tasks wait the same time before sending the messages.
Otherwise the messages would be sent sooner than the delay specified.
> fuzz: correct the delay used when sending messages

- src/org/zaproxy/zap/extension/fuzz/AbstractFuzzer.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
Fix (potential) task submitter thread leak after stopping a paused
fuzzer, it was caused by not unpausing the thread when stopping (the
state was already set to stop so the pause comparison failed, always).
Improve stop time by letting the task threads to query the state of
the fuzzer, allowing to stop sooner (done by releasing the state lock,
which was no longer required as the stop state was already set, so the
"main" thread no longer has to wait 2 seconds for the task threads to
stop (which wouldn't, as the state lock was being held)).
> fuzz: fix issues related to stopping the fuzzer

- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/HttpFuzzerTaskProcessorUtils.java
Deprecate the old method (it might be used by scripts).
> fuzz: fix typo in method name of HttpFuzzerTaskProcessorUtils

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/payloads/processor/ExpandStringProcessor.java
Switch the begin/end statements that add the original string to the
expanded string.
> fuzz: fix the insert location of the string in expand string processor

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/ScriptStringPayloadProcessorAdapterUIHandler.java
Change ScriptStringPayloadProcessorAdapterUI to allow to modify the
selected payload processor script otherwise it requires to remove and
add the payload processor script (and move it to correct position).
Change ScriptStringPayloadProcessorAdapterUIPanel to correctly select
the payload processor script when showing the modify dialogue (by
selecting using a ScriptUIEntry instead of ScriptWrapper) and to not
deselect the scripts when clearing (so that there's always a script
selected when adding).
> fuzz: allow to modify the selected payload processor script

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/impl/AddProcessorDialog.java
- src/org/zaproxy/zap/extension/fuzz/impl/FuzzMessageLocationsPanel.java
- src/org/zaproxy/zap/extension/fuzz/impl/MessageLocationPayloadsPanel.java
- src/org/zaproxy/zap/extension/fuzz/impl/ModifyProcessorDialog.java
- src/org/zaproxy/zap/extension/fuzz/impl/PayloadPreviewPanel.java
- src/org/zaproxy/zap/extension/fuzz/impl/PayloadsProcessedIterator.java
- src/org/zaproxy/zap/extension/fuzz/impl/ProcessorsMessageLocationDialog.java
- src/org/zaproxy/zap/extension/fuzz/impl/ProcessorsPayloadDialog.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/ScriptStringPayloadGeneratorAdapterUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/Base64DecodeProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/Base64EncodeProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/ExpandStringProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/JavaScriptEscapeProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/JavaScriptUnescapeProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/MD5HashProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/PayloadProcessorUIPanel.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/PostfixStringProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/PrefixStringProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/SHA1HashProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/SHA256HashProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/ScriptStringPayloadProcessorAdapterUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/TrimStringProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/URLDecodeProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/URLEncodeProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
Change all processor dialogues to allow to see the current payloads and
to preview the processing of the payloads with the selected options. The
payloads are shown in text areas under the processor options. The
current payloads are shown with previous processors applied (when adding
more processors per payload or adding processors per message location).
The preview does not allow to see all generated/processed payloads since
those might consume too much memory (more than what is actually
available), it is shown a fixed number of payloads which allow to have
an idea of what the processor does.
Add script validation to ScriptStringPayloadProcessorAdapterUIPanel, to
inform the user if the script does not implement the required interface
Fix …
> fuzz: show current and allow to preview payloads in processor dialogues

- src/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java
- src/org/zaproxy/zap/extension/fuzz/FuzzerPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/AbstractPersistentPayloadGeneratorUIPanel.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/DefaultStringPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/FileStringPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/RegexPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/ScriptStringPayloadGeneratorAdapterUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
Change String, Regex, File and Script payload generators to allow to
save the generated payloads to a file, that's available for selection in
the custom files of File Fuzzers. The generated payloads can be saved
using a button shown in the panel of the generators, which allows to
choose the name of the file (the location is always the same, the one
used to save the custom file fuzzers).
Fix zaproxy/zaproxy#1932 - Enhancement: Save user-created payloads for
reuse
> fuzz: allow to save (to file) String, Regex, File and Script payloads

- src/org/zaproxy/zap/extension/fuzz/FuzzerPayloadFileSource.java
- src/org/zaproxy/zap/extension/fuzz/FuzzerPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/FuzzerPayloadJBroFuzzSource.java
- src/org/zaproxy/zap/extension/fuzz/FuzzerPayloadSource.java
Limit the actual number of payloads that are used for the preview of
file fuzzers, otherwise it would be read all the file (during the
calculation of the number of payloads) instead of just enough for the
preview.
> fuzz: limit the number of payloads used for preview of file fuzzers

- src/org/zaproxy/zap/extension/fuzz/FuzzerPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/AbstractPersistentPayloadGeneratorUIPanel.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/FileStringPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/ModifyPayloadsPanel.java
- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
Change File and File Fuzzers payload generators to allow to modify the
payloads read/generated from the file(s). The payloads can be changed
in the modify dialogue of the corresponding generator, through a text
area. To not change the original file(s) nor keep the payloads in memory
longer than needed it's created a temporary file, used to save and load
the payloads as needed. The edition from within ZAP is limited to a
maximum number of payloads and size of the file that contains them (thus
limiting the size of the payloads). If the file is outside the limits
it's edited with an external text editor, if available.
Fix zaproxy/zaproxy#1897 - Enhancement: User Story - I can view and
modify the contents of the payloads I selected
> fuzz: allow to modify the payloads of file and file fuzzers generators

- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParam.java
- src/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Fixes zaproxy/zaproxy#2102 Allow ajax spider options to be set via the API
>  Allow ajax spider options to be set via the API

- src/org/zaproxy/zap/extension/websocket/db/TableWebSocket.java
URLs longer then 255 (actually 288) were truncated (1st Exception)
and could not be found later (2nd kind)
add debug log option
was discussed: github.com/zaproxy/zap-extensions/pull/131
> fix zaproxy/zaproxy#2097 long URL in WebSocket

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/FuzzerHttpMessageScriptProcessorAdapterUIHandler.java
Change FuzzerHttpMessageScriptProcessorAdapterUIHandler to correctly
select the HTTP processor script when showing the modify dialogue, by
selecting using a ScriptUIEntry (instead of ScriptWrapper).
> fuzz: make sure that the http processor script is shown as selected

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/dialogs/ZestAssignmentDialog.java
Add the missing field, operand B, to 'Assign variable to a calculation'
dialogue.
> zest: add missing field in dialogue 'Assign variable to a calculation'

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestAuthenticationRunner.java
Change class ZestAuthenticationRunner to send the requests using the
class AuthenticationHelper (instead of a custom HttpClient), which
respects ZAP's configurations (connection timeout, outgoing proxy...).
Fix zaproxy/zaproxy#2114 - Zest authentication requests not sent with
ZAP's configurations
> zest: send authentication requests with ZAP's configurations

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestSequenceRunner.java
- src/org/zaproxy/zap/extension/zest/resources/Messages.properties
Change class ZestSequenceRunner to use a custom StructuralSiteNode (not
backed by a HistoryReference) for the nodes to be scanned, to return a
custom name and a URI, preventing the NullPointerException(s) from
happening.
The issue was caused by a change in Target's implementation which
started to use a StructuralSiteNode instead of a plain SiteNode.
As part of the changes the nodes to be scanned and the Target were
changed to use a custom name. The custom name (name of the script plus
" (script)") is used, in the active scan tab and progress dialogue, to
properly indicate what is being scanned, otherwise it would not show
anything (that is, an empty string). The custom URI is not actually
scanned it's just used for comparisons with sibling nodes (which never
happen since there are just …
> zest: fix NullPointerException when active scanning a sequence script

- src/org/zaproxy/zap/extension/scripts/CommandPanel.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Change class CommandPanel to force the use of an older constructor of
RTextScrollPane so that the add-on can still be built for older ZAP
versions (>= 2.4.0). The change is required because the new version of
RSyntaxTextArea library introduced a new constructor which would be used
instead of the old constructor (leading to NoSuchMethodError).
Update version (and remove old changes) in ZapAddOn.xml file.
> scripts: force compatibility with older ZAP versions (>= 2.4.0)

- src/org/zaproxy/zap/extension/httpsInfo/MenuEntry.java
- src/org/zaproxy/zap/extension/httpsInfo/RightClickMenu.java
- src/org/zaproxy/zap/extension/httpsInfo/ZapAddOn.xml
Change class (extension) RightClickMenu to declare that it can be
dynamically unloaded and move the management of the SSL/TLS dialogues to
itself to keep track of dialogues open (to be closed when the add-on is
unloaded).
Change class MenuEntry to use the extension to show the dialogues.
> httpsInfo: allow to dynamically update/uninstall the add-on

- src/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/ModifyPayloadsPanel.java
Change the method ModifyPayloadsPanel.createTempFile() to create the
temporary file (used to keep the modified payloads) without custom
(POSIX) permissions (which would lead to an exception in Windows,
UnsupportedOperationException). Also, change to delete the temporary
files once ZAP is exited.
Bump version (in extension too) and update changes in ZapAddOn.xml file.
> fuzz: fix modification of file and file fuzzers in Windows

- src/org/zaproxy/zap/extension/pscanrulesAlpha/XChromeLoggerDataInfoLeakScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
Add new passive scanner to detect the presence of the response headers
X-ChromeLogger-Data or X-ChromePhp-Data which may leak server,
infrastructure, or code details which an attacker may leverage to
further abuse the system.
> New Passive Scanner for X-ChromeLogger-Data

- src/org/zaproxy/zap/extension/customreport/ExtensionCustomReport.java
- src/org/zaproxy/zap/extension/customreport/ZapAddOn.xml
Change class ExtensionCustomReport to declare that it can be dynamically
unloaded and on unloading close/dispose the "Generate report" dialogue.
Also, change to not create/show another dialogue if one is already open.
> customreport: allow to dynamically update/uninstall the add-on

- src/org/zaproxy/zap/extension/revisit/ExtensionRevisit.java
- src/org/zaproxy/zap/extension/revisit/ZapAddOn.xml
Change class ExtensionRevisit to declare that it can be dynamically
unloaded, allowing to dynamically update/uninstall the add-on, and on
unloading remove the RevisitAPI, close/dispose the "revisit setup"
dialogue and remove icons added to Sites tree. Also, change to reset
the revisit state when creating/loading the session and to declare its
dependencies.
> revisit: unload extension and reset revisit state on session changes

- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParam.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Apply the fix done to core class AbstractParam (that fixes its clone
method by cloning the configuration) so that the AJAX Spider add-on can
be fixed without waiting for a core release.
Related to zaproxy/zaproxy#2151 - AJAX Spider does not click all
elements set in the options
> spiderAjax: change AjaxSpiderParam to clone its configuration

- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/coreLang/ZapAddOn.xml
- src/org/zaproxy/zap/extension/directorylistv1/ZapAddOn.xml
- src/org/zaproxy/zap/extension/directorylistv2_3/ZapAddOn.xml
- src/org/zaproxy/zap/extension/directorylistv2_3_lc/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzzdb/ZapAddOn.xml
- src/org/zaproxy/zap/extension/gettingStarted/ZapAddOn.xml
- src/org/zaproxy/zap/extension/help/ZapAddOn.xml
- src/org/zaproxy/zap/extension/help_pt_BR/ZapAddOn.xml
- src/org/zaproxy/zap/extension/onlineMenu/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/quickstart/ZapAddOn.xml
- src/org/zaproxy/zap/extension/reveal/ZapAddOn.xml
- src/org/zaproxy/zap/extension/saverawmessage/ZapAddOn.xml
- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
The change allows to have all add-ons (alpha, beta and release) in a
single branch.
Note: the build system does not yet use that information.
> Add add-on status to ZapAddOn.xml

- src/org/zaproxy/zap/extension/accessControl/ZapAddOn.xml
- src/org/zaproxy/zap/extension/alertFilters/ZapAddOn.xml
- src/org/zaproxy/zap/extension/amf/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/birtreports/ZapAddOn.xml
- src/org/zaproxy/zap/extension/browserView/ZapAddOn.xml
- src/org/zaproxy/zap/extension/callgraph/ZapAddOn.xml
- src/org/zaproxy/zap/extension/cmss/ZapAddOn.xml
- src/org/zaproxy/zap/extension/codedx/ZapAddOn.xml
- src/org/zaproxy/zap/extension/customreport/ZapAddOn.xml
- src/org/zaproxy/zap/extension/domxss/ZapAddOn.xml
- src/org/zaproxy/zap/extension/help_bs_BA/ZapAddOn.xml
- src/org/zaproxy/zap/extension/help_es_ES/ZapAddOn.xml
- src/org/zaproxy/zap/extension/help_fr_FR/ZapAddOn.xml
- src/org/zaproxy/zap/extension/help_ja_JP/ZapAddOn.xml
- src/org/zaproxy/zap/extension/highlighter/ZapAddOn.xml
- src/org/zaproxy/zap/extension/httpsInfo/ZapAddOn.xml
- src/org/zaproxy/zap/extension/importLogFiles/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/revisit/ZapAddOn.xml
- src/org/zaproxy/zap/extension/saml/ZapAddOn.xml
- src/org/zaproxy/zap/extension/sequence/ZapAddOn.xml
- src/org/zaproxy/zap/extension/simpleExample/ZapAddOn.xml
- src/org/zaproxy/zap/extension/sniTerminator/ZapAddOn.xml
- src/org/zaproxy/zap/extension/soap/ZapAddOn.xml
- src/org/zaproxy/zap/extension/sse/ZapAddOn.xml
- src/org/zaproxy/zap/extension/vulncheck/ZapAddOn.xml
- src/org/zaproxy/zap/extension/wappalyzer/ZapAddOn.xml
- src/org/zaproxy/zap/extension/wavsepRpt/ZapAddOn.xml
The change allows to have all add-ons (alpha, beta and release) in a
single branch.
Note: the build system does not yet use that information.
> Add add-on status to ZapAddOn.xml (alpha)

- src/org/zaproxy/zap/extension/accessControl/ZapAddOn.xml
- src/org/zaproxy/zap/extension/accessControl/view/AccessControlStatusPanel.java
Change AccessControlStatusPanel to return immediately when the user
cancels the "Save" dialogue (for the access control report), otherwise
the not selected (null) file would be used in an error message (which
assumed that the report was generated but failed) leading to the
exception. Also, log the exception if it's not possible to create the
XML document during generation of the report (instead of print it to
standard output).
> accessControl: fix NullPointerException in AccessControlStatusPanel

- src/org/zaproxy/zap/extension/pscanrulesAlpha/UserControlledCharsetScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
Change UserControlledCharsetScanner to skip meta elements that specify
the content type but not a charset (thus null), which would lead to a
NullPointerException when attempting to compare the charset with the
values of the parameters.
> pscanrulesAlpha: fix a NPE in UserControlledCharsetScanner

- src/org/zaproxy/zap/extension/zest/OptionsZestIgnoreHeadersTableModel.java
- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
Change OptionsZestIgnoreHeadersTableModel to initialise the instance
variables "allHeaders" and "ignoredHeaders", with an empty list,
preventing, with the former, the EDT from failing to query its number of
rows (when validating the Component tree).
--
Issue reported in OWASP ZAP User Group: https://groups.google.com/d/msg/zaproxy-users/SMsOOxUUBGw/3m_PJz1lBAAJ
> zest: fix NullPointerException in OptionsZestIgnoreHeadersTableModel

- build/build.xml
To facilitate quick Dev builds. Created new macrodef, and targets to
facilitate quicker building during Dev cycles by excluding generation of
help indexes (build time 10sec vs 30-40sec).
> Allow scanner builds without generating help indexes

- src/org/zaproxy/zap/extension/pscanrulesAlpha/ImageLocationScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
Change ImageLocationScanner to initialise the "fileName" with an empty
string if it does not exist (that is, when URI path component does not
exist), which would lead to a NullPointerException when attempting to
extract the extension.
> pscanrulesAlpha: fix NullPointerException in ImageLocationScanner

- src/org/zaproxy/zap/extension/ascanrules/CodeInjectionPlugin.java
- src/org/zaproxy/zap/extension/ascanrules/CommandInjectionPlugin.java
- src/org/zaproxy/zap/extension/ascanrules/TestExternalRedirect.java
Change scanners CodeInjectionPlugin, CommandInjectionPlugin and
TestExternalRedirect to log the messages when an alert is found with
DEBUG level instead of INFO, to reduce the number of messages logged by
default (those messages are not really needed for everyday use, the
absence or presence of an alert already indicates that fact, if an error
occurred while raising the alert it would be logged by core code with
higher level, ERROR). For CodeInjectionPlugin also change TRACE log
level messages to DEBUG, the former is not used.
> ascanrules: reduce log level from INFO to DEBUG (and TRACE to DEBUG)

- src/org/zaproxy/zap/extension/ascanrulesBeta/UsernameEnumeration.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
Adjust logging, and implement plugin skip if runtime requirements not
met.
Fixes zaproxy/zaproxy#2180
> Issue 2180 - UsernameEnumeration - Overly verbose

- src/org/zaproxy/zap/extension/ascanrulesBeta/HPP.java
Added try/catch block around sendAndReceive for exceptions identified
via zapbot automated wavsep testing.
> Issue 2175 - Handle Previously UnCaught Exceptions

- src/org/zaproxy/zap/extension/saml/SAMLExtension.java
- src/org/zaproxy/zap/extension/saml/ZapAddOn.xml
- src/org/zaproxy/zap/extension/saml/resources/Messages.properties
Change class SAMLExtension to use ExtensionPopupMenuMessageContainer
instead of ExtensionPopupMenu to show the main pop up menu, the former
is enabled by default for components with HTTP messages (which contain
the SAML messages). Also, internationalise the label of the menu.
> saml: show (and internationalise) 'SAML Actions' main menu

- src/org/zaproxy/zap/extension/ascanrulesBeta/ExpressionLanguageInjectionPlugin.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
Added try/catch block around sendAndReceive for exceptions identified
via zapbot automated wavsep testing.
Fixes zaproxy/zaproxy#2174
> Issue 2174 - Handle Previously Uncaught Exceptions

- src/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
- src/org/zaproxy/zap/extension/wappalyzer/PopupMenuEvidence.java
- src/org/zaproxy/zap/extension/wappalyzer/ZapAddOn.xml
Change class ExtensionWappalyzer to declare that it can be dynamically
unloaded and change class PopupMenuEvidence to remove its sub menus from
the list of the main pop up menu once the menu is dismissed (otherwise
it would prevent the objects of the add-on from being GC'ed after it has
been unloaded).
> wappalyzer: allow to dynamically update/uninstall the add-on

- src/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2.java
- src/org/zaproxy/zap/extension/ascanrules/TestParameterTamper.java
- src/org/zaproxy/zap/extension/ascanrules/TestPersistentXSSAttack.java
- src/org/zaproxy/zap/extension/ascanrules/TestServerSideInclude.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
Change classes TestCrossSiteScriptV2, TestParameterTamper,
TestPersistentXSSAttack and TestServerSideInclude to check if the
scanner was stopped/skipped, by calling isStop() method.
For class TestServerSideInclude also extracted a method to reduce code
duplication.
Changes for zaproxy/zaproxy#1734 - Scanners take too much time to
skip/stop
> ascanrules: add isStop() checks (to scanners without any check)

- src/org/zaproxy/zap/extension/sequence/ExtensionSequence.java
- src/org/zaproxy/zap/extension/sequence/SequenceAscanPanel.java
- src/org/zaproxy/zap/extension/sequence/SequencePanel.java
- src/org/zaproxy/zap/extension/sequence/SequencePopupMenuItem.java
- src/org/zaproxy/zap/extension/sequence/ZapAddOn.xml
- src/org/zaproxy/zap/extension/sequence/resources/Messages.properties
Allow to dynamically update/uninstall the add-on (just missing the
declaration that it can be unloaded and the removal of the script type).
Declare its (hard) dependencies (ExtensionScript).
Finish internationalisation (some strings that were not yet
internationalised and remove one that was but was not being shown in the
GUI).
Remove hidden column by implementing a custom TableModel, to show the
scripts available in the "Sequence" panel.
Verify and warn if the scripts do not implement SequenceScript
interface.
Initialise view components only when ZAP has a view.
Remove unnecessary type arguments, casts and null checks.
> sequence: tidy up, dynamic unload, finish internationalisation

- src/org/zaproxy/zap/extension/ascanrules/CommandInjectionPlugin.java
Change PowerShell pattern in CommandInjectionPlugin to require the
presence, in the response, of not only "get-help" but one of its
following tokens ("cmdlets" or "get-alias") with at least one character
in between, to reduce false positives when the attack/input ("get-help")
is simply reflected in the response.
> ascanrules: tweak PowerShell control pattern to reduce false positives

- src/org/zaproxy/zap/extension/sqliplugin/ExtensionSQLiPlugin.java
- src/org/zaproxy/zap/extension/sqliplugin/SQLInjectionPlugin.java
- src/org/zaproxy/zap/extension/sqliplugin/SQLiUnionEngine.java
- src/org/zaproxy/zap/extension/sqliplugin/ZapAddOn.xml
- src/org/zaproxy/zap/extension/sqliplugin/resources/Messages.properties
Change scanner SQLInjectionPlugin to:
- Internationalise the name of the scanner and data of the alerts (add
helper extension, ExtensionSQLiPlugin, to force the load of the
resource messages);
- Reduce log level of messages from INFO to DEBUG (when an alert is
raised, a parameter is not "injectable" and info about UNION tests, in
class SQLiUnionEngine), to reduce the number of messages logged by
default (those messages are not really needed for everyday use, the
absence or presence of an alert already indicates that fact, if an
error occurred while raising the alert it would be logged by core code
with higher level, ERROR) and change TRACE log level message to DEBUG,
the former is not used;
- Check for skip/stop more often (before sending a message), to improve
the time it takes to stop …
> sqliplugin: internationalisation, reduce log level and add stop check

- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionMySQL.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionPostgresql.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
Added try/catch block around sendAndReceive for exceptions identified
via zapbot automated wavsep testing.
Fixes zaproxy/zaproxy#2178
Fixes zaproxy/zaproxy#2179
> Handle Previously Uncaught Exceptions

- src/org/zaproxy/zap/extension/zest/ExtensionZest.java
- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
Fixes zaproxy/zaproxy#2294  Zest: cannot use auth script in daemon mode
> Cannot use auth script in daemon mode

- src/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
Update pscanrules.html adding help content for numerous release quality
passive scanners that were missing descriptions.
> Add Missing Help Entries

- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
- src/org/zaproxy/zap/extension/spiderAjax/resources/help/contents/options.html
Remove old options from AJAX Spider's "options.html" help page, the
options no longer exist, browsers' configurations are now done through
the "Selenium" options panel.
> spiderAjax: remove old options from help page

- src/org/zaproxy/zap/extension/ascanrulesAlpha/HttpOnlySite.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
Hello,
According to the issue zaproxy/zaproxy#2207 the original idea of this issue was to raise alerts on all http sites whether or not https was available
But the other rule already raises alerts if http versions of https sites are available
So we thought that it might make sense to just raise alerts if https is _not_ available.
I have implemented this Active Scan rule which raises an alert if a site is only served under HTTP and not HTTPS. The work is still under progress so I would like to hear your feedback @thc202 , @kingthorin , @psiinon . Here is the TODO:
- ~~PLUGIN_ID~~ 
- ~~CATEGORY~~
- ~~RISK~~
- ~~CONFIDENCE~~
- ~~CWE~~ 
- ~~WASC~~ 
- ~~Attack Parameter in the Alert~~
- ~~Description~~ 
- ~~References~~ 
- ~~Solution~~ 
- ~~Testing any other case if needed.~~ 
- ~~Custom …
> A new Active Scan rule HttpOnlySite.

- src/org/zaproxy/zap/extension/alertFilters/ContextAlertFilterPanel.java
- src/org/zaproxy/zap/extension/alertFilters/ZapAddOn.xml
Builds on Pull Request 286.
In ContextAlertFilterPanel:
The Enabled column has a max width based on the optimal width 
for the header content, (can be made smaller, but not bigger).
This means that the dialog can be resized, and the main
content columns will resize, while Enabled stays static based
on the optimal length for the i18n heading being displayed.
> AlertFilters Minor UI Improvements2

- src/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureSVN.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
When the response does result in creation of a SVN wc.db temp file - log
read or query errors at debug level and only include the exception only
if debug is enabled.
Fixes zaproxy/zaproxy#2177
> Issue 2177 Adjust Logging

- src/org/zaproxy/zap/extension/accessControl/ExtensionAccessControl.java
- src/org/zaproxy/zap/extension/accessControl/ZapAddOn.xml
Change the method ExtensionAcessControl.canUnload() to return false,
the extension is not completely unloaded by default (Context factories
are not unloaded, requires core changes), which might lead to issues,
for example, after uninstallation it would no longer be possible to
create new contexts as it leads to a MissingResourceException.
> Do not allow to dynamically unload Access Control

- src/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Change class SpiderThread to add a dummy Crawljax Plugin to suppress the
log warn that indicates that no plugins were loaded ("No plugins loaded.
There will be no output").
---
From https://github.com/jenkinsci/zaproxy-plugin/issues/19#issuecomment-211820358.
> spiderAjax: suppress innocuous log warning

- src/org/zaproxy/zap/extension/pscanrules/CacheControlScanner.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
Per the HTTP 1.1 spec it is possible for a response to have multiple
headers of the same type (i.e.: Cache-Control) [
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2 &
https://tools.ietf.org/html/rfc7230#section-3.2.2], an
alert is only raised if none of the headers on a response fulfill the
criteria being sought.
Fixes zaproxy/zaproxy#2405
> CacheControlScanner Accommodate Multiple Headers

- src/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
- src/org/zaproxy/zap/extension/quickstart/QuickStartPanel.java
- src/org/zaproxy/zap/extension/quickstart/ZapAddOn.xml
- src/org/zaproxy/zap/extension/quickstart/resources/Messages.properties
QuickStartPanel: Add new private methods (updateConfButton, and
updateConfField) to update text, tooltip, and enabled state of the
relevant PnH panel elements based on the enabled state of the API. Added
new public method (updatePnhPanelElements) which wraps the two private
methods to ensure sync when used by outside callers. Modified
getConfButton and getConfField methods to trigger the update methods
when instantiating the related elements.
ExtensionQuickStart: Add OptionsChangedListener hook, overridden
optionsChanged method triggers updatePnhPanelElements in
QuickStartPanel.
Fixes zaproxy/zaproxy#1271
> Disable Plug-n-Hack button if API turned off

- build/build.xml
- src/org/zaproxy/zap/extension/sse/ExtensionServerSentEvents.java
- src/org/zaproxy/zap/extension/sse/ZapAddOn.xml
With the changes done to core, zaproxy/zaproxy#2428, the database table
that was kept in the class EventStreamPanel is no longer up-to-date with
the latest opened database (since old listeners are removed when the
database is closed) leading to exceptions (like,
SQLNonTransientConnectionException: connection exception: closed).
Change class ExtensionServerSentEvents to update the database in
EventStreamPanel when the database is open, to always have the latest
database table (the one with active connection).
Fix add-on name in build.xml for its deploying target.
Bump version and remove old changes in ZapAddOn.xml file.
> sse: keep database up-to-date in EventStreamPanel

- src/org/zaproxy/zap/extension/fuzz/FuzzOptionsPanel.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
Fix the name of the resource message used to indicate that the "fuzzers"
directory is not writable, which was leading to an exception:
ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread
"AWT-EventQueue-0"
java.util.MissingResourceException: Can't find resource for bundle
java.util.PropertyResourceBundle, key fuzz.options.add.dirperms.error
at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
at java.util.ResourceBundle.getString(ResourceBundle.java:407)
at org.zaproxy.zap.extension.fuzz.FuzzOptionsPanel$3.actionPerformed
(FuzzOptionsPanel.java:330)
The name is "fuzz.options.add.file.dirperms.error" not the above.
Add change to ZapAddOn.xml file.
> websocket: correct name of error resource message

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/fuzz/ExtensionWebSocketFuzzer.java
- src/org/zaproxy/zap/extension/websocket/manualsend/ManualWebSocketSendEditorDialog.java
- src/org/zaproxy/zap/extension/websocket/manualsend/WebSocketSendPanel.java
- src/org/zaproxy/zap/extension/websocket/ui/WebSocketPanel.java
Change ExtensionWebSocket class to unload/remove database listener
(TableWebSocket), send/resend dialogues (WebSocketSendPanel) and filter
dialogue (through WebSocketPanel) and change to allow to remove
WebSocketObserver.
Change ExtensionWebSocketFuzzer to remove the fuzzer handler from the
ExtensionFuzz and to remove the added WebSocketObserver from
ExtensionWebSocket.
> websocket: unload components from core

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- src/org/zaproxy/zap/extension/websocket/ui/ExcludeFromWebSocketsMenuItem.java
With the changes done to core, zaproxy/zaproxy#2428, the database table
that was kept in the menu item is no longer up-to-date with the latest
opened database (since old listeners are removed when the database is
closed) leading to exceptions (like, SQLNonTransientConnectionException:
connection exception: closed).
Change class ExcludeFromWebSocketsMenuItem to not use the database table
(directly) to obtain the channels, instead use ExtensionWebSocket which
keeps track of the (latest) usable table.
Change class ExtensionWebSocket to allow to obtain the channels.
~~Bump version in ZapAddOn.xml file.~~
> websocket: remove menu's use of database table

- src/org/zaproxy/zap/extension/saverawmessage/PopupMenuSaveRawMessage.java
- src/org/zaproxy/zap/extension/saverawmessage/ZapAddOn.xml
- src/org/zaproxy/zap/extension/saverawmessage/resources/Messages.properties
Change class PopupMenuSaveRawMessage to use WritableFileChooser, which
already takes care to persist the last selected directory when choosing
the location to save the raw HTTP message.
Remove message no longer used for confirmation to overwrite existing
file, WritableFileChooser already does that.
Fix zaproxy/zaproxy#2446 - Remember current dir when using Save Raw
Results
> saverawmessage: remember last selected directory

- src/org/zaproxy/zap/extension/simpleExample/ExtensionSimpleExample.java
- src/org/zaproxy/zap/extension/simpleExample/RightClickMsgMenu.java
Following tidy up and minor tweaks done:
- Change plain code comments in the classes to JavaDoc and document (a
little more) what the classes do and what is its purpose;
- Remove unnecessary instance variable initialisations;
- Remove empty JavaDoc comments;
- Class ExtensionSimpleExample:
- Remove unused/unnecessary constructor (and related method
initialize());
- Rename "log" instance variable to "LOGGER" and add static and final
modifiers;
- Describe the methods canUnload() and unload();
- Use FontUtils to obtain a Font with the size defined by the user;
- Class RightClickMsgMenu:
- Tweak existing description of method isEnableForInvoker(...);
- Add method isSafe() and describe when it should be used.
> simpleExample: tidy up and minor tweaks

- src/org/zaproxy/zap/extension/sqliplugin/SQLInjectionPlugin.java
Change class SQLInjectionPlugin to log the exceptions RedirectException
(and URIException) as DEBUG instead of WARN, which are not of interest
for SQLi checks.
Based on results from zapbot's WAVSEP scans.
> sqliplugin: log redirect/URI exceptions as debug

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- src/org/zaproxy/zap/extension/websocket/WebSocketProxy.java
- src/org/zaproxy/zap/extension/websocket/WebSocketProxyV13.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
Change to use the hostname/port of the HTTP handshake message for the
name of the channel, instead of the address/port of the remote socket.
It would create the wrong name if ZAP was configured with an outgoing
proxy (that is, it would use the address/port of the proxy).
> websocket: use handshake message for channel name

- src/org/zaproxy/zap/extension/saml/SAMLConfiguration.java
- src/org/zaproxy/zap/extension/saml/ZapAddOn.xml
Change class SAMLConfiguration to use home directory for configuration
file, instead of using the "last selected directory" which might no
longer exist (nor be the same), leading to failure to restore the
configurations and an exception during initialisation:
ERROR org.zaproxy.zap.extension.saml.SAMLExtension  - SAML Extension
can't be loaded. Configuration not found or invalid
org.zaproxy.zap.extension.saml.SAMLException: SAML Configuration file
/tmp/zap_saml_conf.xml can't be modified
> saml: use (ZAP) home dir for configuration file

- src/org/zaproxy/zap/extension/websocket/WebSocketProxy.java
- src/org/zaproxy/zap/extension/websocket/WebSocketProxyV13.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/db/TableWebSocket.java
Change to log trivial actions (like establish a WebSocket channel,
receive/insert a message or sending a custom message) as DEBUG instead
of INFO, to not flood the logs.
For example, the log file would be flooded with messages like:
INFO TableWebSocket  - insert channel: example.com:80 (#1)
INFO WebSocketProxyV13  - got text frame payload
INFO TableWebSocket - insert message: #1.1
INFO WebSocketProxyV13  - got text frame payload
INFO TableWebSocket  - insert message: #1.2
INFO WebSocketProxyV13  - got text frame payload
INFO TableWebSocket  - insert message: #1.3
INFO WebSocketProxyV13  - got text frame payload
INFO TableWebSocket  - insert message: #1.4
INFO WebSocketProxy  - send custom message
INFO TableWebSocket  - insert message: #1.5
(Thread name and package were stripped from the …
> websocket: adjust log levels, from info to debug

- src/org/zaproxy/zap/extension/websocket/WebSocketProxy.java
Change class WebSocketProxy to use the URI cached in HistoryReference
instead of reading the whole HTTP message from the database, when
processing a forwarded WebSocket message.
> websocket: reduce database accesses

- src/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Change class ExtensionScriptsUI to check if there's any script selected
(that is, non-null) before checking if the script should be re-displayed
when a script engine is added, or its script type shown when an engine
is removed.
There's no script selected, for example, when the selected script is
removed, which was then causing NullPointerExceptions if an engine
script (for example, Zest add-on) was immediately added/removed after
that.
> scripts: fix NPEs on engine added/removed

- build/build.xml
Add the compile argument "-Xlint:-options" to javac tasks of "compile"
target to suppress the following warning:
[javac] warning: [options] bootstrap class path not set in conjunction
with -source 1.7
to allow to compile the add-ons with Java 8 (warnings are considered as
errors).
---
From OWASP ZAP Developer Group: https://groups.google.com/d/topic/zaproxy-develop/2kFdlLmXzpA/discussion
> Suppress "options" compile warning

- src/org/zaproxy/zap/extension/ApiGenerator.java
Change ApiGenerator class to deploy the generated Java and Python code
to new repositories, zap-api-java and zap-api-python, respectively.
> Update (release) ApiGenerator to use new API repos

- src/org/zaproxy/zap/extension/ApiGenerator.java
Change ApiGenerator class to deploy the generated Java and Python code
to new repositories, zap-api-java and zap-api-python, respectively.
> Update (beta) ApiGenerator to use new API repos

- src/org/zaproxy/zap/extension/ApiGenerator.java
Change ApiGenerator class to deploy the generated Java and Python code
to new repositories, zap-api-java and zap-api-python, respectively.
> Update (alpha) ApiGenerator to use new API repos

- build/build.xml
Change the target build-all in build.xml file to override the ID of the
HttpsInfo add-on, to also keep the same ID as the old versions when all
add-ons are built.
> Override HttpsInfo add-on ID in build-all target

- src/org/zaproxy/zap/extension/ascanrules/TestPathTraversal.java
- src/org/zaproxy/zap/extension/ascanrules/TestRemoteFileInclude.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
Per https://twitter.com/psiinon/status/741229375140581376 &
zapbot/zap-mgmt-scripts@205f4cc
TestPathTraversal - catch InvalidRedirectLocationException and
URIException.
TestRemoteFileInclude - adjust logging (debug not error).
> Address AScan Release Errors/Exceptions

- src/org/zaproxy/zap/extension/coreLang/ExtensionCoreLanguages.java
- src/org/zaproxy/zap/extension/coreLang/ZapAddOn.xml
Change class ExtensionCoreLanguages to use the file path defined in the
manifest (ZapAddOn.xml) instead of hard coding it, to make sure the file
path/name is always kept in sync and prevent installation issues because
of missing (non existing) file.
> coreLang: fix installation issue

- src/org/zaproxy/zap/extension/fuzz/FuzzOptions.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/impl/FuzzerOptionsPanel.java
Enable the option Limit maximum errors by default and increase the
default number of errors allowed before stopping the scan.
Related to zaproxy/zaproxy#2568 - Fuzzer consuming all memory on error
> fuzz: enable Limit maximum errors by default

- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/HttpFuzzer.java
Change HttpFuzzer class to use the correct resource message key to show
the information message that indicates the fuzzer process stopped
because the maximum number of errors has been reached.
> fuzz: correct info message shown

- src/org/zaproxy/zap/extension/pscanrulesBeta/CSRFCountermeasures.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
Attack and Evidence fields in alerts generated by CSRFCountermeasures
were unnecessary, and didn't add any value. 
Fixes zaproxy/zaproxy#2576
> CSRFCountermeasures Remove Attack & Evidence Msg

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestSequenceRunner.java
Change class ZestSequenceRunner to not reuse existing Sites tree nodes
when creating the sites structure to be active scanned, reusing the tree
nodes changes the internal structure of the Sites tree (when adding to
the custom sites tree the nodes are removed from the original tree).
> zest: do not reuse Sites' nodes in sequence script

- src/org/zaproxy/zap/extension/pscanrulesAlpha/XPoweredByHeaderInfoLeakScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
The highlight of X-Powered-By header alert in the response tab is incorrectly chosen because of the evidence text. Hence I've modified the evidence text so that correct header is highlighted. Though subjective, but I believe it is better to display both the header name and header value in evidence text.
> XPoweredByHeaderInfoLeakScanner modify evidence

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/manualsend/WebSocketPanelSender.java
- src/org/zaproxy/zap/extension/websocket/ui/WebSocketMessagesPopupMenuItem.java
Change classes WebSocketMessagesPopupMenuItem and WebSocketPanelSender
to not use an exception from JAX-WS API (WebServiceException), for the
former class remove the declared exception (it's not needed, pop up menu
items should handle the exceptions appropriately), for the latter class
change to declare that it throws IOException and to throw
IllegalArgumentException when the WebSocket message or WebSocketProxy
are not correct (for example, if there's no connection with the given
ID).
The change allows to run the WebSockets add-on with Java 9 (EA), which
was leading to an exception:
java.lang.NoClassDefFoundError: javax/xml/ws/WebServiceException
Bump version and remove old changes in ZapAddOn.xml file.
> websocket: remove use of JAX-WS API exception

- src/org/zaproxy/zap/extension/sqliplugin/SQLInjectionPlugin.java
- src/org/zaproxy/zap/extension/sqliplugin/ZapAddOn.xml
Change SQLInjectionPlugin scanner to check all DB technologies available
when evaluating if the scanner should be run or not, allowing to run it
even if it's only selected a specific DB technology (not just when it's
selected the top DB technology).
---
From OWASP ZAP User Group: https://groups.google.com/d/topic/zaproxy-users/5vlQfn5I26g/discussion
> sqliplugin: check all DB technologies available

- src/org/zaproxy/zap/extension/plugnhack/ZapAddOn.xml
- src/org/zaproxy/zap/extension/plugnhack/brk/ClientBreakDialog.java
- src/org/zaproxy/zap/extension/plugnhack/brk/ClientBreakDialogAdd.java
- src/org/zaproxy/zap/extension/plugnhack/brk/ClientBreakDialogEdit.java
- src/org/zaproxy/zap/extension/plugnhack/brk/ClientBreakpointsUiManagerInterface.java
- src/org/zaproxy/zap/extension/plugnhack/brk/PopupMenuAddBreakClient.java
- src/org/zaproxy/zap/extension/plugnhack/brk/PopupMenuEditBreak.java
Change the (Client) breakpoint dialogues to be modal, to prevent
interactions with other UI components (and core code) while the
dialogues are shown.
Reduces code complexity in core and add-ons, it's also less error prone,
since it no longer requires the break implementations and core code to
track/tell which type of dialogues (add/edit/remove) are currently
shown.
> plugnhack: change break dialogues to be modal

- src/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanner.java
- src/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScanner.java
- src/org/zaproxy/zap/extension/pscanrules/SetCookieUtils.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- test/org/zaproxy/zap/extension/pscanrules/SetCookieUtilsUnitTest.java
Change scanners CookieSecureFlagScanner and CookieHttpOnlyScanner to
correctly check the attributes of the cookies being set. The previous
behaviour just checked that the name of the attribute existed in the
whole header value, not if it existed an attribute with the expected
name leading to false negatives if the attribute names were contained
in other attribute values or cookie name/value. 
Add helper class, SetCookieUtils, to check if an attribute is present in
the value of a Set-Cookie header.
Change the previously mentioned scanners to use that class.
Add tests to assert the expected behaviour of class SetCookieUtils.
> pscanrules: correctly check cookie attributes

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/brk/PopupMenuAddBreakWebSocket.java
- src/org/zaproxy/zap/extension/websocket/brk/PopupMenuEditBreak.java
- src/org/zaproxy/zap/extension/websocket/brk/WebSocketBreakDialog.java
- src/org/zaproxy/zap/extension/websocket/brk/WebSocketBreakDialogAdd.java
- src/org/zaproxy/zap/extension/websocket/brk/WebSocketBreakDialogEdit.java
- src/org/zaproxy/zap/extension/websocket/brk/WebSocketBreakpointsUiManagerInterface.java
Change the breakpoint dialogues to be modal, to prevent interactions
with other UI components (and core code) while the dialogues are shown.
Reduces code complexity in core and add-ons, it's also less error prone,
since it no longer requires the break implementations and core code to
track/tell which type of dialogues (add/edit/remove) are currently
shown.
> websocket: change break dialogues to be modal

- src/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanner.java
- src/org/zaproxy/zap/extension/pscanrules/MixedContentScanner.java
- src/org/zaproxy/zap/extension/pscanrules/TestInfoPrivateAddressDisclosure.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
Change scanners "Private IP Disclosure" and "Secure Pages Include Mixed
Content" to not fill/set the attack field of the alert, there's no
attack being done, and remove the parameter ("N/A") from the alert
raised by the scanner "Application Error Disclosure".
Bump version and updates changes in ZapAddOn.xml file.
> pscanrules: empty attack and n/a parameter fields

- src/org/zaproxy/zap/extension/zest/ZestSequenceRunner.java
Change to use the new value defined in core for temporary sequence
messages instead of 11, which is/was reserved for messages sent by other
Zest scripts.
Related to zaproxy/zaproxy#2585 - Remove temp Sequence requests on
session clean up
> zest: use new history type in sequence messages

- src/org/zaproxy/zap/extension/zest/ZestZapRunner.java
Change to use the "new" value defined in core for Zest messages, the old
value (11) was (and is) being used by authentication messages (even if
it was originally reserved for Zest messages).
Related to zaproxy/zaproxy#2603 - Add new history type for Zest HTTP
messages
> zest: use new history type in Zest scripts

- src/org/zaproxy/zap/extension/ascanrules/TestSQLInjection.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
Change TestSQLInjection scanner to run if any DB technology is enabled
but skip specific non-applicable error checks (that is, do not check for
errors messages of non selected DBs).
More detailed changes:
- Convert the maps that hold the error messages of the DBs to an Enum
as it allows to include more information, the name of the database, the
Tech it is/has and the types of error messages (specific and union);
- Method targets(TechSet), change to check if any of the selected techs
belongs to DB hierarchy to run or not the scanner;
- In the scan method:
- Change to only check generic error messages if the selected techs
include (the top level tech) DB;
- Change to use the defined Enum when checking for errors (specific,
generic and union);
- Extract methods to check the specific and …
> ascanrules: run SQLi scanner for any DB tech

- build/build.xml
- src/org/openqa/selenium/phantomjs/PhantomJSDriverService.java
- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
Update class PhantomJSDriverService to a newer version, which allows to
(properly) override the location of the PhantomJS (driver) log file. The
location was not being overridden properly, leading to issues if there
was no write permissions in the default directory.
The (latest) version of the class was obtained from:
detro/ghostdriver@b233b2daa3c65af38f9f4667aff7d2f273e34c01
(The class is being updated "manually" since the version included in the
Selenium dependencies is older and does not have the issue fixed.)
Change ExtensionSelenium to remove unnecessary/innocuous slash in the
PhantomJS log file path.
Update build.xml file to include the (updated) class in the add-on.
Fix zaproxy/zaproxy#2636 - AjaxSpider with PhantomJS fails to …
> selenium: properly override PhantomJS log file

- src/org/zaproxy/zap/extension/pscanrules/XFrameOptionScanner.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
The XFO passive scanner now checks for: multiple headers, and attempts
to define XFO via META tag. Help was also updated, as were alert text
for consistency and accuracy.
Fixes zaproxy/zaproxy#2539
> New XFO Variants

- src/org/zaproxy/zap/extension/pscanrulesBeta/CookieLooselyScopedScanner.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
CookieLooselyScopedScanner contains a text in attack field which should be in description field instead. This commit updates the text.
> CookieLooselyScopedScanner remove attack field and update description

- src/org/zaproxy/zap/extension/saml/ZapAddOn.xml
- src/org/zaproxy/zap/extension/saml/ui/SamlManualEditor.java
Change class SamlManualEditor to use HttpResponseBody.toString() to get
the string representation of the response body instead of using the
method createCachedString(String), the latter method was removed in a
newer version of ZAP (2.5.0), as it's not intended to be called
directly.
> saml: use toString() to obtain the response body

- src/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
- src/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
- src/org/zaproxy/zap/extension/wappalyzer/ZapAddOn.xml
Change WappalyzerPassiveScanner to implement PassiveScanner instead of
extending PluginPassiveScanner, the latter is used for passive scanners
that raise alerts (also shown and configured in Passive Scan Rules
options panel).
The passive scanner used by the wappalyzer add-on does not require/have
any configurations, it's always enabled and changes to alert threshold
have no effect.
Change ExtensionWappalyzer to depend on ExtensionPassiveScan and to add
and remove the passive scanner when initialised and unloaded,
respectively.
> wappalyzer: use plain passive scanner

- src/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/payloads/processor/SHA512HashProcessor.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/SHA512HashProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
- src/org/zaproxy/zap/extension/fuzz/resources/help/contents/processors.html
Add a new payload processor to create SHA-512 hashes.
Update help processors page and changes in ZapAddOn.xml file.
Fix zaproxy/zaproxy#2643 - SHA-512 Payload Processor
> fuzz: add SHA-512 payload processor

- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderDialog.java
- src/org/zaproxy/zap/extension/spiderAjax/PopupMenuAjaxSite.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Move the warning about the PhantomJS issue (that prevents localhost
traffic from being proxied through ZAP) to AJAX Spider dialogue to show
it, always. Previously, it would not be shown if the browser selected in
the options were not PhantomJS.
> spiderAjax: show, always, the PhantomJS warning

- src/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
- src/org/zaproxy/zap/extension/spiderAjax/resources/Messages.properties
Add a menu item to Tools menu that allows to shows the AJAX Spider
dialogue (and with a keyboard shortcut).
> spiderAjax: add a spider menu item to Tools menu

- src/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java
- src/org/zaproxy/zap/extension/fuzz/FuzzOptionsPanel.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
Change ExtensionFuzz to not attempt to enumerate the fuzzers directory
if the directory does not exist. Also, change FuzzOptionsPanel to create
the directory if it does not exist when importing/adding a fuzzer file.
Fix zaproxy/zaproxy#2387 - Fuzzer Extension exception when removing PnH
Extension
> fuzz: skip fuzzers dir enumeration if not present

- src/org/zaproxy/zap/extension/fuzz/FuzzerPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
Change class FuzzerPayloadGeneratorUIPanel to allow to search the names
of the fuzzer files when selecting them, the change adds a find bar to
the top of the tree that shows the available files. The find bar/panel
contains a text field, for the search term, and two buttons, to navigate
the matching tree nodes (next/previous).
Fix zaproxy/zaproxy#2227 - Fuzzer: option to search for payload names
> fuzz: allow to search fuzzer file names

- src/org/zaproxy/zap/extension/ascanrules/TestSQLInjection.java
Change TestSQLInjection scanner to use all technologies if none was
previously set (i.e. null), fixing NullPointerException when evaluating
if the DB technologies are or not included.
Issue introduced in #439 - ascanrules: run SQLi scanner for any DB tech
---
From @zapbot weekly scans.
> ascanrules: fix tech related NPE in SQLi scanner

- src/org/zaproxy/zap/extension/ascanrules/TestPathTraversal.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
Catch SocketTimeoutException, enhance logging by including details of
the configured timeout. Add isDebugEnabled check to also include
exceptions specifics. Also include specific method/URL/Param details if
logging IOException. Finally update ZapAddOn.xml, to reflect the change.
Fixes zaproxy/zaproxy#2624
> TestPathTraversal Logging Tweaks

- src/org/zaproxy/zap/extension/zest/ExtensionZest.java
- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
Change class ExtensionZest to assert the response body length using as
initial value the length of the body after converting it to a string
(instead of the using the number of bytes), ensuring that both values
(the initial value and the one used to verify the assertion) are in the
same format.
Fix zaproxy/zaproxy#2669 - Zest does not calculate page length correctly
in assertion
> zest: correct assertion of response body length

- src/org/zaproxy/zap/extension/scripts/CommandPanel.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Change class CommandPanel to discard the undoable edits of the text area
when no longer needed, that is, when the text area is cleared and when a
new script is set, preventing the edits from accumulating and exhausting
the whole memory (it also prevents undoing the changes to previous
scripts or templates).
Fix zaproxy/zaproxy#2675 - Memory exhaustion with Script Console and big
scripts
> scripts: discard undoable edits no longer needed

- src/org/zaproxy/zap/extension/pscanrulesAlpha/CookieSameSiteScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/SetCookieUtils.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
- test/org/zaproxy/zap/extension/pscanrulesAlpha/CookieSameSiteScannerUnitTest.java
Fixes zaproxy/zaproxy#2716 Implement a passive check for cookies without SameSite set
> Implement a passive check for cookies without SameSite set

- src/org/zaproxy/zap/extension/invoke/DialogAddApp.java
- src/org/zaproxy/zap/extension/invoke/ZapAddOn.xml
Change class DialogAddApp to have the text boxes for the application
path and working directory editable, so the user can manually specify
its values.
Fix zaproxy/zaproxy#2708 - Allow to manually specify application path
and working directory
> invoke: allow to manually set app and dir paths

- src/org/zaproxy/zap/extension/zest/resources/help/contents/zest.html
Change Zest help page to have external URLs as links, so they can be
accessed without having to manually copy them to a browser.
> zest: change external URLs to links in help page

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestAuthenticationRunner.java
Change class ZestAuthenticationRunner to return as mandatory parameters
the script parameters that are not credentials parameters (that is, not
username or password) and do not have a value instead of returning
always the same parameters. Also, return as optional parameters the ones
that already have a value.
Fix zaproxy/zaproxy#2734 - Zest authentication script requires fields
even if not needed/used
> zest: check the auth script for parameters

- src/org/zaproxy/zap/extension/ascanrulesAlpha/ApacheRangeHeaderDos.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
Add scanner for Apache Range Header DoS (CVE-2011-3192). Includes help
updates, and ZapAddOn.xml updates.
> New Apache Range Header DoS Scanner

- src/org/zaproxy/zap/extension/wappalyzer/resources/Messages.properties
Minor adjustments to the addon's messages.properties file for title
caps.
See zaproxy/zaproxy#2000
> Wappalyzer Titlecap Fixes

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/fuzz/ExtensionWebSocketFuzzer.java
Change class ExtensionWebSocketFuzzer to check that the view is
initialised before removing the script type from the ExtensionScript
preventing the NullPointerException (the script type is only created if
there's a view/GUI).
---
From @zapbot "release" scans.
> websocket: fix NPE during unload in daemon mode

- src/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/ExtensionHttpFuzzer.java
Change classes ExtensionFuzz and ExtensionHttpFuzzer to check that the
view is initialised before removing the script types from the
ExtensionScript preventing the NullPointerException (the script types
are only created if there's a view/GUI).
---
From @zapbot "release" scans.
> fuzz: fix NPE during unload in daemon mode

- src/org/zaproxy/zap/extension/pscanrules/CacheControlScanner.java
- src/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanner.java
- src/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScanner.java
- src/org/zaproxy/zap/extension/pscanrules/CrossDomainScriptInclusionScanner.java
- src/org/zaproxy/zap/extension/pscanrules/HeaderXssProtectionScanner.java
- src/org/zaproxy/zap/extension/pscanrules/SetCookieUtils.java
- src/org/zaproxy/zap/extension/pscanrules/XContentTypeOptionsScanner.java
- src/org/zaproxy/zap/extension/pscanrules/XFrameOptionScanner.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
- test/org/zaproxy/zap/extension/pscanrules/CacheControlScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrules/CrossDomainScriptInclusionScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrules/HeaderXssProtectionScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrules/PassiveScannerTest.java
- test/org/zaproxy/zap/extension/pscanrules/XContentTypeOptionScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrules/XFrameOptionsScannerUnitTest.java
As per https://groups.google.com/d/msg/zaproxy-develop/6IAnEHANWpI/zva5350aBgAJ
> Pscan rule tweaks

- src/org/zaproxy/zap/extension/alertFilters/AlertFilter.java
- src/org/zaproxy/zap/extension/alertFilters/AlertFilterAPI.java
- src/org/zaproxy/zap/extension/alertFilters/AlertFilterTableModel.java
- src/org/zaproxy/zap/extension/alertFilters/ContextAlertFilterManager.java
- src/org/zaproxy/zap/extension/alertFilters/DialogAddAlertFilter.java
- src/org/zaproxy/zap/extension/alertFilters/DialogModifyAlertFilter.java
- src/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java
- src/org/zaproxy/zap/extension/alertFilters/ZapAddOn.xml
- DialogAddAlertFilter - clearFields(), now resets all relevant field,
addressing an issue reported in IRC. Removed some unused commented code.
- AlertFilter - Various JavaDoc fixes (remove references to "user")
- AlertFilterAPI - Various JavaDoc fixes (remove references to "user"),
remove unused import.
- AlertFilterTableModel - Various JavaDoc fixes (remove references to
"user").
- ExtensionAlertFilters - Various JavaDoc fixes (remove references to
"user").
- ContextAlertFilterManager - Minor JavaDoc updates.
- DialogModifyAlertFilter - Remove placeholder JavaDoc constructs.
- ZapAddOn.xml - Updated to v4 and new change comment added.
> Alert Filters Minor Cleanup and Fix

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/RequestContentLengthUpdaterProcessor.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/RequestContentLengthUpdaterProcessorUIHandler.java
- test/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/RequestContentLengthUpdaterProcessorUnitTest.java
Change class RequestContentLengthUpdaterProcessorUIHandler to use the
RequestContentLengthUpdaterProcessor that updates the Content-Length
request header for all request methods (instead of just POST method).
Change class RequestContentLengthUpdaterProcessor to only add the
Content-Length request header if really needed (that is, there's a
non-empty request body).
Add tests to assert the expected behaviour of class
RequestContentLengthUpdaterProcessor.
Fix zaproxy/zaproxy#2766 - fuzz module request alignment
> fuzz: update Content-Length for all methods

- src/org/zaproxy/zap/extension/importurls/ExtensionImportUrls.java
- src/org/zaproxy/zap/extension/importurls/ImportUrlsAPI.java
- src/org/zaproxy/zap/extension/importurls/ZapAddOn.xml
- src/org/zaproxy/zap/extension/importurls/resources/help/contents/importUrls.html
Add ImportUrlsAPI which accepts a simple parameter filePath. Expecting a
ZAP URL export or plain text file containing a single URL per line.
Adjust ExtensionImportUrls:
- hook, now includes registration of the API implementor.
- importUrlFile, modified slightly. It had been assuming that the method
on every line of ZAP URL exports was GET. Now instead of assuming ZAP
formatted exports start with GET it checks if the line starts with http.
If not it assumes everything up to the first tab is the method.
Note: The import function still assumes that all URLs are accessible via 
GET. This should largely be true, and it is doubtful that we would find
much benefit in trying the original (exported) method, because for
example on a POST we wouldn't have the necessary parameters (same for a
PUT, or …
> Add URL Import API

- .gitignore
- src/org/zaproxy/zap/extension/pscanrulesAlpha/XPoweredByHeaderInfoLeakScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
- test/org/zaproxy/zap/extension/pscanrulesAlpha/CookieSameSiteScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/PassiveScannerTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/XPoweredByHeaderInfoLeakScannerUnitTest.java
The refactoring consists of
1. extending the PassiveScannerTest class to avoid the duplications
2. Raising only one alert if XPoweredByHeaderInfoLeakScanner finds
multiple x-powered-by headers
3. In case of 2, it populates the <Evidence field> with the first header
found and the <Other field> with the rest of found values; It worthwhile
to mention that
4. Updating gitignore on alpha branch, to ignore IntelliJ specific files
> Refactoring/unit testing for x-powered-by scanner, cookie-same-site scanner, and gitignore in alpha branch

- src/org/zaproxy/zap/extension/wappalyzer/Application.java
- src/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
- src/org/zaproxy/zap/extension/wappalyzer/PopupMenuEvidence.java
- src/org/zaproxy/zap/extension/wappalyzer/PopupMenuEvidenceSearch.java
- src/org/zaproxy/zap/extension/wappalyzer/TechPanel.java
- src/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
- src/org/zaproxy/zap/extension/wappalyzer/ZapAddOn.xml
- Remove unnecessary code comments.
- Remove some extra lines.
- Remove some default/boilerplate JavaDoc content.
- Remove one un-necessary Warning Suppression.
- WappalyzerPassiveScanner address TODO in overridden method
appliesToHistoryType accept core handling for getDefautlHistoryTypes.
- ZapAddOn.xml update changes section.
> Wappalyzer Minor Code Cleanup

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/messagelocations/TextWebSocketMessageLocation.java
Change TextWebSocketMessageLocation to check if the new text location
is (or not) an insertion point, when the existing text location has the
same start and different end. If it's not an insertion point it's
overlapping the existing location.
Related to zaproxy/zaproxy#2792 - Able to overlap fuzz (HTTP) locations
> websocket: fix overlapping of text location

- src/org/zaproxy/zap/extension/pscanrulesBeta/CSRFCountermeasures.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
Change the plugin ID of passive scanner Absence of Anti-CSRF Tokens from
40014 to 10202, as the former ID was already in use by other scanner.
Related to zaproxy/zaproxy#2823.
> pscanrulesBeta: correct ID of anti-CSRF scanner

- src/org/zaproxy/zap/extension/gettingStarted/ExtensionGettingStarted.java
- src/org/zaproxy/zap/extension/gettingStarted/ZapAddOn.xml
- src/org/zaproxy/zap/extension/onlineMenu/ExtensionOnlineMenu.java
- src/org/zaproxy/zap/extension/onlineMenu/ZapAddOn.xml
- src/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
- src/org/zaproxy/zap/extension/quickstart/ZapAddOn.xml
- src/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- src/org/zaproxy/zap/extension/websocket/fuzz/ExtensionWebSocketFuzzer.java
Remove unnecessary extensions' constructors, they are not required nor
used by core code to start/load the extensions (it's enough with the
no-arg constructor moreover add-ons do not need nor should start other
extensions). Also, in the cases where an auxiliary "initialize" method
was in use it was merged into the no-arg constructor (in most of the
cases it was only being called by the no-arg constructor).
Bump version and update changes in ZapAddOn.xml files, where needed.
> Remove unnecessary extensions' constructors

- src/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java
- src/org/zaproxy/zap/extension/beanshell/ExtensionBeanShell.java
- src/org/zaproxy/zap/extension/beanshell/ZapAddOn.xml
- src/org/zaproxy/zap/extension/bruteforce/ExtensionBruteForce.java
- src/org/zaproxy/zap/extension/bruteforce/ZapAddOn.xml
- src/org/zaproxy/zap/extension/diff/ExtensionDiff.java
- src/org/zaproxy/zap/extension/diff/ZapAddOn.xml
- src/org/zaproxy/zap/extension/importurls/ExtensionImportUrls.java
- src/org/zaproxy/zap/extension/invoke/ExtensionInvoke.java
- src/org/zaproxy/zap/extension/invoke/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jruby/ExtensionJruby.java
- src/org/zaproxy/zap/extension/jruby/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jython/ExtensionJython.java
- src/org/zaproxy/zap/extension/jython/ZapAddOn.xml
- src/org/zaproxy/zap/extension/plugnhack/ExtensionPlugNHack.java
- src/org/zaproxy/zap/extension/portscan/ExtensionPortScan.java
- src/org/zaproxy/zap/extension/portscan/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
- src/org/zaproxy/zap/extension/tips/ExtensionTipsAndTricks.java
- src/org/zaproxy/zap/extension/tips/ZapAddOn.xml
- src/org/zaproxy/zap/extension/tokengen/ExtensionTokenGen.java
- src/org/zaproxy/zap/extension/tokengen/ZapAddOn.xml
- src/org/zaproxy/zap/extension/treetools/ExtensionTreeTools.java
- src/org/zaproxy/zap/extension/treetools/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ExtensionZest.java
- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
Remove unnecessary extensions' constructors, they are not required nor
used by core code to start/load the extensions (it's enough with the
no-arg constructor moreover add-ons do not need nor should start other
extensions). Also, in the cases where an auxiliary "initialize" method
was in use it was merged into the no-arg constructor (in most of the
cases it was only being called by the no-arg constructor).
Bump version and update changes in ZapAddOn.xml files, where needed.
> beta: remove unnecessary extensions' constructors

- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderAPI.java
- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderDialog.java
- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderTarget.java
- src/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- src/org/zaproxy/zap/extension/spiderAjax/HttpPrefixUriValidator.java
- src/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
- src/org/zaproxy/zap/extension/spiderAjax/resources/Messages.properties
- src/org/zaproxy/zap/extension/spiderAjax/resources/help/contents/scandialog.html
Change the AJAX Spider to allow to spider just a site's subtree, through
the API and GUI.
Update help page of spider dialogue and API endpoints' descriptions.
Fix zaproxy/zaproxy#2847 - AJAX Spider Configuration should be more
similar to standard Spider
> spiderAjax: allow to spider just a site's subtree

- .gitignore
- build/build.xml
Compile test code to other directory ("buildtest") than the one used for
add-ons' classes ("build").
Delete the "buildtest" directory when running "clean" target.
Ignore the "build" directories, not intended to be versioned.
Include add-ons' resource files when running tests (in case tests need
them to run).
> build: do not include test classes in add-ons

- .gitignore
- build/build.xml
Compile test code to other directory ("buildtest") than the one used for
add-ons' classes ("build").
Delete the "buildtest" directory when running "clean" target.
Ignore the "build" directories, not intended to be versioned.
Include add-ons' resource files when running tests (in case tests need
them to run).
> build: do not include tests in add-ons (beta)

- .gitignore
- build/build.xml
Compile test code to other directory ("buildtest") than the one used for
add-ons' classes ("build").
Delete the "buildtest" directory when running "clean" target.
Ignore the "build" directories, not intended to be versioned.
Include add-ons' resource files when running tests (in case tests need
them to run).
> build: do not include tests in add-ons (alpha)

- src/org/zaproxy/zap/extension/treetools/ExtensionTreeTools.java
- src/org/zaproxy/zap/extension/treetools/PopupMenuTreeTools.java
Changes:
- ExtensionTreeTools, remove outdated comments, empty JavaDoc comment
and (unnecessary) null initialisation;
- PopupMenuTreeTools:
- Remove unused constructor;
- Use JTree for sites tree instead of component and rename the
instance variable accordingly.
> treetools: minor tidy up

- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Fix a typo in the changes of ZapAddOn.xml file ("Issue" not "Isssue").
> scripts: fix typo in ZapAddOn.xml file

- src/org/zaproxy/zap/extension/ascanrulesBeta/CrossDomainScanner.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
Change CrossDomainScanner to skip empty cross domain policy files (that
is, responses with no content), there's no point attempting to parse and
process them, moreover it prevents outputs like:
[Fatal Error] :1:1: Premature end of file.
caused by the empty responses.
Remove wildcard import and reorder related imports.
---
Reported in the IRC channel.
> ascanrulesBeta: skip empty cross domain files

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestZapRunner.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestRequestDialog.java
Change ZestRequestDialog to show the URL with tokens if defined, if not,
show "plain" URL (if defined, otherwise fallback to empty URL). Also,
reset the "plain" URL when setting the URL with tokens and reset the URL
with tokens when setting the "plain" URL, which ensures that it's shown
and used the correct URL.
Change ZestZapRunner to throw an exception if the request-uri is not set
(e.g. the URL is not well-formed).
Update changes in ZapAddOn.xml file (remove existing code change
mention, it's no longer needed or of interest).
Fix zaproxy/zaproxy#2854 - Cannot use variable in Zest Script as part of
POST URL
> zest: show always the expected request URL

- src/org/zaproxy/zap/extension/ascanrules/FormatString.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
Change FormatString scanner to use correct HTTP message and attack when
building the alerts. The attack field was using a value that was not the
injected one and the message was one not sent (thus not containing a
response).
> ascanrules: correct FormatString's alert data

- test/org/zaproxy/zap/extension/pscanrules/PassiveScannerTest.java
- test/org/zaproxy/zap/extension/pscanrules/XFrameOptionsScannerUnitTest.java
Change XFrameOptionsScannerUnitTest to assert that the alerts have the
expected name, since it raises different alerts depending on the issue.
Change PassiveScannerTest to load the resource bundle of the scanners
(necessary to assert the names) and add convenience method/Matcher to
assert the expected name.
> pscanrules: assert alert's data in XFO tests

- test/org/zaproxy/zap/extension/ScannerTestUtils.java
- test/org/zaproxy/zap/extension/ascanrules/ActiveScannerTest.java
- test/org/zaproxy/zap/extension/pscanrules/PassiveScannerTest.java
Add/extract helper class that mocks the Constant.messages with the
resource messages of the scanners.
Change base scanner test classes to use the new class (passive scanners
were already using the mocked messages).
The change allows to assert that the scanners are really using existing
messages (which if missing would lead to MissingResourceException, at
runtime).
> Load active scanners' messages when testing

- src/org/zaproxy/zap/extension/birtreports/BirtScriptMenu.java
- src/org/zaproxy/zap/extension/birtreports/BirtTopMenu.java
- src/org/zaproxy/zap/extension/birtreports/logoTopMenu.java
- src/org/zaproxy/zap/extension/cmss/CMSSTopMenu.java
- src/org/zaproxy/zap/extension/cmss/ZapAddOn.xml
- src/org/zaproxy/zap/extension/codedx/CodeDxExtension.java
- src/org/zaproxy/zap/extension/codedx/ZapAddOn.xml
- src/org/zaproxy/zap/extension/customreport/ExtensionCustomReport.java
- src/org/zaproxy/zap/extension/customreport/ZapAddOn.xml
- src/org/zaproxy/zap/extension/importLogFiles/ExtensionImportLogFiles.java
- src/org/zaproxy/zap/extension/importLogFiles/ZapAddOn.xml
- src/org/zaproxy/zap/extension/requester/ExtensionRequester.java
- src/org/zaproxy/zap/extension/requester/ZapAddOn.xml
- src/org/zaproxy/zap/extension/revisit/ExtensionRevisit.java
- src/org/zaproxy/zap/extension/revisit/ZapAddOn.xml
- src/org/zaproxy/zap/extension/sniTerminator/ExtensionSniTerminator.java
- src/org/zaproxy/zap/extension/sniTerminator/ZapAddOn.xml
- src/org/zaproxy/zap/extension/soap/ExtensionImportWSDL.java
- src/org/zaproxy/zap/extension/soap/ZapAddOn.xml
- src/org/zaproxy/zap/extension/vulncheck/VulnCheckTopMenu.java
- src/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
- src/org/zaproxy/zap/extension/wavsepRpt/ExtensionWavsepReport.java
Remove unnecessary extensions' constructors, they are not required nor
used by core code to start/load the extensions (it's enough with the
no-arg constructor moreover add-ons do not need nor should start other
extensions). Also, in the cases where an auxiliary "initialize" method
was in use it was merged into the no-arg constructor (in most of the
cases it was only being called by the no-arg constructor).
Bump version and update changes in ZapAddOn.xml files, where needed.
> alpha: remove unnecessary extensions' constructors

- test/org/zaproxy/zap/extension/ScannerTestUtils.java
- test/org/zaproxy/zap/extension/pscanrulesBeta/PassiveScannerTest.java
Add helper class that mocks the Constant.messages with the resource
messages of the scanners.
Change base passive scanner test class to use the new class.
The change allows to assert that the scanners are really using existing
messages (which if missing would lead to MissingResourceException, at
runtime).
> Load passive scanners' messages when testing, beta

- test/org/zaproxy/zap/extension/ScannerTestUtils.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/PassiveScannerTest.java
Add helper class that mocks the Constant.messages with the resource
messages of the scanners.
Change base passive scanner test class to use the new class.
The change allows to assert that the scanners are really using existing
messages (which if missing would lead to MissingResourceException, at
runtime).
> Load alpha passive scanners' messages when testing

- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
Fixes zaproxy/zaproxy#2860 by adding the suggested relevant links.
Update ZapAddOn.xml with changes entry.
> Updated Loosely Scoped Cookie References

- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/resources/Messages.properties
Remove resource messages that were being used by (just) core code (in
versions prior release of ZAP 2.5.0).
Bump version, updated changes and change minimum ZAP version (to 2.5.0)
in ZapAddOn.xml file.
Fix zaproxy/zaproxy#2386 - Remove unused "Script Console" resource
messages
> scripts: remove unused resource messages

- src/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
- src/org/zaproxy/zap/extension/wappalyzer/PopupMenuEvidence.java
- src/org/zaproxy/zap/extension/wappalyzer/PopupMenuEvidenceSearch.java
Remove unused pop up menu constructors and change existing ones to
require the expected dependencies, also, merge "initialize" method into
the constructor.
> wappalyzer: remove unused pop up menu constructors

- src/org/zaproxy/zap/extension/ascanrulesBeta/RemoteCodeExecutionCVE20121823.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- test/org/zaproxy/zap/extension/ascanrulesBeta/NanoServerHandler.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/RemoteCodeExecutionCVE20121823UnitTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureCVE20121823UnitTest.java
Change scanner RemoteCodeExecutionCVE20121823 to create the attack URL
using the original URL components (authority and path) escaped, as
that's the expected form, otherwise it would lead to an exception:
"escaped absolute path not valid"
if there were characters that required escaping.
Change the scanner to not attempt the second attack if the first was
successful and to update the Content-Length of the request body so the
request body can be properly consumed.
Add tests to assert the expected behaviour of the scanner.
> ascanrulesBeta: fix attack URL in PHP RCE scanner

- src/org/zaproxy/zap/extension/ascanrulesBeta/RemoteCodeExecutionCVE20121823.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/RemoteCodeExecutionCVE20121823UnitTest.java
Change scanner RemoteCodeExecutionCVE20121823 to create the attack URL
outside the loop (it's the same for both iterations) and to move the
attack payloads into constants.
> ascanrulesBeta: minor tidy up in PHP RCE scanner

- src/org/zaproxy/zap/extension/pscanrules/CacheControlScanner.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
- test/org/zaproxy/zap/extension/pscanrules/CacheControlScannerUnitTest.java
Change CacheConstrolScanner to not require the private directive, the
directives already required are enough.
Update tests, ZapAddOn.xml file and resource message.
Fix zaproxy/zaproxy#2900 - Remove Cache-Control: 'private' check from
the passive scanner
> pscanrules: do not require private cache directive

- src/org/zaproxy/zap/extension/ascanrulesBeta/HPP.java
Change HPP scanner to catch URIException when sending a message as that
can be thrown if the URI is not correct (non HTTP/S scheme or invalid
encoding).
Related to zaproxy/zaproxy#2224 - HPP Scanner - Multiple Issues
---
> ascanrulesBeta: improve error handling in scanner

- src/org/zaproxy/zap/extension/ascanrulesBeta/RemoteCodeExecutionCVE20121823.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- test/org/zaproxy/zap/extension/ascanrulesBeta/RemoteCodeExecutionCVE20121823UnitTest.java
Change scanner RemoteCodeExecutionCVE20121823 to respect the
technologies (OS) included in the scan, only try Windows attack if
Windows tech is included and Nix attack if Linux or MacOS tech are
included.
Update test and changes in ZapAddOn.xml file.
> ascanrulesBeta: respect OS tech in PHP RCE scanner

- src/org/zaproxy/zap/extension/ascanrules/BufferOverflow.java
- src/org/zaproxy/zap/extension/ascanrules/FormatString.java
- src/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
Change scanners BufferOverflow, FormatString and TestCrossSiteScriptV2
to catch URIException when sending a message as that can be thrown if
the URI is not correct (non HTTP/S scheme or invalid encoding).
Also, change TestCrossSiteScriptV2 to not attempt to use the message if
it was not successfully sent (e.g. because of the above exception).
---
> ascanrules: improve error handling in scanners

- src/org/zaproxy/zap/extension/ascanrulesAlpha/SourceCodeDisclosureFileInclusion.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
Change scanner SourceCodeDisclosureFileInclusion to fix the key of a
resource message when raising an alert (missing the prefix, "lfibased").
---
> ascanrulesAlpha: fix MissingResourceException

- src/org/zaproxy/zap/extension/ascanrulesAlpha/LDAPInjection.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/RelativePathConfusionScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/SourceCodeDisclosureFileInclusion.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/SourceCodeDisclosureGit.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
Change classes SourceCodeDisclosureFileInclusion, LDAPInjection,
SourceCodeDisclosureGit and RelativePathConfusionScanner to reduce the
log levels, from INFO to DEBUG, of messages logged when an alert is
raised to reduce the number of messages logged by default (those
messages are not really needed, the absence or presence of an alert
already indicates that fact).
For LDAPInjection remove its log messages from Messages.properties file
as they do not need to be internationalised.
---
> ascanruleAlpha: adjust log levels

- src/org/zaproxy/zap/extension/ascanrulesBeta/PaddingOraclePlugin.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionHypersonic.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionOracle.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionPostgresql.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SessionFixation.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/UsernameEnumeration.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/XpathInjectionPlugin.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties
Change classes SessionFixation, PaddingOraclePlugin, SQLInjectionOracle,
SQLInjectionHypersonic, SQLInjectionPostgresql, UsernameEnumeration and
XpathInjectionPlugin to reduce the log levels, from INFO to DEBUG, of
messages logged when an alert is raised to reduce the number of messages
logged by default (those messages are not really needed, the absence or
presence of an alert already indicates that fact).
For SessionFixation remove its log messages from Messages.properties
file as they do not need to be internationalised.
---
> ascanruleBeta: adjust log levels

- src/org/zaproxy/zap/extension/domxss/TestDomXSS.java
- src/org/zaproxy/zap/extension/domxss/ZapAddOn.xml
Change TestDomXSS to skip the scanner if fails to get a browser (e.g.
because of unsupported versions between Selenium and Firefox), otherwise
it would keep trying to scan other pages (and continue failing).
Bump version and update changes in the ZapAddOn.xml file.
---
> domxss: skip the scanner if fails to get a browser

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/files/scripts/templates/httpfuzzerprocessor/Fuzzer HTTP Processor default template.js
Correct a method name in "Fuzzer HTTP Processor default template.js",
which should be getHttpMessage() not getMessage().
> fuzz: correct method name in HTTP template

- src/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleFileActiveScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/LDAPInjection.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ProxyDisclosureScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/SourceCodeDisclosureFileInclusion.java
Add missing override annotations in some scanners.
> ascanrulesAlpha: add missing override annotations

- src/com/sittinglittleduck/DirBuster/GenBaseCase.java
- src/com/sittinglittleduck/DirBuster/HTMLparse.java
- src/com/sittinglittleduck/DirBuster/Manager.java
- src/com/sittinglittleduck/DirBuster/ProcessChecker.java
- src/com/sittinglittleduck/DirBuster/ProcessEnd.java
- src/com/sittinglittleduck/DirBuster/ReportWriter.java
- src/com/sittinglittleduck/DirBuster/Worker.java
- src/com/sittinglittleduck/DirBuster/headless/CatchExit.java
- src/com/sittinglittleduck/DirBuster/workGenerators/BruteForceURLFuzz.java
- src/com/sittinglittleduck/DirBuster/workGenerators/BruteForceWorkGenerator.java
- src/com/sittinglittleduck/DirBuster/workGenerators/WorkerGenerator.java
- src/com/sittinglittleduck/DirBuster/workGenerators/WorkerGeneratorURLFuzz.java
- src/org/zaproxy/zap/extension/bruteforce/ZapAddOn.xml
Change DirBuster code to not use the singleton pattern for the Manager
class as ZAP allows to run multiple scans at the same time, which would
lead to inconsistent results (e.g. results of one scan being used/shown
in another).
> bruteforce: do not use singleton pattern

- src/org/zaproxy/zap/extension/ascanrulesAlpha/LDAPInjection.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/SQLInjectionSQLite.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/TestUserAgent.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
Change scanners LDAPInjection, SQLInjectionSQLite and TestUserAgent
to catch URIException (URI is not correct, non HTTP/S scheme or invalid
encoding), UnknownHostException (if the target host is not known) and
InvalidRedirectLocationException (if redirection is not valid) when
sending messages.
---
> ascanrulesAlpha: improve error handling

- src/org/zaproxy/zap/extension/fuzz/files/scripts/templates/httpfuzzerprocessor/Fuzzer HTTP Processor default template.js
- src/org/zaproxy/zap/extension/fuzz/files/scripts/templates/payloadgenerator/Payload Generator default template.js
- src/org/zaproxy/zap/extension/fuzz/files/scripts/templates/payloadprocessor/Payload Processor default template.js
Convert the plain comments into JSDoc comments in the script templates.
> fuzz: use JSDoc in JavaScript templates

- build/build.xml
Add a new Ant task to build.xml to generate the wiki of the add-on.
> tlsdebug: add task to generate the wiki

- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/resources/help/contents/scripts.html
Change scripts.html help page to also mention the HTTP Sender scripts.
> scripts: mention HTTP Sender script in help page

- src/org/zaproxy/zap/extension/fuzz/FuzzerPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
Change FuzzerPayloadGeneratorUIHandler to check that the tree leaf nodes
being added are of the expected type (the top level nodes might be empty
thus being a leaf and treated as source of file fuzzers, which aren't).
The exception would happen, for example, when adding file fuzzers with
empty "Custom Fuzzers" node selected.
> fuzz: fix exception when adding file fuzzers

- src/org/zaproxy/zap/extension/exportreport/export/ExportReport.java
Change ExportReport to call the correct method to obtain the description
set in the dialogue, for the report.
> exportreport: use correct desc in report (UI)

- src/org/zaproxy/zap/extension/exportreport/ZapAddOn.xml
- src/org/zaproxy/zap/extension/exportreport/resources/help/contents/exportreport.html
Correct the link to official Jenkins plugin in the help page, also
remove an unnecessary space from a URL.
> exportreport: correct link to Jenkins plugin

- src/org/zaproxy/zap/extension/exportreport/resources/help/contents/exportreport.html
Remove mentions to the (current) version of the add-on from the help
page, to avoid the need to update the help page each time the version is
changed.
> exportreport: remove version number from the help

- src/org/zaproxy/zap/extension/pscanrules/TestInfoPrivateAddressDisclosure.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
- test/org/zaproxy/zap/extension/pscanrules/TestInfoPrivateAddressDisclosureUnitTest.java
Changes, as mentioned in #2834:
- prefix AWS-hostnames (ip-)
- Fixed a typo in a regex
- updated the alert-description and help page
Added a UnitTest acc. to #2790
This closes zaproxy/zaproxy#2834 and zaproxy/zaproxy#2790
> Added UnitTest & fix for TestInfoPrivateAddressDisclosure

- src/org/zaproxy/zap/extension/ascanrules/CommandInjectionPlugin.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
Drop suffix on *Nix Time Based Blind Command Injection variants, to
increase OS coverage/compatibility.
Update ZapAddOn.xml change section to reflect the modification.
Fixes zaproxy/zaproxy#2973
> Blind Command Injection Improvement

- src/org/zaproxy/zap/extension/quickstart/AttackThread.java
- src/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
- src/org/zaproxy/zap/extension/quickstart/QuickStartPanel.java
- src/org/zaproxy/zap/extension/quickstart/ZapAddOn.xml
Change the "Attack URL" validations, in GUI and command line, to also
check that the provided URL is a valid request-uri. Also, do not
consider incorrect URIs as ZAP errors (i.e. do not log an error if the
URI is not valid).
> quickstart: validate "Attack URL" as a request-uri

- src/org/zaproxy/zap/extension/ascanrules/CommandInjectionPlugin.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
Change CommandInjectionPlugin to use the time defined in rule configs.
Update help page to mention the new 2.6.0 functionality (as done for
other rules).
Related to:
- zaproxy/zaproxy#2647 - Support a/pscan rule configuration
- zaproxy/zaproxy#3037 - False positive for remote command execution
> ascanrules: use time defined in rule configs

- src/org/zaproxy/zap/extension/zest/ExtensionZest.java
- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/menu/ZestRecordOnOffPopupMenu.java
Change ExtensionZest to also add the requests to Sequence scripts,
moreover add the requests to any script that has the "append"
capability, that is, the ones that can be recorded.
Change ZestRecordOnOffPopupMenu to be enabled to all the scripts that
can be recorded.
Fix zaproxy/zaproxy#3044 - Recording of Zest Sequence scripts not
working
> zest: add reqs to Sequence scripts when recording

- src/org/zaproxy/zap/extension/jython/ExtensionJython.java
Change ExtensionJython to depend on ExtensionScript, since it's required
for the extension to work.
> jython: set to depend on script extension

- src/org/zaproxy/zap/extension/zest/ExtensionZest.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestRecordScriptDialog.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestScriptsDialog.java
- src/org/zaproxy/zap/extension/zest/menu/ZestAddToScriptPopupMenu.java
- src/org/zaproxy/zap/extension/zest/menu/ZestRecordOnOffPopupMenu.java
Replace the hardcoded capability "append" with the core constant,
ScriptType.CAPABILITY_APPEND, which is available in the ZAP version(s)
targeted by the add-on.
> zest: use core constant of script type capability

- src/org/zaproxy/zap/extension/jruby/ExtensionJruby.java
Change ExtensionJruby to depend on ExtensionScript, since it's required
for the extension to work.
> jruby: set to depend on script extension

- test/org/zaproxy/zap/extension/ascanrules/ActiveScannerTest.java
- test/org/zaproxy/zap/extension/ascanrules/NanoServerHandler.java
Add methods to consume/get the request body and obtain the number of
messages sent by the active scanners.
(Same behaviour as in beta branch.)
> Add helper test methods for active scanners

- test/org/zaproxy/zap/extension/ascanrules/HTTPDTestServer.java
- test/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2UnitTest.java
Change to check the path exactly as it was provided (instead of adding
path separators) to allow the tests to precisely define what the path is
(e.g. "/path/file.ext" instead of "/path/file.ext/").
Update existing unit test to match the new behaviour of the test server.
> Change how path segment is checked in test server

- src/org/zaproxy/zap/extension/spiderAjax/AjaxProxyServer.java
- src/org/zaproxy/zap/extension/spiderAjax/AjaxProxyThread.java
- src/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
- src/org/zaproxy/zap/extension/spiderAjax/internal/CacheProcessingItem.java
- src/org/zaproxy/zap/extension/spiderAjax/internal/ProxyServer.java
- src/org/zaproxy/zap/extension/spiderAjax/internal/ProxyServerSSL.java
- src/org/zaproxy/zap/extension/spiderAjax/internal/ProxyThread.java
- src/org/zaproxy/zap/extension/spiderAjax/internal/ProxyThreadSSL.java
Change to use "custom" core proxy classes to allow to override the
HttpSender, to use the custom initiator ID. Copied core classes should
be removed once the add-on is targeting newer ZAP versions.
> spiderAjax: use custom initiator ID in HttpSender

- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderDialog.java
- src/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Change AjaxSpiderDialog to allow to update the browsers shown and change
ExtensionAjax to call that method when showing the dialogue.
Fix zaproxy/zaproxy#3057 - AJAX Spider dialogue might not show all
configured browsers
> spiderAjax: show latest configured browsers always

- src/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureWEBINF.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- test/org/zaproxy/zap/extension/ascanrulesBeta/ActiveScannerTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/HTTPDTestServer.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/RemoteCodeExecutionCVE20121823UnitTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureCVE20121823UnitTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureWEBINFUnitTest.java
Change SourceCodeDisclosureWEBINF to not raise an alert if the
successful response does not decompile correctly to a Java class.
Add tests to assert (some of) the expected behaviour of the scanner.
Also, change how path segment is checked in test server to allow the
tests to precisely define what the path is.
Update existing unit tests to match the new behaviour of the test
server.
Fix typo in JavaDoc of helper test method.
Fix zaproxy/zaproxy#3048 - False positive on source disclosure when
target answers invalid url with 200 OK
> ascanrulesbeta: fix src disclosure false positive

- test/org/zaproxy/zap/extension/ascanrulesBeta/ActiveScannerTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/RemoteCodeExecutionCVE20121823UnitTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureCVE20121823UnitTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureWEBINFUnitTest.java
Change class ActiveScannerTest to be generic so the instance variable
"rule" has the type of the scanner being tested, to allow the tests to
access the scanners without casts.
> Generify ActiveScannerTest (beta)

- src/org/zaproxy/zap/extension/ascanrules/CommandInjectionPlugin.java
- test/org/zaproxy/zap/extension/ascanrules/ActiveScannerTest.java
- test/org/zaproxy/zap/extension/ascanrules/CommandInjectionPluginUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2UnitTest.java
Add tests for CommandInjectionPlugin to check that the value used in
time-based attacks is the expected.
Change class ActiveScannerTest to be generic so the instance variable
"rule" has the type of the scanner being tested (to allow to use its
methods without casts).
Update existing unit test, TestCrossSiteScriptV2UnitTest, to set the
type argument for ActiveScannerTest (and remove unnecessary casts).
> Add some tests for CommandInjectionPlugin

- src/org/zaproxy/zap/extension/ascanrules/BufferOverflow.java
- src/org/zaproxy/zap/extension/ascanrules/FormatString.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
Modify BufferOverflow, FormatString, TestDirectoryBrowsing to ensure
base message is checked for initial scanning logic.
Update ZapAddOn.xml to include the new changes, and fix a missing br on
a previous change element entry.
Fixes zaproxy/zaproxy#3065
> Issue 3065 ensure status check against base message (Release)

- src/org/zaproxy/zap/extension/ascanrulesBeta/IntegerOverflow.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- test/org/zaproxy/zap/extension/ascanrulesBeta/IntegerOverflowUnitTest.java
Change IntegerOverflow to use the base message to check the status code
of the response instead of using the message being scanned, which does
not have a response (always passing the 500 status code check).
Add tests to assert (some of) the expected behaviour.
Fix zaproxy/zaproxy#3064 - False positives with Integer Overflow scanner
and 500 error responses
> ascanrulesbeta: fix FP in Integer Overflow scanner

- src/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
- src/org/zaproxy/zap/extension/scripts/PopupMenuItemSaveScript.java
- src/org/zaproxy/zap/extension/scripts/ScriptsListPanel.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Add a context menu item to Scripts tree that allows to save the selected
script.
> scripts: allow to save a script with context menu

- src/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleFileActiveScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleSimpleActiveScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/SlackerCookieDetector.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleFilePassiveScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleSimplePassiveScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ImageLocationScanner.java
- src/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanner.java
- src/org/zaproxy/zap/extension/soap/SOAPXMLInjectionActiveScanner.java
- src/org/zaproxy/zap/extension/soap/WSDLFilePassiveScanner.java
Change to reference scanners.md (instead of alerts.xml, which was
replaced by the former file).
Remove references from non-example code.
Related to zaproxy/zaproxy#3034 - Remove alerts.xml file
> Update references to registry of scanners' IDs

- src/org/zaproxy/zap/extension/invoke/InvokeAppWorker.java
- src/org/zaproxy/zap/extension/invoke/ZapAddOn.xml
Change InvokeAppWorker to consume std/err output using only one input
stream, preventing the output buffers of the application from becoming
full (and leading to hangs), and from showing, in ZAP, first the error
output and then the standard output.
Fix zaproxy/zaproxy#3074 - external program hang
Fix zaproxy/zaproxy#3078 - external program: async STDERR and STDOUT
> invoke: consume std/err output at the same time

- src/org/zaproxy/zap/extension/tokengen/GenerateTokensDialog.java
- src/org/zaproxy/zap/extension/tokengen/ZapAddOn.xml
Change GenerateTokensDialog to show the same cookies just once (happens
when both the request and response headers have the same cookie).
Part of zaproxy/zaproxy#2116 - Issue with Token generator
> tokengen: show same cookies just once

- src/org/zaproxy/zap/extension/tokengen/TokenGenMessagesTable.java
- src/org/zaproxy/zap/extension/tokengen/TokenGenPopupMenu.java
Change TokenGenMessagesTable to extend ZapTable which already provides
some of the functionality used by the former table and adds support for
auto-scrolling.
Change TokenGenPopupMenu to use the icon of the token generator panel,
to make the menu item easier to spot.
> tokengen: minor UI tweaks

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/dialogs/ZestDialogManager.java
Change ZestDialogManager to execute the mouse click action just once
(i.e. with just the clicked event, release event is included in the
former event).
Fix zaproxy/zaproxy#3099 - Zest nodes' mouse click action done twice
> zest: execute mouse click action just once

- src/org/zaproxy/zap/extension/tokengen/CharacterFrequencyMap.java
- src/org/zaproxy/zap/extension/tokengen/ExtensionTokenGen.java
- src/org/zaproxy/zap/extension/tokengen/TokenAnalysisTestResult.java
- src/org/zaproxy/zap/extension/tokengen/ZapAddOn.xml
- test/org/zaproxy/zap/extension/tokengen/CharacterFrequencyMapUnitTest.java
Change CharacterFrequencyMap to prevent a division by zero when there
are no tokens (also, fail the character uniformity test in that case).
Change TokenAnalysisTestResult to remove dependency on Constant class,
to make tests easier.
Add tests to assert (some of) the expected behaviour of
CharacterFrequencyMap.
Part of zaproxy/zaproxy#2116 - Issue with Token generator
> tokengen: fix division by zero

- src/org/zaproxy/zap/extension/scripts/ConsolePanel.java
- src/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Change ExtensionScriptsUI to reset the console output panel when the
session changes.
Change ConsolePanel to allow to reset the console output panel.
> scripts: reset output panel on session changes

- src/org/zaproxy/zap/extension/zest/ExtensionZest.java
- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
Change ExtensionZest to clear the results shown in Zest Results panel
when the session changes.
> zest: clear zest results on session changes

- src/org/zaproxy/zap/extension/invoke/ZapAddOn.xml
- src/org/zaproxy/zap/extension/invoke/resources/help/contents/concepts.html
- src/org/zaproxy/zap/extension/invoke/resources/help/contents/options.html
Change pages "Options Applications screen" and "Invoke Applications" to
fix some typos.
> invoke: fix typos in help pages

- src/org/zaproxy/zap/extension/jython/ExtensionJython.java
- src/org/zaproxy/zap/extension/jython/JythonOptionsPanel.java
- src/org/zaproxy/zap/extension/jython/JythonOptionsParam.java
- src/org/zaproxy/zap/extension/jython/Messages.properties
- src/org/zaproxy/zap/extension/jython/ZapAddOn.xml
Support the interface to add the python module path.
The "python.path" system property is treated as a module search path inside Jython.
This implementation adds the "zap.jython.modulepath" ZAP option, and set its value to "python.path" system property.
> Support to add the python module path interface to jython extension

- src/org/zaproxy/zap/extension/ascanrules/TestSQLInjection.java
The **TODO** is already implemented using `strippOff` method.
Fixes zaproxy/zaproxy#3137
> Removed comment that contain already implemented TODO

- src/org/zaproxy/zap/extension/pscanrulesAlpha/StrictTransportSecurityScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
Only report HSTS on plain HTTP if threshold is Low.
Fixes zaproxy/zaproxy#3148
> Issue 3148 HTTP HSTS Threshold Check

- src/org/zaproxy/zap/extension/ascanrulesBeta/Csrftokenscan.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrulesBeta/CSRFCountermeasures.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
Note that this includes a couple of changes that were implemented in #570 - I have updated my local copy of the CSRFCountermeasures tests but want to see it the original submitter was going to update them before adding my changes.
> Support security annotations for forms that dont need anti CSRF tokens.

- build/build.xml
- src/org/openqa/selenium/firefox/GeckoDriverService.java
- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
- src/org/zaproxy/zap/extension/selenium/SeleniumOptions.java
- src/org/zaproxy/zap/extension/selenium/SeleniumOptionsPanel.java
- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
- src/org/zaproxy/zap/extension/selenium/resources/Messages.properties
- src/org/zaproxy/zap/extension/selenium/resources/help/contents/api.html
- src/org/zaproxy/zap/extension/selenium/resources/help/contents/intro.html
- src/org/zaproxy/zap/extension/selenium/resources/help/contents/options.html
Change ExtensionSelenium to use geckodriver/marionette, allowing to use
newer versions of Firefox (>= 48).
Change options to allow to specify the path to geckodriver.
Backport GeckoDriverService to not require updating Selenium (which
needs Java 8).
Update help pages to mention the supported versions of Firefox.
Fix zaproxy/zaproxy#2743 - Unable to use Firefox 48+ with AJAX Spider
> selenium: add support for Firefox 48+

- src/org/zaproxy/zap/extension/ascanrulesAlpha/LDAPInjection.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ProxyDisclosureScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/SQLInjectionSQLite.java
Change license header in scanners from JavaDoc comment to a plain
comment.
> Change license header to plain comment (alpha)

- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionHypersonic.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionMySQL.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionOracle.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionPostgresql.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SessionFixation.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/UsernameEnumeration.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/CSRFCountermeasures.java
Change license header in scanners from JavaDoc comment to a plain
comment.
> Change license header to plain comment (beta)

- src/org/zaproxy/zap/extension/selenium/Browser.java
- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
- src/org/zaproxy/zap/extension/selenium/SeleniumOptions.java
- src/org/zaproxy/zap/extension/selenium/SeleniumOptionsPanel.java
- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
- src/org/zaproxy/zap/extension/selenium/resources/Messages.properties
- src/org/zaproxy/zap/extension/selenium/resources/help/contents/options.html
Change Selenium add-on to use the bundled WebDrivers by default (when
available and no WebDriver was previously set).
Update help to mention the new behaviour.
> selenium: use bundled WebDrivers by default

- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/dialogs/NewScriptDialog.java
Modified `NewScriptDialog` to not pad the list with a blank entry if there
is only one script engine available.
Updated changes section of `ZapAddOn.xml`
> New script dialog default engine when only one

- src/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Change SpiderThread to also use the list of global excluded URLs when
checking if the requested URL should be excluded.
Fix zaproxy/zaproxy#3172 - AJAX Spider should honour global excluded
URLs
> spiderAjax: honour global excluded URLs

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/AntiCsrfHttpFuzzerMessageProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/resources/help/contents/httpmessageprocessors.html
Add the HTTP message processor Anti-CSRF Token Refresher by default (if
anti-CSRF tokens were detected).
Update help page to mention which processors are added by default.
> fuzz: add Anti-CSRF Token Refresher by default

- src/org/zaproxy/zap/extension/fuzz/FuzzerPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/AbstractHttpFuzzerMessageProcessorUIPanel.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/AntiCsrfHttpFuzzerMessageProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/FuzzerHttpMessageScriptProcessorAdapterUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/HttpFuzzerReflectionDetectorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/RequestContentLengthUpdaterProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/UserHttpFuzzerMessageProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/tagcreator/HttpFuzzerMessageProcessorTagUIPanel.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/AbstractPersistentPayloadGeneratorUIPanel.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/DefaultStringPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/FileStringPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/RegexPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/ScriptStringPayloadGeneratorAdapterUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/AbstractProcessorUIPanel.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/Base64DecodeProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/Base64EncodeProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/ExpandStringProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/JavaScriptEscapeProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/JavaScriptUnescapeProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/MD5HashProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/PostfixStringProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/PrefixStringProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/SHA1HashProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/SHA256HashProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/ScriptStringPayloadProcessorAdapterUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/TrimStringProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/URLDecodeProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/URLEncodeProcessorUIHandler.java
Add help target/index to the fuzzer dialogues (mainly base classes), to
allow to access the help pages directly with a help button.
> fuzz: show help button in dialogues

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/resources/help/contents/payloads.html
- src/org/zaproxy/zap/extension/fuzz/resources/help/contents/processors.html
Fix typos (missing word or wrong char) in the help pages.
> fuzz: fix typos in the help pages

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/HttpFuzzerReflectionDetectorStateHighlighter.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/tagcreator/HttpFuzzerMessageProcessorTagCreator.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/tagcreator/HttpFuzzerMessageProcessorTagStateHighlighter.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/ui/HttpFuzzerResultStateHighlighter.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/ui/HttpFuzzerResultsTable.java
Change FuzzResultStateHighlighter to render the custom states always
(that is, render the value if the state does not have any renderer
associated).
Fix zaproxy/zaproxy#3166 - Fuzzer: Not Rendering Custom States
> fuzz: render custom states always

- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderResultsTable.java
- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderResultsTableModel.java
- src/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- src/org/zaproxy/zap/extension/spiderAjax/SpiderPanel.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Change AJAX Spider tab to show the alerts/tags of the messages, also,
allow to see more details of the message (size header/body and response
timestamp).
Update changes and bump minimum ZAP version (required to properly show
the alerts) in ZapAddOn.xml file.
> ajaxSpider: show alerts/tags in AJAX Spider tab

- src/org/zaproxy/zap/extension/spiderAjax/SpiderPanel.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Change SpiderPanel to reset the URL counter shown in the AJAX Spider tab
when the session changes.
> ajaxSpider: reset URL counter on session change

- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderAPI.java
- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderResultsTable.java
- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderResultsTableModel.java
- src/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- src/org/zaproxy/zap/extension/spiderAjax/SpiderListener.java
- src/org/zaproxy/zap/extension/spiderAjax/SpiderPanel.java
- src/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
- src/org/zaproxy/zap/extension/spiderAjax/resources/Messages.properties
Change AJAX Spider tab to show the requests that were excluded (i.e. out
of spider scope).
Change the API to allow to obtain the resources in and out of scope,
through a new endpoing "fullResults".
> ajaxSpider: show excluded requests

- src/org/zaproxy/zap/extension/webdriverlinux/WebdriverDownload.java
- src/org/zaproxy/zap/extension/webdriverlinux/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdrivermacos/WebdriverDownload.java
- src/org/zaproxy/zap/extension/webdrivermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverwindows/WebdriverDownload.java
- src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
Update geckodriver to latest version.
Bump versions and update changes in ZapAddOn.xml files.
> webdrivers: update geckodriver to v0.14.0

- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderAPI.java
- src/org/zaproxy/zap/extension/spiderAjax/SpiderPanel.java
- src/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java
Log the ID of the browser used with Crawljax, when starting.
Set a name to the threads started by the AJAX spider.
> spiderAjax: log browser and name the threads used

- build/build.xml
- src/org/zaproxy/zap/extension/webdriverlinux/WebdriverDownload.java
- src/org/zaproxy/zap/extension/webdriverlinux/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdrivermacos/WebdriverDownload.java
- src/org/zaproxy/zap/extension/webdrivermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverwindows/WebdriverDownload.java
- src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
This depends on zaproxy/zap-libs#2
I'll raise another PR to remove them from alpha when this one is merged
> Promote webdriver add-ons to beta

- src/org/zaproxy/zap/extension/selenium/Browser.java
- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
- src/org/zaproxy/zap/extension/selenium/ProvidedBrowser.java
- src/org/zaproxy/zap/extension/selenium/ProvidedBrowserUI.java
- src/org/zaproxy/zap/extension/selenium/ProvidedBrowsersComboBoxModel.java
- src/org/zaproxy/zap/extension/selenium/SingleWebDriverProvider.java
- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
- src/org/zaproxy/zap/extension/selenium/internal/BuiltInSingleWebDriverProvider.java
- src/org/zaproxy/zap/extension/selenium/resources/Messages.properties
Change Selenium add-on to allow to add new browsers (e.g. JxBrowser).
Bump versions and update changes in ZapAddOn.xml file.
> selenium: allow add-ons to add new browsers

- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderDialog.java
- src/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- src/org/zaproxy/zap/extension/spiderAjax/OptionsAjaxSpider.java
- src/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Change AJAX Spider to allow to use the provided browsers from Selenium.
Update changes and bump (minimum) Selenium version in ZapAddOn.xml file.
> spiderAjax: use provided browsers from Selenium

- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderAPI.java
- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderResultsTableModel.java
- src/org/zaproxy/zap/extension/spiderAjax/SpiderListener.java
- src/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
- src/org/zaproxy/zap/extension/spiderAjax/resources/Messages.properties
Change AJAX Spider to also show/provide the messages that were not sent
successfully because of I/O errors (e.g. target not reachable),
otherwise it might seem that the spider is not working and not all
information is provided.
> spiderAjax: show messages with I/O errors

- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
- src/org/zaproxy/zap/extension/selenium/SingleWebDriverProvider.java
- src/org/zaproxy/zap/extension/selenium/internal/BuiltInSingleWebDriverProvider.java
- src/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java
Change Selenium add-on to allow WebDriver providers to show a custom
warning message, when the WebDriver/browser failed to start.
Update AJAX Spider add-on to pass the exception that occurred while
starting the WebDriver/browser (useful for the providers to return a
more accurate warning message).
> selenium: allow providers to show custom warn msg

- src/org/zaproxy/zap/extension/spiderAjax/SpiderPanel.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Change SpiderPanel to ensure that the New Scan button is enabled, when
the current mode allows it.
> spiderAjax: ensure New Scan button is enabled

- .classpath
- src/org/zaproxy/zap/extension/jxbrowser/BrowserFrame.java
- src/org/zaproxy/zap/extension/jxbrowser/BrowserPanel.java
- src/org/zaproxy/zap/extension/jxbrowser/Utils.java
- src/org/zaproxy/zap/extension/jxbrowser/ZapBrowserFrame.java
- src/org/zaproxy/zap/extension/jxbrowser/ZapBrowserPanel.java
- src/org/zaproxy/zap/extension/jxbrowser/ZapTabbedPanel.java
- src/org/zaproxy/zap/extension/jxbrowserlinux32/ExtensionJxBrowserLinux32.java
- src/org/zaproxy/zap/extension/jxbrowserlinux32/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowserlinux32/selenium/ExtSelJxBrowserLinux32.java
- src/org/zaproxy/zap/extension/jxbrowserlinux32/selenium/JxBrowserProvider.java
- src/org/zaproxy/zap/extension/jxbrowserlinux64/ExtensionJxBrowserLinux64.java
- src/org/zaproxy/zap/extension/jxbrowserlinux64/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowserlinux64/selenium/ExtSelJxBrowserLinux64.java
- src/org/zaproxy/zap/extension/jxbrowserlinux64/selenium/JxBrowserProvider.java
- src/org/zaproxy/zap/extension/jxbrowsermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowsermacos/selenium/ExtSelJxBrowserMacOs.java
- src/org/zaproxy/zap/extension/jxbrowsermacos/selenium/JxBrowserProvider.java
- src/org/zaproxy/zap/extension/jxbrowserwindows/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowserwindows/selenium/ExtSelJxBrowserWindows.java
- src/org/zaproxy/zap/extension/jxbrowserwindows/selenium/JxBrowserProvider.java
Change JxBrowser add-ons to provide WebDrivers, so that it can be used
by other add-ons (e.g. AJAX Spider).
Change some classes to allow to create tabs with Browsers, to have just
one window/dialogue for all browsers required by automated tools.
The JxBrowserProvider implementation is duplicated as core does not
support the sharing of the class in other non-dependent add-ons. The
duplication will be removed once core supports that.
The JxBrowser add-ons do not depend (directly) on the Selenium add-on,
allowing the JxBrowser to be used without Selenium add-on.
> jxbrowser: provide WebDrivers

- src/org/zaproxy/zap/extension/invoke/InvokeAppWorker.java
- src/org/zaproxy/zap/extension/invoke/ZapAddOn.xml
Change InvokeAppWorker to properly split the application arguments to
correctly pass them to the application being launched.
> invoke: properly split application arguments

- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderDialog.java
Change AjaxSpiderDialog to not check if the ExtensionSelenium exists or
not, the extension is guaranteed to exist per the dependencies of the
add-on. Also, use the class to obtain the extension (avoids the need
to cast to the extension).
> spiderAjax: remove unnecessary check

- src/org/zaproxy/zap/extension/importLogFiles/ImportLogAPI.java
- src/org/zaproxy/zap/extension/importLogFiles/ZapAddOn.xml
Change ImportLogAPI to use actions (instead of views) to import the
files. Also, move the logic of one action to the method that handles the
actions (instead of the options).
> importLogFiles: use actions when importing files

- src/org/zaproxy/zap/extension/jxbrowsermacos/selenium/JxBrowserProvider.java
Change JxBrowserProvider (macOS) to reuse same JxBrowser port, the
process tends to live longer thus (remote) WebDrivers need to connect to
the same port (otherwise they would fail to connect).
---
Thanks to @psiinon for providing valuable information about the issue.
> jxbrowser: reuse the same JxBrowser port on macOS

- src/org/zaproxy/zap/extension/jxbrowser/resources/Messages.properties
- src/org/zaproxy/zap/extension/jxbrowserlinux32/selenium/JxBrowserProvider.java
- src/org/zaproxy/zap/extension/jxbrowserlinux64/selenium/JxBrowserProvider.java
- src/org/zaproxy/zap/extension/jxbrowsermacos/selenium/JxBrowserProvider.java
- src/org/zaproxy/zap/extension/jxbrowserwindows/selenium/JxBrowserProvider.java
Change JxBrowserProvider(s) to return a custom error message, with the
more likely cause of why the JxBrowser failed to start when using the
WebDriver.
> jxbrowser: show custom message if failed to start

- src/org/zaproxy/zap/extension/pscanrulesAlpha/ContentSecurityPolicyMissingScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
Justification - CSP only helps if its turned on. Having the Report-Only header is good for testing CSP but doesnt improve the security of the site. So we should report a missing (non report) header in the same way regardless of whether the Report-Only header is present. Thats what we'd like at Mozilla anyway, but happy to discuss other options :)
> Report missing CSP header as LOW even if CSP Report header present.

- src/org/zaproxy/zap/extension/jxbrowser/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowser/resources/help/contents/jxbrowser.html
Update help page to mention the ID of the browser, needed for choosing
JxBrowser through the command line or the ZAP API.
> jxbrowser: document the ID of the browser

- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
- src/org/zaproxy/zap/extension/selenium/resources/help/contents/intro.html
Update help page to mention the IDs of the browsers, needed for choosing
a browser through the command line or the ZAP API. Also, mention that
other add-ons can add browsers.
The help page was reorganised to have the name, ID and requirements of
the browsers in the same place (table).
> selenium: document the IDs of the browsers

- build/build.xml
Change build.xml file to add a task to (re)generate the Form Handler's
wiki (into zap-extensions wiki).
> Add task to generate Form Handler's wiki

- src/org/zaproxy/zap/extension/soap/ExtensionImportWSDL.java
Change ExtensionImportWSDL to declare that it can't be unloaded (not all
components are/can be unloaded) and remove unnecessary statements from
unload method (core already takes care to remove hooked components).
> soap: minor tidy up

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestFuzzerDelegate.java
Change ZestFuzzerDelegate to check if the file fuzzers.jbrf exist before
trying to use it, if it doesn't exist continue and allow to add/loop
other files (e.g. from FuzzDB, custom ones or manually specified).
Fix zaproxy/zaproxy#3400 - Zest add-on should cope better with missing
file fuzzers.jbrf
> zest: allow to add loop files, always

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestScriptWrapper.java
Change ZestScriptWrapper to use the hashCode of ScriptWrapper, to remove
the corresponding ScriptWrapper from core extension.
Fix zaproxy/zaproxy#3401 - Unable to remove Zest scripts
> zest: allow to properly remove the scripts

- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
- src/org/zaproxy/zap/extension/selenium/resources/help/contents/intro.html
- src/org/zaproxy/zap/extension/selenium/resources/help/contents/options.html
Move the bundled WebDrivers section to the main help page, to be more
visible, also, recommend using newer versions of the browsers with the
bundled WebDrivers.
For zaproxy/zaproxy#3369 - AJAX Spider via Firefox closes immediately
after upgrade to ZAP 2.6.0
> selenium: move webdrivers section to main page

- src/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
- src/org/zaproxy/zap/extension/openapi/OpenApiSpider.java
- src/org/zaproxy/zap/extension/openapi/ZapAddOn.xml
- src/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverter.java
Change OpenApiSpider and ExtensionOpenApi to use the scheme of the
request URI, used to obtain the spec, when the scheme is not specified
in the spec.
Fix zaproxy/zaproxy#3433 - OpenAPI: Parsing of JSON downloaded from a
URL fails if no schemes element is present
> openapi: fallback to scheme of request URI

- src/org/zaproxy/zap/extension/bugtracker/BugTrackerBugzilla.java
- src/org/zaproxy/zap/extension/bugtracker/BugTrackerGithub.java
- src/org/zaproxy/zap/extension/bugtracker/DialogAddBugzillaConfig.java
- src/org/zaproxy/zap/extension/bugtracker/DialogAddGithubConfig.java
Building anything in the Alpha branch causes a bunch of warnings due to
deprecation etc. This PR addresses the deprecated items in the
bugtracker addon.
> BugTracker Fix Build Warnings

- src/org/zaproxy/zap/extension/exportreport/ExportReportAPI.java
- src/org/zaproxy/zap/extension/exportreport/export/ReportExport.java
Building anything in the Alpha branch causes a bunch of warnings due to
deprecation etc. This PR addresses the deprecated and static access
items in the exportreport addon.
> ExportReport Fix Build Warnings

- src/org/zaproxy/zap/extension/wavsepRpt/ExtensionWavsepReport.java
- src/org/zaproxy/zap/extension/wavsepRpt/ZapAddOn.xml
Building anything in the Alpha branch causes a bunch of warnings due to deprecation etc. This PR addresses the deprecated items in the wavsepRpt addon.
Updated manifest version and removed old changes entry as well.
> WavsepReport Fix Build Warnings

- src/org/zaproxy/zap/extension/domxss/TestDomXSS.java
- src/org/zaproxy/zap/extension/domxss/ZapAddOn.xml
Building anything in the Alpha branch causes a bunch of warnings due to deprecation etc. This PR addresses the deprecated items in the domxss addon.
Also updated manifest version, removed old changes block, and appropriately set dependency info.
http://atetric.com/atetric/javadoc/org.seleniumhq.selenium/selenium-api/2.53.0/src-html/org/openqa/selenium/remote/SessionNotFoundException.html
> DOM XSS Scanner Fix Build Warnings

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/dialogs/ZestAssignmentDialog.java
- src/org/zaproxy/zap/extension/zest/resources/Messages.properties
Add a field, to Add Assignment dialogue, for "assign replace" to control
the case when matching the value to be replaced.
Related to mozilla/zest#93 - Implement exact case replacement when
assigning
> zest: add exact case option for assign replace

- src/org/zaproxy/zap/extension/scripts/ScriptsListPanel.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Change ScriptsListPanel to set the context menu into the Scripts tree
instead of manually invoking it with a MouseListener, the latter could
lead to the context menu being invoked twice leading to duplicated
menu items. Also, remove the KeyListener, the context menu set can be
already invoked with keyboard shortcuts.
Related to zaproxy/zaproxy#2106 - Zest - script context menu has
duplicated items
> scripts: invoke context menu once

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/HttpFuzzerReflectionDetector.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/ui/HttpFuzzerResultsTable.java
Change HttpFuzzerResultsTable to not highlighting empty payloads and
change HttpFuzzerReflectionDetector to ignore empty payloads when
detecting reflections, in both cases the empty payload would always
match highlight nothing and adding useless reflections.
> fuzz: ignore empty payloads for reflections

- src/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/payloads/generator/EmptyPayloadGenerator.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/DefaultEmptyPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
- src/org/zaproxy/zap/extension/fuzz/resources/help/contents/payloads.html
Allow to choose the null/empty payload generator which allows to send
the message multiple times without changes, for later processing with
a processor script.
> fuzz: allow to choose null/empty payload generator

- src/org/zaproxy/zap/extension/pscanrulesBeta/InformationDisclosureDebugErrors.java
- test/org/zaproxy/zap/extension/pscanrulesBeta/InformationDisclosureDebugErrorsUnitTest.java
Added a unit test for InformationDisclosureDebugErrors as described in https://github.com/zaproxy/zaproxy/issues/2802.
The test itself simply checks 1) for alerts on a couple of values taken from debug-error-messages.txt and 2) that no alerts are raised for a couple of strings that might be similiar to error strings.
As this is my first PR for zaproxy, please let me know if there is anything wrong with it.
> Added unit test for InformationDisclosureDebugErrors class

- src/org/zaproxy/zap/extension/pscanrulesBeta/CharsetMismatchScanner.java
- test/org/zaproxy/zap/extension/ScannerTestUtils.java
- test/org/zaproxy/zap/extension/pscanrulesBeta/CharsetMismatchScannerUnitTest.java
Test for issue [2799](https://github.com/zaproxy/zaproxy/issues/2799)
There is probably one bug, unit test implemented for this bug in method differentMetaAndHeaderPlusAdditionalMetaParametersHtml.
> Added unit test for CharsetMismatchScanner class

- .gitignore
- src/org/zaproxy/zap/extension/pscanrulesBeta/CookieLooselyScopedScanner.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- test/org/zaproxy/zap/extension/pscanrulesBeta/CookieLooselyScopedScannerUnitTest.java
The commit includes the following:
1. Unit tests for the CookieLooselyScopedScannerUnitTest class
2. Two necessary refactorings to make the filtering of cookie domains more robust
3. Adding IntelliJ IDEA specific files to gitignore
Fixes zaproxy/zaproxy#2800
> Unit tests for the CookieLooselyScopedScannerUnitTest class (issue #2800)

- test/org/zaproxy/zap/extension/pscanrulesBeta/ViewStateScannerUnitTest.java
Added unit test for ViewstateScanner 2809
3 tests @Ignore'd due to java compatibility issues (works in 8, fails in 7)
Fixes zaproxy/zaproxy#2809
> 2809 viewstate scanner unit test

- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
EL Injection keys removed as the scanner seem to have been promoted to
beta
(https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties#L176-L179)
> ascan alpha removed unused resource messages

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/dialogs/ZestActionDialog.java
Change ZestActionDialog to select the correct script of the action by
using the name of the script instead of the file path. If the script no
longer exists (that is, added to ZAP) it's selected an existing one.
Fix zaproxy/zaproxy#3489 - Zest script execution UI does not show the
correct configuration
> zest: select correct script when editing actions

- src/org/zaproxy/zap/extension/ApiGenerator.java
Add the API class ImportUrlsAPI to the class ApiGenerator, to include it
when (re)generating the client APIs.
> importurls: add to API generator

- src/org/zaproxy/zap/extension/zest/ExtensionZest.java
- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestScriptWrapper.java
Change ExtensionZest to only wrap the script being added if it's not a
wrapper already (the wrapper does not allow to set the contents of the
script leading to an empty script for the Sequence scanning, thus not
perform any scanning at all).
Change ZestScriptWrapper to use the correct Zest type for Sequence
scripts, when recorded. Also, merge common case when choosing the type.
Fix zaproxy/zaproxy#3536 - Sequence Addon "Active scan sequence" Doesn't
Work From Scripts Tree
> zest: don't re-wrap Zest scripts

- src/org/zaproxy/zap/extension/sequence/ZapAddOn.xml
Make Sequence addon depend on Zest extension, since it is currently the only script option for Sequence scripts.
> Sequence Depend on Zest

- src/org/zaproxy/zap/extension/pscanrulesAlpha/XDebugTokenScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
- test/org/zaproxy/zap/extension/pscanrulesAlpha/XDebugTokenScannerUnitTest.java
XDebugTokenScanner - The new scanner.
Messages.properties - Add necessary i18n keys and values.
pscanalpha.html - Add new help entry.
ZapAddOn.xml - Add new change entry, and include the new scanner in the
pscanrules section.
XDebugTokenScannerUnitTest - The unit tests for the new scanner.
Fixes zaproxy/zaproxy#2452
> Issue 2452 Add X-Debug-Token Passive Scanner

- src/org/zaproxy/zap/extension/ascanrules/TestPathTraversal.java
- test/org/zaproxy/zap/extension/ascanrules/TestPathTraversalUnitTest.java
Change TestPathTraversal to simply search for the directory names
instead of using a regular expression, while with the regular expression
the evidence included all the directory names it was not efficient with
bigger responses (new behaviour returns one of the directory names).
For example, with a 76k chars response the regex took 153s to complete
but less than 1s with the simple search.
Add tests to assert the expected behaviour when testing for directory
listings.
Fix zaproxy/zaproxy#3468 - PathTraversal rule performance issue
> Replace use of regex in TestPathTraversal dir test

- src/org/zaproxy/zap/extension/ascanrules/TestParameterTamper.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- test/org/zaproxy/zap/extension/ascanrules/TestParameterTamperUnitTest.java
Change TestParameterTamper to include the evidence in the evidence field
instead of Other Info field, also, correctly set the attack in the
attack field (previously set as Other Info).
Add tests to assert the expected behaviour and alert data.
Fix zaproxy/zaproxy#3524 - 'Parameter Tampering' alert has an invalid
'otherinfo' field value equals @
> Change TestParameterTamper to set evidence field

- src/org/zaproxy/zap/extension/ascanrules/TestPathTraversal.java
Fixed false positive for applications, where only few values are possible for query parameter (including empty string), otherwise it fails with an error.
URI.getName returns empty string in cases, when url ends with /. And second part of test will send request with empty parameter.
This test always alerts in such cases.
> fix path traversal test with random parameter value

- src/org/zaproxy/zap/extension/ascanrulesAlpha/TraceAxdScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
TraceAxdScanner - The new scanner.
Messages.properties - Add necessary i18n keys and values.
ascanalpha.html - Add new help entry.
ZapAddOn.xml - Add new change entry, and include the new scanner in the ascanrules section.
Fixes zaproxy/zaproxy#3280
> Issue 3280 Add trace.axd Active Scanner

- build/build.xml
Add a new task to build.xml file to generate the wiki of the add-on.
> bugtracker: add task to generate the wiki

- src/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/ExtensionHttpFuzzer.java
Change ExtensionFuzz and ExtensionHttpFuzzer to set the custom script
types enabled by default.
Bump minimum ZAP version (to 2.6.0, required by the new feature) and
update changes in ZapAddOn.xml file.
Part of zaproxy/zaproxy#2997 - Change fuzzer related script types to be
enabled by default
> fuzz: set script types enabled by default

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/fuzz/ExtensionWebSocketFuzzer.java
Change ExtensionWebSocketFuzzer to set the custom script type enabled by
default.
Bump minimum ZAP version (to 2.6.0, required by the new feature) and
update changes in ZapAddOn.xml file.
Part of zaproxy/zaproxy#2997 - Change fuzzer related script types to be
enabled by default
> websocket: set fuzzer script enabled by default

- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/dialogs/LoadScriptDialog.java
- src/org/zaproxy/zap/extension/scripts/dialogs/NewScriptDialog.java
- src/org/zaproxy/zap/extension/scripts/resources/Messages.properties
Change NewScriptDialog and LoadScriptDialog to allow to set the enabled
state of the script (based on the selected script type).
Fix zaproxy/zaproxy#2996 - Allow to configure the enabled state of
new/loaded scripts
> scripts: allow to set new/loaded script as enabled

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/Messages.properties
- src/org/zaproxy/zap/extension/websocket/ui/OptionsParamWebSocket.java
- src/org/zaproxy/zap/extension/websocket/ui/SessionExcludeFromWebSocket.java
Change SessionExcludeFromWebSocket to use the same table as the other
exclude panels (to allow to manage the excluded URLs more easily).
> websocket: normalise session properties panel

- src/org/zaproxy/zap/extension/pscanrules/MixedContentScanner.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- test/org/zaproxy/zap/extension/pscanrules/MixedContentScannerUnitTest.java
Change MixedContentScanner to just check HTML files as the parser is
only for HTML content, attempting to use it with other files would lead
to misinterpreted results (e.g. a JavaScript file with HTML tags embeded
in comments). Also, remove redundant null check (the variable is never
null) and reorder statements to reduce the block statement depth.
Add tests to assert the expected behaviour.
Fix zaproxy/zaproxy#3581 - False Positive with Secure Pages Include
Mixed Content and JavaScript files
(Fix zaproxy/zaproxy#2788 as well.)
> pscanrules: fix FP with mixed content and JS files

- src/org/zaproxy/zap/extension/pscanrules/TestInfoPrivateAddressDisclosure.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- test/org/zaproxy/zap/extension/pscanrules/TestInfoPrivateAddressDisclosureUnitTest.java
TestInfoPrivateAddressDisclosure - Change the comparison of private IP matches to only compare the IP or Host portion (excluding port).
TestInfoPrivateAddressDisclosureUnitTest - Add an additional test which covers the revised behavior both with and without port being specified.
Fixes zaproxy/zaproxy#3549
> Private IP Disclosure Handle Non-Standard Ports

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/ui/PopupExcludeWebSocketFromContextMenu.java
- src/org/zaproxy/zap/extension/websocket/ui/PopupIncludeWebSocketInContextMenu.java
Fix context include/exclude pop up menu items, which were no longer
working correctly (the former was throwing a NullPointerException but
still showing the dialogue; the latter was showing the dialogue twice,
moreover changes were being applied to the existing context instead of a
temporary one, to properly cancel the changes).
> websocket: fix context include/exclude menus

- build/build.xml
- src/org/zaproxy/zap/extension/portscan/OptionsPortScanPanel.java
- src/org/zaproxy/zap/extension/portscan/ZapAddOn.xml
OptionsPortScanPanel.java - Change panelPortScan to use sub-panels for some components (which use Flowlayout by default), which should make the alignment in the UI seem more natural. Also change the port
specification control to be a number spinner instead of a slider.
ZapAddOn.xml - Updated changes section of manifest
build.xml - Added `deploy-portscan-without-help-indexes` task to facilitate quick dev builds.
Fixes zaproxy/zaproxy#3513
New options UI screenshot:
> Issue 3513 Tweak Portscan Options UI

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- src/org/zaproxy/zap/extension/websocket/WebSocketProxy.java
- src/org/zaproxy/zap/extension/websocket/WebSocketSenderListener.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/fuzz/WebSocketFuzzerTask.java
- src/org/zaproxy/zap/extension/websocket/fuzz/WebSocketFuzzerTaskProcessorUtils.java
- src/org/zaproxy/zap/extension/websocket/manualsend/WebSocketPanelSender.java
This commit relates to https://github.com/zaproxy/zaproxy/issues/2955
WebSocketSenderListener provides `org.zaproxy.zap.network.HttpSenderListener` like features.
It receives all state change/frame notifies from WebSocketProxy.
> Implements WebSocketSenderListener

- src/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java
- src/org/zaproxy/zap/extension/alertFilters/ZapAddOn.xml
Change ExtensionAlertFilters to add the components through the provided
hook (instead of adding them directly to the core components, so that
they are automatically unloaded when the add-on is uninstalled) and
declare that the extension can be unloaded.
Bump minimum ZAP version and version of the add-on and update changes in
ZapAddOn.xml file.
> alertFilters: dynamically unload the add-on

- src/org/zaproxy/zap/extension/openapi/OpenApiAPI.java
- src/org/zaproxy/zap/extension/openapi/ZapAddOn.xml
Change OpenApiAPI to validate that the provided path is a file (not just
that it exists) and check if the parsing succeeded at all.
> openapi: validate provided path and fix NPE

- src/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java
- src/org/zaproxy/zap/extension/alertFilters/ZapAddOn.xml
Change ExtensionAlertFilters to clear the state of the alert filters
when the session is about to change.
Fix zaproxy/zaproxy#3683 - NPE in ExtensionAlertFilters
> alertFilters: clear filters on session changes

- src/org/zaproxy/zap/extension/pscanrulesBeta/CookieLooselyScopedScanner.java
- test/org/zaproxy/zap/extension/pscanrulesBeta/CookieLooselyScopedScannerUnitTest.java
Change CookieLooselyScopedScanner to verify that the cookie domain and
hostname have the minimum length required when checking if same domain.
Add tests to assert the correct behaviour (i.e. no exceptions).
Fix zaproxy/zaproxy#3713 - CookieLooselyScopedScanner:
ArrayIndexOutOfBoundsException
> pscanrulesBeta: fix exception with cookie scanner

- build/build.xml
Correct packaging of Passive scanner rules (alpha) add-on in all tasks,
some of the tasks didn't include all the required classes.
> pscanrulesAlpha: correct packaging in all tasks

- build/build.xml
- src/org/zaproxy/zap/extension/wappalyzer/ZapAddOn.xml
- src/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html
Updated github link in the Wappalyzer addon help content.
Rolled version in manifest file and updated changes section.
> Wappalyzer Update Help Content Link

- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
Bump version of the add-on and minimum ZAP version (to 2.6.0, latest),
it doesn't run correctly in 2.4.0 (missing commons-codec classes).
> pscanrulesAlpha: update minimum ZAP version

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
Change ExtensionWebSocket to focus the WebSockets tab just once, when
the first handshake is received.
Fix zaproxy/zaproxy#3747 - Websocket tab focuses on every handshake
message
> websocket: focus WebSockets tab just once

- src/org/zaproxy/zap/extension/ascanrulesAlpha/ProxyDisclosureScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/SourceCodeDisclosureFileInclusion.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
Change SourceCodeDisclosureFileInclusion to skip the scan if there's no
path to work with, preventing exceptions when handling it:
StringIndexOutOfBoundsException: String index out of range: -2
Change ProxyDisclosureScanner to properly build the URI when the path is
empty (i.e. add "/" instead of "null"), which would lead to wrong host
being requested, e.g. "example.comnullIAACS".
> ascanrulesAlpha: correct empty path handling

- src/org/zaproxy/zap/extension/importurls/ZapAddOn.xml
- src/org/zaproxy/zap/extension/importurls/resources/help/contents/importUrls.html
Help content updated to align with
https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsImporturlsImportUrls/_compare/8973b94%5E...8973b94
Manifest version rolled and changes element updated.
> Tweak ImportURLs Help Content

- build/build.xml
Change build.xml to use the status declared in the add-ons' manifest
(ZapAddOn.xml) when creating its file name. Allows add-ons of any status
to be in the same branch.
> build: use status declared in add-ons' manifest

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestZapUtils.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestAssignmentDialog.java
Change ZestAssignmentDialog and ZestZapUtils to properly convert
between labels and operations used in ZestAssignCalc, as it was using
the label as operation it was leading always to "Invalid operation".
> zest: use correct operation in calc assign

- src/org/zaproxy/zap/extension/jruby/files/scripts/templates/httpsender/HttpSender default template.rb
ported from python, works the same, even code in comments is changed and tested to work
https://github.com/zaproxy/zaproxy/issues/3009
> addedd HttpSender default template for ruby

- build/build.xml
- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/dialogs/ZestDialogManager.java
When more than one 'Assign variable to a form field' Node is below a RequestNode then the RequestNode is now is correctly determined.
> Bugfix in ZestScript Ui. 

- src/org/zaproxy/zap/extension/pscanrules/XContentTypeOptionsScanner.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- test/org/zaproxy/zap/extension/pscanrules/XContentTypeOptionScannerUnitTest.java
Change XContentTypeOptionsScanner to check if the header value is
present in a locale insensitive manner, in some locales it could lead to
an alert even if the header had the correct value.
> pscanrules: fix FP with X-Content-Type-Options

- test/org/zaproxy/zap/extension/ascanrulesBeta/ActiveScannerTest.java
Replace usage of org.testng.reporters.Files with Apache Commons IO
FileUtils class in ActiveScannerTest (FileUtils is already in use).
> Remove usage of org.testng class (beta)

- test/org/zaproxy/zap/extension/ascanrules/ActiveScannerTest.java
Replace usage of org.testng.reporters.Files with Apache Commons IO
FileUtils class in ActiveScannerTest (FileUtils is already in use).
> Remove usage of org.testng class

- src/org/zaproxy/zap/extension/zest/ZestZapRunner.java
Because the detection of a circular redirect happens even if url-parameters are modified.
> Allow circular redirects in ZestScriptRequests. 

- src/org/zaproxy/zap/extension/webdriverlinux/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdrivermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
Driver file updated via https://github.com/zaproxy/zap-libs/pull/8
Part of https://github.com/zaproxy/zaproxy/issues/3789
> Update webdriver add-ons for new versions

- src/org/zaproxy/zap/extension/ascanrulesAlpha/GetForPostScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
Added a new active scanner that repeats POST requests as GET requests and raises an informational alert if the responses are the same.
Help updated, i18n message keys added, manifest changes and ascanrule sections updated.
Tested with XAMPP, based on the following PHP page:
```php
<?php
if (isset($_REQUEST['name']))
//Displays the data that was received from the input box named name in the form
echo ($_REQUEST['name']);
?>
<hr>
<form action="test.php" method=POST>
Name:<br><input type="text" name="name"><br>
<input type="submit" value="Submit">
</form>
```
> Add GET for POST Scanner

- src/org/zaproxy/zap/extension/pscanrulesAlpha/ServerHeaderInfoLeakScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
In follow-up to https://github.com/zaproxy/zap-extensions/pull/879, recreate changes and apply at LOW threshold (more tolerant to false positives).
Updated manifest changes section, it does not appear that v16 of the add-on has been released yet.
Thanks @rain0r
> Server Header Info Leak LOW Threshold Alert

- src/org/zaproxy/zap/extension/domxss/ExtensionDomXSS.java
- src/org/zaproxy/zap/extension/domxss/TestDomXSS.java
- src/org/zaproxy/zap/extension/domxss/ZapAddOn.xml
- src/org/zaproxy/zap/extension/domxss/resources/Messages.properties
Change ExtensionDomXSS to depend on ExtensionSelenium and to dynamically
add/remove the active scanner (TestDomXSS), to ensure the extension is
always available to the scanner.
Change TestDomXSS to use ExtensionSelenium to obtain the WebDriver,
which uses the latest/correct WebDriver implementation to connect to
Firefox (geckodriver/marionette instead of xpi add-on). Also, set the
reason why the scanner was skipped when failed to use the browser.
Update changes, minimum Java/ZAP version and Selenium add-on version in
ZapAddOn.xml file.
Fix zaproxy/zaproxy#3396 - Enhance DOM XSS scanner addon to use Selenium
addon
Related to zaproxy/zaproxy#3509 - Update Selenium library to version 3.x
> domxss: use Selenium extension and add skip reason

- .travis.yml
Change .travis.yml to install the package ant-optional, required to run
the tests with newer dist trusty.
> Install ant-optional in Travis CI builds

- .travis.yml
Change .travis.yml to install the package ant-optional, required to run
the tests with newer dist trusty.
> Install ant-optional in Travis CI builds (beta)

- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
Change ExtensionSelenium to set the insecure cert capability as an
actual capability instead of as a preference of Firefox (broken when
changing for Selenium 3), also, set it to all browsers to ensure all of
them accept the insecure certs (e.g. ZAP's Root CA cert).
> selenium: correct insecure certs capability

- src/org/zaproxy/zap/extension/quickstart/launch/ExtensionQuickStartLaunch.java
- src/org/zaproxy/zap/extension/quickstart/launch/QuickStartLaunchParam.java
- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
It wasnt getting initialised correctly - it just defaulted to the first one every time.
It should now default initially to JxBrowser (if installed) and then to whichever browser was last launched (not just selected).
Note that the selenium changes arent actually needed, but they might be useful for other add-ons
> Fix the QuickStart default browser

- src/org/zaproxy/zap/extension/selenium/resources/help/contents/intro.html
Change Selenium help page to add the newer versions known to work with
bundled WebDrivers.
> selenium: update known working browser versions

- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
Change ExtensionSelenium to disable captive checks/requests to not flood
the AJAX Spider results (requests to "detectportal.firefox.com" are out
of scope, leading to high number (24) of them).
> selenium: disable Firefox captive checks/requests

- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/ui/HttpFuzzerResultsTableModel.java
Change HttpFuzzerResultsTableModel to use a custom history type for the
temporary messages created during fuzzing sessions, allowing to obtain
the messages through the ZAP API.
---
From talks in IRC channel.
> fuzz: use custom type for temporary HTTP messages

- build/build.xml
Change build.xml file to remove the debug property that's no longer
needed or actually used, it's being overridden to always compile with
debug info.
---
Syncs with other branches (#978 and #979).
> build: remove "unused" debug property (alpha)

- src/org/zaproxy/zap/extension/ascanrules/TestPathTraversal.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- test/org/zaproxy/zap/extension/ascanrules/TestPathTraversalUnitTest.java
Add a secondary check that ensures "etc" is not a substring of a larger word (for example: getChoice).
Add a unit test for the same.
Fixes zaproxy/zaproxy#3735
> Fix false positives in Path Traversal

- src/org/zaproxy/zap/extension/scripts/resources/help/contents/scripts.html
Update outdated links (Groovy and JavaDoc) and make all of them
hyperlinks (a tags), ZAP help can open them in an external browser.
> scripts: update links in help page

- src/org/zaproxy/zap/extension/ascanrulesBeta/HeartBleedActiveScanner.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
Change HeartBleedActiveScanner to notify when sending SSL/TLS msg/data.
Fix zaproxy/zaproxy#2425 - Change active scanners to notify that a
(non-HTTP) message was sent
> ascanrulesBeta: notify the msgs sent by Heartbleed

- src/org/zaproxy/zap/extension/pscanrulesBeta/CSRFCountermeasures.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
- test/org/zaproxy/zap/extension/pscanrulesBeta/CSRFCountermeasuresUnitTest.java
* Alerts are now raised on a per-form basis.
* Unit tests updated.
* Messages.properties resource message updated to align with new behavior.
* ZapAddOn.xml updated changes section.
Fixes zaproxy/zaproxy#3449
> Issue 3449 CSRFcountermeasures scanner handling multiple forms

- src/org/zaproxy/zap/extension/ascanrulesAlpha/SlackerCookieDetector.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
Change SlackerCookieDetector to:
- Leave the solution of the alert empty;
- Use StringBuilder (synchronisation provided by StringBuffer is not
required);
- Check if debug level is enabled before logging with string
concatenations;
- Add paragraphs to class JavaDoc (reads better when rendered);
- Check the cookie names in a locale independent manner.
Remove (now) unused solution ("N.a.") from Messages.properties file.
> ascanrulesAlpha: SlackerCookieDetector tweaks

- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderAPI.java
- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderDialog.java
- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParam.java
- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderResultsTableModel.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Address pending tasks that required newer version of ZAP (already
targeting 2.6.0).
Bump version and remove old changes from ZapAddOn.xml file.
> spiderAjax: address tasks

- src/org/zaproxy/zap/extension/scripts/SyntaxHighlightTextArea.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Change SyntaxHighlightTextArea to use the font selected in the options
or use default font of the component (e.g. monospaced).
> scripts: use selected font in script text area

- src/org/zaproxy/zap/extension/zest/ExtensionZest.java
- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
Change ExtensionZest to use the constant to check the engine name of the
script, which prevents NullPointerExceptions when the name is null
(which it is with Ruby scripts).
Bump version and remove old changes in ZapAddOn.xml file.
> zest: prevent NPE on engine name check

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/dialogs/ZestCookieDialog.java
- src/org/zaproxy/zap/extension/zest/resources/Messages.properties
Change ZestCookieDialog to validate that the cookie name is not empty.
Zest library requires a non-empty name:
IllegalArgumentException: Cookie name may not be blank
> zest: validate cookie name not empty

- src/org/zaproxy/zap/extension/pscanrulesAlpha/CrossDomainMisconfiguration.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/CrossDomainMisconfigurationUnitTest.java
Change CrossDomainMisconfiguration to use core constants for the headers
names.
Add tests to assert the expected behaviour of the scanner.
> pscanrulesAlpha: test CrossDomainMisconfiguration

- src/org/zaproxy/zap/extension/jxbrowser/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowser/ZapBrowserPanel.java
Adds a [console listener](https://www.teamdev.com/downloads/jxbrowser/javadoc/com/teamdev/jxbrowser/chromium/Browser.html#addConsoleListener-com.teamdev.jxbrowser.chromium.events.ConsoleListener-) to the jxbrowser instance for debugging.
Tested that adding an executeJavascript does log to the zap log as described in https://jxbrowser.support.teamdev.com/support/solutions/articles/9000013060-console-messages
e.g.
```
2017-09-19 11:55:44,231 [Browser Events Thread] INFO  ZapBrowserPanel - jxBrowser Console Event - Level: ERROR - Message: Error message
2017-09-19 11:55:44,231 [Browser Events Thread] INFO  ZapBrowserPanel - jxBrowser Console Event - Level: ERROR - Message: Error message
```
Note that it looks like getBrowser is being called four times (maybe once for each of the jxbrowser …
> Add console listener to jxBrowser

- src/org/zaproxy/zap/extension/jruby/ExtensionJruby.java
Change ExtensionJruby to not create the icon if the view is not
initialised.
Related to zaproxy/zaproxy#3798 - java.awt.Toolkit initialised in daemon
mode
> jruby: do not create the icon when in daemon

- src/org/zaproxy/zap/extension/jruby/files/scripts/templates/httpsender/HttpSender default template.rb
Update HttpSender default template to include the initiator ID of AJAX
Spider.
> jruby: update template to include AJAX spider ID

- src/org/zaproxy/zap/extension/zest/ExtensionZest.java
Change ExtensionZest to get the add-on directly through the extension's
method (the add-on is "now" set by core) and use a core constant (from
ExtensionScript).
> zest: minor tweaks in ExtensionZest

- .travis.yml
Change .travis.yml to remove the manual installation of the package
ant-optional, it's now (update 2017-09-06) installed by default.
> travis-ci: remove ant-optional workaround

- .travis.yml
Change .travis.yml to remove the manual installation of the package
ant-optional, it's now (update 2017-09-06) installed by default.
> travis-ci: remove ant-optional workaround (beta)

- .travis.yml
Change .travis.yml to remove the manual installation of the package
ant-optional, it's now (update 2017-09-06) installed by default.
> travis-ci: remove ant-optional workaround (alpha)

- src/org/zaproxy/zap/extension/jython/ExtensionJython.java
- src/org/zaproxy/zap/extension/jython/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jython/files/scripts/templates/httpsender/HttpSender default template.py
Change ExtensionJython to not create the icon if the view is not
initialised. (Related to zaproxy/zaproxy#3798 - java.awt.Toolkit
initialised in daemon mode)
Update HttpSender default template to include the initiator ID of AJAX
Spider.
> jython: change icon init and add new initiator

- src/org/zaproxy/zap/extension/jruby/ExtensionJruby.java
- src/org/zaproxy/zap/extension/jruby/JrubyEngineWrapper.java
- src/org/zaproxy/zap/extension/jruby/JrubyScriptWrapper.java
- src/org/zaproxy/zap/extension/jruby/ZapAddOn.xml
Change ExtensionJruby to unload the engine wrapper and convert the ruby
script wrappers back to core script wrappers.
Change JrubyScriptWrapper to pass-through all the changes to always have
the original wrapper in the expected state.
Change JrubyEngineWrapper to declare the default templates so that they
are removed when the engine wrapper is unloaded.
> jruby: dynamically unload the add-on

- src/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureCVE20121823.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
- test/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureCVE20121823UnitTest.java
* SourceCodeDisclosureCVE20121823 - Modified to ignore non-text responses.
* SourceCodeDisclosureCVE20121823UnitTest - Added unit test to validate handling of image type responses.
* ascanbeta.html - Added a note about response content type handling and reasoning.
* ZapAddOn.xml - Added changes element.
Fixes zaproxy/zaproxy#3846
> Issue 3846 FP Source Code Disclosure - CVE-2012-1823 on image content

- src/org/zaproxy/zap/extension/quickstart/QuickStartPanel.java
- src/org/zaproxy/zap/extension/quickstart/ZapAddOn.xml
- src/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- src/org/zaproxy/zap/extension/spiderAjax/SpiderPanel.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/ui/WebSocketPanel.java
Replace usage of java.awt.Event with KeyEvent, the former is deprecated
in Java 9, also, update to recommended (non-deprecated) masks (e.g.
SHIFT_DOWN_MASK instead of SHIFT_MASK).
Update changes (and bump version, where required) in ZapAddOn.xml files
of the corresponding add-ons.
Part of #2602 - Java 9
> Remove usage of java.awt.Event

- src/org/zaproxy/zap/extension/accessControl/ZapAddOn.xml
- src/org/zaproxy/zap/extension/accessControl/widgets/SiteNodeIcons.java
- src/org/zaproxy/zap/extension/accessControl/widgets/SiteTreeNodeCellRenderer.java
Change SiteNodeIcons and SiteTreeNodeCellRenderer (the latter class is
currently unused) to use the classes themselves to load the resources,
which ensures it's used the correct class loader to load the resource.
Reported in zaproxy/zaproxy#3934.
> accessControl: correct resource loading

- src/org/zaproxy/zap/extension/scripts/SyntaxHighlightTextArea.java
Change SyntaxHighlightTextArea to correct the detection of default font
set.
Fix zaproxy/zaproxy#3939 - Default font in script console is
non-monospaced on OSX
> scripts: correct default font used with macOS

- src/org/zaproxy/zap/extension/accessControl/ZapAddOn.xml
- src/org/zaproxy/zap/extension/accessControl/view/AccessControlResultsTableModel.java
- src/org/zaproxy/zap/extension/accessControl/view/AccessControlStatusPanel.java
Change the results table to use a highlighter/renderer for the icon of
the node results' column, otherwise it's copied the path of the icon
instead of the value it represents. Also, allow to select multiple rows.
> accessControl: correct data copied from results

- src/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Change ExtensionScriptsUI to do the work in the EDT when adding and
removing the script engines.
Fix zaproxy/zaproxy#3945 - GUI hang when installing/uninstalling
scripting add-ons
> scripts: address deadlock on engine changes

- src/org/zaproxy/zap/extension/bruteforce/BruteForcePanel.java
- src/org/zaproxy/zap/extension/bruteforce/ExtensionBruteForce.java
- src/org/zaproxy/zap/extension/fuzz/FuzzerPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/portscan/ExtensionPortScan.java
- src/org/zaproxy/zap/extension/treetools/PopupMenuTreeTools.java
- src/org/zaproxy/zap/extension/treetools/ZapAddOn.xml
Address compilation errors related to change in return type of method
TreeNode.children​() and depthFirstEnumeration​(), with Java 9 it returns
`Enumeration<TreeNode>`.
Update changes in ZapAddOn.xml file (where required).
> Address compilation errors with Java 9 (beta)

- src/org/zaproxy/zap/extension/ascanrules/TestSQLInjection.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
Address compilation error in ExtensionAjax caused by the change of the
return type of DefaultMutableTreeNode.children​().
Address deprecation warning in TestSQLInjection, replace the usage of
constructor Integer(String) with Integer.parseInt(String).
Update changes in ZapAddOn.xml file (of ascanrules, where required).
> Address remaining Java 9 compilation issues

- src/org/zaproxy/zap/extension/bruteforce/BruteForcePanel.java
- src/org/zaproxy/zap/extension/bruteforce/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java
- src/org/zaproxy/zap/extension/fuzz/FuzzersStatusPanel.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/plugnhack/ClientsPanel.java
- src/org/zaproxy/zap/extension/plugnhack/ZapAddOn.xml
- src/org/zaproxy/zap/extension/portscan/PortScanPanel.java
- src/org/zaproxy/zap/extension/portscan/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/ConsolePanel.java
- src/org/zaproxy/zap/extension/scripts/ScriptsListPanel.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/tokengen/TokenPanel.java
- src/org/zaproxy/zap/extension/tokengen/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestResultsPanel.java
Replace usage of java.awt.Event with KeyEvent, the former is deprecated
in Java 9, also, update to recommended (non-deprecated) masks (e.g.
SHIFT_DOWN_MASK instead of SHIFT_MASK).
Update changes (and bump version, where required) in ZapAddOn.xml files
of the corresponding add-ons.
> Remove usage of java.awt.Event (beta)

- src/org/zaproxy/zap/extension/scripts/CommandPanel.java
- src/org/zaproxy/zap/extension/scripts/OutputPanel.java
- src/org/zaproxy/zap/extension/scripts/ScriptsListPanel.java
- src/org/zaproxy/zap/extension/scripts/ZapPopupMenu.java
Change OutputPanel and CommandPanel to set a pop up menu, ZapPopupMenu,
into the text areas instead of listening for mouse clicks, as the former
works with mouse and keyboard.
Add a JPopupMenu (ZapPopupMenu) that invokes the main/core pop menu.
Change ScriptsListPanel to also use the new class, ZapPopupMenu.
These changes also address deprecation warnings with Java 9, by removing
usage of MouseEvent.getModifiers() and InputEvent.BUTTON3_MASK.
Related to zaproxy/zaproxy#2602 - Java 9
> scripts: use component pop up menus in text areas

- src/org/zaproxy/zap/extension/requester/RequesterPanel.java
- src/org/zaproxy/zap/extension/requester/ZapAddOn.xml
- src/org/zaproxy/zap/extension/tlsdebug/TlsDebugPanel.java
- src/org/zaproxy/zap/extension/tlsdebug/ZapAddOn.xml
- src/org/zaproxy/zap/extension/wappalyzer/TechPanel.java
Replace usage of java.awt.Event with KeyEvent, the former is deprecated
in Java 9, also, update to recommended (non-deprecated) masks (e.g.
SHIFT_DOWN_MASK instead of SHIFT_MASK).
Update changes and bump version in ZapAddOn.xml files (where required).
> Remove usage of java.awt.Event (alpha)

- src/org/zaproxy/zap/extension/accessControl/ContextAccessRulesManager.java
- src/org/zaproxy/zap/extension/accessControl/widgets/SiteTree.java
- src/org/zaproxy/zap/extension/accessControl/widgets/SiteTreeNode.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/SQLInjectionSQLite.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ViewStateDecoder.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/revisit/ExtensionRevisit.java
- src/org/zaproxy/zap/extension/revisit/ZapAddOn.xml
- src/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
- src/org/zaproxy/zap/extension/wappalyzer/ZapAddOn.xml
- test/org/zaproxy/zap/extension/sse/EventStreamProxyUnitTest.java
Address compilation errors related to change in return type of method
TreeNode.children​() and depthFirstEnumeration​(), with Java 9 it returns
`Enumeration<TreeNode>`.
Remove/replace usage of Integer and Long constructors.
Update changes and bump version in ZapAddOn.xml files (where required).
> Address compilation errors with Java 9 (alpha)

- src/org/zaproxy/zap/extension/tokengen/AnalyseTokensDialog.java
Change AnalyseTokensDialog to set a custom pop up menu into the text
areas instead of listening for mouse clicks, as the former works with
mouse and keyboard.
This change also addresses deprecation warnings with Java 9, by removing
usage of MouseEvent.getModifiers() and InputEvent.BUTTON3_MASK.
Related to zaproxy/zaproxy#2602 - Java 9
> tokengen: use component pop up menus in text areas

- src/org/zaproxy/zap/extension/zest/ZestZapRunner.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestRecordScriptDialog.java
Change ZestRecordScriptDialog and ZestZapRunner to correct script type
comparisons (they were using different types which would yield always
false).
> zest: correct script type comparisons

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestZapUtils.java
Change ZestZapUtils.calcOperationToLabel to handle null operation,
preventing a NullPointerException.
> zest: fix NPE on assign calc statement

- src/org/zaproxy/zap/extension/zest/ExtensionZest.java
- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
Change ExtensionZest.addBeforeRequest to not add one to the index when
pasting before the statement in a loop statement (otherwise it would add
it after).
> zest: correct dnd before stmt in loops

- src/org/zaproxy/zap/extension/zest/ZestTreeTransferHandler.java
Change ZestTreeTransferHandler.canImport to also check the parent
statement/node when checking if it's the same drop location, otherwise
it would prevent moving the statement if it occupied the same location
in the target (parent) statement/node.
> zest: correct drop location check

- src/org/zaproxy/zap/extension/zest/ZestTreeTransferHandler.java
Change ZestTreeTransferHandler.importData to skip the import if not a
drag-and-drop action, thus avoiding the exception when pasting the
statements with keyboard shortcut.
Related to zaproxy/zaproxy#2300 - Zest - Pasting statements with
keyboard shortcut leads to an exception
> zest: skip (keyboard) paste of statements

- src/org/zaproxy/zap/extension/zest/ZestTreeTransferHandler.java
Change ZestTreeTransferHandler to enable drag-and-drop after the last
statement (e.g. last statement of the script or in nested statements).
Required dnd events might not be generated with all Java versions, they
are with Java 9. (It also prevents an ArrayIndexOutOfBoundsException
while dragging the statements with Java 9.)
> zest: enable dnd after last statement

- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderAPI.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Change AjaxSpiderAPI to initialise all results, to prevent a NPE when
creating the full results response (when no scan was previously started
in daemon mode).
> spiderAjax: address internal error in API

- src/org/zaproxy/zap/extension/invoke/InvokeAppWorker.java
- src/org/zaproxy/zap/extension/invoke/ZapAddOn.xml
- src/org/zaproxy/zap/extension/invoke/resources/Messages.properties
Change InvokeAppWorker to report (to Output tab) and log when the
application fails to start because of an exception (previously it would
fail silently).
Related to zaproxy/zaproxy#3960 - Output from invoked application not
captured in macOS
> invoke: log/report when application fails to start

- src/org/zaproxy/zap/extension/accessControl/ZapAddOn.xml
- src/org/zaproxy/zap/extension/accessControl/view/AccessControlStatusPanel.java
Change AccessControlStatusPanel to convert the view index to model index
to display the correct message when the table is sorted.
> accessControl: display correct msg when sorting

- src/org/zaproxy/zap/extension/tokengen/AnalyseTokensDialog.java
- src/org/zaproxy/zap/extension/tokengen/ZapAddOn.xml
Change AnalyseTokensDialog to use the main ZAP window as its parent, it
avoids the dialogue from being hidden by main window when the focus is
changed.
> tokengen: set parent window to results dialogue

- test/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2UnitTest.java
- test/resources/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2UnitTest/InputInSpan.html
* TestCrossSiteScriptV2UnitTest.java > Removed `@Ignore` annotation on `shouldReportXssInReflectedUrl` since the requirement for core post 2.5.0 is fulfilled. Added `shouldReportXssInSpanContent` test method to
assert the behavior expected (as consistent with discussion in zaproxy/zaproxy#1222)
* InputInSpan.html > Resource file supporting the `shouldReportXssInSpanContent` test method.
> XSS In Span UnitTests

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestZapRunner.java
Change ZestZapRunner to use other plugin ID when creating alerts from
the failed actions. Also, address a TODO by using a core constant
(already targeting required core version).
Related to zaproxy/zaproxy#3963.
> zest: use custom plugin ID for fail actions

- src/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosure.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- test/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosureUnitTest.java
* BackupFileDisclosure.java > Updated to address FP.
* BackupFileDisclosureUnitTest.java > Added to test FP condition.
* ZapAddOn.xml > Added to change section.
Fixes zaproxy/zaproxy#3911
> Issue 3911 - Fix FP in Backup File Disclosure Scanner on 403s

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/Messages.properties
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/options.html
- src/org/zaproxy/zap/extension/websocket/ui/OptionsParamWebSocket.java
- src/org/zaproxy/zap/extension/websocket/ui/OptionsWebSocketPanel.java
Add a new option, enabled by default, that allows to control whether or
not the HTTP header Sec-WebSocket-Extensions should be removed from the
handshake messages. This disables any extensions that could prevent ZAP
from properly process the WebSocket messages sent/received.
Fix zaproxy/zaproxy#3324 - invalid utf-8 in payload when connecting
using a simple websocket client in firefox + chrome
> websocket: remove extensions header by default

- src/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Change ExtensionScriptsUI to not attempt to use the ExtenderScript if
failed to obtain it from the script (e.g. syntax errors) preventing the
NullPointerException.
> scripts: address NPE on script errors

- src/org/zaproxy/zap/extension/pscanrulesAlpha/TimestampDisclosureScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- test/org/zaproxy/zap/extension/pscanrulesAlpha/TimestampDisclosureScannerUnitTest.java
The following request would raise an alert:
```
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 978
```
because of the `max-age`.
> added STS to timestamp rule ignored headers

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/files/scripts/templates/websocketfuzzerprocessor/Fuzzer WebSocket Processor default template.js
Fix typos in the script template and convert the plain comment into
JSDoc.
> websocket: fix typos, use JSDoc in script template

- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/dialogs/NewScriptDialog.java
Correct state of Enabled checkbox when creating a script from templates,
it would be disabled even when the script type could be enabled.
> scripts: fix enabled checkbox with templates

- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/dialogs/LoadScriptDialog.java
- src/org/zaproxy/zap/extension/scripts/dialogs/NewScriptDialog.java
Change New and Load Script dialogues to show the types in alphabetical
order, easier to search the script types.
> scripts: show script types in alphabetical order

- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
Correct typo and update manifest (version & changes).
Fixes zaproxy/zaproxy#3997
> Issue 3997 - XCOLD Resource Message Typo

- src/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/HashDisclosureScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/TimestampDisclosureScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
Leave the attack field empty in alerts ASP.NET ViewState Disclosure,
ASP.NET ViewState Integrity, Hash Disclosure, and Timestamp Disclosure.
The attack is no longer needed to keep the alerts unique (per changes
done in zaproxy/zaproxy#2509 the evidence is enough to differentiate
them), also, it addresses the TODOs.
> pscanrulesAlpha: leave attack fields empty

- src/org/zaproxy/zap/extension/pscanrules/TestInfoSessionIdURL.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
Change TestInfoSessionIdURL to remove "N/A" value from the alert
parameter, if there's no parameter it should be left empty.
> pscanrules: remove N/A from alert parameter

- src/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/DirectoryBrowsingScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/HashDisclosureScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/TimestampDisclosureScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
Change the scanners to use the method toString() of the request/response
bodies instead of creating manually the String, which relies on the
system's charset (might not be correct, different from the one defined
in the HTTP header).
> pscanrulesAlpha: do not rely on system's charset

- src/org/zaproxy/zap/extension/ascanrules/TestSQLInjection.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- test/org/zaproxy/zap/extension/ascanrules/TestSQLInjectionUnitTest.java
__The third commit involves some additional changes that might be implemented.
This is what I'm talking about. I've implemented it for Check4 ONLY this time to show you the idea.__
Previously `unstripped` comparison is needed for the following case: 
```
$query=" SELECT * FROM users WHERE id = " . $_GET['id']; 
$result=mysqli_query($connection, $query); 
while($row= mysqli_fetch_assoc($result)){
echo "ID        : ".$row['id']."<br/>";
echo "User_name : ".$row['name']."<br/>";
}
```
where parameter gets reflected back after evaluation from database.
Unstripped output:
**HTML normal parmeter=2 output**
```
ID : 2 
User_name : richguy
```
**HTML modified parmeter=4-2 output**
```
ID : 2
User_name : richguy
```
Hence they are equal
But previous stripping concept:
On stripping Off 
**HTML …
> TestSQLInjection Modifications

- src/org/zaproxy/zap/extension/tokengen/TokenGenerator.java
- src/org/zaproxy/zap/extension/tokengen/ZapAddOn.xml
Change TokenGenerator to use a custom initiator ID, to differentiate its
requests from the active scanner.
--- 
Constant defined in zaproxy/zaproxy#4058 - Add initiator constant for Token Gen requests
> tokengen: use custom initiator ID in HttpSender

- src/org/zaproxy/zap/extension/openapi/resources/help/contents/openapi.html
Add the supported OpenAPI Specification versions to the help page.
> openapi: add versions supported to help page

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- src/org/zaproxy/zap/extension/websocket/ui/SessionExcludeFromWebSocket.java
Fix a NullPointerException during installation if the Session dialogue
was already initialised (caused by missing OptionsParamWebSocket, which
was not yet added to core).
> websocket: address npe during installation

- build/build.xml
For zaproxy/zaproxy#4032
Dont merge yet - we'll do that just before generating 2.7.0 in case
there are any last minute add-on releases required on 2.6.0
> Update to use java 8

- src/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
Remove Java 7 built-in scripts code from ExtensionScriptsUI, the add-on
now requires Java 8 (per ZAP 2.7.0 requirements). (No further changes
required, no built-in scripts were being installed for Java 7.)
> scripts: remove Java 7 built-in scripts code

- src/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
- src/org/zaproxy/zap/extension/scripts/InvokeScriptWithHttpMessageMenu.java
- src/org/zaproxy/zap/extension/scripts/InvokeScriptWithHttpMessagePopupMenu.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Change Invoke with Script pop up menus to extend HTTP Message container
menus, to invoke the scripts on the selected HTTP message(s) (instead of
the (first) HTTP message of the corresponding site node).
Rename pop up menus to reflect the new inheritance.
Fix zaproxy/zaproxy#4085 - Invoking with script invokes with wrong
message
> scripts: invoke script with selected HTTP messages

- src/org/zaproxy/zap/extension/bugtracker/ZapAddOn.xml
- src/org/zaproxy/zap/extension/bugtracker/resources/Messages.properties
Remove unused resource message (which had a typo, reported in Crowdin).
> bugtracker: remove unused resource message

- src/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
- test/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2UnitTest.java
Ignore testing the request if the method is PUT.
Update UnitTest to check the new behavior.
Fixes zaproxy/zaproxy#3979
> Fix Issue 3979 Reflected XSS in PUT Response

- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/files/scripts/templates/extender/Add api call.js
- src/org/zaproxy/zap/extension/scripts/files/scripts/templates/extender/Add history record menu.js
- src/org/zaproxy/zap/extension/scripts/files/scripts/templates/extender/Add toolbar button.js
- src/org/zaproxy/zap/extension/scripts/files/scripts/templates/extender/Add tools menu.js
- src/org/zaproxy/zap/extension/scripts/files/scripts/templates/extender/Copy as curl command menu.js
- src/org/zaproxy/zap/extension/scripts/files/scripts/templates/extender/Extender default template.js
Update extender JavaScript templates to Nashorn (e.g. remove println
workaround and other specific Rhino code).
Part of zaproxy/zaproxy#3470 - Move to using Java 8
> scripts: update extender templates to Java 8

- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/files/scripts/templates/extender/Add history record menu.js
Correct example extender script Add history record menu.js, by keeping a
reference to the view to be later used in the menu item. It was leading
to an error when triggering the menu item:
<eval>:16 ReferenceError: "helper" is not defined
> scripts: correct menu item extender template

- src/org/zaproxy/zap/extension/authstats/ExtensionAuthStats.java
- src/org/zaproxy/zap/extension/authstats/ZapAddOn.xml
- src/org/zaproxy/zap/extension/authstats/resources/help/contents/authStats.html
Change ExtensionAuthStats to check if the context has an authentication
method, in future ZAP versions the context might not have one. Also,
extract a method to reduce statement nesting.
Update help page to mention the new stat, that indicates the context
does not have the authentication method.
Part of zaproxy/zaproxy#2620 - Allow to add/remove authentication and
session management methods
> authstats: check if context has an auth method

- build/build.xml
Change build.xml file to deploy the wiki of the (new) bundled add-ons to
the core wiki.
> build: deploy wiki of bundled add-ons to core wiki

- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/dialogs/NewScriptDialog.java
Change NewScriptDialog to not show an empty choice if the selected
script engine requires a template (e.g. Zest engine).
> scripts: do not show empty choice if tmpl required

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/dialogs/ZestActionDialog.java
Change ZestActionDialog to check if the stand alone scripts available
have a file before using it, preventing the NullPointerException. The
NPE would happen when editing an action invoke with unsaved scripts.
> zest: fix NPE when editing action invoke

- src/org/zaproxy/zap/extension/openapi/ZapAddOn.xml
- src/org/zaproxy/zap/extension/openapi/generators/FormGenerator.java
Change FormGenerator to cope with null "in" value, as with RefParameter.
> openapi: fix NPE with RefParameter

- build/build.xml
Update build.xml file to build the wiki of JxBrowser add-on to
zap-core-help wiki, the add-on is bundled in ZAP by default (the wiki
was already being manually deployed there).
> jxbrowser: generate wiki to zap-core-help

- src/org/zaproxy/zap/extension/amf/ExtensionAMF.java
- src/org/zaproxy/zap/extension/amf/ZapAddOn.xml
Change ExtensionAMF to use the newer core method that allows to properly
remove (request) default view selectors.
Bump add-on and minimum ZAP version (to 2.7.0) and update changes in
ZapAddOn.xml file.
> amf: update for ZAP 2.7.0

- src/org/zaproxy/zap/extension/domxss/TestDomXSS.java
- src/org/zaproxy/zap/extension/domxss/ZapAddOn.xml
Change TestDomXSS to use the class ExtensionSelenium (instead of the
instance) to get the WebDriver (it's a static method).
> domxss: address compilation warning

- src/org/zaproxy/zap/extension/replacer/ReplacerParam.java
- src/org/zaproxy/zap/extension/replacer/ZapAddOn.xml
Change ReplacerParam to initialise the list of rules, to prevent a
NullPointerException during start up (caused by a request from
ExtensionQuickStartLaunch).
> replacer: fix NPE during start up

- src/org/zaproxy/zap/extension/ascanrulesBeta/Csrftokenscan.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
- test/org/zaproxy/zap/extension/ascanrulesBeta/CsrftokenscanUnitTest.java
Csrftokenscan - At HIGH threshold only check messages inScope.
ascanbeta.html - Added this detail to the help content.
ZapAddOn.xml - Version incremented and changes updated.
Related to zaproxy/zaproxy#1354
pscanrulesBeta will be similarly updated after https://github.com/zaproxy/zap-extensions/pull/1190 is accepted. (I'll add the fix tag in that forth coming PR.)
> ascanrulesBeta - Issue 1354

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/dialogs/ZestRequestDialog.java
Change ZestRequestDialog to allow to select all HTTP methods supported
(by Zest library).
> zest: allow to select more HTTP methods

- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderResultsTableModel.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Change AjaxSpiderResultsTableModel to not refresh the table entries by
default when handling alert events, to avoid performance issues if new
(minor) alert events are added.
> spiderAjax: do not refresh table by default

- test/org/zaproxy/zap/extension/ScannerTestUtils.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/ActiveScannerTest.java
- test/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/tagcreator/HttpResponseTagCreatorUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesBeta/CharsetMismatchScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesBeta/PassiveScannerTest.java
Update ActiveScannerTest, CharsetMismatchScannerUnitTest,
PassiveScannerTest, and ScannerTestUtils to use latest (non-deprecated)
core code.
Address unchecked warnings in HttpResponseTagCreatorUnitTest.
> Address compilation warns in beta test code

- src/org/zaproxy/zap/extension/quickstart/QuickStartPanel.java
- src/org/zaproxy/zap/extension/quickstart/ZapAddOn.xml
- src/org/zaproxy/zap/extension/quickstart/launch/ExtensionQuickStartLaunch.java
- src/org/zaproxy/zap/extension/quickstart/launch/QuickStartLaunchAPI.java
Change ExtensionQuickStartLaunch to use the API core method now that
the add-on is targeting 2.7.0. Set the name of the threads to be easier
to identify them.
Remove code no longer needed in QuickStartLaunchAPI per previous API
change.
Change QuickStartPanel to set the state that indicates the panel is
shown by default (instead of overriding the method).
> quickstart: update code to ZAP 2.7.0

- src/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Change ExtensionAjax to add/hook the session listener even if there's no
view, it should also be executed in daemon mode to reset the API scan.
Update changes in ZapAddOn.xml file (remove the old change, no longer
relevant).
Fix zaproxy/zaproxy#4163 - ajaxSpider.number_of_results is not cleared
when a new session is created
> spiderAjax: reset API scan also in daemon mode

- src/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
- test/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2UnitTest.java
- test/resources/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2UnitTest/example.json
* TestCrossSiteScriptV2 - Add handling for simple XSS in JSON responses.
* Messages.properties - Add supporting keys and messages.
* ascanrules.html - Add relevant note to the help content.
* TestCrossSiteScriptV2UnitTest - Add unit test to cover the new behavior.
* example.json - New resource file to support the unit test.
* ZapAddOn.xml - Updated changes section.
Fixes zaproxy/zaproxy#3978
> Issue 3978 - Handle reflected XSS in JSON response

- src/org/zaproxy/zap/extension/quickstart/AttackThread.java
- src/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
- src/org/zaproxy/zap/extension/quickstart/ZapAddOn.xml
Change ExtensionQuickStart to stop the scan if the session is changed.
Change AttackThread to keep a reference to the spider and active scans,
to prevent NullPointerException(s) when the scans are stopped and
removed because of session changes.
> quickstart: stop the quick scan on session changes

- src/org/zaproxy/zap/extension/pscanrulesBeta/CSRFCountermeasures.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
- test/org/zaproxy/zap/extension/pscanrulesBeta/CSRFCountermeasuresUnitTest.java
CSRFCountermeasures - Add alert threshold and scope check.
CSRFCountermeasuresUnitTest - Updated to test the new behavior.
pscanbeta.html - Updated help content.
ZapAddOn.xml - Updated changes section.
Fixes zaproxy/zaproxy#1354
> pscanBeta - CSRFCountermessures High Threshold Only In Scope

- src/org/zaproxy/zap/extension/accessControl/ZapAddOn.xml
- src/org/zaproxy/zap/extension/accessControl/view/AccessControlStatusPanel.java
Change AccessControlStatusPanel to use core method to display the HTTP
messages instead of manually setting up the request/response panels.
> accessControl: use core method to display messages

- src/org/zaproxy/zap/extension/zest/ExtensionZest.java
Change ExtensionZest to use core method to display the HTTP messages
instead of manually setting up the request/response panels.
> zest: use core method to display messages

- build/build.xml
- src/org/zaproxy/zap/extension/domxss/TestDomXSS.java
- src/org/zaproxy/zap/extension/domxss/ZapAddOn.xml
- src/org/zaproxy/zap/extension/domxss/resources/help/contents/domxss.html
* TestDomXSS.java > Added polyglot payload. Updated payloads per attack strength (+1) [per
https://github.com/zaproxy/zap-extensions/wiki/AddOnsBeta the adjusted numbers are still below the guideline].
* domxss.html - Updated details of payloads per strength.
* ZapAddOn.xml - Updated changes section.
* build.xml - Added `deploy-domxss-without-help-indexes` task.
Fixes zaproxy/zaproxy#2322
> Issue 2322 Add XSS Polyglot

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/ui/httppanel/models/StringWebSocketPanelViewModel.java
ensure switching between views in resender does not edit messages in some special cases
closes zaproxy/zaproxy#4108
> Do not overwrite websocket messages with encoding error messages

- src/org/zaproxy/zap/extension/pscanrulesBeta/InformationDisclosureDebugErrors.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
- test/org/zaproxy/zap/extension/pscanrulesBeta/InformationDisclosureDebugErrorsUnitTest.java
InformationDisclosureDebugErrors.java > Updated to ignore javascript responses at medium and high thresholds.
InformationDisclosureDebugErrorsUnitTest.java > Updated with tests for the new behavior.
pscanbeta.html > Added a note to help content.
Fixes zaproxy/zaproxy#4210
> Fix Issue 4210 Error Disclosure False Positive

- src/org/zaproxy/zap/extension/ascanrules/FormatString.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
FormatString.java > Add a check after the submission of the initial modified message, if the response is 500 then bail (since further manipulation is also likely to result in a 500 and thus false positive).
Fixes zaproxy/zaproxy#4211
> Issue 4211 - Fix FormatString ascan false positive

- src/org/zaproxy/zap/extension/exportreport/ExtensionExportReport.java
- src/org/zaproxy/zap/extension/exportreport/ZapAddOn.xml
Change ExtensionExportReport to hook the API implementor instead of
adding it "manually" to ensure it's (automatically) removed when
uninstalled.
Bump version, update minimum ZAP version (to 2.7.0) and replace changes
in ZapAddOn.xml file.
> exportreport: unload API when uninstalling

- src/org/zaproxy/zap/extension/highlighter/ExtensionHighlighter.java
- src/org/zaproxy/zap/extension/highlighter/ZapAddOn.xml
Change ExtensionHighlighter to not enable the help for the Highlighter
panel, the help is not yet available. Also, remove unused and commented
code.
> highlighter: fix exception in Highlighter panel

- src/org/zaproxy/zap/extension/scripts/autocomplete/ScriptAutoCompleteMenu.java
Change ScriptAutoCompleteMenu to use the commented code targeting Java
8, the add-on already requires ZAP 2.7.0 which requires Java 8. Also,
tweak to append char instead of string when creating the method
signature.
> scripts: use Java 8 method in auto complete

- build/build.xml
Change build.xml to use the status declared in the add-ons' manifest
(ZapAddOn.xml) when creating its file name.
> build: use status declared by add-ons (alpha)

- src/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
- src/org/zaproxy/zap/extension/openapi/OpenApiSpider.java
- src/org/zaproxy/zap/extension/openapi/ZapAddOn.xml
- src/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverter.java
- src/org/zaproxy/zap/extension/openapi/generators/PathGenerator.java
- test/org/zaproxy/zap/extension/openapi/OpenApiUnitTest.java
- test/org/zaproxy/zap/extension/openapi/ServerBasedTest.java
- test/resources/org/zaproxy/zap/extension/openapi/PetStore_defn_no_host.json
- test/resources/org/zaproxy/zap/extension/openapi/PetStore_defn_no_schemes.json
Change ExtensionOpenApi and OpenApiSpider to default to host:port of the
request URI, used to obtain the specification.
Change SwaggerConverter to allow to specify a default host, used if not
specified in the specification.
Change PathGenerator to require a host instead of obtaining it from
Swagger class (which might not exist).
Update tests to assert the expected behaviour when the scheme or the
host are not specified in the specification. Also, refactor the tests to
reduce code duplication (extract a server handler).
Fix zaproxy/zaproxy#4271 - OpenAPI add-on should fallback to host of URI
> openapi: fallback to host of request URI

- src/org/zaproxy/zap/extension/webdriverlinux/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdrivermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
Update ChromeDriver to v2.35.
Bump versions and update changes in ZapAddOn.xml files.
Fix zaproxy/zaproxy#4256 - New ChromeDriver - 2.35
> webdrivers: update ChromeDriver to v2.35

- src/org/zaproxy/zap/extension/jython/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jython/files/scripts/templates/passive/Passive default template.py
Change Passive default template.py to implement the new function
available in 2.7.0 that allows to choose which types of message are
passive scanned. Also, tweak/add docstrings.
Related to zaproxy/zaproxy#3476 - Allow passive rules to choose the type
of msgs
> jython: update template of passive rule

- src/org/zaproxy/zap/extension/webdriverlinux/WebdriverDownload.java
Change WebdriverDownload to no longer download the ChromeDriver 32bits,
that's no longer available.
Related to #1274 - webdrivers: update ChromeDriver to v2.35
> webdriverlinux: rm download of ChromeDriver 32bits

- src/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Change ExtensionScriptsUI to handle the (UI part of) add/remove events
in the EDT to avoid threading issues (like the GUI freeze).
Fix zaproxy/zaproxy#4302 - GUI freezes while adding/removing scripts
through the API
> scripts: address EDT deadlock

- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
Change ExtensionSelenium to declare that it supports all DB types (no
custom tables added).
> selenium: enable extension for all DB types

- src/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
- src/org/zaproxy/zap/extension/quickstart/ZapAddOn.xml
- src/org/zaproxy/zap/extension/quickstart/launch/ExtensionQuickStartLaunch.java
- src/org/zaproxy/zap/extension/quickstart/pnh/ExtensionQuickStartPnH.java
Change all extensions to declare that they supports all DB types (no
custom tables added).
> quickstart: enable extensions for all DB types

- src/org/zaproxy/zap/extension/scripts/ScriptsListPanel.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/resources/Messages.properties
Change ScriptsListPanel to show a dialogue prompting for a charset if
the default charsets (UTF-8 and JVM default) don't properly decode the
script.
Fix zaproxy/zaproxy#3383 - Prompt the user for a charset when failed to
read the script file
> scripts: prompt for charset on load (if needed)

- src/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/ExtensionHttpFuzzer.java
Change all extensions (main and HTTP) to declare that they supports all
DB types (no custom tables added).
> fuzz: enable extensions for all DB types

- src/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
- src/org/zaproxy/zap/extension/scripts/InvokeScriptWithHttpMessageMenu.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Change InvokeScriptWithHttpMessageMenu to use a new thread to execute
the targeted script, to not block the EDT.
Change ExtensionScriptsUI to execute UI related statements, done before
executing the targeted script, in the EDT to avoid threading issues.
> scripts: do not run targeted scripts in EDT

- src/org/zaproxy/zap/extension/scripts/CommandPanel.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Change CommandPanel to clear the highlighting syntax when a non-script
node is selected.
> scripts: clear syntax on non-script node selection

- src/org/zaproxy/zap/extension/jython/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jython/files/scripts/templates/variant/Input Vector default template.py
Add default template for Script Input Vector.
Update the changes and declare the template in ZapAddOn.xml file.
Part of zaproxy/zaproxy#3009 - Add missing templates for core script
types to Python/Ruby scripting add-ons
> jython: add variant template

- src/org/zaproxy/zap/extension/ascanrules/TestServerSideInclude.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- Include `DOTALL` in the regex detection patterns.
- Pre-check the original response against the detection patterns to reduce false positives.
- Updated addon manifest (rolled version and updated changes section)
Fixes zaproxy/zaproxy#1366
> Fix Issue 1366 - Adjust detection pattern & pre-check original response

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestResultsPanel.java
- src/org/zaproxy/zap/extension/zest/resources/Messages.properties
Change ZestResultsPanel to show a button that clears the results of an
executed script.
> zest: allow to clear the Zest panel

- src/org/zaproxy/zap/extension/ascanrules/CommandInjectionPlugin.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
Before sending a new message with the injection pre-check `getBaseMsg()` for the detection pattern, if it's found skip (continue) to the next pattern. Thus reducing false positives.
Fixes zaproxy/zaproxy#4230
> Fix Issue 4230 - Pre-check the original message against the detection

- src/org/zaproxy/zap/extension/ascanrules/TestPathTraversal.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- test/org/zaproxy/zap/extension/ascanrules/TestPathTraversalUnitTest.java
Change TestPathTraversal to skip the messages which already have the
evidence of a successful attack present in the response.
Add test to assert the new behaviour.
Fix zaproxy/zaproxy#4168.
> ascanrules: path traversal, skip msg with evidence

- src/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- test/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2UnitTest.java
- test/resources/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2UnitTest/InputInsideDiv.html
TestCrossSiteScriptV2 > Add handling for img onerror injections when poor quality input filtering is in play.
TestCrossSiteScriptV2UnitTest > Add new unit test.
InputInsideDiv.html > Supports the new unit test.
ZapAddOn.xml > Rolled version and updated changes.
Fixes zaproxy/zaproxy#1852
> Fix Issue 1852 False Negative

- src/org/zaproxy/zap/extension/simpleExample/ZapAddOn.xml
- src/org/zaproxy/zap/extension/simpleExample/resources/help/contents/about.html
- src/org/zaproxy/zap/extension/simpleExample/resources/help/map.jhm
- src/org/zaproxy/zap/extension/simpleExample/resources/help/toc.xml
This is proposed as a standard for all add-ons.
The structure should be standard but can be extended, eg to link to author's home pages etc.
We dont have to change them all to use it right now but can gradually add such pages over time as add-ons are updated.
I think it will help people see what changes have been made and find the source code more easily.
I also think we should have standard help pages for API and cmdline support, but this addon doesnt have either ;)
Note that the about page is deliberately not in the index as I dont think that will be so useful, but happy to be convinced otherwise.
> Added example 'about' help page

- build/build.xml
- src/org/zaproxy/zap/extension/jsonview/ExtensionHttpPanelJsonView.java
- src/org/zaproxy/zap/extension/jsonview/HttpPanelJsonArea.java
- src/org/zaproxy/zap/extension/jsonview/HttpPanelJsonView.java
- src/org/zaproxy/zap/extension/jsonview/README.md
- src/org/zaproxy/zap/extension/jsonview/ZapAddOn.xml
I keep copying stuff to jq while doing API assessments and decided to make my life easier with this addon. Useful for manual testing of JSON APIs of mobile applications, especially when responses grow into a few kilobytes.
Tested mainly this week during an assessment, and a few issues already fixed after that. Changing between view methods (split and combined), breakpoints, repeating messages, unloading the plugin, and default view selection all seem to work without throwing exceptions.
> JSON view with basic features: indenting, highlighting, folding

- src/org/zaproxy/zap/extension/pscanrulesAlpha/ImageLocationScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
Change ImageLocationScanner to also scan "hidden" (proxied) images,
removing the requirement to enable another option to effectively use the
scanner, if the scanner is enabled it should scan.
Update help page to remove the requirement, also, update the name of the
scanner to reflect the latest name.
> pscanrulesAlpha: change ILS to scan "hidden" images

- src/org/zaproxy/zap/extension/websocket/WebSocketProxyV13.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
Tested to ensure Websocket message editing works manually as well as with Websocket sender scripts (zap-extensions/pull/971) and extender scripts.
> fix #4149 as suggested in comments

- src/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java
- src/org/zaproxy/zap/extension/alertFilters/ZapAddOn.xml
Change ExtensionAlertFilters to always discard the alert filter configs
when the context is deleted.
Fix zaproxy/zaproxy#4405 - NPE with Context Alert Filters in daemon mode
> alertFilters: fix NPE in daemon mode

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- src/org/zaproxy/zap/extension/websocket/WebSocketSenderScript.java
- src/org/zaproxy/zap/extension/websocket/WebSocketSenderScriptHelper.java
- src/org/zaproxy/zap/extension/websocket/WebSocketSenderScriptListener.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/files/scripts/templates/websocketsender/WebsocketSender Default Template.js
- src/org/zaproxy/zap/extension/websocket/resources/Messages.properties
This adds a feature to the websocket extension that provides a way to edit messages by calling scripts. The new WebSocket Sender script interface practically exposes the `onMessageFrame` to the user so that quick processing, logging or modification of WebSocket messages can be performed more easily.
This might not be a commonly wanted functionality, but even if this is not merged, I'd gladly take some comments with later contributions in mind.
> Add WebSocket Sender script interface

- src/org/zaproxy/zap/extension/help_fil_PH/ZapAddOn.xml
- src/org/zaproxy/zap/extension/help_id_ID/ZapAddOn.xml
- src/org/zaproxy/zap/extension/help_zh_CN/ZapAddOn.xml
Tweak the names of the help add-ons (fil_PH, id_ID, and zh_CN) so that
all of them use the same pattern ("Help - \<language>").
> help: tweak add-on names

- src/org/zaproxy/zap/extension/pscanrulesAlpha/BlankLinkTargetScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- test/org/zaproxy/zap/extension/pscanrulesAlpha/BlankLinkTargetScannerUnitTest.java
Change BlankLinkTargetScanner to handle the absence of href attribute in
the elements a and area, preventing a NullPointerException.
Add test to assert the expected behaviour.
(Spotted while working on #1377)
> pscanrulesAlpha: fix NPE in blank link scanner

- src/org/zaproxy/zap/extension/pscanrulesAlpha/UsernameIdorScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
Change UsernameIdorScanner to check if the HTTP Sessions extension is
enabled (non-null) before using it, preventing a NullPointerException.
> pscanrulesAlpha: fix NPE in username hash scanner

- src/org/zaproxy/zap/extension/pscanrulesAlpha/UsernameIdorScanner.java
Change UsernameIdorScanner to assign the extension when obtaining it,
with the previous change (#1395) it no longer assigned the extension
(thus causing a NPE when it was enabled), also, the extension is Users
not HTTP Sessions...
Sorry for the mess up.
> pscanrulesAlpha: properly fix NPE in username hash

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
Change ExtensionWebSocket to also include the exception's stack trace
when logging errors during the channel setup. Gives more information
about the actual issue, instead of just:
Adding WebSockets channel failed due to: 'class NullPointerException'
null
> websocket: include stack trace in channel setup

- src/org/zaproxy/zap/extension/replacer/ZapAddOn.xml
- src/org/zaproxy/zap/extension/replacer/resources/help/contents/replacer.html
Remove reference to an inexistent option/checkbox, the Initiators tab is
always shown.
> replacer: tweak help page

- src/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- test/org/zaproxy/zap/extension/ascanrules/ActiveScannerTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2UnitTest.java
- TestCrossSiteScriptV2 - Updated with new logic to check for double decoded injections. Also made a constant to represent and reuse a simple script alert injection.
- TestCrossSiteScriptV2 - Updated with new unit tests to cover the new check when GET and POST (one test assets that other input variants are ignored).
- ActiveScannerTest - Expose scannerParams so that unit tests can set specific input variants.
- ZapAddOn.xml - Add to changes section, and made a slight tweak of the existing changes message (for Issue 1852).
Fixes zaproxy/zaproxy#1640
> Fix Issue 1640 False Negative on Double Encoding

- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
Remove redundant EL injection entry. ELi scanner has moved to beta
https://github.com/zaproxy/zap-extensions/blob/e8a0706d34e060daede4426b55918d14ee2da241/src/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html#L30-L33
Update manifest.
> Activescan Alpha help cleanup

- src/org/zaproxy/zap/extension/ascanrules/TestSQLInjection.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
TestSQLInjection > Add the necessary error string to the MySQL, MSSQL, and GenericRDBMS sections since it applies to various products.
ZapAddOn.xml > Update changes section.
Fixes zaproxy/zaproxy#2290
> Fix 2290 - SQLi False Negative

- src/org/zaproxy/zap/extension/reveal/ExtensionReveal.java
- src/org/zaproxy/zap/extension/reveal/ZapAddOn.xml
- test/org/zaproxy/zap/extension/pscanrules/PassiveScannerTest.java
Change ExtensionReveal and PassiveScannerTest to just use the response
body when instantiating the Source, the header is not required (body
already using the expected charset).
Related to zaproxy/zaproxy#4487.
> Normalise Source instantiations

- src/org/zaproxy/zap/extension/domxss/TestDomXSS.java
- src/org/zaproxy/zap/extension/domxss/ZapAddOn.xml
- src/org/zaproxy/zap/extension/domxss/resources/help/contents/about.html
- src/org/zaproxy/zap/extension/domxss/resources/help/contents/domxss.html
- src/org/zaproxy/zap/extension/domxss/resources/help/map.jhm
- src/org/zaproxy/zap/extension/domxss/resources/help/toc.xml
- TestDomXSS - Changed to AbstractAppParamPlugin and added functionality to handle param injection attempts.
- ZapAddOn.xml - Rolled version and updated changes section.
- about.html - Added.
- domxss.html - Updated to clarify implications of strength settings and URL fragment vs. parameter injections.
Fixes zaproxy/zaproxy#2917
> Issue 2917 - Allow DOMXSS to target URL params

- src/org/zaproxy/zap/extension/viewstate/ViewStateModel.java
- src/org/zaproxy/zap/extension/viewstate/ZapAddOn.xml
- test/org/zaproxy/zap/extension/pscanrulesAlpha/PassiveScannerTest.java
Change instantiations of Source class to only use the response body, the
header is not required, the body is already using the expected charset.
Bump version and update changes in ZapAddOn.xml file (viewstate).
Related to zaproxy/zaproxy#4487.
> Normalise Source instantiations (alpha)

- src/org/zaproxy/zap/extension/webdriverlinux/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdrivermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
Update geckodriver to v0.20.0.
---
Depends on zaproxy/zap-libs#15.
> webdrivers: update geckodriver to v0.20.0

- src/org/zaproxy/zap/extension/webdriverlinux/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdrivermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
Update ChromeDriver to v2.36.
Fix zaproxy/zaproxy#4506 - ChromeDriver 2.36 released
---
Depends on zaproxy/zap-libs#16.
> webdrivers: update ChromeDriver to v2.36

- src/org/zaproxy/zap/extension/websocket/WebSocketAPI.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
Change WebSocketAPI to remove and unregister the event consumer when the
channel is closed, no longer needs to be notified.
Update changes in ZapAddOn.xml and about.html.
> websocket: remove event consumer if channel closed

- src/org/zaproxy/zap/extension/httpsinfo/ExtensionHttpsInfo.java
This minor change changes the tab close functionality so that tabs are actually removed not just hidden. As this is related to the previous PR I have not included any further "changes" in the manifest.
I decided to go ahead with this changes as the 5.1.0beta integration has been stalled due to some performance issues that I've had to go back to the author with and am now waiting on a new build.
> HttpsInfo UI Tweak

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestResultsPanel.java
- src/org/zaproxy/zap/extension/zest/resources/Messages.properties
Add a button to Zest panel that opens the Zest options panel.
> zest: allow to open the options through zest panel

- src/org/zaproxy/zap/extension/replacer/ReplacerParamRule.java
- src/org/zaproxy/zap/extension/replacer/ZapAddOn.xml
Change ReplacerParamRule to always return false when checking if the
rule applies to CFU messages, to not inadvertently break the check for
updates.
---
From a thread in the mailing list where a replacer rule was breaking the check for updates.
> replacer: ignore CFU messages

- src/org/zaproxy/zap/extension/replacer/ReplaceRuleAddDialog.java
- src/org/zaproxy/zap/extension/replacer/ZapAddOn.xml
- src/org/zaproxy/zap/extension/replacer/resources/Messages.properties
Allow to explicitly select token generator messages.
> replacer: allow to select token gen messages

- src/org/zaproxy/zap/extension/importLogFiles/ExtensionImportLogFiles.java
- src/org/zaproxy/zap/extension/importLogFiles/ImportLogAPI.java
- src/org/zaproxy/zap/extension/importLogFiles/ZapAddOn.xml
- src/org/zaproxy/zap/extension/importLogFiles/resources/Messages.properties
Internationalise the strings shown when choosing the log type and file.
Replace the strings used for the log type with an enum.
> importLogFiles: i18n changes

- src/org/zaproxy/zap/extension/accessControl/ExtensionAccessControl.java
- src/org/zaproxy/zap/extension/accessControl/ZapAddOn.xml
- src/org/zaproxy/zap/extension/accessControl/view/AccessControlStatusPanel.java
- src/org/zaproxy/zap/extension/accessControl/view/ContextAccessControlPanel.java
Change ExtensionAccessControl to:
- Hook the ContextDataFactory and ContextPanelFactory, to get them
automatically removed when unloaded;
- Unload the status/context panels and close the dialogue when the
add-on is unloaded;
- Unload the context panels when the context(s) are discard;
- Declare that it can be unloaded.
Change AccessControlStatusPanel to also reset the panel when unloaded.
Change ContextAccessControlPanel to unload the users combo box.
Fix zaproxy/zaproxy#2380 - Dynamically unload "Access Control Testing"
add-on
> accessControl: dynamically unload the add-on

- src/org/zaproxy/zap/extension/accessControl/ExtensionAccessControl.java
- src/org/zaproxy/zap/extension/accessControl/ZapAddOn.xml
- src/org/zaproxy/zap/extension/accessControl/resources/Messages.properties
Change ExtensionAccessControl to report the running tests so that the
user is informed when changing the session or uninstalling the add-on.
> accessControl: inform of running tests

- src/org/zaproxy/zap/extension/ascanrulesAlpha/SlackerCookieDetector.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/TestUserAgent.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
Change SlackerCookieDetector and TestUserAgent to not resend the "base"
message (for the latter scanner it was a new message), it should not be
modified and it's no longer needed (the base message is now guaranteed
to have response).
Related to zaproxy/zaproxy#1964 - ZAP should ensure response in base
message before passing them to scanners
> ascanrulesAlpha: do not resend "base" message

- src/org/zaproxy/zap/extension/reveal/ExtensionReveal.java
- src/org/zaproxy/zap/extension/reveal/ZapAddOn.xml
- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
- src/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Change ExtensionAjax, ExtensionReveal, and ExtensionSelenium to hook the
APIs instead of adding them through the API singleton, it avoids the
need to manually unload them. Also, hook tool bar components in
ExtensionReveal. For ExtensionReveal and ExtensionSelenium it allows to
completely remove the unload method.
Bump version, update changes and minimum ZAP version in ZapAddOn.xml
files, where needed.
Related to zaproxy/zaproxy#2785 - Allow to hook ApiImplementor
> Add APIs through the ExtensionHook

- src/org/zaproxy/zap/extension/importurls/ExtensionImportUrls.java
- src/org/zaproxy/zap/extension/importurls/ZapAddOn.xml
- src/org/zaproxy/zap/extension/plugnhack/ExtensionPlugNHack.java
Change ExtensionImportUrls and ExtensionPlugNHack to hook the APIs
instead of adding them through the API singleton, it avoids the need to
manually unload them.
For ExtensionImportUrls it allows to completely remove the unload method
(the tool menu item was already being hooked).
Bump version and update changes in ZapAddOn.xml file, where needed.
Related to zaproxy/zaproxy#2785 - Allow to hook ApiImplementor
> Add APIs through the ExtensionHook (beta)

- src/org/zaproxy/zap/extension/importLogFiles/ExtensionImportLogFiles.java
- src/org/zaproxy/zap/extension/importLogFiles/ZapAddOn.xml
- src/org/zaproxy/zap/extension/revisit/ExtensionRevisit.java
- src/org/zaproxy/zap/extension/soap/ExtensionImportWSDL.java
- src/org/zaproxy/zap/extension/soap/ZapAddOn.xml
Change ExtensionImportLogFiles, ExtensionRevisit, and
ExtensionImportWSDL to hook the APIs instead of adding them through the
API singleton, it avoids the need to manually unload them.
For ExtensionImportLogFiles it allows to completely remove the unload
method.
Update minimum ZAP version in ZapAddOn.xml files, where needed.
Related to zaproxy/zaproxy#2785 - Allow to hook ApiImplementor
> Add APIs through the ExtensionHook (alpha)

- src/org/zaproxy/zap/extension/tokengen/ExtensionTokenGen.java
- src/org/zaproxy/zap/extension/tokengen/ZapAddOn.xml
- src/org/zaproxy/zap/extension/tokengen/resources/Messages.properties
Change ExtensionTokenGen to report the running test so that the user is
informed when changing the session or uninstalling the add-on.
> tokengen: inform of running test

- src/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosure.java
Remove check no longer needed in BackupFileDisclosure, which compared
to a 0 status code (i.e. an empty response, which no longer happens).
Related to zaproxy/zaproxy#1964 - ZAP should ensure response in base
message before passing them to scanners
> ascanrulesBeta: remove unnecessary check

- src/org/zaproxy/zap/extension/tokengen/ExtensionTokenGen.java
- src/org/zaproxy/zap/extension/tokengen/TokenGenerator.java
- src/org/zaproxy/zap/extension/tokengen/TokenOptionsPanel.java
- src/org/zaproxy/zap/extension/tokengen/TokenParam.java
- src/org/zaproxy/zap/extension/tokengen/ZapAddOn.xml
- src/org/zaproxy/zap/extension/tokengen/resources/Messages.properties
- src/org/zaproxy/zap/extension/tokengen/resources/help/contents/options.html
Add a new option (in options panel) that allows to configure the time
(in milliseconds) to wait before sending each request.
Split from #1147.
---
Note that I changed the default to 0ms (instead of the suggested 51ms) to keep the same behaviour (also, 51ms * 20k reqs = +17min).
The option was added to main Options panel instead of the Generate Tokens dialogue (as there's already another option), we can change the latter dialogue to have an advanced tab (like Spider, Active Scan) to tweak the extra options.
> tokengen: allow to delay the requests

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/payloads/generator/RegexPayloadGenerator.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/RegexPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
Instead of having generated payloads in order like this:
Now you can get random payloads matching your regex, but they may be not unique:
> Possibility to enforce a random order in the RegexPayloadGenerator

- src/org/zaproxy/zap/extension/fuzz/payloads/generator/RegexPayloadGenerator.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/RegexPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
Change RegexPayloadGenerator to take into account the random state when
calculating the number of payloads that are generated (with random it
generates into the limit specified).
Change RegexPayloadGeneratorUIHandler to prevent setting the max/limit
to 0 when random, as that prevents the generation of any payload. Also,
take into account the random state when calculating the maximum number
of payloads that should be persisted and when previewing the payloads.
> fuzz: correct payload count for random regex

- src/org/zaproxy/zap/extension/pscanrulesAlpha/UserControlledHTMLAttributesScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- test/org/zaproxy/zap/extension/cspscanner/ContentSecurityPolicyScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/DirectoryBrowsingScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/InsecureFormLoadScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/InsecureFormPostScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/PassiveScannerTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/RetrievedFromCacheScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/ServerHeaderInfoLeakScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/StrictTransportSecurityScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/UserControlledCharsetScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/UserControlledCookieScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/UserControlledHTMLAttributesScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/UserControlledJavascriptEventScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/UserControlledOpenRedirectScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/XBackendServerInformationLeakUnitTest.java
- test/org/zaproxy/zap/extension/pscanrulesAlpha/XChromeLoggerDataInfoLeakScannerUnitTest.java
Added Unit Tests:
- DirectoryBrowsingScannerUnitTest.java
- InsecureFormLoadScannerUnitTest.java
- InsecureFormPostScannerUnitTest.java
- RetrievedFromCacheScannerUnitTest.java
- ServerHeaderInfoLeakScannerUnitTest.java
- SourceCodeDisclosureScannerUnitTest.java
- StrictTransportSecurityScannerUnitTest.java
- UserControlledCharsetScannerUnitTest.java
- UserControlledCookieScannerUnitTest.java
- UserControlledHTMLAttributesScannerUnitTest.java
- UserControlledJavascriptEventScannerUnitTest.java
- UserControlledOpenRedirectScannerUnitTest.java
- XBackendServerInformationLeakUnitTest.java
- XChromeLoggerDataInfoLeakScannerUnitTest.java
PassiveScannerTest.java > Updated with some functionality from the active scan test packages in order to handle logging etc. This first became necessary while …
> Add Passive Scan Alpha Unit Tests

- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
Fix a typo in the description of Referer Exposes Session ID.
> pscanrules: fix typo in alert description

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
Change ExtensionWebSocket to not set the sender script type enabled by
default, the scripts are expected to be enabled by the user when needed.
> websocket: don't enable sender scripts by default

- src/org/zaproxy/zap/extension/webdriverlinux/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdrivermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
Update geckodriver to v0.20.1.
---
Per zaproxy/zap-libs#17.
> webdrivers: update geckodriver to v0.20.1

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestProxyRunner.java
Change ZestProxyRunner to update the Content-Length of the response.
Fix zaproxy/zaproxy#4613 - Zest "Replace in response-body" doesn't
update the Content-Length header
> zest: update Content-Length of proxied responses

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
Change ExtensionWebSocket to not wait forever for the persisted hanshake
message, if the message is not persisted the proxy thread would hang
forever. It will now wait at most 1 second, which should be enough time
(if not it simply doesn't show the handshake message). Also, core is now
persisting the message synchronously (zaproxy/zaproxy#4586) which makes
the wait obsolete.
> websocket: don't wait forever for persisted msg

- test/org/zaproxy/zap/extension/ascanrules/ActiveScannerTest.java
Change ActiveScannerTest to use a random port for the test server to
avoid clashes (BindException) when running the tests in parallel.
> Use random port for the test server

- build/build.xml
- test/org/zaproxy/zap/extension/ascanrules/ActiveScannerTest.java
- test/resources/install/README
- test/resources/install/xml/config.xml
Change ActiveScannerTest to use a temporary directory for the home and
installation dirs, to avoid having ZAP create its files in the resources
directory.
Remove old install files, they are now created on demand.
Also, change build.xml file to copy the test resource files to the test
build dir so they can be accessed without the prefix "test/resources",
thus normalising the access of the resource files.
> Use temp dir for ZAP's home and install dirs

- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/birtreports/ZapAddOn.xml
- src/org/zaproxy/zap/extension/browserView/ZapAddOn.xml
- src/org/zaproxy/zap/extension/callgraph/ZapAddOn.xml
- src/org/zaproxy/zap/extension/cmss/ZapAddOn.xml
- src/org/zaproxy/zap/extension/codedx/ZapAddOn.xml
- src/org/zaproxy/zap/extension/customreport/ZapAddOn.xml
- src/org/zaproxy/zap/extension/highlighter/ZapAddOn.xml
- src/org/zaproxy/zap/extension/saml/ZapAddOn.xml
- src/org/zaproxy/zap/extension/simpleExample/ZapAddOn.xml
- src/org/zaproxy/zap/extension/sse/ZapAddOn.xml
- src/org/zaproxy/zap/extension/tlsdebug/ZapAddOn.xml
- src/org/zaproxy/zap/extension/viewstate/ZapAddOn.xml
- src/org/zaproxy/zap/extension/vulncheck/ZapAddOn.xml
- src/org/zaproxy/zap/extension/wavsepRpt/ZapAddOn.xml
Bump min ZAP version to 2.5.0 for add-ons targeting an older version.
Version 2.5.0 is the older version available in Maven Central and the
older one that the add-ons can use.
Bump version (where needed) and update changes in ZapAddOn.xml files.
> Bump min ZAP version to 2.5.0 (alpha)

- src/org/zaproxy/zap/extension/alertReport/ZapAddOn.xml
- src/org/zaproxy/zap/extension/beanshell/ZapAddOn.xml
- src/org/zaproxy/zap/extension/portscan/ZapAddOn.xml
- src/org/zaproxy/zap/extension/sqliplugin/ZapAddOn.xml
- src/org/zaproxy/zap/extension/svndigger/ZapAddOn.xml
- src/org/zaproxy/zap/extension/treetools/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverlinux/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdrivermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
Bump min ZAP version to 2.5.0 for add-ons targeting an older version.
Version 2.5.0 is the older version available in Maven Central and the
older one that the add-ons can use.
Bump version (where needed) and update changes in ZapAddOn.xml files.
> Bump min ZAP version to 2.5.0 (beta)

- src/org/zaproxy/zap/extension/directorylistv1/ZapAddOn.xml
- src/org/zaproxy/zap/extension/directorylistv2_3/ZapAddOn.xml
- src/org/zaproxy/zap/extension/directorylistv2_3_lc/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzzdb/ZapAddOn.xml
Bump min ZAP version to 2.5.0 for add-ons targeting an older version.
Version 2.5.0 is the older version available in Maven Central and the
older one that the add-ons can use.
Bump version and update changes in ZapAddOn.xml files.
> Bump min ZAP version to 2.5.0

- src/org/zaproxy/zap/extension/accessControl/ExtensionAccessControl.java
Suppress fall-through warning in ExtensionAccessControl, cases standard
and attack are handled the same way.
> accessControl: address compiler warning

- src/org/zaproxy/zap/extension/alertFilters/AlertFilterAPI.java
- src/org/zaproxy/zap/extension/alertFilters/ZapAddOn.xml
Add missing type arguments to ApiResponseSet in AlertFilterAPI.
> alertFilters: address compiler warning

- src/org/zaproxy/zap/extension/alertReport/AlertReportExportMenuItem.java
- src/org/zaproxy/zap/extension/alertReport/AlertReportExportODT.java
- src/org/zaproxy/zap/extension/alertReport/AlertReportExportPDF.java
- src/org/zaproxy/zap/extension/alertReport/ExtensionAlertReportExport.java
Use Alert.getName() (instead of getAlert()) to obtain the name of the
alert.
> alertReport: address deprecations

- src/org/zaproxy/zap/extension/ascanrulesBeta/HeartBleedActiveScanner.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
Correct timeout per attack strength in heartbleed scanner, by not
falling-through into the following cases.
> ascanrulesBeta: correct timeout in heartbleed

- src/org/zaproxy/zap/extension/tokengen/ZapAddOn.xml
The add-on is already using newer features from 2.6.0.
> tokengen: bump minimum ZAP version to 2.6.0

- src/org/zaproxy/zap/extension/jsonview/ZapAddOn.xml
The add-on is already using newer features from 2.7.0.
> jsonview: bump minimum ZAP version to 2.7.0

- src/org/zaproxy/zap/extension/sqliplugin/DBMSHelper.java
Change DBMSHelper to access the database Tech constants directly.
> sqliplugin: address compiler warnings

- src/org/zaproxy/zap/extension/beanshell/ExtensionBeanShell.java
Change ExtensionBeanShell to use a ZapMenuItem (with no default
accelerator) when adding the tools menu item.
> beanshell: address deprecation

- src/org/zaproxy/zap/extension/diff/ZapAddOn.xml
- src/org/zaproxy/zap/extension/diff/ZapDiffRowGenerator.java
- src/org/zaproxy/zap/extension/diff/diff_match_patch.java
Use copy constructor instead of clone (which does not require unchecked
cast) in ZapDiffRowGenerator and implement Diff.hashCode.
> diff: address compiler warnings

- test/org/zaproxy/zap/extension/openapi/HTTPDTestServer.java
- test/org/zaproxy/zap/extension/openapi/NanoServerHandler.java
- test/org/zaproxy/zap/extension/openapi/OpenApiPre2dot0UnitTest.java
- test/org/zaproxy/zap/extension/openapi/OpenApiUnitTest.java
Change NanoServerHandler.serve accessibility from package to protected,
to allow classes in other packages to implement it.
> Tweak accessibility of test server handler (alpha)

- test/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosureUnitTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/HTTPDTestServer.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/NanoServerHandler.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/RemoteCodeExecutionCVE20121823UnitTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureCVE20121823UnitTest.java
Change NanoServerHandler.serve accessibility from package to protected,
to allow classes in other packages to implement it.
> Tweak accessibility of test server handler (beta)

- test/org/zaproxy/zap/extension/ascanrules/HTTPDTestServer.java
- test/org/zaproxy/zap/extension/ascanrules/NanoServerHandler.java
- test/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2UnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestParameterTamperUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestPathTraversalUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestSQLInjectionUnitTest.java
Change NanoServerHandler.serve accessibility from package to protected,
to allow classes in other packages to implement it.
> Tweak accessibility of test server handler

- .classpath
- test/org/zaproxy/zap/extension/ascanrules/ActiveScannerTest.java
Correct the path of the test resources to be properly loaded on Windows
and to not require the hardcoded path (just rely on the class package).
Correct Eclipse classpath to find/load the test resources.
> Correct loading of test resources

- src/com/veggiespam/imagelocationscanner/ILS.java
- src/org/zaproxy/zap/extension/imagelocationscanner/ZapAddOn.xml
- src/org/zaproxy/zap/extension/imagelocationscanner/resources/help/contents/about.html
Add deprecated annotation to deprecated method (JavaDoc tag).
Remove unused imports.
Bump version and updated changes in ZapAddOn.xml file.
Update about.html page.
---
Upstream change veggiespam/ImageLocationScanner#13.
> ils: address compiler warning

- src/org/zaproxy/zap/extension/tokengen/ExtensionTokenGen.java
Suppress fall-through warning in ExtensionTokenGen, cases standard and
attack are handled the same way.
> tokengen: address compiler warning

- src/org/zaproxy/zap/extension/soap/ExtensionImportWSDL.java
- src/org/zaproxy/zap/extension/soap/WSDLSpider.java
- src/org/zaproxy/zap/extension/soap/ZapAddOn.xml
- test/org/zaproxy/zap/extension/soap/WSDLSpiderTestCase.java
Change ExtensionImportWSDL to remove the spider parser when unloaded and
declare that it can be unloaded (it was the last change need to
dynamically unload the add-on). Also, remove unnecessary log when adding
the parser, the presence of the spider already indicates if the parser
is added.
Remove code no longer needed in the spider parser and corresponding test
case, as the parser is removed it not longer needs to be enabled and
disabled.
> soap: dynamically unload the add-on

- build/build.xml
- src/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanner.java
- src/org/zaproxy/zap/extension/soap/WSDLCustomParser.java
- test/org/zaproxy/zap/extension/soap/ExtensionImportWSDLTestCase.java
- test/org/zaproxy/zap/extension/soap/ImportWSDLTestCase.java
- test/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScannerTestCase.java
- test/org/zaproxy/zap/extension/soap/WSDLCustomParserTestCase.java
Fix failing tests in ImportWSDLTestCase (by not depending on the order
of the tests) and ExtensionImportWSDLTestCase (by loading the resource
messages).
Change WSDLCustomParserTestCase to not use reflection nor depend on the
order of the tests.
Rename SOAPActionSpoofingActiveScannerTest to have the same suffix as
the other tests ("TestCase", to use the same Ant include rule), also,
change it to not use reflection.
Tweak WSDLCustomParser and SOAPActionSpoofingActiveScanner to ease the
tests, by relaxing accessibility of the methods or return proper values.
Change build.xml file to run the soap tests (and copy its resources).
> soap: fix and tidy up tests

- src/org/zaproxy/zap/extension/scripts/resources/help/contents/scripts.html
Mention in the help how other scripting languages (than the ones that
have access to the ScriptContext) can access/set script variables.
Related to zaproxy/zaproxy#4185 - Expose global and script variables
> scripts: mention new access to script variables

- src/org/zaproxy/zap/extension/pscanrulesAlpha/InPageBannerInfoLeakScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
- test/org/zaproxy/zap/extension/pscanrulesAlpha/InPageBannerInfoLeakScannerUnitTest.java
Add new passive scanner (InPageBannerInfoLeakScanner), test (InPageBannerInfoLeakScannerUnitTest), update addon manifest (ZapAddOn.xml), help content (pscanalpha.html), and add supporting resources messages (Messages.properties).
Fixes zaproxy/zaproxy#178
> Issue 178 - Add In Page Banner Info Leak Scanner

- test/org/zaproxy/zap/extension/pscanrulesBeta/ViewStateScannerUnitTest.java
Change ViewStateScannerUnitTest to not ignore any test, now targeting
Java 8.
> pscanrulesBeta: run all viewstate scanner tests

- src/org/zaproxy/zap/extension/alertFilters/ZapAddOn.xml
- src/org/zaproxy/zap/extension/alertReport/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/beanshell/ZapAddOn.xml
- src/org/zaproxy/zap/extension/bruteforce/ZapAddOn.xml
- src/org/zaproxy/zap/extension/diff/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/importurls/ZapAddOn.xml
- src/org/zaproxy/zap/extension/invoke/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jruby/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jython/ZapAddOn.xml
- src/org/zaproxy/zap/extension/plugnhack/ZapAddOn.xml
- src/org/zaproxy/zap/extension/portscan/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/replacer/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/sqliplugin/ZapAddOn.xml
- src/org/zaproxy/zap/extension/svndigger/ZapAddOn.xml
- src/org/zaproxy/zap/extension/tips/ZapAddOn.xml
- src/org/zaproxy/zap/extension/tokengen/ZapAddOn.xml
- src/org/zaproxy/zap/extension/treetools/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverlinux/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdrivermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
Remove the filters entry from the ZapAddOn.xml files.
Related to zaproxy/zaproxy#4191 - Remove filter extension from core
functionality
> Remove "filters" from add-ons' manifests (beta)

- src/org/zaproxy/zap/extension/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/coreLang/ZapAddOn.xml
- src/org/zaproxy/zap/extension/directorylistv1/ZapAddOn.xml
- src/org/zaproxy/zap/extension/directorylistv2_3/ZapAddOn.xml
- src/org/zaproxy/zap/extension/directorylistv2_3_lc/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzzdb/ZapAddOn.xml
- src/org/zaproxy/zap/extension/gettingStarted/ZapAddOn.xml
- src/org/zaproxy/zap/extension/groovy/ZapAddOn.xml
- src/org/zaproxy/zap/extension/help/ZapAddOn.xml
- src/org/zaproxy/zap/extension/help_fil_PH/ZapAddOn.xml
- src/org/zaproxy/zap/extension/help_id_ID/ZapAddOn.xml
- src/org/zaproxy/zap/extension/help_pt_BR/ZapAddOn.xml
- src/org/zaproxy/zap/extension/help_tr_TR/ZapAddOn.xml
- src/org/zaproxy/zap/extension/help_zh_CN/ZapAddOn.xml
- src/org/zaproxy/zap/extension/onlineMenu/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/quickstart/ZapAddOn.xml
- src/org/zaproxy/zap/extension/reveal/ZapAddOn.xml
- src/org/zaproxy/zap/extension/saverawmessage/ZapAddOn.xml
- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
- src/org/zaproxy/zap/extension/todo/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
Remove the filters entry from the ZapAddOn.xml files, the filters are no
longer supported.
Related to zaproxy/zaproxy#4191 - Remove filter extension from core
functionality
> Remove "filters" from add-ons' manifests

- src/org/zaproxy/zap/extension/jython/JythonOptionsPanel.java
- src/org/zaproxy/zap/extension/jython/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jython/resources/help/contents/jython.html
- src/org/zaproxy/zap/extension/jython/resources/help/contents/options.html
- src/org/zaproxy/zap/extension/jython/resources/help/index.xml
- src/org/zaproxy/zap/extension/jython/resources/help/map.jhm
- src/org/zaproxy/zap/extension/jython/resources/help/toc.xml
Add help page for Jython options panel.
Add the help key to JythonOptionsPanel.
> jython: add options help page

- src/org/zaproxy/zap/extension/jython/ExtensionJython.java
- src/org/zaproxy/zap/extension/jython/JythonEngineWrapper.java
- src/org/zaproxy/zap/extension/jython/ZapAddOn.xml
Change ExtensionJython to no longer set the module path to the "default"
system state, the script engines use their own (new each time).
Change JythonEngineWrapper to set the path on the system state of the
engine (which is set to the current thread after its creation).
Update changes in ZapAddOn.xml file and capitalise the add-on name.
Fix zaproxy/zaproxy#4651 - UI hang during start after setting module
path for Python Scripting
> jython: fix path module loading and UI hang

- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
- src/org/zaproxy/zap/extension/selenium/resources/help/contents/options.html
Mention the configuration keys in the options help page.
> selenium: mention config keys in options help page

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/Messages.properties
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
Add missing error message shown when attempting to send a message to the
client and no connection is established.
> websocket: add missing error message

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
- src/org/zaproxy/zap/extension/websocket/ui/PopupExcludeWebSocketFromContextMenu.java
- src/org/zaproxy/zap/extension/websocket/ui/PopupIncludeWebSocketInContextMenu.java
Remove the pop up menu items when no longer needed, to prevent them from
staying in the main pop up menu after the add-on has been uninstalled
or updated, which would lead to exceptions (ClassCastException) as the
old menu items tried to use classes of the newer version.
> websocket: properly remove pop up menu items

- src/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
- src/org/zaproxy/zap/extension/openapi/ZapAddOn.xml
Change ExtensionOpenApi to save the directory chosen when importing
local file, to not require to navigate to the same directory if the file
needs to be imported again.
> openapi: open previously chosen dir

- src/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleFileActiveScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleSimpleActiveScanner.java
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/httpsender/Alert on HTTP Response Code Errors.js
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/httpsender/Alert on Unexpected Content Types.js
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleFilePassiveScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleSimplePassiveScanner.java
Update the links to scanners.md in example scanners and community
scripts.
Part of zaproxy/zaproxy#4672 - Move (non-dist) doc files to top level
directory
> Update links to scanners.md

- src/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
- src/org/zaproxy/zap/extension/openapi/ZapAddOn.xml
- src/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverter.java
Change ExtensionOpenApi to read the file with UTF-8 instead of relying
on the default charset.
Change SwaggerConverter to remove the BOM from the definition, the
Swagger library checks the first character to decide if the contents
should be parsed as JSON or YAML.
Fix zaproxy/zaproxy#4676 - openAPI import error
> openapi: use UTF-8 and ignore BOM

- src/org/zaproxy/zap/extension/scripts/NullScriptEngineWrapper.java
- src/org/zaproxy/zap/extension/scripts/dialogs/LoadScriptDialog.java
- src/org/zaproxy/zap/extension/scripts/dialogs/NewScriptDialog.java
Change NullScriptEngineWrapper to declare that it's not visible.
Add tasks to NewScriptDialog and LoadScriptDialog to remove the
workaround when targeting newer core version.
Related to zaproxy/zaproxy#4680 - Ignore null script engine when listing
engines
> scripts: make null engine not visible

- src/com/fasteasytrade/JRandTest/Algo/DES.java
- src/com/fasteasytrade/JRandTest/Algo/MT19937Prng.java
- src/com/fasteasytrade/JRandTest/Algo/RSA.java
- src/com/fasteasytrade/JRandTest/Algo/RSACrypt.java
- src/com/fasteasytrade/JRandTest/Algo/TripleDES.java
- src/com/fasteasytrade/JRandTest/IO/HttpGetUrlRandomStream.java
- src/com/fasteasytrade/JRandTest/Tests/Base.java
- src/com/fasteasytrade/JRandTest/Tests/Squeeze.java
Remove redundant casts, address raw type warnings, and unchecked calls
in JRandTest code to compile the add-on with all lint checks and with
warnings as error.
> tokengen: address compiler warnings

- src/org/zaproxy/zap/extension/highlighter/HighlighterPanel.java
- src/org/zaproxy/zap/extension/highlighter/ZapAddOn.xml
Change HighlighterPanel to use a scroll panel for its internal panel to
allow to scroll/resize the panel, instead of expanding it each time a
new highlight entry is added. Also, remove unused/empty panel and use
BorderLayout instead of GridBagLayout to simplify the layout, where
possible.
Part of zaproxy/zaproxy#232 - String Highlighter
> highlighter: correct resizing of main panel

- build/build.xml
- src/org/zaproxy/zap/extension/savexmlmessage/ExtensionSaveXMLHttpMessage.java
- src/org/zaproxy/zap/extension/savexmlmessage/PopupMenuSaveXMLMessage.java
- src/org/zaproxy/zap/extension/savexmlmessage/ZapAddOn.xml
- src/org/zaproxy/zap/extension/savexmlmessage/resources/Messages.properties
It's my **first** pull request ever so bare with me if I am missing some good practices :). 
Anyways the code I added allows for saving base64 encoded requests/responses as XML files (Burpsuit-style) to avoid corruption of data in case binary files get downloaded or sent.
I tried to keep the code as much as the original **saverawmessage** as possible (thought it was a good idea).
> Added SaveXMLMessage extentions

- src/org/zaproxy/zap/extension/pscanrules/TestInfoSessionIdURL.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- TestInfoSessionIdURL.java > Updated to include a supplemental check for situations like:
`http://tld.gtld/fred;jsessionid=1A530637289A03B07199A44E8D531427?foo=bar`
- ZapAddOn.xml > Updated changes section.
Fixes zaproxy/zaproxy#3008
> Issue 3008 - Session ID In URL Rewrite False Negative

- src/org/zaproxy/zap/extension/groovy/ZapAddOn.xml
- src/org/zaproxy/zap/extension/groovy/resources/Messages.properties
- src/org/zaproxy/zap/extension/groovy/resources/help/contents/about.html
- src/org/zaproxy/zap/extension/groovy/resources/help/contents/intro.html
- src/org/zaproxy/zap/extension/groovy/resources/help/helpset.hs
- src/org/zaproxy/zap/extension/groovy/resources/help/index.xml
- src/org/zaproxy/zap/extension/groovy/resources/help/toc.xml
Change the add-on name (and description) to Groovy Support to not focus
just on scripting, the add-on is also useful as a dependency for add-ons
written in Groovy.
Update help to mention that use case and reflect the name/description
changes.
Change version to follow semantic versioning, to make it reliable for
other add-ons to depend on.
> groovy: rename add-on for broader usage

- src/org/zaproxy/zap/extension/jython/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jython/resources/help/contents/jython.html
Add the Jython version bundled in the add-on to the help page, to inform
the user.
> jython: mention Jython version in the help

- src/org/zaproxy/zap/extension/jruby/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jruby/resources/help/contents/jruby.html
Add the JRuby version bundled in the add-on to the help page, to inform
the user.
Update changes and capitalise add-on name in ZapAddOn.xml file.
> jruby: mention JRuby version in the help

- src/org/zaproxy/zap/extension/bruteforce/BruteForce.java
- src/org/zaproxy/zap/extension/bruteforce/DirBusterManager.java
Change BruteForce to log the creation of the instance with debug level,
not of much interest.
Change DirBusterManager to log errors with warn level, the errors do not
represent a bug or other serious issue (e.g. extracted a URL that's not
valid).
> brutefoce: tweak logging levels

- src/org/zaproxy/zap/extension/bruteforce/BruteForcePanel.java
- src/org/zaproxy/zap/extension/bruteforce/ZapAddOn.xml
Change BruteForcePanel to also enable the start button when a file is
selected, to allow to start the scan without the need to change the
target.
> bruteforce: enable start button on file selection

- src/org/zaproxy/zap/extension/jxbrowser/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowser/resources/help/contents/jxbrowser.html
Add the JxBrowser version bundled (in the specific OS add-ons) to the
help page, to inform the user.
Bump version and up changes in ZapAddOn.xml file.
> jxbrowser: mention JxBrowser version in the help

- src/org/zaproxy/zap/extension/websocket/WebSocketAPI.java
Change WebSocketAPI's WebSocketObserver to return immediately if the
message received is a PING, it's not an API request and attempting to
parse it as JSON would fail. Also, add a TODO to reply with a PONG..
---
The PONG reply is being added in #1618.
> websocket: don't try parse PINGs as API requests

- src/org/zaproxy/zap/extension/websocket/WebSocketMessageDTO.java
- src/org/zaproxy/zap/extension/websocket/ui/WebSocketMessagesViewModel.java
- src/org/zaproxy/zap/extension/websocket/ui/httppanel/models/StringWebSocketPanelViewModel.java
- src/org/zaproxy/zap/extension/websocket/ui/httppanel/views/WebSocketPanelTextView.java
- src/org/zaproxy/zap/extension/websocket/ui/httppanel/views/WebSocketSyntaxHighlightTextView.java
New Methods in order binary displayed payloads to be more informative
In current state when a payload contains unmapped or/end malformed characters, websocket panel display an informative message `<unreadable binary payload>`. Adding those methods we are able to get some info about payload.
Example Current State: 
Example with replacing unmapped & malformed Chars
I haven't yet replaced methods which make use of getReadablePayload because I would like your input about that.
> Add Method getPayloadAsString by replacing unmapped & malformed Chars

- src/org/zaproxy/zap/extension/ZapAddOn.xml
Add example on how to declare a bundle.
Part of zaproxy/zaproxy#3841 - Allow add-ons without extensions to have
resource messages
> Update example ZapAddOn.xml with resource bundle

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- src/org/zaproxy/zap/extension/websocket/db/TableWebSocket.java
- src/org/zaproxy/zap/extension/websocket/ui/WebSocketMessagesViewModel.java
Add methods back to restore binary compatibility and deprecate replaced
method (typo in its name).
Tweak JavaDoc of some restored methods.
> websocket: restore binary compatibility

- src/org/zaproxy/zap/extension/ZapAddOn.xml
Add example on how to declare a helpset.
Part of zaproxy/zaproxy#3734 - Allow add-ons without extensions to have
help pages
> Update example ZapAddOn.xml with a helpset

- src/org/zaproxy/zap/extension/websocket/WebSocketAPI.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
Change WebSocketAPI to check that the target node is non-null before
using it, the target might not have a node (e.g. spider started with a
URL not yet accessed).
> websocket: fix NPE when dispatching events

- README.md
Use "add-ons" (instead of "extensions") when referring to add-ons.
Also, correct the case of the menu item to match the one in ZAP and
remove two consecutive spaces.
Part of zaproxy/zaproxy#4732 - Correct/normalise terms used throughout
the docs
> Tweak README for correct term usage

- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
Fix typo and correct term (`scanner` instead of `plugin`) in help page.
Part of zaproxy/zaproxy#4732 - Correct/normalise terms used throughout
the docs
> pscanrulesBeta: tweak help page

- src/org/zaproxy/zap/extension/scripts/resources/help/contents/scripts.html
- src/org/zaproxy/zap/extension/scripts/resources/help/helpset.hs
- src/org/zaproxy/zap/extension/scripts/resources/help/index.xml
- src/org/zaproxy/zap/extension/scripts/resources/help/toc.xml
Remove recommendation to copy JARs to lib directory, that will not work
by default with newer ZAP versions (the classpath needs to be changed to
include them).
Change the TOC, index, headers, and titles to use Script Console instead
of Scripts, so they match the add-on name (as with other add-ons).
Related to zaproxy/zaproxy#4755 - Stop relying on ClassLoaderUtil
> scripts: tweak help

- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/dialogs/EditScriptDialog.java
Change EditScriptDialog to use a non-editable text field to allow the
path to be selected/copied, to allow easy/faster access to the file.
> scripts: allow to select the path of the script

- src/org/zaproxy/zap/extension/ascanrulesBeta/ChallengeCallbackImplementor.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/XXEPlugin.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/XXEPluginCallbackImplementor.java
Rename callback classes and variables to not use "API" in the names,
they are no longer related to the API.
> ascanrulesBeta: rename callback classes

- src/org/zaproxy/zap/extension/ZapAddOn.xml
Fix a typo in the description of the version.
> Fix typo in example ZapAddOn.xml file

- src/org/zaproxy/zap/extension/customreport/ExtensionCustomReport.java
- src/org/zaproxy/zap/extension/customreport/OptionDialog.java
Change OptionDialog to always (on cancel, accept, and close) clear its
own reference in ExtensionCustomReport to ensure that it's always shown
when invoked through the menu, otherwise if closed through the window
decorations it will not be shown anymore.
Change ExtensionCustomReport to not expose the method that clears the
reference to the dialogue as that's handled internally also create the
dialogue when invoked through the menu (instead of using a public
method).
> customreport: show dialogue, always

- src/org/zaproxy/zap/extension/ascanrulesBeta/HeartBleedActiveScanner.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/InsecureHTTPMethod.java
- src/org/zaproxy/zap/extension/sqliplugin/SQLiUnionEngine.java
Change HeartBleedActiveScanner and SQLiUnionEngine to not use the
Integer constructors (deprecated in Java 9+), not needed in string
concatenation and when parsing (use parseInt instead).
Change import in InsecureHTTPMethod from Commons Lang 3 to Lang 2.x, the
former version is not bundled in the targeted ZAP version (2.7.0).
(The latter was spotted while building with Gradle.)
> Address deprecations and correct import

- src/org/zaproxy/zap/extension/websocket/WebSocketProxy.java
Change WebSocketProxy to send the Pong responses also when in server
mode (e.g. API).
> websocket: send Pong responses also in server mode

- src/org/zaproxy/zap/extension/websocket/WebSocketAPI.java
Change WebSocketAPI's WebSocketObserver to return immediately if the
message received is a control frame (not just Ping or Close), none of
those frames are API requests.
Remove TODO task added previously, the Pong should be handled by the
WebSocketProxy instead.
> websocket: ignore all control frames in the API

- src/org/zaproxy/zap/extension/websocket/utility/WebSocketUtils.java
Generates 'Sec-WebSocket-Key' which is used in websocket Handshake. 
Open this PR in order to break up [PR#1618](https://github.com/zaproxy/zap-extensions/pull/1618)
> WebSocketUtils: Generate Sec-WebSocket-Key

- src/org/zaproxy/zap/extension/pscanrulesAlpha/UsernameIdorScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/XBackendServerInformationLeak.java
Remove misleading code comment when setting the evidence in the scanner
UsernameIdorScanner and XBackendServerInformationLeak (it's not setting
the Server header in those scanners).
> pscanrulesAlpha: remove misleading comments

- src/org/zaproxy/zap/extension/cmss/FingerPrintingThread.java
Remove unnecessary call to finalize in FingerPrintingThread, the method
should not be called directly and it's deprecated in Java 9+.
> cmss: remove unnecessary call to finalize

- src/org/zaproxy/zap/extension/webdriverlinux/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
- src/org/zaproxy/zap/extension/webdrivermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
- src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html
Update geckodriver to v0.21.0.
Update help pages.
Part of zaproxy/zaproxy#4770 - Update geckodriver to 0.21.0
---
Depends on zaproxy/zap-libs#25.
> webdrivers: update geckodriver to v0.21.0

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
Change ExtensionWebSocket to not try to remove the breakpoint UI manager
when uninstalling if not initialised, preventing the NPE.
Remove unused imports in ExtensionWebSocket.
Fix zaproxy/zaproxy#4815 - NullPointerException while uninstalling
WebSockets add-on with ZAP without GUI
> websocket: fix NPE while uninstalling

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
Change ExtensionWebSocket to also register the script type in daemon
mode, the scripts can be used without UI. Also, don't create the script
icon if in daemon to prevent initialisation of UI classes (which might
fail if in headless environment).
> websocket: register script type also in daemon

- src/org/zaproxy/zap/extension/websocket/WebSocketAPI.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
Change WebSocketAPI to remove and unregister the event consumer on
socket exceptions (e.g. channel not cleanly closed) when dispatching the
events.
Update changes in ZapAddOn.xml and about.html.
Related to #1489.
Depends on zaproxy/zaproxy#4827 - Allow consumers to remove themselves
during events
> websocket: remove consumer on socket exception

- .travis.yml
- build/build.xml
Change .travis.yml to also run the build with Java 9.
Change build.xml file to include a Messages.properties file on the
classpath as it's required by core.
> Add Java 9 to Travis CI builds

- .travis.yml
- build/build.xml
- test/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScannerTestCase.java
Change .travis.yml to also run the build with Java 9.
Change build.xml file to include a Messages.properties file on the
classpath as it's required by core, also, include add-ons in test
classpath to include helper class (SystemUtils, from commons-lang3).
Disable SOAPActionSpoofingActiveScannerTestCase on Java 9+ because of
class used (i.e. zaproxy/zaproxy#4037).
> Add Java 9 to Travis CI builds (alpha)

- .travis.yml
- build/build.xml
- test/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureWEBINFUnitTest.java
Change .travis.yml to also run the build with Java 9.
Change build.xml file to include a Messages.properties file on the
classpath as it's required by core.
Disable SourceCodeDisclosureWEBINFUnitTest on Java 9+ because of an
issue in the used library (i.e. zaproxy/zaproxy#4038).
> Add Java 9 to Travis CI builds (beta)

- src/org/zaproxy/zap/extension/plugnhack/manualsend/ClientMessagePanelSender.java
Change ClientMessagePanelSender to remove the throws clause from a
method, it does not throw the exception.
> plugnhack: remove unnecessary throws clause

- src/org/zaproxy/zap/extension/onlineMenu/ExtensionOnlineMenu.java
- src/org/zaproxy/zap/extension/onlineMenu/ZapAddOn.xml
- src/org/zaproxy/zap/extension/quickstart/QuickStartPanel.java
- src/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- src/org/zaproxy/zap/extension/spiderAjax/SpiderPanel.java
- src/org/zaproxy/zap/extension/websocket/ui/WebSocketPanel.java
Address warnings with usage of ToolKit.getMenuShortcutKeyMask by
suppressing them, the new method is only available in Java 10.
Update version and changes in ZapAddOn.xml file, where needed.
> Address warnings with Java 10

- src/org/zaproxy/zap/extension/alertFilters/AlertFilterAPI.java
- src/org/zaproxy/zap/extension/alertFilters/ZapAddOn.xml
Change AlertFilterAPI to set the parameter "contextId" of the view as
required (the view requires it).
> alertFilters: correct required state of API param

- build/build.xml
- src/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanner.java
- src/org/zaproxy/zap/extension/soap/WSDLCustomParser.java
- src/org/zaproxy/zap/extension/soap/ZapAddOn.xml
- src/org/zaproxy/zap/extension/soap/resources/Messages.properties
build.xml > Now include a "without-help-indexes" target for faster dev builds.
Messages.properties > Added keys/values to support other changes.
SOAPActionSpoofingActiveScanner > Now returns (and outputs an info message) if there are no actions to test.
WSDLCustomParser > Now logs and displays (if appropriate) a message if `ResourceDownloadException` is encountered.
ZapAddOn.xml > Added to the changes section.
> SOAP Extension - Various Fixes

- src/org/zaproxy/zap/extension/soap/ImportFromUrlDialog.java
- src/org/zaproxy/zap/extension/soap/ImportWSDL.java
- src/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanner.java
- src/org/zaproxy/zap/extension/soap/SOAPMsgConfig.java
- src/org/zaproxy/zap/extension/soap/SOAPXMLInjectionActiveScanner.java
- src/org/zaproxy/zap/extension/soap/SoapAPI.java
- src/org/zaproxy/zap/extension/soap/WSDLCustomParser.java
- src/org/zaproxy/zap/extension/soap/WSDLSpider.java
* ImportFromUrlDialog, ImportWSDL, & SOAPMsgConfig > Added license header (2014) per history.
* WSDLSpider > Added license header (2014) per history, removed unused `importer` field and handling, reduce some logging to debug (from info).
* WSDLCustomParser > Added license header (2014) per history, removed one double semi-colon, removed un-necessary `log != null` checks, made LOG full caps (constant naming), removed cast on extHistory (get extension by class vs NAME).
* SoapAPI > Remove trailing white space in license header content.
* SOAPActionSpoofingActiveScanner > Made LOG full caps (constant naming) 
* SOAPXMLInjectionActiveScanner > Made LOG full caps (constant naming)
> SOAP Extension - Maint Changes

- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
- src/org/zaproxy/zap/extension/selenium/resources/Messages.properties
Tweak message shown when failed to start or connect to the browser, to
be more clear that while the browser might have started it might have
failed to connect to it.
> selenium: tweak error message

- src/org/zaproxy/zap/extension/soap/ExtensionImportWSDL.java
- src/org/zaproxy/zap/extension/soap/ZapAddOn.xml
Change ExtensionImportWSDL to use a different accelerator than the one
already in use by Import files containing URLs add-on.
Part of zaproxy/zaproxy#3519 - Keyboard Shortcuts Issue
> soap: change default accelerator for import file

- src/org/zaproxy/zap/extension/requester/RequesterPanel.java
- src/org/zaproxy/zap/extension/requester/ZapAddOn.xml
Change Requester tab to use a different accelerator than the WebSockets
tab.
Part of zaproxy/zaproxy#3519 - Keyboard Shortcuts Issue
> requester: change tab's default accelerator

- src/org/zaproxy/zap/extension/tlsdebug/TlsDebugPanel.java
- src/org/zaproxy/zap/extension/tlsdebug/ZapAddOn.xml
Change TLS Debug tab to use a different accelerator than Clients tab.
Part of zaproxy/zaproxy#3519 - Keyboard Shortcuts Issue
> tlsdebug: change tab's default accelerator

- src/org/zaproxy/zap/extension/alertFilters/AlertFilterAPI.java
- src/org/zaproxy/zap/extension/alertFilters/ZapAddOn.xml
- src/org/zaproxy/zap/extension/alertFilters/resources/Messages.properties
Add basic description to endpoints.
Change AlertFilterAPI to set a custom description tag to the endpoints,
since the API uses a different prefix than the extension ("alertFilter"
vs "alertFilters").
> alertFilters: add description to API endpoints

- src/org/zaproxy/zap/extension/requester/ManualHttpRequestEditorPanel.java
- src/org/zaproxy/zap/extension/requester/RequesterPanel.java
- src/org/zaproxy/zap/extension/requester/RightClickMsgMenuRequester.java
- src/org/zaproxy/zap/extension/requester/ToolsMenuItemRequester.java
- src/org/zaproxy/zap/extension/soap/ExtensionImportWSDL.java
- src/org/zaproxy/zap/extension/tlsdebug/TlsDebugPanel.java
- src/org/zaproxy/zap/extension/wappalyzer/TechPanel.java
Address compilation warning with usage of ToolKit.getMenuShortcutKeyMask
by suppressing it, the new method is only available in Java 10.
> Address warnings with Java 10 (alpha)

- src/org/zaproxy/zap/extension/bruteforce/BruteForcePanel.java
- src/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java
- src/org/zaproxy/zap/extension/importurls/ExtensionImportUrls.java
- src/org/zaproxy/zap/extension/plugnhack/ClientsPanel.java
- src/org/zaproxy/zap/extension/portscan/PortScanPanel.java
- src/org/zaproxy/zap/extension/portscan/ZapAddOn.xml
- src/org/zaproxy/zap/extension/replacer/ExtensionReplacer.java
- src/org/zaproxy/zap/extension/replacer/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/ConsolePanel.java
- src/org/zaproxy/zap/extension/scripts/ScriptsListPanel.java
- src/org/zaproxy/zap/extension/tokengen/TokenPanel.java
- src/org/zaproxy/zap/extension/zest/ZestResultsPanel.java
Address compilation warning with usage of ToolKit.getMenuShortcutKeyMask
by suppressing it, the new method is only available in Java 10.
Update changes in ZapAddOn.xml files, where needed.
> Address warnings with Java 10 (beta)

- src/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosure.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- test/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosureUnitTest.java
BackupFileDisclosure > Ignore empty "backup" responses.
ZapAddOn.xml > Add to changes section.
BackupFileDisclosureUnitTest > Added a test to cover the new behavior.
Related to zaproxy/zaproxy#4850
> BackupFileDisclosure Handle Empty "Backup" Responses

- src/org/zaproxy/zap/extension/requester/ExtensionRequester.java
- src/org/zaproxy/zap/extension/requester/NumberedTabbedPane.java
- src/org/zaproxy/zap/extension/requester/RequesterPanel.java
- src/org/zaproxy/zap/extension/requester/ZapAddOn.xml
Change ExtensionRequester to unload the view components dynamically
added and declare that it can be unloaded.
Change NumberedTabbedPane and RequesterPanel to unload the components,
that is, remove the request/response panels from core class.
> requester: dynamically unload the add-on

- src/org/zaproxy/zap/extension/viewstate/ExtensionHttpPanelViewStateView.java
- src/org/zaproxy/zap/extension/viewstate/ZapAddOn.xml
Change ExtensionHttpPanelViewStateView to not keep references to the
latest model/view created (not used to anything), to not prevent them
and, more important, parent components from being GC'ed.
Related to #1751, this issue was preventing the Requester add-on from being completely GC'ed.
> viewstate: fix memory leak

- src/org/zaproxy/zap/extension/quickstart/AttackThread.java
- src/org/zaproxy/zap/extension/quickstart/ZapAddOn.xml
Change AttackThread to create the HTTP message, for the spider, with the
connection configurations to use the default user agent.
Part of zaproxy/zaproxy#4846 - User-Agent changes from configured value
> quickstart: use default user agent for spider seed

- test/org/zaproxy/zap/extension/websocket/client/WebSocketProxyUnitTest.java
Change WebSocketProxyUnitTest to give more time for all the expected
pongs to be received, also, assert that the minimum expected was
received.
---
From IRC channel.
> websocket: address timing issue in test

- src/org/zaproxy/zap/extension/birtreports/resources/Messages.properties
- src/org/zaproxy/zap/extension/cmss/resources/Messages.properties
- src/org/zaproxy/zap/extension/sequence/resources/Messages.properties
- src/org/zaproxy/zap/extension/vulncheck/resources/Messages.properties
- src/org/zaproxy/zap/extension/wappalyzer/resources/Messages.properties
- src/org/zaproxy/zap/extension/wavsepRpt/resources/Messages.properties
Remove example comment in Messages.properties files, remnant from
example add-on.
> Remove example comment from Messages files (alpha)

- src/org/zaproxy/zap/extension/jruby/resources/Messages.properties
- src/org/zaproxy/zap/extension/jython/resources/Messages.properties
- src/org/zaproxy/zap/extension/tokengen/resources/Messages.properties
Remove example comment in Messages.properties files, remnant from
example add-on.
> Remove example comment from Messages files (beta)

- build/build.xml
- test/org/zaproxy/zap/extension/groovy/VerifyScriptTemplates.java
Add test to verify that the Groovy templates are parsed without errors,
currently excluding the ones that require add-ons not available in the
test classpath.
> groovy: verify script templates can be parsed

- src/org/zaproxy/zap/extension/spiderAjax/SpiderPanel.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
SpiderPanel.java > Add components to expose a TableExportButton in the GUI.
Fixes zaproxy/zaproxy#4875
> Fix Issue 4875 - Allow exporting Ajax Spider results table

- src/org/zaproxy/zap/extension/fuzz/FuzzersStatusPanel.java
Change FuzzersStatusPanel to not call the deprecated constructor,
already targeting newer ZAP version.
> fuzz: address core deprecation

- src/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- CacheableScanner - When parsing "lifetime" (max-age) value split on comma and use the 0th item in case there's a malformed value passed. (This works whether or not there's a comma to split on. The string was already split on space, and has been checked to start with max-age.) If a NFE still occurs (exceed Long.MAX_VALUE or still non-number characters) mark lifetime as not found and log a debug message. 
- ZapAddOn.xml - Updated change section.
Fixes zaproxy/zaproxy#4924
> Issue 4924 - CacheableScanner Fix NumberFormatException

- src/org/zaproxy/zap/extension/pscanrules/CrossDomainScriptInclusionScanner.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
- test/org/zaproxy/zap/extension/pscanrules/CrossDomainScriptInclusionScannerUnitTest.java
* CrossDomainScriptInclusionScanner - Added check for HTML responses (others skipped).
* CrossDomainScriptInclusionScannerUnitTest - Added a test to assert the new behavior and ensure FP doesn't happen.
* ZapAddOn.xml - Updated changes section.
pscanrules.html - Made the details more specific to account for this change.
> CrossDomainScriptInclusionScanner - Only Analyze HTML Responses

- src/org/zaproxy/zap/extension/frontendscanner/ExtensionFrontEndScanner.java
- src/org/zaproxy/zap/extension/frontendscanner/FrontEndScannerOptions.java
- src/org/zaproxy/zap/extension/frontendscanner/resources/Messages.properties
Persist enabled state of the front-end scanner and expose it through the
API.
Part of zaproxy/zaproxy#4939 - [FrontEndScanner] Phase 1 tracker
> frontendscanner: persist enabled state

- src/org/zaproxy/zap/extension/quickstart/launch/GenerateQuickStartLangFile.java
Change GenerateQuickStartLangFile to close the FileInputStream(s) after
reading the properties.
Issues reported by `lgtm.com`.
> quickstart: close streams

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/menu/ZestAddAssignPopupMenu.java
Use selected text when adding assignments from the response (when
applicable, e.g. assign to string and replacement), also, don't quote
the text since the default is non-regex.
> zest: use selected text in assignments

- src/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Change ExtensionScriptsUI to implement the methods that allow to add and
remove a tree selection listener.
Part of zaproxy/zaproxy#4964 - Allow to react to selection change in
Scripts tree
> scripts: implement new ScriptUI methods

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/dialogs/ZestDialogManager.java
Change ZestDialogManager to display the HTTP message when a ZestRequest
statement is selected (e.g. using keyboard), not just when clicked.
> zest: display HTTP message on node selection

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestZapUtils.java
- src/org/zaproxy/zap/extension/zest/resources/Messages.properties
Change ZestZapUtils to also show the inverse state (as "Not") in equals,
is integer, and length expressions' tree nodes.
Replace "!" with "Not" in other existing regex expression/assert to be
more noticeable.
> zest: show inverse state in more expressions

- src/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- test/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScannerUnitTest.java
Wrap calls to `DateUtil.parseDate` in try/catch blocks and allow the variable(s) to remain null if parsing fails. Enhance messaging in outter `catch (Exception e)` block.
Add very basic UnitTest that served as a PoC while putting this fix together.
Update changes section of ZapAddOn.xml.
Fixes zaproxy/zaproxy#4969
> Fix Issue 4969 - CacheableScanner DateParseException

- src/org/zaproxy/zap/extension/ascanrules/CommandInjectionPlugin.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
For issue #4968 Enhancement: Command Injection Uninitialized Env Var WAF Bypass.
I think is hard to know what Env is uninitialized on the target machine and as most env is in upper case, code just guesses a random lower case variable.
cat /etc/passwd will become:
cat$xxx $xxx/etc$xxx/passwd
> Add Uninitialized Env Var WAF Bypass

- src/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosure.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/HeartBleedActiveScanner.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosureUnitTest.java
Remove the switch cases using `AttackStrength.DEFAULT`, those cases do
not happen, the method used to obtain the strength returns the value
configured for the default strength (for example, `MEDIUM`).
Remove test using `DEFAULT` strength, redundant with the other strength
tests.
> ascanrulesBeta: remove unreachable strength cases

- src/org/zaproxy/zap/extension/ascanrules/TestExternalRedirect.java
- src/org/zaproxy/zap/extension/pscanrules/XContentTypeOptionsScanner.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
Remove switch cases using `DEFAULT` or `OFF` for `AttackStrength` and
`AlertThreshold`, those cases do not happen, the methods used to obtain
the strength/threshold return the value configured for the default
strength (for example, MEDIUM) and the `OFF` is used to disable the
scanners so the scanner would not even be called in that case.
Update changes in ZapAddOn.xml file (where required).
> Remove unreachable strength/threshold cases

- src/org/zaproxy/zap/extension/ascanrulesAlpha/LDAPInjection.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ProxyDisclosureScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/SQLInjectionSQLite.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/SourceCodeDisclosureFileInclusion.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
Remove switch cases and if statements using `DEFAULT` or `OFF` for
`AttackStrength` and `AlertThreshold`, those do not happen/match.
For ProxyDisclosureScanner remove all alert threshold checks, not doing
anything.
> Remove unreachable strength/threshold stmt (alpha)

- src/org/zaproxy/zap/extension/sse/EventStreamListener.java
- src/org/zaproxy/zap/extension/sse/EventStreamProxy.java
- src/org/zaproxy/zap/extension/sse/ZapAddOn.xml
- src/org/zaproxy/zap/extension/sse/db/TableEventStream.java
Adjust log levels to be less verbose (info to debug) and have some
events with more relevance (info to warn), also, remove redundant log
message already done by the proxy.
Remove prints of exceptions' stacktraces, either already included in
logging message or added to a new one.
> sse: adjust log levels and remove stacktrace print

- test/org/zaproxy/zap/extension/ascanrules/ActiveScannerAppParamTest.java
- test/org/zaproxy/zap/extension/ascanrules/ActiveScannerAppTest.java
- test/org/zaproxy/zap/extension/ascanrules/BufferOverflowUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/CodeInjectionPluginUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/CommandInjectionPluginUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/FormatStringUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2UnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestDirectoryBrowsingUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestExternalRedirectUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestInjectionCRLFUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestParameterTamperUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestPathTraversalUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestPersistentXSSAttackUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestPersistentXSSPrimeUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestPersistentXSSSpiderUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestRemoteFileIncludeUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestSQLInjectionUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestServerSideIncludeUnitTest.java
- test/org/zaproxy/zap/testutils/ActiveScannerTestUtils.java
Add tests (for each attack strength) to assert the number of messages
sent by the scanners (AbstractAppParamPlugin and AbstractAppPlugin).
> Assert number of messages sent by scanners

- test/org/zaproxy/zap/extension/websocket/client/WebSocketProxyUnitTest.java
Waiting interval increased because sometimes the tests fail.
> Increase waiting interval at WebSocketProxyUnitTest by 10ms

- src/org/zaproxy/zap/extension/ascanrules/CommandInjectionPlugin.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- test/org/zaproxy/zap/extension/ascanrules/CommandInjectionPluginUnitTest.java
Change CommandInjectionPlugin to replace the time token directly without
using MessageFormat, some of the payloads are quoted which would prevent
the replacement (while one could escape the quotes and keep using the
MessageFormat it would make the payloads harder to read and maintain).
Add test to assert the expected behaviour.
---
From OWASP ZAP User Group: https://groups.google.com/d/topic/zaproxy-users/JUQFaBTRYwo/discussion
> ascanrules: correct time replacement

- src/org/zaproxy/zap/extension/saml/SAMLExtension.java
- src/org/zaproxy/zap/extension/saml/ZapAddOn.xml
- src/org/zaproxy/zap/extension/saml/ui/SamlExtentionSettingsUI.java
Change SAMLExtension to declare that it can be unloaded.
Change SamlExtentionSettingsUI to dispose when exited, to be GC'ed
sooner.
> saml: dynamically unload the add-on

- src/org/zaproxy/zap/extension/ascanrules/CommandInjectionPlugin.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrules/CookieUtils.java
- test/org/zaproxy/zap/extension/ascanrules/CommandInjectionPluginUnitTest.java
- test/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScannerUnitTest.java
Replace literal strings with the corresponding core rule configuration
constants. The add-ons are already targeting the minimum required ZAP
version.
Update changes in ZapAddOn.xml file (where needed).
> Use core rule config constants

- src/org/zaproxy/zap/extension/ascanrulesBeta/Csrftokenscan.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionHypersonic.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionMySQL.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionPostgresql.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ShellShockScanner.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/CSRFCountermeasures.java
Replace literal strings with the corresponding core rule configuration
constants. The add-ons are already targeting the minimum required ZAP
version.
> Use core rule config constants (beta)

- src/org/zaproxy/zap/extension/exportreport/export/ReportExport.java
- src/org/zaproxy/zap/extension/saml/SAMLConfiguration.java
Change ReportExport and SAMLConfiguration to use the add-on classloader
when creating the JAXBContext to ensure the add-ons are searched when
loading JAXB-API implementation, for when the add-ons bundle it.
Part of:
- zaproxy/zaproxy#4214 - Unable to create reports with Export Report
add-on and Java 9
- zaproxy/zaproxy#5032 - SAML add-on leads to errors with Java 9+
> Use add-on classloader when creating JAXBContext

- src/org/zaproxy/zap/extension/ascanrulesAlpha/SQLInjectionMsSQL.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/LinkTargetScanner.java
Replace literal string with corresponding core rule config constant.
Update changes in ZapAddOn.xml file and update minimum ZAP version,
required to use the constant.
Add TODO task to LinkTargetScanner to replace one rule config when
available.
> Use core rule config constants (alpha)

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestZapUtils.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestActionDialog.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestAssertionsDialog.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestAssignmentDialog.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestClientElementAssignDialog.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestClientElementDialog.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestClientElementSendKeysDialog.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestClientLaunchDialog.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestClientSwitchToFrameDialog.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestClientWindowHandleDialog.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestControlDialog.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestCookieDialog.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestExpressionDialog.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestLoopDialog.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestParameterDialog.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestRequestDialog.java
Set the popup menu into the text fields so that the popup menu can be
invoked with mouse (as before) and keyboard.
> zest: allow to invoke popup menu with keyboard

- src/org/zaproxy/zap/extension/exportreport/export/ReportExport.java
- src/org/zaproxy/zap/extension/saml/SAMLConfiguration.java
Use own add-on classloader instead of the main add-on classloader to
prevent one add-on from using the bundled JAXB-API implementation of
the other.
Follow up on #1833.
> Use own add-on classloader for JAXBContext

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/dialogs/ZestClientSwitchToFrameDialog.java
Change ZestClientSwitchToFrameDialog to use a DocumentListener for the
name and ChangeListener for the index, to properly react to changes in
those fields.
> zest: fix listeners in Switch To Frame dialogue

- src/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java
- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
Change SpiderThread to get the WebDriver using AJAX_SPIDER_INITIATOR
instead of SPIDER_INITIATOR.
> spiderAjax: correct WebDriver requester ID

- src/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
- src/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
- src/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html
Link to pages that show which versions of the browsers are supported by
the corresponding WebDriver implementations.
> webdrivers: add links to geckodriver/ChromeDriver

- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
- src/org/zaproxy/zap/extension/selenium/internal/BuiltInSingleWebDriverProvider.java
Disable Firefox JSON viewer when returning a WebDriver for AJAX Spider
to prevent the spider from crawling it.
Add static methods to ExtensionSelenium to allow to get a WebDriver with
a requester and Browser, to be used by BuiltInSingleWebDriverProvider.
Change BuiltInSingleWebDriverProvider to call the new methods.
> selenium: disable JSON viewer for AJAX Spider

- test/org/zaproxy/zap/extension/websocket/client/WebSocketProxyUnitTest.java
- test/org/zaproxy/zap/testutils/websocket/server/NanoWebSocketConnection.java
Change WebSocketProxyUnitTest.shouldAnswerToPingWithPong to wait (with
a timeout of 2 seconds) for the expected number of pongs instead of
sleep some time.
Change NanoWebSocketConnection to allow to set a listener to be notified
of the messages (e.g. pongs) received, to support the previous case.
---
Per comments in #1849.
> websocket: wait for all expected pongs

- src/org/zaproxy/zap/extension/communityScripts/ExtensionCommunityScripts.java
Normalise indentation and license header of ExtensionCommunityScripts
to eliminate changes when migrating to community-scripts repository (the
format/license is already being enforced there).
The class CommunityScriptFiles was not normalised, it will not be
migrated (superseded by the build).
> communityScripts: normalise license header/code

- build/build.xml
- src/org/zaproxy/zap/extension/replacer/ReplacerAPI.java
- src/org/zaproxy/zap/extension/replacer/ZapAddOn.xml
- build.xml > Added "deploy-replacer-without-help-indexes" target for quick dev builds.
- ReplacerAPI.java > Moved PARAM_REPLACEMENT to optional param list.
- ZapAddOn.xml > Updated changes section.
Fixes zaproxy/zaproxy#5080
> Issue 5080 - Replacer API "Replacement" shouldn't be mandatory

- src/org/zaproxy/zap/extension/webdriverlinux/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
- src/org/zaproxy/zap/extension/webdrivermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
- src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html
Update geckodriver to 0.23.0 and ChromeDriver to 2.43.
Update help pages.
----
Depends on zaproxy/zap-libs#27.
> webdrivers: update geckodriver and ChromeDriver

- build/build.xml
- src/org/zaproxy/zap/extension/webdriverlinux/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
- src/org/zaproxy/zap/extension/webdrivermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
- src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html
Correct the link to ChromeDriver downloads page.
Add tasks to generate the wiki pages.
> webdrivers: fix link in help page

- test/org/zaproxy/zap/extension/groovy/VerifyScriptTemplates.java
- test/org/zaproxy/zap/testutils/AbstractVerifyScriptTemplates.java
Extract a class from groovy's VerifyScriptTemplates class to match the
class used by other scripting (beta) add-ons (e.g. Zest, Jython, JRuby),
to reduce the changes needed when merging the branches.
> Extract class for verification of script templates

- src/org/zaproxy/zap/extension/accessControl/AccessControlScannerThread.java
- src/org/zaproxy/zap/extension/accessControl/ZapAddOn.xml
Change AccessControlScannerThread to notify that it has finished in a
finally block to ensure it's always done. Also, catch and log any
exceptions that might occur during the test.
Related to zaproxy/zaproxy#5097 - Catch credentials exception when
authenticating
> accessControl: notify test finished, always

- src/org/zaproxy/zap/extension/accessControl/AccessControlAlertsProcessor.java
- src/org/zaproxy/zap/extension/accessControl/ZapAddOn.xml
- src/org/zaproxy/zap/extension/accessControl/resources/Messages.properties
Change the alerts to use other info field instead of attack/evidence
fields, the info provided is not the attack nor the evidence (as
expected for those fields).
> accessControl: do not use attack/evidence fields

- src/org/zaproxy/zap/extension/ApiGenerator.java
Change ApiGenerator to include the SOAP Scanner add-on.
> Include SOAP API when generating API clients

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestZapUtils.java
- test/org/zaproxy/zap/extension/zest/ZestZapUtilsUnitTest.java
Change ZestZapUtils to not drop the first header when converting the ZAP
request to Zest request, the method HttpHeader#getHeadersAsString()
returns just the headers so no header should be dropped.
Add tests to assert the expected behaviour.
Fix zaproxy/zaproxy#5100 - Some Zest Scripts Drop Every Topmost Request
Header
> zest: correct request conversion

- build/build.xml
- src/lang/Messages.properties
- src/org/zaproxy/zap/extension/api/ApiGenerator.java
Add target generate-apis to build.xml file.
Move ApiGenerator to api package to access core class.
Change ApiGenerator to make use of the new core method (>=2.8.0) which
allows to pass a ResourceBundle, to include the descriptions of the API
endpoints being generated.
Add dummy Messages.properties to be able to work with ZAP 2.7.0.
For zaproxy/zaproxy#5044 - NodeJS API Upgrade
> Add build target to generate the APIs (alpha)

- build/build.xml
- src/lang/Messages.properties
- src/org/zaproxy/zap/extension/api/ApiGenerator.java
Add target generate-apis to build.xml file.
Move ApiGenerator to api package to access core class.
Change ApiGenerator to make use of the new core method (>=2.8.0) which
allows to pass a ResourceBundle, to include the descriptions of the API
endpoints being generated.
Add dummy Messages.properties to be able to work with ZAP 2.7.0.
For zaproxy/zaproxy#5044 - NodeJS API Upgrade
> Add build target to generate the APIs (beta)

- build/build.xml
- src/lang/Messages.properties
- src/org/zaproxy/zap/extension/api/ApiGenerator.java
Move ApiGenerator to api package to access core class.
Add Websocket API to ApiGenerator.
Change ApiGenerator to make use of the new core method (>=2.8.0) which
allows to pass a ResourceBundle, to include the descriptions of the API
endpoints being generated.
Add dummy Messages.properties to be able to work with ZAP 2.7.0.
Update generate-apis in build.xml file to include just the required
files on the classpath and to depend on compile to work by itself.
For zaproxy/zaproxy#5044 - NodeJS API Upgrade
> Update API generator for 2.7.0 and 2.8.0

- src/org/zaproxy/zap/extension/jxbrowser/JxBrowserDownload.java
- src/org/zaproxy/zap/extension/jxbrowserlinux64/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowserlinux64/selenium/ExtSelJxBrowserLinux64.java
- src/org/zaproxy/zap/extension/jxbrowserlinux64/selenium/JxBrowserProvider.java
- src/org/zaproxy/zap/extension/jxbrowsermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowsermacos/selenium/JxBrowserProvider.java
- src/org/zaproxy/zap/extension/jxbrowsermacos/selenium/MacOsJxBrowserProvider.java
- src/org/zaproxy/zap/extension/jxbrowserwindows/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowserwindows/selenium/ExtSelJxBrowserWindows.java
- src/org/zaproxy/zap/extension/jxbrowserwindows/selenium/JxBrowserProvider.java
- src/org/zaproxy/zap/extension/jxbrowserwindows64/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowserwindows64/selenium/ExtSelJxBrowserWindows64.java
- src/org/zaproxy/zap/extension/jxbrowserwindows64/selenium/JxBrowserProvider.java
Bundle compatible ChromeDriver (v2.37) in OS specific JxBrowser add-ons.
Change JxBrowserProvider to use the bundled ChromeDrivers.
Change JxBrowserDownload to download the ChromeDrivers.
Change ZapAddOn.xml files to no longer depend on the WebDriver add-ons
and to declare the bundled files.
---
Depends on zaproxy/zap-libs#29.
> jxbrowsers: bundle compatible ChromeDriver

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestZapRunner.java
Change ZestZapRunner to not set the script console writer as output
writer if the script context writer is already set, while both end up in
the script console the latter allows the core to intercept the writes.
For the cases the context writer is not set the writes are not
intercepted.
Related to zaproxy/zaproxy#5113 - Allow to differentiate scripts' output
> zest: rely on script context writer

- src/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html
Remove the entry that has the version as a to do, the version is now
reported per changes done #1541.
---
Spotted while reviewing the add-on for a new release.
> wappalyzer: update help

- src/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
The current ASP 'On Error Resume Next' source disclosure detection pattern also matches Rx.Observable.onErrorResumeNext in RxJS because it specifies any amount of whitespace between the terms (including none). The latter executes in the browser, and so must be disclosed!
> Fix source disclosure false positive 

- test/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScannerUnitTest.java
Change test class to extend from PassiveScannerTestUtils instead,
removing the dependency on classes from other add-on.
> wappalyzer: correct test class inheritance

- test/org/zaproxy/zap/testutils/PassiveScannerTestUtils.java
Change PassiveScannerTestUtils to assert that the alerts raised have the
attack field empty and the expected scanner ID.
Related to zaproxy/zaproxy#5061 and referenced issues.
> Add default assertions to passive alerts

- src/org/zaproxy/zap/extension/pscanrulesAlpha/InsecureFormLoadScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/InsecureFormPostScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/UserControlledCharsetScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/UserControlledCookieScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/UserControlledHTMLAttributesScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/UserControlledJavascriptEventScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
- test/org/zaproxy/zap/testutils/PassiveScannerTestUtils.java
Change UserControlledCharsetScanner to not set the attack field in the
alert, instead mention that in the description. Also, remove unused
parameter.
Change UserControlledCookieScanner to not set the attack field in the
alert, instead mention that in the extra info. Fix zaproxy/zaproxy#5149.
Change InsecureFormLoadScanner, UserControlledHTMLAttributesScanner,
InsecureFormPostScanner, and UserControlledJavascriptEventScanner to not
read the (empty) resource message for the attack field.
Remove other empty and unused attack resource messages, should not be
needed.
Change PassiveScannerTestUtils to assert that the alerts raised have the
attack field empty and the expected scanner ID.
Related to zaproxy/zaproxy#5061 and referenced issues.
> Add default assertions to passive alerts (alpha)

- src/org/zaproxy/zap/extension/ascanrulesBeta/CrossDomainScanner.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
Change CrossDomainScanner to return empty strings for the description
and solution instead of trying to get the resource messages (which do
not exist), the alerts being raised do not use those methods but
external code might still call them which would lead to exception or
errors.
> ascanrulesBeta: fix missing resource messages

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestHttpSenderRunner.java
Change ZestHttpSenderRunner to not check if the request/response header
is empty to stop processing the message, that behaviour does not apply
to HTTP Sender scripts only Proxy.
> zest: correct message handling in HTTP Sender

- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
Change ExtensionSelenium to disable Firefox captive check for all
requesters not just AJAX Spider, it is generally useful to avoid
unwanted requests.
From zaproxy/zap-hud#328.
> selenium: disable Firefox captive check always

- src/org/zaproxy/zap/extension/websocket/WebSocketAPI.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
Adds a wrapper around all of the API responses, but only if the user supplies an 'id' - if they dont then no response is sent. If the user also supplies a 'caller' (eg for routing) then this is also returned.
Without this its not really possible for the caller to work out which response is for which request.
Required for the HUD :)
> Add wrapper to websocket API responses.

- src/org/zaproxy/zap/extension/pscanrulesAlpha/HashDisclosureScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
Unlike `Mac OS X salted SHA-1`, which really has a MEDIUM
confidence level (because it will match any long hex string),
hashes with very specific patterns, such as
`$NT$7f8fe03093cc84b267b109625f6bbf4b` have now an HIGH
confidence, as they are very unlikely to be false positives
> Update confidence level for reliable hash patterns

- src/org/zaproxy/zap/extension/groovy/ZapAddOn.xml
- src/org/zaproxy/zap/extension/groovy/resources/help/contents/about.html
Update ZapAddOn.xml and about help page to mention that the add-on is
now using Semantic Versioning (change done in #1639).
> groovy: mention SemVer change

- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
Change ExtensionSelenium to just quit the WebDrivers, calling also close
leads to WebDriver process leaks (e.g. geckodriver) if the browser was
previously closed.
> selenium: just quit the WebDrivers

- src/org/zaproxy/zap/extension/websocket/WebSocketProxy.java
- src/org/zaproxy/zap/extension/websocket/WebSocketProxyV13.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
Change WebSocketProxy to always use the local output stream when in
server mode (there's no remote to read/write to).
Change WebSocketProxyV13 to warn when no output stream exists (shouldn't
happen under normal conditions).
> websocket: correct output stream used for server

- src/org/zaproxy/zap/extension/websocket/WebSocketAPI.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
Change WebSocketAPI to validate that the origin of the WebSocket
handshake is the expected one (that is, zap domain).
> websocket: validate the Origin for API connections

- src/org/zaproxy/zap/extension/frontendscanner/ExtensionFrontEndScanner.java
- src/org/zaproxy/zap/extension/frontendscanner/FrontEndScannerAPI.java
- src/org/zaproxy/zap/extension/frontendscanner/files/frontendscanner/front-end-scanner.js
Use `handleCallBack` in FrontEndScannerAPI to serve the `front-end-scanner.js` code.
Tried to stay close to the "pattern" used to inject files in the HUD.
> [FrontEndScanner] Do not inject inlined JS

- src/org/zaproxy/zap/extension/frontendscanner/FrontEndScannerAPI.java
Change FrontEndScannerAPI to set the URI and the HTTP message to the
Alert being raised, otherwise it's not properly processed by core. Also,
for consistency set the HistoryReference.
> frontendscanner: set URI and message to alerts

- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
Change ExtensionSelenium to add an argument to ChromeOptions to not
bypass localhost when proxying, thanks to:
https://github.com/cypress-io/cypress/issues/1872#issuecomment-450800890
for the syntax to use with `proxy-bypass-list`.
> selenium: proxy "localhost" in Chrome 72

- src/org/zaproxy/zap/extension/ascanrulesAlpha/CloudMetadataScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
Thanks to @thc202 for the magic which preserves the Host header.
I've tested this and the host header is correctly sent.
However I havnt actually got a failing server to test this on :/
Confidence is currently LOW as it just checks for a non failing response code. Hopefully we can improve that if and when we get some failing servers to test with.
> Added Cloud Metadata Scanner

- .travis.yml
Remove the `sudo: false` configuration, the builds run now always in the
same (new) infrastructure regardless of the configuration.
---
To keep in sync with master.
> Remove obsolete Travis CI configuration (beta)

- .travis.yml
Remove the `sudo: false` configuration, the builds run now always in the
same (new) infrastructure regardless of the configuration.
---
To keep in sync with master.
> Remove obsolete Travis CI configuration (alpha)

- src/org/zaproxy/zap/extension/importurls/ImportUrlsAPI.java
- src/org/zaproxy/zap/extension/plugnhack/PlugNHackAPI.java
- src/org/zaproxy/zap/extension/replacer/ReplacerAPI.java
Make it easier to generate the API client files, by programmatically
instantiate all the APIs with the default constructor.
> Add default constructor to APIs (beta)

- src/org/zaproxy/zap/extension/importLogFiles/ImportLogAPI.java
- src/org/zaproxy/zap/extension/openapi/OpenApiAPI.java
- src/org/zaproxy/zap/extension/soap/SoapAPI.java
Make it easier to generate the API client files, by programmatically
instantiate all the APIs with the default constructor.
> Add default constructor to APIs (alpha)

- src/org/zaproxy/zap/extension/reveal/RevealAPI.java
- src/org/zaproxy/zap/extension/selenium/SeleniumAPI.java
- src/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderAPI.java
- src/org/zaproxy/zap/extension/websocket/WebSocketAPI.java
Make it easier to generate the API client files, by programmatically
instantiate all the APIs with the default constructor.
> Add default constructor to APIs

- src/org/zaproxy/zap/extension/selenium/Browser.java
- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
- src/org/zaproxy/zap/extension/selenium/SeleniumOptions.java
- src/org/zaproxy/zap/extension/selenium/SeleniumOptionsPanel.java
- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
- src/org/zaproxy/zap/extension/selenium/resources/Messages.properties
- src/org/zaproxy/zap/extension/selenium/resources/help/contents/api.html
- src/org/zaproxy/zap/extension/selenium/resources/help/contents/intro.html
- src/org/zaproxy/zap/extension/selenium/resources/help/contents/options.html
- test/org/zaproxy/zap/extension/selenium/BrowserUnitTest.java
- test/org/zaproxy/zap/extension/selenium/BrowsersComboBoxModelUnitTest.java
No longer allow to choose Internet Explorer or configure the path to
IEDriverServer, the browser no longer starts as it does not support the
required capabilities (`acceptInsecureCerts`).
Update help accordingly.
Per reports in zaproxy/zaproxy#5213.
> selenium: remove IE support

- src/org/zaproxy/zap/extension/webdriverwindows/WebdriverDownload.java
- src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html
The Selenium add-on no longer supports it (#1947).
Update help accordingly.
> webdriverwindows: remove IEDriverServer

- src/org/zaproxy/zap/extension/jxbrowser/ExtensionJxBrowser.java
- src/org/zaproxy/zap/extension/jxbrowser/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowser/resources/Messages.properties
Fix typo in the initial message shown in the browser window (missing
space between "browsers" and "to").
Remove references to the ChromeDriver and Selenium help page in the
message that indicates that the browser failed to start, the driver is
now bundled in the JxBrowser add-ons.
Log the JxBrowser version used by the add-on, to be easier to know which
version is in use.
> jxbrowser: tweak messages and log browser version

- src/org/zaproxy/zap/extension/websocket/WebSocketAPI.java
- src/org/zaproxy/zap/extension/websocket/WebSocketEventPublisher.java
The channelHost field is so that we can filter on the host in the HUD,
and the net.fs.json classes were autoconverting valid JSON strings into JSON which we really dont want.
Fixes https://github.com/zaproxy/zap-hud/issues/433
> WebSockets - add channelHost and fix encodings

- src/org/zaproxy/zap/extension/websocket/WebSocketMessage.java
- src/org/zaproxy/zap/extension/websocket/brk/WebSocketProxyListenerBreak.java
Not surprisingly this was found with the HUD.
Set websockets to break on the 'all request/response' break buttons and the HUD becomes unusable ;)
> Dont break on websocket API calls

- src/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
Change ExtensionSelenium to quit the WebDrivers of the provider being
removed, to prevent leaks and avoid other issues.
> selenium: quit WebDrivers when removing provider

- src/org/zaproxy/zap/extension/pscanrulesAlpha/PiiScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- test/org/zaproxy/zap/extension/pscanrulesAlpha/PiiScannerUnitTest.java
- PiiScanner add word boundary checks to reduce false positives.
- Added unittest and a utility method for message creation.
- Updated manifest.
- Fixed typo in `MAESTRO` enum name.
https://www.regexplanet.com/share/index.html?share=yyyyyq6d1nr (Click java, then test)
Fixes zaproxy/zaproxy#5124
> PiiScanner Add Word Boundary Check

- src/org/zaproxy/zap/extension/cmss/ZapAddOn.xml
- src/org/zaproxy/zap/extension/saml/ZapAddOn.xml
- src/org/zaproxy/zap/extension/vulncheck/ZapAddOn.xml
The info URLs linked to the main repo, which does not provide any info
about the add-ons.
> Remove redundant add-ons' info URLs

- src/org/zaproxy/zap/extension/imagelocationscanner/ZapAddOn.xml
- src/org/zaproxy/zap/extension/imagelocationscanner/resources/help/contents/about.html
Correct the repo URL in about help page.
> imagelocationscanner: correct URL in help page

- src/org/zaproxy/zap/extension/pscanrulesAlpha/HashDisclosureScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- test/org/zaproxy/zap/extension/pscanrulesAlpha/HashDisclosureScannerUnitTest.java
- HashDisclosureScanner - Update MD4/MD5 regex. https://www.regexplanet.com/share/index.html?share=yyyyu0ua0ar
- HashDisclosureScannerUnitTest - Created, adding unit tests.
- ZapAddOn.xml - Updated changes section with new entry.
Fixes zaproxy/zaproxy#5215
> Fix Issue 5215 - HashDisclosureScanner ignore obvious jsessionid Values

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/dialogs/ZestDialogManager.java
Change ZestDialogManager to remove the Scripts tree selection listener
when unloaded.
> zest: remove tree selection listener on unload

- addOns/fuzzdb/fuzzdb.gradle.kts
Prevent the home files from being compiled by Eclipse, the files are not
intended to be compiled (and just leads to errors).
> fuzzdb: prevent compilation in Eclipse

- addOns/webdrivers/webdriverlinux/CHANGELOG.md
- addOns/webdrivers/webdriverlinux/src/main/javahelp/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
- addOns/webdrivers/webdrivermacos/CHANGELOG.md
- addOns/webdrivers/webdrivermacos/src/main/javahelp/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
- addOns/webdrivers/webdrivers.gradle.kts
- addOns/webdrivers/webdriverwindows/CHANGELOG.md
- addOns/webdrivers/webdriverwindows/src/main/javahelp/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html
upgrading geckodriver version to `0.24.0` for issue Fixes zaproxy/zaproxy#5273
upgrading chromedriver version to `74.0.3729.6 ` for issue Fixes zaproxy/zaproxy#5274
> updated geckodriver and chromedriver webdriver versions.

- buildSrc/build.gradle.kts
- buildSrc/src/main/java/org/zaproxy/gradle/tasks/ProcessSvnDiggerFiles.java
Force use of Commons Codec 1.11 (instead of 1.10 from transitive
dependencies of WebDriverManager) as it's required by the ZAP plugin
when generating the ZapVersions data.
Ensure the SvnDigger output directory is clean (by removing it) before
processing the files to avoid stale files/directories.
> Fix build issues

- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ApacheRangeHeaderDos.java
As stated in https://httpd.apache.org/security/CVE-2011-3192.txt "Request-Range" is legacy so it is good to send both "Range" and "Request-Range". But "Range-Request" does not exist.
> Fixed wrong header name "Request-Range"

- addOns/saml/CHANGELOG.md
- addOns/saml/saml.gradle.kts
- addOns/saml/src/main/java/org/zaproxy/zap/extension/saml/SAMLMessage.java
replaced joda.time.datetime with java.time.localtime (JDK8). Fixes zaproxy/zaproxy#5301.
> replaced joda.time.datetime with java.time.localtime (JDK8).

- addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentTypeMissingScannerUnitTest.java
Initial unittest for ContentTypeMissingScanner.
Fixes zaproxy/zaproxy#2787
> Content-Type Missing Scanner Unit Test

- addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/InformationDisclosureInURL.java
Remove test code in `InformationDisclosureInURL`, there's already an
issue to add proper tests: zaproxy/zaproxy#2803.
> pscanrulesBeta: remove manual test code

- addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
- addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/PatternErrorHandler.java
- addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java
- addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerAppsJsonParseUnitTest.java
Add unittest and remove main method from ExtensionWappalyzer. If (when) someone does an apps.json upgrade (from AliasIO/wappalyzer) any failing patterns should be removed. (Per discussion in IRC and other PRs.)
Thanks to @thc202 for all the advice, collaboration, and extreme patience on this!
See https://travis-ci.com/zaproxy/zap-extensions/jobs/192365059 for PoC.
> wappalyzer: Add apps.json Parsing UnitTest

- addOns/addOns.gradle.kts
Change to link to the tag of the add-on (instead of being tied to the
current ZAP release, e.g. tag 2.7).
> Change the download URL of the add-ons

- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
The old reference link for the alert "Web Browser XSS Protection Not Enabled" no longer works. Updated with a new link.
> Updated an alert reference link

- build.gradle.kts
- gradle/travis-ci.gradle.kts
Use full format to output the stack trace when the tests fail, to make
it easier to know where it's failing.
---
(Same behaviour as in zap-hud repo.)
> Include test stack trace when running in Travis CI

- addOns/httpsInfo/CHANGELOG.md
- addOns/httpsInfo/httpsInfo.gradle.kts
- addOns/httpsInfo/src/main/java/org/zaproxy/zap/extension/httpsinfo/HttpsInfoOutputPanel.java
* Remove lib/dvAPI_5.0.3.jar
* httpsInfo.gradle.kts - Remove local lib reference and use 5.1.16 from maven.
* HttpsInfoOutputPanel - Minor changes for compatability with latest DV, and to correct incorrect logger setup.
* Updated changelog.
Fixes zaproxy/zaproxy#5254
> HttpsInfo: Update DeepViolet

- addOns/openapi/CHANGELOG.md
- addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
Change ExtensionOpenApi to check if the exception has a message before
processing it (thus preventing the NPE).
---
Reported in OWASP ZAP User Group:
https://groups.google.com/d/topic/zaproxy-users/c9HhSOB7ieU/discussion
> openapi: fix NPE when reporting errors

- build.gradle.kts
- gradle/lgtm.gradle.kts
- gradle/travis-ci.gradle.kts
The downloads fail too often breaking the analysis, while not required.
Change Travis CI tweaks to configure all test tasks in all projects, not
just the root project (which does not have any).
> Skip WebDriver downloads in LGTM builds

- addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
The version of the extension is not actually used by core.
> selenium: remove extension's version

- testutils/src/main/java/org/zaproxy/zap/testutils/TestUtils.java
Assert that the resource key exists also for the alert matchers, to
ensure all used keys exist.
> testutils: assert resource key for alert matchers

- .github/main.workflow
- buildSrc/src/main/java/org/zaproxy/gradle/tasks/CreateGitHubRelease.java
Use empty login name when creating the GitHub API instance to avoid
requesting the login name (which is not accessible).
Execute the filters sequentially and the tag filter first, to stop
earlier and with neutral result.
> Fix release on tag

- addOns/addOns.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/java/org/zaproxy/gradle/tasks/PrepareAddOnNextDevIter.java
- buildSrc/src/main/java/org/zaproxy/gradle/tasks/PrepareAddOnRelease.java
Add the following tasks to help with the release process:
- `prepareAddOnRelease` to update the changelog with the release date
and link to the GitHub release;
- `prepareAddOnNextDevIter` to add the unreleased section to changelog
and bump the version in the build file.
> Add helper release tasks

- addOns/wappalyzer/CHANGELOG.md
- addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html
Change help page to use HTTPS for Wappalyzer home page (and link once).
> wappalyzer: prepare release

- addOns/addOns.gradle.kts
The generation of the ZapVersions.xml data will be done in the zap-admin
repository when needed.
> Remove ZapVersions configuration

- addOns/httpsInfo/CHANGELOG.md
- addOns/httpsInfo/httpsInfo.gradle.kts
* Updated CHANGELOG.md based on `./gradlew :addOns:httpsinfo:pAOR`
* Minor change to httpsInfo.gradle.kts so that wiki generation will work (while httpsinfo uses a different prefix vs other add-ons)
> httpsinfo Prepare Release

- buildSrc/src/main/java/org/zaproxy/gradle/tasks/PrepareAddOnNextDevIter.java
- buildSrc/src/main/java/org/zaproxy/gradle/tasks/PrepareAddOnRelease.java
Add group/desc to `PrepareAddOnRelease` and `PrepareAddOnNextDevIter`.
Change `PrepareAddOnRelease` to not add a new line when inserting the
link to the tag if the previous line is empty.
> Tweaks to release related tasks

- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ViewstateScanner.java
2012 based on:
https://github.com/zaproxy/zap-extensions/commit/1ae748d5346ace3843648ba7374244fdc4aaa343#diff-e465b5d5344c14fb9a37701810248775
It took me quite a while to track that down. If anyone has advice on searching repo history I'm all ears (Eclipse or CLI).
Edit: I came up with this after going through a bunch of pain via the github web UI: `git log --before="2012-12-31" -Sviewstate` or `git log --before="2012-12-31" -Sviewstate --pretty="%h - %ad - %s"`
> Add License to ViewState Scanner
