- src/org/zaproxy/zap/extension/fuzz/impl/FuzzMessageLocationsPanel.java
- src/org/zaproxy/zap/extension/fuzz/impl/MessageLocationPayloadsPanel.java
- src/org/zaproxy/zap/extension/fuzz/impl/ProcessorsMessageLocationDialog.java
- src/org/zaproxy/zap/extension/fuzz/impl/ProcessorsPayloadDialog.java
Eclipse IDE for Java Developers
Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
> Fix build errors

- src/org/zaproxy/zap/extension/ascanrulesAlpha/FormatString.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
For Review on Issue #1558 for inclusion into Alpha Extensions
> Alpha  Review for issue #1558 via pull request

- src/org/zaproxy/zap/extension/ascanrulesBeta/BufferOverflow.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
This should have all of the things you found fixed.
> Issue zaproxy/zaproxy#1605 New pull request after re-syncing fork.

- src/org/zaproxy/zap/extension/ascanrules/BufferOverflow.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
Attached is the buffer overflow code for change from Beta to release.
> Issue zaproxy/zaproxy#1790  Move Buffer Overflow Scanner from Beta to Release

- .gitignore
- src/com/sittinglittleduck/DirBuster/Worker.java
I am trying to get a general understanding about how Force Browser works. As part of that, I am refactoring the Worker class. This pull request is part of this refactoring and I would like to get some feedback (and some testing as well) before I proceed. For now, I extracted common methods, but I am planning to extract classes and make Worker simpler.
> General refactoring on DirBuster Worker

- src/org/zaproxy/zap/extension/ascanrules/FormatString.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
I want to move Format String from Beta to Release.  I also updated ascanrules.html to
re-alphabetize the listings.
> zaproxy/zaproxy #1937.  This is a request for review to move Format String from Beta to Release

- src/org/zaproxy/zap/extension/ascanrulesAlpha/TestUserAgent.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
Check for differences in content based on User Agent. Different content could be returned if there is a mobile site. Some websites provides different content if a search engine Crawler access the site.
> Implemented new ascanrule TestUserAgent

- src/org/zaproxy/zap/extension/ascanrulesAlpha/IntegerOverflow.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
> zaproxy/zaproxy #1846 Review for Alpha Inclusion

- src/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
which be accessed => which can be accessed
> Fixed typo in ascanrules directorybrowsing

- src/org/zaproxy/zap/extension/ascanrulesAlpha/IntegerOverflow.java
> Fix False Positives in Integer Overflow.

- src/org/zaproxy/zap/extension/advreport/AlertDetailsPanel.java
- src/org/zaproxy/zap/extension/advreport/AlertsPanel.java
- src/org/zaproxy/zap/extension/advreport/ExtensionAdvReport.java
- src/org/zaproxy/zap/extension/advreport/OptionDialog.java
- src/org/zaproxy/zap/extension/advreport/ScopePanel.java
- src/org/zaproxy/zap/extension/advreport/resources/Messages.properties
Added internationalization and the Messages.properties file to the advreport extension.
> advreport: added internationalization

- src/org/zaproxy/zap/extension/ascanrulesAlpha/IntegerOverflow.java
Fix adding targets(TechSet technologies)
> Added targets(TechSet technologies)

- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/ExtensionHttpFuzzer.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/tagcreator/ExtractByRegexTagRule.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/tagcreator/HttpFuzzerMessageProcessorTagCreator.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/tagcreator/HttpFuzzerMessageProcessorTagStateHighlighter.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/tagcreator/HttpFuzzerMessageProcessorTagUI.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/tagcreator/HttpFuzzerMessageProcessorTagUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/tagcreator/HttpFuzzerMessageProcessorTagUIPanel.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/tagcreator/HttpResponseTagCreator.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/tagcreator/MatchByRegexTagRule.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/tagcreator/RegexTagRule.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/tagcreator/TagRule.java
- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
- test/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/tagcreator/HttpResponseTagCreatorUnitTest.java
Fuzzer Message Processor analyses response header and response body. The Processor tags the response in the fuzzer result table if configured Regex is matching.
Related Issue: https://github.com/zaproxy/zaproxy/issues/1866
> New Fuzzer Message Processor which create tags based on Regex

- src/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleFileActiveScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleSimpleActiveScanner.java
Added targets(TechSet technologies) and IOException to ExampleFileActiveScanner and ExampleSimpleActiveScanner to make them consistent with new methods.
> Added targets(TechSet technologies) and IOException to Various Files.

- src/org/zaproxy/zap/extension/customreport/resources/help/contents/customreport.html
- src/org/zaproxy/zap/extension/customreport/resources/help/helpset.hs
- src/org/zaproxy/zap/extension/customreport/resources/help/index.xml
- src/org/zaproxy/zap/extension/customreport/resources/help/map.jhm
- src/org/zaproxy/zap/extension/customreport/resources/help/toc.xml
Added help pages to the customreport add-on.
> customreport: added help pages

- src/org/zaproxy/zap/extension/ascanrules/TestExternalRedirect.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
> Fixed incorrect i18n string being used which caused the External

- src/org/zaproxy/zap/extension/fuzz/payloads/generator/ScriptStringPayloadGeneratorAdapter.java
Change ScriptStringPayloadGeneratorAdapter to just use once the script
instance when returning an iterator, to prevent the script from being
used by several iterators at the same time which would lead to wrong
iteration of the payloads.
Change to cache the number of payloads from the script (to avoid
creating another instance when the old script instance is no longer
available).
Change to return a new instance when copy() is called, to prevent
reusing the script instance.
Issue introduced in @f0dc4bde81647cee019040a771215fe2f74db4a0.
> fuzz: change script payload generator to not reuse the script instance

- src/org/zaproxy/zap/extension/fuzz/payloads/generator/CompositePayloadGenerator.java
Change CompositePayloadGenerator$CompositeIterator to reset the existing
iterators when reset() is called instead of creating new iterators, it
might be more expensive to (re)create the iterators than just reset the
existing ones (for example, creation of a ScriptPayloadGeneratorIterator
might require instantiate again the script, instead of just calling its
reset method). The change also ensures that the iterators are always
closed.
> fuzz: change CompositeIterator to reset the iterators on reset call

- src/org/zaproxy/zap/extension/customreport/AlertDetailsPanel.java
- src/org/zaproxy/zap/extension/customreport/AlertsPanel.java
- src/org/zaproxy/zap/extension/customreport/OptionDialog.java
- src/org/zaproxy/zap/extension/customreport/ReportGenerator.java
- src/org/zaproxy/zap/extension/customreport/ReportLastScan.java
- src/org/zaproxy/zap/extension/customreport/ReportParser.java
- src/org/zaproxy/zap/extension/customreport/ScopePanel.java
Added standard license headers.
> customreport: added license headers

- .gitignore
- src/org/zaproxy/zap/extension/ascanrulesBeta/IntegerOverflow.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
I want to get this moved to the next level.
> zaproxy/zaproxy issue #1986 Move Integer Overflow from Alpha to Beta

- src/org/zaproxy/zap/extension/codedx/CodeDxExtension.java
- src/org/zaproxy/zap/extension/codedx/ZapAddOn.xml
Change class CodeDxExtension to declare that it can be dynamically
unloaded (no other changes required to successfully unload the add-on).
> codedx: allow to dynamically update/uninstall the add-on

- src/org/zaproxy/zap/extension/pscanrulesBeta/CharsetMismatchScanner.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
Update to passive scan help related to previously provided fix. Fixup commit now also includes alignment with: https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsPscanrules#threshold
> zaproxy/zaproxy#1966 Charset Mismatch passive scanner updated help

- .classpath
- build/nbproject/project.properties
- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
Allow to use latest version of Firefox (43).
Fix zaproxy/zaproxy#2149 - When I run Ajax spider I get 'Failed to start
'Firefox', is the browser installed/available' pop up
> selenium: update Selenium library to version 2.48.2

- src/org/zaproxy/zap/extension/pscanrulesBeta/InsecureAuthenticationScan.java
Add missing WASC ID and CWE ID elements.
> InsecureAuthenticationScan address todo items

- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
Incorporate XCOLD in the alert name.
> New Passive Scanner for X-ChromeLogger-Data

- src/org/zaproxy/zap/extension/ascanrules/CodeInjectionPlugin.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrules/ContentTypeMissingScanner.java
- src/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanner.java
- src/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScanner.java
- src/org/zaproxy/zap/extension/pscanrules/CrossDomainScriptInclusionScanner.java
- src/org/zaproxy/zap/extension/pscanrules/MixedContentScanner.java
- src/org/zaproxy/zap/extension/pscanrules/PasswordAutocompleteScanner.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
> issue-823-i18n-active-passive-scan-rules-release

- src/org/zaproxy/zap/extension/ascanrules/CommandInjectionPlugin.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
Fixes zaproxy/zaproxy#2001
I haven't updated ZapAddOn.xml in this PR as there's another pending PR for the same package...not sure how we plan to handle such occurrences.
> Issue 2001 commandinjection add powershell variants

- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesBeta/files/xml/debug-error-messages.txt
Fixes zaproxy/zaproxy#316
I haven't updated ZapAddOn.xml in this PR as there's another pending PR for the same package...not sure how we plan to handle such occurrences.
> Issue 316 Requested addition 'information disclosure - debug error messages'

- src/org/zaproxy/zap/extension/ascanrulesBeta/Csrftokenscan.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ExpressionLanguageInjectionPlugin.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/PaddingOraclePlugin.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/XXEPlugin.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/XpathInjectionPlugin.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrulesBeta/InformationDisclosureDebugErrors.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/InformationDisclosureInURL.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/InformationDisclosureReferrerScanner.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/InformationDisclosureSuspiciousComments.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ServletParameterPollutionScanner.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ViewstateScanner.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
> issue-823-i18n-active-passive-scan-rules-beta

- src/org/zaproxy/zap/extension/ascanrulesAlpha/SourceCodeDisclosureGit.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
> issue-823-i18n-active-passive-scan-rules-alpha

- src/org/zaproxy/zap/extension/alertReport/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/beanshell/ZapAddOn.xml
- src/org/zaproxy/zap/extension/bruteforce/ZapAddOn.xml
- src/org/zaproxy/zap/extension/diff/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/importurls/ZapAddOn.xml
- src/org/zaproxy/zap/extension/invoke/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jruby/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jython/ZapAddOn.xml
- src/org/zaproxy/zap/extension/plugnhack/ZapAddOn.xml
- src/org/zaproxy/zap/extension/portscan/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/sqliplugin/ZapAddOn.xml
- src/org/zaproxy/zap/extension/svndigger/ZapAddOn.xml
- src/org/zaproxy/zap/extension/tips/ZapAddOn.xml
- src/org/zaproxy/zap/extension/tokengen/ZapAddOn.xml
- src/org/zaproxy/zap/extension/treetools/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
The change allows to have all add-ons (alpha, beta and release) in a
single branch.
Note: the build system does not yet use that information.
> Add add-on status to ZapAddOn.xml (beta)

- src/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureSVN.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
> Fix Source Code Disclosure SVN Throws False Positive

- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
Various help updates for active and passive scanners. To address deficiencies identified in a recent initiative to promote scanners between various quality levels.
Ref: https://groups.google.com/forum/#!topic/zaproxy-develop/kpxnenhuoJA
& https://docs.google.com/spreadsheets/d/1cmN-2A1wYBOqcOukOAwQe7wxpQyFBRspPZtcZ-a869A/edit?usp=sharing
> Help Updates for Beta Scanners

- src/org/zaproxy/zap/extension/pscanrulesAlpha/StrictTransportSecurityScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
Strict-Transport-Security Header Scanner added support for max-age=0 per
rfc6797
> new-sts-variant-max-age-zero

- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
Update version and remove old changes (while keeping the change already
done for new version) in ZapAddOn.xml file.
> ascanrulesBeta: prepare add-on for next/current development iteration

- src/org/zaproxy/zap/extension/ascanrulesBeta/ExpressionLanguageInjectionPlugin.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/HPP.java
Change log.info messages for specific exception catching to log.debug.
This aligns pull #221 and pull #228 with more recent comments on
pull #236.
> Align Logging

- src/org/zaproxy/zap/extension/ascanrules/TestRemoteFileInclude.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
> Prevent RFI FP when original title includes 'Google'

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestHttpSenderRunner.java
- src/org/zaproxy/zap/extension/zest/ZestScriptWrapper.java
- src/org/zaproxy/zap/extension/zest/files/scripts/templates/httpsender/HttpSender default template.zst
> Support httpsender scripts

- src/org/zaproxy/zap/extension/zest/ExtensionZest.java
- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestZapUtils.java
- src/org/zaproxy/zap/extension/zest/dialogs/ZestRequestDialog.java
- src/org/zaproxy/zap/extension/zest/menu/ZestPasteVariablePopupMenu.java
- src/org/zaproxy/zap/extension/zest/menu/ZestPopupZestDelete.java
Fixes zaproxy/zaproxy#2007
Fixes zaproxy/zaproxy#2106
Fixes zaproxy/zaproxy#2295
Fixes zaproxy/zaproxy#2296
> Fix context menu issues

- src/org/zaproxy/zap/extension/zest/ExtensionZest.java
- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
- src/org/zaproxy/zap/extension/zest/ZestTreeTransferHandler.java
Fixes zaproxy/zaproxy#2299
Fixes zaproxy/zaproxy#2302
> Fix statement lost after drag and drop #2299

- src/org/zaproxy/zap/extension/pscanrulesBeta/InsecureAuthenticationScan.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
This will fix the issue zaproxy/zaproxy#2230 in zaproxy.
> Fixes issue #2230

- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
Per:
https://github.com/zaproxy/zaproxy/wiki/DevGuidelines#style-guidelines
Related to zaproxy/zaproxy#2000
> pscanAlpha Title Caps Fixes

- src/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java
- src/org/zaproxy/zap/extension/alertFilters/ZapAddOn.xml
- src/org/zaproxy/zap/extension/alertFilters/resources/help/contents/alertFilter.html
> Context Alter Filter fixes

- .classpath
- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
> Updated to use Selenium 2.52.0 (Issue 2321)

- src/org/zaproxy/zap/extension/alertFilters/ContextAlertFilterPanel.java
- src/org/zaproxy/zap/extension/alertFilters/ZapAddOn.xml
- src/org/zaproxy/zap/extension/alertFilters/resources/Messages.properties
- src/org/zaproxy/zap/extension/alertFilters/resources/help/contents/alertFilter.html
In ContextAlertFilterPanel:
URL column can now be resized. While the Enabled column
has a max width (can be made smaller, but not bigger).
Various minor wording adjustments (in both properties 
and xml files), and help updates.
> Minor UI Improvements

- src/org/zaproxy/zap/extension/ascanrulesAlpha/HttpsAsHttpScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
Add missing @Override annotations.
Relocate isStop() check.
Adjust some of the logging from INFO to DEBUG.
Ensure consistent use of braces.
Improve otherinfo alert element.
Remove unnecessary comments.
Remove unnecessary use of the 'this' keyword.
> Https as Http Scanner Updates

- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionHypersonic.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
Added try/catch block around sendAndReceive for exceptions identified
via zapbot automated wavsep testing.
Fixes zaproxy/zaproxy#2272
> Issue 2272 Add Exception Handling

- src/org/zaproxy/zap/extension/httpsInfo/MDialog.java
- src/org/zaproxy/zap/extension/httpsInfo/MenuEntry.java
- src/org/zaproxy/zap/extension/httpsInfo/RightClickMenu.java
- src/org/zaproxy/zap/extension/httpsInfo/SSLServer.java
Autoformat code before starting to address zaproxy/zaproxy#758, in order
for things to be more easily maintainable. (Per dev guidelines
formatting changes are to be submitted separately from code changes.)
https://github.com/zaproxy/zaproxy/wiki/DevGuidelines
> HTTPSInfo Extension Code Autoformat

- src/org/zaproxy/zap/extension/pscanrules/CrossDomainScriptInclusionScanner.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
At HIGH threshold check if URLs for included scripts fall within the same
context as the message being analyzed. Also update help entry and
ZapAddOn.xml.
https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsPscanrules#threshold
Fixes zaproxy/zaproxy#395
> Issue 395 Allowed Cross Domain Hosts

- src/org/zaproxy/zap/extension/ascanrulesBeta/Csrftokenscan.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
- src/org/zaproxy/zap/extension/pscanrulesBeta/CSRFCountermeasures.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
Also tidied up the CSRF rules a little bit as well
> Support ignoring specified forms when checking from CSRF vulnerabilities

- src/org/zaproxy/zap/extension/ascanrulesBeta/IntegerOverflow.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/RemoteCodeExecutionCVE20121823.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionHypersonic.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionMySQL.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionOracle.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionPostgresql.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureCVE20121823.java
IntegerOverflow - Fix targets() static-access
RemoteCodeExecutionCVE20121823 - Fix targets() static-access
SourceCodeDisclosureCVE20121823 - Fix targets() static-access
SQLInjectionHypersonic - Fix "Techonologies" typo, and targets()
static-access
SQLInjectionMySQL - Fix "Techonologies" typo
SQLInjectionOracle - Fix "Techonologies" typo, and targets()
static-access
SQLInjectionPostgresql - Fix "Techonologies" typo
> Minor Corrections (Beta Quality)

- src/org/zaproxy/zap/extension/ascanrules/CodeInjectionPlugin.java
CodeInjectionPlugin - Fix "techonologies" typo
> Minor Correction (Release Quality)

- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
Remove unused resource message from Messages.properties file.
> fuzz: removed unused resource message

- src/org/zaproxy/zap/extension/ascanrules/TestSQLInjection.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
TestSQLInjection - Modified test case 2 to not continue with other
injection attempts if an alert has been raised.
ZapAddOn.xml - Incremented version and updated changes section.
Fixes zaproxy/zaproxy#1211
> Fix Issue 1211 SQLi Duplicate Alerts

- src/org/zaproxy/zap/extension/bugtracker/ZapAddOn.xml
- src/org/zaproxy/zap/extension/bugtracker/resources/help/contents/bugtracker.html
- src/org/zaproxy/zap/extension/bugtracker/resources/help/helpset.hs
- src/org/zaproxy/zap/extension/bugtracker/resources/help/index.xml
- src/org/zaproxy/zap/extension/bugtracker/resources/help/map.jhm
- src/org/zaproxy/zap/extension/bugtracker/resources/help/toc.xml
Please review @psiinon @thc202 @kingthorin  :)
> Added help for Bug Tracker add-on

- build/build.xml
- src/org/zaproxy/zap/extension/wappalyzer/Application.java
- src/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
- src/org/zaproxy/zap/extension/wappalyzer/PopupMenuEvidence.java
- src/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
- src/org/zaproxy/zap/extension/wappalyzer/ZapAddOn.xml
- src/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html
Address TODO item. Enable Wappalyzer Meta Tag checks.
WappalyzerPassiveScanner also capitalize logger constant.
build.xml add `deploy-wappalyzer-without-help-indexes` entry.
ZapAddOn.xml updates changes section.
> Wappalyzer Add Meta Tag Checks

- src/org/zaproxy/zap/extension/ascanrulesBeta/IntegerOverflow.java
- src/org/zaproxy/zap/extension/diff/DiffDialog.java
Remove unused imports in Diff add-on and Integer Overflow scanner.
> beta: remove unused imports

- test/org/zaproxy/zap/extension/pscanrules/PasswordAutocompleteScannerUnitTest.java
Hi there!
since this is my pull-request ever, please check the changes carefully.
Best regards,
Thomas
> added UnitTest for PasswordAutocompleteScanner

- src/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanner.java
- src/org/zaproxy/zap/extension/pscanrules/resources/application_errors.xml
- test/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScannerRegexMatcherUnitTest.java
- test/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScannerUnitTest.java
Hello,
Let's try to a PR for ApplicationErrorScanner test.
1. first commit on this repo
2. not easy to do parametrized tests with JUnit... so only one test for Regex evidence...
3. not signed/found any Contributor Licensing Agreement for OWASP. Can you help me to do that?
I hope it can help.
Adrien
> Unit tests for ApplicationErrorScanner

- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
Bump version and update changes in ZapAddOn.xml file per latest changes
done to ApplicationErrorScanner.
---
Forgot the changes to ZapAddOn.xml file when reviewing #527.
> pscanrules: update ZapAddOn.xml file

- src/org/zaproxy/zap/extension/jython/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jython/files/scripts/templates/httpsender/HttpSender default template.py
Add a Python HTTP Sender template script (same behaviour as JavaScript
template).
Update changes and files in ZapAddOn.xml file.
> jython: add httpsender template script

- src/org/zaproxy/zap/extension/exportreport/ExtensionExportReport.java
- src/org/zaproxy/zap/extension/exportreport/ZapAddOn.xml
- src/org/zaproxy/zap/extension/exportreport/resources/Messages.properties
Fixes zaproxy/zaproxy#3015
Updated the command line help messages.
> exportreport: updated the command line help messages

- test/org/zaproxy/zap/extension/ascanrulesBeta/ActiveScannerTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/IntegerOverflowUnitTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/RemoteCodeExecutionCVE20121823UnitTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionHypersonicUnitTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionMySQLUnitTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionOracleUnitTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/SQLInjectionPostgresqlUnitTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureCVE20121823UnitTest.java
Add unit tests for the scanners that target just some technologies.
> ascanrulesbeta: assert targeted technologies

- src/org/zaproxy/zap/extension/pscanrules/TestInfoPrivateAddressDisclosure.java
- test/org/zaproxy/zap/extension/pscanrules/TestInfoPrivateAddressDisclosureUnitTest.java
Change TestInfoPrivateAddressDisclosure to ignore (if not LOW alert
threshold) private IP addresses found in the response if they match the
requested host/address.
Add tests to assert the expected behaviour.
Fix zaproxy/zaproxy#3031 - Ignore requested private IP addresses on
Private IP Disclosure scan
> pscanrules: ignore private IPs requested

- src/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanner.java
- src/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScanner.java
- src/org/zaproxy/zap/extension/pscanrules/CookieUtils.java
- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- test/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScannerUnitTest.java
- test/org/zaproxy/zap/extension/pscanrules/CookieUtilsUnitTest.java
I'll update the beta and alpha rules once this has been approved and merged
> Add support for cookie ignore rule

- test/org/zaproxy/zap/extension/ascanrules/ActiveScannerTest.java
- test/org/zaproxy/zap/extension/ascanrules/BufferOverflowUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/CodeInjectionPluginUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/CommandInjectionPluginUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/FormatStringUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestSQLInjectionUnitTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestServerSideIncludeUnitTest.java
Add unit tests for the scanners that target just some technologies.
> ascanrules: assert targeted technologies

- src/org/zaproxy/zap/extension/ascanrules/TestSQLInjection.java
This check is an extension of the original **check(4)**.
It uses **multiplication** variant instead.
Also, repetition of codes of both checks(**mult** and **plus**) has been addressed by extracting a new method.
> Add both variants of check4 in TestSQLInjection

- src/org/zaproxy/zap/extension/ascanrules/TestSQLInjection.java
Change license header in TestSQLInjection from JavaDoc comment to a
plain comment.
> Change license header to plain comment

- src/org/zaproxy/zap/extension/sequence/SequencePopupMenuItem.java
- src/org/zaproxy/zap/extension/sequence/ZapAddOn.xml
Change SequencePopupMenuItem to include the script name in the error
message, that indicates the script does not implement the required
interface.
> sequence: correct error message

- build/build.xml
- src/org/zaproxy/zap/extension/webdriverlinux/WebdriverDownload.java
- src/org/zaproxy/zap/extension/webdrivermacos/WebdriverDownload.java
- src/org/zaproxy/zap/extension/webdriverwindows/WebdriverDownload.java
Also changed the build so that it works more constantly when invoked via automation.
> Tweak to fail if webdrivers fail to download

- src/org/zaproxy/zap/extension/plugnhack/PlugNHackAPI.java
- src/org/zaproxy/zap/extension/plugnhack/resources/manifest.json
- src/org/zaproxy/zap/extension/plugnhack/resources/service.json
- src/org/zaproxy/zap/extension/plugnhack/resources/welcome.html
Probably wont rerelease this until we have a signed XPI, but these changes should allow that to work with 2.6.0
> Fix pnh to always supply nonces

- .classpath
- src/org/zaproxy/zap/extension/ascanrulesBeta/ChallengeCallbackAPI.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ExtensionAscanRulesBeta.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/XXEPlugin.java
- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
I've tested this locally and it appears to work fine - it finds and reports an XXE via the callback mechanism.
I'm working on adding a unit test but its non trivial due to the number of classes needed to be mocked :/
So I think its worth reviewing now anyway, esp as the current implementation will no longer work.
> Changed XXE rule to use new callback extension.

- build/build.xml
Update version and include webdriver add-ons in full release
> Update build for 2.6.0

- build/build.xml
Change build.xml file to use the 2.6 release link for downloads of
add-ons.
> Update download link to 2.6 release (master)

- src/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java
- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/payloads/generator/NumberPayloadGenerator.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/NumberPayloadGeneratorAdapterUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
- src/org/zaproxy/zap/extension/fuzz/resources/help/contents/payloads.html
Moved the number generator to a separate branch.
Made changes according to suggestions from @kingthorin.
Signed-off-by: Steven van der Baan steven@pentest.7safe.com
> A new Number Fuzz generator.

- src/org/zaproxy/zap/extension/customreport/ExtensionCustomReport.java
- src/org/zaproxy/zap/extension/customreport/ReportLastScan.java
Building anything in the Alpha branch causes a bunch of warnings due to
deprecation etc. This PR addresses the deprecated items in the
customreport addon.
> CustomReport Fix Build Warnings

- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
In follow-up to https://github.com/zaproxy/zap-extensions/pull/515
Increment version, and update changes section.
> Ascan Manifest Updates

- test/org/zaproxy/zap/extension/pscanrulesBeta/InformationDisclosureDebugErrorsUnitTest.java
Extracted HttpMessage creation to a method. Fixed trailing whitespaces.
Throws RuntimeException when IOExceptions caught during file writes.
Re: https://github.com/zaproxy/zap-extensions/pull/536
> Tweaks for InformationDisclosureDebugErrors UnitTest

- src/org/zaproxy/zap/extension/pscanrulesBeta/CSRFCountermeasures.java
- test/org/zaproxy/zap/extension/pscanrulesBeta/CSRFCountermeasuresUnitTest.java
Added unit test for CSRFCountermeasures, Minor changes to CSRFCountermeasures to facilitate testing.
Added the unit test. 
Fixes zaproxy/zaproxy#2801
> #2801 Fixed unit test for CSRFCountermeasures

- src/org/zaproxy/zap/extension/pscanrulesBeta/InsecureJSFViewStatePassiveScanner.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- test/org/zaproxy/zap/extension/pscanrulesBeta/InsecureJSFViewStatePassiveScannerUnitTest.java
Test for issue [2807](https://github.com/zaproxy/zaproxy/issues/2807) + fix small bug checking value of view state instead of id
> Added unit test for InsecureJSFViewStatePassiveScanner 

- test/org/zaproxy/zap/extension/ScannerTestUtils.java
- test/org/zaproxy/zap/extension/pscanrulesBeta/InsecureAuthenticationScanUnitTest.java
Test for issue [2806](https://github.com/zaproxy/zaproxy/issues/2806)
> Added unit test for InsecureAuthenticationScanUnitTest

- .classpath
Not quite sure how this slipped through :/ Will be creating PRs to update beta and alpha too..
> Update to use the 2.6.0 jar

- src/org/zaproxy/zap/extension/portscan/resources/Messages.properties
- src/org/zaproxy/zap/extension/portscan/resources/help/contents/options.html
Minor tweaks to title caps and pluralness of resource keys.
See zaproxy/zaproxy#2000
> Port Scan Issue 2000

- build/build.xml
Add a new task to build.xml file to generate the wiki of the add-on.
> importurls: add task to generate the wiki

- src/org/zaproxy/zap/extension/importurls/resources/Messages.properties
> Various Issue 2000 Tweaks

- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/resources/Messages.properties
> Scripts Console Title Caps

- test/org/zaproxy/zap/extension/ascanrules/ActiveScannerTest.java
- test/org/zaproxy/zap/extension/ascanrules/TestPathTraversalUnitTest.java
Add tests to assert the number of messages sent by TestPathTraversal.
> Assert number of msgs sent by TestPathTraversal

- src/org/zaproxy/zap/extension/ascanrulesAlpha/ElmahScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
ElmahScanner - The new scanner.
Messages.properties - Add necessary i18n keys and values.
ascanalpha.html - Add new help entry.
ZapAddOn.xml - Add new change entry, and include the new scanner in the
ascanrules section.
Fixes zaproxy/zaproxy#3279
> Issue 3279 Add ELMAH Active Scanner

- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
> Tweak Elmah Scanner

- src/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanner.java
- src/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScanner.java
- test/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScannerUnitTest.java
Removed unused imports from passive scanners and test.
> Remove unused imports

- test/org/zaproxy/zap/extension/ascanrules/TestPathTraversalUnitTest.java
Change TestPathTraversalUnitTest to test the fixed false positive (test
failing before the changes).
> ascanrules: add test for (fixed) path traversal FP

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/ui/HttpFuzzResultsContentPanel.java
Backport the changes implemented in the newer generic component.
https://github.com/zaproxy/zaproxy/pull/3545#issuecomment-302499767
https://github.com/zaproxy/zaproxy/pull/3543
https://github.com/zaproxy/zaproxy/pull/3540
The generic component won't be available to extension until after the next core update.
Fixes zaproxy/zaproxy#3557
> Backport Table Export Changes

- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
Fix typo in issue number and add missing break line in ZapAddOn.xml
changes.
> ascanrulesAlpha: fixes in changes

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/ui/OptionsWebSocketPanel.java
- src/org/zaproxy/zap/extension/websocket/ui/SessionExcludeFromWebSocket.java
Correct help indexes of the buttons shown in dialogues Options and
Session Properties.
> websocket: correct help buttons' index

- src/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
- src/org/zaproxy/zap/extension/openapi/ImportFromUrlDialog.java
- src/org/zaproxy/zap/extension/openapi/OpenApiAPI.java
- src/org/zaproxy/zap/extension/openapi/OpenApiSpider.java
- src/org/zaproxy/zap/extension/openapi/ZapAddOn.xml
- src/org/zaproxy/zap/extension/openapi/converter/swagger/RequestModelConverter.java
- src/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverter.java
- src/org/zaproxy/zap/extension/openapi/generators/ArrayGenerator.java
- src/org/zaproxy/zap/extension/openapi/generators/BodyGenerator.java
- src/org/zaproxy/zap/extension/openapi/generators/DataGenerator.java
- src/org/zaproxy/zap/extension/openapi/generators/FormGenerator.java
- src/org/zaproxy/zap/extension/openapi/generators/Generators.java
- src/org/zaproxy/zap/extension/openapi/generators/HeadersGenerator.java
- src/org/zaproxy/zap/extension/openapi/generators/PathGenerator.java
- src/org/zaproxy/zap/extension/openapi/network/Requestor.java
- src/org/zaproxy/zap/extension/openapi/resources/Messages.properties
- src/org/zaproxy/zap/extension/openapi/resources/help/contents/openapi.html
- test/org/zaproxy/zap/extension/openapi/OpenApiUnitTest.java
- test/resources/org/zaproxy/zap/extension/openapi/PetStore_defn_loop.yaml
The change to only support 2.6.0 is deliberate - more than 1/2 of our users have upgraded now so I dont think we need to keep supporting old versions indefinitely. Esp for relatively minor enhancements.
> OpenAPI: added host override and detection for potential loops

- src/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
- src/org/zaproxy/zap/extension/openapi/OpenApiSpider.java
- src/org/zaproxy/zap/extension/openapi/ZapAddOn.xml
- src/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverter.java
- src/org/zaproxy/zap/extension/openapi/generators/ArrayGenerator.java
- src/org/zaproxy/zap/extension/openapi/generators/BodyGenerator.java
- src/org/zaproxy/zap/extension/openapi/generators/DataGenerator.java
- src/org/zaproxy/zap/extension/openapi/generators/FormGenerator.java
- src/org/zaproxy/zap/extension/openapi/generators/Generators.java
- src/org/zaproxy/zap/extension/openapi/generators/HeadersGenerator.java
- src/org/zaproxy/zap/extension/openapi/generators/PathGenerator.java
- src/org/zaproxy/zap/extension/openapi/generators/ValueGenerator.java
- src/org/zaproxy/zap/extension/openapi/resources/help/contents/openapi.html
- test/org/zaproxy/zap/extension/openapi/OpenApiUnitTest.java
> Support user specified values when importing openapi def

- src/org/zaproxy/zap/extension/pscanrulesAlpha/UsernameIdorScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
- test/org/zaproxy/zap/extension/pscanrulesAlpha/UsernameIdorScannerUnitTest.java
UsernameIdorScanner - a new passive scanner that looks for hashed
usernames in HTTP responses (based on the users configured in the
context).
UsrnameIdorScannerUnitTest - The unit tests for the new scanner.
> Add Username Hash IDOR Passive Scanner

- src/org/zaproxy/zap/extension/jruby/ZapAddOn.xml
Add the new template to the list of add-on files in ZapAddOn.xml file,
also, update the changes with the latest more relevant change.
> jruby: add template to add-on manifest

- build/build.xml
This will give the addon more exposure, esp as we will then try it vs 100+ Mozilla sites every day :)
> Include cspscanner in weekly release

- .travis.yml
- src/org/zaproxy/zap/extension/cspscanner/ContentSecurityPolicyScanner.java
- src/org/zaproxy/zap/extension/cspscanner/ZapAddOn.xml
- test/org/zaproxy/zap/extension/cspscanner/ContentSecurityPolicyScannerUnitTest.java
The loops were invalid meaning that no error messages were added. Also added evidence and a simple unit test.
> Fixed missing messages and added evidence

- build/build.xml
- src/org/zaproxy/zap/extension/webdriverlinux/WebdriverDownload.java
- src/org/zaproxy/zap/extension/webdrivermacos/WebdriverDownload.java
- src/org/zaproxy/zap/extension/webdriverwindows/WebdriverDownload.java
Ensure that the files are always downloaded to the right locations no
matter where the ant target is invoked from.
> Fix download locations

- build/build.xml
Looks like the 2 stars dont work :/
> Correct jxbrowser regex

- src/org/zaproxy/zap/extension/zest/ZapAddOn.xml
> Support latest selenium addon.

- src/org/zaproxy/zap/extension/jxbrowserlinux32/selenium/ExtSelJxBrowserLinux32.java
- src/org/zaproxy/zap/extension/jxbrowserlinux64/selenium/ExtSelJxBrowserLinux64.java
- src/org/zaproxy/zap/extension/jxbrowsermacos/selenium/ExtSelJxBrowserMacOs.java
- src/org/zaproxy/zap/extension/jxbrowserwindows/selenium/ExtSelJxBrowserWindows.java
Change browser provider extensions to depend on ExtensionSelenium (it's
a dependency).
> jxbrowser: change extensions to depend on selenium

- src/org/zaproxy/zap/extension/todo/ExtensionTodoList.java
- src/org/zaproxy/zap/extension/todo/TodoList.java
Remove unused imports from ExtensionTodoList and TodoList.
> todo: remove unused imports

- .classpath
- src/org/zaproxy/zap/extension/jxbrowser/BrowserFrame.java
- src/org/zaproxy/zap/extension/jxbrowser/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowserlinux32/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowserlinux32/selenium/JxBrowserProvider.java
- src/org/zaproxy/zap/extension/jxbrowserlinux64/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowserlinux64/selenium/JxBrowserProvider.java
- src/org/zaproxy/zap/extension/jxbrowsermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowsermacos/selenium/ExtSelJxBrowserMacOs.java
- src/org/zaproxy/zap/extension/jxbrowsermacos/selenium/JxBrowserProvider.java
- src/org/zaproxy/zap/extension/jxbrowsermacos/selenium/MacOsJxBrowserProvider.java
- src/org/zaproxy/zap/extension/jxbrowserwindows/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowserwindows/selenium/JxBrowserProvider.java
>  Changes to support launching proxied browsers

- src/org/zaproxy/zap/extension/quickstart/ZapAddOn.xml
- src/org/zaproxy/zap/extension/quickstart/launch/ExtensionQuickStartLaunch.java
- src/org/zaproxy/zap/extension/quickstart/launch/QuickStartLaunchAPI.java
@thc202 @kingthorin ok for a v quick review? The version I've just released is broken :/
> Fix quick start default launch url

- src/org/zaproxy/zap/extension/scripts/ConsolePanel.java
Address pending task that required newer version of ZAP (already
targeting 2.6.0).
> scripts: address task

- README.md
Add indication of where they can download ZAP plugins from.
> Minor Update README.md

- src/org/zaproxy/zap/extension/scripts/resources/help/contents/scripts.html
Add links to Nashorn documentation and Rhino migration guide.
> scripts: add Nashorn links to help page

- src/org/zaproxy/zap/extension/jython/ExtensionJython.java
Change ExtensionJython to load the Jython engine in a separate thread,
the new Jython engine takes longer to load which would make ZAP's start
up slower. In daemon mode the extension will hold (postInit) the start
up process until the engine is loaded/added, the engine might be
required for normal operation (e.g. HTTP Sender scripts).
---
From #1021.
Related core changes that improve the loading time: zaproxy/zaproxy#3880
> jython: load engine in a separate thread

- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
* Message.properties > Updated relevant resource key value.
* ZapAddOn.xml > Added changes entry, & fixed the br tag on the previous one for consistency.
Fixes zaproxy/zaproxy#3937
> Issue 3937 Fix ServletParameterPollution Scanner Reference

- src/org/zaproxy/zap/extension/sqliplugin/ResponseMatcher.java
- src/org/zaproxy/zap/extension/sqliplugin/SQLInjectionPlugin.java
- src/org/zaproxy/zap/extension/sqliplugin/SQLiBoundary.java
- src/org/zaproxy/zap/extension/sqliplugin/SQLiPayloadManager.java
- src/org/zaproxy/zap/extension/sqliplugin/SQLiTest.java
- src/org/zaproxy/zap/extension/sqliplugin/SQLiTestDetails.java
- src/org/zaproxy/zap/extension/sqliplugin/SQLiUnionEngine.java
- src/org/zaproxy/zap/extension/sqliplugin/ZapAddOn.xml
Address raw type warnings (by using diamond operator).
> sqliplugin: address raw type warnings

- src/org/zaproxy/zap/extension/communityScripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/active/User defined attacks.js
Planning on releasing this add-on after this PR is merged
> Added User defined attacks script

- src/org/zaproxy/zap/extension/callgraph/CallGraphFrame.java
- src/org/zaproxy/zap/extension/callgraph/PopupMenuCallGraph.java
- src/org/zaproxy/zap/extension/callgraph/ZapAddOn.xml
- src/org/zaproxy/zap/extension/callgraph/resources/Messages.properties
Move the labels/title into Messages.properties files and update classes
to use them.
> callgraph: finish internationalisation

- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
pscanrules.html > Remove dangling sentence.
ZapAddOn.xml > Add changes entry.
Fixes zaproxy/zaproxy#3986
> Fix Help Content for XCTO Passive Scanner

- src/org/zaproxy/zap/extension/scripts/SyntaxHighlightTextArea.java
- src/org/zaproxy/zap/extension/scripts/ViewMenu.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Add a context menu item to allow enable/disable code folding in script
text area.
> scripts: allow to enable code folding

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
Add description to script types.
> fuzz: add description to script types

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/Messages.properties
Add description to Fuzzer WebSocket Processor script type.
> websocket: add description to fuzzer script type

- src/org/zaproxy/zap/extension/pscanrulesAlpha/XAspNetVersionScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
- test/org/zaproxy/zap/extension/pscanrulesAlpha/XAspNetVersionScannerUnitTest.java
Fixed the comments on #1115
Also reserved the scanner id on zaproxy/zaproxy#3996
Also, there was no OWASP guide - should I create one?
> X aspnet version scanner

- test/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2UnitTest.java
Removed unused import for previous `@Ignore` annotation(s).
> TestCrossSiteScriptV2UnitTest Remove Unused Import

- .classpath
Update the version of Selenium add-on to existing version.
> alpha: update Eclipse's classpath

- .classpath
- src/org/zaproxy/zap/extension/accessControl/ExtensionAccessControl.java
- src/org/zaproxy/zap/extension/accessControl/ZapAddOn.xml
- src/org/zaproxy/zap/extension/communityScripts/ExtensionCommunityScripts.java
- src/org/zaproxy/zap/extension/communityScripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/domxss/ExtensionDomXSS.java
- src/org/zaproxy/zap/extension/domxss/ZapAddOn.xml
- src/org/zaproxy/zap/extension/httpsinfo/ExtensionHttpsInfo.java
- src/org/zaproxy/zap/extension/httpsinfo/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowserlinux64/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowserlinux64/selenium/ExtSelJxBrowserLinux64.java
- src/org/zaproxy/zap/extension/jxbrowsermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowsermacos/selenium/ExtSelJxBrowserMacOs.java
- src/org/zaproxy/zap/extension/jxbrowserwindows/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowserwindows/selenium/ExtSelJxBrowserWindows.java
- src/org/zaproxy/zap/extension/revisit/ExtensionRevisit.java
- src/org/zaproxy/zap/extension/revisit/ZapAddOn.xml
- src/org/zaproxy/zap/extension/sequence/ExtensionSequence.java
- src/org/zaproxy/zap/extension/sequence/ZapAddOn.xml
- src/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
- src/org/zaproxy/zap/extension/wappalyzer/ZapAddOn.xml
Note that this is a pre release version for testing - I'll update the PR
with the final jar once all changes have been merged.
> Update zap jar

- src/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
- src/org/zaproxy/zap/extension/wappalyzer/ZapAddOn.xml
> wappalyzer Address Deprecations

- src/org/zaproxy/zap/extension/jxbrowser/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowser/ZapBrowserPanel.java
> JXBrowser Address Deprecations

- src/org/zaproxy/zap/extension/requester/ManualHttpRequestEditorPanel.java
- src/org/zaproxy/zap/extension/requester/ZapAddOn.xml
> requester Address Deprecations

- src/org/zaproxy/zap/extension/pscanrulesBeta/CharsetMismatchScanner.java
- src/org/zaproxy/zap/extension/pscanrulesBeta/ZapAddOn.xml
> pscanrulesBeta Address Deprecation

- src/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ContentSecurityPolicyMissingScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleFilePassiveScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ServerHeaderInfoLeakScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/StrictTransportSecurityScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
> pscanrulesAlpha Address Deprecations

- src/org/zaproxy/zap/extension/scripts/ScriptsListPanel.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
Change ScriptsListPanel to use a WritableFileChooser when saving the
script, to get confirmation when overwriting a existing file.
> scripts: confirm overwrite of script file

- src/org/zaproxy/zap/extension/scripts/SyntaxHighlightTextArea.java
- src/org/zaproxy/zap/extension/scripts/ViewMenu.java
Change SyntaxHighlightTextArea to use the new method in FontUtils.
Change ViewMenu to use the core resource message.
> scripts: update to use 2.7.0 features

- src/org/zaproxy/zap/extension/quickstart/resources/Messages.properties
We'll still use the zap-admin file, but I'll write a program to generate it from any translations we get on Crowdin
> Add browser HTML message to aid l18n

- src/org/zaproxy/zap/extension/coreLang/resources/help/contents/coreLang.html
Not updated the version as I'm expecting more changes, both to the credits and to the translations before long
> Updated the credits

- src/org/zaproxy/zap/extension/zest/ZestActiveRunner.java
- src/org/zaproxy/zap/extension/zest/ZestPassiveRunner.java
- src/org/zaproxy/zap/extension/zest/ZestZapRunner.java
- src/org/zaproxy/zap/extension/zest/menu/ZestGenerateScriptFromAlertMenu.java
Address deprecations in usage of core classes.
> zest: address core deprecations

- src/org/zaproxy/zap/extension/pscanrules/TestInfoSessionIdURL.java
If the "sessionOptions " is null , ignore it.
> Null pointer checking

- src/org/zaproxy/zap/extension/scripts/CommandPanel.java
- src/org/zaproxy/zap/extension/scripts/ScriptTreeTransferHandler.java
- src/org/zaproxy/zap/extension/scripts/ScriptsListPanel.java
- src/org/zaproxy/zap/extension/scripts/autocomplete/JScrollPopupMenu.java
- src/org/zaproxy/zap/extension/scripts/dialogs/CopyScriptDialog.java
- src/org/zaproxy/zap/extension/scripts/dialogs/EditScriptDialog.java
- src/org/zaproxy/zap/extension/scripts/dialogs/LoadScriptDialog.java
- src/org/zaproxy/zap/extension/scripts/dialogs/NewScriptDialog.java
Add missing override annotations and remove (now) unnecessary cast.
> scripts: add annotations and remove cast

- src/org/zaproxy/zap/extension/jython/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jython/files/scripts/templates/extender/Add tools menu.py
Move docstring in Add tools menu.py template to be in the function its
documenting.
Bump version and update changes.
> jython: move docstring closer to function

- src/org/zaproxy/zap/extension/pscanrulesAlpha/PiiScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
- test/org/zaproxy/zap/extension/pscanrulesAlpha/PiiScannerCreditCardUnitTest.java
Currently only credit card numbers are detected
> Implemented PII Scanner

- src/org/zaproxy/zap/extension/help_tr_TR/ZapAddOn.xml
Will add the jar file in another PR when I regenerate them all
> Added add-on for Turkish help

- src/org/zaproxy/zap/extension/invoke/InvokeAppWorker.java
- src/org/zaproxy/zap/extension/invoke/ZapAddOn.xml
- src/org/zaproxy/zap/extension/invoke/resources/help/contents/options.html
See issue in main zaproxy repo
https://github.com/zaproxy/zaproxy/issues/4396
> Added additional parameter replacements of %msgid% and %header-*% 

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- src/org/zaproxy/zap/extension/websocket/WebSocketAPI.java
- src/org/zaproxy/zap/extension/websocket/WebSocketProxy.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/Messages.properties
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/api.html
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/introduction.html
- src/org/zaproxy/zap/extension/websocket/resources/help/index.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/map.jhm
- src/org/zaproxy/zap/extension/websocket/resources/help/toc.xml
- src/org/zaproxy/zap/extension/websocket/utility/WebSocketUtils.java
- test/org/zaproxy/zap/extension/websocket/utility/WebSocketUtilsUnitTest.java
I've also added basic API and About help pages.
> Added API support

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
Tweak about help page (add bullets to release changes) to improve the
rendering in the wiki page.
Bump version and update changes.
> websocket: tweak about help page

- src/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2.java
Autoformatted with Eclipse defaults. (Attempted use of Google's Java formatting plugin for eclipse but was unsuccessful.)
> Format TestCrossSiteScriptV2

- src/org/zaproxy/zap/extension/pscanrulesAlpha/LinkTargetScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
- test/org/zaproxy/zap/extension/pscanrulesAlpha/LinkTargetScannerUnitTest.java
The vulnerability is on all 'target's that open a new window, not just _blank.
Also added support for a trusted domain config value - this isnt actually registered yet as plan to do tha via one of the release ones that will use the same key.
> Renamed and corrected Link Target Scanner

- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
pscanalpha.html > Updated headings to include scanner names (based on getName()), added missing entries, tweaked alpha sorting, and removed un-used entry.
Messages.properties > Removed un-used resource keys/messages.
ZapAddOn.xml > Incremented version and updated changes section.
> Alpha Help Tweaks

- src/org/zaproxy/zap/extension/httpsinfo/ExtensionHttpsInfo.java
- src/org/zaproxy/zap/extension/httpsinfo/HttpsInfoOutputPanel.java
- src/org/zaproxy/zap/extension/httpsinfo/MenuEntry.java
- src/org/zaproxy/zap/extension/httpsinfo/ZapAddOn.xml
- src/org/zaproxy/zap/extension/httpsinfo/resources/help/contents/httpsinfo.html
Changed from Dialog(s) to a Status panel with tabs. Part of zaproxy/zaproxy#2532
> HttpsInfo New UI

- src/org/zaproxy/zap/extension/scripts/ConsolePanel.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/resources/Messages.properties
- src/org/zaproxy/zap/extension/scripts/resources/help/contents/console.html
Depends on https://github.com/zaproxy/zaproxy/pull/4449
> Warn users if the script has been edited by another program

- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
ascanalpha.html > Sorted help content alphabetically, adjusted names to match scan rules, and added missing entries.
> ascan alpha help tweaks

- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
> ascanrulesAlpha: prepare next dev iteration

- src/org/zaproxy/zap/extension/replacer/ReplaceRuleAddDialog.java
Address pending tasks by using core constants (already targeting newer
ZAP version).
> replacer: address tasks

- src/org/zaproxy/zap/extension/soap/ExtensionImportWSDL.java
- src/org/zaproxy/zap/extension/soap/ZapAddOn.xml
- src/org/zaproxy/zap/extension/soap/resources/Messages.properties
Internationalise the file filter description set in ExtensionImportWSDL.
> soap: i18n file filter description

- src/org/zaproxy/zap/extension/ascanrules/TestPersistentXSSAttack.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/quickstart/AttackThread.java
- src/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
- src/org/zaproxy/zap/extension/websocket/fuzz/WebSocketFuzzerHandler.java
Replace usage of MessageFormat and I18N.getString(String) with a call
to I18N.getString(String, Object...), the latter already does the
formatting.
Bump version and update changes in ZapAddOn.xml file (only required in
one of the add-ons).
> Use I18N.getString(String, Object...)

- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/HttpFuzzer.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/HttpFuzzerHandler.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/HttpFuzzerTask.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/AntiCsrfHttpFuzzerMessageProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/UserHttpFuzzerMessageProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/AbstractPersistentPayloadGeneratorUIPanel.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/RegexPayloadGeneratorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/Base64DecodeProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/Base64EncodeProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/ExpandStringProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/MD5HashProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/SHA1HashProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/SHA256HashProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/SHA512HashProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/TrimStringProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/URLDecodeProcessorUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/URLEncodeProcessorUIHandler.java
- src/org/zaproxy/zap/extension/plugnhack/brk/ClientBreakpointMessage.java
- src/org/zaproxy/zap/extension/plugnhack/httppanel/component/ClientComponent.java
- src/org/zaproxy/zap/extension/zest/ZestHttpSenderRunner.java
- src/org/zaproxy/zap/extension/zest/ZestProxyRunner.java
- src/org/zaproxy/zap/extension/zest/ZestZapUtils.java
- src/org/zaproxy/zap/extension/zest/menu/ZestGenerateScriptFromAlertMenu.java
Replace usage of MessageFormat and I18N.getString(String) with a call
to I18N.getString(String, Object...), the latter already does the
formatting.
> Use I18N.getString(String, Object...) (beta)

- src/org/zaproxy/zap/extension/birtreports/ReportLastScan.java
- src/org/zaproxy/zap/extension/birtreports/ZapAddOn.xml
- src/org/zaproxy/zap/extension/cspscanner/ContentSecurityPolicyScanner.java
- src/org/zaproxy/zap/extension/cspscanner/ZapAddOn.xml
- src/org/zaproxy/zap/extension/customreport/ReportLastScan.java
- src/org/zaproxy/zap/extension/customreport/ZapAddOn.xml
- src/org/zaproxy/zap/extension/httpsinfo/HttpsInfoOutputPanel.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/BigRedirectsScanner.java
- src/org/zaproxy/zap/extension/revisit/ExtensionRevisit.java
- src/org/zaproxy/zap/extension/revisit/RevisitDialog.java
- src/org/zaproxy/zap/extension/revisit/ZapAddOn.xml
- src/org/zaproxy/zap/extension/simpleExample/ExtensionSimpleExample.java
- src/org/zaproxy/zap/extension/simpleExample/RightClickMsgMenu.java
- src/org/zaproxy/zap/extension/simpleExample/ZapAddOn.xml
Replace usage of MessageFormat and I18N.getString(String) with a call
to I18N.getString(String, Object...), the latter already does the
formatting.
Bump version and update changes in ZapAddOn.xml files, where needed.
> Use I18N.getString(String, Object...) (alpha)

- src/org/zaproxy/zap/extension/codedx/CodeDxExtension.java
- src/org/zaproxy/zap/extension/codedx/CodeDxProperties.java
- src/org/zaproxy/zap/extension/codedx/ExtensionAlertHttp.java
- src/org/zaproxy/zap/extension/codedx/UploadPropertiesDialog.java
- src/org/zaproxy/zap/extension/codedx/ZapAddOn.xml
- src/org/zaproxy/zap/extension/codedx/resources/Messages.properties
The changes made to the Code Dx plugin include:
1. Set default timeout value of report upload process to 120 seconds
2. Added a null check when looking at Alert HttpMessages
3. Made the timeout value of report upload process configurable
> Update to Code Dx Plugin

- src/org/zaproxy/zap/extension/codedx/ZapAddOn.xml
> codedx: prepare next dev iteration

- src/org/zaproxy/zap/extension/groovy/ZapAddOn.xml
- src/org/zaproxy/zap/extension/groovy/resources/help/contents/about.html
The add-on meets all requirements to be promoted.
Update status and changes in ZapAddOn.xml file.
Update about help page with the promotion.
> groovy: promote to beta status

- src/org/zaproxy/zap/extension/scripts/CommandPanel.java
- src/org/zaproxy/zap/extension/scripts/ConsolePanel.java
- src/org/zaproxy/zap/extension/scripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/scripts/resources/Messages.properties
See [#4589](https://github.com/zaproxy/zaproxy/issues/4589)
> Script console: highlight is disabled if > 500KB  or totally disable if > 1000KB

- build/build.xml
- src/org/zaproxy/zap/extension/cspscanner/ZapAddOn.xml
- src/org/zaproxy/zap/extension/cspscanner/resources/help/contents/about.html
Add new version entry in about help page.
Add task to generate the wiki.
> cspscanner: prepare next dev iteration

- .classpath
- test/org/zaproxy/zap/extension/ascanrulesBeta/ActiveScannerTest.java
- test/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosureUnitTest.java
BackupFileDisclosure > Add unit tests for message counts at different strengths.
ActiveScannerTest > Aligned to the latest changes in the master branch in order to handle scanner configuration, etc.
See zaproxy/zaproxy#2169
> Issue 2169 - BackupFileDisclosure Unit Tests

- src/org/zaproxy/zap/extension/requester/ZapAddOn.xml
- src/org/zaproxy/zap/extension/tlsdebug/ZapAddOn.xml
Add status to the add-on manifests of requester and tlsdebug.
> Add missing add-on status

- src/org/zaproxy/zap/extension/communityScripts/ZapAddOn.xml
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/passive/HUNT - Debug & Logic Parameters.py
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/passive/HUNT - File Inclusion.py
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/passive/HUNT - IDOR.py
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/passive/HUNT - RCE.py
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/passive/HUNT - SQLi.py
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/passive/HUNT - SSRF.py
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/passive/HUNT - SSTI.py
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/proxy/Return fake response.js
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/proxy/dropCookiesSelectively.js
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/standalone/Loop through alerts.js
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/standalone/enableDebugLogging.js
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/standalone/loadListInGlobalVariable.js
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/variant/param_name_variant.js
- src/org/zaproxy/zap/extension/communityScripts/files/community-scripts/websocketfuzzerprocessor/README.md
Update from:
zaproxy/community-scripts@64ea8107ac7b1cd342c3a2e4febc4328a59ae68b
Bump version in ZapAddOn.xml file.
> communityScripts: update from upstream

- src/org/zaproxy/zap/extension/communityScripts/ZapAddOn.xml
> communityScripts: prepare next dev iteration

- src/org/zaproxy/zap/extension/jython/ZapAddOn.xml
> jython: prepare next dev iteration

- src/org/zaproxy/zap/extension/webdriverlinux/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdrivermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
Update version and remove old changes in ZapAddOn.xml files.
> webdrivers: prepare next dev iteration

- src/org/zaproxy/zap/extension/plugnhack/ZapAddOn.xml
- src/org/zaproxy/zap/extension/plugnhack/resources/Messages.properties
Adjust strings in Messages.properties.
Update version and changes in manifest. (https://github.com/zaproxy/zap-extensions/releases)
There seem to be more for PnH, but I didn't want to get too carried away when I wasn't sure of all the places in the UI that they appeared (so that I can ensure I'm making the right adjustment(s)).
> Issue 2000 - Plug'n'hack Add-on Title Caps

- src/org/zaproxy/zap/extension/sequence/ZapAddOn.xml
- src/org/zaproxy/zap/extension/sequence/resources/Messages.properties
Adjust strings in Messages.properties.
Update version and changes in manifest. (https://github.com/zaproxy/zap-extensions/releases)
> Issue 2000 - Sequence Add-on Title Caps

- src/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
Add a paragraph to the help docs outlining the known FP condition for the Private IP Disclosure passive scanner and potential work arounds.
Ref: zaproxy/zaproxy#4598
> pscan Private IP Disclosure - FP Help Tweak

- src/org/zaproxy/zap/extension/openapi/ZapAddOn.xml
> openapi: prepare next dev iteration

- src/org/zaproxy/zap/extension/tokengen/ZapAddOn.xml
Tweak the name of the add-on to follow title capitalisation.
> tokengen: prepare next dev iteration

- src/org/zaproxy/zap/extension/websocket/WebSocketAPI.java
Related to https://github.com/zaproxy/zaproxy/pull/4677
> Ensure strings that are JSON are not auto converted

- src/org/zaproxy/zap/extension/ascanrules/TestPersistentXSSAttack.java
Normalize format (to eclipse defaults) prior to tackling a reported False Negative
> Autoformat TestPersistentXSSAttack

- src/org/zaproxy/zap/extension/plugnhack/resources/pnh_probe.js
On-going work on plug-n-hack.
This PR is meant to receive any "minor" refactoring aimed to clarify the JS and explicit its intent.
> [WIP] Refactoring to clarify plug-n-hack

- src/org/zaproxy/zap/extension/highlighter/ZapAddOn.xml
> highlighter: prepare next dev iteration

- src/org/zaproxy/zap/extension/savexmlmessage/PopupMenuSaveXMLMessage.java
- src/org/zaproxy/zap/extension/savexmlmessage/ZapAddOn.xml
Update version (minor) and remove old changes in ZapAddOn.xml file.
Remove some unused imports.
> savexmlmessage: prepare next dev iteration

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
- src/org/zaproxy/zap/extension/websocket/ui/WebSocketMessagesViewModel.java
Set the release date and add changes to about help page.
Remove unused method/imports in WebSocketMessagesViewModel.
> websocket: prepare release

- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
Add new version entry in about help page.
> websocket: prepare next dev iteration

- src/org/zaproxy/zap/extension/ascanrules/TestPersistentXSSAttack.java
- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
Address specific false negative, plus merge all interim updates from Reflected XSS scanner.
TestPersistentXSSAttack > Updated with new/missing functionality.
ascanrules.html > Updated to align with current functionality.
Messages.properties > Added necessary keys/values to support updated functionality.
> Issue 4692 Plus Updates

- src/org/zaproxy/zap/extension/replacer/ZapAddOn.xml
> replacer: prepare next dev iteration

- src/org/zaproxy/zap/extension/communityScripts/ZapAddOn.xml
Add new scripts to ZapAddOn.xml file.
Missed in #1674.
> communityScripts: add new scripts to manifest

- src/org/zaproxy/zap/extension/jxbrowser/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowserlinux64/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowsermacos/ZapAddOn.xml
- src/org/zaproxy/zap/extension/jxbrowserwindows/ZapAddOn.xml
Update versions and remove changes in ZapAddOn.xml files.
> jxbrowsers: prepare next dev iteration

- src/org/zaproxy/zap/extension/websocket/WebSocketMessageDTO.java
- src/org/zaproxy/zap/extension/websocket/WebSocketProxy.java
- src/org/zaproxy/zap/extension/websocket/WebSocketProxyV13.java
When WebSocketProxy acts as client, send automatically response to ping messages. The ping websocket message are declared by opcode.
> Websocket heartbeat messages are handled by WebSocket Proxy

- src/org/zaproxy/zap/extension/customreport/ZapAddOn.xml
> customreport: prepare next dev iteration

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- src/org/zaproxy/zap/extension/websocket/utility/WebSocketUtils.java
Extract methods (parseWebSocketExtensions ,parseWebSocketSubProtocol, parseWebSocketVersion) from ExtensionWebSocket to WebSocketUtils in order to be able to establish WebSocket Connection outside of WebSocketExtension
> Extract methods from ExtensionWebSocket to WebSocketUtils

- src/org/zaproxy/zap/extension/importurls/ZapAddOn.xml
- src/org/zaproxy/zap/extension/importurls/resources/Messages.properties
Add description to API endpoint.
Update changes in ZapAddOn.xml file
> importurls: add description to API endpoint

- src/org/zaproxy/zap/extension/websocket/client/HandshakeConfig.java
- src/org/zaproxy/zap/extension/websocket/client/HttpHandshakeBuilder.java
- src/org/zaproxy/zap/extension/websocket/client/RequestOutOfScopeException.java
- src/org/zaproxy/zap/extension/websocket/client/ServerConnectionEstablisher.java
Websocket sends a HttpMessage in order to establish websocket connection. Also informs the appropriate ManualWebSocketConnectionOpenedListener. 
Open this PR in order to break up [PR#1618](https://github.com/zaproxy/zap-extensions/pull/1618)
> Websocket Handshake Builder and Sender

- src/org/zaproxy/zap/extension/simpleExample/ExtensionSimpleExample.java
- src/org/zaproxy/zap/extension/simpleExample/RightClickMsgMenu.java
- src/org/zaproxy/zap/extension/simpleExample/SimpleExampleAPI.java
- src/org/zaproxy/zap/extension/simpleExample/ZapAddOn.xml
- src/org/zaproxy/zap/extension/simpleExample/files/example/ExampleFile.txt
- src/org/zaproxy/zap/extension/simpleExample/resources/Messages.properties
* cleaning: indentation, trailing spaces, random lines
* add a small API example
> Improve `simpleExample`

- src/org/zaproxy/zap/extension/soap/ExtensionImportWSDL.java
- src/org/zaproxy/zap/extension/soap/ImportFromUrlDialog.java
- src/org/zaproxy/zap/extension/soap/ImportWSDL.java
- src/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanner.java
- src/org/zaproxy/zap/extension/soap/SOAPMsgConfig.java
- src/org/zaproxy/zap/extension/soap/SOAPXMLInjectionActiveScanner.java
- src/org/zaproxy/zap/extension/soap/SoapAPI.java
- src/org/zaproxy/zap/extension/soap/WSDLCustomParser.java
- src/org/zaproxy/zap/extension/soap/WSDLFilePassiveScanner.java
- src/org/zaproxy/zap/extension/soap/WSDLSpider.java
I preparation for some other work this PR is an application of the Eclipse default auto-format.
> SOAP Extension - Code Formatting

- test/org/zaproxy/zap/extension/websocket/client/ServerConnectionEstablisherUnitTest.java
- test/org/zaproxy/zap/extension/websocket/client/WebSocketProxyUnitTest.java
- test/org/zaproxy/zap/testutils/WebSocketTestUtils.java
- test/org/zaproxy/zap/testutils/websocket/server/NanoWebSocketConnection.java
- test/org/zaproxy/zap/testutils/websocket/server/NanoWebSocketTestServer.java
Tests if ServerConnectionEstablisher establishes WebSocket Connection correctly. Also,
test added for WebSocketProxy automate ping response.
Tests for PRs #1689 & #1686
> Tests for ServerConnectionEstablisher and WebSocketProxy

- src/org/zaproxy/zap/extension/ascanrulesBeta/ZapAddOn.xml
> ascanrulesBeta: prepare next dev iteration

- src/org/zaproxy/zap/extension/quickstart/ZapAddOn.xml
> quickstart: prepare next dev iteration

- src/org/zaproxy/zap/extension/spiderAjax/ZapAddOn.xml
> spiderAjax: prepare next dev iteration

- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
Make the title for the "Reverse Tabnabbing" alert titlecaps.
> pscan Alpha - Title Caps (Issue 2000)

- src/org/zaproxy/zap/extension/pscanrules/ZapAddOn.xml
> pscanrules: prepare next dev iteration

- src/org/zaproxy/zap/extension/frontendscanner/ExtensionFrontEndScanner.java
- src/org/zaproxy/zap/extension/frontendscanner/resources/Messages.properties
* Remove "terrible UX toggle"
* Replace it with a ZapToggleButton in the menu, with a nice image
> [FrontEndScanner] Replace UX for toggling the addon

- src/org/zaproxy/zap/extension/requester/ZapAddOn.xml
- src/org/zaproxy/zap/extension/requester/resources/Messages.properties
Change labels to have the word "Tab" with a leading capital. Remove
unnecessary blanks lines from messages.properties. Add change to
ZapAddOn.xml.
> Requester - Title Caps & Minor Clean Code Tweak

- src/org/zaproxy/zap/extension/ascanrulesAlpha/EnvFileScanner.java
- src/org/zaproxy/zap/extension/ascanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
- src/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
EnvFileScanner.java - Add a new Active Scanner to check for .env files.
ascanalpha.html - Added relevant help entry.
Messages.properties - Added i18n strings.
ZapAddOn.xml - Updated changes section.
See: https://mobile.twitter.com/svblxyz/status/1045013939904532482
> Add .env File Scanner

- build/build.xml
- src/org/zaproxy/zap/extension/saml/SAMLConfigData.java
- src/org/zaproxy/zap/extension/saml/SAMLConfiguration.java
- src/org/zaproxy/zap/extension/saml/SAMLMessage.java
- src/org/zaproxy/zap/extension/saml/SAMLUtils.java
- src/org/zaproxy/zap/extension/saml/ZapAddOn.xml
- src/org/zaproxy/zap/extension/saml/resources/Messages.properties
- src/org/zaproxy/zap/extension/saml/resources/zap_saml_conf.xml
- src/org/zaproxy/zap/extension/saml/ui/SamlExtentionSettingsUI.java
Compressed SAMLMessage is not required anymore and implemented possibility to disable compression when sending
> Compressed SAMLMessage is not required anymore

- src/org/zaproxy/zap/extension/zest/resources/Messages.properties
Tweak pop up menu item labels to follow title capitalisation.
Part of zaproxy/zaproxy#2000 - General - Fix Title Caps
> zest: tweak pop up menu item labels

- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
Correct some typos in changes in ZapAddOn.xml file.
> ascanrules: fix typos in changes

- src/org/zaproxy/zap/extension/ascanrules/ZapAddOn.xml
> ascanrules: prepare next dev iteration

- src/org/zaproxy/zap/extension/requester/ZapAddOn.xml
- src/org/zaproxy/zap/extension/tlsdebug/ZapAddOn.xml
Update version and remove changes in ZapAddOn.xml files of Requester and
TLS Debug.
> Prepare next dev iterations

- src/org/zaproxy/zap/extension/formhandler/ZapAddOn.xml
> formhandler: prepare next dev iteration

- src/org/zaproxy/zap/extension/ApiGenerator.java
Part of issue [NodeJS API Upgrade](https://github.com/zaproxy/zaproxy/issues/5044)
As per discussion with @thc202 in [zaproxy](https://github.com/zaproxy/zaproxy/pull/5088)
> Updated node output dir

- src/org/zaproxy/zap/extension/jsonview/HttpPanelJsonArea.java
- src/org/zaproxy/zap/extension/jsonview/HttpPanelJsonView.java
- src/org/zaproxy/zap/extension/jsonview/ZapAddOn.xml
Change HttpPanelJsonView to set the main context menu to the view.
Change HttpPanelJsonArea to have the JSON syntax in the menu.
> jsonview: add the main context menu to the view

- src/org/zaproxy/zap/extension/accessControl/ZapAddOn.xml
> accessControl: prepare next dev iteration

- src/org/zaproxy/zap/extension/openapi/ZapAddOn.xml
- src/org/zaproxy/zap/extension/openapi/network/Requestor.java
> Fixes #4961 by adding appropriate accept headers.

- src/org/zaproxy/zap/extension/pscanrulesAlpha/StrictTransportSecurityScanner.java
- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
- src/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
- test/org/zaproxy/zap/extension/pscanrulesAlpha/StrictTransportSecurityScannerUnitTest.java
Justification: https://twitter.com/psiinon/status/1080782442259234817
Might be worth seeing if there are other responses later today before merging?
Can of course discuss any concern here too ;)
> Only report missing STS header on domain redirects at Low threshold.

- src/org/zaproxy/zap/extension/invoke/ZapAddOn.xml
> invoke: prepare next dev iteration

- src/org/zaproxy/zap/extension/portscan/PortScanParam.java
- src/org/zaproxy/zap/extension/portscan/ZapAddOn.xml
Update the default values to match the ones in the default configuration
file.
> portscan: update default values in options

- src/org/zaproxy/zap/extension/domxss/ZapAddOn.xml
- src/org/zaproxy/zap/extension/domxss/resources/help/contents/about.html
Add new version entry in about help page.
> domxss: prepare next dev iteration

- src/org/zaproxy/zap/extension/saverawmessage/ZapAddOn.xml
> saverawmessage: prepare next dev iteration

- src/org/zaproxy/zap/extension/fuzz/ZapAddOn.xml
- src/org/zaproxy/zap/extension/fuzz/files/scripts/templates/httpfuzzerprocessor/Fuzzer HTTP Processor default template.js
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/HttpFuzzerTaskProcessorUtils.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/FuzzerHttpMessageScriptProcessorAdapter.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/FuzzerHttpMessageScriptProcessorAdapterUIHandler.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/HttpFuzzerProcessorScript.java
- src/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/HttpFuzzerProcessorScriptProxy.java
- src/org/zaproxy/zap/extension/fuzz/resources/Messages.properties
- src/org/zaproxy/zap/extension/fuzz/resources/help/contents/httpmessageprocessors.html
> Add parameters to script in httpfuzzer processors

- src/org/zaproxy/zap/extension/frontendscanner/resources/help/contents/frontendscanner.html
- src/org/zaproxy/zap/extension/frontendscanner/resources/help/helpset.hs
- src/org/zaproxy/zap/extension/frontendscanner/resources/help/index.xml
- src/org/zaproxy/zap/extension/frontendscanner/resources/help/map.jhm
- src/org/zaproxy/zap/extension/frontendscanner/resources/help/toc.xml
Relates to zaproxy/zaproxy#4939 .
> [FrontEndScanner] Add basic user help

- src/org/zaproxy/zap/extension/websocket/WebSocketAPI.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
> Add support for 'other' API operations

- src/org/zaproxy/zap/extension/selenium/ZapAddOn.xml
> selenium: prepare next dev iteration

- src/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- src/org/zaproxy/zap/extension/websocket/WebSocketEventPublisher.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
Required for the HUD.
Note that the websocket events are sent synchronously, while the HTTP
events are sent asynchronously.
@thc202 - do you think it would be better to send them asynchronously so
that it has less of a potential impact on performance?
> Generate websocket events

- src/org/zaproxy/zap/extension/websocket/WebSocketAPI.java
- src/org/zaproxy/zap/extension/websocket/ZapAddOn.xml
- src/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
Change WebSocketAPI to also handle API view/action options.
> websocket: handle API options

- test/org/zaproxy/zap/testutils/ActiveScannerTestUtils.java
- test/org/zaproxy/zap/testutils/NanoServerHandler.java
Apply the changes done in master branch to `ActiveScannerTestUtils` and
`NanoServerHandler`, to reduce conflicts when merging.
> Sync testutils (beta)

- test/org/zaproxy/zap/testutils/ActiveScannerTestUtils.java
- test/org/zaproxy/zap/testutils/NanoServerHandler.java
Apply the changes done in master branch to `ActiveScannerTestUtils` and
`NanoServerHandler`, to reduce conflicts when merging.
> Sync testutils (alpha)

- src/org/zaproxy/zap/extension/webdriverwindows/ZapAddOn.xml
Update the description in ZapAddOn.xml file.
Missed in #1948.
> webdriverwindows: update add-on description

- src/org/zaproxy/zap/extension/quickstart/ZapAddOn.xml
- src/org/zaproxy/zap/extension/quickstart/launch/ExtensionQuickStartLaunch.java
Depends on https://github.com/zaproxy/zap-admin/pull/199
> Support dev and 2.8+ versions for default quick start page

- build/build.xml
The add-on is not working correctly.
From zaproxy/zaproxy#4866.
> soap: remove from weekly

- src/org/zaproxy/zap/extension/pscanrulesAlpha/ZapAddOn.xml
Per discussion on zaproxy/zap-extensions#1958
> Pscan Alpha Fix Manifest Typo

- src/org/zaproxy/zap/extension/jython/ZapAddOn.xml
Add the template to manifest, missed in #1931.
> jython: add template to manifest

- .gitignore
Ignore the output directories also in the add-ons and testutils.
> Ignore IntelliJ IDEA output dirs in all projects

- addOns/jxbrowsers/jxbrowser/CHANGELOG.md
- addOns/jxbrowsers/jxbrowser/src/main/javahelp/org/zaproxy/zap/extension/jxbrowser/resources/help/contents/jxbrowser.html
- addOns/jxbrowsers/jxbrowserlinux64/CHANGELOG.md
- addOns/jxbrowsers/jxbrowsermacos/CHANGELOG.md
- addOns/jxbrowsers/jxbrowsers.gradle.kts
- addOns/jxbrowsers/jxbrowserwindows/CHANGELOG.md
- addOns/jxbrowsers/jxbrowserwindows64/CHANGELOG.md
Update JxBrowser to 6.23.1.
Update changelogs for the release of the new version.
Fix zaproxy/zaproxy#5292.
> jxbrowser: update JxBrowser to 6.23.1

- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanner.java
- addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
- addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScannerUnitTest.java
> Application Error Disclosure for 500s modified

- addOns/spiderAjax/spiderAjax.gradle.kts
- addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderListener.java
- addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderPanel.java
> Ajax Spider - Quick Start2 enablers

- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CharsetMismatchScanner.java
- addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
- addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
- addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CharsetMismatchScannerUnitTest.java
- addOns/pscanrulesBeta/CHANGELOG.md
- addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
- addOns/pscanrulesBeta/src/main/resources/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
> Promote Charset Mismatch Passive Scanner to Release

- addOns/jxbrowsers/jxbrowser/CHANGELOG.md
- addOns/jxbrowsers/jxbrowserlinux64/CHANGELOG.md
- addOns/jxbrowsers/jxbrowsermacos/CHANGELOG.md
- addOns/jxbrowsers/jxbrowserwindows/CHANGELOG.md
- addOns/jxbrowsers/jxbrowserwindows64/CHANGELOG.md
Update the release date to the current date and add link to tags.
> jxbrowsers: update changelogs

- addOns/ascanrules/CHANGELOG.md
- addOns/ascanrules/ascanrules.gradle.kts
- addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureWEBINF.java
- addOns/ascanrules/src/main/javahelp/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
- addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
- addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureWEBINFUnitTest.java
- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
- addOns/ascanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
- addOns/ascanrulesBeta/src/main/resources/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties
> ascan Beta to Release Promotion

- addOns/webdrivers/webdriverlinux/CHANGELOG.md
- addOns/webdrivers/webdrivermacos/CHANGELOG.md
- addOns/webdrivers/webdriverwindows/CHANGELOG.md
> webdrivers: prepare release

- .github/main.workflow
- addOns/addOns.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/java/org/zaproxy/gradle/tasks/CreateGitHubRelease.java
- buildSrc/src/main/java/org/zaproxy/gradle/tasks/ExtractLatestChangesChangelog.java
Add a GitHub workflow to create a GitHub release from a pushed tag of an
add-on.
Add build tasks to support the above case.
> Create GitHub release on tag

- testutils/src/main/java/org/zaproxy/zap/testutils/TestUtils.java
Uncomment the override annotations, the classpath is now in the expected
state.
> testutils: address TODOs

- addOns/wappalyzer/CHANGELOG.md
- addOns/wappalyzer/wappalyzer.gradle.kts
> wappalyzer: prepare next dev iteration

- addOns/webdrivers/webdriverlinux/CHANGELOG.md
- addOns/webdrivers/webdriverlinux/webdriverlinux.gradle.kts
- addOns/webdrivers/webdrivermacos/CHANGELOG.md
- addOns/webdrivers/webdrivermacos/webdrivermacos.gradle.kts
- addOns/webdrivers/webdriverwindows/CHANGELOG.md
- addOns/webdrivers/webdriverwindows/webdriverwindows.gradle.kts
The add-ons already met the release status recommendations.
> webdrivers: promote to release

- addOns/addOns.gradle.kts
The extension will not be needed/used.
> Remove ZapVersions extension

- addOns/svndigger/CHANGELOG.md
- addOns/svndigger/svndigger.gradle.kts
Promote to release, the add-on just provides files.
> svndigger: promote to release

- addOns/quickstart/src/main/javahelp/org/zaproxy/zap/extension/quickstart/resources/help/contents/quickstart.html
> Update help for recent changes

- addOns/quickstart/CHANGELOG.md
- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
> Dont make news request if -silent option used

- addOns/webdrivers/webdriverlinux/CHANGELOG.md
- addOns/webdrivers/webdriverlinux/src/main/javahelp/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
- addOns/webdrivers/webdrivermacos/CHANGELOG.md
- addOns/webdrivers/webdrivermacos/src/main/javahelp/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
- addOns/webdrivers/webdrivers.gradle.kts
- addOns/webdrivers/webdriverwindows/CHANGELOG.md
- addOns/webdrivers/webdriverwindows/src/main/javahelp/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html
> Update ChromeDriver to v74.0.3729.6.

- addOns/addOns.gradle.kts
The add-ons included in main and weekly releases will be defined in the
zaproxy repo.
> Remove main/weekly release related tasks

- addOns/addOns.gradle.kts
Check that the tag matches the expected format.
> Validate tag for releases

- addOns/tips/CHANGELOG.md
- addOns/tips/src/main/resources/org/zaproxy/zap/extension/tips/resources/Messages.properties
> Updated tips for 2.8.0

- addOns/fuzzdb/CHANGELOG.md
Mention that the backdoors were moved to a new add-on.
Split into sections.
> fuzzdb: tweak changelog

- addOns/spiderAjax/CHANGELOG.md
- addOns/spiderAjax/spiderAjax.gradle.kts
- addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderTarget.java
- addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderEventPublisher.java
- addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java
> Ajax Spider - generate start and stop events

- addOns/ascanrules/CHANGELOG.md
- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/domxss/CHANGELOG.md
- addOns/domxss/src/main/javahelp/org/zaproxy/zap/extension/domxss/resources/help/contents/about.html
- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesBeta/CHANGELOG.md
- addOns/sqliplugin/CHANGELOG.md
- Active scanner rules;
- Active scanner rules (beta);
- Active scanner rules (alpha);
- Advanced SQLInjection Scanner;
- DOM XSS Active scanner rule;
- Passive scanner rules;
- Passive scanner rules (beta);
- Passive scanner rules (alpha).
> Prepare release of scanner rules add-ons

- addOns/jxbrowsers/jxbrowser/CHANGELOG.md
- addOns/jxbrowsers/jxbrowserlinux64/CHANGELOG.md
- addOns/jxbrowsers/jxbrowsermacos/CHANGELOG.md
- addOns/jxbrowsers/jxbrowserwindows/CHANGELOG.md
- addOns/jxbrowsers/jxbrowserwindows64/CHANGELOG.md
Update changelogs with release date and link to tags.
> jxbrowsers: prepare releases

- addOns/alertFilters/CHANGELOG.md
- addOns/bruteforce/CHANGELOG.md
- addOns/diff/CHANGELOG.md
- addOns/fuzz/CHANGELOG.md
- addOns/gettingStarted/CHANGELOG.md
- addOns/importurls/CHANGELOG.md
- addOns/quickstart/CHANGELOG.md
- addOns/scripts/CHANGELOG.md
- addOns/selenium/CHANGELOG.md
- addOns/spiderAjax/CHANGELOG.md
- addOns/tips/CHANGELOG.md
- addOns/websocket/CHANGELOG.md
- addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/contents/about.html
- addOns/zest/CHANGELOG.md
- Ajax Spider;
- Context Alert Filters;
- Diff;
- Forced Browse;
- Fuzzer;
- Getting Started with ZAP Guide;
- Import files containing URLs;
- Quick Start;
- Script Console;
- Selenium;
- Tips and Tricks;
- WebSockets;
- Zest.
> Prepare release of last main add-ons

- addOns/importurls/CHANGELOG.md
- addOns/importurls/importurls.gradle.kts
- addOns/importurls/src/main/java/org/zaproxy/zap/extension/importurls/ExtensionImportUrls.java
- addOns/importurls/src/main/javahelp/org/zaproxy/zap/extension/importurls/resources/help/contents/importUrls.html
- addOns/importurls/src/main/resources/org/zaproxy/zap/extension/importurls/resources/Messages.properties
Part of issue [zaproxy#3578](https://github.com/zaproxy/zaproxy/issues/3578)
> Updated ImportURL add-on to use new Import Menu

- addOns/allinonenotes/CHANGELOG.md
> allinonenotes: Prepare release v1

- addOns/alertFilters/alertFilters.gradle.kts
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFilterAPI.java
Add the configuration to generate the API clients.
> alertFilters: add API gen config

- addOns/allinonenotes/CHANGELOG.md
- addOns/allinonenotes/allinonenotes.gradle.kts
> allinonenotes: prepare next dev iteration

- addOns/regextester/CHANGELOG.md
> regextester: Prepare release v1

- addOns/regextester/CHANGELOG.md
- addOns/regextester/regextester.gradle.kts
> regextester: prepare next dev iteration

- addOns/spiderAjax/CHANGELOG.md
- addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java
Fixes https://github.com/zaproxy/zaproxy/issues/4521
> Ajax Spider: enable websockets

- addOns/bruteforce/CHANGELOG.md
- addOns/bruteforce/bruteforce.gradle.kts
- addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/BruteForcePanel.java
- addOns/bruteforce/src/main/javahelp/org/zaproxy/zap/extension/bruteforce/resources/help/contents/concepts.html
- addOns/bruteforce/src/main/javahelp/org/zaproxy/zap/extension/bruteforce/resources/help/contents/tab.html
- Add a TableExportButton
- Tweak help (mention the button, and tweak an external link).
> bruteforce: Add export button

- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureSVN.java
- addOns/ascanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
These changes prevent a load of FPs that I'm seeing.
> Fix FP in "Source Code Disclosure SVN"

- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/AbstractAppFilePlugin.java
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/CloudMetadataScanner.java
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/HtAccessScanner.java
Fixes https://github.com/zaproxy/zaproxy/issues/5433
Sorry for no tests, if there were some existing ones I'd have added to them :/
I have tested the FPs against the sites that they were incorrectly flagging.
> Fix FPs in HtAccess and Cloud Metadata rules

- addOns/exportreport/CHANGELOG.md
> exportreport: prepare release

- addOns/exportreport/CHANGELOG.md
- addOns/exportreport/exportreport.gradle.kts
> exportreport: prepare next dev iteration

- addOns/pscanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ModernAppDetectionScanner.java
- addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
- addOns/pscanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
- addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/ModernAppDetectionScannerUnitTest.java
The rule id is added in https://github.com/zaproxy/zaproxy/pull/5446
> pscanrulesAlpha: Added Modern App Detection Scanner

- addOns/fuzzdb/CHANGELOG.md
- addOns/fuzzdb/fuzzdb.gradle.kts
> fuzzdb: prepare next dev iteration

- addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/contents/introduction.html
- addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/contents/pscanrules.html
- addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/contents/script.html
- addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/index.xml
- addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/map.jhm
- addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/toc.xml
Add help for WebSocket Passive scan and scripts
> [WS-Passive-Scan] Add help content

- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
Add scripts under ` addOns/websocket/src/main/zapHomeFiles/scripts/scripts/websocketpassive/`
> [WS-Passive-Scan] Add WebSocket passive scripts by default

- addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/contents/pscanrules.html
- addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Email Disclosure.js
This script scans incoming WebSocket messages for email address.
_____________________________________________________
TODOs:
> [WS-Passive-Scan] Email disclosure scan with javascript 

- addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/contents/pscanrules.html
- addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Base64 Disclosure.js
> [WS-Passive-Scan] Base64 disclosure script with javascript

- addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/contents/pscanrules.html
- addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Application Error Scanner Regex.js
- addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Application Error Scanner.js
This Script analyzes incoming websocket messages for error messages.
____________________________________________________
TODOs:
> [WS-Passive-Scan] Add Error Application Disclosure scan 

- addOns/accessControl/CHANGELOG.md
- addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/AccessControlAPI.java
- addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/ExtensionAccessControl.java
- addOns/accessControl/src/main/javahelp/org/zaproxy/zap/extension/accessControl/resources/help/contents/concepts.html
- addOns/accessControl/src/main/resources/org/zaproxy/zap/extension/accessControl/resources/Messages.properties
Hello, I implemented the module's API for a personal project of mine, so I thought I would share it
> Implement Access Control API

- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/pscanrulesAlpha/CHANGELOG.md
> Release ascanrulesAlpha, ascanrulesBeta and pscanrulesAlpha

- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
- addOns/pscanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts
> Prepare add-ons for next release

- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/pscan/WebSocketScanHelperImpl.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/pscan/scripts/ScriptPassiveHelperDecorator.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/pscan/scripts/ScriptsWebSocketPassiveScanner.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/pscan/scripts/WebSocketPassiveScript.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/pscan/scripts/WebSocketPassiveScriptDecorator.java
- addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Application Error Scanner.js
- addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Base64 Disclosure.js
- addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Debug Error Disclosure.js
- addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Email Disclosure.js
- addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/PII Disclosure.js
- addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Private IP Disclosure.js
- addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Username Idor Scanner.js
- addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/XML Comments Disclosure.js
Makes possible to add getName and getId in the WebSocket Passive scan scripts in order to be displayed in alerts.
> [WS-Passive-Scan] Override getName & getId

- addOns/tokengen/CHANGELOG.md
> tokengen: Prepare release v13

- addOns/websocket/src/test/java/org/zaproxy/zap/extension/websocket/WebSocketAddonTestUtils.java
- addOns/websocket/src/test/java/org/zaproxy/zap/extension/websocket/client/ServerConnectionEstablisherUnitTest.java
- addOns/websocket/src/test/java/org/zaproxy/zap/extension/websocket/client/WebSocketProxyUnitTest.java
- testutils/src/main/java/org/zaproxy/zap/testutils/WebSocketTestUtils.java
Used to establish WebSockcet connection and send messages
> Add Base Class for WebSocket Unit testing

- addOns/openapi/CHANGELOG.md
> openapi: prepare release

- addOns/websocket/CHANGELOG.md
> Prepare websocket for release

- addOns/websocket/CHANGELOG.md
- addOns/websocket/websocket.gradle.kts
> Websocket post release

- addOns/jython/src/main/zapHomeFiles/scripts/templates/extender/getInputsFromuser.py
Adding author name as kamalpreetSec in comments
> Adding author name as kamalpreetSec in comments

- addOns/groovy/CHANGELOG.md
- addOns/groovy/src/main/zapHomeFiles/scripts/templates/extender/ExtenderDefaultTemplate.groovy
- addOns/groovy/src/main/zapHomeFiles/scripts/templates/httpsender/HttpSenderDefaultTemplate.groovy
- addOns/jruby/CHANGELOG.md
- addOns/jruby/src/main/zapHomeFiles/scripts/templates/httpsender/HttpSender default template.rb
- addOns/jython/CHANGELOG.md
- addOns/jython/src/main/zapHomeFiles/scripts/templates/httpsender/HttpSender default template.py
- addOns/replacer/CHANGELOG.md
- addOns/replacer/src/main/resources/org/zaproxy/zap/extension/replacer/resources/Messages.properties
- addOns/scripts/CHANGELOG.md
- addOns/scripts/src/main/zapHomeFiles/scripts/templates/extender/Add panels.js
- addOns/scripts/src/main/zapHomeFiles/scripts/templates/extender/Add toolbar button.js
- addOns/wavsepRpt/src/main/java/org/zaproxy/zap/extension/wavsepRpt/ExtensionWavsepReport.java
Use the new dir path to source files/dirs in zaproxy.
Related to zaproxy/zaproxy#5369.
> Fix links to source files/dirs

- CONTRIBUTING.md
Mention that the help should be updated accordingly to the changes done.
> Mention help update in CONTRIBUTING

- addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/BigRedirectsScannerUnitTest.java
> Add unit tests for BigRedirectsScanner

- addOns/wappalyzer/CHANGELOG.md
> wappalyzer: preapare release v13

- addOns/bruteforce/CHANGELOG.md
- addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/BruteForce.java
- addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/BruteForcePanel.java
- addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/ExtensionBruteForce.java
- addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/OptionsBruteForcePanel.java
- addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/PopupMenuBruteForceDirectory.java
- addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/PopupMenuBruteForceDirectoryAndChildren.java
- addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/PopupMenuBruteForceSite.java
Fixes https://github.com/zaproxy/zaproxy/issues/2848
This is a precursor to addressing https://github.com/zaproxy/zaproxy/issues/2849
> Forced Browse: restructure and provide external access

- addOns/codedx/CHANGELOG.md
> codedx: prepare release

- addOns/customreport/CHANGELOG.md
- addOns/saml/CHANGELOG.md
Update changelogs with release date and link to tag.
> Prepare release for customreport and saml

- addOns/customreport/CHANGELOG.md
- addOns/customreport/customreport.gradle.kts
- addOns/saml/CHANGELOG.md
- addOns/saml/saml.gradle.kts
> Prepare next dev iteration of customreport/saml

- addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/Config.java
Remove `Config#debug`, no longer used/needed.
> bruteforce: remove unused config

- addOns/directorylistv1/CHANGELOG.md
- addOns/directorylistv1/directorylistv1.gradle.kts
- addOns/directorylistv2_3/CHANGELOG.md
- addOns/directorylistv2_3/directorylistv2_3.gradle.kts
- addOns/directorylistv2_3_lc/CHANGELOG.md
- addOns/directorylistv2_3_lc/directorylistv2_3_lc.gradle.kts
The DirBuster link was broken, it didn't redirected to the correct page.
> directorylists: update info URL

- addOns/alertFilters/CHANGELOG.md
- addOns/alertFilters/alertFilters.gradle.kts
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFilter.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFilterAPI.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/DialogAddAlertFilter.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/DialogModifyAlertFilter.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java
- addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/contents/alertFilter.html
- addOns/alertFilters/src/main/resources/org/zaproxy/zap/extension/alertFilters/resources/Messages.properties
- addOns/alertFilters/src/test/java/org/zaproxy/zap/extension/alertFilters/AlertFilterTest.java
Fixes https://github.com/zaproxy/zaproxy/issues/5574
> Extend Alert Filters to apply to more alert fields

- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/treemap/WebSocketTreeMap.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/treemap/nodes/NodesUtilities.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/treemap/nodes/WebSocketNode.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/treemap/nodes/contents/HostFolderContent.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/treemap/nodes/contents/MessageContent.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/treemap/nodes/contents/NodeContent.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/treemap/nodes/contents/RootContent.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/treemap/nodes/contents/WebSocketContent.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/treemap/nodes/factories/NodeFactory.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/treemap/nodes/factories/SimpleNodeFactory.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/treemap/nodes/namers/WebSocketNodeNamer.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/treemap/nodes/namers/WebSocketSimpleNodeNamer.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/treemap/nodes/structural/TreeNode.java
- addOns/websocket/src/main/resources/org/zaproxy/zap/extension/websocket/resources/Messages.properties
- addOns/websocket/src/test/java/org/zaproxy/zap/extension/websocket/WebSocketAddonTestUtils.java
- addOns/websocket/src/test/java/org/zaproxy/zap/extension/websocket/treemap/nodes/WebSocketNodesUnitTest.java
- addOns/websocket/src/test/java/org/zaproxy/zap/extension/websocket/treemap/nodes/content/MessageContentUnitTest.java
- addOns/websocket/src/test/java/org/zaproxy/zap/extension/websocket/treemap/nodes/factories/SimpleNodeFactoryUnitTest.java
This PR is refactor of the existing [PR#1742](https://github.com/zaproxy/zap-extensions/pull/1742). Implements the logic of the Tree Map
______________________________________________________________________________
TODOs
> Add infrastructure for WebSocket Tree Map

- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/XSLTInjection.java
- addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
- addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
See [#3572](https://github.com/zaproxy/zaproxy/issues/3572)
This is a new PR based on the changes in #1384 , but reworked to add more checks.
Tested against https://gist.github.com/CaptainFreak/bf8fb57f5029d29569f76bc7f67c5389, some requests were tested against https://github.com/ctxis/VulnerableXsltConsoleApplication.
> Adds XSLT injection Scanner active rule

- addOns/alertFilters/CHANGELOG.md
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFilter.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFilterAPI.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFiltersMultipleOptionsPanel.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ContextAlertFilterPanel.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/DialogAddAlertFilter.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/DialogModifyAlertFilter.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/GlobalAlertFilterParam.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/OptionsGlobalAlertFilterPanel.java
- addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/contents/alertFilter.html
- addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/contents/globalAlertFilter.html
- addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/index.xml
- addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/map.jhm
- addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/toc.xml
- addOns/alertFilters/src/main/resources/org/zaproxy/zap/extension/alertFilters/resources/Messages.properties
Fixes 5575
Still plan to add more validation (eg of urls and regexes) and the ability to create an alert filter from an alert, but they will be in future PRs.
> Add global alert filters

- addOns/alertFilters/CHANGELOG.md
- addOns/alertFilters/alertFilters.gradle.kts
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFilter.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFiltersMultipleOptionsPanel.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ContextAlertFilterPanel.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/DialogAddAlertFilter.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/DialogModifyAlertFilter.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/OptionsGlobalAlertFilterPanel.java
- addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/contents/alertFilter.html
- addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/contents/alertFilterDialog.html
- addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/contents/contextAlertFilter.html
- addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/contents/globalAlertFilter.html
- addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/helpset.hs
- addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/index.xml
- addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/map.jhm
- addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/toc.xml
- addOns/alertFilters/src/main/resources/org/zaproxy/zap/extension/alertFilters/resources/Messages.properties
Also added the option to test and apply alert filters.
Still WIP as I need to update the help, but I think the code is ready to review.
Fixes https://github.com/zaproxy/zaproxy/issues/3027 (at least I think it does;)
> Added option to create alert filters from alert

- addOns/alertFilters/CHANGELOG.md
- addOns/alertFilters/alertFilters.gradle.kts
Promote addon to release status, per: https://github.com/zaproxy/zap-extensions/pull/2179
> Alert Filters - Promote to Release

- addOns/alertFilters/CHANGELOG.md
- addOns/alertFilters/alertFilters.gradle.kts
> alert filters: Prepare next dev iteration

- addOns/wappalyzer/CHANGELOG.md
> wappalyzer: prepare release

- addOns/custompayloads/CHANGELOG.md
update changelog with release date and link to tag
> custompayloads: Prepare release v0.9

- addOns/custompayloads/CHANGELOG.md
- addOns/custompayloads/custompayloads.gradle.kts
> custompayloads: prepare next dev iteration

- addOns/ascanrulesAlpha/CHANGELOG.md
> ascanrulesAlpha: Prepare release v26

- addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/brk/ClientBreakDialogAdd.java
- addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/brk/ClientBreakDialogEdit.java
- addOns/plugnhack/src/main/resources/org/zaproxy/zap/extension/plugnhack/resources/Messages.properties
- addOns/websocket/CHANGELOG.md
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/brk/WebSocketBreakDialogAdd.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/brk/WebSocketBreakDialogEdit.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ui/WebSocketMessagesViewFilterDialog.java
- addOns/websocket/src/main/resources/org/zaproxy/zap/extension/websocket/resources/Messages.properties
Use resource messages from the add-ons, the core resource messages will
be removed.
Part of zaproxy/zaproxy#5244 - Remove Filter extension
> Do not use core filter resource messages

- addOns/pscanrulesBeta/CHANGELOG.md
update changelog with release date and link to tag
> pscanrulesBeta: prepare relase v20

- addOns/pscanrulesBeta/CHANGELOG.md
- addOns/pscanrulesBeta/pscanrulesBeta.gradle.kts
> pscanrulesBeta: prepare next dev iteration

- addOns/scripts/CHANGELOG.md
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/dialogs/NewScriptDialog.java
Add the empty template entry to the top for consistency with other
fields.
---
Reported in IRC channel.
> scripts: move empty template entry to the top

- addOns/zest/CHANGELOG.md
> zest: prepare release

- addOns/zest/CHANGELOG.md
- addOns/zest/zest.gradle.kts
> zest: prepare next dev iteration

- addOns/tips/CHANGELOG.md
- addOns/tips/src/main/javahelp/org/zaproxy/zap/extension/tips/resources/help/contents/tips.html
- addOns/tips/src/main/resources/org/zaproxy/zap/extension/tips/resources/Messages.properties
Part of https://github.com/zaproxy/zaproxy/issues/5759
> Updated for move from irc.mozilla.org to freenode

- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesBeta/CHANGELOG.md
> Scan rule promotions: prepare releases

- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrules/pscanrules.gradle.kts
- addOns/pscanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts
- addOns/pscanrulesBeta/CHANGELOG.md
- addOns/pscanrulesBeta/pscanrulesBeta.gradle.kts
- ascanrulesAlpha
- ascanrulesBeta
- pscanrulesAlpha
- pscanrulesBeta
- pscanrules
> scanrules: Prepare Next Dev Iteration

- addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java
Check for the "cpe" element instead of catching exception.
> wappalyzer: Tweak CPE handling

- addOns/wappalyzer/CHANGELOG.md
> wappalyzer: prepare release v15

- addOns/quickstart/CHANGELOG.md
- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/LearnMorePanel.java
- addOns/quickstart/src/main/resources/org/zaproxy/zap/extension/quickstart/resources/Messages.properties
> Added online link to ZAP in Ten videos

- addOns/ascanrules/CHANGELOG.md
- addOns/ascanrules/src/main/javahelp/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/ascanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
- addOns/pscanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
- addOns/pscanrulesBeta/CHANGELOG.md
- addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
Plan to do for all of the relevant add-ons:
Feedback appreciated asap so I have less to rework ;)
> Added links to the code in the help.

- addOns/onlineMenu/CHANGELOG.md
- addOns/onlineMenu/src/main/java/org/zaproxy/zap/extension/onlineMenu/ExtensionOnlineMenu.java
> Online menu: updated for new site

- addOns/openapi/CHANGELOG.md
- addOns/openapi/openapi.gradle.kts
- openapi.gradle.kts > Set status BETA.
- CHANGELOG.md > Document promotion "change".
> openapi: Promote to beta

- addOns/alertFilters/CHANGELOG.md
- addOns/ascanrules/CHANGELOG.md
- addOns/bruteforce/CHANGELOG.md
- addOns/diff/CHANGELOG.md
- addOns/directorylistv1/CHANGELOG.md
- addOns/fuzz/CHANGELOG.md
- addOns/gettingStarted/CHANGELOG.md
- addOns/importurls/CHANGELOG.md
- addOns/invoke/CHANGELOG.md
- addOns/onlineMenu/CHANGELOG.md
- addOns/openapi/CHANGELOG.md
- addOns/pscanrules/CHANGELOG.md
- addOns/quickstart/CHANGELOG.md
- addOns/replacer/CHANGELOG.md
- addOns/reveal/CHANGELOG.md
- addOns/saverawmessage/CHANGELOG.md
- addOns/savexmlmessage/CHANGELOG.md
- addOns/scripts/CHANGELOG.md
- addOns/selenium/CHANGELOG.md
- addOns/spiderAjax/CHANGELOG.md
- addOns/tips/CHANGELOG.md
- addOns/webdrivers/webdriverlinux/CHANGELOG.md
- addOns/webdrivers/webdrivermacos/CHANGELOG.md
- addOns/webdrivers/webdriverwindows/CHANGELOG.md
- addOns/websocket/CHANGELOG.md
- addOns/zest/CHANGELOG.md
Prepare the releases of add-ons included in 2.9.0:
- Active scanner rules
- Ajax Spider
- Alert Filters
- Diff
- Directory List v1.0
- Forced Browse
- Fuzzer
- Getting Started with ZAP Guide
- Import files containing URLs
- Invoke Applications
- Linux WebDrivers
- MacOS WebDrivers
- Online menus
- OpenAPI Support
- Passive scanner rules
- Quick Start
- Replacer
- Reveal
- Save Raw Message
- Save XML Message
- Script Console
- Selenium
- Tips and Tricks
- WebSockets
- Windows WebDrivers
- Zest - Graphical Security Scripting Language
Part of zaproxy/zaproxy#5799.
> Prepare releases for 2.9.0

- addOns/wappalyzer/CHANGELOG.md
- addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
CHANGELOG.md > Added change note.
ExtensionWappalyzer > Show panel in `postInstall()`
> wappalyzer: Show panel on install

- addOns/quickstart/CHANGELOG.md
- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/PlugableHud.java
- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/hud/ExtensionQuickStartHud.java
- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/launch/ExtensionQuickStartLaunch.java
- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/launch/LaunchPanel.java
- addOns/quickstart/src/main/resources/org/zaproxy/zap/extension/quickstart/resources/Messages.properties
Also plan to change the HUD icon in another PR
> Added warning when HUD is enabled only in scope

- addOns/pscanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
Per: https://github.com/zaproxy/zaproxy-website/pull/101
Move the space outside the bold tag.
> pscanrulesAlpha - Tweak Spacing in Help

- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
> pscanrules - HttpOnly Help Tweak

- addOns/wappalyzer/CHANGELOG.md
- addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
- addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java
- addOns/wappalyzer/wappalyzer.gradle.kts
- Added SVG Icon support.
- Fixed PNG icon resizing.
> wappalyzer: Initial SVG support using Apache Batik

- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanner.java
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/payloader/ExtensionPayloader.java
- addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
- addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScannerUnitTest.java
Added new functionality and associated unit tests, updated help, and changelog.
> pscanrules: Add Custom Payloads support to Application Error ascan rule

- addOns/quickstart/CHANGELOG.md
> quickstart: prepare for release

- addOns/quickstart/CHANGELOG.md
- addOns/quickstart/quickstart.gradle.kts
> Prepare for next release

- addOns/pscanrules/CHANGELOG.md
> pscanrules: Prepare Release

- addOns/pscanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
- addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
- At Low Threshold alert on all occurrences identified within each response.
- Help and changelog tweaked accordingly.
> Base 64 Disclosure allow to leverage previous behaviour

- build.gradle.kts
Can be run as:
- `./gradlew addOns:ascanrules:dependencyUpdates`
- `./gradlew dependencyUpdates`
> Add Gradle Task to Check Dependency Updates

- addOns/scripts/CHANGELOG.md
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ScriptsListPanel.java
- addOns/scripts/src/main/resources/org/zaproxy/zap/extension/scripts/resources/Messages.properties
Improve Extender descriptive text.
Fix zaproxy/zaproxy#5746
> Improve discoverability for installing scripts from templates

- addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
Use code tags on domain examples, per: https://github.com/zaproxy/zaproxy-website/issues/47
> Minor Punctuation Fix

- addOns/wappalyzer/CHANGELOG.md
> Wappalyzer version 17

- addOns/selenium/CHANGELOG.md
- addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
Fixes https://github.com/zaproxy/zap-hud/issues/701
Thanks to @thc202 for finding this!
> Set Firefox browser.tabs.documentchannel pref to false to fix HUD issue

- addOns/selenium/CHANGELOG.md
> Selenium: release 15.2

- addOns/selenium/CHANGELOG.md
- addOns/selenium/selenium.gradle.kts
> Selenium: prepare for the next release

- addOns/jruby/jruby.gradle.kts
- org.apache.commons:commons-lang3 [3.5 -> 3.10]
> jruby: Update dependency

- addOns/sqliplugin/sqliplugin.gradle.kts
- addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLiBoundary.java
- addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLiPayloadManager.java
- addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLiTest.java
- addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLiTestDetails.java
- addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLiTestRequest.java
- addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLiTestResponse.java
- org.jdom:jdom [1.1.3 -> 2.0.2]
Update all imports. CHANGELOG already includes 'Maintenance changes'.
> sqliplugin: Update dependencies

- addOns/bugtracker/CHANGELOG.md
- addOns/bugtracker/bugtracker.gradle.kts
- org.kohsuke:github-api [1.75 -> 1.109]
> bugtracker: Update Dependency

- addOns/groovy/CHANGELOG.md
- addOns/groovy/groovy.gradle.kts
- org.codehaus.groovy:groovy-all [2.4.14 -> 3.0.2]
Tested, running a stand alone history loop.
> groovy: Update Dependency

- addOns/wappalyzer/CHANGELOG.md
> wappalyzer: Prepare Addon Release v18

- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjection.java
- addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
- addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
Adding four active scan rules packages
Adding control for Authentication Bypass
> Implemented penetration test for MongoDB Injection

- addOns/pscanrules/CHANGELOG.md
> pscanrules: Prepare release v28

- .gitattributes
Prevent line ending changes in PDF files.
> Handle PDFs as binary

- addOns/fuzzdb/CHANGELOG.md
> fuzzdb: Prepare release v6

- addOns/fuzzdb/CHANGELOG.md
- addOns/fuzzdb/fuzzdb.gradle.kts
> fuzzdb:Prepare next dev iteration

- addOns/selenium/CHANGELOG.md
- addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
- addOns/selenium/src/main/javahelp/org/zaproxy/zap/extension/selenium/resources/help/contents/intro.html
Prevent the Selenium scripts from interfering with the crawl process.
Add note in the help page.
> selenium: run script synchronously for AJAX Spider

- addOns/tips/CHANGELOG.md
- addOns/tips/src/main/javahelp/org/zaproxy/zap/extension/tips/resources/help/contents/tips.html
- addOns/tips/src/main/resources/org/zaproxy/zap/extension/tips/resources/Messages.properties
Align with: https://github.com/zaproxy/zaproxy-website/pull/103
> tips-and-tricks: Update docker refs

- addOns/pscanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
- addOns/pscanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
- addOns/pscanrulesBeta/CHANGELOG.md
- addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ModernAppDetectionScanner.java
- addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
- addOns/pscanrulesBeta/src/main/resources/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
- addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/ModernAppDetectionScannerUnitTest.java
- Moved rule class.
- Moved unit test.
- Moved resource keys/values.
- Moved help entry.
> pscanrules alpha/beta: Promote 'Modern Web Application' rule to Beta

- addOns/quickstart/CHANGELOG.md
- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ajaxspider/AjaxSpiderExplorer.java
Use/copy the main AJAX Spider options for the automated scan.
Fix zaproxy/zaproxy#5981.
> quickstart: use AJAX Spider options

- addOns/encoder/CHANGELOG.md
- addOns/retire/CHANGELOG.md
> retire & encoder: Prepare release v0.1.0

- addOns/commonlib/CHANGELOG.md
> commonlib: prepare release v1.0.0

- addOns/commonlib/CHANGELOG.md
- addOns/commonlib/commonlib.gradle.kts
> commonlib: prepare next dev iteration

- addOns/encoder/CHANGELOG.md
- addOns/encoder/encoder.gradle.kts
- addOns/encoder/src/main/java/org/zaproxy/addon/encoder/EncodeDecodeDialog.java
Don't force "heading" text black.
> encoder: Prepared next dev iteration & dark mode tweaks

- addOns/custompayloads/CHANGELOG.md
- addOns/custompayloads/custompayloads.gradle.kts
> custompayloads: update ZAP to 2.9.0

- addOns/encoder/CHANGELOG.md
- addOns/encoder/src/main/java/org/zaproxy/addon/encoder/EncodeDecodeDialog.java
- addOns/encoder/src/main/java/org/zaproxy/addon/encoder/EncodeDecodeOptions.java
- addOns/encoder/src/main/java/org/zaproxy/addon/encoder/EncodeDecodeOptionsPanel.java
- addOns/encoder/src/main/java/org/zaproxy/addon/encoder/ExtensionEncoder.java
- addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Base64Decoder.java
- addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Base64Encoder.java
- addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Base64UrlDecoder.java
- addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Base64UrlEncoder.java
- addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/contents/options.html
- addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/index.xml
- addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/map.jhm
- addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/toc.xml
- addOns/encoder/src/main/resources/org/zaproxy/addon/encoder/resources/Messages.properties
- Base64Encoder/Decoder > Handle charset/line break options.
- EncodeDecodeDialog > Add update call.
- EncodeDecodeParam & Panel > Config handling & UI component.
- ExtensionEncoder > Updated to hook the options panel, listen for options changes, etc.
- Messages.properties > Add new supporting keys/values & properly alphabetize.
- CHANGELOG > Note the addition.
Part of: zaproxy/zaproxy#5996
> encoder: Implement Base64 options

- addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerAppsJsonParseUnitTest.java
Should I revert the date change, I'm not sure why spotlessApply did that.
> wappalyzer: Tweak UnitTest to collect all failing patterns

- addOns/encoder/src/main/java/org/zaproxy/addon/encoder/ExtensionEncoder.java
Initialise the dialogue when hooking the options changed listener.
Extract getter for the dialogue.
> encoder: init dialogue for options listener

- addOns/ascanrules/CHANGELOG.md
- addOns/ascanrules/ascanrules.gradle.kts
- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
- addOns/encoder/CHANGELOG.md
- addOns/encoder/encoder.gradle.kts
- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrules/pscanrules.gradle.kts
- addOns/pscanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts
- addOns/pscanrulesBeta/CHANGELOG.md
- addOns/pscanrulesBeta/pscanrulesBeta.gradle.kts
- addOns/retire/CHANGELOG.md
- addOns/retire/retire.gradle.kts
> pscanrules (all), ascanrules (all), retire, encoder: Next dev iteration

- addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ExtensionGraphQl.java
- addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlApi.java
- addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParser.java
- addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ImportFromAbstractDialog.java
- addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ImportFromFileDialog.java
- addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ImportFromUrlDialog.java
- addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/contents/graphql.html
- addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties
- Create classes for Import from File / URL Dialogs
- Create class GraphQlParser
- Ability to add endpoint url to the sites tree
- Replace 'Target URL' with 'Endpoint URL' for clarity
> Add Import from File / URL Dialogs

- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesAlpha/src/main/zapHomeFiles/json/hidden_files.json
* hidden_files.json - Added a few more files/patterns from snallygaster.
* CHANGELOG - Updated with add note.
> Hidden File Finder add patterns

- addOns/wappalyzer/CHANGELOG.md
> wappalyzer: Prepare release v19

- addOns/jruby/CHANGELOG.md
- addOns/jruby/src/main/zapHomeFiles/scripts/templates/passive/Passive default template.rb
ZAP complained about `appliesToHistoryType()` missing.
> Make Ruby passive template work again

- addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/Messages.properties
Adding description to the AjaxSpider functions on API
> Add descriptions to AJAX Spider API endpoints

- addOns/retire/CHANGELOG.md
- addOns/retire/retire.gradle.kts
> retire: Prepare next dev iteration

- addOns/graaljs/graaljs.gradle.kts
- addOns/graaljs/src/main/java/org/zaproxy/zap/extension/graaljs/GraalJsEngineWrapper.java
Update to latest version, adapt code accordingly.
> graaljs: update GraalVM JavaScript library

- addOns/sqliplugin/sqliplugin.gradle.kts
- addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLInjectionScanRule.java
- addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLiUnionEngine.java
- addOns/sqliplugin/src/main/javahelp/help/contents/sqliplugin.html
- addOns/sqliplugin/src/main/resources/org/zaproxy/zap/extension/sqliplugin/resources/Messages.properties
- Help content.
- Some Messages.properties key names and values.
- CHANGELOG already contains "Maintenance changes" item.
- sqliplugin.gradle.kts updated class name for spotless exclusion.
> sqliplugin: ScanRule Consistency

- addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2UnitTest.java
- addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/BruteForcePanel.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/ui/HttpFuzzerResultsTableModel.java
- addOns/onlineMenu/src/main/java/org/zaproxy/zap/extension/onlineMenu/ExtensionOnlineMenu.java
- addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/ClientsPanel.java
- addOns/portscan/src/main/java/org/zaproxy/zap/extension/portscan/PortScanPanel.java
- addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/LinkTargetScanRule.java
- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartPanel.java
- addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ExtensionReplacer.java
- addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ManualHttpRequestEditorPanel.java
- addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/RequesterPanel.java
- addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/RightClickMsgMenuRequester.java
- addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ToolsMenuItemRequester.java
- addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderPanel.java
- addOns/tlsdebug/src/main/java/org/zaproxy/zap/extension/tlsdebug/TlsDebugPanel.java
- addOns/tokengen/src/main/java/org/zaproxy/zap/extension/tokengen/TokenGenerator.java
- addOns/tokengen/src/main/java/org/zaproxy/zap/extension/tokengen/TokenPanel.java
- addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechPanel.java
- addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ui/WebSocketPanel.java
- addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestResultsPanel.java
- addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestLoopDialog.java
Address TODOs by using newer core methods and constants.
> Address TODOs

- addOns/fuzzdb/CHANGELOG.md
> fuzzdb: prepare relase v7

- .github/workflows/create_retirejs_update.yml
- .github/workflows/create_wappalyzer_update.yml
> Wappalyzer and Retire update jobs now include commit signoff

- addOns/imagelocationscanner/imagelocationscanner.gradle.kts
- addOns/imagelocationscanner/src/main/java/org/zaproxy/zap/extension/imagelocationscanner/ImageLocationScanRule.java
- addOns/imagelocationscanner/src/test/java/org/zaproxy/zap/extension/imagelocationscanner/ImageLocationScanRuleUnitTest.java
- Unit Test class names.
- CHANGELOG already contains a "maintenance changes" note.
> ILS: ScanRule Consistency

- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/CloudMetadataScanRule.java
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/EnvFileScanRule.java
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleFileActiveScanRule.java
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleSimpleActiveScanRule.java
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/HiddenFilesScanRule.java
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRule.java
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjectionScanRule.java
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/XsltInjectionScanRule.java
- addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
- addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
- addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/XsltInjectionScanRuleUnitTest.java
- Message.properties keys (and some values).
- Help content.
- Replace blogspot URLs with zaproxy.org.
---
- CHANGELOG already contains "Maintenance changes" entry.
> ascanrules Alpha: ScanRule Consistency

- addOns/fuzz/src/test/java/org/zaproxy/zap/extension/fuzz/payloads/generator/JsonPayloadGeneratorUnitTest.java
Rename `JsonPayloadGeneratorUnitTest#shouldGenerateOneFuzzedPayload` to
`shouldGenerateAtLeastOneFuzzedPayload` and tweak accordingly, as the
original value might be returned as well.
Fix zaproxy/zaproxy#5349.
> fuzz: tweak test to match the expectations

- addOns/imagelocationscanner/CHANGELOG.md
> imagelocationscanner: Prepare release v2

- addOns/imagelocationscanner/CHANGELOG.md
- addOns/imagelocationscanner/imagelocationscanner.gradle.kts
> imagelocationscanner: Prepare next dev iteration

- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosureScanRule.java
- addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosureScanRuleUnitTest.java
Fixes https://github.com/zaproxy/zaproxy/issues/6059
> Don't raise issues for non success codes unless at LOW threshold

- addOns/viewstate/CHANGELOG.md
- addOns/viewstate/viewstate.gradle.kts
> viewstate: prepare next dev iteration

- addOns/requester/CHANGELOG.md
> requester: prepare release

- addOns/requester/CHANGELOG.md
- addOns/requester/requester.gradle.kts
> requester: prepare next dev iteration

- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ElmahScanRule.java
- addOns/ascanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
- addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/ElmahScanRuleUnitTest.java
Fixes https://github.com/zaproxy/zaproxy/issues/6076
> ELMAH: by default dont report files without expected content

- addOns/ascanrulesBeta/CHANGELOG.md
> Prepare ascanBeta release v29

- addOns/ascanrulesAlpha/src/main/zapHomeFiles/json/hidden_files.json
CHANGELOG already contains a note regarding addition of HFF patterns.
> Hidden File Finder: Add Apache Server Information

- addOns/webdrivers/webdriverlinux/CHANGELOG.md
- addOns/webdrivers/webdriverlinux/src/main/javahelp/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
- addOns/webdrivers/webdrivermacos/CHANGELOG.md
- addOns/webdrivers/webdrivermacos/src/main/javahelp/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
- addOns/webdrivers/webdrivers.gradle.kts
- addOns/webdrivers/webdriverwindows/CHANGELOG.md
- addOns/webdrivers/webdriverwindows/src/main/javahelp/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html
> Update and release new gecko and chrome drivers

- addOns/webdrivers/webdriverlinux/CHANGELOG.md
- addOns/webdrivers/webdriverlinux/webdriverlinux.gradle.kts
- addOns/webdrivers/webdrivermacos/CHANGELOG.md
- addOns/webdrivers/webdrivermacos/webdrivermacos.gradle.kts
- addOns/webdrivers/webdriverwindows/CHANGELOG.md
- addOns/webdrivers/webdriverwindows/webdriverwindows.gradle.kts
> Prepare webdrivers for next release

- addOns/ascanrules/CHANGELOG.md
- addOns/commonlib/CHANGELOG.md
- addOns/retire/CHANGELOG.md
- addOns/wappalyzer/CHANGELOG.md
> Prepare releases: commonlib, retire, wappalyzer, ascanrules

- addOns/scripts/CHANGELOG.md
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/OutputPanelWriter.java
> Fixed case where script print statements could deadlock ZAP

- addOns/ascanrules/CHANGELOG.md
- addOns/ascanrules/ascanrules.gradle.kts
- addOns/commonlib/CHANGELOG.md
- addOns/commonlib/commonlib.gradle.kts
- addOns/retire/CHANGELOG.md
- addOns/retire/retire.gradle.kts
- addOns/wappalyzer/CHANGELOG.md
- addOns/wappalyzer/wappalyzer.gradle.kts
> Next Dev Iteration: ascanrules, commonlib, retire, wappalyzer

- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesAlpha/CHANGELOG.md
> a & p scanrulesAlpha: Prepare releases

- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
- addOns/pscanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts
Signed-off-by: Kingthorin <kingthorin@users.noreply.github.com>
> a & p scanrulesAlpha: Prepare next dev iteration

- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ViewstateScanRule.java
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XFrameOptionScanRule.java
Associated script changes will follow v shortly...
> Changed ViewState and XFrameOption to return example alerts for the docs

- addOns/graphql/CHANGELOG.md
- addOns/graphql/graphql.gradle.kts
- Update version and changelog of graphql
- Update manifest
> Prepare next dev iteration

- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionHypersonicScanRule.java
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionMsSqlScanRule.java
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionMyqlScanRule.java
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionOracleScanRule.java
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionPostgreScanRule.java
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionSqLiteScanRule.java
- addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/ActiveScannerAppParamTest.java
- addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionHypersonicScanRuleUnitTest.java
- addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionMsSqlScanRuleUnitTest.java
- addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionMySsqlScanRuleUnitTest.java
- addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionOracleScanRuleUnitTest.java
- addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionSQLiteScanRuleUnitTest.java
Plan to change all similar rules like this.
> Double check potential SQL timing issues

- addOns/ascanrulesBeta/CHANGELOG.md
> Prepare to release ascanrulesBeta 31

- .github/workflows/create_wappalyzer_update.yml
Per: https://github.com/AliasIO/wappalyzer/commit/9e8537383a8cd2fb35921e591dc9fb20fe7547ed#diff-76d5ffeac090c76ed5f4c581f02f3c53
> Update Wappalyzer workflow to conform to upstream changes

- addOns/fuzz/CHANGELOG.md
- addOns/fuzz/fuzz.gradle.kts
> fuzz: prepare release

- addOns/fuzz/CHANGELOG.md
- addOns/fuzz/fuzz.gradle.kts
> fuzz: prepare next dev iteration

- addOns/customreport/CHANGELOG.md
- addOns/customreport/src/main/java/org/zaproxy/zap/extension/customreport/AlertDetailsPanel.java
- addOns/customreport/src/main/java/org/zaproxy/zap/extension/customreport/ExtensionCustomReport.java
- addOns/customreport/src/main/java/org/zaproxy/zap/extension/customreport/ReportLastScan.java
- addOns/customreport/src/main/javahelp/org/zaproxy/zap/extension/customreport/resources/help/contents/customreport.html
- addOns/customreport/src/main/resources/org/zaproxy/zap/extension/customreport/resources/Messages.properties
- addOns/customreport/src/main/zapHomeFiles/xml/report.concise.html.xsl
- addOns/customreport/src/main/zapHomeFiles/xml/report.separated.html.xsl
- addOns/customreport/src/main/zapHomeFiles/xml/report.traditional.html.xsl
This is my first contribution.
I added the checkbox and field as hinted in the issue report https://github.com/zaproxy/zaproxy/issues/6151
However I wasn't able to test my solution as I'm not sure how to install a locally built addOn. Also I couldn't find any tests to update. So any help testing this would be much appreciated!
Fix zaproxy/zaproxy#6151.
> Add evidence to custom HTML reports

- addOns/kotlin/CHANGELOG.md
> Prepare kotlin for release

- addOns/encoder/CHANGELOG.md
> encoder: Prepare release v0.3.0

- addOns/kotlin/CHANGELOG.md
- addOns/kotlin/kotlin.gradle.kts
> Kotlin - prepare for next release

- addOns/encoder/CHANGELOG.md
- addOns/encoder/encoder.gradle.kts
- Update version and changelog.
- Promote to beta.
- Add agreed info URL for manifest.
> encoder: Prepare next dev iteration

- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
> AscanRulesBeta: Prepare for next release

- addOns/wappalyzer/CHANGELOG.md
> wappalyzer: Prepare release v20.3.0

- addOns/openapi/openapi.gradle.kts
Update Swagger parser to latest version.
Close zaproxy/zaproxy#6205.
> openapi: update dependency

- addOns/accessControl/CHANGELOG.md
> Prepare release v6 Access Control

- addOns/accessControl/CHANGELOG.md
- addOns/accessControl/accessControl.gradle.kts
> Access Control: prepare for the next release

- addOns/scripts/CHANGELOG.md
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/OutputPanel.java
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/SyntaxHighlightTextArea.java
Depends on https://github.com/zaproxy/zaproxy/pull/6202
Part of https://github.com/zaproxy/zaproxy/issues/5542
> Support dark mode and dynamic Look and Feel switching

- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartBackgroundPanel.java
- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartHelper.java
- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartPanel.java
This is not perfect - some of the text backgrounds turn grey, but its much better than the current code handles Look and Feel switching ;)
Havnt updated the ChangeLog as this is related to the dark mode handling..
> QuickStart - cope with LaF switching

- addOns/graphql/src/main/java/org/zaproxy/addon/graphql/InlineInjector.java
- Add javadoc comments for InlineInjector methods.
- Add if check in InlineInjector#inject to reduce number of operations.
> GraphQL: Minor updates

- addOns/ascanrules/CHANGELOG.md
- addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/BufferOverflowScanRule.java
- addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CodeInjectionScanRule.java
- addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrlfInjectionScanRule.java
- addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ExternalRedirectScanRule.java
- addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/FormatStringScanRule.java
- addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ParameterTamperScanRule.java
- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleFileActiveScanRule.java
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleSimpleActiveScanRule.java
- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ChallengeCallbackImplementor.java
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/CloudMetadataScanRule.java
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ExpressionLanguageInjectionScanRule.java
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/HeartBleedActiveScanRule.java
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureSvnScanRule.java
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionSqLiteScanRule.java
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/UsernameEnumerationScanRule.java
- addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/XsltInjectionScanRule.java
Address all Sonar findings for ascanrules, ascanrulesAlpha, ascanrulesBeta (there was 33 total, I may have skipped one). A change
note to CHANGELOGs. Update ascanruleBeta test dependency Apache commons-lang3 3.9 to 3.11.
> ascanrules address Sonar findings & Maintenance

- addOns/tlsdebug/src/main/java/org/zaproxy/zap/extension/tlsdebug/TlsDebugPanel.java
Reinstate the background colour of the panel when the look and feel is
changed.
Part of zaproxy/zaproxy#6201.
> tlsdebug: react to L&F changes

- .travis.yml
- addOns/domxss/CHANGELOG.md
- addOns/domxss/domxss.gradle.kts
- addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
- addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/ExtensionDomXSS.java
- addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/WebDriverWrapper.java
- addOns/domxss/src/main/javahelp/org/zaproxy/zap/extension/domxss/resources/help/contents/domxss.html
- addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java
- addOns/domxss/src/test/resources/org/zaproxy/zap/extension/domxss/DomPropagation.html
- addOns/domxss/src/test/resources/org/zaproxy/zap/extension/domxss/EventInnerHtml.html
- addOns/domxss/src/test/resources/org/zaproxy/zap/extension/domxss/LocationHashAssign.html
- addOns/domxss/src/test/resources/org/zaproxy/zap/extension/domxss/LocationHashEval.html
- addOns/domxss/src/test/resources/org/zaproxy/zap/extension/domxss/LocationHashFormAction.html
- addOns/domxss/src/test/resources/org/zaproxy/zap/extension/domxss/LocationHashFunction.html
- addOns/domxss/src/test/resources/org/zaproxy/zap/extension/domxss/LocationHashInlineEvent.html
- addOns/domxss/src/test/resources/org/zaproxy/zap/extension/domxss/LocationHashReplace.html
- addOns/domxss/src/test/resources/org/zaproxy/zap/extension/domxss/LocationHashSetTimeout.html
- addOns/domxss/src/test/resources/org/zaproxy/zap/extension/domxss/TypingInnerHtml.html
> Support Chrome, Perf improvements, Unit tests and promote to beta

- addOns/onlineMenu/CHANGELOG.md
- addOns/onlineMenu/src/main/java/org/zaproxy/zap/extension/onlineMenu/ExtensionOnlineMenu.java
- addOns/onlineMenu/src/main/resources/org/zaproxy/zap/extension/onlineMenu/resources/Messages.properties
> Menu changes

- addOns/formhandler/CHANGELOG.md
- addOns/formhandler/formhandler.gradle.kts
> Form handler: promote to beta

- addOns/retire/CHANGELOG.md
- addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
> Retire: Add example alerts

- addOns/retire/CHANGELOG.md
> Retire: Prepare release 0.5.0

- addOns/retire/CHANGELOG.md
- addOns/retire/retire.gradle.kts
> Retire: prepare for next release

- addOns/bugtracker/CHANGELOG.md
- addOns/bugtracker/src/main/javahelp/org/zaproxy/zap/extension/bugtracker/resources/help/contents/bugtracker.html
> bugtracker: Remove broken link from the user guide

- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieLooselyScopedScanRule.java
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieSameSiteScanRule.java
- addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieLooselyScopedScanRuleUnitTest.java
- addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieSameSiteScanRuleUnitTest.java
Allow to ignore cookies in same site and loosely scoped scan rules
Resolves zaproxy/zaproxy#6264
(Edit: by @kingthorin, fixed linked issue number)
> Allow to ignore cookies in same site and loosely scoped scan rules

- addOns/webdrivers/webdriverlinux/CHANGELOG.md
- addOns/webdrivers/webdriverlinux/src/main/javahelp/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
- addOns/webdrivers/webdrivermacos/CHANGELOG.md
- addOns/webdrivers/webdrivermacos/src/main/javahelp/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
- addOns/webdrivers/webdrivers.gradle.kts
- addOns/webdrivers/webdriverwindows/CHANGELOG.md
- addOns/webdrivers/webdriverwindows/src/main/javahelp/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html
> Update to geckodriver 0.28.0 and prep for release

- addOns/webdrivers/webdriverlinux/CHANGELOG.md
- addOns/webdrivers/webdriverlinux/webdriverlinux.gradle.kts
- addOns/webdrivers/webdrivermacos/CHANGELOG.md
- addOns/webdrivers/webdrivermacos/webdrivermacos.gradle.kts
- addOns/webdrivers/webdriverwindows/CHANGELOG.md
- addOns/webdrivers/webdriverwindows/webdriverwindows.gradle.kts
> Webdrivers - prepare for the next release

- addOns/fuzz/CHANGELOG.md
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/processor/Base64DecodeProcessor.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/processor/Base64EncodeProcessor.java
- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InsecureAuthenticationScanRule.java
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InsecureJsfViewStatePassiveScanRule.java
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ViewstateScanRule.java
- addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InsecureAuthenticationScanRuleUnitTest.java
- addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InsecureJsfViewStatePassiveScanRuleUnitTest.java
- addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ViewStateScanRuleUnitTest.java
- addOns/pscanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
- addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ViewStateDecoder.java
- addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/XChromeLoggerDataInfoLeakScanRule.java
- addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/XChromeLoggerDataInfoLeakScanRuleUnitTest.java
- addOns/saml/CHANGELOG.md
- addOns/saml/src/main/java/org/zaproxy/zap/extension/saml/SAMLUtils.java
- addOns/viewstate/CHANGELOG.md
- addOns/viewstate/src/main/java/org/zaproxy/zap/extension/viewstate/zap/utils/ASPViewState.java
- addOns/viewstate/src/main/java/org/zaproxy/zap/extension/viewstate/zap/utils/JSFViewState.java
- addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestScriptsDialog.java
Use JRE Base64 class instead, the core class is deprecated.
> Replace usages of core Base64 class

- addOns/pscanrulesAlpha/CHANGELOG.md
> pscanrulesAlpha: prepare release

- addOns/pscanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts
> pscanrulesAlpha: prepare next dev iteration

- addOns/graaljs/CHANGELOG.md
- addOns/graaljs/src/main/java/org/zaproxy/zap/extension/graaljs/ExtensionGraalJs.java
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/active/Active default template GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/authentication/Authentication default template GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/authentication/BodgeIt Store Authentication GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/authentication/Simple Form-Based Authentication GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/authentication/Wordpress Authentication GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/httpsender/AddZapHeader GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/httpsender/HttpSender default template GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/passive/Passive default template GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/proxy/Proxy default template GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/session/Juice Shop Session Management GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/session/Session Management default template GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/standalone/Loop through history table GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/standalone/Standalone default template GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/standalone/Traverse sites tree GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/targeted/Find HTML comments GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/targeted/Targeted default template GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/variant/Input Vector default template GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/variant/Site modifying JSON example GraalJS.js
> Add templates and prepare for release

- addOns/webdrivers/webdriverlinux/CHANGELOG.md
- addOns/webdrivers/webdriverlinux/src/main/javahelp/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
- addOns/webdrivers/webdrivermacos/CHANGELOG.md
- addOns/webdrivers/webdrivermacos/src/main/javahelp/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
- addOns/webdrivers/webdrivers.gradle.kts
- addOns/webdrivers/webdriverwindows/CHANGELOG.md
- addOns/webdrivers/webdriverwindows/src/main/javahelp/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html
> Webdrivers: Update ChromeDriver to 87.0.4280.20

- addOns/graaljs/CHANGELOG.md
- addOns/graaljs/graaljs.gradle.kts
> Graal JS - Prepare for the next release

- addOns/webdrivers/webdriverlinux/CHANGELOG.md
- addOns/webdrivers/webdriverlinux/webdriverlinux.gradle.kts
- addOns/webdrivers/webdrivermacos/CHANGELOG.md
- addOns/webdrivers/webdrivermacos/webdrivermacos.gradle.kts
- addOns/webdrivers/webdriverwindows/CHANGELOG.md
- addOns/webdrivers/webdriverwindows/webdriverwindows.gradle.kts
> Webdrivers: prepare for next release

- addOns/graphql/CHANGELOG.md
> graphql: Prepare release

- addOns/graphql/CHANGELOG.md
- addOns/graphql/graphql.gradle.kts
> graphql: Prepare next dev iteration

- addOns/pscanrules/CHANGELOG.md
Update changelog with release date and link to tag. (Publish changes before 2.10 adaptations.)
> pscanrules: Prepare release v30

- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrules/pscanrules.gradle.kts
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRule.java
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRule.java
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XContentTypeOptionsScanRule.java
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XFrameOptionScanRule.java
- addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRuleUnitTest.java
- addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRuleUnitTest.java
- addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/XContentTypeOptionScanRuleUnitTest.java
- addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/XFrameOptionsScanRuleUnitTest.java
- Prepare next dev iteration.
- Update version and changelog.
- Update scan rule unit tests to account for the changes.
- As a "clean code" task added Given/When/Then comments to unit tests.
> pscanrules: Next Dev Iteration & Update to take advantage of 2.10 core

- addOns/ascanrules/CHANGELOG.md
- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesBeta/CHANGELOG.md
> ascanrules: Prepare releases

- addOns/ascanrules/CHANGELOG.md
- addOns/ascanrules/ascanrules.gradle.kts
- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
Update versions and changelogs
> ascanrules: Prepare next dev iterations

- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/AttackThread.java
Depends on https://github.com/zaproxy/zaproxy/pull/6350
DO NOT merge unless the above PR is merged :)
> Quick Start - handle urls ending with a slash correctly

- addOns/openapi/openapi.gradle.kts
Update Swagger parsers to latest versions.
> openapi: update dependencies

- addOns/wappalyzer/src/main/resources/org/zaproxy/zap/extension/wappalyzer/resources/apps.json
- apps.json > Remove improper comma.
> wappalyzer: apps.json remove spurious comma

- addOns/ascanrules/CHANGELOG.md
- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/bruteforce/CHANGELOG.md
- addOns/bruteforce/bruteforce.gradle.kts
- addOns/commonlib/CHANGELOG.md
- addOns/commonlib/commonlib.gradle.kts
- addOns/customreport/CHANGELOG.md
- addOns/customreport/customreport.gradle.kts
- addOns/encoder/CHANGELOG.md
> First phase of 2.10 add-on releases

- addOns/ascanrules/CHANGELOG.md
- addOns/ascanrulesBeta/CHANGELOG.md
- addOns/bruteforce/CHANGELOG.md
- addOns/commonlib/CHANGELOG.md
- addOns/customreport/CHANGELOG.md
- addOns/encoder/CHANGELOG.md
> Updated release date

- addOns/exportreport/CHANGELOG.md
- addOns/exportreport/exportreport.gradle.kts
- addOns/formhandler/CHANGELOG.md
- addOns/formhandler/formhandler.gradle.kts
- addOns/fuzz/CHANGELOG.md
- addOns/fuzz/fuzz.gradle.kts
- addOns/groovy/CHANGELOG.md
- addOns/groovy/groovy.gradle.kts
- addOns/jruby/CHANGELOG.md
- addOns/jruby/jruby.gradle.kts
- addOns/jython/CHANGELOG.md
- addOns/jython/jython.gradle.kts
> 2.10 add-on releases phase 2

- addOns/domxss/CHANGELOG.md
- addOns/domxss/domxss.gradle.kts
- addOns/scripts/CHANGELOG.md
- addOns/scripts/scripts.gradle.kts
- addOns/selenium/CHANGELOG.md
- addOns/selenium/selenium.gradle.kts
- addOns/tlsdebug/CHANGELOG.md
- addOns/tlsdebug/tlsdebug.gradle.kts
- addOns/tokengen/CHANGELOG.md
- addOns/tokengen/tokengen.gradle.kts
- addOns/wappalyzer/CHANGELOG.md
> 2.10 add-on releases phase 4

- addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/CookieUtils.java
- addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/CookieUtilsUnitTest.java
- addOns/customreport/src/main/java/org/zaproxy/zap/extension/customreport/ReportGenerator.java
- addOns/diff/src/main/java/org/zaproxy/zap/extension/diff/diff_match_patch.java
- addOns/encoder/src/main/java/org/zaproxy/addon/encoder/EncodeDecodeDialog.java
- addOns/httpsInfo/src/main/java/org/zaproxy/zap/extension/httpsinfo/HttpsInfoOutputPanel.java
- addOns/httpsInfo/src/main/resources/org/zaproxy/zap/extension/httpsinfo/resources/Messages.properties
- addOns/imagelocationscanner/src/main/java/org/zaproxy/zap/extension/imagelocationscanner/ImageLocationScanRule.java
- addOns/importLogFiles/src/main/java/org/zaproxy/zap/extension/importLogFiles/ImportLogAPI.java
- addOns/portscan/src/main/java/org/zaproxy/zap/extension/portscan/PortScan.java
- addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
- CookieUtils > Address theoretical NPE on cookie name.
- ReportGenerator > Use try-with-resource.
- diff_match_patch > `equals(Object)` add null and type check, add override notation.
- EncodeDecodeDialog > Rename `initialize()` to `init()` to avoid name collision with parent.
- HttpsInfoOutputPanel > Address theoretical NPE in getTarget.
- ImagelocationScanRule > Assign to value from the toLowerCase operation.
- ImportLogAPI > Use try-with-resource.
- PortScan > Use try-with-resource.
- RetireScanRule > Address theoretical NPE on repo.
I didn't update CHANGELOGs as these changes don't seem end-user relevant.
> Fix various issues identified via sonarcloud

- addOns/scripts/CHANGELOG.md
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/OutputPanel.java
> Scripts: GUI locking fix and new release

- addOns/websocket/CHANGELOG.md
> Prepare Websockets v23

- addOns/scripts/CHANGELOG.md
- addOns/scripts/scripts.gradle.kts
- addOns/websocket/CHANGELOG.md
- addOns/websocket/websocket.gradle.kts
> Prep Scripts and WebSocket add-ons for next release

- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleFileActiveScanRule.java
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleSimpleActiveScanRule.java
- addOns/graaljs/CHANGELOG.md
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/httpsender/AddZapHeader GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/httpsender/HttpSender default template GraalJS.js
- addOns/graaljs/src/main/zapHomeFiles/scripts/templates/variant/Input Vector default template GraalJS.js
- addOns/groovy/CHANGELOG.md
- addOns/groovy/src/main/zapHomeFiles/scripts/templates/extender/ExtenderDefaultTemplate.groovy
- addOns/groovy/src/main/zapHomeFiles/scripts/templates/httpsender/HttpSenderDefaultTemplate.groovy
- addOns/jruby/CHANGELOG.md
- addOns/jruby/src/main/zapHomeFiles/scripts/templates/httpsender/HttpSender default template.rb
- addOns/jython/CHANGELOG.md
- addOns/jython/src/main/zapHomeFiles/scripts/templates/httpsender/HttpSender default template.py
- addOns/pscanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleFilePassiveScanRule.java
- addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleSimplePassiveScanRule.java
- addOns/replacer/CHANGELOG.md
- addOns/replacer/src/main/resources/org/zaproxy/zap/extension/replacer/resources/Messages.properties
- addOns/scripts/CHANGELOG.md
- addOns/scripts/src/main/zapHomeFiles/scripts/templates/extender/Add panels.js
- addOns/scripts/src/main/zapHomeFiles/scripts/templates/extender/Add toolbar button.js
- addOns/selenium/CHANGELOG.md
- addOns/selenium/src/main/zapHomeFiles/scripts/templates/selenium/Selenium default template.js
- addOns/wavsepRpt/src/main/java/org/zaproxy/zap/extension/wavsepRpt/ExtensionWavsepReport.java
Use main branch instead of develop/master.
> Update references to zaproxy repo

- addOns/soap/CHANGELOG.md
> soap: Prepare release

- addOns/soap/CHANGELOG.md
- addOns/soap/soap.gradle.kts
> soap: Prepare next dev iteration

- addOns/alertReport/CHANGELOG.md
- addOns/alertReport/alertReport.gradle.kts
- addOns/alertReport/src/main/java/org/zaproxy/zap/extension/alertReport/AlertReportExportODT.java
- addOns/alertReport/src/main/java/org/zaproxy/zap/extension/alertReport/AlertReportExportPDF.java
- addOns/alertReport/src/main/java/org/zaproxy/zap/extension/alertReport/ExtensionAlertReportExport.java
> alertReport: Use 2.10 Core

- addOns/allinonenotes/CHANGELOG.md
- addOns/allinonenotes/allinonenotes.gradle.kts
- addOns/allinonenotes/src/main/java/org/zaproxy/zap/extension/allinonenotes/EventConsumerImpl.java
> allInOneNotes: Use 2.10 Core

- addOns/alertFilters/CHANGELOG.md
- addOns/alertFilters/alertFilters.gradle.kts
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFilter.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFilterAPI.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/DialogAddAlertFilter.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java
- addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/GlobalAlertFilterParam.java
> AlertFilters: Use Log4j 2.x

- addOns/accessControl/CHANGELOG.md
- addOns/accessControl/accessControl.gradle.kts
- addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/AccessControlAPI.java
- addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/AccessControlAlertsProcessor.java
- addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/AccessControlScannerThread.java
- addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/ContextAccessRulesManager.java
- addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/ExtensionAccessControl.java
- addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/view/AccessControlResultsTableModel.java
- addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/view/AccessControlStatusPanel.java
- addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/view/ContextAccessControlPanel.java
- addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/widgets/ContextSiteTree.java
- addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/widgets/SiteTree.java
> accessControl: Use Log4j 2.x

- addOns/ascanrulesAlpha/CHANGELOG.md
- addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleFileActiveScanRule.java
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleSimpleActiveScanRule.java
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ForbiddenBypassScanRule.java
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRule.java
- addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjectionScanRule.java
> ascanrulesAlpha: Use Log4j 2.x

- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrules/pscanrules.gradle.kts
> pscanrules: prepare for next dev iteration

- addOns/encoder/CHANGELOG.md
> encoder: Release v0.5.0

- addOns/callgraph/CHANGELOG.md
- addOns/callgraph/callgraph.gradle.kts
- addOns/callgraph/src/main/java/org/zaproxy/zap/extension/callgraph/CallGraphFrame.java
- addOns/callgraph/src/main/java/org/zaproxy/zap/extension/callgraph/PopupMenuCallGraph.java
> callgraph: Use Log4j 2.x

- addOns/browserView/CHANGELOG.md
- addOns/browserView/browserView.gradle.kts
- addOns/browserView/src/main/java/org/zaproxy/zap/extension/browserView/BrowserPanel.java
- addOns/browserView/src/main/java/org/zaproxy/zap/extension/browserView/BrowserViewParam.java
- addOns/browserView/src/main/java/org/zaproxy/zap/extension/browserView/ExtensionHttpPanelBrowserView.java
> browserview: Use Log4j 2.x

- addOns/bugtracker/CHANGELOG.md
- addOns/bugtracker/bugtracker.gradle.kts
- addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerBugzilla.java
- addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerBugzillaParam.java
- addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerGithub.java
- addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerGithubParam.java
- addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/ExtensionBugTracker.java
- addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/PopupMenuItemAlert.java
> bugtracker: Use Log4j 2.x

- addOns/codedx/CHANGELOG.md
- addOns/codedx/codedx.gradle.kts
- addOns/codedx/src/main/java/org/zaproxy/zap/extension/codedx/CodeDxAPI.java
- addOns/codedx/src/main/java/org/zaproxy/zap/extension/codedx/CodeDxExtension.java
- addOns/codedx/src/main/java/org/zaproxy/zap/extension/codedx/CodeDxProperties.java
- addOns/codedx/src/main/java/org/zaproxy/zap/extension/codedx/ExtensionAlertHttp.java
- addOns/codedx/src/main/java/org/zaproxy/zap/extension/codedx/UploadActionListener.java
- addOns/codedx/src/main/java/org/zaproxy/zap/extension/codedx/UploadPropertiesDialog.java
- CodeDxAPI > Clean code activity, remove wildcard import and use specific imports.
> codedx: Use Log4j 2.x

- addOns/commonlib/commonlib.gradle.kts
- addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/AbstractAppFilePlugin.java
- addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/CookieUtils.java
- addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/binlist/BinList.java
> commonlib: Use Log4j 2.x

- addOns/invoke/CHANGELOG.md
- addOns/invoke/invoke.gradle.kts
- addOns/invoke/src/main/java/org/zaproxy/zap/extension/invoke/InvokeAppWorker.java
- addOns/invoke/src/main/java/org/zaproxy/zap/extension/invoke/InvokeParam.java
- addOns/invoke/src/main/java/org/zaproxy/zap/extension/invoke/PopupMenuItemInvoke.java
> invoker: Use Log4j 2.x

- addOns/diff/CHANGELOG.md
- addOns/diff/diff.gradle.kts
- addOns/diff/src/main/java/org/zaproxy/zap/extension/diff/DiffDialog.java
- addOns/diff/src/main/java/org/zaproxy/zap/extension/diff/PopupMenuDiff.java
> diff: Use Log4j 2.x

- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRule.java
- addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
- addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
- addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRuleUnitTest.java
Per: https://twitter.com/veggiespam/status/1359353014289649669 and related to zaproxy/zaproxy#6446
> pscanrules: Remove pragma details from CacheControlScanRule

- addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
- addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
- addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
- addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationJobUnitTest.java
Turns out that if there no value for a param in the yaml file then the value is null :(
> Automation: null param fix

- addOns/encoder/CHANGELOG.md
- addOns/encoder/encoder.gradle.kts
- addOns/encoder/src/main/java/org/zaproxy/addon/encoder/EncodeDecodeDialog.java
- addOns/encoder/src/main/java/org/zaproxy/addon/encoder/EncoderConfig.java
- addOns/encoder/src/main/java/org/zaproxy/addon/encoder/ExtensionEncoder.java
- addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/script/ScriptBasedEncodeDecodeProcessor.java
> encoder: Use Log4j 2.x

- addOns/domxss/domxss.gradle.kts
- addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
- Update build file, change code to use updated logging infrastructure. (CHANGELOG already contains 2.10 upgrade info and
"maintenance changes".)
> domxss: Use Log4j 2.x

- addOns/formhandler/CHANGELOG.md
- addOns/formhandler/formhandler.gradle.kts
- addOns/formhandler/src/main/java/org/zaproxy/zap/extension/formhandler/FormHandlerParam.java
> formhandler: Use Log4j 2.x

- addOns/gettingStarted/CHANGELOG.md
- addOns/gettingStarted/gettingStarted.gradle.kts
- addOns/gettingStarted/src/main/java/org/zaproxy/zap/extension/gettingStarted/ExtensionGettingStarted.java
> gettingStarted: Use Log4j 2.x

- addOns/graphql/CHANGELOG.md
- addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlGenerator.java
- addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlOptionsPanel.java
- addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParam.java
- addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/contents/options.html
- addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties
- addOns/graphql/src/test/java/org/zaproxy/addon/graphql/GraphQlGeneratorUnitTest.java
- addOns/graphql/src/test/resources/org/zaproxy/addon/graphql/deepNestedLeaf.graphql
- Add two new options
- Lenient Maximum Query Depth
- Additional Query Depth
- Fixes zaproxy/zaproxy#6316
> graphql: Fix Issue 6316

- addOns/wappalyzer/CHANGELOG.md
> wappalyzer: Prepare release v21.1.0

- addOns/retire/CHANGELOG.md
- addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
- addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireUtil.java
- Update CHANGELOG, and change code to use updated logging infrastructure.
> retire: Use Log4j 2.x

- addOns/openapi/CHANGELOG.md
- addOns/openapi/openapi.gradle.kts
- addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
- addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/HistoryPersister.java
- addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/OpenApiResults.java
- addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/ExtensionOpenApiAutomation.java
- addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJob.java
- addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/contents/automation.html
- addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/contents/openapi.html
- addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/index.xml
- addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/map.jhm
- addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/toc.xml
- addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/Messages.properties
- addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/openapi-max.yaml
- addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/openapi-min.yaml
Also adds basic statistics support as well.
> OpenAPI: Automation Framework Support

- addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
- addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
- addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
- addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/activeScan-max.yaml
- addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/activeScan-min.yaml
- addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java
- addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanJobUnitTest.java
- addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-config.yaml
- addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
- addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml
Part of https://github.com/zaproxy/zaproxy/issues/6461 - adds support for the active scanner and active scan rule support.
> Automation: Support active scan

- addOns/spiderAjax/CHANGELOG.md
- addOns/spiderAjax/spiderAjax.gradle.kts
- addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderAPI.java
- addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
- addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJob.java
- addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/ExtensionAjaxAutomation.java
- addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/Messages.properties
- addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/spiderAjax-max.yaml
- addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/spiderAjax-min.yaml
- addOns/spiderAjax/src/test/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJobUnitTest.java
> Ajax Spider - add automation framework support

- addOns/plugnhack/CHANGELOG.md
- addOns/plugnhack/plugnhack.gradle.kts
- addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/ClientsPanel.java
- addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/ExtensionPlugNHack.java
- addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/MonitoredPagesManager.java
- addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/PlugNHackAPI.java
- addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/PopupMenuConfigureClient.java
- addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/brk/PopupMenuAddBreakClient.java
- addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/db/MessageTable.java
> plugnhack: Use Log4j 2.x

- addOns/portscan/CHANGELOG.md
- addOns/portscan/portscan.gradle.kts
- addOns/portscan/src/main/java/org/zaproxy/zap/extension/portscan/ExtensionPortScan.java
- addOns/portscan/src/main/java/org/zaproxy/zap/extension/portscan/PopupMenuPortCopy.java
- addOns/portscan/src/main/java/org/zaproxy/zap/extension/portscan/PortScan.java
> portscan: Use Log4j 2.x

- addOns/requester/CHANGELOG.md
- addOns/requester/requester.gradle.kts
- addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/HttpPanelSender.java
- addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ManualHttpRequestEditorPanel.java
- addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ManualRequestEditorPanel.java
> requester: Use Log4j 2.x

- addOns/saverawmessage/CHANGELOG.md
- addOns/saverawmessage/saverawmessage.gradle.kts
- addOns/saverawmessage/src/main/java/org/zaproxy/zap/extension/saverawmessage/PopupMenuSaveRawMessage.java
> saverawmessage: Use Log4j 2.x

- addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/contents/automation.html
- addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/contents/concepts.html
- addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/index.xml
- addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/map.jhm
- addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/toc.xml
sure I did this before, but couldnt find it :/
> Ajax Spider - add automation help

- addOns/automation/CHANGELOG.md
- addOns/openapi/CHANGELOG.md
- addOns/reports/CHANGELOG.md
- addOns/spiderAjax/CHANGELOG.md
> Prepare automation related add-ons for release

- addOns/automation/CHANGELOG.md
- addOns/automation/automation.gradle.kts
- addOns/openapi/CHANGELOG.md
- addOns/openapi/openapi.gradle.kts
- addOns/reports/CHANGELOG.md
- addOns/reports/reports.gradle.kts
- addOns/spiderAjax/CHANGELOG.md
- addOns/spiderAjax/spiderAjax.gradle.kts
> Automation - prep add-ons for next release

- addOns/fuzz/CHANGELOG.md
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/FuzzersController.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/FuzzersStatusPanel.java
Update all results panels when the look and feel changes.
Fix zaproxy/zaproxy#6479.
> fuzz: update results panels on L&F changes

- addOns/custompayloads/CHANGELOG.md
- addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomMultiplePayloadDialog.java
- addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadColumns.java
- addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadMultipleOptionsTableModel.java
- addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsMultipleOptionsTablePanel.java
- addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/contents/custompayloads.html
- addOns/custompayloads/src/main/resources/org/zaproxy/zap/extension/custompayloads/resources/Messages.properties
- Added dialog to add multiple payloads from a file.
Issue link:- https://github.com/zaproxy/zaproxy/issues/5708
Signed-off-by: nikolai6303 <iit2018152@iiita.ac.in>
> custompayload: Allow for bulk import of payloads from a file

- CONTRIBUTING.md
As discussed in other PRs and IRC.
> Refer to zaproxy Contribution Guidance in CONTRIBUTING.md

- addOns/reports/CHANGELOG.md
- addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java
- addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportMessageResolver.java
- addOns/reports/src/main/java/org/zaproxy/addon/reports/Template.java
- addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/create.html
- addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/Messages.properties
- addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/report.html
Have tested manually with locale specific language files.
> Reports: support template specific i18n files

- addOns/automation/CHANGELOG.md
- addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
- addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-spider.html
- addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
- addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/spider-max.yaml
- addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationJobUnitTest.java
- addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/SpiderJobUnitTest.java
- addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
> automation: Add support for enum parameters.

- addOns/soap/CHANGELOG.md
- addOns/soap/soap.gradle.kts
- addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/ExtensionImportWSDL.java
- addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SoapAPI.java
- addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/WSDLCustomParser.java
- addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/automation/ExtensionSoapAutomation.java
- addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/automation/SoapJob.java
- addOns/soap/src/main/javahelp/org/zaproxy/zap/extension/soap/resources/help/contents/automation.html
- addOns/soap/src/main/javahelp/org/zaproxy/zap/extension/soap/resources/help/contents/soap.html
- addOns/soap/src/main/javahelp/org/zaproxy/zap/extension/soap/resources/help/index.xml
- addOns/soap/src/main/javahelp/org/zaproxy/zap/extension/soap/resources/help/map.jhm
- addOns/soap/src/main/javahelp/org/zaproxy/zap/extension/soap/resources/help/toc.xml
- addOns/soap/src/main/resources/org/zaproxy/zap/extension/soap/resources/Messages.properties
- addOns/soap/src/main/resources/org/zaproxy/zap/extension/soap/resources/soap-max.yaml
- addOns/soap/src/main/resources/org/zaproxy/zap/extension/soap/resources/soap-min.yaml
- addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/automation/SoapJobUnitTest.java
- Add support for the Automation Framework.
- Add support for statistics for the number of added URLs (or SOAP Actions).
> soap: Support Automation Framework

- addOns/zest/CHANGELOG.md
- addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ExtensionZest.java
> Clear Zest Results Table whenever new Zest script is added

- addOns/reports/CHANGELOG.md
- addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java
- addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportDialog.java
- addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportParam.java
- addOns/reports/src/main/resources/org/zaproxy/addon/reports/resources/Messages.properties
> Reports: Reload templates on dir change and handle no reports

- addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportData.java
- addOns/reports/src/main/resources/org/zaproxy/addon/reports/resources/Messages.properties
- addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/report.html
- addOns/reports/src/main/zapHomeFiles/reports/traditional-html/report.html
Missing translation, changed colour to green and the FPs were not shown in the summary.
> Reports: Fix FP issues

- addOns/reports/CHANGELOG.md
To be released after #2769 had been merged.
> Reporting: Release 0.1.0

- addOns/reports/CHANGELOG.md
- addOns/reports/reports.gradle.kts
> Reports: prepare for the next release

- addOns/quickstart/CHANGELOG.md
- addOns/quickstart/quickstart.gradle.kts
- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/AttackThread.java
- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartParam.java
- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/hud/ExtensionQuickStartHud.java
- addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/launch/ExtensionQuickStartLaunch.java
> quickstart: Use Log4j 2.x

- addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java
Simple but efective (hopefully).
Can build on these of course...
> Reports: unit test for generating all reports

- addOns/retire/CHANGELOG.md
> retire: Prepare release v0.7.0

- addOns/automation/CHANGELOG.md
> automation: Prepare release v0.1.0

- addOns/automation/CHANGELOG.md
- addOns/automation/automation.gradle.kts
> automation: Prepare next dev iteration

- addOns/graphql/CHANGELOG.md
- addOns/graphql/graphql.gradle.kts
- addOns/graphql/src/main/java/org/zaproxy/addon/graphql/automation/ExtensionGraphQlAutomation.java
- addOns/graphql/src/main/java/org/zaproxy/addon/graphql/automation/GraphQlJob.java
- addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/contents/automation.html
- addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/contents/graphql.html
- addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/contents/options.html
- addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/contents/script.html
- addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/index.xml
- addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/map.jhm
- addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/toc.xml
- addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties
- addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/graphql-max.yaml
- addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/graphql-min.yaml
- addOns/graphql/src/test/java/org/zaproxy/addon/graphql/automation/GraphQlJobUnitTest.java
> graphql: Support Automation Framework

- addOns/pscanrulesAlpha/CHANGELOG.md
- addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
- addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScanRule.java
- addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleFilePassiveScanRule.java
- addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleSimplePassiveScanRule.java
- addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/FeaturePolicyScanRule.java
- addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/InPageBannerInfoLeakScanRule.java
- addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsFunctionScanRule.java
- addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanRule.java
Changed the code to use the updated logging infrastructure, and updated the CHANGELOG
> pscanrulesAlpha: Use Log4j 2.x

- addOns/pscanrulesBeta/CHANGELOG.md
- addOns/pscanrulesBeta/pscanrulesBeta.gradle.kts
- addOns/wappalyzer/CHANGELOG.md
- addOns/wappalyzer/wappalyzer.gradle.kts
Update to latest version, 1.6.
> Update RE2/J library

- addOns/graphql/CHANGELOG.md
- addOns/graphql/graphql.gradle.kts
- addOns/soap/CHANGELOG.md
- addOns/soap/soap.gradle.kts
Update versions and changelogs.
Add help URL to SOAP add-on.
> graphql, soap: prepare next dev iterations

- addOns/soap/CHANGELOG.md
- addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/ExtensionImportWSDL.java
- addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanRule.java
- addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPXMLInjectionActiveScanRule.java
- addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SitesTreeHelper.java
- addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/TableWsdl.java
- addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/WSDLCustomParser.java
- addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/WSDLSpider.java
- addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/WSDLCustomParserTestCase.java
> soap: use Log4j 2 APIs

- addOns/scripts/CHANGELOG.md
- addOns/scripts/scripts.gradle.kts
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ConsolePanel.java
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/InvokeScriptWithHttpMessageMenu.java
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/OutputPanel.java
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/PopupEnableDisableScript.java
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/PopupUseScriptAsAuthenticationScript.java
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ScriptTreeTransferHandler.java
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ScriptsListPanel.java
- addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/autocomplete/ScriptAutoCompleteKeyListener.java
> scripts: update ZAP to 2.10.0

- addOns/fuzz/CHANGELOG.md
- addOns/fuzz/fuzz.gradle.kts
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/AbstractFuzzer.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/HttpFuzzer.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/HttpFuzzerTask.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/HttpFuzzerTaskProcessorUtils.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/HttpFuzzerProcessorScriptProxy.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/ui/HttpFuzzResultsContentPanel.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/ui/HttpFuzzerResultsTable.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/ui/HttpFuzzerResultsTableModel.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/ui/HttpMessageSelectorPanel.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/impl/PayloadPreviewPanel.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/messagelocations/MultipleMessageLocationsBreadthFirstReplacer.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/messagelocations/MultipleMessageLocationsDepthFirstReplacer.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/generator/FileStringPayloadGenerator.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/generator/NumberPayloadGenerator.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/generator/ProcessPayloadGenerator.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/generator/RegexPayloadGenerator.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/generator/ScriptStringPayloadGeneratorAdapter.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/processor/Base64DecodeProcessor.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/processor/Base64EncodeProcessor.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/AbstractPersistentPayloadGeneratorUIPanel.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/JsonPayloadGeneratorAdapterUIHandler.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/ModifyPayloadsPanel.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/NumberPayloadGeneratorAdapterUIHandler.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/ScriptStringPayloadGeneratorAdapterUIHandler.java
- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/ui/processors/ScriptStringPayloadProcessorAdapterUIHandler.java
> fuzz: update ZAP to 2.10.0

- addOns/todo/src/main/java/org/zaproxy/zap/extension/todo/TodoList.java
- addOns/todo/todo.gradle.kts
> todo: update ZAP to 2.10.0

- addOns/sse/CHANGELOG.md
- addOns/sse/src/main/java/org/zaproxy/zap/extension/sse/EventStreamListener.java
- addOns/sse/src/main/java/org/zaproxy/zap/extension/sse/EventStreamProxy.java
- addOns/sse/src/main/java/org/zaproxy/zap/extension/sse/ExtensionServerSentEvents.java
- addOns/sse/src/main/java/org/zaproxy/zap/extension/sse/db/EventStreamStorage.java
- addOns/sse/src/main/java/org/zaproxy/zap/extension/sse/db/TableEventStream.java
- addOns/sse/src/main/java/org/zaproxy/zap/extension/sse/ui/EventStreamPanel.java
- addOns/sse/src/main/java/org/zaproxy/zap/extension/sse/ui/EventStreamView.java
- addOns/sse/src/main/java/org/zaproxy/zap/extension/sse/ui/EventStreamViewModel.java
- addOns/sse/sse.gradle.kts
> sse: update ZAP to 2.10.0

- addOns/viewstate/CHANGELOG.md
- addOns/viewstate/src/main/java/org/zaproxy/zap/extension/viewstate/ExtensionHttpPanelViewStateView.java
- addOns/viewstate/src/main/java/org/zaproxy/zap/extension/viewstate/HttpPanelViewStateView.java
- addOns/viewstate/src/main/java/org/zaproxy/zap/extension/viewstate/ViewStateModel.java
- addOns/viewstate/src/main/java/org/zaproxy/zap/extension/viewstate/zap/utils/ASPViewState.java
- addOns/viewstate/src/main/java/org/zaproxy/zap/extension/viewstate/zap/utils/JSFViewState.java
- addOns/viewstate/src/main/java/org/zaproxy/zap/extension/viewstate/zap/utils/ViewState.java
- addOns/viewstate/viewstate.gradle.kts
Update ZAP to 2.10.0 and address deprecation.
Remove unused loggers.
> viewstate: update ZAP to 2.10.0

- addOns/bruteforce/CHANGELOG.md
- addOns/bruteforce/bruteforce.gradle.kts
- addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/EasySSLProtocolSocketFactory.java
- addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/GenBaseCase.java
- addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/HTMLparse.java
- addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/Manager.java
- addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/ProcessChecker.java
- addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/ReportWriter.java
- addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/Worker.java
- addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/BruteForceURLFuzz.java
- addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/BruteForceWorkGenerator.java
- addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/WorkerGenerator.java
- addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/WorkerGeneratorURLFuzz.java
- addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/BruteForce.java
- addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/BruteForcePanel.java
- addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/DirBusterManager.java
- addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/ExtensionBruteForce.java
> bruteforce: use Log4j 2 APIs

- addOns/saml/CHANGELOG.md
- addOns/saml/saml.gradle.kts
- addOns/saml/src/main/java/org/zaproxy/zap/extension/saml/SAMLConfiguration.java
- addOns/saml/src/main/java/org/zaproxy/zap/extension/saml/SAMLExtension.java
- addOns/saml/src/main/java/org/zaproxy/zap/extension/saml/SAMLMessage.java
- addOns/saml/src/main/java/org/zaproxy/zap/extension/saml/SAMLProxyListener.java
- addOns/saml/src/main/java/org/zaproxy/zap/extension/saml/SAMLResendMenuItem.java
- addOns/saml/src/main/java/org/zaproxy/zap/extension/saml/SAMLResender.java
- addOns/saml/src/main/java/org/zaproxy/zap/extension/saml/SAMLUtils.java
- addOns/saml/src/main/java/org/zaproxy/zap/extension/saml/ui/SamlExtentionSettingsUI.java
> saml: update ZAP to 2.10.0

- addOns/sqliplugin/CHANGELOG.md
- addOns/sqliplugin/sqliplugin.gradle.kts
- addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLInjectionScanRule.java
- addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLiPayloadManager.java
- addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLiUnionEngine.java
> sqliplugin: update ZAP to 2.10.0

- addOns/reports/CHANGELOG.md
- addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportData.java
- addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportDialog.java
- addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportParam.java
- addOns/reports/src/main/java/org/zaproxy/addon/reports/Template.java
- addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/ReportJob.java
- addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/automation.html
- addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/create.html
- addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/reports.html
- addOns/reports/src/main/resources/org/zaproxy/addon/reports/resources/Messages.properties
- addOns/reports/src/main/resources/org/zaproxy/addon/reports/resources/report-max.yaml
- addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/report.html
- addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/template.yaml
- addOns/reports/src/main/zapHomeFiles/reports/traditional-html/Messages.properties
- addOns/reports/src/main/zapHomeFiles/reports/traditional-html/report.html
- addOns/reports/src/main/zapHomeFiles/reports/traditional-html/template.yaml
- addOns/reports/src/main/zapHomeFiles/reports/traditional-md/Messages.properties
- addOns/reports/src/main/zapHomeFiles/reports/traditional-md/report.md
- addOns/reports/src/main/zapHomeFiles/reports/traditional-md/template.yaml
- addOns/reports/src/main/zapHomeFiles/reports/traditional-pdf/Messages.properties
- addOns/reports/src/main/zapHomeFiles/reports/traditional-pdf/report.html
- addOns/reports/src/main/zapHomeFiles/reports/traditional-pdf/template.yaml
- addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java
Part of https://github.com/zaproxy/zaproxy/issues/6483
> Reporting: support report sections

- addOns/automation/CHANGELOG.md
- addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
- addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationProgress.java
- addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
- addOns/automation/src/main/java/org/zaproxy/addon/automation/JobResultData.java
- addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
- addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJobResultData.java
- addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PassiveScanJobResultData.java
- addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PassiveScanWaitJob.java
- addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanJobResultsUnitTest.java
- addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanJobUnitTest.java
- addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/PassiveScanJobResultsUnitTest.java
- addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/PassiveScanWaitJobUnitTest.java
The job data isnt actually used in this add-on its used in reporting, but we'll need to release this add-on before I can raise the reporting PR :)
> Automation: Add support for job result data

- addOns/reports/CHANGELOG.md
- addOns/reports/reports.gradle.kts
- addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/about.html
- addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/automation.html
- addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/create.html
- addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/reports.html
- addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/index.xml
- addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/toc.xml
- addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/report.html
- addOns/reports/src/main/zapHomeFiles/reports/traditional-html/report.html
- addOns/reports/src/main/zapHomeFiles/reports/traditional-pdf/report.html
- addOns/reports/src/main/zapHomeFiles/reports/traditional-xml/report.xml
Plan to actually apply this and then include the HTML + XML changes once #2780 and #2781 have been merged :)
Thanks to @thc202 for most of the work here ;)
> Reports: spotless html and xml

- addOns/webdrivers/webdriverlinux/CHANGELOG.md
- addOns/webdrivers/webdriverlinux/webdriverlinux.gradle.kts
- addOns/webdrivers/webdrivermacos/CHANGELOG.md
- addOns/webdrivers/webdrivermacos/webdrivermacos.gradle.kts
- addOns/webdrivers/webdriverwindows/CHANGELOG.md
- addOns/webdrivers/webdriverwindows/webdriverwindows.gradle.kts
> webdrivers: update ZAP to 2.10.0

- addOns/amf/CHANGELOG.md
- addOns/amf/amf.gradle.kts
- addOns/amf/src/main/java/org/zaproxy/zap/extension/amf/AbstractAMFTextView.java
Update ZAP to 2.10.0 and address deprecations.
> amf: update ZAP to 2.10.0

- addOns/custompayloads/CHANGELOG.md
- addOns/custompayloads/custompayloads.gradle.kts
- addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsMultipleOptionsTablePanel.java
> custompayloads: update ZAP to 2.10.0

- addOns/revisit/CHANGELOG.md
- addOns/revisit/revisit.gradle.kts
- addOns/revisit/src/main/java/org/zaproxy/zap/extension/revisit/ExtensionRevisit.java
- addOns/revisit/src/main/java/org/zaproxy/zap/extension/revisit/RevisitAPI.java
- addOns/revisit/src/main/java/org/zaproxy/zap/extension/revisit/RevisitDialog.java
Update ZAP to 2.10.0 and address deprecations.
> revisit: update ZAP to 2.10.0

- addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/JsonPayloadGeneratorAdapterUIHandler.java
JsonPayloadGeneratorAdapterUIHandler > Remove unused LOGGER and fix wildcard import.
> Fuzz Addon - Tweaks

- addOns/simpleexample/src/main/java/org/zaproxy/addon/simpleexample/ExtensionSimpleExample.java
- addOns/simpleexample/src/main/java/org/zaproxy/addon/simpleexample/SimpleExampleAPI.java
SimpleExampleAPI & ExtensionSimpleExample > Remove unused variable.
I didn't update CHANGELOG as this seems to never have been "released".
> SimpleExample Addon - Tweak

- addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerGithub.java
- addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/ExtensionBugTracker.java
- addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/PopupSemiAutoIssue.java
BugTrackerGithub > Removed unused local variable in `createDialogs()` method.
ExtensionBugTracker > Remove unused constants and update per `PopupSemiAutoIssue` changes below.
PopupSemiAutoIssue > Removed unused variable.
> BugTracker Addon - Tweaks

- addOns/sequence/CHANGELOG.md
- addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/SequencePanel.java
SequencePanel > Address TODOs and link to previously added help info (https://github.com/zaproxy/zap-extensions/pull/885).
CHANGELOG > Add note to unreleased section.
> Sequence Addon - Enable Help

- addOns/viewstate/src/main/java/org/zaproxy/zap/extension/viewstate/ExtensionHttpPanelViewStateView.java
ExtensionHttpPanelViewStateView > Remove unnecessary dependency declaration.
> Viewstate Addon - Tweaks

- addOns/pscanrules/CHANGELOG.md
- addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XFrameOptionScanRule.java
Replaced the CWE ID 16 with 1021, and updated the comment.
Fixes https://github.com/zaproxy/zaproxy/issues/6532
Signed-off-by: Elie Saad <eliesaad7@gmail.com>
> Set a better defining CWE ID to XFO

- addOns/exim/CHANGELOG.md
- addOns/exim/exim.gradle.kts
- addOns/exim/src/main/java/org/zaproxy/addon/exim/ExtensionExim.java
- addOns/exim/src/main/java/org/zaproxy/addon/exim/PopupMenuSaveRawMessage.java
- addOns/exim/src/main/java/org/zaproxy/addon/exim/PopupMenuSaveXmlMessage.java
- addOns/exim/src/main/javahelp/help/contents/exim.html
- addOns/exim/src/main/javahelp/help/helpset.hs
- addOns/exim/src/main/javahelp/help/index.xml
- addOns/exim/src/main/javahelp/help/map.jhm
- addOns/exim/src/main/javahelp/help/toc.xml
- addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/Messages.properties
- settings.gradle.kts
Initial add-on with migration of saveraw and savexml.
There is a fair amount of overlap between those two classes, I'll look at making an Abstract or something to reduce the duplication. (Next PR.)
Also note if anyone in the core goes ahead with testing this you should remove saverawmessage or savexmlmessage first, as nothing has been done to address the duplicate menu topic.
> exim: Initial Addition

- addOns/automation/CHANGELOG.md
- addOns/reports/CHANGELOG.md
> Automation, reporting - release 0.2.0

- addOns/automation/CHANGELOG.md
- addOns/automation/automation.gradle.kts
- addOns/reports/CHANGELOG.md
- addOns/reports/reports.gradle.kts
Update versions and changelogs.
> automation, reports: prepare next dev iteration

- addOns/httpsInfo/CHANGELOG.md
- addOns/httpsInfo/src/main/java/org/zaproxy/zap/extension/httpsinfo/ExtensionHttpsInfo.java
- addOns/httpsInfo/src/main/resources/org/zaproxy/zap/extension/httpsinfo/resources/Messages.properties
I tried to follow the steps provided by thc202 to solve DCO check and Travis CI check.
Fix zaproxy/zaproxy#6113
> Added usage message in httpsinfo extension

- addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/env.yaml
- addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-config.yaml
- addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
- addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml
> automation: Update config files with docs link

- addOns/ascanrules/CHANGELOG.md
- addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
- addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java
- addOns/ascanrules/src/test/resources/org/zaproxy/zap/extension/ascanrules/crosssitescriptingscanrule/InputInScript.html
- addOns/ascanrules/src/test/resources/org/zaproxy/zap/extension/ascanrules/crosssitescriptingscanrule/MultipleInput.html
Fixes zaproxy/zaproxy#5958
Signed-off-by: Aman Rawat <rawataman6525@gmail.com>
> Solved XSS false positive issue

- addOns/webdrivers/webdrivermacos/CHANGELOG.md
- addOns/webdrivers/webdrivermacos/webdrivermacos.gradle.kts
> webdrivermacos: prepare next dev iteration
