zaproxy/zap-extensions

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/FeaturePolicyScanner.java
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
addOns/pscanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/FeaturePolicyScannerUnitTest.java

Adds the feature policy scanner to `alphascanrules`
Unit tests included.
Fixes https://github.com/zaproxy/zaproxy/issues/4885

Adds Feature Policy scanner

---

addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java

Change `ExtensionSelenium` to enable the ServiceWorkers for Firefox to
allow to use the HUD more easily (in case it's disabled by default).

selenium: ensure ServiceWorkers enabled in Firefox

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureSVN.java
addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanner.java

In my view disclosing the source code is not as serious as things like XSS and SQLi. It may well be a serious problem for the company involved but it does not mean that the attacker will definitely be able to find other vulnerabilities, especially if the code is already open source.
Happy to discuss this further if anyone disagrees...

Downgrade source code disclosure to Medium

---

addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ui/OptionsWebSocketPanel.java
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ui/WebSocketMessagesView.java
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ui/WebSocketMessagesViewFilterDialog.java
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ui/WebSocketPanel.java
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ui/WebSocketUiHelper.java

The websockets tab does not scale correctly when a user defined font size is specified, this is particularly obvious when using a high DPI display.
To test configure ZAP to use a much larger font size - without this change the text and icons in the Websockets tab are not correctly scaled.

Websockets: scale fonts and icons correctly

---

addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java

Change ExtensionSelenium to add a preference to FirefoxOptions to keep
proxying localhost with newer Firefox versions.

selenium: proxy "localhost" in Firefox 67

---

addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2UnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/TestParameterTamperUnitTest.java

Set the required option when available in one test and tweak test URLs
in others to have the required parameters, to make the tests pass with
2.7.0 and 2.8.0.

ascanrules: correct preconditions in tests

---

addOns/gettingStarted/gettingStarted.gradle.kts

The guide is already targeting the newer version.

gettingStarted: set minimum ZAP version to 2.8.0

---

addOns/cmss/CHANGELOG.md
addOns/cmss/cmss.gradle.kts
addOns/sqliplugin/CHANGELOG.md
addOns/sqliplugin/sqliplugin.gradle.kts

Change sqliplugin and cmss to depend on JDOM to bundle the dependency
in the add-on instead of using the one from core, which will be removed.
Related to zaproxy/zaproxy#5374 - Remove usage of JDOM library

Bundle JDOM in sqliplugin and cmss

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/ascanrules.gradle.kts
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/diff/CHANGELOG.md
addOns/diff/diff.gradle.kts

Change ascanrules, ascanrulesBeta, and diff to depend on Diff Utils to
bundle the dependency in the add-on instead of using the one from core,
which will be removed.
Related to zaproxy/zaproxy#5380 - Set Diff Utils as a runtime only
dependency

Bundle Diff Utils in ascanrules/Beta and diff

---

testutils/src/main/java/org/zaproxy/zap/testutils/ActiveScannerTestUtils.java

Do not call base methods when being notified of a new message otherwise
it would count same message twice (base implementation calls one of the
other methods).

testutils: correct count of messages sent

---

addOns/jxbrowsers/jxbrowsers.gradle.kts
buildSrc/build.gradle.kts

Use HTTPS that is now available.
Remove hash checks, no longer needed.

jxbrowsers: use HTTPS repo

---

addOns/domxss/CHANGELOG.md
addOns/domxss/domxss.gradle.kts
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/TestDomXSS.java
addOns/domxss/src/main/javahelp/org/zaproxy/zap/extension/domxss/resources/help/contents/domxss.html
addOns/jxbrowsers/jxbrowser/CHANGELOG.md
addOns/jxbrowsers/jxbrowserlinux64/CHANGELOG.md
addOns/jxbrowsers/jxbrowsermacos/CHANGELOG.md
addOns/jxbrowsers/jxbrowsers.gradle.kts
addOns/jxbrowsers/jxbrowserwindows/CHANGELOG.md
addOns/jxbrowsers/jxbrowserwindows64/CHANGELOG.md
addOns/quickstart/CHANGELOG.md
addOns/quickstart/quickstart.gradle.kts
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ajaxspider/AjaxSpiderExplorer.java
addOns/selenium/CHANGELOG.md
addOns/selenium/selenium.gradle.kts
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/Browser.java
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
addOns/selenium/src/main/javahelp/org/zaproxy/zap/extension/selenium/resources/help/contents/intro.html
addOns/selenium/src/main/resources/org/zaproxy/zap/extension/selenium/resources/Messages.properties
addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/spiderAjax.gradle.kts
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParam.java
addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/contents/options.html
addOns/zest/CHANGELOG.md
addOns/zest/zest.gradle.kts

Change Selenium add-on to provide Chrome and Firefox headless, also, use semantic versioning.
Change AJAX Spider, DOM XSS, and Quick Start (AJAX Spider) to run with Firefox headless by default.
Change Zest and JxBrowser add-ons to depend on newer Selenium version.
Fix zaproxy/zaproxy#3866.

Allow to use Chrome/Firefox headless and use Firefox headless by default

---

addOns/webdrivers/webdriverlinux/CHANGELOG.md
addOns/webdrivers/webdriverlinux/src/main/javahelp/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
addOns/webdrivers/webdrivermacos/CHANGELOG.md
addOns/webdrivers/webdrivermacos/src/main/javahelp/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
addOns/webdrivers/webdrivers.gradle.kts
addOns/webdrivers/webdriverwindows/CHANGELOG.md
addOns/webdrivers/webdriverwindows/src/main/javahelp/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html

Update ChromeDriver to 75.0.3770.8.
Add release dates and link to tags.

webdrivers: update ChromeDriver, prepare releases

---

addOns/domxss/CHANGELOG.md
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/TestDomXSS.java
addOns/domxss/src/main/javahelp/org/zaproxy/zap/extension/domxss/resources/help/contents/about.html

Don't try to get a browser if there's no ID in the configuration rule
(it would lead to an exception), instead use the default.
Prepare add-on release.

domxss: correct default when no browser specified

---

addOns/importLogFiles/CHANGELOG.md
addOns/importLogFiles/importLogFiles.gradle.kts
addOns/importLogFiles/src/main/java/org/zaproxy/zap/extension/importLogFiles/ExtensionImportLogFiles.java
addOns/importLogFiles/src/main/resources/org/zaproxy/zap/extension/importLogFiles/resources/Messages.properties
addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/contents/openapi.html
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/Messages.properties
addOns/soap/CHANGELOG.md
addOns/soap/soap.gradle.kts
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/ExtensionImportWSDL.java
addOns/soap/src/main/javahelp/org/zaproxy/zap/extension/soap/resources/help/contents/soap.html
addOns/soap/src/main/resources/org/zaproxy/zap/extension/soap/resources/Messages.properties

Part of issue [zaproxy#3578](https://github.com/zaproxy/zaproxy/issues/3578). 
Updated the following alpha addons to use new Import Menu.

Updated import addons to use new Import menu

---

addOns/regextester/CHANGELOG.md
addOns/regextester/regextester.gradle.kts
addOns/regextester/src/main/java/org/zaproxy/zap/extension/regextester/ExtensionRegExTester.java
addOns/regextester/src/main/java/org/zaproxy/zap/extension/regextester/RegExTesterPopupMenuItem.java
addOns/regextester/src/main/java/org/zaproxy/zap/extension/regextester/RegexTest.java
addOns/regextester/src/main/java/org/zaproxy/zap/extension/regextester/RegexTestInput.java
addOns/regextester/src/main/java/org/zaproxy/zap/extension/regextester/RegexTestResult.java
addOns/regextester/src/main/java/org/zaproxy/zap/extension/regextester/RegexTester.java
addOns/regextester/src/main/java/org/zaproxy/zap/extension/regextester/ui/MatchPanel.java
addOns/regextester/src/main/java/org/zaproxy/zap/extension/regextester/ui/RegexDialog.java
addOns/regextester/src/main/java/org/zaproxy/zap/extension/regextester/ui/RegexPanel.java
addOns/regextester/src/main/java/org/zaproxy/zap/extension/regextester/ui/TestValuePanel.java
addOns/regextester/src/main/java/org/zaproxy/zap/extension/regextester/ui/model/RegexModel.java
addOns/regextester/src/main/java/org/zaproxy/zap/extension/regextester/ui/util/SimpleDocumentListener.java
addOns/regextester/src/main/resources/org/zaproxy/zap/extension/regextester/resources/Messages.properties
settings.gradle.kts

You can open this dialog via ToolMenu. Then the dialog is empty
Furthermore you can open this dialog via ContextMenu  and choose the part  of the request/response that should prefill the dialog
If this is merged I like to implement, that textboxes containing regular expressions can launch this dialog. It could be prefilled with the regex and an example of the possible value or the user can choose a "real value" from the NodeSelectDialog.

Implemented dialog for testing regular expressions

---

addOns/addOns.gradle.kts
addOns/spiderAjax/spiderAjax.gradle.kts

Configure the build to use 2.8.0 for API generation.
Fix AJAX Spider API generation (missing Selenium dependency).

Use newer ZAP version for API generation

---

addOns/bruteforce/CHANGELOG.md
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/HTMLparse.java

Check if base url ends with a slash and append one if necessary.
Fixes zaproxy/zaproxy#5435

Fix Issue 5435

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SessionFixation.java

- Fix NPE in "Session Fixation" scan rule when the path of the request URI is null.
- Update Changelog.
Fixes zaproxy/zaproxy#5444

Fix Issue 5444 - Sessions Fixation Scan Rule NPE

---

addOns/fuzzdb/CHANGELOG.md
addOns/fuzzdb/fuzzdb.gradle.kts

Update minimum ZAP version to 2.8.0.

fuzzdb: update ZAP and prepare release

---

addOns/regextester/CHANGELOG.md
addOns/regextester/src/main/java/org/zaproxy/zap/extension/regextester/ExtensionRegExTester.java

Make sure that nothing is left open after the add-on is uninstalled.

regextester: close dialog when unloading extension

---

addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/contents/pscanrules.html
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Private IP Disclosure.js

This script scans websocket messages for private IP V4 addresses as well as Amazon EC2 private hostnames Private IP V4 such as: 10.x.x.x, 172.x.x.x, 192.168.x.x Amazon EC2 private hostname: such as ip-10-0-56-78
__________________________________________________________
TODOs:

[WS-Passive-Scan] Add Private IP Disclosure

---

addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/contents/pscanrules.html
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/PII Disclosure.js

This script scans for the presence of Personally Information Identifiable in incoming WebSocket Messages. More specifically, it passively scan messages for credit card numbers
TODOs:

[WS-Passive-Scan] Credit Card Disclosure

---

testutils/src/main/java/org/zaproxy/zap/testutils/PassiveScannerTestUtils.java

Make it clear what the problem is when doing the default assertions for
alerts raised by passive rules.

testutils: add reason to default assertions

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/pscanrules.gradle.kts
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanner.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScannerUnitTest.java

* pscanrules.gradle.kts - Change dependency to salvation 2.7.0.
* CHANGELOG.md - Updated.
* ContentSecurityPolicyScanner.java - Updated to add handling for script-src-elem, script-src-attr, style-src-elem, and style-src-attr.
* ContentSecurityPolicyScannerUnitTest.java  - Updated.

Fix Issue 5459 - Salvation 2.7.0 Upgrade

---

addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/contents/pscanrules.html
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Username Idor Scanner.js

This script passively scans the incoming WebSocket messages for usernames.
Finds usernames which are hashed with one of the following encoding methods {MD2, MD5
SHA1, SHA256, SHA384, SHA512}. The usernames has to be defined in any context.
TODOs:

[WS-Passive-Scan] Add Username disclosure scan 

---

addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/contents/pscanrules.html
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Debug Error Disclosure.js

This script checks the incoming WebSocket message payload for known Debug Error message fragments. Access to such details may provide a malicious individual with means by which to further abuse the web site. They may also leak data not specifically meant for end user consumption.

[WS-Passive-Scan] Add Debug Error Disclosure

---

addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/contents/pscanrules.html
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/XML Comments Disclosure.js

This script seek at incoming WebSocket messages payloads, which are XML formatted, for suspicious comments. The comments it is searching for are relevant to components with which an attacker can extract useful information. Comments like FIXME, BUG, etc might be helpful for further attacks targeting the weaknesses of the web application.

[WS-Passive Scan] Add XML Suspicious comment disclosure

---

addOns/tokengen/src/main/java/org/zaproxy/zap/extension/tokengen/TokenGenerator.java

Change `TokenGenerator` to catch and log errors (`Throwable`) that
occurred during token generation, otherwise they would be silently
ignored.

tokengen: log errors during generation

---

addOns/addOns.gradle.kts

Add JaCoCo plugin to generate code coverage reports with all add-ons
`:addOns:jacocoReport` and each e.g. `:addOns:reveal:jacocoTestReport`.
Add task `:addOns:testReport` to generate a test report with the tests
from all add-ons.

Add JaCoCo plugin

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ServletParameterPollutionScanner.java
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/ServletParameterPollutionScannerUnitTest.java

- CHANGELOG.md - Added change entry.
- ServletParameterPollutionScanner.java - Add Threshold check and return if not LOW.
- ServletParameterPollutionScannerUnitTest.java - Add before() method setting Threshold LOW (as used by the majority of the UnitTest methods). Add unit tests for new behavior. Add Given, When, and Then comments.

Issue 4454 - ServletParameterPollutionScanner only at Low Threshold

---

addOns/browserView/CHANGELOG.md
addOns/browserView/src/main/java/org/zaproxy/zap/extension/browserView/ResponseBrowserView.java
addOns/invoke/CHANGELOG.md
addOns/invoke/src/main/java/org/zaproxy/zap/extension/invoke/InvokeAppWorker.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanner.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/WSDLCustomParser.java

Check that the request/response body is empty instead of null, they are
never null.
In one case remove the check completely and just check the body as
string (used later), also, log (debug) when empty.

Correct request/response body checks

---

addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CSRFCountermeasures.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InsecureAuthenticationScan.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleSimplePassiveScanner.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/LinkTargetScanner.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ServletParameterPollutionScanner.java

Remove unused method `getCategory()` in passive rules (only active rules
have categories).

Remove unused methods

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/OpenApiSpider.java

Change `OpenApiSpider` to not consume the resource if not actually
parsed, to still allow other spider parsers (e.g. text) to parse it.

openapi: do not consume resource if not parsed

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CommandInjectionPlugin.java

Current PS injection control pattern trips and causes FPs on anything that reflects the 'get-help' string that is being used as a test.
Therefore, the control pattern for the string "Get-Help" was changed to being case sensitive with capitalized letters (injection and command would work if entered in any case, and then the output would reflect Get-Help in capitalized form), while the rest of the regex was forced case-insensitive with the (?i) modifier in the regex.
This tests now matches " Get-Help" specifically (including leading space) and "cmdlet","get-alias" in any case, but not " get-help".

Improve PS control pattern to reduce FPs.

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsoScanner.java
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
addOns/pscanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsoScannerUnitTest.java

Detect potential JSO based on signature
- When cookie or header start with special base64 signature
- When body or header start with special base64 or raw signatures
Next steps:
- Add payload generator
- Add in active scan

Add alert for Java Serialized Object (JSO)

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/LearnMorePanel.java

Link to 2.8.0 instead of 2.7.0.

quickstart: link to newer getting started guide

---

addOns/jruby/CHANGELOG.md
addOns/jruby/src/main/java/org/zaproxy/zap/extension/jruby/ExtensionJruby.java

Check that the script engine exists before attempting to use it when
unloading the extension, it does not exist with newer Java versions as
it fails to load.

jruby: fix NPE while unloading

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/XXEPlugin.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/XXEPluginTest.java

Fixing ArrayIndexOutOfBoundsException in xxeplugin. There must be a LOCAL_FILE_PATTERNS entry for each LOCAL_FILE_TARGETS entry
Remove XXEPlugin now removes original xml header in Local File Reflection Attack. Added some tests for replacing values with payloads in xml

xxeplugin: Fixing ArrayIndexOutOfBoundsException and remove original xml header

---

addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ContentSecurityPolicyMissingScanner.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/ContentSecurityPolicyMissingScannerUnitTest.java

* Fix a typo with getAlertAttribute
* Replace `== false` with `!`
* Closes zaproxy/zaproxy#5496

Add unit tests for ContentSecurityPolicyMissingScanner

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScannerUnitTest.java

In order to further address performance, such as this item I encountered the other day:
`79049 [ZAP-PassiveScanner] WARN
org.zaproxy.zap.extension.pscan.PassiveScanThread  - Passive Scan rule
Wappalyzer Scanner (Tech Detection) took 7 seconds to scan
http://xxx/favicon.ico image/x-icon 15086`
* WappalyzerPassiveScanner > Changed to skip response body checks if the response isn't a text type.
* WappalyzerPassiveScannerUnitTest > Updated to actually set the content-type on test messages. Added test methods to assert the expected behavior.
* CHANGELOG > Added note to unreleased section.

Wappalyzer Performance Tweak

---

addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/HeartBleedScanner.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/HeartBleedScannerUnitTest.java

* Closes zaproxy/zaproxy#5494
* Fixes defect where regex wasn't matching 1.0.1-Beta{1,2,3}
* Fixes defect where scanner would only look at first OpenSSL Server header
* Removes unused parameter

Add unit tests for HeartBleedScanner

---

addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanner.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScannerUnitTest.java

Each regular expression in the language patterns is a small program
in itself.  I haven't tested each and every one as there are 180.
Instead I took 2 and tested their implementation.  For more confidence
I'd want to write at least one unit test per expression.
Additionally
* Removes unused parameter
* Closes zaproxy/zaproxy#5499

Add unit tests for SourceCodeDisclosureScanner

---

addOns/codedx/CHANGELOG.md
addOns/codedx/src/main/java/org/zaproxy/zap/extension/codedx/CodeDxAPI.java
addOns/codedx/src/main/java/org/zaproxy/zap/extension/codedx/UploadActionListener.java

Files.write in generateReportFile appears to sometimes cause exceptions from encoding conflicts. This uses the ReportLastScan.generate method that saves to a file internally instead. It also now parses the report file with an XMLEventReader to check if it's empty.

Generate and save CodeDx report with ReportLastScan.generate

---

addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ElmahScanner.java

Tweak comment in `getWascId()` method.
Not updating changelog: maintenance change irrelevant to end users.

ElmahScanner Typo Fix

---

addOns/customreport/CHANGELOG.md
addOns/customreport/src/main/java/org/zaproxy/zap/extension/customreport/OptionDialog.java
addOns/customreport/src/main/java/org/zaproxy/zap/extension/customreport/ScopePanel.java

Add the tabbed panel to the centre of the dialogue so that its tabs are
properly (re)sized.
Tweak the Scope tab to let the fields expand/shrink when the dialogue is
resized, also, give extra vertical space to the description field (the
biggest).
Fix zaproxy/zaproxy#5521 - Customizable HTML report is not working

customreport: fix dialogue layout

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ContentSecurityPolicyMissingScanner.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/FeaturePolicyScanner.java
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/ContentSecurityPolicyMissingScannerUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/FeaturePolicyScannerUnitTest.java

CSP Missing and Feature Policy: ignore missing headers on redirects

---

addOns/bruteforce/CHANGELOG.md
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/GenBaseCase.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/HTMLparse.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/Manager.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/ProcessChecker.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/Worker.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/BruteForceURLFuzz.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/BruteForceWorkGenerator.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/WorkerGenerator.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/WorkerGeneratorURLFuzz.java

Bruteforce extension was migrated from standard output to logging.
Standard outputs for debugging purposes that were already commented out were not removed as part of this pull request.
Fixes [#5530](https://github.com/zaproxy/zaproxy/issues/5530)

Forced browse: Use logger instead of standard output 

---

addOns/webdrivers/webdriverlinux/CHANGELOG.md
addOns/webdrivers/webdriverlinux/src/main/javahelp/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
addOns/webdrivers/webdrivermacos/CHANGELOG.md
addOns/webdrivers/webdrivermacos/src/main/javahelp/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
addOns/webdrivers/webdrivers.gradle.kts
addOns/webdrivers/webdriverwindows/CHANGELOG.md
addOns/webdrivers/webdriverwindows/src/main/javahelp/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html

Update ChromeDriver to 77.0.3865.40 and geckodriver to 0.25.0.
Add release dates and link to tags.

webdrivers: update WebDrivers, prepare releases

---

addOns/spiderAjax/spiderAjax.gradle.kts

Use non-development version "now" that it's released.

spiderAjax: compile with 2.8.0

---

addOns/replacer/CHANGELOG.md
addOns/replacer/replacer.gradle.kts
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ExtensionReplacer.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/HexString.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerParamRule.java
addOns/replacer/src/main/javahelp/org/zaproxy/zap/extension/replacer/resources/help/contents/replacer.html
addOns/replacer/src/test/java/org/zaproxy/zap/extension/replacer/ExtensionReplacerTest.java
addOns/replacer/src/test/java/org/zaproxy/zap/extension/replacer/ReplacerParamRuleTest.java

Resolve zaproxy/zaproxy#5328
When 
* the Match string is "abc\x01\x03\x02def"  and is a regex
* the content is "61 62 63 01 03 02 64 65 66" in hexa 
* the replacement string is "abc\x01\x02\x03def"
Then
*  the content is "61 62 63 01 02 03 64 65 66" in hexa

Ability to replace byte values using hexadecimal escapes with the Replacer tool

---

addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/ActiveScannerAppParamTest.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/ActiveScannerTest.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/XSLTInjectionUnitTest.java
testutils/src/main/java/org/zaproxy/zap/testutils/StaticContentServerHandler.java

* ascanrulesAlpha.gradle.kts > add testutils testImplementation to dependencies
* ActiveScannerAppParamTest, ActiveScannerTest > UnitTest infra pulled from release or beta (I forget which, I believe they're the same).
* XSLTInjectionUnitTest > The new unit tests.
* StaticContentServerHandler > Convenience class added.
This is not meant to be a complete set of unit tests, but more to set the ground work for future use.

ascanAlpha add initial XSLT scan rule unit test

---

addOns/bruteforce/CHANGELOG.md
addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/BruteForce.java

Add the message to the panel/table in the EDT to avoid deadlock between
DirBuster worker threads and the EDT, also, change it to a lambda.
Update changelog with this and previous change.

bruteforce: address deadlock

---

addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CrossDomainScriptInclusionScannerUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/LinkTargetScannerUnitTest.java
addOns/sse/src/test/java/org/zaproxy/zap/extension/sse/EventStreamListenerUnitTest.java
addOns/sse/src/test/java/org/zaproxy/zap/extension/sse/EventStreamProxyUnitTest.java
addOns/tokengen/src/test/java/org/zaproxy/zap/extension/tokengen/TokenRandomStreamUnitTest.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScannerUnitTest.java
addOns/websocket/src/test/java/org/zaproxy/zap/extension/websocket/pscan/WebSocketPassiveScannerManagerUnitTest.java
testutils/src/main/java/org/zaproxy/zap/testutils/TestUtils.java
testutils/testutils.gradle.kts

Change tests to:
- Address deprecations;
- Remove unnecessary stubbings or make the mock lenient if the stubs
are used in different/several tests;
- Extract mocks/stubs in some classes to avoid repeating the same in
several/every test.

testutils: update Mockito to 3.1.0

---

addOns/exportreport/CHANGELOG.md
addOns/exportreport/src/main/java/org/zaproxy/zap/extension/exportreport/ExportReportAPI.java
addOns/exportreport/src/main/java/org/zaproxy/zap/extension/exportreport/ExtensionExportReport.java
addOns/exportreport/src/main/java/org/zaproxy/zap/extension/exportreport/export/ExportReport.java
addOns/exportreport/src/main/java/org/zaproxy/zap/extension/exportreport/export/ReportExport.java
addOns/exportreport/src/main/javahelp/org/zaproxy/zap/extension/exportreport/resources/help/contents/exportreport.html
addOns/exportreport/src/main/resources/org/zaproxy/zap/extension/exportreport/resources/Messages.properties

Fixes [#2920](https://github.com/zaproxy/zaproxy/issues/2920)
Modifies `exportreport`'s `generate` API action to include two new optional parameters : `scanId` and `includePassiveAlerts`. Updates the command line interface to support those options.

Adds options to specify inclusion of scans/alerts in exportreport

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/TestUserAgent.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/payloader/ExtensionPayloader.java
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
addOns/custompayloads/CHANGELOG.md
addOns/custompayloads/custompayloads.gradle.kts
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/AbstractColumnDialog.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/AbstractColumnTableModel.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/AbstractMultipleOptionsColumnTableModel.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/AbstractTableModelAsAbstractColumnTableModelWrapper.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/Column.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayload.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadCategoryColumn.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadColumns.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadDialog.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadModel.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadMultipleOptionsTableModel.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsMultipleOptionsTablePanel.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsOptionsPanel.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsParam.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/EditableColumn.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/EditableSelectColumn.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/ExtensionCustomPayloads.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/PayloadCategory.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/PayloadIterator.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/PluginWithConfigurablePayload.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/ScanRulePayloadsProvider.java
addOns/custompayloads/src/main/resources/org/zaproxy/zap/extension/custompayloads/resources/Messages.properties
settings.gradle.kts

It provides the ability to add, edit or remove payloads that are used by active scanners. I added an example how to use the new extension in the alpha active scanner TestUserAgent.
The whole idea is that scanners provide default payloads via implementing the interface `PluginWithConfigurablePayload`. The payloads which are used during the scan are retrieved by the `ExtensionCustomPayloads` class from the method` getPayloadsByCategory(String category)`. The scanners ask the `ExtensionCustomPayloads` for payloads of a particular category.
This enables the user to add, modify or remove payloads as he like.
Once the PR #1072 "First implementation of scanner that uses callbacks for identifying XSS vulnerabilities" is merged I will change the new `XssByCallbackScanner.java ` to use …

Implemented a new Extension CustomPayloads. 

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/custompayloads/custompayloads.gradle.kts
addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/contents/custompayloads.html
addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/helpset.hs
addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/index.xml
addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/map.jhm
addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/toc.xml

ascanrulesAlpha > Updated help for User Agent Fuzzer scan rulesmentioning Custom Payloads.
Custompayloads > Added basic help.
Both > Updated custompayloads version and dependency to 0.9.0.
Follow-up to: https://github.com/zaproxy/zap-extensions/pull/1114

Add Help for Custom Payloads, Update ascanrulesAlpha Help, etc

---

addOns/selenium/CHANGELOG.md
addOns/selenium/selenium.gradle.kts

Update Selenium library to version 3.141.59.
Add dependency on `htmlunit-driver` and `phantomjsdriver`, no longer
included in the other library.

selenium: update Selenium library

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/javahelp/org/zaproxy/zap/extension/scripts/resources/help/contents/scripts.html

Mention in the help how to access/set custom variables.
Part of zaproxy/zaproxy#3402 - Share custom variables between scripts

scripts: mention custom variables

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestSequenceRunner.java

Use ZAP instead of Zest's client to send the messages from the sequence
scripts so that they make use of ZAP features (e.g. authentication, HTTP
Sender scripts).
Fix zaproxy/zaproxy#5590 - Sequence script does not invoke HTTP Sender
script

zest: send sequence messages with ZAP

---

addOns/beanshell/CHANGELOG.md
addOns/beanshell/src/main/java/org/zaproxy/zap/extension/beanshell/BeanShellConsoleFrame.java
addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/DefaultExplorePanel.java
addOns/tokengen/CHANGELOG.md
addOns/tokengen/src/main/java/org/zaproxy/zap/extension/tokengen/AnalyseTokensDialog.java
addOns/tokengen/src/main/java/org/zaproxy/zap/extension/tokengen/TokenPanel.java

Update various extensions to leverage WritableFileChooser for saving and exporting.
Related to: zaproxy/zaproxy#5667 and zaproxy/zaproxy#5516

Extensions Leverage WritableFileChooser

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/pscanrulesBeta.gradle.kts
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/UsernameIdorScanner.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/payloader/ExtensionPayloader.java
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/pscanrulesBeta/src/main/resources/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/UsernameIdorScannerUnitTest.java

- UsernameIdorScanner.java > Minor changes to accommodate Custom Payloads functionality.
- UsernameIdorScannerUnitTest.java > Added a test method to check for a default payload.
- ExtensionPayloader.java > Extension added as bridge between pscanrulesBeta and the Custom Payloads addon (as was done with ascanrulesAlpha).
- Messages.properties > Added keys/values necessary for ExtensionPayloader.
- pscanbeta.html > Updated help entry.
- pscanrulesBeta.gradle.kts > Added dependency details, etc.
- CHANGELOG.md > Added "change" entry.

pscanrulesBeta: Username IDOR Scanner Custom Payloads support

---

addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/HiddenFilesScanRule.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/HiddenFilesScanRuleUnitTest.java

Add unit tests for the Hidden File Finder. Includes minor changes to HiddenFilesScanRule to accommodate testing. I didn't update changelog because this isn't user impacting.
Related to zaproxy/zaproxy#4585

ascanrulesAlpha: HiddenFilesScanRule Unit Tests

---

addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/HexString.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/HiddenFilesScanRule.java
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/ascanrulesAlpha/src/main/zapHomeFiles/json/hidden_files.json
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/HiddenFilesScanRuleUnitTest.java

- hidden_files.json > Updated with CVS payload, and "not_content" element. Updated with various other payloads which leverage new "binary" element.
- HiddenFilesScanRule.java > Refactored to read and handle "not_content" and "binary" elements in HiddenFiles. Extracted convenience methods for doesMatch, doesNotMatch, and doesBinaryMatch.
- HiddenFilesScanFuleUnitTest.java > Added unit tests for new negative content checks, and binary checks, revised behavior when only a path matches (or path and partial content) [now Low confidence].
- ascanalpha.html > Remove todo notes, added JSON info and examples.
- HexString > Duplicated from Replacer addon, to facilitate binary matching.
Fixes zaproxy/zaproxy#4585

ascanrulesAlpha: HiddenFilesScanRule add other match handling

---

addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/UriBuilder.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/converter/swagger/UriBuilderUnitTest.java

Allow to parse and merge URI components from several URIs, to implement
overriding functionality (e.g. merge URL present in the definition with
the default URL or the one provided by the user).

openapi: add simple URI builder

---

addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ImportFromAbstractDialog.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ImportFromUrlDialog.java
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/Messages.properties

To avoid duplicating the dialogue for file import (#2152).
Add more URL validations:
- Don't try to import if the URL is empty;
- Check that the URL is HTTP/HTTPS.

openapi: extract base class for import dialogue

---

addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html

It occurred to me that perhaps I wasn't specific enough about this in the previous PR. Plus I noticed a mistake in the descriptive link syntax.

ascanrulesAlpha: Tweak Hidden File Finder help entry

---

addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ui/WebSocketMessagesView.java

The sorting does not work properly.
Part of zaproxy/zaproxy#1661.

websocket: disable table sorting

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ElmahScanner.java

Elmah scan rule updated to include a response content check, and vary alert confidence values accordingly.

ascanrulesAlpha: ELMAH scan rule add content check

---

addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/UriBuilder.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/converter/swagger/UriBuilderUnitTest.java

Make sure the relative path is added to the URI with the path separator.
Use char path separator where possible.

openapi: fix merge/build with relative path

---

addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/UriBuilder.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/converter/swagger/UriBuilderUnitTest.java

Add a method to set a default path (set only if not already set one) to
allow to override the path before merging other paths.
Test that attempting to merge with a null `UriBuilder` results in a NPE,
mention that in the JavaDoc.

openapi: allow to default to a path in URI builder

---

addOns/openapi/openapi.gradle.kts
addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/contents/openapi.html
addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/helpset.hs
addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/toc.xml
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/Messages.properties

Normalise OpenAPI name (`Open API`/`OpenApi` → `OpenAPI`).
Tweak menu tool tips to refer to definition instead of file.
Split API parameters' description from endpoint description.

openapi: text tweaks

---

addOns/tips/CHANGELOG.md
addOns/tips/src/main/javahelp/org/zaproxy/zap/extension/tips/resources/help/contents/tips.html
addOns/tips/src/main/resources/org/zaproxy/zap/extension/tips/resources/Messages.properties

The Filter functionality no longer exists.
Part of zaproxy/zaproxy#5244 - Remove Filter extension

tips: remove filter related tips

---

addOns/webdrivers/webdriverlinux/CHANGELOG.md
addOns/webdrivers/webdriverwindows/CHANGELOG.md
buildSrc/build.gradle.kts
buildSrc/src/main/java/org/zaproxy/gradle/tasks/DownloadWebDriver.java

Change `DownloadWebDriver` to use a custom `FirefoxDriverManager` to
ignore cached binaries of different architecture than the one being
requested, affects only geckodriver which has 32/64bits binaries for
Linux and Windows.
Update WebDriverManager to latest version.
Add release dates and links to tags.
Fix zaproxy/zaproxy#5763 - WebDriver add-ons might bundle binaries with
incorrect architecture

webdrivers: use correct arch, prepare release

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/Application.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/PopupMenuEvidence.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/PopupMenuEvidenceSearch.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechPanel.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechTableModel.java
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html
addOns/wappalyzer/src/main/resources/org/zaproxy/zap/extension/wappalyzer/resources/Messages.properties

- CHANGELOG.md > Added change info.
- PopupMenuEvidence*.java > Added handling for multi-select (disable menu if multiple rows selected.)
- Techpanel > Add export button. Added icon to "Name" column which is now actually `Application` not string and uses a new custom renderer.
- TechTableModel > Removed icon column, made the new first column "Name" be based on `Application`.
- Messages.properties > Removed now un-used icon key.
- wappalyzer.html > Updated to note the multi-select behavior of the context menu, and mention the export button.

wappalyzer: Add export button and handle multi-select

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerAPI.java
addOns/wappalyzer/src/main/resources/org/zaproxy/zap/extension/wappalyzer/resources/Messages.properties

- ExtensionWappalyzer > Hook the api. (Remove todo about API calls.)
- WappalyzerAPI > Brand new, with a few views.
- Messages.properties > Add API and param descriptions (param won't be applicable until targeting next zap version [likely 2.9]).
- CHANGELOG > Added details of the new API(s).
Fixes zaproxy/zaproxy#5761

wappalyzer: Add API

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieSameSiteScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieUtils.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScannerUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieSameSiteScannerUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScannerUnitTest.java

- CookieUtils > Added `isExpired(String)` method.
- CookieHttpOnlyScanner, CookieSecureFlagScanner, CookieSameSiteScanner > Changed to leverage new isExpired method and just return if the cookies are expired (deleted).
- CookieHttpOnlyScannerUnitTest, CookieSecureFlagScannerUnitTest, CookieSameSiteScannerUnitTest > Added unit tests for both space and hyphen delimited dates in support of the new behavior.
- CHANGELOG > Added change entry.
Fixes zaproxy/zaproxy#5295

Fix 5295: Cookie Flag FPs

---

addOns/addOns.gradle.kts

Add task `reportMissingHelp` to `addOns` project, which lists the
add-ons that do not have help (migrated from zap-admin repo).

Add task to list add-ons without help

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TestSQLInjection.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/TestSQLInjectionUnitTest.java

- Fix false positive/false negative conditions when the response bodies contain the test expressions.
- Address Java 8 todos, leverage Math functions now that Java 8 is being targeted.
- UnitTests simplify seeming reflected content inclusions, add reflected variants of shouldNotAlert tests.
- Updated CHANGELOG.
Fixes zaproxy/zaproxy#5271

ascanrules: SQLi fix FP/FN & Address Java 8 todos

---

addOns/bruteforce/bruteforce.gradle.kts
addOns/bruteforce/src/test/java/com/sittinglittleduck/DirBuster/EasySSLProtocolSocketFactoryUnitTest.java

Start the test server with random port to avoid clashes, also, use the
server from `testutils` instead of another server implementation.

bruteforce: use random port in test server

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScanner.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScannerTest.java

- SubResourceIntegrityAttributeScanner > Modify `getHost` to handle relative paths and elements without src attributes.
- SubResourceIntegrityAttributeScannerTest > Add tests.
Fixes zaproxy/zaproxy#5789

Fix pscanrulesAlpha: SubResourceIntegrityAttributeScanner NPE

---

addOns/zest/CHANGELOG.md
addOns/zest/zest.gradle.kts

Update Zest library to 0.14.1, to restore proxying capability.

zest: update Zest library

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/pscanrules.gradle.kts
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentTypeMissingScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieSameSiteScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/HeaderXssProtectionScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureReferrerScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InsecureAuthenticationScan.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/UsernameIdorScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XAspNetVersionScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XContentTypeOptionsScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XDebugTokenScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XFrameOptionScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XPoweredByHeaderInfoLeakScanner.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/payloader/ExtensionPayloader.java

- UsernameIdorScanner > Updated to leverage `getHelper().getUsers`.
- pscanrules.gradle.kts > Updated to use `org.zaproxy:zap:2.9.0`.
- CHANGELOG.md > Added change notes related to core changes and 'Username Hash Found' scan rule change.
&nbsp;
- Various scan rules updated to accommodate core deprecations related to: zaproxy/zaproxy#5756
&nbsp;
- ExtensionPayloader > Removed `getUrl()` use of `Constant.ZAP_HOMEPAGE`.

pscanrules: Update scan rules to leverage 2.9.0 core

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechPanel.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerAPI.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
addOns/wappalyzer/src/main/resources/org/zaproxy/zap/extension/wappalyzer/resources/Messages.properties
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScannerUnitTest.java

Instead of using host:port use scheme and authority.
Ex:

Normalize site "names"

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestZapRunner.java
addOns/zest/zest.gradle.kts

Update Zest library to 0.14.2, to correctly ignore cert checks.
Update ZestZapRunner to ignore cert checks (e.g. when proxying through
ZAP).

zest: update Zest library and prepare release

---

addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/VulnerabilityCache.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/InsecureComponentScannerUnitTest.java

As specified in issue [5498](https://github.com/zaproxy/zaproxy/issues/5498), unit-tests for class `InsecureComponentScanner` are added.
The VulnerabilityCache-Database is not used. Instead of the vulnerabilities are injected in the unit-tests with the new method `VulnerabilityCache.add()`. With this approach no difficult mocking of the singleton-class `VulnerabilityCache` is needed.
Fix zaproxy/zaproxy#5498.

Unit-Tests for class InsecureComponentScanner

---

addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScannerUnitTest.java

This Pull-Request adds all unit-tests, where we expect the response to be store- and cacheable.
In the first step the focus was on non-storeable or non-cacheable responses. Now in the second step the focus is on store- and cacheable responses.
Fix zaproxy/zaproxy#5500.

Unit-Tests for class CacheableScanner second step

---

addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/AlertsCacheableScannerUnitTest.java

According to issue [zaproxy-5500](https://github.com/zaproxy/zaproxy/issues/5500), i implemented a part of the unit-tests for the class `CacheableScanner` in Add-On `pscanrulesAlpha`.
Pack up all unit-tests would be too much for a single Pull-Request.
So i wanted to split these tests and make two Pull-Requests.
This PR contains all the testcases, where alerts are expected, 
The second step is to implementing the testcases, where no alerts are expected. For the second step, i want to open another Pull-Request.

Unit-Tests for class CacheableScanner first step

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureSuspiciousComments.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureSuspiciousCommentsUnitTest.java

* When matching in JavaScript or script blocks alerts at Low confidence.
* All alerts now contain more specific "other info" details.
* Updated UnitTest to assert new confidence detail.
* Updated changelog with change details.
* Messages.properties updated with new key/value to facilitate "other info" enhancement.
Fixes zaproxy/zaproxy#5834

Fix 5834: Information Disclosure: Suspicious Comments

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/PiiScanner.java
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/pscanrulesBeta/src/main/resources/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/PiiScannerCreditCardUnitTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/PiiScannerUnitTest.java

Despite the previously added boundary check if number sequences were exactly the right length they may still be flagged as CC even though they may be numbers with exponents. Tweak the alert name to be more clear (from 'PII Disclosure scanner' to 'PII Disclosure'). The scan rule now attempts to grab characters after the matched string and convert to Float, so that values such as 2.4670000000000001E-2 or 2.4670000000000001E2 are no longer considered CCs.
Includes UnitTest updates, help tweak, and change log entries.

Fix issue 5841 - PII False Positives on exponential numbers

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanner.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScannerUnitTest.java

Timestamp Disclosure scan rule now only considers potential timestamps within plus or minus one year when used at High threshold.
Fixes zaproxy/zaproxy#5837

Issue 5837: Add High Threshold Handling

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureInURL.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureInURLUnitTest.java

- 'Information Disclosure - Sensitive Information in URL'
- Expanded details in 'otherinfo' field.
- Corrected evidence matching (paramnames are checked so paramnames should be evidence [not param values]).
Fixes zaproxy/zaproxy#5832

Issue 5832: Clarify URL Info Disclosure

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
addOns/pscanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties

Base64Disclosure > Functional change to return after alerting.
CHANGELOG > Added fix note.
Messages.properties > Added note to description.
Fixes zaproxy/zaproxy#5856

Fix Issue 5856: Reduce alerting in Base64 Disclosure

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosure.java
addOns/ascanrulesBeta/src/main/resources/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties

- Updated CWE to [530](https://cwe.mitre.org/data/definitions/530.html), added reference links to alerts, made sure WASC and CWE identifiers are included in alerts.
- Updated CHANGELOG.

Backup File Disclosure Tweaks

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/pscanrules.gradle.kts

- Tweak pscanrules.gradle.kts to use the updated libarary.
- Add 'change' entry to CHANGELOG

pscanrules: CSP Salvation Library Upgrade to 2.7.1

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureReferrerScanner.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureReferrerScannerUnitTest.java
addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/pscanrulesBeta.gradle.kts
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/PiiScanner.java
sharedutils/src/main/java/org/zaproxy/zap/sharedutils/PiiUtils.java

- Created PiiUtils from the PiiScanner.
- Modify PiiScanner to use the shared utils, remove TODO note.
- Modify InformationDisclosureReferrerScanner to use the shared utils.
InformationDisclosureReferrerScannerUnitTest removed an un-used local variable in one of the tests (call it a clean code activity).
- Add generic "Maintenance changes" note to CHANGELOGs.

Extract more sharedutil methods

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/OpenApiSpider.java

Content type check in canParseResource(Httpmessage, String, boolean) is made more specific. Fixes zaproxy/zaproxy#5725.
Signed-off-by: Akshath Kothari <akshath.kothari@gmail.com>

Fix 5725: Spider Check for JSON/YAML'ish content

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/javahelp/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html

Link to site blog posts (from zaproxy/zaproxy-website#15).
Remove duplicated "the" (from zaproxy/zaproxy-website#16).

Update blog links and fix typos

---

addOns/authstats/CHANGELOG.md
addOns/authstats/authstats.gradle.kts
addOns/authstats/src/main/java/org/zaproxy/zap/extension/authstats/ExtensionAuthStats.java

Change `ExtensionAuthStats` to:
- Hook the `HttpSenderListener` to be automatically removed when the
extension is unloaded, allowing the extension to be dynamically
unloaded;
- Remove the author, it will use the one from the add-on.
Update minimum ZAP version to 2.9.0.
Normalise author in the manifest (`ZAP Core Team` → `ZAP Dev Team`).

authstats: dynamically unload the add-on

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ExtensionZest.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestActiveRunner.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestEngineWrapper.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestPassiveRunner.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestSequenceRunner.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestZapRunner.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestDialogManager.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestRecordScriptDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestScriptsDialog.java
addOns/zest/zest.gradle.kts

Use new core features.
Address deprecations and unnecessary casts.
Remove redundant author/URL in the extension.

zest: update ZAP to 2.9.0

---

addOns/custompayloads/custompayloads.gradle.kts
addOns/openapi/openapi.gradle.kts
addOns/soap/soap.gradle.kts

Use `ZAP Dev Team` instead of `ZAP Core Team`, the latter was less used.

Normalise author name in add-ons

---

addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestZapUtils.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestActionDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestAssertionsDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestAssignmentDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestClientElementAssignDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestClientElementDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestClientElementSendKeysDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestClientLaunchDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestClientScreenshotDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestClientSwitchToFrameDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestClientWindowHandleDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestControlDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestCookieDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestExpressionDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestLoopDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestParameterDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestRequestDialog.java

Replace add-on code with core method that sets the pop up menu into
the dialogue fields.

zest: use core method to set pop up menu

---

addOns/jruby/CHANGELOG.md
addOns/jruby/jruby.gradle.kts
addOns/jruby/src/main/java/org/zaproxy/zap/extension/jruby/ExtensionJruby.java
addOns/jruby/src/main/java/org/zaproxy/zap/extension/jruby/JrubyEngineWrapper.java

Address deprecation.
Use the `ScriptEngineFactory` directly, remove code no longer needed.
Remove redundant author in the extension.

jruby: update ZAP to 2.9.0

---

addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledCookieScanner.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledCookieScannerUnitTest.java

Change `UserControlledCookieScanner` to return earlier if there are no
cookies or parameters.
Remove unused instance when preparing the tests.

pscanrulesBeta: tidy up scan rule

---

addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/UsernameIdorScanner.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/UsernameIdorScannerUnitTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/ServletParameterPollutionScannerUnitTest.java
testutils/src/main/java/org/zaproxy/zap/extension/pscan/PassiveScanTestHelper.java
testutils/src/main/java/org/zaproxy/zap/testutils/PassiveScannerTestUtils.java
testutils/src/main/java/org/zaproxy/zap/testutils/TestUtils.java
testutils/src/main/resources/mockito-extensions/org.mockito.plugins.MockMaker
testutils/testutils.gradle.kts

Allow to test scan rules that use new core features (i.e. raise alerts
through the alert builder and use `PassiveScanData`).
Update `UsernameIdorScanner` as example.

testutils: update ZAP to 2.9.0

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestRequestDialog.java

Make sure the header fields are separated with CRLFs when setting them
to the script as the editor might just add LFs, also, normalise them to
LFs when reading from the script.
----
From OWASP ZAP User Group: https://groups.google.com/d/topic/zaproxy-users/BSENsfc5Zs4/discussion

zest: properly separate header fields when editing

---

addOns/bruteforce/CHANGELOG.md
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/Manager.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/ProcessChecker.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/Worker.java
addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/DirBusterManager.java

The problem was in the getTotalDone() method: when the number of requests was too small the areWorkersAlive() check would return false without assigning any value to the done variable. Now we call the parent's method that returns its totalDone variable.
Also, I noticed some problems with the progress bar that shows the same percentage as the totalDone after finishing.
Adding a new target site was also unobvious to me, but it could be caused by a lack of experience. :)
Closes zaproxy/zaproxy#5437

Forced Browse - Correct request count reported

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/JSFunctionPassiveScanner.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/payloader/ExtensionPayloader.java
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
addOns/pscanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
addOns/pscanrulesAlpha/src/main/zapHomeFiles/xml/js-function-list.txt
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/JSFunctionPassiveScannerUnitTest.java

Resolves zaproxy/zaproxy#5673
Hello, I'm hoping to get feedback on my initial implementation of the pscan rule. I'm assuming converting the DOM source into a string and checking if it contains methods in the list should be sufficient?
Additionally, I don't know how to test the feature properly. The list of functions are loaded from a file and so whenever I try to test it in my dev environment the function list would be empty (since in deployment the files are loaded from `Constant.getZapHome`)

Add passive scan rule for dangerous js functions

---

addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/SeleniumOptionsPanel.java

Do not specify any colour when creating the titled border, let the look
and feel use the most appropriate one.
Part of zaproxy/zaproxy#5542.

selenium: remove hardcoded colour in titled border

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TestExternalRedirect.java
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/TestUserAgent.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/TestUserAgentUnitTest.java

Use the same risk that the scan rules use to raise the alerts:
- `TestExternalRedirect` → `HIGH`;
- `TestUserAgent` → `INFO`.
(Both were using the default, `MEDIUM`.)
Replace the risk constant with the getter when raising the alerts.

Correct active scan rules' risk

---

addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/WebSocketAPI.java

Ensure the parameters object passed to API implementors is not null,
they expect/require non-null object.

websocket: prevent exception in API implementors

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/HiddenFilesScanRule.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/HiddenFilesScanRuleUnitTest.java

Check if the path is null when creating the new path for the hidden
file.

ascanrulesAlpha: fix NPE in HiddenFilesScanRule

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ServletParameterPollutionScanner.java
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/ServletParameterPollutionScannerUnitTest.java

Fixes zaproxy/zaproxy#4454
Update scan rule, unit test, help, and changelog. If the threshold isn't Low or techset doesn't include JSP/Servlet don't scan response.

pscanrulesBeta: SPP Check Tech

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/UsernameEnumeration.java

- com.googlecode.java-diff-utils:diffutils [1.2.1 -> 1.3.0] (Used by UsernameEnumeration)
- org.apache.commons:commons-lang3 [3.5 -> 3.9] (Used in unit tests testImplementation)
- org.jsoup:jsoup [1.7.2 -> 1.13.1] (Used by RelativePathConfusionScanner)

ascanrulesBeta: Update Dependencies

---

addOns/ascanrules/ascanrules.gradle.kts
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TestSQLInjection.java

- com.googlecode.java-diff-utils:diffutils [1.2.1 -> 1.3.0] (Used by TestSQLInjection)
- org.bitbucket.mstrobel:procyon-compilertools [0.5.25 -> 0.5.36] (Used by SourceCodeDisclosureWEBINF)
I didn't update the CHANGELOG further as it already contains a "maintenance changes" entry

ascanrules: Update Dependencies

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TestSQLInjection.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/TestSQLInjectionUnitTest.java

Do not check the `Db` tech by reference since imported contexts use new
`Tech` instances.
Fix zaproxy/zaproxy#5918 - Skipped plugin TestSQLInjection with imported
Context

ascanrules: correct tech check in SQL Injection

---

addOns/diff/CHANGELOG.md
addOns/diff/diff.gradle.kts
addOns/diff/src/main/java/org/zaproxy/zap/extension/diff/ZapDiffRowGenerator.java
addOns/diff/src/main/resources/org/zaproxy/zap/extension/diff/resources/Messages.properties

- com.googlecode.java-diff-utils:diffutils [1.2.1 -> 1.3.0]
- Also tweaked the menu item entries to use Title Caps (per: zaproxy/zaproxy#2000)

diff: Update Dependencies

---

.github/workflows/create_wappalyzer_update.yml

Versus the April 3rd run from the test repo this one uses different github token, different git global config details, and further uses $GITHUB_USER in various places (global config and URLs), and standardizes the permissions of icons before copying them.
This job is setup to run 'At 04:00 on day-of-month 3.', per https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule time is UTC.

Add Wappalyzer Updates Github Action

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/wappalyzer.gradle.kts

- com.google.re2j:re2j [1.2 -> 1.3]
Tested, all unit tests pass, and tested live without issue.

wappalyzer: Update dependency

---

addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts

- io.swagger:swagger-compat-spec-parser [1.0.48 -> 1.0.50]
- io.swagger.parser.v3:swagger-parser [2.0.16 -> 2.0.18]
Tested all unit tests pass.

openapi: Update dependencies

---

addOns/pscanrulesBeta/pscanrulesBeta.gradle.kts

- com.google.re2j:re2j [1.2 -> 1.3] - Used by PiiScanner
Tested unit tests all pass.

pscanrulesBeta: Update dependencies

---

addOns/callgraph/CHANGELOG.md
addOns/callgraph/callgraph.gradle.kts

- org.tinyjee.jgraphx:jgraphx [2.0.0.1 -> 3.4.1.3]
Removed un-necessary dependency:
- jgraph:jgraph [5.5.1]

callgraph: Update Dependencies

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanner.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScannerUnitTest.java

- Update ContentSecurityPolcyScanner to handle multiple CSP headers via merge (intersect).
- Add a unit test to validate the change in functionality.
- Add note to help entry.
- Update CHANGELOG.
- Add supporting key/value to messages.properties.
Fixes zaproxy/zaproxy#5931

pscanrules: CSP Merge (Intersect) Multiple Headers

---

addOns/domxss/CHANGELOG.md
addOns/domxss/domxss.gradle.kts
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/TestDomXSS.java
addOns/soap/CHANGELOG.md
addOns/soap/soap.gradle.kts
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanner.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPXMLInjectionActiveScanner.java

Use new method to raise alerts in the scan rules.

Update ZAP to 2.9.0 in DOM XSS and SOAP

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/network/Requestor.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/network/RequestorUnitTest.java

Notify all redirects followed so that the responses match the requests,
otherwise first request would contain different response which could
lead to misleading alert (i.e. alert that belongs to different request).
---
Reported in OWASP ZAP User Group: https://groups.google.com/d/topic/zaproxy-users/KqfdEDTE4QA/discussion

openapi: notify all redirects followed

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestAuthenticationRunner.java

Intercept and handle the client requests as authentication requests.
Fix zaproxy/zaproxy#5940- Zest client side scripts cannot be used for
authentication

zest: handle client requests when authenticating

---

addOns/codedx/CHANGELOG.md
addOns/codedx/src/main/java/org/zaproxy/zap/extension/codedx/ExtensionAlertHttp.java

Change `ExtensionAlertHttp` to not extend `ExtensionAlert`, not needed
and it could end up in the add-on manifest (and thus being loaded as an
actual `Extension`).

codedex: remove unnecessary extends

---

addOns/tlsdebug/CHANGELOG.md
addOns/tlsdebug/src/main/java/org/zaproxy/zap/extension/tlsdebug/TlsDebugPanel.java

Use the background colour of the text field instead of hardcoding white.
Part of zaproxy/zaproxy#5542.

tlsdebug: replace hardcoded colour

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/AttackPanel.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/DefaultExplorePanel.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/LearnMorePanel.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartBackgroundPanel.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartHelper.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartPanel.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartSubPanel.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ajaxspider/AjaxSpiderExplorer.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/launch/LaunchPanel.java

Use the background colour of the text field instead of hardcoding white.
Extract a class for the panel with the custom background.
Part of zaproxy/zaproxy#5542.

quickstart: replace hardcoded colour

---

addOns/addOns.gradle.kts

Update add-on plugin to 0.4.0 to properly generate the add-on manifest.
The add-ons `ascanrulesBeta` and `ascanrulesAlpha` were not declaring in
the manifest the scan rules that extended `AbstractAppFilePlugin`.

Update add-on plugin

---

.github/workflows/create_wappalyzer_update.yml

Per:
- https://github.com/zaproxy/zap-extensions/pull/2386
- https://github.com/zaproxy/gradle-plugin-add-on/pull/28

Wappalyzer job now uses new gradle plugin CHANGELOG functionality

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureReferrerScanner.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureReferrerScannerUnitTest.java
addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/PiiScanner.java
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/pscanrulesBeta/src/main/resources/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
sharedutils/sharedutils.gradle.kts
sharedutils/src/main/java/org/zaproxy/zap/sharedutils/PiiUtils.java
sharedutils/src/main/java/org/zaproxy/zap/sharedutils/binlist/BinList.java
sharedutils/src/main/java/org/zaproxy/zap/sharedutils/binlist/BinRecord.java

- sharedutils > Add classes and functionality to load BINList and retrieve entries. This leverages a compressible collection structure from Apache commons collections (PatriciaTrie).
- pscanrulesBeta > Change PiiScanner to leverage the new functionality and lookup evidence against the BINList. If a match is found raise at High confidence and with additional details included in otherinfo, otherwise Medium confidence.
- pscanrules > Change InformationDisclosureReferrerScanner to leverage the new functionality and lookup evidence against the BINList. If a match is found raise at High confidence and with additional details included in otherinfo, otherwise Medium confidence.
Fixes zaproxy/zaproxy#5842

Add BINList Support

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledCharsetScanner.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledCookieScanner.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledJavascriptEventScanner.java

- UserControlledCookieScanner, UserControlledJavascriptEventScanner, and UserControlledCharsetScanner > Changed to set Risk Info and Confidence Low for these passive scanners.
- CHANGELOG > Added note to unreleased section.
Fixes zaproxy/zaproxy#5333

Adjust Risk and Confidence on some User Controlled value pscan rules

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/zapHomeFiles/json/hidden_files.json

- 'Hidden File Finder' add pattern for vim_settings.xml (CVE-2019-14957).

HFF Add vim_settings.xml pattern

---

testutils/src/main/java/org/zaproxy/zap/testutils/HTTPDTestServer.java

Make sure the request body is consumed in case of 404 to keep the
connection in good state.

testutils: consume request body on 404

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/pscanrules.gradle.kts

Changelog tweaked, 2.7.1 revision wasn't released yet.
Minor upstream changes:
https://github.com/shapesecurity/salvation/compare/v2.7.1..v2.7.2

pscanrules: CSP scan rule upgrade salvation to 2.7.2

---

addOns/retire/CHANGELOG.md
addOns/retire/retire.gradle.kts
addOns/retire/src/main/java/org/zaproxy/addon/retire/Result.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/model/Repo.java
addOns/retire/src/test/java/org/zaproxy/addon/retire/RetireScanRuleUnitTest.java
addOns/retire/src/test/resources/org/zaproxy/addon/retire/testrepository.json

- Prepare next dev iteration.
- Repo, Result, RetireScanRule, RetireScanRuleUnitTest: Changes to accommodate new behavior. Per alert (result) CVEs and info/references are collected/used as a Set.
- testrepository.json: Update so that one of the libraries has vulns with overlapping (non-unique) CVE and info (ref) details.

Retire: Change "info" to proper references & change otherinfo handling

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/ascanrules.gradle.kts
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/BufferOverflow.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CodeInjectionPlugin.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CommandInjectionPlugin.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/FormatString.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureWEBINF.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TestCrossSiteScriptV2.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TestDirectoryBrowsing.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TestExternalRedirect.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TestInjectionCRLF.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TestParameterTamper.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TestPathTraversal.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TestPersistentXSSAttack.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TestRemoteFileInclude.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TestSQLInjection.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TestServerSideInclude.java

Use new method to raise alerts in the scan rules.

ascanrules: update ZAP to 2.9.0

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/CloudMetadataScanner.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleFileActiveScanner.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleSimpleActiveScanner.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/HiddenFilesScanRule.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/LDAPInjection.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjection.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/XSLTInjection.java

Use new method to raise alerts in the scan rules.

ascanrulesAlpha: update ZAP to 2.9.0

---

addOns/encoder/CHANGELOG.md
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/contents/encoder.html
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/helpset.hs
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/index.xml
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/map.jhm
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/toc.xml
addOns/encoder/src/main/resources/org/zaproxy/addon/encoder/resources/Messages.properties

- Copy and update primary help content from zap-core-help.
- Make one minor UI string change adding a colon at the end of the input text label.
Part of: zaproxy/zaproxy#5996

encoder: Add help content

---

addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Base64Decoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Base64Encoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Base64UrlDecoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Base64UrlEncoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/DefaultEncodeDecodeProcessor.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/HexStringEncoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/HtmlStringEncoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/IllegalUTF8Encoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/JavaScriptStringEncoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Md5Hasher.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Sha1Hasher.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/UrlDecoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/UrlEncoder.java

Use direct or local calls instead of depending on core Encoder class.
Base64 charset/breaklines options still needs to be handled. The plan is to do that in another PR.

encoder: Remove dependence on core Encoder class

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanner.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScannerUnitTest.java

Related to zaproxy/zaproxy#6014

Correct CSP directive name frame-ancestors

---

.github/workflows/create_wappalyzer_update.yml

Per: https://github.com/AliasIO/wappalyzer/commits/master/src (May 27th commits) the location of icons in the upstream repo has been changed.
https://github.com/AliasIO/wappalyzer/commit/b7f4d81866220b63d6791f85da25f2530d69d196#diff-25d902c24283ab8cfbac54dfa101ad31
And
https://github.com/AliasIO/wappalyzer/commit/eb8284884795992752b7c2514f75d50280cb9eb1#diff-25d902c24283ab8cfbac54dfa101ad31

Update icons location in wappalyzer GitHub action

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesBeta/CHANGELOG.md
addOns/encoder/CHANGELOG.md
addOns/pscanrules/CHANGELOG.md
addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesBeta/CHANGELOG.md
addOns/retire/CHANGELOG.md

* ascanrules v35
* ascanrulesBeta v28
* ascanrulesAlpha v28
* encoder v0.2.0
* pscanrules v29
* pascanrulesBeta v22
* pscanrulesAlpha v27
* retire v0.2.0

pscanrules (all), ascanrules (all), retire, encoder: prepare releases

---

.github/workflows/create_retirejs_update.yml

Following: https://github.com/zaproxy/zap-extensions/runs/729601355?check_suite_focus=true
The project is "retire" not "retirejs".
Luckily nothing was actually missed, there hasn't been an upstream update since April 12.

Retire.js GitHub Action Fix

---

addOns/encoder/CHANGELOG.md
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/EncodeDecodeProcessors.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Sha256Hasher.java
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/contents/encoder.html
addOns/encoder/src/main/resources/org/zaproxy/addon/encoder/resources/Messages.properties
addOns/encoder/src/main/resources/org/zaproxy/addon/encoder/resources/encoder-default.xml
addOns/encoder/src/main/zapHomeFiles/scripts/templates/encode-decode/rot13.js

- Added a ROT13 example script.
- Added a SHA256 predefined processor.
Part of: zaproxy/zaproxy#5996

encoder: Add rot13 example script & SHA256 Predefined

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/ExtensionHttpFuzzer.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/HttpFuzzerHandler.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/messagelocations/MessageLocationReplacers.java

For more information please have a look at PR: https://github.com/SasanLabs/owasp-zap-jwt-addon/pull/6/files?diff=split&w=1#diff-eb7bf36677e406a2ac8688229c232a94R52
Commit with the difference:
https://github.com/SasanLabs/owasp-zap-jwt-addon/pull/6/commits/6448f54108a5262dc799437a514cf7442415ca0f

Fix handling of other HTTP message locations when fuzzing

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechPanel.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerParam.java
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html

* ExtensionWappalyzer - Add necessary variables and functionality to handle enable state.
* TechPanel - The enable toggle is associate with the param (enable state).
* WappalyzerParam - New class extending AbstractParam to handle the enable state.
* wappalyzer.html - Updated help content to contain a short bit about the toggle button and persistence.
* CHANGELOG - Added change entry.

wappalyzer: Persist enable state

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/processors/FuzzerHttpMessageScriptProcessorAdapter.java
addOns/groovy/CHANGELOG.md
addOns/groovy/src/main/zapHomeFiles/scripts/templates/httpfuzzerprocessor/FuzzerHttpProcessorDefaultTemplate.groovy

Bugfix for Template raising Exception
```
ERROR org.zaproxy.zap.extension.scripts.OutputPanel  - groovy.lang.MissingMethodException: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getRequiredParamsNames() is applicable for argument types: () values: []
java.lang.RuntimeException: groovy.lang.MissingMethodException: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getRequiredParamsNames() is applicable for argument types: () values: []
```

Bugfix for groovy.lang.MissingMethodException

---

addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/BodyGenerator.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/DataGenerator.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/PathGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/AbstractServerTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v2/OpenApiUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/BodyGeneratorUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v2/PetStore_defn.json
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v2/PetStore_defn.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v2/PetStore_defn_examples.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v2/PetStore_defn_loop.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v2/PetStore_defn_no_host.json
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v2/PetStore_defn_no_schemes.json
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/Complex_object_in_form_data.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/OpenApi_defn_examples.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/PetStore_defn.json
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/PetStore_defn.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/PetStore_defn_loop.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/PetStore_defn_no_servers.json
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/PetStore_defn_with_examples.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/Petstore_defn_variable_in_server_definition.yaml

Using Example values from the imported API Definition for Request values.
Closes zaproxy/zaproxy#5168
Changes made on behalf of SDA SE
OpenAPI 2 didn't support examples in the path or query sections of requests. The in official fallback was to use a property called `x-example` or `x-examples` to specify multiple examples. The `x-example` properties are also supported by this change, as the automatic OpenAPI 2 => 3 conversion upgrades these to the official OpenAPI 3 `example` property automatically.
This implementation currently only supports examples using the single value `example` property not the `examples` property. The `examples` object is basically a map of named examples where the key is the name. See: https://swagger.io/docs/specification/adding-examples/
I guess the best thing to …

Use OpenAPI examples to generate Values in Requests on behalf of SDA SE

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/BodyGeneratorUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiUnitTest.java

Update the new tests for JUnit 5.

openapi: update tests for JUnit 5, prepare release

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java

- In wappalyzer (postInstall) and websocket (onHandshakeResponse) when extension panels/tabs are shown ensure it's done in EDT thus preventing the exception that was manifesting.
- Add a Fix entry to the CHANGELOGs.

Fix IndexOutOfBounds Exception when showing tabs

---

addOns/retire/CHANGELOG.md
addOns/retire/retire.gradle.kts
addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/wappalyzer.gradle.kts

- *.gradle.kts > Now sets Beta status.
- Update changelogs with release date and link to tag.

retire & wappalyzer: Promote to Beta & Prepare releases

---

addOns/retire/CHANGELOG.md
addOns/retire/retire.gradle.kts
addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/wappalyzer.gradle.kts

- Both: Update version and changelog
- retire: set URL to web help content

retire/wappalyzer: prepare next dev iteration & set URL (retire)

---

addOns/bugtracker/CHANGELOG.md
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTracker.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerBugzilla.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerBugzillaOptionsPanel.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerGithub.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerGithubOptionsPanel.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/ExtensionBugTracker.java

Remove the options panel when the extension is unloaded.
Correct the help key in the options panels.

bugtracker: remove options panels when uninstalled

---

testutils/src/main/java/org/zaproxy/zap/testutils/TestUtils.java
testutils/src/main/resources/Messages.properties

Remove test setup required for older ZAP versions, all the add-ons are
now targeting 2.9.0.

testutils: remove support for older ZAP versions

---

addOns/retire/CHANGELOG.md
addOns/retire/retire.gradle.kts
addOns/retire/src/main/resources/org/zaproxy/addon/retire/resources/jsrepository.json

- "Add CVE-2020-7676 for angular < 1.8.0".
- https://github.com/RetireJS/retire.js/commit/bb639d52783247f6578be6c021e521a9cbb99815
- CHANGELOG change note added & updated for release (tag link, date, etc).

retire: Upstream update

---

testutils/src/main/java/org/zaproxy/zap/testutils/TestUtils.java

Otherwise on some platforms (Win10) zap.log might seem to be in use.
<details>
<summary>Exception prior to fix (Click the triangle/control to the left to expand)</summary>
```log
Jun 18, 2020 10:35:32 PM org.junit.jupiter.engine.execution.JupiterEngineExecutionContext close
SEVERE: Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.ClassExtensionContext@546e61d5
java.io.IOException: Failed to delete temp directory C:\Users\someuser\AppData\Local\Temp\junit1073536641428285888. The following paths could not be deleted (see suppressed exceptions for details): , home, home\zap.log
at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.createIOExceptionWithAttachedFailures(TempDirectory.java:249)
at …
```

testutils: Partially revert 2448 prevent setup and creation of the log

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ImportFromFileDialog.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/BodyGenerator.java
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/Messages.properties
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/BodyGeneratorUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/OpenApi_defn_no_schema.yaml

Show exception in the Output tab and tweak message.
Correct parent dialogue when choosing the file to import.
Handle no schema when generating the request body, not required.
Fix zaproxy/zaproxy#6041 - OpenAPI Import Choose File Dialog
appears behind OpenAPI Import dialog
Fix zaproxy/zaproxy#6042 - Error parsing small valid OpenAPI spec

openapi: correct dialogue parent, handle no schema

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanner.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScannerUnitTest.java

- The CSP scan rule now checks if the form-action directive allows wildcards.
- The CSP scan rule now includes further information in the description of allowed wildcard directives alerts when the impacted directive is one (or more) which doesn't fallback to default-src.
- CHANGELOG and Messages.properties updated as necessary to support the improvements.
- UnitTest increased coverage from 75.7% to 99%.

CSP Scan Rule Improvements

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/dialogs/EditScriptDialog.java

Allow to see/copy the engine name/language of a script.
Use core method to add the read only text fields.

scripts: show engine when editing script

---

addOns/jython/CHANGELOG.md
addOns/jython/jython.gradle.kts
addOns/jython/src/main/java/org/zaproxy/zap/extension/jython/ExtensionJython.java
addOns/jython/src/main/javahelp/org/zaproxy/zap/extension/jython/resources/help/contents/jython.html

Update to latest version, 2.7.2, for improvements and fixes (addresses
"illegal reflective access" warnings with newer Java versions).
Remove workaround for slow engine start up, no longer required.
Part of zaproxy/zaproxy#2602.

jython: update Jython library

---

addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleFilePassiveScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleSimplePassiveScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/FeaturePolicyScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/InPageBannerInfoLeakScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsFunctionScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsoScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/payloader/ExtensionPayloader.java
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
addOns/pscanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/AlertsCacheableScanRuleUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScanRuleUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/FeaturePolicyScanRuleUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/InPageBannerInfoLeakScanRuleUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsFunctionScanRuleUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsoScanRuleUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanRuleUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScanRuleUnitTest.java

- Scan Rule unittest names.
- Message.properties keys (and some values).
- Help content.
- Remove boilerplate javadoc in one scan rule class.
- Replace blogspot URLs with zaproxy.org.

pscanrules Alpha: ScanRule Consistency

---

addOns/soap/CHANGELOG.md
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanRule.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPXMLInjectionActiveScanRule.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/WSDLFilePassiveScanRule.java
addOns/soap/src/main/javahelp/org/zaproxy/zap/extension/soap/resources/help/contents/soap.html
addOns/soap/src/main/resources/org/zaproxy/zap/extension/soap/resources/Messages.properties
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanRuleTestCase.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/WSDLFilePassiveScanRuleTestCase.java

- Scan Rule unittest names.
- Help content.
- CHANGELOG split Fixed and Changed items, already contained "Maintenance changes" item.

soap: ScanRule Consistency

---

.github/workflows/create_retirejs_update.yml
.github/workflows/create_wappalyzer_update.yml

Wappalyzer and Retirejs create update PR jobs now support being triggered by a web request.
https://github.community/t/who-will-be-the-github-actor-when-a-workflow-runs-on-a-schedule/17369/2 seems to suggest that it's whoever commits the job that is `github.actor` for the scheduled invocation. So that if actor check should be fine for the monthly cron use.

Add External Trigger support for retirejs and wappalyzer jobs

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScanRule.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScanRuleUnitTest.java

Resolves zaproxy/zaproxy#6047.

Avoid flagging missing SRI attribute when HTML asset is inline

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScannerUnitTest.java

Check only the src attribute of script elements not the whole response.
Fix zaproxy/zaproxy#6054 - Wappalyzer regexes being applied to the wrong
elements

wappalyzer: correct script check

---

addOns/graphql/graphql.gradle.kts
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ExtensionGraphQl.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlApi.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParseFilter.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParser.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlSpider.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/HistoryPersister.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ImportFromAbstractDialog.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ImportFromFileDialog.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ImportFromUrlDialog.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/MessageValidator.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/RequesterListener.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/Requestor.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/UrlBuilder.java
addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/contents/graphql.html
addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties

- Add import functionality to the UI, API, and the CLI.
- Schema in SDL can now be imported.
- Import via Introspection also works.
- Rename fieldFrom to fieldSchema for clarity.
- Add Spider Checks

Add Import Functionality for GraphQL Schemas

---

.github/workflows/create_retirejs_update.yml
.github/workflows/create_wappalyzer_update.yml

PRs will now only be created if there are actually changes from upstream.
In follow-up to: https://github.com/zaproxy/zap-extensions/pull/2479

Add conditional handling to add-on update jobs

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/OpenApiAPI.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/OpenApiAPIUnitTest.java

Check the return value for null when importing the OpenAPI definition
through the API, it's null when unable to access/get the definition
(`IOException`).

openapi: fix NPE when unable to get the definition

---

addOns/viewstate/CHANGELOG.md

---
For the leak fix, which prevents the requester add-on from being properly unloaded.

viewstate: prepare release

---

addOns/requester/CHANGELOG.md
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ExtensionRequester.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/HttpPanelSender.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ManualHttpRequestEditorPanel.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/NumberedTabbedPane.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/RequesterPanel.java

Apply the changes done in core manual request editor:
- Add the requests to the Sites tree (to be able to scan them);
- Reset the user when resending the message;
- Use HTTP/1.1 in the default message;
- Allow to disable cookies;
- Enforce the mode (e.g. protected, safe);
- Dynamically enable/disable the session tracking button when the
option changes.
Fix zaproxy/zaproxy#5778 - It is not possible attack a history entry
generated by Requester tab
Fix zaproxy/zaproxy#4934 - Requester - Allow to disable cookies

requester: sync with core features

---

.github/workflows/create_retirejs_update.yml
.github/workflows/create_wappalyzer_update.yml

Instead of using web requests (repository_dispatch) use the new web UI manual run functionality (workflow_displatch). Per:
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

Switch retire and wappalyzer jobs manual trigger

---

addOns/frontendscanner/frontendscanner.gradle.kts
addOns/frontendscanner/src/main/java/org/zaproxy/zap/extension/frontendscanner/ExtensionFrontEndScanner.java
addOns/frontendscanner/src/main/java/org/zaproxy/zap/extension/frontendscanner/FrontEndScannerProxyListener.java
addOns/frontendscanner/src/main/javahelp/org/zaproxy/zap/extension/frontendscanner/resources/help/contents/frontendscanner.html
addOns/frontendscanner/src/test/java/org/zaproxy/zap/extension/frontendscanner/FrontEndScannerProxyListenerUnitTest.java

3 features in 1 PR:
* solution for zaproxy/zaproxy#4897
* ~brutal~ easy fix for zaproxy/zaproxy#4893
* deal with "corner cases" in `<head>`: when it's not present, and when it's empty

Some improvements for the FrontEndScanner

---

.github/workflows/sonar.yml
addOns/addOns.gradle.kts
build.gradle.kts

~Add support for Sonar scan for each branch according to [Using SonarCloud with Travis CI](https://docs.travis-ci.com/user/sonarcloud/)~
~To do to make it work:~
~1. Get a token from https://sonarcloud.io/account/security~
~2. Add an environment variable SONAR_TOKEN with the token in travis-ci.org~
~3. To activate analysis on pull requests, you need to install the SonarCloud application on your GitHub organization(s).  (cf. https://docs.travis-ci.com/user/sonarcloud/#analysis-of-internal-pull-requests)~
- addOns.gradle.kts > Modified so that jacoco reports include XML output.
- build.gradle.kts > Modified to include sonarqube.
- sonar.yml > Added to run a GitHub action workflow every Saturday in order to update the SonarCloud SAST results and coverage info.

Add SonarCloud as a Scheduled GitHub Action

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SessionFixationScanRule.java

- SessionFixationScanRule > Add convenience method for checking `Set<String>` content case insensitively.
- CHANGELOG > Add change entry.
Fixes zaproxy/zaproxy#6082

Fix 6082: Session Fixation check flags case insensitively

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/CsrfTokenScanRule.java
addOns/ascanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/CsrfTokenScanRuleUnitTest.java

- ascanrulesBeta.gradle.kts > Update version for next iteration.
- CHANGELOG > Update for next iteration and add change note.
- CsrfTokenScanRule > Add conditional to bail if the original message was non-HTML.
- CsrfTokenScanRuleUnitTest > Add a new test method to assert the new behavior, that no message is sent when the content-type of the original isn't HTML.
Fixes zaproxy/zaproxy#6089

CsrfTokenScanRule Ignore Non-HTML & Prepare Release

---

addOns/spiderAjax/spiderAjax.gradle.kts

Use latest ZAP version for API generation.

spiderAjax: use newer ZAP version for API gen

---

addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjectionScanRule.java
addOns/customreport/CHANGELOG.md
addOns/customreport/src/main/java/org/zaproxy/zap/extension/customreport/AlertsPanel.java
addOns/customreport/src/main/java/org/zaproxy/zap/extension/customreport/ReportLastScan.java
addOns/exportreport/CHANGELOG.md
addOns/exportreport/src/main/java/org/zaproxy/zap/extension/exportreport/FrameExportReport.java
addOns/exportreport/src/main/java/org/zaproxy/zap/extension/exportreport/filechooser/ReportFilter.java
addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/FuzzOptionsPanel.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XDebugTokenScanRule.java
addOns/revisit/CHANGELOG.md
addOns/revisit/src/main/java/org/zaproxy/zap/extension/revisit/ExtensionRevisit.java
addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderDialog.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderResultsTableModel.java
addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/treemap/nodes/contents/MessageContent.java
addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestSequenceRunner.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestAssignmentDialog.java

- ZestSequenceRUnner & ZestAssignmentDialog > String content check should use .isEmpty vs double-double-quote. (Added CHANGELOG entry.)
https://sonarcloud.io/project/issues?id=zaproxy_zap-extensions&open=AW0_ntKMVuKkC1XNoNuM&resolved=false&rules=java%3AS4973&types=BUG
https://sonarcloud.io/project/issues?id=zaproxy_zap-extensions&open=AXKGSLG7WlkO9R-U5SQp&resolved=false&rules=java%3AS4973&types=BUG
https://sonarcloud.io/project/issues?id=zaproxy_zap-extensions&open=AXKGSLG7WlkO9R-U5SQq&resolved=false&rules=java%3AS4973&types=BUG
https://sonarcloud.io/project/issues?id=zaproxy_zap-extensions&open=AXKGSLG7WlkO9R-U5SQr&resolved=false&rules=java%3AS4973&types=BUG
https://sonarcloud.io/project/issues?id=zaproxy_zap-extensions&open=AXKGSLG7WlkO9R-U5SQs&resolved=false&rules=java%3AS4973&types=BUG …

Sonar Fixes

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/AbstractAppFilePlugin.java

- AbstractAppFilePlugin > Only alert for 401/403 responses at Low threshold.
- CHANGELOG > Add a change note.
Fixes zaproxy/zaproxy#6077

commonlib: Adjust AbstractAppFilePlugin non-200 handling

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/HiddenFilesScanRule.java
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/HiddenFilesScanRuleUnitTest.java

* Builtin checks with content checks will alert with HIGH confidence if both conditions are met (for any threshold).
* Builtin checks that only match path (200) will alert at LOW confidence (only at HIGH threshold).
* User added payloads/checks alert at LOW confidence (for any threshold) [User added checks are purely path based].
- UnitTests updated.
- CHANGELOG updated.
Fixes zaproxy/zaproxy#6116

'Hidden File Finder' threshold handling

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/MessagePanelManager.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/impl/FuzzerDialog.java

Add two methods to `ExtensionFuzz` to allow to add custom components and
views to the fuzzer dialogue, for client and server messages.
Change `FuzzerDialog` to use the custom components/views.
Add `MessagePanelManager` to manage the custom components and views.

fuzz: allow to add custom message components/views

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/fuzz.gradle.kts
addOns/websocket/CHANGELOG.md
addOns/websocket/websocket.gradle.kts

Add release dates and links to tags.
Change fuzz add-on to use semantic versioning and remove "Adv" from the
name.
The add-on will be published to Maven Central with the following
group/id:
- Group: `org.zaproxy.addon`;
- Id: `fuzz` (same as the add-on ID).
Change websocket add-on to also target the newer version of fuzz add-on.

Prepare release of websocket and fuzz add-ons

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/HiddenFilesScanRule.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/HiddenFilesScanRuleUnitTest.java
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ElmahScanRule.java
addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/AbstractAppFilePlugin.java

- Ensure that requests sent by file presence rules are GET, with no body, and no content-type.
- Update CHANGELOGs.
- Update UnitTest for HFF.
Fixes zaproxy/zaproxy#6129

HFF, AbstractAppFilePlugin, & ELMAH appropriately use GET requests

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/FuzzOptionsPanel.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/FuzzerPayloadGeneratorUIHandler.java

Check that the default category is selected (non-null) before using it.
Fix zaproxy/zaproxy#6136.

fuzz: properly handle no default category selected

---

addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ExtensionGraphQl.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlGenerator.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlOptionsPanel.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParam.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParser.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ParserThread.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/Requestor.java
addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/contents/graphql.html
addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/contents/options.html
addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/toc.xml
addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/GraphQlGeneratorUnitTest.java

- Added option to provide arguments using variables (i.e. not inline).
- The active scan input vectors for separated arguments are working as expected.
To do:
(see https://stackoverflow.com/q/43675933).
All inputs / suggestions are appreciated :D.

GraphQL: Add Option For Separated Arguments 

---

addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScanRule.java

The CWE id was already managed for these Alerts/ScanRules and within ZAP they were already presented to the user.
However, when visiting the alert detail pages online (https://www.zaproxy.org/docs/alerts/), CWE (and WASC) links were not generated correctly.
The reason is, that the id values were set inline to the alert.
For the script which generates the detail pages however, the getter methods for the ids have to be added publicly to the class.
Note: if this solves the issue, I'll vote for another follow up issue to add this change to the PluginPassiveScanner parent class,
so that the docs will be generated consistently over all Passive Scan Rules.
Fixes zaproxy/zaproxy#6140.

Provide example alerts in Cookie scan rules

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/HistoryPersister.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/HistoryPersisterUnitTest.java

Change `HistoryPersister` to add the messages synchronously to the site
map (and history) to ensure that everything is completely imported
before finishing (e.g. return the API response).
Other changes:
- Log with the class itself, to avoid misleading log entries;
- Get the history extension once in the constructor, the extension
state will not change to try getting it each time;
- Remove unnecessary final modifier and code comment;
- Log the failure to persist the message as warn, this is bound to
happen if the session is being changed (e.g. new, save, load);
- Add the messages to the site map even when the history extension is
not enabled, there's no dependency between the two;
- Use `ThreadUtils` to add the message synchronously which does not
initialise the `EventQueue` if the view is …

openapi: add messages synchronously to site map

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/HeadersGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/generators/HeadersGeneratorUnitTest.java

Check for cookie parameters when generating the headers.
Other changes:
- Change accessibility of some methods to allow to test the header
generation individually (e.g. Accept, Content-Type, custom headers);
- Lower case the content type once and use a neutral locale;
- Use a `LinkedHashSet` when collecting the media types for the Accept
header to preserve their order.
Fix zaproxy/zaproxy#6045.

openapi: handle cookie parameters

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/DataGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiDefaultValuesTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v2/PetStore_defn.json
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v2/PetStore_defn.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v2/PetStore_defn_loop.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v2/PetStore_defn_no_host.json
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v2/PetStore_defn_no_schemes.json
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/PetStore_defn.json
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/PetStore_defn.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/PetStore_defn_all_relative_urls.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/PetStore_defn_loop.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/PetStore_defn_no_servers.json
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/PetStore_defn_with_examples.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/Petstore_defn_variable_in_server_definition.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/openapi_default_values.yaml

Change DataGenerator to use the default values of the body properties
too.
Fix zaproxy/zaproxy#6095.

openapi: use default values in bodies

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/SyntaxHighlightTextArea.java

In follow-up to: https://github.com/zaproxy/zaproxy/pull/5719
Signed-off-by: Kingthorin <kingthorin@users.noreply.github.com>

scripts: Remove config handling from SyntaxHighlightTetArea

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/Application.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechPanel.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerAPI.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParserUnitTest.java
addOns/wappalyzer/src/test/resources/org/zaproxy/zap/extension/wappalyzer/apps.json

- Application > Add description field, getter and setter.
- TechPanel > Add handling for getting the tooltip based on the description.
- WappalyzerAPI > Include the description in detailed API output.
- WappalyzerJsonParser > Set the description when available.
- CHANGELOG > Add a change note.
Ex (my cursor isn't showing but it is on the second row):

wappalyzer: Add technology descriptions to tooltip/API output

---

addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerAppsJsonParseUnitTest.java

Change `WappalyzerAppsJsonParseUnitTest` to fail if there was any
exception while parsing the `apps.json` file instead of logging an
error, which would go unnoticed in the tests.
Change `WappalyzerJsonParser` to allow to customise the behaviour when
an exception is thrown while parsing the file, log by default.

wappalyzer: fail on parsing exception of apps.json

---

addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanRuleUnitTest.java
testutils/src/main/java/org/zaproxy/zap/testutils/ActiveScannerTestUtils.java
testutils/src/main/java/org/zaproxy/zap/testutils/PassiveScannerTestUtils.java
testutils/src/main/java/org/zaproxy/zap/testutils/TestUtils.java

Check that active and passive scan rules have a non-empty i18n'ed name.
Tweak mock in `CookieHttpOnlyScanRuleUnitTest` to be lenient, not used
when checking the scan rule name.

testutils: check scan rules have i18n'ed name

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/XxeScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/XxeScanRuleUnitTest.java
testutils/src/main/java/org/zaproxy/zap/testutils/ActiveScannerTestUtils.java

Use correct message prefix when getting the reason why the `XxeScanRule`
was skipped.

ascanrulesBeta: fix message key in XxeScanRule

---

addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionSQLiteScanRuleUnitTest.java

Allow more messages to be sent, the CI builds have been failing because
more messages are being sent than the previous values (the exact number
depends on timing).

ascanrulesBeta: tweak msg count in SQLite tests

---

addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/CloudMetadataScanRuleUnitTest.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/EnvFileScanRuleUnitTest.java
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/HtAccesScanRuleUnitTest.java
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/AbstractAppFilePlugin.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/AbstractAppFilePluginUnitTest.java

- Add UnitTests and testing components for `CloudMetadataScanRule`, `EnvFileScanRule` (via AbstractAppFilePlugin), and `HtAccessScanRule`.
Fixes zaproxy/zaproxy#6212

Issue 6212: Add Scan Rule UnitTests

---

addOns/retire/CHANGELOG.md
addOns/retire/retire.gradle.kts
addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/wappalyzer.gradle.kts

- Updated CHANGELOG and build file promoting Wappalyzer and Retire.js add-ons to Release.

wappalyzer & retire: Promote to Release

---

addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ExtensionGraphQl.java

Without this change the graphql script is always displayed on startup, which is not what we want :)

Graphql: Dont display script on startup

---

addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SiteIsolationScanRule.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SiteIsolationScanRuleTest.java

Adjust inner class and variable naming to be more "Rule" centric and less "scanner".
Related to: zaproxy/zaproxy#6049

SiteIsolationScanRule: Issue 6049 Tweaks

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/wappalyzer.gradle.kts

- re2j 1.4 to 1.5. 
- batik 1.12 to 1.13
- CHANGELOG added change note.

wappalyzer: Dependency updates

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParam.java

- As discussed on Friday, enable optional arguments by default, for convenience when scanning small schemas using the zap-api-scan docker script.

GraphQL: Set Optional Arguments Enabled by Default

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java

Validate that the fuzz handler being added is non-null to fail earlier,
otherwise it would fail later when trying to select a message to fuzz.

fuzz: prevent adding null fuzz handlers

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/PopupEnableDisableScript.java

Change `PopupEnableDisableScript` to only be visible if the there's at
least one script that can be enabled/disabled.
Fix zaproxy/zaproxy#6256.

scripts: hide menu item if not applicable

---

addOns/customreport/CHANGELOG.md
addOns/customreport/src/main/java/org/zaproxy/zap/extension/customreport/ReportGenerator.java

customreport: Fix Report Write Failure When Path Contains '#'

---

addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
addOns/pscanrulesBeta/src/main/resources/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties

- Remove extra newline character from the references of the Directory Browsing scan rule. This was resulting in an extra empty bullet point in the [alert docs](https://www.zaproxy.org/docs/alerts/0/):

ascanrules: Remove extra newline character

---

addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParser.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/Requestor.java
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/GraphQlParserUnitTest.java

- Throw exception to outer method instead of catching it.
- Keeping the send() method because it is used in other classes as well.
As discussed on IRC.

GraphQL: Fix NPEs in case of Network Problems

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRule.java
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ProxyDisclosureScanRule.java

- Addressed STEs encountered in specific locations in these two scan rules.
- Added Fix note to the CHANGELOGs.

Handle SocketTimeoutExceptions in LDAP and Proxy Disclosure Scan Rules

---

addOns/requester/CHANGELOG.md
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ManualRequestEditorPanel.java
addOns/requester/src/main/resources/org/zaproxy/zap/extension/requester/resources/Messages.properties

Catch exception that might be thrown when saving the request panel and
inform the user.
Part of zaproxy/zaproxy#4235.

requester: warn on malformed messages

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/RelativePathConfusionScanRule.java
addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRuleUnitTest.java

- pscanrules : ApplicationErrorScanRule > Will not alert on web assembly responses (web assembly is likely to contain error strings). Added Unit Test and change note in CHANGELOG.
- ascanrulesBeta : RelativePathConfusionScanRule > No longer treats 'href="#"' as a relative path. Added change note to CHANGELOG.

Scan Rule Tweaks

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ExtensionGraphQl.java

As discussed on IRC, 
fix bug where the "GraphQL Support.js" script
was enabled when ZAP was restarted even
if it had been disabled and saved before.

graphql: Save Script to Config

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderEventPublisher.java

Unregister the event publisher when the extension is unloaded otherwise
it would lead to a leak and exceptions after updating the add-on.

spiderAjax: unregister event publisher

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/OptionsAjaxSpider.java

Persist the state of "Remove Without Confirmation" of non-default
elements to click.

spiderAjax: persist option state, prepare release

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/XxeScanRule.java
addOns/ascanrulesBeta/src/main/resources/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/XxeScanRuleUnitTest.java

Extracted XXE Local File Reflection and Local File Inclusion to separate methods to enable unit testing.
Removed the check to parse response only when the status code is 200. 
Response is now parsed for XXE reflection/inclution regardless of the status code.
Added unit tests.
Closes zaproxy/zaproxy#6203

6203: Remove status code check in XXE, extract Local File Reflection and Local File Inclusion

---

addOns/soap/CHANGELOG.md
addOns/soap/soap.gradle.kts
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/ExtensionImportWSDL.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanRule.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPXMLInjectionActiveScanRule.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SitesTreeHelper.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SoapMessageFactory.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/WSDLCustomParser.java
addOns/soap/src/main/resources/org/zaproxy/zap/extension/soap/resources/Messages.properties
addOns/soap/src/main/zapHomeFiles/scripts/scripts/variant/SOAP Support.js
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/Sample.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/SitesTreeHelperTestCase.java

- Add node names in the sites tree via a variant script.
- Fix a bug where some classes were not being loaded correctly with Java 9+.
- Resolves zaproxy/zaproxy#1867.

SOAP Add-on Sites Tree Fix

---

addOns/retire/retire.gradle.kts
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
addOns/retire/src/test/java/org/zaproxy/addon/retire/RetireScanRuleUnitTest.java
testutils/src/main/java/org/zaproxy/zap/testutils/TestUtils.java

- retire.gradle.kts > Set compatibility as ZAP 2.10, and depend on ZAP 2.10 snapshot.
- RetireScanRule > Leverage new request/response header isCss() methods, and CustomPages.Type.OK_200 handling.
- RetireScanRuleUnitTest > Additional coverage.
- TestUtils > Changed to accomodate newer core logging infrastructure.

retire & testutils: Adapt to 2.10 core enhancements

---

addOns/encoder/CHANGELOG.md
addOns/encoder/encoder.gradle.kts
addOns/encoder/src/main/resources/org/zaproxy/addon/encoder/resources/Messages.properties

Part of zaproxy/zaproxy#5996
- Build file set ZAP version 2.10.
- Remove "Advanced" from resource key values.
- Make resource key value pairs consistent (equals sign with no spaces on either side).

encoder: Adapt to 2.10 core

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/zapHomeFiles/scripts/scripts/variant/GraphQL Support.js
addOns/soap/src/main/zapHomeFiles/scripts/scripts/variant/SOAP Support.js

As discussed on IRC. 
Fix a bug where sites tree entries were not showing parameters because of the scripts.
(The changelog for the soap add-on was not updated because the script was added only recently .)

graphql, soap: script updates

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/InPageBannerInfoLeakScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SiteIsolationScanRule.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/InPageBannerInfoLeakScanRuleUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SiteIsolationScanRuleTest.java

- Update scan rule unit tests to account for the changes.

pscanrulesAlpha: Update to take advantage of 2.10 core

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/pscanrulesBeta.gradle.kts
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ContentSecurityPolicyMissingScanRule.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/ContentSecurityPolicyMissingScanRuleUnitTest.java

- ContentSecurityPolicyMissingScanRule - Adjust risk to medium to align with other CSP findings. Adjust confidence to High, it's pretty solid whether or not headers exist.
- ContenSecurityPolicyMissingScanRuleUnitTest - Updated to assert new values.
- CHANGELOG - Change note added.
Fixes zaproxy/zaproxy#6301

pscanrulesBeta: CSP Missing scan rule adjust risk and confidence

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/pscanrulesBeta.gradle.kts
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/InsecureFormLoadScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/InsecureFormPostScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledCharsetScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledHTMLAttributesScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledJavascriptEventScanRule.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/InsecureFormLoadScanRuleUnitTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/InsecureFormPostScanRuleUnitTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledCharsetScanRuleUnitTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledHTMLAttributesScanRuleUnitTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledJavascriptEventScanRuleUnitTest.java

- Update scan rule unit tests to account for the changes.
Part of zaproxy/zaproxy#9

pscanrulesBeta: Update to take advantage of 2.10 core

---

addOns/graaljs/graaljs.gradle.kts
addOns/graaljs/src/main/java/org/zaproxy/zap/extension/graaljs/PacScript.java
addOns/graaljs/src/test/java/org/zaproxy/zap/extension/graaljs/PacScriptUnitTest.java
addOns/graaljs/src/test/resources/org/zaproxy/zap/extension/graaljs/dateRange.pac
addOns/graaljs/src/test/resources/org/zaproxy/zap/extension/graaljs/dnsDomainIs.pac
addOns/graaljs/src/test/resources/org/zaproxy/zap/extension/graaljs/dnsDomainLevels.pac
addOns/graaljs/src/test/resources/org/zaproxy/zap/extension/graaljs/dnsResolve.pac
addOns/graaljs/src/test/resources/org/zaproxy/zap/extension/graaljs/isInNet.pac
addOns/graaljs/src/test/resources/org/zaproxy/zap/extension/graaljs/isPlainHostName.pac
addOns/graaljs/src/test/resources/org/zaproxy/zap/extension/graaljs/isResolvable.pac
addOns/graaljs/src/test/resources/org/zaproxy/zap/extension/graaljs/localHostOrDomainIs.pac
addOns/graaljs/src/test/resources/org/zaproxy/zap/extension/graaljs/myIpAddress.pac
addOns/graaljs/src/test/resources/org/zaproxy/zap/extension/graaljs/shExpMatch.pac
addOns/graaljs/src/test/resources/org/zaproxy/zap/extension/graaljs/timeRange.pac
addOns/graaljs/src/test/resources/org/zaproxy/zap/extension/graaljs/weekdayRange.pac

Move `PacScript` and related resources from core to use the Graal
JavaScript engine (Nashorn is deprecated and no longer present in newer
Java versions).
Tweak `PacScript` to work with Graal JavaScript engine:
- Use `Object` when parsing times/dates to allow to consume `String`
and `Integer` values;
- Use `GraalSandbox`, still not tuned.
Related to zaproxy/zaproxy#265 and zaproxy/zaproxy#4851.
Removed from core in zaproxy/zaproxy#6331.

graaljs: add PacScript

---

addOns/browserView/CHANGELOG.md
addOns/browserView/src/main/java/org/zaproxy/zap/extension/browserView/ExtensionHttpPanelBrowserView.java

- ExtensionHttpPanelBroswerView > In regular use just log the exception's `getMessage()` value. If debug is enabled log the whole stack trace as well.
Related to zaproxy/zaproxy#6339

BrowserView reduce missing JavaFX logging in regular use

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/ascanrules.gradle.kts
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/BufferOverflowScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrlfInjectionScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/DirectoryBrowsingScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/FormatStringScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ParameterTamperScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/RemoteFileIncludeScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureWebInfScanRule.java

* CrlfInjectionScanRule > Remove un-necessary commented code block.

Update ascanrules to take advantage of 2.10 core

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/HiddenFilesScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/HttpsAsHttpScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/InsecureHttpMethodScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/IntegerOverflowScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/PaddingOracleScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/RemoteCodeExecutionCve20121823ScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SessionFixationScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureCve20121823ScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureGitScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureSvnScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/RemoteCodeExecutionCve20121823ScanRuleUnitTest.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureCve20121823ScanRuleUnitTest.java

- Fix naming mistake on RCE and Source Code Disclosure CVE-2012-1823 scan rules (the leading 2 on the year had been dropped).

Update ascanrulesBeta to take advantage of 2.10 core

---

addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/DataGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiGeneratedCookieValuesTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/openapi_generated_cookie_values.yaml

Use `JohnDoe` instead of `"John Doe"`, the latter is not a valid cookie
value.
Per comments in zaproxy/zaproxy#6045.

openapi: generate valid value for string cookies

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/Application.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/PopupMenuEvidence.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScannerUnitTest.java
addOns/wappalyzer/src/test/resources/org/zaproxy/zap/extension/wappalyzer/apps.json
addOns/wappalyzer/wappalyzer.gradle.kts

Part of zaproxy/zaproxy#6180
- Added necessary infrastructure/code.
- Added unit tests.
- Add CHANGELOG notes.
- Rolled version identifier to 21.0.0 (since now targeting ZAP 2.10,
which is somewhat breaking).

wappalyzer: Add support for CSS inspection/patterns

---

addOns/domxss/CHANGELOG.md
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java
addOns/domxss/src/test/resources/org/zaproxy/zap/extension/domxss/CancelButton.html

The goal of this MR is to have the DomXSS Plugin click on additional buttons within the DOM to see if XSS can be triggered.
The script is hitting buttons like this: `<button onclick="onCancelClicked()">Click me</button>` , but doesn't test buttons formatted like this: but not like this `<button type="button">Cancel</button>`
Tested against an internal site, screenshot here:

Include button elements in DOM XSS Scan Rule

---

addOns/soap/CHANGELOG.md
addOns/soap/soap.gradle.kts
addOns/soap/src/main/javahelp/org/zaproxy/zap/extension/soap/resources/help/contents/soap.html
addOns/soap/src/main/javahelp/org/zaproxy/zap/extension/soap/resources/help/helpset.hs
addOns/soap/src/main/javahelp/org/zaproxy/zap/extension/soap/resources/help/toc.xml

Rename the add-on to "SOAP Support", it's not just a scanner, it allows
to import and spider.
Update the help accordingly.
Update minimum ZAP version to 2.10.0.

soap: tweak name/help and prepare release

---

addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/manualsend/WebSocketPanelSender.java
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/utility/WebSocketUtils.java
addOns/websocket/src/test/java/org/zaproxy/zap/extension/websocket/pscan/WebSocketPassiveScannerManagerUnitTest.java
addOns/websocket/websocket.gradle.kts

Set empty list for ignore rules to avoid NPE when handling the
breakpoints.
Update ZAP to 2.10.0, required to call the setter.
Address deprecations in ZAP 2.10.0:
- Remove usage of `Encoder`;
- Call `SessionStructure#addPath` with the `model`.
Remove log set up in the tests, calling method that does not exist (per
Log4j major update in core).

websocket: fix NPE when handling breakpoints

---

addOns/encoder/CHANGELOG.md
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/contents/encoder.html

Remove "Advanced" in help page, no longer needed.

encoder: help tweak

---

testutils/src/main/java/org/zaproxy/zap/testutils/websocket/server/NanoWebSocketConnection.java

Sync ping to make sure the internal state is consistent when checking
if expected pong was received.
Addresses intermittent failure in WebSocket ping/pong test.

testutils: sync ping in WebSocket test server

---

testutils/testutils.gradle.kts

Addresses UnitTest failures with Eclipse 2020-12.
Upgrade testutils to use jupiterVersion 5.7.0, and org.mockito:mockito-junit-jupiter 3.6.28. (JUnit 5.7.0 to address a 0local test failure issue in Eclipse 2020-12, and mockito just as a dependency maintenance activity.)
```console
java.lang.NoClassDefFoundError:
org/junit/platform/commons/util/ClassNamePatternFilterUtils
at org.junit.platform.launcher.core.LauncherFactory.loadAndFilterTestExecutionListeners(LauncherFactory.java:122)
at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:108)
at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:75)
at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.<init>(JUnit5TestLoader.java:34)
at …
```

testutils: Upgrade test libraries to address UnitTest failures

---

addOns/imagelocationscanner/CHANGELOG.md
addOns/imagelocationscanner/imagelocationscanner.gradle.kts
addOns/imagelocationscanner/src/main/java/org/zaproxy/zap/extension/imagelocationscanner/ImageLocationScanRule.java
addOns/imagelocationscanner/src/test/java/org/zaproxy/zap/extension/imagelocationscanner/ImageLocationScanRuleUnitTest.java

- Update build file, and CHANGELOG.
- ImageLocationScanRule > Upgrade to more recent Alert and parent handling, and leverage newer logging infrastructure.

ImageLocationScanner: Use core 2.10

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
addOns/wappalyzer/wappalyzer.gradle.kts

- Remove use of 2.10 snapshot in build file.

Wappalyzer: Use Log4j 2.x

---

addOns/ascanrules/ascanrules.gradle.kts
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts
addOns/pscanrules/pscanrules.gradle.kts
addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts
addOns/pscanrulesBeta/pscanrulesBeta.gradle.kts
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/ServletParameterPollutionScanRuleUnitTest.java
addOns/retire/retire.gradle.kts
addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/spiderAjax.gradle.kts
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderTarget.java

Use main version instead of snapshots, no longer available.

Compile add-ons with main ZAP release

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/BufferOverflowScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CodeInjectionScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CommandInjectionScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ElmahScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ExternalRedirectScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/FormatStringScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ParameterTamperScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PersistentXssPrimeScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PersistentXssScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PersistentXssSpiderScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PersistentXssUtils.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/RemoteFileIncludeScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ServerSideIncludeScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureWebInfScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java

- Update build file, CHANGELOGS, and change code to use updated logging infrastructure.
- Remove use of 2.10 snapshot in build files where it is no longer necessary.

ascanrules: Use Log4j 2.x

---

addOns/domxss/domxss.gradle.kts
addOns/webdrivers/webdriverlinux/CHANGELOG.md
addOns/webdrivers/webdriverlinux/src/main/javahelp/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
addOns/webdrivers/webdrivermacos/CHANGELOG.md
addOns/webdrivers/webdrivermacos/src/main/javahelp/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
addOns/webdrivers/webdrivers.gradle.kts
addOns/webdrivers/webdriverwindows/CHANGELOG.md
addOns/webdrivers/webdriverwindows/src/main/javahelp/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html

Update geckodriver to 0.29.0.
Add release dates and links to tags.
Update the geckodriver version used for domxss tests.

webdrivers: update geckodriver, prepare releases

---

addOns/accessControl/CHANGELOG.md
addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/view/ContextAccessControlPanel.java

- CHANGELOG > Add change entry.
- ContextAccessControlPanel > Don't set font color "default" (inherited) entries.
Fixes zaproxy/zaproxy#6397

accessControl: Fix font color handling in non-default LaFs

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/BigRedirectsScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ContentSecurityPolicyMissingScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/HashDisclosureScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/LinkTargetScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/RetrievedFromCacheScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ServerHeaderInfoLeakScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ServletParameterPollutionScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/StrictTransportSecurityScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledOpenRedirectScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/XBackendServerInformationLeakScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/XChromeLoggerDataInfoLeakScanRule.java

- Remove use of 2.10 snapshot in build file.

pscanrulesBeta: Use Log4j 2.x

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureSuspiciousCommentsScanRule.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureSuspiciousCommentsScanRuleUnitTest.java

The alert did not added the offending line as evidence, changed the code to add each offending line as a single alert

chore: added evidence to suspicious comment scan rule

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/zapHomeFiles/xml/application_errors.xml
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRuleBundledStringsUnitTest.java

- application_errors.xml > Added Express error string pattern.
- ApplicationErrorScanRuleBundledStringsUnitTest > Add Unit Test which uses string patterns from the bundled file.
Fixes zaproxy/zaproxy#6412

pscanrules: Added Express Error Pattern

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/Application.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/PopupMenuEvidence.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParserUnitTest.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScannerUnitTest.java
addOns/wappalyzer/src/test/resources/org/zaproxy/zap/extension/wappalyzer/apps.json
addOns/wappalyzer/wappalyzer.gradle.kts

- Added necessary code.
- Added unit tests.
- Added CHANGELOG notes.
- Used Jsoup as dom selector as Jericho lacks jquery-like selector capabilities.
Fixes zaproxy/zaproxy#6180
Signed-off-by: bettercalln1ck bettercallnck6303@gmail.com

wappalyzer: Add support for Dom inspection/patterns

---

addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/LinkTargetScanRule.java

Use the correct logger class in `LinkTargetScanRule`.

pscanrulesBeta: correct logger

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureSuspiciousCommentsScanRule.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureSuspiciousCommentsScanRuleUnitTest.java

The last set of changes to this rule exposed a core bug:
https://github.com/zaproxy/zaproxy/issues/6421
Examining the alerts raised in that case showed that the info included
was actually not that useful.
An issue would be raise for every instance of a suspicious string in a
page, and the evidence was the relevant page element, which for scripts
could be very large. And scripts could trigger the bug above ;)
This PR changes the rule to only raise one alert per suspicious string
instance per page - if there are more than one instance then it gives
the count. The evidence is just the string matched while the 'other'
field now contains the first 128 bytes of the first relevant element.
Screen shots to be included...
Also prepare add-on for release so that we're less likely to hit the
core …

Suspicious Comments rule alert tweaks + release

---

addOns/authstats/CHANGELOG.md
addOns/authstats/authstats.gradle.kts
addOns/authstats/src/main/java/org/zaproxy/zap/extension/authstats/ExtensionAuthStats.java

authstats: Use Log4j 2.x

---

addOns/beanshell/CHANGELOG.md
addOns/beanshell/beanshell.gradle.kts
addOns/beanshell/src/main/java/org/zaproxy/zap/extension/beanshell/BeanShellConsoleFrame.java

- As a clean code activity remove unused private method `BeanShellConsoleFrame.getExtension()`.

beanshell: Use Log4j 2.x

---

addOns/frontendscanner/frontendscanner.gradle.kts
addOns/frontendscanner/src/main/java/org/zaproxy/zap/extension/frontendscanner/ExtensionFrontEndScanner.java
addOns/frontendscanner/src/main/java/org/zaproxy/zap/extension/frontendscanner/FrontEndScannerAPI.java
addOns/frontendscanner/src/main/java/org/zaproxy/zap/extension/frontendscanner/FrontEndScannerProxyListener.java

- Address deprecation of ParameterParser.getParams, with the upgrade to target 2.10.

frontendscanner: Use Log4j 2.x

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/ascanrules.gradle.kts
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ElmahScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/ElmahScanRuleUnitTest.java
addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/AbstractHostFilePlugin.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/AbstractHostFilePluginUnitTest.java

- Updated commonlib to target 2.10 more specifically (now that 2.10 has been released).
- Added AbstractHostFilePlugin and UnitTest.
- Updated other commonlib classes to use Log4j 2.x infrastructure.
- Updated ElmanScanRule to leverage AbstractHostFilePlugin.
Fixes zaproxy/zaproxy#6133

commonlib: Add AbstractHostFilePlugin

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CsrfCountermeasuresScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CsrfCountermeasuresScanRuleUnitTest.java

In the report after a spider attack, the Anti-CSRF scanner 10202 prints the standard Anti-CSRF tokens and the scanned form's fields in the Other information section when no anti-CSRF token is found. The output can look like this:
No known Anti-CSRF token [anticsrf, CSRFToken, __RequestVerificationToken, csrfmiddlewaretoken, authenticity_token, OWASP_CSRFTOKEN, anoncsrf, csrf_token, _csrf, _csrfSecret] was found in the following HTML form: [Form 1: "tenant-status" "toggle-tenant-status" "woEnabled" "toggle-woEnabled" "campManagerEnabled" "toggle-campManagerEnabled" "conSpeechEnabled" "toggle-conSpeechEnabled" "webCallBackEnabled" "toggle-webCallBackEnabled" "cccEnabled" "toggle-cccEnabled" "sbrEnabled" "toggle-sbrEnabled" "multiMediaEnabled" "toggle-multiMediaEnabled" …

Sort form input names scanner 10202

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRule.java
addOns/ascanrules/src/main/javahelp/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRuleUnitTest.java

- PathTraversalScanRule > Only do "check 5" at Low Threshold, add "Check #" reference to Other info field (to facilitate future user inquiries).
- PathTraversalScanRuleUnitTests > Add assertions for Other info field.
- Messages.properties > Add Other info pair.
- CHANGELOG > Add change notes.
* Fixes zaproxy/zaproxy#4209
* Fixes zaproxy/zaproxy#6030
* Fixes zaproxy/zaproxy#6219
* Fixes zaproxy/zaproxy#6372
* Fixes zaproxy/zaproxy#6380

ascanrules: Path Traversal Check 5 and Other Info adjustments

---

addOns/importLogFiles/CHANGELOG.md
addOns/importLogFiles/importLogFiles.gradle.kts
addOns/importLogFiles/src/main/java/org/zaproxy/zap/extension/importLogFiles/ExtensionImportLogFiles.java
addOns/importLogFiles/src/main/java/org/zaproxy/zap/extension/importLogFiles/ImportLogAPI.java

importLogFiles: Use Log4j 2.x

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ExtensionGraphQl.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlApi.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlGenerator.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParam.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParser.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlSpider.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/HistoryPersister.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/Requestor.java

- Update CHANGELOG, and change code to use updated logging infrastructure.
- GraphQlApi > Removed un-used logger instantiation.

graphql: Use Log4j 2.x

---

addOns/jython/CHANGELOG.md
addOns/jython/jython.gradle.kts
addOns/jython/src/main/java/org/zaproxy/zap/extension/jython/JythonOptionsParam.java

jython: Use Log4j 2.x

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CrossDomainMisconfigurationScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CrossDomainScriptInclusionScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CsrfCountermeasuresScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureDebugErrorsScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureInUrlScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureReferrerScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureSuspiciousCommentsScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InsecureAuthenticationScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/UsernameIdorScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XDebugTokenScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XPoweredByHeaderInfoLeakScanRule.java

- Update CHANGELOG, and change code to use updated logging infrastructure.
- TimestampDisclosureScanRule shows a significant change because a try/catch was removed which was never/no-longer needed.

pscanrules: Use Log4j 2.x

---

addOns/importurls/CHANGELOG.md
addOns/importurls/importurls.gradle.kts
addOns/importurls/src/main/java/org/zaproxy/zap/extension/importurls/ExtensionImportUrls.java
addOns/importurls/src/main/java/org/zaproxy/zap/extension/importurls/ImportUrlsAPI.java

importUrls: Use Log4j 2.x

---

addOns/soap/CHANGELOG.md
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/WSDLFilePassiveScanRule.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/WSDLFilePassiveScanRuleTestCase.java

As @kingthorin told.
```
Should be as simple as:
- return baseURL.endsWith(".wsdl")
-                    || contentType.equals("text/xml")
-                    || contentType.equals("application/wsdl+xml");
+ return (baseURL.endsWith(".wsdl")
+                    && contentType.equals("text/xml"))
+                    || contentType.equals("application/wsdl+xml");
Or
- return baseURL.endsWith(".wsdl")
-                    || contentType.equals("text/xml")
-                    || contentType.equals("application/wsdl+xml");
+ return baseURL.endsWith(".wsdl")
+                    && (contentType.equals("text/xml")
+                    || contentType.equals("application/wsdl+xml"));
```
I made changes.
Fixes zaproxy/zaproxy/issues/6440
Signed-off-by: Aman Rawat <rawataman6525@gmail.com>

Correct detection of WSDL files

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testPlan-failOnErrorApplyingParameters.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testPlan-failOnWarningApplyingParameters.yaml

- Stop running when applyParameters encounters an error or warning and env:parameters:failOnError or env:parameters:failOnWarning is true.

automation: Stop plan when applyParameters fails

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRule.java
addOns/ascanrules/src/main/javahelp/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRuleUnitTest.java

As discussed via email, and in follow-up to recent wavsep runs.
- PathTraversalScanRule > Do check 5 at both LOW and MEDIUM threshold. (Which gives the user the option of setting Threshold HIGH to exclude it.)
- PathTraversalScanRuleUnitTest > Revised to accomodate modified logic.
- ascanrules.html > Updated threshold note.
- CHANGELOG > Updated change note.

ascanrules: Path Traveral rule further tweaks

---

addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/HistoryPersister.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/OpenApiSpider.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/ExtensionOpenApiAutomation.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJob.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/OperationHelper.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverter.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/BodyGenerator.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/ValueGenerator.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/network/Requestor.java
addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/contents/automation.html
addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/contents/openapi.html
addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/index.xml
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/openapi-max.yaml
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/openapi-min.yaml
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/HistoryPersisterUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJobUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/BodyGeneratorUnitTest.java

- Use Log4j 2.x (part of zaproxy/zaproxy#6376).
- Automation Framework Support Updates
- Add unit tests.
- Change params to camelCase.
- Other minor changes.

openapi: Updates

---

addOns/birtreports/CHANGELOG.md
addOns/birtreports/birtreports.gradle.kts
addOns/birtreports/src/main/java/org/zaproxy/zap/extension/birtreports/ExtensionBirtReports.java
addOns/birtreports/src/main/java/org/zaproxy/zap/extension/birtreports/ReportLastScan.java

Update build file, CHANGELOG, and change code to use updated logging infrastructure.

birtreports: Use Log4j 2.x

---

addOns/httpsInfo/CHANGELOG.md
addOns/httpsInfo/httpsInfo.gradle.kts
addOns/httpsInfo/src/main/java/org/zaproxy/zap/extension/httpsinfo/HttpsInfoOutputPanel.java

- Set minimum ZAP version to 2.10.
- Change from slf4j12 v1.7.6 (which was behind as a dependency) to up-to-date log4j-slf4j-impl v2.14.1
- Update CHANGELOG entry.

httpsinfo: Use Log4j 2.x

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRuleUnitTest.java

- CHANGELOG > Added change note
- TimestampDisclosureScanRule > Added "Report-To" and "NEL" as headers to ignore.
- TimestampDisclosureScanRuleUnitTest > Add test for number of excluded headers, and that the array contains the newly added headers.
Fixes zaproxy/zaproxy#6493

pscanrules: Timestamp Disclosure ignore further headers

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/DirectoryBrowsingScanRule.java
addOns/jruby/CHANGELOG.md
addOns/jruby/src/main/zapHomeFiles/scripts/templates/active/Active default template.rb
addOns/jruby/src/main/zapHomeFiles/scripts/templates/passive/Passive default template.rb
addOns/jython/CHANGELOG.md
addOns/jython/src/main/zapHomeFiles/scripts/templates/active/Active default template.py
addOns/jython/src/main/zapHomeFiles/scripts/templates/passive/Passive default template.py
addOns/pscanrulesAlpha/CHANGELOG.md

Update code, changelog, and script templates to use confidence instead
of reliability.
Update/add confidence values in script templates.

Rename reliability to confidence

---

addOns/alertFilters/CHANGELOG.md
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/DialogAddAlertFilter.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PersistentXssUtils.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureWebInfScanRule.java
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/GraphQlParserUnitTest.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/UsernameIdorScanRule.java
addOns/replacer/CHANGELOG.md
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/OptionsReplacerPanel.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
addOns/revisit/src/main/java/org/zaproxy/zap/extension/revisit/RevisitDialog.java
addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/CommandPanel.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ConsolePanel.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/OutputPanel.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ScriptsListPanel.java
addOns/soap/CHANGELOG.md
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPMsgConfig.java
addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLiPayloadManager.java
addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/utility/WebSocketUtils.java

- pscanrules > UsernameIdorScanRule make DEFAULT_USERNAMES unmodifiable. (This addresses "Mutable fields should not be 'public static'")
- ascanrules
- PersistentXssUtils make prefix and postfix constants final. (This addresses two findings for each const: "'public static' fields should be constant" and "Class variable fields should not have public accessibility")
- SourceCodeDisclosureWebInfScanRule > When delete() is called log a debug message if not successful. (This addresses "Return values should not be ignored when they contain the operation status code")
- websocket > WebSocketUtils, save and re-use Random.
- sqliplugin > SQLiPayloadManager, save and re-use Random.
- graphql > GraphQlParserUnitTests, instantiate the GraphQlParser before the assertion, so that the assertion is …

Fix various issues identified via SAST (Sonar)

---

addOns/browserView/src/main/java/org/zaproxy/zap/extension/browserView/BrowserViewParam.java
addOns/bruteforce/CHANGELOG.md
addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/BruteForceParam.java
addOns/formhandler/src/main/java/org/zaproxy/zap/extension/formhandler/FormHandlerParam.java
addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/FuzzOptions.java
addOns/invoke/src/main/java/org/zaproxy/zap/extension/invoke/InvokeParam.java
addOns/jython/src/main/java/org/zaproxy/zap/extension/jython/JythonOptionsParam.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerParam.java
addOns/reveal/src/main/java/org/zaproxy/zap/extension/reveal/RevealParam.java
addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/SeleniumOptions.java
addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParam.java
addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestParam.java

Use the core methods that already handle conversion exceptions when
reading the properties.

Use core helper methods to read properties

---

addOns/replacer/CHANGELOG.md
addOns/replacer/replacer.gradle.kts
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ExtensionReplacer.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerParam.java

replacer: update ZAP to 2.10.0

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderAPI.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderDialog.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParam.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderTarget.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/HttpPrefixUriValidator.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/PopupMenuAjaxSite.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderPanel.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java

spiderAjax: use Log4j 2 APIs

---

addOns/sequence/CHANGELOG.md
addOns/sequence/sequence.gradle.kts
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/ExtensionSequence.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/SequenceAscanPanel.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/SequencePopupMenuItem.java

sequence: update ZAP to 2.10.0

---

addOns/simpleexample/simpleexample.gradle.kts
addOns/simpleexample/src/main/java/org/zaproxy/zap/extension/simpleexample/ExtensionSimpleExample.java
addOns/simpleexample/src/main/java/org/zaproxy/zap/extension/simpleexample/SimpleExampleAPI.java

simpleexample: update ZAP to 2.10.0

---

addOns/selenium/CHANGELOG.md
addOns/selenium/selenium.gradle.kts
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/Browser.java
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/PopupMenuItemOpenInBrowser.java

selenium: update ZAP to 2.10.0

---

addOns/savexmlmessage/CHANGELOG.md
addOns/savexmlmessage/savexmlmessage.gradle.kts
addOns/savexmlmessage/src/main/java/org/zaproxy/zap/extension/savexmlmessage/PopupMenuSaveXMLMessage.java

savexmlmessage: update ZAP to 2.10.0

---

addOns/tlsdebug/CHANGELOG.md
addOns/tlsdebug/src/main/java/org/zaproxy/zap/extension/tlsdebug/HttpsCallerLauncher.java
addOns/tlsdebug/src/main/java/org/zaproxy/zap/extension/tlsdebug/TlsDebugPanel.java
addOns/tlsdebug/tlsdebug.gradle.kts

tlsdebug: update ZAP to 2.10.0

---

addOns/reveal/CHANGELOG.md
addOns/reveal/reveal.gradle.kts
addOns/reveal/src/main/java/org/zaproxy/zap/extension/reveal/ExtensionReveal.java

reveal: update ZAP to 2.10.0

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/PiiScanRule.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/PiiScanRuleUnitTest.java

- PiiScanRule > Use core isCss() utility methods, return early if either is true. Added a utility method that removes STYLE elements and attributes prior to the scan rule looking for Pii.
- PiiScanRuleUnitTest > Add tests to assert the updated behavior.
Fixes zaproxy/zaproxy#6288

PscanrulesBeta: PII Scan Rule ignore CSS and Styles

---

addOns/directorylistv1/CHANGELOG.md
addOns/directorylistv1/directorylistv1.gradle.kts
addOns/directorylistv2_3/CHANGELOG.md
addOns/directorylistv2_3/directorylistv2_3.gradle.kts
addOns/directorylistv2_3_lc/CHANGELOG.md
addOns/directorylistv2_3_lc/directorylistv2_3_lc.gradle.kts
addOns/fuzzdb/CHANGELOG.md
addOns/fuzzdb/fuzzdb.gradle.kts
addOns/svndigger/CHANGELOG.md
addOns/svndigger/svndigger.gradle.kts

directorylists, fuzzdb, svndigger: update ZAP

---

addOns/bruteforce/CHANGELOG.md
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/Manager.java
addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/BruteForce.java

Change `Manager` to allow to set a custom user-agent.
Change `BruteForce` to set the user-agent defined in ZAP.
Part of zaproxy/zaproxy#173.

bruteforce: use User-Agent defined in ZAP

---

addOns/coreLang/CHANGELOG.md
addOns/coreLang/coreLang.gradle.kts
addOns/graaljs/CHANGELOG.md
addOns/graaljs/graaljs.gradle.kts
addOns/groovy/groovy.gradle.kts
addOns/highlighter/CHANGELOG.md
addOns/highlighter/highlighter.gradle.kts
addOns/jruby/jruby.gradle.kts
addOns/jsonview/CHANGELOG.md
addOns/jsonview/jsonview.gradle.kts
addOns/kotlin/CHANGELOG.md
addOns/kotlin/kotlin.gradle.kts
addOns/onlineMenu/CHANGELOG.md
addOns/onlineMenu/onlineMenu.gradle.kts
addOns/regextester/CHANGELOG.md
addOns/regextester/regextester.gradle.kts
addOns/tips/CHANGELOG.md
addOns/tips/tips.gradle.kts
addOns/treetools/CHANGELOG.md
addOns/treetools/treetools.gradle.kts

Update ZAP to 2.10.0 on remaining add-ons

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRuleUnitTest.java

- TimestampDisclosureScanRule > Now checks if the request/response is related to fonts and skips if so.
- TimestampDisclosureScanRuleUnitTest > Added new tests to assert the new behavior.
Fixes zaproxy/zaproxy#6274
Reference resources:
- https://www.w3schools.com/css/css3_fonts.asp
- https://en.wikipedia.org/wiki/Web_Open_Font_Format
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

pscanrules: Don't look for timestamps in fonts

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/EnvFileScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/EnvFileScanRuleUnitTest.java
addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/AbstractAppFilePlugin.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/AbstractAppFilePluginUnitTest.java

- ascanrulesBeta/EnvFileScanRule > Added overridden isFalsePositive method that does a simple content check.
- ascanrulesBeta/EnvFileScanRuleUnitTest > Added overridden test methods to assert the rule specific behavior.
- ascanrulesBeta/CHANGELOG > Added change note.
* commonlib/AbstractAppFilePlugin > Relocate "isFalsePositive" check to be in the valid (200'ish) response block (obviously content or FP checks are unlikely to be successful in Unauthorized or Forbidden responses).
* commonlib/AbstractAppFilePluginUnitTest > Change visibility of "createHandler" to protected (from private).
* commoblib/CHANGELOG > Added change reference.
Note I locally ran other uses of AbstractAppFilePluginUnitTest to ensure the changes didn't negatively impact other scan rules.
Fixes zaproxy/zaproxy#6099 …

ascanrulesBeta: Add simple .env file scan rule content check

---

addOns/zest/CHANGELOG.md
addOns/zest/zest.gradle.kts

The add-on is required to work with Zest scripts.
Fix zaproxy/zaproxy#2656.

zest: depend on scritps add-on

---

addOns/addOns.gradle.kts

Exclude Log4j 1.x when compiling to prevent usage of old API.

Prevent usage of Log4j 1.x by add-ons

---

addOns/addOns.gradle.kts

Use latest ZAP version to generate the ZAP API of the add-ons.

Generate ZAP API with ZAP 2.10.0

---

testutils/src/main/java/org/zaproxy/zap/testutils/TestUtils.java
testutils/src/main/resources/log4j2-test.properties
testutils/testutils.gradle.kts

Compile with 2.10.0.
Address deprecations.
Use Log4j2 configuration file.
Exclude Log4j 1.x when compiling to prevent usage of old API.

testutils: update ZAP to 2.10.0

---

addOns/beanshell/CHANGELOG.md
addOns/beanshell/src/main/java/org/zaproxy/zap/extension/beanshell/BeanShellConsoleFrame.java
addOns/beanshell/src/main/java/org/zaproxy/zap/extension/beanshell/ExtensionBeanShell.java

BeanShellConsoleFrame & ExtensionBeanShell > Stop handling unused `Extension` variable, remove unnecessary constructor. 
ExtensionBeanShell > Use no-arg constructor.
CHANGELOG > Added maintenance note.

BeanShell Addon - Tweaks

---

addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationEnvironment.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-addons.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-ascan.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-pscanconf.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-pscanwait.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-spider.html
addOns/reports/CHANGELOG.md
addOns/reports/reports.gradle.kts
addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/ExtensionReportAutomation.java
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/create.html
addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/Messages.properties
addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/report.html
addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/template.yaml
addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java

Part of https://github.com/zaproxy/zaproxy/issues/6483
This adds a new Passing Rules section to the HTML plus report:

Reporting: Support job specific data

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CharsetMismatchScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieSameSiteScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InsecureJsfViewStatePassiveScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ViewstateScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XContentTypeOptionsScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CharsetMismatchScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InsecureJsfViewStatePassiveScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ViewStateScanRuleUnitTest.java
addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/FeaturePolicyScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SiteIsolationScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScanRule.java
addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ContentSecurityPolicyMissingScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/InsecureFormLoadScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/InsecureFormPostScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/StrictTransportSecurityScanRule.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/ContentSecurityPolicyMissingScanRuleUnitTest.java

In all three pscanrules add-ons replace use of CWE-16 which is a category and shouldn't be referenced directly (per Mitre's guidance/documentation). [Update unit tests where necessary.]
In cases where a more specific CWE couldn't be identified, CWE-693 is now used (https://cwe.mitre.org/data/definitions/693.html):
```console
This weakness covers three distinct situations. A "missing" protection
mechanism occurs when the application does not define any mechanism against a certain
class of attack. An "insufficient" protection mechanism might provide some defenses
- for example, against the most common attacks - but it does not protect against
everything that is intended. Finally, an "ignored" mechanism occurs when a mechanism is
available and in active use within the product, but the …
```

pscanrules all: Discontinue use of CWE-16

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/TraceAxdScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/TraceAxdScanRuleUnitTest.java

- TraceAxdScanRule > Add overridden `isFalsePositive(HttpMessage)` method that performs a simple content check.
- TraceAxdScanRuleUnitTest > Add unit test to assert the new behavior.
- CHANGELOG  > Add change note.
Content strings are based on screenshots:
https://docs.microsoft.com/en-us/previous-versions/aspnet/bb386420(v=vs.100)
Fixes zaproxy/zaproxy#6517

ascanrulesBeta: trace.axd rule FP fix

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/XxeScanRule.java
addOns/ascanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/XxeScanRuleUnitTest.java
addOns/ascanrulesBeta/src/test/resources/org/zaproxy/zap/extension/ascanrulesBeta/xxescanrule/SampleXml.txt

Introduced functions to create payloads where only a certain specified tag value is changed. Depending on the attack strength, a number of such payloads are sent and their response is matched against local file patterns, which if matches raises an alert.Fixes zaproxy/zaproxy#6204

Improved the XXE Scan Rule to detect a possible XXE Local File Reflection Attack when XML is validated

---

addOns/exim/exim.gradle.kts
addOns/exim/src/main/java/org/zaproxy/addon/exim/AbstractPopupMenuSaveMessage.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/PopupMenuSaveRawMessage.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/PopupMenuSaveXmlMessage.java
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/Messages.properties

Reduce duplication for the original saverawmessage and savexmlmessage components now that they're in a single add-on. This creates an abstract class for the popup menus, and an output interface for processing content and actually writing to the file.

exim: De-duplicate first two components

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ExtensionZest.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestScriptWrapper.java

Keep mod count in `ZestScriptWrapper` to properly report changes done to
the scripts (to refresh cached ones).
Change `ExtensionZest` to update the mod count of the scripts when
changed.
Fix zaproxy/zaproxy#6558.

zest: track changes done to scripts

---

addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLInjectionScanRule.java

Catch HTTP exception instead (base class of redirect exception and URI
exception) to remove the usage of redirect exception class.
While other exceptions might be caught where previously wouldn't they
are caused by malformed response (like with the redirection).

sqliplugin: remove usage of redirect exception

---

addOns/webdrivers/webdrivermacos/CHANGELOG.md
buildSrc/src/main/java/org/zaproxy/gradle/tasks/DownloadWebDriver.java

Exclude aarch64 when obtaining the download URLs of geckodriver to
bundle the one with the correct architecture.
Prepare release of the add-on.
Fix zaproxy/zaproxy#6543.

webdrivermacos: bundle correct geckodriver

---

addOns/reports/CHANGELOG.md
addOns/reports/reports.gradle.kts

Add bridge for slf4j, used by a dependency.
Reported in zaproxy/zaproxy#6524.

reports: add logging bridge

---

addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportParam.java

Use the core methods that already handle conversion exceptions when
reading the configurations.

reports: use core helper methods to read configs

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/dialogs/EditScriptDialog.java

Change Edit Script dialogue to not show hidden engines, which are not
actual script engines (e.g. avoid showing " : Null").

scripts: do not show hidden script engines

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java

Use UTF-8 to write the reports, to prevent encoding issues.
Fix zaproxy/zaproxy#6561.

reports: do not rely on default encoding

---

addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosureScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/GitMetadata.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/InsecureHttpMethodScanRule.java

Replace usage of `HttpStatus` with `HttpStatusCode` to use constants
provided by core rather than a dependency.

ascanrulesBeta: use core constants

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/HashDisclosureScanRule.java
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/HashDisclosureScanRuleUnitTest.java

- HashDisclosureScanRule > Add necessary logic.
- HashDisclosureScanRuleUnitTest > Add tests to assert the new behavior.
- pscanbeta.html > Add note to help.
Fixes zaproxy/zaproxy#6071

pscanrulesBeta: Hash Disclosure Skip JS unless Threshold Low

---

addOns/accessControl/CHANGELOG.md
addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/AccessControlAlertsProcessor.java
addOns/domxss/CHANGELOG.md
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/PopupUseScriptAsAuthenticationScript.java
addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ExtensionZest.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestRecordScriptDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/menu/ZestSurroundWithPopupMenu.java

- accessControl > Replaced two prints with debug logging. Fixed a typo in the CHANGELOG and added maintenance entry.
- domxss > Replaced one print with debug logging. CHANGELOG added maintenance entry.
- pscanrulesAlpha > Removed one commented print.
- scripts > Replaced one print with debug logging. (Unreleased section already has maint note.)
- zest > Replaced three prints with debug logging. CHANGELOG added maintenance entry.

improvement: various add-ons - stop using printStackTrace

---

addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/XxeScanRule.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/PopupMenuSaveXmlMessage.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRuleUnitTest.java

- PopupMenuSaveXmlMessage > Use a doc builder with XXE disabled.
- TimestampDisclosureScanRule > Use a non-capturing group to ensure operator precedence (\z should apply to all, not only .otf). Add a Unit Test to check the pattern behavior.
- XxeScanRule > Don't bother passing `payload` to `localFileReflectionAttack(HttpMessage)` which is simply overwritten.
CHANGELOGs weren't updated as none of the related changes have been released.

fix: SAST Items

---

addOns/addOns.gradle.kts

Always use Java 8 when building for ZAP releases as the core build now
requires running with Java 11, which could lead to wrong compilation.

Use Java 8 when building for ZAP releases

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRule.java
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureFileInclusionScanRule.java
addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/DiceMatcher.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/DiceMatcherUnitTest.java

The LdapInjectionScanRule and SourceCodeDisclosureFileInclusionScanRule
were modified to make use of the new DiceMatcher to calculate match
percentage between two strings. Added test and update the Changelogs.
Takes care of two out of the three rules reported as having poor performance in zaproxy/zaproxy#6515

Introduce DiceMatcher to replace HirshbergMatcher in scan rules

---

addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/AccessControlAlertsProcessor.java

The comments to enable/disable the formatter no longer have any effect.

accessControl: remove formatter related comments

---

.github/workflows/ci.yml

To cancel in-progress builds when a force push is done and a ci workflow is already running.
Ref: 
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
- https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context

improve: ci workflow add concurrency grouping

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/zapHomeFiles/scripts/templates/extender/Copy as curl command menu.js

- Menu item is now preceded by a separator.
- Tweaked the capitalization of the menu item (title caps, curl was purposefully left lowercase and that's how it's usually presented,
despite being a name).
<sub>Ignore the XML/HAR part, an old build of exim was installed.</sub>

scripts: improve: Copy as curl Command extender JavaScript script

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ParameterTamperScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/ParameterTamperScanRuleUnitTest.java
addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/CorsScanRule.java
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureSvnScanRule.java
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
addOns/formhandler/src/main/java/org/zaproxy/zap/extension/formhandler/OptionsFormHandlerPanel.java
addOns/importLogFiles/CHANGELOG.md
addOns/importLogFiles/src/main/java/org/zaproxy/zap/extension/importLogFiles/ImportLogAPI.java
addOns/invoke/src/main/java/org/zaproxy/zap/extension/invoke/OptionsInvokePanel.java
addOns/portscan/CHANGELOG.md
addOns/portscan/src/main/java/org/zaproxy/zap/extension/portscan/OptionsPortScanPanel.java
addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScanRule.java
addOns/saml/src/main/java/org/zaproxy/zap/extension/saml/SAMLConfiguration.java

- ascanrules
- ParameterTamperScanRule - Change VBScript pattern so use non-capturing groups and put repetition modifiers on the group instead of within the group. (CHANGELOG added change note, also added unit test.)
- ascanrulesBeta
- SourceCodeDisclosureSvnScanRUle - Use the return value from deleting the temporary sqlite file, log a warning if the delete isn't successful.
- ascanrulesAlpha
- CorsScanRule - Use .equals for string equality conditionals.
- domxss
- DomXssScanRule - Make public arrays protected.
- formhandler
- OptionsFormHandlerPanel - Remove initialize and add content to constructor (to not overlap with parents method), remove pointless javadoc.
- importLogFiles
- ImportLogAPI - Don't explicitly create the file, allow it to be created while writing.
- invoke
- …

improve: various add-ons more SAST (sonar) fixes

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CodeInjectionScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CodeInjectionScanRuleUnitTest.java

- Reduce try/catch nesting (SocketException is a child of IOException).
- Remove some seemingly pointless comments.
- Return logical comparisons directly instead of within another conditional.
- Use simpler or more realistic math operations.
- Update unit test to account for newer math/behavior.

improve: ascanrules: Address SAST (sonar) findings in CodeInjection Rule

---

addOns/exim/src/main/java/org/zaproxy/addon/exim/AbstractPopupMenuSaveMessage.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/EximFileChooser.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarImporter.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/PopupMenuItemSaveHarMessage.java

- Remove static modifier on enum, which is implicitly static.
- Return logical comparisons directly instead of within another conditional.
- Add private constructor to utility class (to prevent java from implicitly offering a public constructor).

improve: exim: Address SAST (sonar) findings

---

addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanJobUnitTest.java

Change `ActiveScanJobUnitTest` to set up a temporary ZAP home to not
create home files under the repository.

automation: use temporary ZAP home for test

---

addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/DiceMatcher.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/DiceMatcherUnitTest.java

- Reduce cognitive complexity.
- Use .equals() for string comparison.
- Extract assignments from conditionals.
- Declare variables on separate lines.

improve: commonlib: DiceMatcher SAST (sonar) fixes

---

.github/workflows/ci.yml

Until we can find a solution that will work for both PRs and pushes/merges.
See https://github.com/zaproxy/zap-extensions/pull/2894

revert: ci workflow concurrency grouping

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/generator/FileStringPayloadGenerator.java
addOns/fuzz/src/test/java/org/zaproxy/zap/extension/fuzz/payloads/generator/FileStringPayloadGeneratorUnitTest.java

Correct loop break check when calculating payloads.
Keep the value of payloads counted until there's an error (e.g. charset
mismatch) to still report the number of payloads that can be actually
used.

fuzz: correct file payload count

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRuleUnitTest.java

- CacheControlScanRule > CSS traffic is now skipped unless threshold is Low. Clean code: Merged some conditional statements, removed some unused parameters in private methods, remove empty method for which there is now a default.
- CacheControlScanRuleUnitTest > Parameterized some tests. Added tests to assert new CSS behavior.
- pscanrules.html > Updated help to reflect current threshold handling details.
Fixes zaproxy/zaproxy#6596

fix: pscanrules: CacheControl scan rule CSS & Threshold adjustment

---

addOns/addOns.gradle.kts

The compile only projects were no longer being included as dependencies
in the required projects when importing/refreshing in Eclipse, after the
upgrade to Gradle 7.

Include compileOnly deps in Eclipse's classpath

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieSameSiteScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieSameSiteScanRuleUnitTest.java

- CookieSameSiteScanRule > Added logic to handle "none" SameSite value. Removed unused variable handling in a private method.
- CookieSameSiteScanRuleUnitTest > Added tests to assert the updated behavior. Clean code: Added a convenience method for message creation (to reduce code duplication). Added Given, When, Then comments and reduced unnecessary whitespace.
- Messages.properties > Added keys/values to support new "none" related alerts.
- pscanrules.html > Updated help entry.
Fixes zaproxy/zaproxy#6482

fix: pscanrules: Cookie SameSite Attribute "none" handling

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureWebInfScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java
addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRule.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjectionScanRule.java
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosureScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/GitMetadata.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/InsecureHttpMethodScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/RelativePathConfusionScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/RemoteCodeExecutionCve20121823ScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SessionFixationScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureCve20121823ScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureFileInclusionScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureGitScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureSvnScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionHypersonicScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionMyqlScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionOracleScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionPostgreScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionSqLiteScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/UsernameEnumerationScanRule.java
addOns/callgraph/src/main/java/org/zaproxy/zap/extension/callgraph/PopupMenuCallGraph.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InsecureAuthenticationScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InsecureAuthenticationScanRuleUnitTest.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/RetrievedFromCacheScanRule.java

Raise alerts and log with URIs in encoded form, decoding the URI might
change its meaning.
Use URIs in encoded form when checking if they are in context, that's
the expected form.

Use/report URIs in encoded form not decoded

---

addOns/bruteforce/bruteforce.gradle.kts
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/DirToCheck.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/HTMLparse.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/Manager.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/ProcessChecker.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/ProcessEnd.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/ReportWriter.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/Worker.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/BruteForceURLFuzz.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/BruteForceWorkGenerator.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/WorkerGenerator.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/WorkerGeneratorURLFuzz.java

Address the following warnings:
- Add missing type arguments.
- Add missing override annotations.
- Address deprecation.
- Remove casts no longer needed.
- Remove unused vectors.
Use default compiler flags (no more warnings).

bruteforce: address warnings

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/CookieUtils.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/CookieUtilsUnitTest.java

Take into account the timezones when checking if a cookie is expired.
Fix zaproxy/zaproxy#6550.

commonlib: correct cookie expiration calculation

---

addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java
addOns/wappalyzer/wappalyzer.gradle.kts

- A few log statements were missed during the Log4j 2.x conversion (or were introduced by overlapping PRs). These were fixed. (Relocated NumberFormatException handling.)
- Removed unnecessary toString()ing when using a log formatter.
- Changed indexOf conditionals to use -1 for not found instead of 0.
- Upgrade batik dependencies 1.13 -> 1.14.

improve: wappalyzer: Further Log4j 2.x changes & some SAST (Sonar) Fixes

---

addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SessionFixationScanRule.java
addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/CookieUtils.java
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/http/HttpDateUtils.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/CookieUtilsUnitTest.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/http/HttpDateUtilsUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieSameSiteScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScanRuleUnitTest.java
addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScanRule.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScanRuleUnitTest.java

Add utility class to parse/format HTTP dates.
Update codebase to make use of the new class.
Remove redundant test in `CookieSameSiteScanRuleUnitTest`, the supported
formats are now being tested in the corresponding class.

Use commonlib to parse/format HTTP dates

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/PermissionsPolicyScanRule.java
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
addOns/pscanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/PermissionsPolicyScanRuleUnitTest.java

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy
The header has now been renamed to Permissions-Policy in the spec, and
this article will eventually be updated to reflect that change.

Rename of Feature-Policy header to Permissions-Policy to follow spec change

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScannerUnitTest.java

- WappalyzerPassiveScanner
- Only attempt to check DOM patterns when response is HTML.
- WappalyzerPassiveScannerUnitTest > Add a test to assert the new behavior.
- WappalyzerJonParser > Remove unnecessary throws declarations, add IOException to an existing catch block. Check that Selector Queries are valid before adding them for use.
* WappalyzerAppsJsonParseUnitTest > Will now record an exception if Selector Queries don't parse properly (so the scheduled update jobs will error out on bad upstream Selector Queries).
See: zaproxy/zaproxy#6607

improve: wappalyzer: Catch/Log DOM pattern exceptions & adjust DOM use

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/reports/CHANGELOG.md
addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/Messages.properties
addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/report.html
addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechTableModel.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerAPI.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/automation/ExtensionWappalyzerAutomation.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/automation/WappalyzerJob.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/automation/WappalyzerJobResultData.java
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html
addOns/wappalyzer/src/main/resources/org/zaproxy/zap/extension/wappalyzer/resources/Messages.properties
addOns/wappalyzer/wappalyzer.gradle.kts

I've not added any help as I'm not sure where it would or should go :/
I've also not added a section for it - if the datas available then it will be included - the add-on is optional after all.
Example report snippet:

Wappalyzer - make data available for reports

---

addOns/bugtracker/bugtracker.gradle.kts

The newer versions of the dependencies no longer require the repository.

bugtracker: remove usage of custom repository

---

addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/HiddenFilesScanRuleUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationEnvironmentUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationJobUnitTest.java
addOns/kotlin/src/test/java/org/zaproxy/addon/kotlin/ClassLoaderTests.java
addOns/kotlin/src/test/java/org/zaproxy/addon/kotlin/PrintOutputTests.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureInUrlScanRuleUnitTest.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/ExtensionImportWSDLTestCase.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanRuleTestCase.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/SOAPMsgConfigTestCase.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/SOAPXMLInjectionActiveScanRuleTestCase.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/SitesTreeHelperTestCase.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/SoapActionUnitTest.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/WSDLCustomParserTestCase.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/WSDLFilePassiveScanRuleTestCase.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/WSDLSpiderTestCase.java

- ascanrulesBeta > HiddenFlieScanRuleUnitTest, ensure unit tests have an assertion.
- "JUnit5 test classes and methods should have default package visibility"
- Automation
- commonlib
- Kotlin
- pscanrules
- soap

improve: various add-ons: Even More SAST (sonar) fixes

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureWebInfScanRule.java
addOns/ascanrules/src/main/javahelp/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureWebinfScanRuleUnitTest.java

See:
- https://github.com/mstrobel/procyon/issues/12
- zaproxy/zaproxy#4038 / zaproxy/zap-extensions#2338 / 
- Related to zaproxy/zaproxy#2602
- Reverts zaproxy/zap-extensions#1723

fix: ascanrules: Source Code Disclosure WEB-INF no longer skipped

---

.github/workflows/create_retirejs_update.yml
.github/workflows/create_wappalyzer_update.yml

As discussed via email, use a static feature branch name vs. datestamp so that zapbot doesn't endup with a ton of branches (or hitting some GitHub limit).

chore: Add-on update workflows use static feature branch name

---

addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/AddOnJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PassiveScanConfigJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PassiveScanWaitJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/SpiderJob.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/AddOnJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/PassiveScanConfigJobUnitTest.java

The type and value of all paramters of all the jobs specified in the config is now verified before execution, thus ensuring that  if any job has a misconfigured param, then no job would be executed.
A test was also tweaked according to these changes.
Part of zaproxy/zaproxy#6461

Implement initial sanity check before running the jobs

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationEnvironment.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/ContextWrapper.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/SpiderJob.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/environment.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/env.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationEnvironmentUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/SpiderJobUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-config.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testPlan-failOnErrorApplyingParameters.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testPlan-failOnWarningApplyingParameters.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testplan-dontfail.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testplan-failonerror.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testplan-failonwarning.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testplan-withwarnings.yaml
addOns/reports/CHANGELOG.md
addOns/reports/reports.gradle.kts
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/ReportJob.java
addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/spiderAjax.gradle.kts
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJob.java
addOns/spiderAjax/src/test/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJobUnitTest.java

This is to support contexts that include more than one top level URL, eg https://www.example.com and https://www.example.org - this use case is not supported without this change.
Quite a few knock on changes for this seemingly simple change :/
The SpiderJob now requests each of the top level URLs otherwise it wont work.
WIP as I intend to add at least one test which checks that the URLs are really requested by the SpiderJob and to clean up the option not to request the URLs.

Automation: Change contexts to support list of URLs

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsFunctionScanRule.java
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsFunctionScanRuleUnitTest.java

- JsFunctionScanRule > Don't java quote patterns, but do apply boundary markers on either side as well as an optional $ at the start, when assembling the patterns list. Clean code: Remove unnecessary parameters being passed in private method.
- JsFunctionScanRule > Add rule to assert the new boundary behavior.
- pscanalpha.html > Update help info.
Fixes zaproxy/zaproxy#6594

fix: pscanrulesAlpha: Dangerous JS func word boundary FPs

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportDialog.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/ReportJob.java
addOns/reports/src/main/zapHomeFiles/reports/traditional-xml/report.xml
addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-xml.xml

Fixed issue where report was not generated via the API.
Made more backwards compatible as per #2952
Fixed issue where you could end up with report.xml.xml (applies to all reports).
Added more detailed tests for the report.

Reports: XML template fixes

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PassiveScanConfigJob.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-pscanconf.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/passiveScan-config-max.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/PassiveScanConfigJobUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml

We already disable the pscan tags in the packaged scans - this can give a significant performance improvement, esp for the passive scanning.
Unlike the packaged scans the user will be able to override the setting.

Automation: Added passiveScan-config enableTags param

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java

The trailing slash (and path) were not being striped off the name which meant that directories were incorectly being created.

Reports - fix slash issue

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/EnvFileScanRule.java
addOns/ascanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/EnvFileScanRuleUnitTest.java

Resolves zaproxy/zaproxy#6629 Adding better content type checking for .env files content and more checks based on how most default webservers serve this content if exposed.

Updated the env file rule and test with a bit more accurate information

---

addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java

Fix a bug due to which the jobs ran in a different order than the one specified in the config. Added tests to verify the same.

automation: Fix job run order

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/ExtensionReportAutomation.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/OutputSummaryJob.java
addOns/reports/src/main/resources/org/zaproxy/addon/reports/resources/Messages.properties
addOns/reports/src/main/resources/org/zaproxy/addon/reports/resources/outputSummary-max.yaml
addOns/reports/src/test/java/org/zaproxy/addon/reports/automation/OutputSummaryJobUnitTest.java

Part of https://github.com/zaproxy/zaproxy/issues/6483
Required to replicate the packaged scan functionality.
No unit tests, but not really sure what useful ones could be added :/
I've been manually testing the new baseline code - thats much easier as you can then compare the output side by side...

Reports: Output summary job

---

addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/AddOnJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PassiveScanConfigJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PassiveScanWaitJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/SpiderJob.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationJobUnitTest.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/OutputSummaryJob.java

Modified the verifyCustomParameter method to indicate whether the parameter was verified. Added tests to validate that no warnings are raised. Updated existing tests to replace applyParameters by verifyParameters where necessary.

automation: Fix bug in which known custom parameters raise warnings

---

addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testplan-applyResolvedParams.yaml

Fix bug where the environment was not set for the jobs, which lead to the jobs not using resolved values. Added test to verify the same.

automation: set the environment for jobs

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationEnvironment.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/environment.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/env.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationEnvironmentUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/SpiderJobUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-config.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml

The user can now specify regexes to be included/excluded from the context. 
Modified documentation, added tests and updated the Changelog

Include support for include/exclude regexes in automation framework

---

addOns/kotlin/CHANGELOG.md
addOns/kotlin/src/main/java/org/zaproxy/addon/kotlin/KotlinEngineWrapper.java
addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/SyntaxHighlightTextArea.java
addOns/scripts/src/main/resources/org/zaproxy/zap/extension/scripts/resources/Messages.properties

Allow to choose Kotlin and use appropriate style.
Requires zaproxy/zaproxy#6653 for actual highlighting.

Enable Kotlin syntax highlighting

---

addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/ExtensionReportAutomation.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/OutputSummaryJob.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/automation/OutputSummaryJobUnitTest.java

Use the default constructor for the OutputSummaryJob so that the job can be copied easily for #2980

Reports - OutputSummaryJob default constructor

---

addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationJobUnitTest.java

Do not break existing automation jobs that have not yet implemented
the new verifyCustomParameter method (AjaxSpiderJob, OpenApiJob, SoapJob, etc.)

automation: Fix broken custom params verification

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CodeInjectionScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ExternalRedirectScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/RemoteFileIncludeScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java

Fixes [zaproxy/zaproxy#6647](https://github.com/zaproxy/zaproxy/issues/6647)
The original issue was only for the CodeInjectionScanRule. This change also updates other rules that had the same problem.
Doesn't look like any of the rules currently unit test responding to stops and I did not see a straightforward way to add tests. Please let me know if anyone with more experience on the code base has thoughts for testing.

Check isStop at start of loops in ascanrules

---

addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/HttpStatusReason.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/OutputSummaryJob.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/automation/OutputSummaryJobUnitTest.java

Initial support for the packaged scan config files.
Supports setting the alerts to IGNORE/INFO/WARN/FAIL.
It does not yet support the OUTOFSCOPE elements so will not be enabled in the baseline scan just yet.
However this PR also includes some tweaks to make the output more backwards compatible, based on tests created for the baseline scan.

Reports: OutputSummary config file support phase 1

---

addOns/webdrivers/webdriverlinux/CHANGELOG.md
addOns/webdrivers/webdriverlinux/src/main/javahelp/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
addOns/webdrivers/webdrivermacos/CHANGELOG.md
addOns/webdrivers/webdrivermacos/src/main/javahelp/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
addOns/webdrivers/webdrivers.gradle.kts
addOns/webdrivers/webdriverwindows/CHANGELOG.md
addOns/webdrivers/webdriverwindows/src/main/javahelp/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html

Fix for Chrome browser not launching or immediate closing using ZAP 2.10
Update Chrome driver version to latest "91.0.4472.114"

webdrivers: update ChromeDriver

---

addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportApi.java
addOns/reports/src/main/zapHomeFiles/reports/traditional-xml/report.xml
addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/ReportApiUnitTest.java
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-xml.xml

Default to all sites when called by the API.
Dont append file extension via API if its already there.
Add missing `alert` element in XML report.

Report tweaks

---

addOns/requester/CHANGELOG.md
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/HttpPanelSender.java

This commit adds the button to automatically update the content length. The code was copied from the Resend Request window in ZAP core (see https://github.com/zaproxy/zaproxy/pull/6193).
Closes https://github.com/zaproxy/zaproxy/issues/6254

Requester: Add button to update content length

---

addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java

Use hardcoded version when testing the generated reports to not rely on
the order the tests are executed, some tests make use of the ZAP home
which resolve the ZAP version to `2.10.0`, while the test reports are
expected to have `Dev Build`.

reports: hardcode ZAP version in tests

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/automation/GraphQlJob.java
addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/automation/GraphQlJobUnitTest.java

The docs even say `default: null, no schema is imported`

GraphQL - dont fail if no URL in automation job

---

build.gradle.kts

Add the required dependency when building the ZAP releases, it also uses
Java 8.

Correct Error Prone setup

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/OpenApiAPI.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverter.java
addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/contents/openapi.html
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApiTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/OpenApiAPIUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/bad-json.json
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/bad-yaml.yml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v2/multi-file/api.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v2/multi-file/person.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/MultiVarPath_defn.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/multi-file/api.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/multi-file/pet.api.yaml
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/multi-file/pet.model.yaml

* Build and return a `StructuralNodeModifier` list based on path parameters found
in the provided OpenAPI spec
* Handle multiple path variables and generate appropriate regex for data driven nodes
* Use default context for adding DDNs if not provided
* Add multi-file schema support
Signed-off-by: Adam Baldwin <adam.baldwin@stackhawk.com>

openapi: Updates for data-driven node parsing and multi-file schema support

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/pscanrules.gradle.kts
addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts

Change `ascanrulesBeta`, `pscanrules`, and `pscanrulesAlpha` to use a
version range when declaring the dependency on `custompayloads` to
include more versions and allow to use the version already released.

Correct dependency requirements

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts

Make `commonlib` a dependency of the whole add-on not just the
extension.
Fix zaproxy/zaproxy#6674.

pscanrulesAlpha: correct dependency declaration

---

addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java

The tests started to fail recently and are blocking unrelated pull
requests.

domxss: disable tests

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java

- WappalyzerJsonParser > Move "Unexpected header type" messages from error to debug logging.
Related to zaproxy/zaproxy#6607

improve: wappalyzer: Reduce visibility of 'Unexpected header type' msgs

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanRule.java
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanRuleUnitTest.java

As discussed in zaproxy/zaproxy#6595, modified SourceCodeDisclosureScanRule to ignore HttpResponse with content type header as css or javascript.
Fix zaproxy/zaproxy#6595.

Fix for ZAP Source Code Disclosure-Java-false positive Issue 6595

---

addOns/addOns.gradle.kts
buildSrc/build.gradle.kts
testutils/testutils.gradle.kts

- Remove hardcoded JaCoCo version and rely on Gradle default.
- Update other libraries and Gradle plugins to newer versions.

Remove the specification of the JaCoCo version

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/PiiScanRule.java
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/PiiScanRuleUnitTest.java

- Ignore images
- PiiScanRule > Add request and response isImage checks.
- PiiScanRuleUnitTets> Add tests to assert the updated behavior.
Fixes zaproxy/zaproxy#6697
- Ignore decimal'ish numbers
- PiiScanRule > Add checks for decimal'ish values.
- PiiScanRuleUnitTets> Add tests to assert the updated behavior.
- pscanbeta.html > Added note about threshold handling.
Fixes zaproxy/zaproxy#6639

fix: pscanrulesBeta: PII Scan rule ignore images and handle decimal like values

---

addOns/alertFilters/CHANGELOG.md
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFilterAPI.java
addOns/alertFilters/src/main/resources/org/zaproxy/zap/extension/alertFilters/resources/Messages.properties

To apply Alert Filters to existing alerts.
AlertFilterAPI > Added endpoints and functionality.
CHANGELOG > Added addition note.
Messages.properties > Added endpoint description key/value pairs.
Fixes zaproxy/zaproxy#5966

improve: alertFilters: Add apply and test API endpoints

---

addOns/httpsInfo/httpsInfo.gradle.kts

Use all lower case for the name of the add-on when uploading the files
to Crowdin.

httpsInfo: correct Crowdin path

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/Application.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScannerUnitTest.java
addOns/wappalyzer/src/test/resources/org/zaproxy/zap/extension/wappalyzer/apps.json

Per zaproxy/zap-extensions#3046
- apps.json > Updated with test content.
- CHANGELOG > Updated with addition note.
- WappalyzerPassiveScanner > Updated to parse and handle cookie patterns.
- WappalyzerPassiveScannerUnitTest > Updated to test cookie patterns. Also tweaked local assertion method name, and made more test methods leverage it.

improve: wappalyzer: Added Cookie Patterns Support

---

addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/SpiderJobDialog.java
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties

I noticed this when I watched the ZAPCon after hours video.
OOData should be OData, per:
https://github.com/zaproxy/zaproxy/blob/80fb2ab540fb3d580b8b208ebc5ed1674e20c749/zap/src/main/resources/org/zaproxy/zap/resources/Messages.properties#L2994

fix: automation: Typo

---

addOns/addOns.gradle.kts

Depend on the task of the add-on being released instead of the task of
add-ons project (which would have no effect).

Correctly wire Crowdin upload source tasks

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/JobUtils.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/SpiderJob.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/JobUtilsUnitTest.java
addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJob.java

Correctly ignore the parameters that shouldn't be copied to param
objects (convert the parameter names to getter names).
Ignore context and URL parameters in spiders, they are not present in
the param objects.

automation: address "failed to find method" errors

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationEnvironment.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/RequestorJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/SpiderJob.java
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/env.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/requestor-max.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/RequestorJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/SpiderJobUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-config.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml
addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/automation/GraphQlJob.java
addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/automation/GraphQlJobUnitTest.java
addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJob.java
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/Messages.properties
addOns/soap/CHANGELOG.md
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/automation/SoapJob.java
addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJob.java

Fixes: https://github.com/zaproxy/zaproxy/issues/6726)
Mostly tested manually as automation jobs are hard to unit test :/
Also supports env in requestor data and improved some of the info messages to inc URLs.

Automation: Fix var support in URLs

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastOptionsPanelTab.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastParam.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastServer.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastService.java
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/services/boast/options.html
addOns/oast/src/main/resources/org/zaproxy/addon/oast/resources/Messages.properties
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/boast/BoastParamUnitTests.java

- Added an option to allow changing the polling frequency of BOAST servers.
- Added a table that lists the payloads and canary values of all registered BOAST servers.
- Removed the _ID_ and the _Canary Value_ fields, in favour of the _Active Servers_ table in the BOAST options window.
<details><summary>Before and After Options Window Screenshots</summary>
</details>

oast: Updates

---

addOns/addOns.gradle.kts

Update plugin to latest version to fix the issue when copying
translations that have a common prefix in the export path.

Update Gradle Crowdin plugin

---

gradle/crowdin-help-only.yml

Remove incorrect suffix in the output dir path of help resources.

Correct output dir of localized resources

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/scripts/ExtensionOastScripts.java
addOns/oast/src/main/resources/org/zaproxy/addon/oast/resources/Messages.properties

Script templates already loaded by core were being loaded again by the
add-on, resulting in a warning.

oast: Do not load script templates twice

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties

Replaced the dead URL in Cross-Domain misconfiguration with correct updated URL:
https://vulncat.fortify.com/en/detail?id=desc.config.dotnet.html5_overly_permissive_cors_policy
Fix zaproxy/zaproxy#6731.

Fix 6731 - replaced dead CORS misconfiguration reference URL

---

addOns/exim/src/main/java/org/zaproxy/addon/exim/har/PopupMenuItemSaveHarMessage.java

Save raw/XML are currently available in safe mode, but export HAR is not.

exim: Mark export HAR as safe

---

addOns/automation/CHANGELOG.md
addOns/retest/retest.gradle.kts

- Bumped the minimum required version of the automation addon required by the retest addon to 0.5.0
- Updated the changelog of the automation addon.

Automation and retest addon tweaks

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/zapHomeFiles/scripts/templates/extender/Copy as curl command menu.js

Like #3085, make 'Copy as curl Command' also available in safe mode.

scripts: Mark 'Copy as curl Command' as safe

---

addOns/retest/retest.gradle.kts

Override the default location so the source files that require
localization are found.

retest: specify location of files for Crowdin

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverter.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApiTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/defn-with-warns.yml

Change `SwaggerConverter` to return as soon as it's able to parse the
definition, even if it has issues.
Change `ExtensionOpenApi` to not skip the parsed file definition when it
has issues, still try to import what was parsed.
Restore behaviour of previous versions and match the behaviour when
importing from URL.
Fix zaproxy/zaproxy#6758.

openapi: import from file even if it has issues

---

addOns/retest/CHANGELOG.md
addOns/retest/src/main/javahelp/org/zaproxy/addon/retest/resources/help/map.jhm
addOns/retest/src/main/javahelp/org/zaproxy/addon/retest/resources/help/toc.xml

Add missing mapping for the about help page.
Remove image attribute from main TOC item, the image does not exist.

retest: fix about help page

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/RequestModelConverter.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/BodyGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/BodyGeneratorUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/OpenApi_defn_examples.yaml

What do think about if we support OpenAPI examples as a generated request body if it's available ?

openapi: utilize media type examples if available

---

addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
addOns/websocket/src/main/javahelp/org/zaproxy/zap/extension/websocket/resources/help/contents/script.html

It worked fine with the previous code when the add-on was installed, but not when its included as standard in ZAP.

Websockets: Always auto add+enable missing default pscan scripts

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/generator/NumberPayloadGenerator.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/ui/impl/NumberPayloadGeneratorAdapterUIHandler.java

- CHANGELOG > Added Fix & change entry.
- NumberPayloadGenerator > Remove spurious isDebug check missing in 2.10 logging infrastructure changes.
- NumberPayloadGeneratorAdapterUIHandler > The clear() method now properly resets increment to 1 (which is the initial default used elsewhere) instead of zero.

fix: fuzz: Numberzz payload generator properly reset the increment field

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanRule.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanRuleUnitTest.java

- SourceCodeDisclosureScanRule > Added check for font request/response to early return conditional.
- SourceCodeDisclosureScanRule > Added unit tests to assert the new behavior, and extended coverage on one existing test.
Closes zaproxy/zaproxy#6795

improve: pscanrulesAlpha: Source Code Disclosure no longer check fonts

---

addOns/domxss/src/main/javahelp/org/zaproxy/zap/extension/domxss/resources/help/contents/domxss.html

Wrapped example link in code tags, to address a weird parsing issue on https://www.zaproxy.org/docs/desktop/addons/dom-xss-active-scan-rule/
No changelog entry, leaving this attributed to "maintenance changes".

fix: Address help URL parsing issue

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/javahelp/org/zaproxy/zap/extension/fuzz/resources/help/contents/options.html

I have added the missing definitions to the documentation of fuzzer options screen.
It resolves zaproxy/zaproxy#6791

Updated Fuzzer Options Documentation

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/OutputSummaryJob.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/automation/OutputSummaryJobUnitTest.java

As defined on https://www.zaproxy.org/docs/docker/baseline-scan/
> You can add your own messages to each rule by appending them after a tab on each line.
I think this is actually the last java code change required in order to completely support config files in the baseline scan :O
I'll update https://github.com/zaproxy/zaproxy/pull/6781 to use this once it has been merged.

Reports: Support for custom messages in outputSummary job.

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosureScanRule.java

- BackupFileDisclosureScanRule
- Remove unnecessary array creation when instantiating various sets.
- Extract convenience method for HttpMessage cookie setting (reduces nesting, and duplication).
- Remove unnecessary toString calls in logging.
- Reduce use of generic Exception.
- Remove empty instantiation of byte arrays.
- CHANGELOG added maintenance note.
This is a prelude PR to addressing: zaproxy/zaproxy#5330

fix: ascanrulesBeta: Backup File Disclosure Sonar Fixes

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanRule.java
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanRuleUnitTest.java

- CHANGELOG.md > Updated change note.
- pscanalpha.html > Tweaked help note.
- SourceCodeDisclosureScanRule.java > Added image to request/response exclusions.
- SourceCodeDisclosureScanRuleUnitTest.java > Added test methods to assert the image related behavior.
Fixes zaproxy/zaproxy#6820

fix: pscanrulesAlpha: Source Code Disclosure image false positive

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverter.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverterUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/converter/swagger/openapi_path_servers.yaml

Use path servers when available.
Fix zaproxy/zaproxy#6754.

openapi: use path servers

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/zapHomeFiles/scripts/templates/standalone/OAST Register Request Handler.js

Update the _OAST Register Request Handler.js_ script template so that it also prints the raw request sent to the server.
Signed-off-by: Akshath Kothari <ricekot@gmail.com>

oast: Update script template

---

addOns/retire/CHANGELOG.md
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/model/ExtractorsTypeAdapter.java
addOns/retire/src/test/java/org/zaproxy/addon/retire/RetireScanRuleUnitTest.java
addOns/retire/src/test/java/org/zaproxy/addon/retire/model/VersionPatternUnitTest.java

- ExtracrotsTypeAdapter > Fixed version extraction regex and fixPattern method.
- RetireScanRule.java > Added trim on evidence (whitespace doesn't need to be included).
- RetireSccanRuleUnitTest > Parameterized an existing  test method to more completely test this condition, and added VersionPatternUnitTest to further ensure things behave as expected.
Fixes zaproxy/zaproxy#6818

fix: retire: Version Extraction Pattern False Positives

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/LinkTargetScanRule.java
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/LinkTargetScanRuleUnitTest.java

The default value of rel in Chrome, Firefox, safari, etc. has been changed to noopener, so I think the scanning rule needs to be changed 🤔
so I modified from existing if statements to finding `rel=opener`.
* https://chromium-review.googlesource.com/c/chromium/src/+/1630010
* https://twitter.com/mikewest/status/1325694207546318851
```html
<a href="https://www.hahwul.com/phoenix/reverse-tabnabbing-1" target="_blank">Click me</a>
```
```html
<a href="https://www.hahwul.com/phoenix/reverse-tabnabbing-1" target="_blank" rel="opener">Click me</a>
```

Modified the reverse tabnabbing(link target) scanning rule.

---

addOns/retire/CHANGELOG.md
addOns/retire/src/main/java/org/zaproxy/addon/retire/Result.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireUtil.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/model/Repo.java

- CHANGELOG.md added maintenance note.
- Repo.java removed unnecessary toString. Remove unnecessary hashmap assignments. Use entrySet vs keySet.
- Result.java rename info field to information so that it doesn't hide or conflict with the INFO constant.
- ReiteScanRule.java rename local variable to not hide class field.
- RetireUtil.java add private constructor to hide implicit public constructor. Corrected naming of some local variables.

improve: retire: Address SAST (sonar) Items

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/quickstart.gradle.kts
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/launch/LaunchPanel.java
addOns/quickstart/src/main/resources/org/zaproxy/zap/extension/quickstart/resources/Messages.properties

Screenshot for when the panel is disabled:

Quickstart: Disable browser launch in containers unless override option enabled

---

addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ChallengeCallbackImplementor.java

Use TimeUnit to simplify reading/maintenance.
CHANGELOG already has a maintenance note.

improve:ascanrulesBeta:Leverage TimeUnit in ChallengeCallbackImplementor

---

addOns/domxss/CHANGELOG.md
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomAlertInfo.java
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java
addOns/domxss/src/test/resources/org/zaproxy/zap/extension/domxss/RandomAlert.html
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java

- DomXssScanRule > Now gets the alert dialog's content before catching UnhandledAlertException then compares it to ensure the dialog is likely to be one ZAP caused. Increased confidence to HIGH.
- DomXswsScanRuleUnitTest > Added a single method to test an unrelated alert dialog condition. (Ex: When an alert shouldn't pop.) Adjusted to accommodate new HIGH confidence. Corrected one documentation URL.
- DomAlertException > Renamed to DomAlertInfo, and changed control away from Throwing a custom exception to checking if the return is null or not.
- DomXswsScanRuleUnitTest > Added a single method to test an unrelated alert dialog condition. (Ex: When an alert shouldn't pop.) Adjusted to accommodate new HIGH confidence.
- ExtensionSelenium > Added a utility method to accept a capabilities …

fix: domxss: Check alert dialog content to reduce false positives

---

addOns/exim/src/main/java/org/zaproxy/addon/exim/ExtensionExim.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/ImportExportApi.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/urls/MenuItemImportUrls.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/urls/UrlsImporter.java
addOns/exim/src/main/javahelp/help/contents/exim.html
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/Messages.properties

- ExtensionExim > Updated to hook the new menu item.
- ImportExportApi > Updated to include the importUrls endpoint.
- MenuItemImportUrls > Extracted from the original add-on.
- UrlsImporter > Utility class with static work methods.
- Messages.properties > Added necessary resource key value pairs.
- exim.html > Added help info for this functionality.
Part of: zaproxy/zaproxy#6579
Didn't include any CHANGELOG entry as the add-on has not yet been released.

improve:exim: Add importUrls functionality

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosureScanRule.java

- Backup File Disclosure Scan Rule: When checking a parent folder for 404 behavior assume a minimum folder name length of four to further eliminate chance of collision on short folder names (Issue 5330). Also fix 'alphabet' used for random name generation (missing zero, had two nines & missing n, had two o's).
- CHANGELOG: Add change note.
Fixes zaproxy/zaproxy#5330

fix: ascanrulesBeta: Use assumed minimum length for parent folder names

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshParam.java

See https://github.com/projectdiscovery/interactsh/issues/99.
Signed-off-by: Akshath Kothari <ricekot@gmail.com>

oast: Update default Interactsh server URL

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/SpringActuatorScanRule.java
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/SpringActuatorScanRuleTest.java

Resolves zaproxy/zaproxy#6777 Adds a basic check for Spring Boot Actuators, specifically the health check.
Also, my first cut at adding a new rule so thanks for the help.

ascanrulesAlpha: Basic Check for Spring Actuators

---

addOns/alertFilters/CHANGELOG.md
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFiltersMultipleOptionsPanel.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ContextAlertFilterPanel.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/DialogAddAlertFilter.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/DialogModifyAlertFilter.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/OptionsGlobalAlertFilterPanel.java

The alert filter dialog can be accessed via the global options, contexts and right clicking alerts.
Previously is assumed the parent was always the same which meant that in many cases it appeared under the main frame.
This change associates the parent with the dialog so that we can always display it correctly.

Fix dialogs being shown under owning frame/dialog

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/CorsScanRule.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ForbiddenBypassScanRule.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRule.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjectionScanRule.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/SpringActuatorScanRule.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/WebCacheDeceptionScanRule.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/CorsScanRuleUnitTest.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/ForbiddenBypassScanRuleUnitTest.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRuleUnitTest.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjectionScanRuleUnitTest.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/SpringActuatorScanRuleUnitTest.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/WebCacheDeceptionScanRuleUnitTest.java

- Updated scan rules and unit tests.
- Renamed SpringActuatorScanRuleTest to SpringActuatorScanRuleUnitTest for consistency.
- Added note to CHANGELOG.

improve: ascanrulesAlpha: Add Top10 Mappings

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/InPageBannerInfoLeakScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsFunctionScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsoScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/PermissionsPolicyScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SiteIsolationScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScanRule.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64DisclosureUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/InPageBannerInfoLeakScanRuleUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsFunctionScanRuleUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsoScanRuleUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/PermissionsPolicyScanRuleUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SiteIsolationScanRuleTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanRuleUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScanRuleUnitTest.java

- Updated scan rules and unit tests.
- Didn't add mappings for CacheablesScanRule as it's informational (or Examples).

improve: pscanrulesAlpha: Add Top10 Mappings

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PersistentXssScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/PersistentXssScanRuleUnitTest.java
addOns/domxss/CHANGELOG.md
addOns/domxss/domxss.gradle.kts
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java
addOns/sqliplugin/CHANGELOG.md
addOns/sqliplugin/sqliplugin.gradle.kts
addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLInjectionScanRule.java

ascanrules
- Update XSS rules to use the XSS mapping for 2017.
domxss & sqliplugin
- Updated scan rules and unit tests (some unit test classes added).
- Fixed naming (and help link) for MySql scan rule and unit test.
- Update build files to depend on commonlib.
- Added note to CHANGELOG.

improve: domxss,sqliplugin, ascanrules: Add/update Top10 Mappings

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationEnvironment.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/ContextWrapper.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/ActiveScanJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/RequestorJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/SpiderJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/RequestorJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/SpiderJob.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/authentication.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/automation.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/environment.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-ascan.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-requestor.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-spider.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/index.xml
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/map.jhm
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/toc.xml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/activeScan-max.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/activeScan-min.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/env.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/requestor-max.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/requestor-min.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/spider-max.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/spider-min.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-config.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml

This actually enables limited authentication support, enough (I think) to make it worth releasing.
Initial support is just for manual and http/ntlm auth - the others will be added asap.
The GUI doesnt support most of the auth elements but will create them from an existing context and shouldnt delete those elements unless you delete the context.
The requestor, spider and active scan jobs have all been updated to support auth - the relevant dialogs have an "Authenticated User" pulldown.
I'll submit a separate PR for supporting auth in the Ajax Spider.

Automation: enable authentication for jobs

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/impl/FuzzerOptionsPanel.java

- FuzerOptionsPanel.java > Ensure the panel from the received fuzzerHandlerOptions parameter is actually displayed/used.
I did test this with a 301 and once displayed the option does seem to be handled as expected.

fix: fuzz: Ensure 'Follow Redirects' is displayed

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CharsetMismatchScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentTypeMissingScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieLooselyScopedScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieSameSiteScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CrossDomainMisconfigurationScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CrossDomainScriptInclusionScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CsrfCountermeasuresScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InfoPrivateAddressDisclosureScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InfoSessionIdUrlScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureDebugErrorsScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureInUrlScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureReferrerScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureSuspiciousCommentsScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InsecureAuthenticationScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InsecureJsfViewStatePassiveScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/MixedContentScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/UsernameIdorScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ViewstateScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XAspNetVersionScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XContentTypeOptionsScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XDebugTokenScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XFrameOptionScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XPoweredByHeaderInfoLeakScanRule.java

In follow-up to: https://github.com/zaproxy/zaproxy/pull/6598

chore: pscanrules: remove use of setParent

---

addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/PassiveScanConfigJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/PassiveScanJobResultsUnitTest.java
addOns/imagelocationscanner/CHANGELOG.md
addOns/imagelocationscanner/src/main/java/org/zaproxy/zap/extension/imagelocationscanner/ImageLocationScanRule.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/automation/OutputSummaryJobUnitTest.java
addOns/retire/CHANGELOG.md
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
addOns/saml/CHANGELOG.md
addOns/saml/src/main/java/org/zaproxy/zap/extension/saml/SAMLPassiveScanner.java
addOns/soap/CHANGELOG.md
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/WSDLFilePassiveScanRule.java

In follow-up to: https://github.com/zaproxy/zaproxy/pull/6598
- automation
- imagelocationscanner
- reports
- retire
- saml
- soap

chore: various add-ons: remove use of setParent

---

addOns/pscanrulesAlpha/CHANGELOG.md

Per: https://github.com/zaproxy/zap-extensions/pull/3306#discussion_r745693123

fix: pscanrulesAlpha: Improper CHANGELOG note placement

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/CommonAlertTag.java

- CommonAlertTag > Adjusted the tag of "OWASP_A10_LOGGING_FAIL" to match other alert tags for 2017/2021.
- CHANGELOG > Added maintenance note.

fix: commonlib: 2017 A10 naming consistency

---

addOns/network/network.gradle.kts
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpMessageEncoder.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpRequestEncoder.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpResponseEncoder.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/HttpMessageEncoderUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/HttpRequestEncoderUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/HttpResponseEncoderUnitTest.java

Allow to encode the request and response of a `HttpMessage`.

network: add encoders for HttpMessage

---

addOns/network/network.gradle.kts
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/quickstart/CHANGELOG.md
addOns/quickstart/quickstart.gradle.kts
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/DefaultExplorePanel.java

Move the write of the root CA certificate to the network add-on to hide
implementation details (network add-on will manage the Root CA cert).
Change Network add-on to target 2.11, to not require existing add-ons
to also target the newer version.
---
WIP pending release of Quick Start add-on with the callhome changes.

quickstart: use network add-on to write cert

---

addOns/addOns.gradle.kts
addOns/network/CHANGELOG.md
addOns/network/network.gradle.kts
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/NetworkApi.java
addOns/network/src/main/javahelp/help/contents/api.html
addOns/network/src/main/javahelp/help/contents/network.html
addOns/network/src/main/javahelp/help/index.xml
addOns/network/src/main/javahelp/help/map.jhm
addOns/network/src/main/javahelp/help/toc.xml
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/NetworkApiUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/NetworkTestUtils.java
testutils/src/main/java/org/zaproxy/zap/testutils/TestUtils.java

Add API to generate, import, and obtain the root CA certificate,
replaces core endpoints `generateRootCA` and `rootcert`.
Add network add-on to the list of mandatory add-ons.
Fix zaproxy/zaproxy#2280.
Related to zaproxy/zaproxy#6949.

network: add API to manage root CA certificate

---

addOns/network/network.gradle.kts
addOns/oast/CHANGELOG.md
addOns/oast/oast.gradle.kts

Bundle the Bouncy Castle library to no longer rely on core to create
the server certificates, core will no longer need it.
Change OAST add-on to depend on Network add-on, which also uses Bouncy
Castle library, it will also use other network features (e.g. server
for callbacks).

network: bundle Bouncy Castle library

---

addOns/selenium/CHANGELOG.md
addOns/selenium/gradle.properties
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/SeleniumOptions.java
addOns/selenium/src/test/java/org/zaproxy/zap/extension/selenium/SeleniumOptionsUnitTest.java

Check if files were returned from the extensions directory to prevent a
NullPointerException.
Create the extensions directory for proper enumeration of the files and
for the user to not need to create it manually.
Fix zaproxy/zaproxy#6951.

selenium: address exception when saving options

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java

Tested vs https://hackxpert.com/RXSS/
10, 30, 40 and 70 were already detected.
These changes detect the XSSs on 11, 12 and 13.
50 and 60 cant be detected by this rule as they use client side javascript - we'd have to use the DOM XSS rule...

Ascan Rules: RXSS tweaks

---

addOns/exim/src/main/java/org/zaproxy/addon/exim/ExtensionExim.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/PopupMenuSaveRawMessage.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/PopupMenuSaveXmlMessage.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarImporter.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/PopupMenuItemSaveHarMessage.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/log/LogsImporter.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/urls/UrlsImporter.java
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/Messages.properties

Part of zaproxy/zaproxy#6579
Add stats for importing and saving files, individual URLs/messages, and errors.
Add output panel messages for starting and finishing files. (Can be handy for example when importing a file of URLs and encountering timeouts.)

exim: Add import and save stats

---

addOns/soap/CHANGELOG.md
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/ImportFromUrlDialog.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/WSDLCustomParser.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/WSDLFilePassiveScanRule.java
addOns/soap/src/main/resources/org/zaproxy/zap/extension/soap/resources/Messages.properties
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/WSDLFilePassiveScanRuleTestCase.java

- WSDL File scan rule now includes identification of URLs in the form "example.com/service?wsdl", and specifically excludes 404s and 500s (including support for Custom Pages).
- Import a WSDL file from a URL now logs a more specific message for some exception conditions, or when failing to convert the
input 'URL' string into an actual URL to make the WSDL request.
- The import from URL dialog now accepts pressing the enter key to activate the import process (instead of having to click the Import button), and the escape key to close/cancel the dialog.
- Changed Scan Rule test class to extend PassiveScannerTest, adjusted some test names to be more specific, added tests to assert the new behavior.

improve: soap: Various User friendliness changes

---

addOns/pscanrules/pscanrules.gradle.kts
addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts
addOns/pscanrulesBeta/pscanrulesBeta.gradle.kts

I didn't tweak the CHANGELOGs because this should probably have been done when the WSTG mappings were added.

chore: pscanrules all: Depend on commonlib 1.6.0 or newer

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/cert/CertificateUtils.java
addOns/network/src/main/javahelp/help/contents/cmdline.html
addOns/network/src/main/javahelp/help/index.xml
addOns/network/src/main/javahelp/help/map.jhm
addOns/network/src/main/javahelp/help/toc.xml
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/cert/CertificateUtilsUnitTest.java

Handle command line arguments `-certload`, `-certpubdump`, and
`-certfulldump` when the corresponding core extension is deprecated.
Moves core deprecated functionality, zaproxy/zaproxy#6950.

network: handle cert command line args

---

addOns/domxss/CHANGELOG.md
addOns/domxss/domxss.gradle.kts
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java
addOns/imagelocationscanner/CHANGELOG.md
addOns/imagelocationscanner/imagelocationscanner.gradle.kts
addOns/imagelocationscanner/src/main/java/org/zaproxy/zap/extension/imagelocationscanner/ImageLocationScanRule.java
addOns/imagelocationscanner/src/test/java/org/zaproxy/zap/extension/imagelocationscanner/ImageLocationScanRuleUnitTest.java

- Added alert mappings to scan rules.
- Updated UnitTests.
- Added change note.
- Update build file to depend on commonlib 1.6.0 or newer.

feat: domxss & ILS: Add WSTG v4.2 alert mappings

---

addOns/graaljs/CHANGELOG.md
addOns/graaljs/graaljs.gradle.kts

Use the previous version of the Graal JavaScript library, the newer
version is causing problems in the live Docker image.
Remove change from changelog.
---
Per OWASP ZAP User Group thread: https://groups.google.com/g/zaproxy-users/c/fbrYAVKKu9Y/m/DvARO3c2CwAJ

graaljs: revert dependency update

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/Log4ShellScanRule.java
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/Log4ShellScanRuleUnitTest.java

Steps for testing:
1. Run the vulnerable app: `docker run -p 8000:8080 ghcr.io/christophetd/log4shell-vulnerable-app` (from  https://github.com/christophetd/log4shell-vulnerable-app)
1. Send a manual request to the hosted app with the `X-Api-Version` header and a random value.
1. Select BOAST or Interactsh as the active scan service in the OAST options panel.
1. Run an active scan against the vulnerable app node. Ensure that the HTTP Headers checkbox under Input Vectors is enabled. Also enable the Log4Shell scan rule.
1. Click on `Poll Now` in the OAST tab.

ascanrulesAlpha: Add Log4Shell (CVE-2021-44228) Scan Rule

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/DelayJob.java

It works fine when creating the job from the desktop as the parameters are set directly.
But if you load the job from a file or run it on the command line then the parameters are not applied.

Automation: Fix setting the delay params via the cmdline

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpMessageDecoder.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpRequestDecoder.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpResponseDecoder.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/HttpMessageDecoderUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/HttpRequestDecoderUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/HttpResponseDecoderUnitTest.java

Allow to decode the request and response into a `HttpMessage`.

network: add decoders for HttpMessage

---

addOns/importLogFiles/importLogFiles.gradle.kts
addOns/importLogFiles/src/main/java/org/zaproxy/zap/extension/importLogFiles/ExtensionImportLogFiles.java
addOns/importLogFiles/src/main/java/org/zaproxy/zap/extension/importLogFiles/ImportLogAPI.java
addOns/importLogFiles/src/main/resources/org/zaproxy/zap/extension/importLogFiles/resources/Messages.properties
addOns/importurls/CHANGELOG.md
addOns/importurls/importurls.gradle.kts
addOns/importurls/src/main/java/org/zaproxy/zap/extension/importurls/ExtensionImportUrls.java
addOns/importurls/src/main/java/org/zaproxy/zap/extension/importurls/ImportUrlsAPI.java
addOns/importurls/src/main/resources/org/zaproxy/zap/extension/importurls/resources/Messages.properties

- Add Retire entry to CHANGELOGs.
- Add exim dependency to build files.
- Display a warning dialog and log a warning message in `postInstall()`.
- Log a warning message on API use.
Part of zaproxy/zaproxy#6579

chore: importLogFIles & importUrls: Hollow & Retire

---

addOns/callhome/callhome.gradle.kts
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/CallHomeParam.java
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/OptionsCallHomePanel.java
addOns/callhome/src/main/javahelp/org/zaproxy/addon/callhome/resources/help/contents/callhome.html
addOns/callhome/src/main/resources/org/zaproxy/addon/callhome/resources/Messages.properties
addOns/callhome/src/test/java/org/zaproxy/addon/callhome/ExtensionCallHomeUnitTest.java

Adds support for the telemetry service.
Telemetry calls are made on startup (reporting the add-ons and versions) and when the session changes (including when ZAP is stopped) (reporting stats that shouldnt leak any sensitive info).
The new `-notel` command line option turns off telemetry and theres a new Options / Call Home screen which allows you to switch telemetry on and off and shows the last telemetry data sent.
The telemetry data sent is also logged at debug level.

Callhome: Add telemetry

---

addOns/network/network.gradle.kts
addOns/openapi/openapi.gradle.kts
addOns/reports/reports.gradle.kts
addOns/soap/soap.gradle.kts

Updated build files.
Related to zaproxy/zaproxy#6980

chore: Upgrade Log4j to 2.17.0

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshOptionsPanelTab.java
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/services/interactsh/options.html

OAST Interactsh Options Dialog: If host or token config changed the 'New Payload' Button generates the Payload still with the old config.
That is confusing (especially if there were errors in the config). 
As a quick fix I disabled the button if the relevant configs changed

oast: Interactsh Options Dialog - 'New Payload' Button use old config

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/Log4ShellScanRule.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/Log4ShellScanRuleUnitTest.java

ascanalpha: Log4Shell: Continue with further payloads if one payload throws an error
I observed this behavior especially on the vulnerable docker container `ghcr.io/christophetd/log4shell-vulnerable-app` which returns an read timeout if the vuln is triggered! This results in an exception for the specific payload and no further payload is tested.

ascanalpha: Log4Shell: Continue with further payloads if one payload throws an error

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/Log4ShellScanRule.java

Log4ShellScanner bugfixes: Fixes zaproxy/zaproxy#7002 RMI Payloads and continue with further payloads if one payload throws an error.
I tested all payloads with: 
```
sudo docker run -p 8000:8080 ghcr.io/christophetd/log4shell-vulnerable-app
``` 
Therefore the try..catch also addressed in #3421 is also necessary here.

ascanalpha: Log4Shell: Correct RMI Payloads

---

addOns/requester/CHANGELOG.md
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ExtensionRequester.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ManualHttpRequestEditorPanel.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ManualRequestEditorPanel.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/NumberedTabbedPane.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/RequesterNumberedTabbedPane.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/RequesterOptionsPanel.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/RequesterPanel.java
addOns/requester/src/main/resources/org/zaproxy/zap/extension/requester/resources/Messages.properties

- CHANGELOG > Added maintenance note.
- ExtensionRequester > Avoid use of boolean literal.
- ManualHttpRequestEditorPanel > Use SwingConstants and combine identical catch blocks.  Set help key.
- ManualRequestEditorPanel > Remove unnecessary comment. Merge nested conditionals.
- NumberedTabbedPane > Merge nested conditionals.
- RequesterNumberedTabbedPane > Re-work constructors and use of constants.
- RequesterOptionsPanel > Add comment to empty overridden method.
- RequeterPanel > Use InputEvent vs. KeyEvent for hotkey constants. Removed un-used constant.
- Messages.properties > Add missing period (related to Issue 2000).

improve: requester: Address SAST (sonar) Findings

---

addOns/network/network.gradle.kts
addOns/openapi/openapi.gradle.kts
addOns/reports/reports.gradle.kts
addOns/soap/soap.gradle.kts

Updated build files.
Related to zaproxy/zaproxy#6980

chore: Upgrade Log4j to 2.17.1

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationEnvironment.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationEnvironmentUnitTest.java

Reorder the variables to ensure that the system env vars take
precedence when replacing them.
Fix zaproxy/zaproxy#7000.

automation: ensure env vars take precedence

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/Log4ShellScanRule.java
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties

Was a bit tricky to find out why the original payload does not trigger:
`"${jndi:ldap://127.0.0.1#{0}/abc}"`
Turns out it was due to how interactsh parses the correlationId. It needs a dot between arbitrary characters and the correlationId.
Fixed it in that case with `a.` in front of the canary token:
`"${jndi:ldap://127.0.0.1#a.{0}/abc}"`
I will create a ticket if we should handle that more generally in the `getNewPayload()` Method
This CVE Detection can be reproduced with this vuln app:
`sudo docker run -p 8000:8080 --rm ghcr.io/denniskniep/vulnerable-app-log4shell-2.15.0:latest`
Can be found here: https://github.com/denniskniep/log4shell-vulnerable-app

ascanalpha: Log4Shell: Added detection for CVE-2021-45046

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRuleUnitTest.java

- ContentSecurityPolicyScanRule > Added functionality to skip allowed directives that aren't handled/known to the salvation library.
- ContentSecurityPolicyScanRuleUnitTest > Added a new test to assert the updated behavior.
Fixes zaproxy/zaproxy#6602

chore: pscanrules: Fix CSP false positive on trusted-types directives

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRule.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties

- Messages.properties > Update name, description, and solution to be more lenient.
Fixes zaproxy/zaproxy#6462

chore: pscanrules: Update cache-control details to be more lenient

---

addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Username Idor Scanner.js

- Updated the references in the script.
- Added change not to CHANGELOG.

chore: websockets: Replace old OWASP mediawiki links

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java

In the XSS addOn, in the case when the payload is reflected outside…f HTML tags, try more payloads.
I made this to catch a potential XSS that I noticed being missed by the active scan in an API that I was scanning. Payload was reflected in a json response.

ascanrules: XSS: try more payloads if outside of HTML tags

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/HttpFuzzerHandler.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/impl/FuzzMessagePanel.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/impl/FuzzerDialog.java
addOns/fuzz/src/main/javahelp/org/zaproxy/zap/extension/fuzz/resources/help/contents/dialogue.html
addOns/fuzz/src/main/resources/org/zaproxy/zap/extension/fuzz/resources/Messages.properties

Fixes https://github.com/zaproxy/zaproxy/issues/2315
This adds a new 'Edit' button to the Fuzz Dialog.
When clicked this changes to 'Save', makes the message editable and clears all fuzz locations. It also disabled the 'Add...' button so people cant add new fuzz locations in 'edit mode'.
It seems to work well with HTTP messages and WebSocket ones (although I've done less testing with those).
It would be better if we didnt have to remove the fuzz locations but in order to handle them we'd need to get edit events from the relevant text areas - this will be _very_ tricky without core changes.

Fuzz: Add edit option

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/zapHomeFiles/scripts/scripts/variant/GraphQL Support.js

Do not attempt to parse empty content as JSON and do not print an error
message for unknown content type.
---
From OWASP ZAP User Group: https://groups.google.com/g/zaproxy-users/c/ZBMWInpSH94/m/qsck-NU2AwAJ

graphql: reduce error messages in input vector

---

addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/callback/CallbackProxyListener.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/callback/CallbackService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/callback/OastRequestFactory.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/callback/CallbackProxyListenerUnitTest.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/callback/CallbackServiceUnitTest.java
testutils/src/main/java/org/zaproxy/zap/testutils/TestUtils.java

Add tests to test the callback server, make it safer to verify the
replacement of the server implementation.

oast: test callback server

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/callback/CallbackProxyListener.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/callback/CallbackProxyListenerUnitTest.java

Change the response to indicate that it contains an empty body and that
the connection will be closed, instead of waiting for a timeout.
Minor tweaks:
- Extract a constant for the response header;
- Do not use a Date to get the current time in milliseconds;
- Let the URI be converted to string when logging.
Update the expected response header in the tests.

oast: close callback connections gracefully

---

addOns/alertFilters/CHANGELOG.md
addOns/alertFilters/alertFilters.gradle.kts
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/automation/AlertFilterJobDialog.java
addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/ActiveScanJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AddOnJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AutomationPanel.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/DelayJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/PassiveScanConfigJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/PassiveScanWaitJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/RequestorJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/SpiderJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/DelayJob.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/DelayJobUnitTest.java
addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/automation/GraphQlJobDialog.java
addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJobDialog.java
addOns/reports/CHANGELOG.md
addOns/reports/reports.gradle.kts
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/ReportJobDialog.java
addOns/soap/CHANGELOG.md
addOns/soap/soap.gradle.kts
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/automation/SoapJobDialog.java

* **When a Job is loaded via yaml and edited via Ui Dialog then the saved changes will be applied on the next job run**
Before running the job there is always an `applyParameters()` which overwrites the fresh changes from the UI Dialog with the yaml input hashmap!
* **DelayJob will be verified on yaml load**
The verification logic used the parameters member, which was not set yet
* **When a Job is edited via Ui Dialog then the status will be set to NOT_STARTED** 
Because the parameters are changed now and the job was running with other parameters before. Therefore the Job Status message includes the old parameters, which is confusing. Would be more clear to the user, that the summary is displayed with the new parameter

automation: bugfixes: DelayJob and apply job changes

---

addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/WebSocketListener.java

Reset the name of the threads when not actively used, keeping the name
of the closed WebSocket channel is misleading.

websocket: reset threads' name returned to pool

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/zapHomeFiles/json/hidden_files.json

Resolved some false positives for the .svn/entries detector triggering on HTML content AND adds the new wc.db file for newer versions of SVN.

Updating Hidden File detector for SVN

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshOptionsPanelTab.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java

Make Interactsh payloads more robust by adding a further char with a dot before the actual correlationId. 
Fixes zaproxy/zaproxy#7003

oast: Make Interactsh payloads more robust

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRuleUnitTest.java

Resolves false positive cases where "error" or "exception" appears in the content body and is not detected because of case sensitivity in the RegEx. Case-insensitive search for error messages.

Updating PathTraversal error checking to be case-insensitive

---

addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/OutOfBandXssScanRule.java
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties

As discussed on IRC,
- Skip the rule if oast is not available or no active scan
oast service is selected.
- Catch IO Exceptions in loops so that all attacks are made.

ascanrulesAlpha: Update OOB XSS Rule

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/ChannelAttributes.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpMessageDecoder.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpRequestDecoder.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpResponseDecoder.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/HttpRequestDecoderUnitTest.java

Set the sender address and if it is secure (using TLS) when decoding
the request, using attributes set on the channel.

network: set request attributes when decoding

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScanRule.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScanRuleUnitTest.java

- SubResourceIntegrityAttributeScanRule > Add functionality to skip tags where rel=canonical is set.
- SubResourceIntegrityAttributeScanRuleUnitTest > Add test method to assert the new behavior.
Fixes zaproxy/zaproxy#7040.

fix: pscanrulesAlpha: SRI False Positive on link rel=canonical

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/CloudMetadataScanRule.java

- CloudMetadataScanRule > Switched from status code attack to checking
the whole message for success state which includes (Custom Pages, Analyser, etc).
Fixes zaproxy/zaproxy#7033.

fix: ascanrulesBeta: Cloud Metadata scan rule address possible FPs

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/cert/SniX509KeyManager.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/cert/SniX509KeyManagerUnitTest.java

Add a key manager that generates server certificates.
Extracted from core class `SSLConnector` and adapted for the add-on.

network: add key manager for server cert gen

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ExponentialEntityExpansionScanRule.java
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/ExponentialEntityExpansionScanRuleUnitTest.java

Closes https://github.com/zaproxy/zaproxy/issues/6671.
The attack payloads were taken from https://en.wikipedia.org/wiki/Billion_laughs_attack.
<details><summary> Testing Code (Vulnerable Python FastAPI Server) </summary>
```python
import yaml
from fastapi import FastAPI
from fastapi.requests import Request
from fastapi.responses import JSONResponse
app = FastAPI()
@app.post(
"/yaml-to-json/",
openapi_extra={"requestBody": {"content": {"application/yaml": {"schema": {}}}}},
)
async def parse_yaml(request: Request):
return JSONResponse(content=yaml.safe_load(await request.body()))
```
</details>
<details><summary>Screenshot</summary>
</details>

ascanrulesAlpha: Add Exponential Entity Expansion Scan Rule

---

addOns/network/network.gradle.kts
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/ChannelGroupHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/ReadTimeoutHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/ServerExceptionHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/TestLogAppender.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/ChannelGroupHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/ReadTimeoutHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/ServerExceptionHandlerUnitTest.java

Add handlers to:
- Keep track of activated channels;
- Produce read timeouts;
- Handle exceptions in the pipeline.
Update Netty and add required dependency.

network: add helper handlers

---

addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/WebSocketEventPublisher.java

Check if the proxy exists when checking if it serves the API, it might
not exist if manually reconnecting to the server.

websocket: address exception on manual reconnect

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/ServerExceptionHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/ServerExceptionHandlerUnitTest.java

Handle `IOException` and log them as debug, these are expected to
happen.
Include the stack trace when logging errors.

network: tweak exception handler

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/ChannelAttributes.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/ReadTimeoutHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/BaseServer.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/ReadTimeoutHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/BaseServerUnitTest.java

Add attribute to indicate if a message is still being processed to
ignore the timeouts and update timeout handler accordingly.
Change the base server to set the attribute.

network: do not timeout while processing message

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsConfig.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsConfigUnitTest.java

Add `hashCode` and `equals` so it can be properly used in other
classes' implementations.

network: add hashCode and equals to TlsConfig

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/BaseServer.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/BaseServerUnitTest.java

Allow to set the channel initialiser after creating the base server to
allow to use the instance's state in the initialiser.

network: make it easier to extend BaseServer

---

addOns/network/network.gradle.kts
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ChannelAttributes.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/RecursiveRequestHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/BaseServer.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/ServerConfig.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/RecursiveRequestHandlerUnitTest.java

Add handler that checks if a message is a request to the server itself,
to prevent forwarding recursive requests.
Change the base server to set the corresponding attribute.

network: add recursive handler

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/LegacyProxyListenerHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/server/HttpMessageHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/server/HttpMessageHandlerContext.java
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/LegacyProxyListenerHandlerUnitTest.java

Add interfaces for handling of HTTP messages in the local servers
provided by the add-on.
Add handler for compatibility with core proxy related listeners to use
existing core and add-on logic in the servers.

network: allow handling of HTTP messages

---

addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/ServerExceptionHandlerUnitTest.java

Check that the log message is present instead of requiring that's the
only one logged, other classes might log as well which would make the
assertion fail even if the message was actually logged.
Remove workaround.

network: correct exception handler's assertions

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java

Rely on the core cert service if running in older versions.

network: use core cert service for older versions

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/CloseOnRecursiveRequestHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/DecodeResponseHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/HandlerState.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpIncludedMessageHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpRequestHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpResponseHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/RemoveAcceptEncodingHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/CloseOnRecursiveRequestHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/DecodeResponseHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpIncludedMessageHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpRequestHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpResponseHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/RemoveAcceptEncodingHandlerUnitTest.java

Add handlers to:
- Close connection if recursive request;
- Remove Accept-Encoding request header;
- Decode the response.
Add helper handlers for common behaviour, e.g. act only on request,
response, and ignore excluded messages.

network: add handlers for proxy

---

addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/oast/CHANGELOG.md
addOns/oast/oast.gradle.kts
addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/callback/CallbackProxyListener.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/callback/CallbackService.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/callback/CallbackProxyListenerUnitTest.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/callback/CallbackServiceUnitTest.java

Replace the usage of core `ProxyServer` and related classes with the
`Server` provided by the add-on.

oast: use server provided by the Network add-on

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/HttPoxyScanRule.java
addOns/ascanrulesBeta/src/main/resources/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties

Change `HttPoxyScanRule` to use the server provided by the network
add-on.

ascanrulesBeta: change rule to use network server

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/MainServerHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpSenderHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/LegacyProxyListenerHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/server/HttpMessageHandlerContext.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/MainServerHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpSenderHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/LegacyProxyListenerHandlerUnitTest.java

Return immediately if a handler overrides the message.
Do not override when setting an error response nor if legacy listeners
set a response to allow other handlers to be notified.
Do not send a message if it already has a response.
Be more clear of the outcome of override and close in the JavaDoc.

network: correct handlers result

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java

Initialise the `LegacyProxyListenerHandler` always, needed for all
proxies (e.g. AJAX Spider) not just the ones in the add-on itself to
support other protocols than HTTP (e.g. WebSocket).

network: init legacy listeners handler always

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/ResourceIdentificationUtils.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/ResourceIdentificationUtilsUnitTest.java

- CHANGELOG > Fixed spacing, didn't add note, attributing this to existing 6810 note.
- ResourceIdentificaitonUtils > Added new method that combines request/response check from core for isImage.
- ResourceIdentificationUtilsUnitTest > Added new test methods to assert the new behavior.

feat: commonlib: Add unified isImage method

---

addOns/domxss/CHANGELOG.md
addOns/domxss/domxss.gradle.kts
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/ExtensionDomXSS.java
addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java

Replace the usage of core `ProxyServer` and related classes with the
proxy provided by the add-on.

domxss: use the proxy from the network add-on

---

addOns/spider/CHANGELOG.md
addOns/spider/gradle.properties
addOns/spider/spider.gradle.kts
addOns/spider/src/main/java/org/zaproxy/addon/spider/ExtensionSpider2.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/SvgHrefSpider.java
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/contents/intro.html
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/helpset.hs
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/index.xml
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/map.jhm
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/toc.xml
addOns/spider/src/main/resources/org/zaproxy/addon/spider/resources/Messages.properties
addOns/spider/src/test/java/org/zaproxy/addon/spider/SvgHrefSpiderUnitTest.java
settings.gradle.kts

Fixes zaproxy/zaproxy#4984
Initial addition of spider add-on with support for parsing HREFs from SVGs.

feat: spider: Add spider add-on with SVG href parsing

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/Application.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParserUnitTest.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScannerUnitTest.java
addOns/wappalyzer/src/test/resources/org/zaproxy/zap/extension/wappalyzer/apps.json

Fixes zaproxy/zaproxy#6607
- Application.java > Add new field, setter, and getter.
- apps.json > Add new simple test entry.
- WappalyzerJsonParser.java > Add handling for building/using a simple string list with DOM selector patterns.
- WappalyzerJsonParserUnitTest.java > Updated test assertions.
- WappalyzerPassiveScanner.java > Updated to handle the new simple DOM selector patterns/functionality.
- WappalyzerPassiveScannerUnitTest.java > Added a test method to test the new simple DOM selector functionality.

feat: wappalyzer: Handle simple DOM selectors

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ExtensionZest.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestAuthenticationRunner.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestScriptWrapper.java
addOns/zest/zest.gradle.kts

Replace the usage of core `ProxyServer` and related classes with the
proxy provided by the add-on for client authentication requests.

zest: use the proxy from network add-on

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRuleUnitTest.java

- TimestampDisclosureScanRule > Slight adjustment to regex to prevent matching of percentage values.
- TimestampDisclosureScanRuleUnitTest > Add additional test to assert the updated behavior.
Fixes zaproxy/zaproxy#7057

fix: pscanrules: Timestamp Disclosure shouldn't alert on percentages

---

addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/PiiScanRule.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java

- Updated various passive scan rules replacing request/response isImage calls with unified commonlib isImage call.
- All relevant add-on CHANGELOGs already contain maintenance notes.
Related to: https://github.com/zaproxy/zap-extensions/pull/3506

chore: various add-ons: leverage new commonlib unified isImage method

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/LocalServersOptions.java
addOns/network/src/main/java/org/zaproxy/addon/network/LocalServersOptionsPanel.java
addOns/network/src/main/java/org/zaproxy/addon/network/NetworkApi.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ChannelAttributes.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/PassThroughHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/MainProxyHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/PassThrough.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/AddPassThroughDialog.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/ModifyPassThroughDialog.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/PassThroughTableModel.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/PassThroughTablePanel.java
addOns/network/src/main/javahelp/help/contents/api.html
addOns/network/src/main/javahelp/help/contents/options/localservers.html
addOns/network/src/main/javahelp/help/contents/options/options.html
addOns/network/src/main/javahelp/help/map.jhm
addOns/network/src/main/javahelp/help/toc.xml
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/LocalServersOptionsUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/NetworkApiUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/PassThroughHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/PassThroughUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/ui/PassThroughTableModelUnitTest.java

Allow to manage pass-through authorities with the UI and API.
Set `PassThroughHandler` as sharable to reuse the same handler in
several proxies.
Correct pass-through word everywhere.
Part of zaproxy/zaproxy#6832.

network: manage pass-through authorities

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/CsrfTokenScanRule.java
addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CsrfCountermeasuresScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CsrfCountermeasuresScanRuleUnitTest.java

- Standardize the risk of CSRF alerts.
- Reduce confidence of pscan alert.
- Add change note to CHANGELOGs.
- Tweak scan rule unit tests where necessary.
Fixes zaproxy/zaproxy#7021

fix: ascanrulesBeta & pscanrules: CSRF alerts Medium Risk

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/LegacyProxiesApi.java
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java

Provide the deprecated `localProxies` endpoints with the add-on to
completely disable the corresponding extension in core.

network: provide localProxies endpoints

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AddAddOnsDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AddOnJobDialog.java
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties

Fixes https://github.com/zaproxy/zaproxy/issues/7075
The problem was that when adding the addons job from the UI the add-ons to add/remove default to `Collections.emptyList()`.
This was then used as is - but the collection is immutable and therefore we got an exception when we tried to add to it.
The fix is to always copy the relevant lists.

Automation: Fix add-ons UI bug

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/server/Server.java
addOns/network/src/main/javahelp/help/contents/cmdline.html
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java

Process the command line arguments `-host` and `-port`, they will be
removed from core.

network: process args -host and -port

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/LocalServersOptions.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/LocalServerInfoLabel.java
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties
addOns/network/src/test/java/org/zaproxy/addon/network/LocalServersOptionsUnitTest.java

Show proxy info (main, enabled, and disabled) in the main footer panel,
similar to what was being done in core.

network: show proxy info in the main footer

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/LocalServersOptionsPanel.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/BaseServer.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/LocalServerConfig.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/BaseServerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/LocalServerConfigUnitTest.java

Use the server itself instead of keeping that in the configuration, let
the extension handle the removal of started servers to later check the
available ports.

network: move the started state to the server

---

addOns/network/src/main/java/org/zaproxy/addon/network/LocalServersOptions.java
addOns/network/src/test/java/org/zaproxy/addon/network/LocalServersOptionsUnitTest.java

Cope with address missing, check the presence of the port instead.
Use all supported protocols if none present.

network: correct core proxy migration

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/ServerExceptionHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/MainServerHandler.java

Reduce logging "noise" when the client does not trust ZAP's Root CA
cert and when not able to write the response because the client
already closed the connection.

network: tweak logging

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/LegacyOptionsPanel.java
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties

Add the old options panel, linking to the new ones, to make migration
easier.

network: add old options panel, link to new ones

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/LocalServersOptions.java
addOns/network/src/test/java/org/zaproxy/addon/network/LocalServersOptionsUnitTest.java

Use `localhost` when migrating core proxy options if the address is not
present, instead of "any address".
Use one of the local addresses when providing the main proxy address to
other extensions, when the main proxy is using "any address".
Set the core proxy address/port when changes are done to the main
proxy.

network: fix issues

---

addOns/replacer/CHANGELOG.md
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ExtensionReplacer.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerParamRule.java

```python
extReplacer = Control.getSingleton().getExtensionLoader().getExtension(ExtensionReplacer.NAME)
initiators = [ ]
replacer_rule = ReplacerParamRule(description=TOKEN_RULE_NAME,enabled=True,initiators=[],matchRegex=False,matchString="AuthenticationToken",matchType=MatchType.REQ_HEADER,replacement=token_value)
extReplacer.getParams().addRule(replacer_rule)
```

replacer: allow to invoke from scripts

---

addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/ui/ReadableFileChooser.java
addOns/commonlib/src/main/resources/org/zaproxy/addon/commonlib/resources/Messages.properties
addOns/exim/CHANGELOG.md
addOns/exim/exim.gradle.kts
addOns/exim/src/main/java/org/zaproxy/addon/exim/ExtensionExim.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarImporter.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/MenuImportHar.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/log/LogsImporter.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/log/MenuItemImportLogs.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/urls/MenuItemImportUrls.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/urls/UrlsImporter.java

exim
- ExtensionExim > Add output error message key constant. Move updateOutput(String, String) out of Log and URL importer classes to reduce code duplication.
- HarImporter, LogsImporter, UrlsImporter > Reduce logging. Display read warning where applicable.
- Messages.properties > Add permissions hint to import error.
commonlib
- Add `ReadableFileChooser`, similar to the core's `WritableFileChooser` a JFileChooser with basic permissions handling/warning dialog.
- Messages.properties > Add supporting resource name/value pairs.
Fixes zaproxy/zaproxy#7081

improve: exim: Reduce logging and handle exceptions

---

.github/workflows/create_eval_villian_update.yml

Related to: zaproxy/zaproxy#7008

fix: Eval Villain workflow follow redirects to save properly

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastRequest.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastServer.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/callback/CallbackProxyListener.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/callback/CallbackService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/boast/BoastServerUnitTests.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/callback/CallbackProxyListenerUnitTest.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/callback/CallbackServiceUnitTest.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/interactsh/InteractshServiceUnitTests.java

Add the following two statistics:
- `stats.oast.<service>.payloadsGenerated`
- `stats.oast.<service>.interactions`
Also use HistoryReference.TYPE_OAST directly instead of assigning it to
a variable and using that.

oast: Add statistics

---

addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/BaseServerUnitTest.java

Wait for the expected condition before asserting it, when restarting
the old connection might not be closed immediately.

network: make test more reliable

---

addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java

Check that the log message is present instead of requiring just that
one in case other messages are logged while the test is executed.

network: make another test more reliable

---

addOns/automation/src/main/java/org/zaproxy/addon/automation/SessionManagementData.java

Bug in https://github.com/zaproxy/zap-extensions/pull/3612
Difficult to unit test but picked up by integration tests:
https://github.com/zaproxy/zaproxy/runs/5290697338?check_suite_focus=true

Automation: fix silly error

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRuleUnitTest.java

I move the detailed alert info into the otherInfo field to keep the rich CSP description. 
Also adds an alertRef to differentiate between all the alerts this plugin may raise.
Updated the Changelog.
Live streamed the whole thing :) https://youtu.be/MqpskwSuSjc

pscanrules: Updated CSP add detailed info into the otherInfo field

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java

Prevent the zap domain from being forwarded, either force to be served
by the API or close the connection if the API is not enabled.
---
From OWASP ZAP User Group: https://groups.google.com/g/zaproxy-users/c/rbRyv8Y_w5s/m/sovP-POqAQAJ

network: make zap domain an alias

---

addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/ui/ProgressPane.java
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/ui/ProgressPaneListener.java
addOns/commonlib/src/main/resources/org/zaproxy/addon/commonlib/resources/Messages.properties
addOns/exim/CHANGELOG.md
addOns/exim/src/main/java/org/zaproxy/addon/exim/ExtensionExim.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/ImportExportApi.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarImporter.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/MenuImportHar.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/log/LogsImporter.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/log/MenuItemImportLogs.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/urls/MenuItemImportUrls.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/urls/UrlsImporter.java
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/Messages.properties
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ProgressListener.java

* commonlib
- ProgressPane.java > Allow to set a "resource" (such as a URL or file system location as part of the pane's title.
- ProgressPaneListener.java > No longer abstract. Provides convenience methods to set the current task and completed status of the associated pane.
- Messages.properties > Key/value pair to support the extended pane title.
* exim
- CHANGELOG.md > Noted the addition of progress panels for URLs and HAR.
- ExtensionExim.java > Depend on commonlib and add convenience method to get the progress panel.
- ImportExportApi.java > Updated to leverage the updated importer functionality.
- HarImporter.java > Updated constructors to allow passing the progress listener. Added functionality to update/display progress.
- MenuImportHar.java > Updated to handle process …

 feat: exim: Add progress bars (openapi: tweak progress bar impl) 

---

addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/BaseServerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/testutils/TestClient.java

Wait for the channels to be closed instead of checking if they are no
longer active.

network: make tests reliable, again

---

addOns/retire/src/main/resources/org/zaproxy/addon/retire/resources/jsrepository.json
addOns/retire/src/test/java/org/zaproxy/addon/retire/UpstreamJsRepositoryUnitTest.java

Fix expected type for CVE entry, array instead of string.
Add test to ensure the `jsrepository.json` can be parsed.

retire: correct retire.js data

---

addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/interactsh/InteractshServiceUnitTests.java

The issue was happening because of a race condition between the test and
the poller which was running in a different thread. They both were
calling the `getInteractions` method which led to the statistic being
incremented twice. When the poller called the method before the test,
the assertion failed because it was only expecting a single increment
but found two.
The fix was to disable the polling thread for the test.

oast: Fix flaky unit test

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/javahelp/help/contents/cmdline.html

Start the main proxy when running in command line mode to allow, for
example, proxy integration tests.

network: start main proxy in command line mode

---

addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java

Move some cleanup from `unload` to `stop`, to ensure it's also done
when ZAP is shutting down not just when the add-on is uninstalled.
---
Reported in IRC channel :)

websocket: stop when shutting down

---

addOns/replacer/CHANGELOG.md
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/HexString.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/OptionsReplacerTableModel.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplaceRuleAddDialog.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerAPI.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerParam.java

- ReplacerRuleAddDialog > Internalize the save that way the modify can still reset the description in the save method while preserving the current state when changing the type.
- other > Address SAST (SonarLit) findings.
Fixes zaproxy/zaproxy#3840

fix: replacer: Allow changing the "type" of rule

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRuleUnitTest.java

- ContentSecurityPolicyScanRule > Tweak unsafe-inline handling.
- ContentSecurityPolicyScanRuleUnitTest > Updated to reflect the new behavior.
Fixes zaproxy/zaproxy#7120

fix: pscanrules: CSP scan rule consider unsafe-inline in default-src

---

.github/workflows/ci.yml
addOns/codedx/CHANGELOG.md
addOns/codedx/src/main/java/org/zaproxy/zap/extension/codedx/security/InvalidCertificateDialogStrategy.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/AbstractFuzzer.java
addOns/graaljs/src/test/java/org/zaproxy/zap/extension/graaljs/PacScriptUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandlerUnitTest.java
addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastService.java

Build with Java 17 which is a LTS version.
Address deprecation warnings:
- Remove Security Manager usage which will be removed in a future
release, JEP 411;
- Replace usage of deprecated methods.
Disable PAC tests on newer Java versions, no longer works (requires
Nashorn classes).

Add Java 17 to CI

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/HeadersGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/generators/HeadersGeneratorUnitTest.java

Generate the Content-Type header in the same order the body is
generated to return the expected value (and prevent exception).
Fix zaproxy/zaproxy#7082.

openapi: correct generation of Content-Type

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/DataGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/generators/DataGeneratorUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/generators/defn-with-query-params.yml

Change `DataGenerator` to check for `content` field in parameters and
generate the data (JSON, fallback to example if other type).
Fix zaproxy/zaproxy#6166.

openapi: support content in parameters

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/BodyGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiValueGeneratorFormatsTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/openapi_formats.yaml

Change `BodyGenerator` to quote string values provided by Form Handler.
Fix zaproxy/zaproxy#7128.

openapi: quote provided strings in JSON

---

addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java

During ZAP startup there's a pause when wappalzer is parsing patterns. Add a start log message so that it's more clear what's going on.

chore: wappalyzer: Add start of parse log message

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/PaddingOracleScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/PaddingOracleScanRuleUnitTest.java

Double check error patterns with an empty value to prevent false
positives with validation fields.
Fix zaproxy/zaproxy#6183.

ascanrulesBeta: address FP in Padding Oracle

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/HiddenFilesScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/HiddenFilesScanRuleUnitTest.java

- HiddenFilesScanRule > No longer follow redirects when making hidden file requests.
- HiddenFilesScanRule > Add a test based on redirects. Correct the path in one existing test (more of a cosmetic or consistency issue ... clean code), also corrected expected vs. actual values in one existing test method.
Fixes zaproxy/zaproxy#7036

fix: ascanrulesBeta: HFF don't follow redirects on HFF requests

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java

To prevent NPEs when editing them.
To reproduce run the ZAP Gui with -autorun and then try to add a job to the plan - its will NPE.

Automation:  Register plans run by -autorun

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/ascanrules.gradle.kts
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ExtensionAscanRules.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PersistentXssPrimeScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PersistentXssScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PersistentXssSpiderScanRule.java
addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/ExtensionCommonlib.java
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/SourceSinkUtils.java

- Add maintenance note to changelogs.
- Move PersistentXssUtils to commonlib, renaming it to SourceSinkUtils.
- Update ascanrules dependant files to use the renamed class.
- Update ascanrules build file to depend on commonlib 1.9.0+.
- Also addressed a few SAST (SonarLint) items in SourceSinkUtils.
- `ReferenceMap` &gt; `AbstractReferenceMap` for static access.
- Private `getCachedItem(Map, String)` method moved to inner class which was the only place it was used.

chore: Relocate PersistentXssUtils

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java
addOns/ascanrules/src/test/resources/org/zaproxy/zap/extension/ascanrules/crosssitescriptingscanrule/InputInScript.html

Do not require a surrounding quote when checking the reflection if
there was none originally.
Caused by #3661.

ascanrules: address FNs in XSS

---

addOns/retest/CHANGELOG.md
addOns/retest/src/main/java/org/zaproxy/addon/retest/ExtensionRetest.java

- ExtensionRetest > Added SessionChangedListener implementation which resets the Retest dialog when the ZAP session changes.
Fixes zaproxy/zaproxy#7147

fix: retest: Use SessionChangedListener to reset between sessions

---

.github/workflows/ci.yml
.github/workflows/sonar.yml
addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/Browser.java
addOns/webdrivers/webdrivermacos/CHANGELOG.md
addOns/webdrivers/webdrivermacos/webdrivermacos.gradle.kts
addOns/webdrivers/webdrivers.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/java/org/zaproxy/gradle/tasks/DownloadWebDriver.java

Updated webdriver manager to 5.1.0
added aarch64/arm64 drivers macos
Fix zaproxy/zaproxy#7008.
Signed-off-by: kcberg <kc.berg@stackhawk.com>

Webdrivers for macos M1

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/automation/GraphQlJob.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/automation/GraphQlJobDialog.java
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/automation/GraphQlJobUnitTest.java

Replace variables present in `schemaFile` when running the automation
job.
---
From OWASP ZAP User Group: https://groups.google.com/g/zaproxy-users/c/XSG4GasGoYY/m/tQt6Kq84CAAJ

graphql: replace vars in schemaFile

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/RemoteFileIncludeScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/RemoteFileIncludeScanRuleUnitTest.java

- RemoteFileIncludeScanRule.java > No longer follow redirects when checking content.
- RemoteFileIncludeScanRuleUnitTest.java > Add tests to assert the updated behavior and increase converage.
Fixes zaproxy/zaproxy#5887

fix: ascanrules: Remote File Inclusion rule no longer follows redirects

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverter.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/OpenApi_defn_servers_empty_default_value.yaml

Properly handle empty default values in server variables.
Signed-off-by: Akshath Kothari <akshath.kothari@levo.ai>

openapi: Fix NPE on empty default server var value

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/BodyGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/generators/BodyGeneratorUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/OpenApi_defn_body_with_json.yaml

Don't enclose JSON body examples in double quotes.
Output of running the new unit tests without the change:
```
Expected :{"foo":"bar"}
Actual   :"{"foo":"bar"}"
```
Discovered when I tried to import https://github.com/kmmanoj96/vulnerable-apis/blob/main/openAPISpecBank.yaml into ZAP.

openapi: Add JSON body examples correctly

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/ui/ProgressPane.java
addOns/exim/CHANGELOG.md
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarImporter.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/MenuImportHar.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/log/LogsImporter.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/urls/UrlsImporter.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/log/LogImporterUnitTest.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/urls/UrlsImporterUnitTest.java

- Log, Urls, and Har importers will now set the progress components as complete even if an exception occurs during import (thus allowing them to be cleared from the progress tab).
- Log import exception handling simplified slightly.
- HAR import will now use an indeterminate progress bar if the count of entries can't be processed for some reason.
- exim/CHANGELOG.md > Added fix note.
- commoblib/CHANGELOG.md > Added maintenance note.
- commonlib/ProgressPane > Fix typo in javadoc and internal variable name in/determinant vs in-determinate.

feat: exim: Importer tweaks

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties

**- Summary**
After a question on IRC, @psiinon suggested I make the change to better reflect what pscanrules actually checks
Follow up to https://github.com/zaproxy/zaproxy-website/pull/886 after feedback from @thc202 
**- Description for the changelog**
Document that rule 10015 applies only to secure content

pscanrules: Specify that rule 10015 applies only to secure content

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/ReportJob.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/ReportJobDialog.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/automation/ReportJobUnitTest.java

Replace variables present in `reportDir` and `reportFile` when running
the automation job.

reports: replace vars in reportDir and reportFile

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanJobUnitTest.java

Setting a rule to enabled changes the threshold from OFF to DEFAULT ;)
https://github.com/zaproxy/zaproxy/blob/c4dcce58e572c078fdb0a7919088343faa4e574b/zap/src/main/java/org/parosproxy/paros/core/scanner/AbstractPlugin.java#L777-L779

Automation: Fix turning off specific active scan rules

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/server/ServerInfo.java
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java

Expose the address/port of the main proxy, to allow other add-ons to
stop using core.
Update changelog with latest changes.

network: provide main proxy info

---

addOns/plugnhack/CHANGELOG.md
addOns/plugnhack/plugnhack.gradle.kts
addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/ExtensionPlugNHack.java
addOns/quickstart/CHANGELOG.md
addOns/quickstart/quickstart.gradle.kts
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/DefaultExplorePanel.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartPanel.java
addOns/selenium/CHANGELOG.md
addOns/selenium/selenium.gradle.kts
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ExtensionZest.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestActiveRunner.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestAuthenticationRunner.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestHttpSenderRunner.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestPassiveRunner.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestProxyRunner.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestScriptWrapper.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestSequenceRunner.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestTargetedRunner.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestZapRunner.java
addOns/zest/zest.gradle.kts

Obtain the main proxy address/port from the Network add-on instead of
core.
The plugnhack and selenium add-ons will now depend on network.

Stop using core for main proxy address/port

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PersistentXssScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/httputils/HtmlContext.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/httputils/HtmlContextAnalyser.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java
addOns/ascanrules/src/test/resources/org/zaproxy/zap/extension/ascanrules/crosssitescriptingscanrule/InputInTextArea.html

A script tag will not run inside a textarea, previously the code would incorrectly report it as an XSS.
As part of this change I've copied HtmlContext and HtmlContextAnalyser from the core - I'll deprecate them in another PR.
Tested against Firing Range (no change) and WebSecLab locally - this fixes 2 of the FP's ZAP currently reports.
The plan is to publish the WebSecLab results on the website.

Ascanrules: Fix XSS false positive in textarea

---

addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/SstiBlindScanRule.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/SstiScanRule.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ssti/DjangoTemplateFormat.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ssti/GoTemplateFormat.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ssti/InputPoint.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ssti/ReflectedSinkPoint.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ssti/SinkPoint.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ssti/StoredSinkPoint.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ssti/TemplateFormat.java
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/SstiBlindScanRuleUnitTest.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/SstiScanRuleUnitTest.java
addOns/ascanrulesAlpha/src/test/resources/org/zaproxy/zap/extension/ascanrulesAlpha/sstiscanrule/ErrorPage.html
addOns/ascanrulesAlpha/src/test/resources/org/zaproxy/zap/extension/ascanrulesAlpha/sstiscanrule/NoInput.html
addOns/ascanrulesAlpha/src/test/resources/org/zaproxy/zap/extension/ascanrulesAlpha/sstiscanrule/Rendered.html

The SSTI scanner is ready.
I have some real tests in https://github.com/DiogoMRSilva/websitesVulnerableToSSTI but I don't know how to integrate them. 
Sorry for the delay and thanks for your help. I look forward to hearing from you.
---
@kingthorin's TODO list:

Add Server Side Template Injection Scan Rule

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRule.java
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/InsecureHttpMethodScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ProxyDisclosureScanRule.java

- CHANGELOGs > Added maintenance note.
- Leverage randomAlphanumeric in cases where the full `a-zA-Z0-9` character set was passed.

chore: Active Scan rules: Leverage lang3 RandomStringUtils methods

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java

This finds a header splitting vulnerability in https://github.com/yahoo/webseclab
Also restructured the XSS scan(..) method to split it up.
The plan was for this to make no changes but I spotted some cases when we exited on finding no HtmlContexts where I think we should just continue to try the next payload, so changed those cases. This hasnt affected the unit tests at all.
I havnt updated the help as its pretty generic but happy to do so if anyone things it would help.

Ascanrules: XSS Header splitting

---

addOns/bugtracker/CHANGELOG.md
addOns/bugtracker/bugtracker.gradle.kts
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerGithub.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerGithubConfigParams.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerGithubParam.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerGithubTableModel.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/DialogAddGithubConfig.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/DialogModifyGithubConfig.java
addOns/bugtracker/src/main/javahelp/org/zaproxy/zap/extension/bugtracker/resources/help/contents/bugtracker.html
addOns/bugtracker/src/main/resources/org/zaproxy/zap/extension/bugtracker/resources/Messages.properties

- Update help to mention tokens along with passwords.
- Update UI and config classes to use "Token" for variables etc where applicable.
- Update CHANGELOG adding change note.
- Update Messages.properties key/value pairs as applicable
- Removed a few unused key/value pairs. (As a clean code activity.)
- Update build file to use the updated library.
Fixes zaproxy/zaproxy#6893

chore: Bugtracker: Address github library deprecations

---

addOns/webdrivers/webdriverlinux/CHANGELOG.md
addOns/webdrivers/webdriverlinux/src/main/javahelp/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
addOns/webdrivers/webdrivermacos/CHANGELOG.md
addOns/webdrivers/webdrivermacos/src/main/javahelp/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
addOns/webdrivers/webdrivers.gradle.kts
addOns/webdrivers/webdriverwindows/CHANGELOG.md
addOns/webdrivers/webdriverwindows/src/main/javahelp/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html

Gecko -> 0.31.0
Chrome -> 100.0.4896.60
- Added change note to CHANGELOGs.
- Updated version in help files.
- Updated version in the build file.

chore: webdrivers: Upgrade Gecko and Chrome drivers

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/scripts/ExtensionOastScripts.java
addOns/oast/src/main/resources/org/zaproxy/addon/oast/resources/Messages.properties

- Add getDescription() and getUIName() methods to ExtensionOast.
- CHANGELOG add change note.
- Messages.properties add supporting key/value pairs.
Before
`12490 [ZAP-BootstrapGUI] INFO org.parosproxy.paros.extension.ExtensionLoader - Initializing ExtensionOast -  ExtensionOast`
After
`11260 [ZAP-BootstrapGUI] INFO org.parosproxy.paros.extension.ExtensionLoader - Initializing Out-of-band Application Security Testing -  Adds Out-of-band Application Security Testing functionality.`

feat: oast: Add Name and Description methods to extension class

---

addOns/network/CHANGELOG.md
addOns/network/src/main/javahelp/help/contents/options/localservers.html
addOns/network/src/main/javahelp/help/contents/options/options.html

Add newline after a quote for proper rendering in the site.
Remove extra space for correct alignment of example commands.
Merge related tables.

network: minor help tweaks

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/ActiveScanJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/EnvironmentDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/PassiveScanConfigJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/RequestorJobDialog.java
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties

Check that a row is selected before attempting to get it.
Disable modify buttons by default, no entries selected to modify
initially.
Add missing resource message, shown when removing a request.

automation: address exceptions in dialogues

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/VerificationData.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/VerificationDataUnitTest.java

I think there is a typo here which causes envs that use `request` as verification method to be generated as contexts with `EACH_RESP`. I have been able to reliably replicate this by creating a new automation plan from YAML using request as verification method.
Sadly, I am not sure how to write a test for this.
There is more context in the [user group](https://groups.google.com/g/zaproxy-users/c/blg_7qu5gTw).

automation: fix: Set authCheckingStrategy to EACH_REQ if the env sets the method to 'request'.

---

addOns/callhome/CHANGELOG.md
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java
addOns/callhome/src/main/resources/org/zaproxy/addon/callhome/resources/Messages.properties

- ExtensionCallHome > Add exception handling for relevant circumstance
Fixes zaproxy/zaproxy#1623

fix: callhome: Handle CA chain failures with more user friendly messages

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/NetworkApi.java
addOns/network/src/main/javahelp/help/contents/api.html
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/NetworkApiUnitTest.java

Provide an API endpoint and shortcut to obtain a PAC file, to move core
functionality.
Part of zaproxy/zaproxy#7240.

network: provide proxy.pac API endpoint

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java

Reset the global HTTP state when the session changes to keep intended
legacy core behaviour.
Related to zaproxy/zaproxy#7243.

network: reset HTTP state on session change

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/ContextDialog.java

Show each context URL in its own line when editing in the GUI, by
calling the method that joins the URLs with newline.
Fix zaproxy/zaproxy#7241.

automation: show context URLs correctly in GUI

---

.github/workflows/create_webdriver_update.yml

- Triggered on schedule every day or manually.
- When triggered manually the version can be specified at trigger time. (In order to work around issues like: mozilla/geckodriver#2009)
- The workflow updates help and build file replacing the version strings as necessary, as well as adding a change note to the CHANGELOGs.

feat: Add GitHub workflow for updating WebDrivers

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/automation/WappalyzerJobResultData.java

Use an empty `ArrayList` instead of `Collections.emptyList()` when the
site is not defined to avoid errors in Thymeleaf when using Java 17.
Part of zaproxy/zaproxy#6880.

wappalyzer: address report generation error

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/ZapAuthenticator.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/ZapProxySelector.java

Set the default authenticator and proxy selector, to replace core
functionality.
Related to zaproxy/zaproxy#7253.

network: set authenticator and proxy selector

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ViewstateScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ViewStateScanRuleUnitTest.java

- pscanrules.html > Added note about threshold handling.
- ViewstateScanRule.java > Minor tweak to conditionals to only raise the "unsure" alert when threshold is Low.
- ViewstateScanRuleUnitTest.java > Add tests to assert the new behavior, and update existing tests as applicable.
Fixes zaproxy/zaproxy#7230

fix: pscanrules: ViewState "unsure" alert only raised at Low threshold

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/HttpFuzzer.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/HttpFuzzerHandlerOptionsPanel.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/HttpFuzzerOptions.java

Remove the call that was disabling circular redirects always, also,
remove code that's no longer used/needed.
Related to zaproxy/zaproxy#7256.

fuzz: allow circular redirects always

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/FormatStringScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ParameterTamperScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ExpressionLanguageInjectionScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionHypersonicScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionMsSqlScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionMySqlScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionOracleScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionPostgreScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionSqLiteScanRule.java

Reduce usage of implementation details, moreover the exception should
no longer be thrown with the change of core (zaproxy/zaproxy#7177), it
will always resolve the redirection to something, the request might
still fail but it would be with a different exception.

Remove handling of redirect exception

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java

Register the jobs when the extension is initialised instead of when the
extension is instantiated, to allow other extensions (e.g. network) to
setup themselves.

automation: delay job registration

---

addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/Browser.java

Restore the fallback to 32bits when checking for bundled WebDrivers to
default to the 32bits ChromeDriver binary.
Fix zaproxy/zaproxy#7272.

selenium: restore usage of bundled ChromeDriver

---

addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/alerts/WebSocketAlertWrapper.java

- WebSockertAlertWrapper > Tweaked logging when Handshake HTTP Message can't be found.
Related to zaproxy/zaproxy#5601

chore: websocket: Tweak Log Message WS Handshake Not Found

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/LegacyConnectionParam.java

Replace core connection API endpoints with custom ones provided by the
add-on.
Part of zaproxy/zaproxy#7281.

network: handle core connection API endpoints

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/LegacyOptionsPanel.java

Use the panels themselves for selection instead of their names which
might not be unique, leading to wrong panel being selected/shown.

network: use the option panels for selection

---

addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties

Remove incorrect escape in a resource message, should be escaping the
newline.

network: remove incorrect escape in message

---

addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ExtensionWebSocket.java
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/pscan/scripts/ScriptsWebSocketPassiveScanner.java
addOns/websocket/src/main/resources/org/zaproxy/zap/extension/websocket/resources/Messages.properties

Cache the passive rules for better performance with all script engines.
Handle the errors that the scripts might cause, which were stopping the
passive scan thread.
Include WebSocket in the error message shown when the script does not
implement the interface to avoid confusions with (HTTP) Passive Rules.
---
Reported in the IRC channel.

websocket: cache passive rules and handle errors

---

addOns/network/src/main/java/org/zaproxy/addon/network/ConnectionOptions.java
addOns/network/src/main/java/org/zaproxy/addon/network/ConnectionOptionsPanel.java
addOns/network/src/main/javahelp/help/contents/options/connection.html
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties
addOns/network/src/test/java/org/zaproxy/addon/network/ConnectionOptionsUnitTest.java

Add option to allow unsafe SSL/TLS renegotiations, to replace core
option.
Related to zaproxy/zaproxy#7294.

network: add unsafe SSL/TLS renegotiation option

---

addOns/retire/CHANGELOG.md
addOns/retire/src/main/java/org/zaproxy/addon/retire/Result.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
addOns/retire/src/test/java/org/zaproxy/addon/retire/RetireScanRuleUnitTest.java

- Result > Add convenience method to get a list of associated CVEs.
- RetireScanRule > Added functionality to add CVEs as alert tags when they're available.
- RetireScanRuleUnitTest > Asserted the new behavior in one unittest.

feat: retire: Include CVEs as Alert Tags when available

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/CloudMetadataScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/CloudMetadataScanRuleUnitTest.java

- CloudMetadataScanRule.java > Updated to attempt multiple payloads. Reduced logging level on exception handling, and allow to continue payloads if an exception is encountered.
- CloudMetadataScanRuleUnitTest.java > Updated in two ways:
- Make UnitTest for non 200 conditions use content that aligns with the response status code.
- Parameterize the 200 condition test to align with and assert the new behavior.

feat: ascanrulesBeta: Leverage aws.zaproxy.org

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/CloseOnRecursiveRequestHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpRequestHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/ZapApiHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/CloseOnRecursiveRequestHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/ZapApiHandlerUnitTest.java

Do not check if the requests are excluded from the proxy in the API
handler, they should be handled even if excluded.
Apply same logic to close on recursive request handler.
Fix zaproxy/zaproxy#7301.

network: handle API requests always

---

addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/RelativePathConfusionScanRule.java
addOns/sqliplugin/CHANGELOG.md
addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLInjectionScanRule.java

Reduce usage of implementation details.
The `CircularRedirectException` should no longer happen, they are now
allowed always (zaproxy/zaproxy#7256).
The `HttpException` would be thrown in very specific cases and for the
scan rule those do not need a different handling than the generic
`IOException` already being caught.

Remove handling of internal exceptions

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html

- Wappalyzer is now part of the Wappalyzer organization, no longer within a personal repo of AliasIO, update help documentation accordingly.

chore: wappalyzer: Update Help URL Reference

---

addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/http/domains/RegexTrust.java
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/http/domains/SameOriginPolicyTrust.java
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/http/domains/Trust.java
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/http/domains/TrustedDomains.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/http/domains/RegexTrustUnitTest.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/http/domains/TrustedDomainsUnitTest.java
addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScanRule.java
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScanRuleUnitTest.java
addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/pscanrulesBeta.gradle.kts
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/LinkTargetScanRule.java
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/LinkTargetScanRuleUnitTest.java

This PR is the refactoring described in #2164 ([More information here](https://github.com/zaproxy/zap-extensions/pull/2164#issuecomment-532258685))
This PR:
- Add a class to manage trusted domains (`rules.domains.trusted` parameter)
- Refactor `LinkTargetScanner` and `SubResourceIntegrityAttributeScanner` to use this class
- Update documentation (pscan*.html) to have only one paragraph about `rules.domains.trusted` parameter and add references from `LinkTargetScanner` and `SubResourceIntegrityAttributeScanner` paragraphs
Comments are welcome. :smirk_cat:

Refactor Trusted Domains into a consistent class

---

addOns/retire/CHANGELOG.md
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/model/Repo.java
addOns/retire/src/main/resources/org/zaproxy/addon/retire/resources/Messages.properties

- Messages.properties > Updated name.
- Repo.java > Added script element extraction for html responses.
- RetireScanRule > Pass Jericho Source object instead of re-creating it.
Fixes zaproxy/zaproxy#6959

retire: Performance adjustment & Minor naming tweak

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/InsecureHttpMethodScanRule.java

Change `InsecureHttpMethodScanRule` to use the `HttpSender` to send the
CONNECT request if the newer implementation is available in the
classpath, to reduce usage of superseded implementation details in
newer versions.

ascanrulesBeta: rely more on newer HttpSender

---

addOns/requester/CHANGELOG.md
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/HttpPanelSender.java

Change `HttpPanelSender` to check the type of the object present in the
message to prevent a class cast exception when it has other types. Also,
close the socket if it has one (i.e. from CONNECT request).

requester: fix class cast exception

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/WebCacheDeceptionScanRule.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/WebCacheDeceptionScanRuleUnitTest.java
testutils/src/main/java/org/zaproxy/zap/testutils/HTTPDTestServer.java

Check that the path exists or it's not a single slash when composing
the new path, otherwise it would add "null" to the domain/port or add
two slashes to the path, e.g.:
- `http://example.org:1234null/test`
- `http://example.org:1234//test`

ascanrulesAlpha: correct path in web cache rule

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/CertificateEntry.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/KeyStoreEntry.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/KeyStores.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/KeyStoresException.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/LaxTrustManager.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/Pkcs11Configuration.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/Pkcs11Driver.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/SingleAliasKeyManager.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/CertificateEntryUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/KeyStoreEntryUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/KeyStoresUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/LaxTrustManagerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/Pkcs11ConfigurationUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/Pkcs11DriverUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/SingleAliasKeyManagerUnitTest.java

Add classes to support the management of client certificates, to stop
relying on core classes which are now deprecated.

network: add classes for client cert management

---

addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/CloudMetadataScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/InsecureHttpMethodScanRule.java

Only rely on the newer `HttpSender` implementation if the core one is
deprecated, otherwise it would fail in the tests since it is still
using the older implementation, even if the newer is available in the
classpath.

ascanrulesBeta: add constraint for new HttpSender

---

addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/schema_component_recursion.yaml

Add test with definition that has component recursion to verify the fix
once the Swagger library is updated.
Adapted example definition provided in the issue.
Part of zaproxy/zaproxy#7346.

openapi: test definition with component recursion

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java

Were getting some scans stuck. The rules that were stuck were always rules that use OAST. After some debugging found out that the thread was getting stuck at the method `registerAlertAndGetPayload()` in the line `alertCache.put(payload, alert);`. This happens very infrequently.

oast: Synchronize alert cache accesses to avoid locks

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJobResultData.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanJobResultDataUnitTest.java

Skip the alerts that might have been removed when building the scan
result.
---
Reported in the OWASP ZAP User Group: https://groups.google.com/g/zaproxy-users/c/PErQlsAl-T8/m/1STkYjQUAAAJ

automation: skip removed alerts for scan result

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/HiddenFilesScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/HiddenFilesScanRuleUnitTest.java

- CHANGELOG > Add, added note.
- HiddenFilesScanRule > Added default payloads for source control paths not already covered by ZAP.
- HiddenFilesScanRule > Updated to account for default payloads in messages sent counts.
Note: 
1. UnitTest wise these are covered by:
`shouldRaiseAlertWithLowConfidenceIfTestedUrlRespondsOkToCustomPayload`
2. These have been added as Custom Payloads as I do not currently have content checks to supplement them.

ascanrulesBeta: Add more source control paths to Hidden File Finder

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/zapHomeFiles/reports/modern/report.html
addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/report.html

Check in the report templates that the `passiveScanData` exists before
using it, it's no available if the automation add-on is not installed.
---
Reported in the OWASP ZAP User Group: https://groups.google.com/g/zaproxy-users/c/PErQlsAl-T8/m/Cd1xsZMcAAAJ

reports: check that the passive scan data exists

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/testutils/TestHttpServer.java

Set the content-length to the response as it is not set when the
corresponding header field is simply added to the header.
This was breaking the download of add-ons bigger than 16MiB.

network: set content-length to response

---

addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java

Ensure the callhome extension is destroyed before the network extension
otherwise it would not be able to send the HTTP requests as the network
extension would be already destroyed.

callhome: set order to the extension

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/LegacyUtils.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/LegacyUtilsUnitTest.java

Check that the cookies being converted actually have an expiry date
before converting it.

network: fix cookie conversion without expiry

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJob.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJobUnitTest.java

…ed the extraneous URL argument now the offending filename is displayed in the error output
Fixes zaproxy/zaproxy#7370
Signed-off-by: Wil Hadden <wilhadden@gmail.com>

openapi: correct job error message on incorrect apiFile

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/httputils/HtmlContextAnalyser.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/httputils/HtmlContextAnalyserUnitTest.java

Was seeing this stacktrace in the most recent update to the XSS rule that was causing the rule to crash and not find the reflected injection.
```
java.lang.StringIndexOutOfBoundsException: begin 3, end 1, length 28
at java.lang.String.checkBoundsBeginEnd(String.java:4604) ~[?:?]
at java.lang.String.substring(String.java:2707) ~[?:?]
at org.zaproxy.zap.extension.ascanrules.httputils.HtmlContextAnalyser.parseTag(HtmlContextAnalyser.java:172) ~[?:?]
at org.zaproxy.zap.extension.ascanrules.httputils.HtmlContextAnalyser.getHtmlContexts(HtmlContextAnalyser.java:308) ~[?:?]
at org.zaproxy.zap.extension.ascanrules.CrossSiteScriptingScanRule.performAttack(CrossSiteScriptingScanRule.java:240) ~[?:?]
at org.zaproxy.zap.extension.ascanrules.CrossSiteScriptingScanRule.performAttack(CrossSiteScriptingSc …
```

ascanrules: correct tag search in HtmlContextAnalyser

---

addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts

Update GraphQL Java to latest version (18.2), which reduces the size of
the add-on (the number of transitive dependencies is lower).
Fix zaproxy/zaproxy#7322.

graphql: update dependency

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRuleUnitTest.java

- ContentSecurityPolicyScanRule > Added example alerts functionality, tweaked alert param details, and bumped confidence up to high.
- ContentSecurityPolicyScanRuleUnitTest > Added a test to assert the expected example alerts.
Related to https://github.com/zaproxy/zaproxy/issues/7100

pscanrules: CSP Scan Rule adjust confidence add example alerts

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRuleUnitTest.java

This is based on https://github.com/zaproxy/zap-extensions/pull/3877, so that one will need to be merged first, then this one rebased.
- CHANGELOG > Added Change note.
- ContentSecurityPolicyScanRule > Updated with new functionality.
- ContentSecurityPolicyScanRuleUnitTest > Added a new test to assert the new behavior.
- Messages.properties > Added supporting key/value pairs.
Fixes zaproxy/zaproxy#7379

pscanrules: CSP rule now raises alerts on non-ASCII policies

---

addOns/formhandler/CHANGELOG.md
addOns/formhandler/formhandler.gradle.kts
addOns/formhandler/src/main/java/org/zaproxy/zap/extension/formhandler/FormHandlerValueGenerator.java
addOns/formhandler/src/test/java/org/zaproxy/zap/extension/formhandler/FormHandlerValueGeneratorUnitTest.java

Check if the provided field ID is invalid (null/empty) and return an
appropriate value, preventing the exception when normalising the ID.
Fix zaproxy/zaproxy#7386.

formhandler: properly handle unidentified fields

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpMessageEncoder.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/HttpMessageEncoderUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/testutils/TestHttpServer.java

Encode and send with UTF-8 instead of ASCII to attempt to preserve the
most data possible.

network: use UTF-8 for the HTTP headers

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ExternalRedirectScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/ExternalRedirectScanRuleUnitTest.java

Related to: https://groups.google.com/g/zaproxy-users/c/n-l-8qj9ggk
- ExternalRedirectScanRule > Updated to be hopefully more accurate.
- ExternalRedirectScanRuleUnitTest > Updated to more fully test functionality.
Tested against wavsep docker, 60 alerts before, 60 after.

ascanrules: External Redirect scan rule accuracy updates

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/contents/automation.html

Ajax Spider: Missing 'user' param in the AF job help

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64DisclosureUnitTest.java

- Base64Disclosure > Added constant defining headers to be ignored and functionality to remove them before analyzing further.
- Base64DisclosureUnitTest > Added tests to assert the updated behavior.
Fixes zaproxy/zaproxy#6619

pscanrulesAlpha: Base64 Disclosure ignore specific headers

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/RemoveTransferEncoding.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Set the Content-Length if the response was chunked, ZAP removes the
Transfer-Encoding header and the chunks, for the client to properly
know the boundary of the response we should set the Content-Length.
Fix zaproxy/zaproxy#5815.

network: set content-length for chunked response

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/main/javahelp/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java
addOns/ascanrules/src/test/resources/org/zaproxy/zap/extension/ascanrules/crosssitescriptingscanrule/example.csv

Related to issue [6617](https://github.com/zaproxy/zaproxy/issues/6617)
I found that content-type tests done [HERE](https://github.com/zaproxy/zap-extensions/blob/fe232e2bda5286eb73910f09a39d6c66fbeb6c87/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java#L692-L746) were not being done [HERE](https://github.com/zaproxy/zap-extensions/blob/fe232e2bda5286eb73910f09a39d6c66fbeb6c87/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java#L269-L290). 
I have added the content-type tests for 'direct attacks' & 'is the payload reflected outside of any tags' attacks (these are the comments above the two attacks I have implemented this feature in). This is because I felt it was best to only show attacks …

ascanrules: check file type for XSS

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/JobUtils.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/JobUtilsUnitTest.java

Use the script wrapper that was added to the node rather than the one
being added as they might be different and the former is the correct
one (e.g. Zest injects its own script wrapper).
---
Issue reported in the OWASP ZAP User Group: https://groups.google.com/g/zaproxy-users/c/a1spgsKb-Qs/m/hd6SFDJmAwAJ

automation: use latest script wrapper added

---

addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlSpiderHelper.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/spider/ExtensionGraphQlSpider.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/spider/GraphQlSpider.java
addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties

Add extension that depends on the spider add-on and adds a custom
spider parser.
Extract common spider parser code into helper class and update existing
parser accordingly.

graphql: use Spider add-on

---

addOns/formhandler/CHANGELOG.md
addOns/formhandler/gradle.properties
addOns/formhandler/src/main/java/org/zaproxy/zap/extension/formhandler/ExtensionFormHandler.java
addOns/formhandler/src/main/resources/org/zaproxy/zap/extension/formhandler/resources/Messages.properties

Allow other add-ons to use the custom value generator without going
through the spider (e.g. importers don't need the spider).
Tweak the description of the extension which was referring just to
spider usage.
Change the add-on version to SemVer.
Related to zaproxy/zaproxy#3113.

formhandler: expose value generator

---

addOns/graphql/graphql.gradle.kts
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ExtensionGraphQl.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlGenerator.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParser.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/MessageValidator.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/formhandler/ExtensionGraphQlFormHandler.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/spider/GraphQlParseFilter.java
addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/GraphQlGeneratorUnitTest.java

Add extension that depends on the Form Handler add-on to use its value
generator.
Add the parse filter to the spider add-on.

graphql: use Form Handler and add parse filter

---

addOns/spider/spider.gradle.kts
addOns/spider/src/main/java/org/zaproxy/addon/spider/ExtensionSpider2.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/formhandler/ExtensionSpiderFormHandler.java
addOns/spider/src/main/resources/org/zaproxy/addon/spider/Messages.properties
addOns/spider/src/test/java/org/zaproxy/addon/spider/formhandler/ExtensionSpiderFormHandlerUnitTest.java

Add extension that depends on the Form Handler add-on to use its value
generator.

spider: use Form Handler add-on

---

addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SvgHrefParser.java
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/contents/spider.html
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SvgHrefParserUnitTest.java

[/test/html/body/svg/image/xlink.found](https://security-crawl-maze.app/test/html/body/svg/image/xlink.found) and [/test/html/body/svg/script/xlink.found](https://security-crawl-maze.app/test/html/body/svg/script/xlink.found) are now handled by the SvgHrefParser.
Related to zaproxy/zaproxy#7152
It looks like a lot of change but it really isn't, it's just that the original SVG file handling was indented another level within a conditional.

spider: Extend SVG handling (crawl maze)

---

addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/formhandler/ExtensionOpenApiFormHandler.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/spider/ExtensionOpenApiSpider.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/spider/OpenApiSpider.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/spider/OpenApiSpiderFunctionality.java
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/Messages.properties
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/formhandler/ExtensionOpenApiFormHandlerUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/spider/ExtensionOpenApiSpiderUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/spider/OpenApiSpiderFunctionalityUnitTest.java

- CHANGELOG > Added change notes.
- Build file > Included spider extension and updated dependencies.
- Separated spider functionality into a static class which is now used by both spider parser implementations (core & add-on).
Part of zaproxy/zaproxy#3113

openapi: Use the Spider add-on when available

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/spider/spider.gradle.kts
addOns/spider/src/main/java/org/zaproxy/addon/spider/automation/ExtensionSpiderAutomation.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/automation/SpiderJob.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/automation/SpiderJobDialog.java
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/contents/automation.html
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/index.xml
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/map.jhm
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/toc.xml
addOns/spider/src/main/resources/org/zaproxy/addon/spider/Messages.properties
addOns/spider/src/main/resources/org/zaproxy/addon/spider/automation/spider-max.yaml
addOns/spider/src/main/resources/org/zaproxy/addon/spider/automation/spider-min.yaml
addOns/spider/src/test/java/org/zaproxy/addon/spider/automation/SpiderJobUnitTest.java

Copy the spider automation job from the automation add-on into the
spider add-on, doing the required changes to work with the add-on
instead of core.
Only add the spider job in the automation add-on if the core spider
extension is not yet deprecated.

spider: add automation job

---

addOns/spider/src/main/java/org/zaproxy/addon/spider/ExtensionSpider2.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderPanel.java

Unload the scan panel to remove the scan status from the footer.

spider: unload the scan panel

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/resources/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties

The link and description for Integer Overflow hadn't been updated in 12 years. Improved the description and added modern links that are both secure to visit and contain information for multiple programming languages and scenarios.
Fix zaproxy/zaproxy#7245.

ascanrulesBeta: Improved text and sources for Integer Overflow

---

addOns/spider/src/main/java/org/zaproxy/addon/spider/ExtensionSpider2.java

Only destroy if the core spider is disabled, otherwise as side effect
it would initialise the scan panel and add the scan status to the
footer.

spider: do not destroy if core spider enabled

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/quickstart.gradle.kts
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/AttackPanel.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/AttackThread.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartPanel.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/TraditionalSpider.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/spider/ExtensionQuickStartSpider.java
addOns/quickstart/src/main/resources/org/zaproxy/zap/extension/quickstart/resources/Messages.properties

Add extension that depends on the spider add-on and adds it to the
attack panel and the attack thread.

quickstart: use Spider add-on

---

addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderParam.java

Use `VersionedAbstractParam` to make it easier to migrate the
configurations.

spider: use versioned param

---

addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java

When the core spider isn't available don't WARN on failure to add custom spider, just DEBUG.

openapi: Reduce logging when core spider not available

---

addOns/exim/CHANGELOG.md
addOns/exim/src/main/java/org/zaproxy/addon/exim/urls/UrlsImporter.java
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/Messages.properties

Related to: https://groups.google.com/g/zaproxy-users/c/hCQAsOIOuSY
Example output:
```console
GET	fed.com/test	"fed.com/test" does not seem to have a scheme.
GET	fred.com/bleh	"fred.com/bleh" does not seem to have a scheme.
GET	https://scanme.nmap.org	Connect to https://scanme.nmap.org:443 [scanme.nmap.org/45.33.32.156] failed: Connection refused: connect
```

exim: Import URLs is now more informative about failures

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CommandInjectionScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CommandInjectionScanRuleUnitTest.java

ZAP reported 22 more CMDi vulnerabilities in OWASP Benchmark with this change :).

ascanrules: CMDi: Decode HTML Entities in Responses

---

addOns/spider/src/main/java/org/zaproxy/addon/spider/ExtensionSpider2.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/ExtensionSpider2UnitTest.java

Do not expose the `SessionChangedListener` through the extension it's
used to manage internal state and not meant for client code to call
directly.

spider: hide session changed listener

---

addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/contents/automation.html
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/contents/dialog.html
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/contents/options.html
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/contents/spider.html
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/contents/tab.html

- Ensure sitemap.xml, SVN metadata, and Git metadata are covered.
- Use capitals on Traditional and Spider where it is used as a name.
- Other minor grammar tweaks.

Spider help tweaks

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRule.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRuleUnitTest.java

- CacheControlScanRule > Adjust confidence to Low.
- CacheControlScanRuleUnitTest > Assested the new confidence, updated  test method names to be more specific.
- Messages.properties > Add new reference.
Fixes zaproxy/zaproxy#6446

pscanrules: Adjust Cache Control scan rule confidence and references

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/HiddenFilesScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/UserAgentScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/HiddenFilesScanRuleUnitTest.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/UserAgentScanRuleUnitTest.java
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/CommonAlertTag.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/CommonAlertTagsUnitTest.java
addOns/custompayloads/CHANGELOG.md
addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/contents/custompayloads.html
addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/pscanrules.gradle.kts
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/UsernameIdorScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/UsernameIdorScanRuleUnitTest.java
addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsFunctionScanRule.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsFunctionScanRuleUnitTest.java

- commonlib > Add new CommonAlertTag "CUSTOM_PAYLOADS". Added convenience method for merging Maps of CommonAlertTags with vargs of CommonAlertTags. CHANGELOG already has a maintenance changes entry.
- custompayloads > Update help to point to the supported scan rules, CHANGELOG add change note.
- ascanrulesBeta > Leverage new alert tag in Hidden File Finder and User Agent scan rules example alerts. Update unit tests as needed. Tweak commonlib dependency in build file. CHANGELOG add change note.
- pscanrules > Leverage new alert tag in Application Error and Username IDOR scan rules example alerts. Update unit tests as needed. Tweak commonlib dependency in build file. CHANGELOG add change note.
- pscanrulesAlpha > Leverage new alert tag in Dangerous JS Function scan rule example alerts. …

Add and leverage "CUSTOM_PAYLOADS" CommonAlertTag

---

addOns/spider/src/main/java/org/zaproxy/addon/spider/ExtensionSpider2.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/OptionsSpiderPanel.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/Spider.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderController.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderDialog.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderEventPublisher.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderMessagesTable.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderPanel.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderParam.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderScan.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderTask.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderThread.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/UrlCanonicalizer.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/filters/DefaultFetchFilter.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderGitParser.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderHtmlFormParser.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderHtmlParser.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderHttpHeaderParser.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderODataAtomParser.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderParser.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderRedirectParser.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderResourceFound.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderRobotstxtParser.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderSitemapXmlParser.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderSvnEntriesParser.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderTextParser.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SvgHrefParser.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/UrlCanonicalizerUnitTest.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderParserUnitTest.java

Remove redundant initialisations.
Remove "init" methods.
Use expected case for constants.
Set constants static and final.
Rename some methods to normalise the case of acronyms.

spider: tidy up

---

addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieHttpOnlyScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieSecureFlagScanRuleUnitTest.java

Specify correct locale when producing dates for the tests.
The month abbreviation for September in GB locale has changed in latest
Java versions (16+, now "Sept" instead of the wanted 3 letters "Sep")
which was causing the incorrect dates to be created.

pscanrules: fix tests in newer Java versions

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/zapHomeFiles/scripts/templates/extender/Copy as curl command menu.js

When investigating and reproducing errors found in zap i found that errors caused by an empty user agent were not reproduce able with this extension due to curl adding the user agent 'User-Agent: curl/version' to any requests without a specified user agent. To fix this I have specified an empty user agent in this case.

scripts: prevent curl from adding User-Agent

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java

- CHANGELOG > Add maintenance note.
- ContentSecurityPolicyScanRule > Extract code blocks from scanHttpResponseReceive in to individual methods for specific checks.
Done in lead-up to: zaproxy/zaproxy#7303

pscanrules: CSP Scan Rule Modularization

---

addOns/graaljs/CHANGELOG.md
addOns/graaljs/src/main/java/org/zaproxy/zap/extension/graaljs/GraalJsEngineWrapper.java

Declare the engine is single threaded, to have the cached scripts
accessed by a single thread at a time.
Fix zaproxy/zaproxy#6992.
---
Depends on zaproxy/zaproxy#7446.

graaljs: declare engine single threaded

---

.github/workflows/sonar.yml

We believe this is not necessary for the job.

Sonar Cloud workflow remove setting GITHUB_TOKEN into env

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Check that the minor HTTP version is present when converting it, in case the message is being sent with just the major version.
Related to zaproxy/zaproxy#7456.

network: correct HTTP version conversion

---

addOns/alertFilters/CHANGELOG.md
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/DialogAddAlertFilter.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/automation/AddAlertFilterDialog.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/internal/ScanRulesInfo.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/internal/ui/ScanRulesInfoComboBoxModel.java

Change the dialogues to show the ID of the scan rules along the name.
Use a specific class to hold the scan rule info to avoid mappings between the names and the IDs.
Fix zaproxy/zaproxy#5699.

alertFilters: include ID when listing scan rules

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyMissingScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyMissingScanRuleUnitTest.java

- CHANGELOG.md > Add change note.
- ContentSecurityPolicyMissingScanRule > Add functionality to validate if CSP is specified via META. Remove unnecessary block comment for functionality now covered by 10055. Remove unnecessary block comment for functionality now covered by 10055.
- ContentSecurityPolicyMissingScanRuleUnitTest > Add a new unit test to assert the new behavior.
- pscanrules.html > Update help entry.
Related to zaproxy/zaproxy#7303

pscanrules: CSP Missing add check for META definition

---

addOns/network/network.gradle.kts

Update the following dependencies:
- Netty, 4.1.73.Final → 4.1.81.Final;
- Bouncy Castle, 1.69 → 1.70.

network: update dependencies

---

addOns/requester/CHANGELOG.md
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ManualRequestEditorPanel.java

Handle `SSLException` separately to report a better error, migration of
core change zaproxy/zaproxy#3204.

requester: improve reporting of TLS errors

---

addOns/pscanrules/CHANGELOG.md

Fix "THe" typo and remove a blank line to be more consistent with other recent entries. Insert missing "Not" in the scan rule name. While this is already released, it doesn't need to persist into the future.

pscanrules: Fix changelog mistake

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ImportFromAbstractDialog.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ImportFromFileDialog.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ImportFromUrlDialog.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/TableOpenApi.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/VariantOpenApi.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJob.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJobDialog.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/OperationModel.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverter.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/PathGenerator.java
addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/contents/automation.html
addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/contents/openapi.html
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/Messages.properties
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/openapi-max.yaml
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/openapi-min.yaml
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApiTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/VariantOpenApiUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJobUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/openapi_slash_node.yaml

Added
- Imported specs are now persisted to the session database. They are used by the new variant to mark path parameters as
Data Driven Nodes.
Changed
- DDNs added as Structural Modifiers have been superseded by a custom variant. The variant supports nested DDNs and leaf
DDNs, prevents non-parameter URL paths from being merged with DDNs, and treats paths with different HTTP methods
uniquely. DDNs are named with the parameter name from the spec.

openapi: Improve Support for DDNs

---

addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/contents/openapi.html

The openapi help pages were not up to date with the latest changes in #3851.

openapi: Update help

---

.github/workflows/release-add-on.yml

Allow to use more memory to avoid out of memory errors when releasing
several add-ons at the same time.

Increase memory for releases

---

addOns/requester/requester.gradle.kts
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/RequesterParam.java
addOns/requester/src/test/java/org/zaproxy/zap/extension/requester/RequesterParamUnitTest.java

Use `VersionedAbstractParam` to make it easier to update the
configurations.

requester: use versioned param

---

addOns/addOns.gradle.kts

Use the Java version defined in the env var when building for ZAP releases.
Part of zaproxy/zaproxy#7478.

Use Java version from env var for releases

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/report-traditional-html-plus.html
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/report-traditional-html.html
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/report-traditional-pdf.html

Correct the ID of reports' sections, adjust the names accordingly.
---
From OWASP ZAP User Group: https://groups.google.com/g/zaproxy-users/c/cX5U-Er1epA/m/5KEnzOY1LwAJ

reports: fix typos in help

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/database/CHANGELOG.md
addOns/database/database.gradle.kts
addOns/database/gradle.properties
addOns/database/src/main/javahelp/help/contents/database.html
addOns/database/src/main/javahelp/help/helpset.hs
addOns/database/src/main/javahelp/help/index.xml
addOns/database/src/main/javahelp/help/map.jhm
addOns/database/src/main/javahelp/help/toc.xml
addOns/spider/spider.gradle.kts
settings.gradle.kts

Add an add-on that provides database engines, currently SQLite.
Change the `ascanrulesBeta` and `spider` add-ons to depend on it, to no
longer rely on core.
Part of zaproxy/zaproxy#3113
---
Opted to add a new add-on as we could move the scan rule and the spider parser to the add-on instead of having the other two add-ons depend on it.
The add-on can also be used to provide SQLite for the session/permanent database in the future.
Also happy to move it to `commonlib` instead.

Add database add-on

---

addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/JobUtils.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PassiveScanConfigJob.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/JobUtilsUnitTest.java

The change to use postInit is to allow other add-ons (like ajaxSpider) to register job types first.

Automation: misc minor fixes

---

addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java

Allow one more request to prevent failures.
---
e.g.: https://github.com/zaproxy/zap-extensions/actions/runs/3184317359/jobs/5193002934#step:7:443

domxss: increase allowed requests in tests

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java
addOns/requester/CHANGELOG.md
addOns/requester/src/main/java/org/zaproxy/addon/requester/internal/HttpPanelSender.java
addOns/requester/src/main/java/org/zaproxy/addon/requester/internal/ManualHttpRequestEditorPanel.java

Notify the persistent connection listeners when sending the messages to allow other add-ons (e.g. WebSocket) to take over the connection.
Remove code no longer needed.
Change network add-on to allow to notify the persistent connection listeners through the message being sent.

requester: notify persistent connection listeners

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ForbiddenBypassScanRule.java
testutils/src/main/java/org/zaproxy/zap/testutils/ActiveScannerTestUtils.java
testutils/src/main/java/org/zaproxy/zap/testutils/PassiveScannerTestUtils.java

Test that the scan rules create the example alerts without issues.
Fix an exception in `ForbiddenBypassScanRule`.

Test example alerts

---

.github/workflows/ci.yml

Prevent warnings in newer Java versions from being introduced to the codebase.
Related to zaproxy/zaproxy#7389.

Add Java 18 to CI

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScanRule.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScanRuleUnitTest.java
addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ServerHeaderInfoLeakScanRule.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/ServerHeaderInfoLeakScanRuleUnitTest.java

- Rework scan rules to have example alerts and use related alert builder methods.
- Include Unit Test methods to assert the example alert collections.
- Include change note in CHANGELOGs
Part of zaproxy/zaproxy#6119
Fixes zaproxy/zaproxy#7502

pscanrulesAlpha and pscanrulesBeta: Add example alerts

---

addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ServerHeaderInfoLeakScanRule.java

Follow-up to: https://github.com/zaproxy/zap-extensions/pull/4097/
Discussed in: https://github.com/zaproxy/zaproxy-website/pull/1337
CHANGELOGs already have maint note.

pscanrulesAlpha & Beta: Remove unnecessary setUri on example alerts

---

addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-requestor.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help_sr_CS/contents/job-requestor.html
addOns/scripts/scripts.gradle.kts

Relocate help accidentally added to a translation file to the main help file.
Update minimum version of automation in scripts, using newer features.

Relocate help and update minimum add-on version

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/ZapHttpRequestExecutor.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/MainServerHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/MainServerHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/testutils/TestHttpServer.java

Close the client side connection if the server side closed the connection otherwise it could be kept open longer than needed.
Fix zaproxy/zaproxy#7292.

network: close client conn if server closed

---

addOns/encoder/CHANGELOG.md
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/EncodeDecodeProcessors.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/FullHtmlStringEncoder.java
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/contents/encoder.html
addOns/encoder/src/main/resources/org/zaproxy/addon/encoder/resources/Messages.properties
addOns/encoder/src/main/resources/org/zaproxy/addon/encoder/resources/encoder-default.xml

- EncodeDecodeProcessors > Accommodate new encoder.
- encoder-default.xml > Accommodate new encoder.
- encoder.html > Added associated help content.
- FullHtmlStringEncoder > Newly added encoder which encodes all characters in a script not just HTML entities.
- Messages.properties > Added support key/value pair for the panel title.
Along with the customizability of the encoder add-on I believe this fixes zaproxy/zaproxy#2222.
Note: No accompanying decoder was added as the existing HTML Decoder already handles this.

encoder: Add Full HTML Entity encoder

---

addOns/spider/src/main/java/org/zaproxy/addon/spider/ExtensionSpider2.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/automation/ExtensionSpiderAutomation.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/ExtensionSpider2UnitTest.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderParserTestUtils.java

The core checks are no longer needed.
Use the help key of the add-on.

spider: remove core spider checks

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/spider/ExtensionQuickStartSpider.java

Remove the core spider usage that managed the spider scan.
Related to zaproxy/zaproxy#3113.

quickstart: remove core spider usage

---

addOns/formhandler/CHANGELOG.md
addOns/formhandler/src/main/java/org/zaproxy/zap/extension/formhandler/ExtensionFormHandler.java

Remove the code that un/set the value generator to the core spider, the other add-ons are now obtaining the value generator directly.
Related to zaproxy/zaproxy#3113.

formhandler: remove core spider usage

---

addOns/requester/CHANGELOG.md
addOns/requester/src/main/java/org/zaproxy/addon/requester/ExtensionRequester.java

The core extension checks are no longer needed, the features provided by the add-on should be added always as it's no longer targeting 2.11.
Tweak the changelog to no longer mention 2.11.

requester: remove core extension checks

---

addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html

Missed from https://github.com/zaproxy/zap-extensions/pull/4118

PScan Rules - move trusted domain help

---

addOns/encoder/encoder.gradle.kts
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/FullHtmlStringEncoder.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/FullHtmlStringEncoderUnitTest.java

- FullHtmlStringEncoder > Set the string builder's initial size to input length times 6 (assuming code point is 3 digits and we add 3 characters to each).
- FullHtmlStringEncoderUnitTest > Add tests for the new encoder.
- encoder.gradle.kts > Add testutils dependency.
Follow-up to: https://github.com/zaproxy/zap-extensions/pull/4103

encoder: Full HTML Entity encoder add unit tests and size string builder

---

addOns/network/CHANGELOG.md
addOns/network/src/main/javahelp/help/contents/api.html
addOns/network/src/main/javahelp/help/contents/cmdline.html
addOns/network/src/main/javahelp/help/contents/options/clientcertificates.html
addOns/network/src/main/javahelp/help/contents/options/connection.html
addOns/network/src/main/javahelp/help/contents/options/localservers.html
addOns/network/src/main/javahelp/help/contents/options/options.html
addOns/network/src/main/javahelp/help/contents/options/servercertificates.html

Remove references in the help pages to 2.11.
Update changelog with newer additions.

network: tidy up for newer main release

---

addOns/addOns.gradle.kts
addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/database/CHANGELOG.md
addOns/database/database.gradle.kts
addOns/database/src/main/java/org/zaproxy/addon/database/Database.java
addOns/database/src/main/java/org/zaproxy/addon/database/PermanentDatabase.java
addOns/oast/CHANGELOG.md
addOns/oast/oast.gradle.kts
addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastEntity.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastParam.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastState.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastEntity.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastPoller.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastServer.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshOptionsPanelTab.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshPoller.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/ui/GeneralOastOptionsPanelTab.java
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/options.html
addOns/oast/src/main/resources/META-INF/package-hsql.orm
addOns/oast/src/main/resources/META-INF/persistence.xml
addOns/oast/src/main/resources/db/migration/V1__Create_table_boast.sql
addOns/oast/src/main/resources/org/zaproxy/addon/oast/resources/Messages.properties

Here is an overview of the changes in this PR (click to expand):
<details><summary>Datanucleus</summary>
[Datanucleus](https://www.datanucleus.org/) allows mapping java classes to tables in a database. This makes it convenient to interact with data simply by interacting with java objects.
- `addOns/addOns.gradle.kts`: The datanucleus gradle plugin is added here. Datanucleus modifies Java bytecode to add methods to classes with appropriate annotations. For this, it provides a tool called an "enhancer" that does this. The [unofficial gradle plugin](https://datanucleus-gradle-plugin.rm3l.org/) used here adds enhancement tasks to all the add-ons. While they can be called manually, annotated classes are automatically enhanced during building which is convenient.
</details> …

Add Permanent Database Support

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/Text4ShellScanRule.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/Text4ShellScanRuleUnitTest.java

- Text4ShellScanRule > Add an Alert Tag specifically for the CVE.
- Text4ShellScanRuleUniTest > Add a test to assert the expected number of alert tags.

ascanrulesAlpha: Text4shell - Add CVE Alert Tag

---

addOns/retest/CHANGELOG.md
addOns/retest/src/main/java/org/zaproxy/addon/retest/RetestPlanGenerator.java
addOns/retest/src/test/java/org/zaproxy/addon/retest/RetestAPIUnitTest.java
addOns/retest/src/test/java/org/zaproxy/addon/retest/RetestPlanGeneratorUnitTest.java

Use the name of the enum instead of its localized name, otherwise it would fail for localized languages.
Remove unnecessary test setup code which was also hiding the issue.

retest: fix plan generator

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java

The `HttpSender` implementation is used by core and other add-ons.

network: do not allow to dynamically unload

---

addOns/portscan/CHANGELOG.md
addOns/portscan/portscan.gradle.kts
addOns/portscan/src/main/java/org/zaproxy/zap/extension/portscan/ExtensionPortScan.java
addOns/portscan/src/main/java/org/zaproxy/zap/extension/portscan/PortScan.java

Use the network add-on to obtain the outgoing proxy instead of core, the latter is deprecated.

portscan: use network add-on for outgoing proxy

---

addOns/network/src/main/java/org/zaproxy/addon/network/common/ZapSocketTimeoutException.java
addOns/network/src/main/java/org/zaproxy/addon/network/common/ZapUnknownHostException.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Change network add-on to throw exceptions with more information, for timeouts include its value and for unknown host names whether it was while resolving the proxy's host.

network: provide exceptions with more info

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/ascanrules.gradle.kts
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRule.java
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ProxyDisclosureScanRule.java

Catch the exception provided by the network add-on instead of checking the connection options to know the value of the timeout.

Use network exception in active scan rules
