addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportDialog.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportParam.java

Replace string concatenations with parameterized messages.

reports: log with parameterized messages

---

addOns/reports/CHANGELOG.md

reports: remove duplicated section in changelog

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/BufferOverflowScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CodeInjectionScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrlfInjectionScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/DirectoryBrowsingScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/BufferOverflowScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CodeInjectionScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrlfInjectionScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/DirectoryBrowsingScanRuleUnitTest.java
addOns/ascanrules/src/test/resources/org/zaproxy/zap/extension/ascanrules/directorybrowsingscanrule/DirectoryListing.html
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/IntegerOverflowScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionSqLiteScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/XpathInjectionScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/IntegerOverflowScanRuleUnitTest.java
addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/InsecureFormLoadScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/InsecureFormPostScanRule.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/InsecureFormLoadScanRuleUnitTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/InsecureFormPostScanRuleUnitTest.java

Fix [zaproxy/zaproxy#6563](https://github.com/zaproxy/zaproxy/issues/6563).

Add and improve alerts evidences and attack values

---

addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java

fix: wappalyzer typo

---

addOns/reports/CHANGELOG.md
addOns/reports/reports.gradle.kts
addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportApi.java
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/api.html
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/reports.html
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/index.xml
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/map.jhm
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/toc.xml
addOns/reports/src/main/resources/org/zaproxy/addon/reports/resources/Messages.properties
addOns/reports/src/test/java/org/zaproxy/addon/reports/ReportApiUnitTest.java

- Add basic API support.
Part of https://github.com/zaproxy/zaproxy/issues/6483.
<details>
<summary> Screenshot of API Web UI (Action Generate) </summary>
</details>

reports: API Support

---

addOns/ascanrules/CHANGELOG.md

Follow-up to https://github.com/zaproxy/zap-extensions/pull/2905

ascanrules: Add missed CHANGELOG entry

---

addOns/reports/CHANGELOG.md
addOns/reports/reports.gradle.kts

Reports: promote to beta and release

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/WebCacheDeceptionScanRule.java
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/WebCacheDeceptionScanRuleUnitTest.java

- Added WebCacheDeception scan rule.
- Added Unit Test.
- Added CHANGELOG notes.
Ref https://github.com/zaproxy/zaproxy/issues/6263
Signed-off-by: nikolai6303 <iit2018152@iiita.ac.in>

Create WebCacheDeception scan rule

---

addOns/reports/CHANGELOG.md
addOns/reports/reports.gradle.kts

Reports: prepare for the next dev iteration

---

addOns/automation/CHANGELOG.md
addOns/automation/automation.gradle.kts
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationEnvironment.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/environment.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/env.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationEnvironmentUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationJobUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-config.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml

Introduce the use of custom/environment variables in the config file.
Add tests and update documentation.
Part of zaproxy/zaproxy#6461

Add variable support for automation framework

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/ascanrules.gradle.kts
addOns/commonlib/CHANGELOG.md
addOns/commonlib/commonlib.gradle.kts

Ascanrules, commonlib: Prepare next dev iteration

---

.gitignore

Ignore the `.DS_Store` files, created by macOS.

Ignore macOS file

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/impl/PayloadsDialog.java

Use the Payloads dialogue as the parent of Add Payload dialogue.

fuzz: correct parent dialogue

---

addOns/wappalyzer/src/main/resources/org/zaproxy/zap/extension/wappalyzer/resources/apps.json

Correct CSS selectors which were causing exceptions.
Ref zaproxy/zaproxy#6607.

wappalyzer: correct CSS selectors

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportHelper.java
addOns/reports/src/main/zapHomeFiles/reports/traditional-xml/report.xml

Fixes https://github.com/zaproxy/zaproxy/issues/6627

Include all relevant alerts in XML report templates

---

addOns/tips/CHANGELOG.md
addOns/tips/tips.gradle.kts

tips: prepare next dev iteration

---

addOns/fuzz/CHANGELOG.md

Fuzz: Prepare release 13.2.0

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportHelper.java
addOns/reports/src/main/zapHomeFiles/reports/traditional-json/report.json
addOns/reports/src/main/zapHomeFiles/reports/traditional-json/template.yaml
addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/ReportHelperUnitTest.java

Depends on #2951 - will refactor this once thats merged.

Reports: Add traditional JSON report

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/zapHomeFiles/scripts/templates/extender/Add toolbar button.js

scripts: update link to community-scripts repo

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/report.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-html-plus.html

Also qualified the ids with "plugin-" and "alert-" - these were conflicting :/
Note that this will impact #2961

Reports: Traditional plus report - link to zaproxy.org pages for passing rules

---

addOns/automation/automation.gradle.kts
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJobException.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationProgress.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationEnvironmentUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testplan-sametype.yaml

Automation: fixed bug re jobs with same type

---

addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJob.java

Ajax Spider - fix automation context url

---

addOns/reports/src/main/java/org/zaproxy/addon/reports/HttpStatusReason.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportHelper.java

Use up-to-date listing of reasons, as defined in the registry.

reports: use up-to-date status reasons

---

addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanJobUnitTest.java

Automation - Fix NPE in ascan job

---

addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/automation.html

Automation : Help tweak

---

addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportHelper.java
addOns/reports/src/main/zapHomeFiles/reports/traditional-json/report.json
addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-html-plus.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-html.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-json.json
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-md.md
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-xml.xml

Double quotes broke JSON reports :(

Reports: JSON double quote fix

---

addOns/wappalyzer/CHANGELOG.md

Tweak "Added" header to level 3, merge two separate "Changed" sections.

fix: wappalyzer changelog 21.2.0

---

addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportDialog.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportParam.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/ReportParamUnitTest.java

And sort the template names alphabetically.

Reports: Default to modern template

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AbstractAutomationTest.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationStatisticTest.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/SpiderJob.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-spider.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/tests.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/index.xml
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/map.jhm
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/toc.xml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/spider-max.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/spider-min.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationStatisticTestUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/SpiderJobUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-config.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testPlan-failOnLoggedTestError.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testPlan-withTests.yaml
addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJob.java
addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/contents/automation.html
addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/spiderAjax-max.yaml
addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/spiderAjax-min.yaml
addOns/spiderAjax/src/test/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJobUnitTest.java

- Only stats tests are supported for now.
- Part of zaproxy/zaproxy#6496
<details>
<summary> Simple UML diagram </summary>
</details>

automation: Add support for tests

---

addOns/accessControl/CHANGELOG.md
addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/ExtensionAccessControl.java

AccessControl: no longer rely on core reports

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PassiveScanConfigJob.java
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/PassiveScanConfigJobUnitTest.java

Automation: Fix NPE in pscan job with no rule id

---

addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/ExtensionReportAutomation.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/OutputSummaryJob.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/ReportJob.java

Reports - use right path for outputSummary job templates

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/BodyGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/generators/BodyGeneratorUnitTest.java

Reported via https://groups.google.com/g/zaproxy-users/c/Bl2AvQek8ts/m/nk69dfW-BgAJ

OpenAPI: Fixed NPE if form has no schema element

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/RequestorJob.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/automation.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-requestor.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/requestor-max.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/requestor-min.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/RequestorJobUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-config.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml

Add a new requestor job to the automation framework, allowing users to
make specifically crafted requests to targets.

automation: Add new requestor Job

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/OperationHelper.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/network/RequestMethod.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/network/RequestorUnitTest.java

Fixes https://github.com/zaproxy/zaproxy/issues/6666

fix: RequestMethod typo

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AbstractAutomationTest.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationAlertTest.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationStatisticTest.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/JobResultData.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJobResultData.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PassiveScanJobResultData.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/tests.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/activeScan-max.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/activeScan-min.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/passiveScan-wait-max.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/passiveScan-wait-min.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationAlertTestUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationStatisticTestUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanJobResultsUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/PassiveScanJobResultsUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/SpiderJobUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml

Added new alert tests to validate the presence/absence of specific alerts in the active/passive scan.
Modified the PassiveScanJobResultData and ActiveScanJobResultData classes to store the alerts raised during the passive/active scan. Added tests to verify the logic added and updated the Changelog.

automation: Add alert tests

---

addOns/addOns.gradle.kts

Update plugin to latest version to fix the issue with empty files.

Update Gradle Crowdin plugin

---

addOns/oast/CHANGELOG.md
addOns/oast/gradle.properties
addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastPoller.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastService.java

Sorry there are already issues, my bad for not testing the add-on after yesterday's changes.
- Requests were not showing up in the OAST Callbacks panel.
- BOAST servers were not being polled after registration.

oast: Fix issues

---

addOns/automation/CHANGELOG.md
addOns/automation/gradle.properties

Update version and changelog for:
- Automation Framework

Prepare next dev iteration(s)

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/OutputSummaryJob.java

Reports: Address errors when running the OutputSummary job

---

addOns/oast/CHANGELOG.md
addOns/oast/oast.gradle.kts
addOns/oast/src/main/java/org/zaproxy/addon/oast/scripts/ExtensionOastScripts.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastPoller.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastService.java
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/oast.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/services/boast/boast.html
addOns/oast/src/main/resources/org/zaproxy/addon/oast/resources/Messages.properties
addOns/oast/src/main/zapHomeFiles/scripts/scripts/standalone/OAST Get BOAST Servers.js
addOns/oast/src/main/zapHomeFiles/scripts/templates/standalone/OAST Register Request Handler.js

Add two scripts that demonstrate how to interact with this add-on:
- OAST Register Request Handler.js (Template)
- OAST Get BOAST Servers.js

oast: Add example scripts

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/ui/OastPanel.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/ui/OastTableModel.java
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/oast.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/services/boast/boast.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/services/boast/options.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/services/callbacks/callbacks.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/services/callbacks/options.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/tab.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/index.xml
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/map.jhm
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/toc.xml
addOns/oast/src/main/resources/org/zaproxy/addon/oast/resources/Messages.properties

- Renamed the "OAST Callbacks" tab to "OAST".
- Updated help pages.

oast: Updates

---

addOns/oast/CHANGELOG.md
addOns/oast/gradle.properties

oast: Release add-on

---

addOns/automation/gradle.properties
addOns/retest/gradle.properties

Reset the state to trigger a new release after.

Reset release state of automation and retest

---

addOns/automation/gradle.properties
addOns/retest/gradle.properties

Set the release state of the add-ons.

Trigger release of automation and retest

---

addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/alerts/WebSocketAlertWrapper.java
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/pscan/WebSocketScanHelperImpl.java
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/pscan/scripts/WebSocketPassiveScript.java
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Application Error Scanner.js
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Base64 Disclosure.js
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Debug Error Disclosure.js
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Email Disclosure.js
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/PII Disclosure.js
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Private IP Disclosure.js
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Username Idor Scanner.js
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/XML Comments Disclosure.js

So far just changes one script - that look ok before I change the rest?

Websockets - support examples for pscan scripts

---

addOns/jsonview/CHANGELOG.md
addOns/jsonview/src/main/java/org/zaproxy/zap/extension/jsonview/HttpPanelJsonView.java

Related to zaproxy/zaproxy#2000

improve: jsonview: capitalize menu entry

---

addOns/soap/CHANGELOG.md
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SitesTreeHelper.java

Include the exception when logging.

fix: soap: User proper class in logger declaration

---

addOns/webdrivers/webdriverlinux/CHANGELOG.md
addOns/webdrivers/webdriverlinux/src/main/javahelp/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
addOns/webdrivers/webdrivermacos/CHANGELOG.md
addOns/webdrivers/webdrivermacos/src/main/javahelp/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
addOns/webdrivers/webdrivers.gradle.kts
addOns/webdrivers/webdriverwindows/CHANGELOG.md
addOns/webdrivers/webdriverwindows/src/main/javahelp/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html

Update ChromeDriver to 93.0.4577.15.

webdrivers: update ChromeDriver

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java

Found while adding integration tests for zaproxy/zaproxy#6781 

Reports: Fix alert counts to ignore false positives

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/resources/org/zaproxy/zap/extension/fuzz/resources/Messages.properties

fuzz: fix typo

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java

Found while adding integration tests for https://github.com/zaproxy/zaproxy/pull/6781

Reports: Ignore FPs when listing messages in outputSummary job

---

addOns/webdrivers/webdriverlinux/CHANGELOG.md
addOns/webdrivers/webdriverlinux/src/main/javahelp/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
addOns/webdrivers/webdrivermacos/CHANGELOG.md
addOns/webdrivers/webdrivermacos/src/main/javahelp/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
addOns/webdrivers/webdrivers.gradle.kts
addOns/webdrivers/webdriverwindows/CHANGELOG.md
addOns/webdrivers/webdriverwindows/src/main/javahelp/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html

webdrivers: update geckodriver

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/tests/AbstractAutomationTest.java

Remove unnecessary semicolon after method body.

automation: remove unnecessary semicolon

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/PlanTreeTableModel.java

"Unexpected obj object java.lang.String" shown when attempting to get a value for the root node.

Automation: fixed startup error

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/scripts/ExtensionOastScripts.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastOptionsPanelTab.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshEvent.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshException.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshOptionsPanelTab.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshParam.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshPoller.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/services/boast/options.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/services/interactsh/interactsh.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/services/interactsh/options.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/index.xml
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/map.jhm
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/toc.xml
addOns/oast/src/main/resources/org/zaproxy/addon/oast/resources/Messages.properties
addOns/oast/src/main/zapHomeFiles/scripts/scripts/standalone/OAST Get Interactsh Payloads.js
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/interactsh/InteractshEventUnitTests.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/interactsh/InteractshParamUnitTests.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/interactsh/InteractshServiceUnitTests.java

oast: Support interactsh

---

addOns/reports/CHANGELOG.md
addOns/reports/reports.gradle.kts

Reports: promote to release

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ChallengeCallbackImplementor.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/XxeScanRule.java
addOns/ascanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/XxeScanRuleUnitTest.java

Signed-off-by: Akshath Kothari <ricekot@gmail.com>

ascanrulesBeta: Use OAST callbacks

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationAPI.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationPlan.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/automation.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties

The plan is to promote this to beta and release it after this PR is merged - any objections?

Automation API support: runplan action and planprogress view

---

addOns/selenium/CHANGELOG.md
addOns/selenium/selenium.gradle.kts
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/PopupMenuItemOpenInBrowser.java

As per core menu to open URL in system browser, even uses the same message ;)

Selenium: Disable browser launch in containers unless override option enabled

---

addOns/reports/CHANGELOG.md
addOns/reports/reports.gradle.kts
addOns/reports/src/main/resources/org/zaproxy/addon/reports/resources/Messages.properties
addOns/reports/src/main/zapHomeFiles/reports/modern/report.html
addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/report.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-html-plus.html

Need to fix the tests, for some reason its not picking up the alert tags :/

Reports: Support alert tags

---

addOns/alertFilters/CHANGELOG.md
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java

AlterFilter: Add stats for alerts changed

---

addOns/imagelocationscanner/CHANGELOG.md
addOns/imagelocationscanner/imagelocationscanner.gradle.kts
addOns/imagelocationscanner/src/main/java/org/zaproxy/zap/extension/imagelocationscanner/ImageLocationScanRule.java
addOns/imagelocationscanner/src/test/java/org/zaproxy/zap/extension/imagelocationscanner/ImageLocationScanRuleUnitTest.java
addOns/retire/CHANGELOG.md
addOns/retire/retire.gradle.kts
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
addOns/retire/src/test/java/org/zaproxy/addon/retire/RetireScanRuleUnitTest.java

- Add Top 10 mappings.
- Update build files with commonlib dependency.
- Update unit tests.
- Update changelogs.
- ILS add example alert.

improve: ils & retire: Add Top10 Mappings, ils add example alert

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/BodyGenerator.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/DataGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/BodyGeneratorUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/Schema_invalid_property_type.yaml

Fix for StackOverflow in the Body/DataGenerator when an invalid openapi property type is specified.
Here is an example of the exception...
```
java.lang.StackOverflowError
at org.apache.logging.log4j.core.Logger$PrivateConfig.filter(Logger.java)
at org.apache.logging.log4j.core.Logger.isEnabled(Logger.java:197)
at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1914)
at org.apache.logging.log4j.spi.AbstractLogger.debug(AbstractLogger.java:463)
at org.zaproxy.zap.extension.openapi.generators.ValueGenerator.getValue(ValueGenerator.java:43)
at org.zaproxy.zap.extension.openapi.generators.DataGenerator.generateValue(DataGenerator.java:160)
at org.zaproxy.zap.extension.openapi.generators.DataGenerator.generateBodyValue(DataGenerator.java:142)
at …
```

openapi: fix StackOverflow in Body/DataGenerator

---

addOns/soap/CHANGELOG.md
addOns/soap/soap.gradle.kts
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanRule.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPXMLInjectionActiveScanRule.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/WSDLFilePassiveScanRule.java

soap: Add OWASP Top 10 alert tags

---

addOns/reports/reports.gradle.kts
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportParam.java
addOns/reports/src/main/zapHomeFiles/reports/risk-confidence-html/report.html
addOns/reports/src/test/java/org/zaproxy/addon/reports/ReportParamUnitTest.java

Removed report from the spotless checks and corrected it, hopefully as per #3188
Also made this the default report :D

Reports: risk-confidence-html tweaks

---

addOns/quickstart/gradle.properties
addOns/replacer/gradle.properties
addOns/retest/gradle.properties
addOns/retire/gradle.properties
addOns/reveal/gradle.properties
addOns/saverawmessage/gradle.properties
addOns/savexmlmessage/gradle.properties
addOns/scripts/gradle.properties
addOns/selenium/gradle.properties
addOns/soap/gradle.properties
addOns/spiderAjax/gradle.properties
addOns/tips/gradle.properties
addOns/webdrivers/webdriverlinux/gradle.properties
addOns/webdrivers/webdrivermacos/gradle.properties
addOns/webdrivers/webdriverwindows/gradle.properties
addOns/websocket/gradle.properties
addOns/zest/gradle.properties

Resetting the release state again

---

addOns/spiderAjax/gradle.properties
addOns/tips/gradle.properties
addOns/webdrivers/webdriverlinux/gradle.properties
addOns/webdrivers/webdrivermacos/gradle.properties
addOns/webdrivers/webdriverwindows/gradle.properties
addOns/websocket/gradle.properties
addOns/zest/gradle.properties

Release the failed add-ons

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/StatisticTestDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/tests/AutomationStatisticTest.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/automation.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/tests.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/SpiderJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/tests/AutomationStatisticTestUnitTest.java

Automation: Support site specific statistics

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/spiderAjax.gradle.kts
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderTarget.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJob.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJobDialog.java

Depends on #3280 - will rebase once thats been merged.

Ajax Spider: Automation authentication support

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/javahelp/org/zaproxy/zap/extension/fuzz/resources/help/contents/dialogue.html

- dialogue.html > Added new content.
Following https://groups.google.com/g/zaproxy-users/c/y9tNvx_Efig

improve: fuzz: Fuzz dialog options tab help

---

addOns/domxss/CHANGELOG.md
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java

- Added functionality for example alert handling in order to assist in documentation efforts.
- CHANGELOG.md > Added note.

feat: domxss: Example alert functionality

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/CacheableScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleFilePassiveScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleSimplePassiveScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/InPageBannerInfoLeakScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsFunctionScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsoScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/PermissionsPolicyScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SiteIsolationScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScanRule.java

In follow-up to: https://github.com/zaproxy/zaproxy/pull/6598

chore: pscanrulesAlpha: remove use of setParent

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/BigRedirectsScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ContentSecurityPolicyMissingScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/DirectoryBrowsingScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/HashDisclosureScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/HeartBleedScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/InsecureFormLoadScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/InsecureFormPostScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/LinkTargetScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ModernAppDetectionScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/PiiScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/RetrievedFromCacheScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ServerHeaderInfoLeakScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ServletParameterPollutionScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/StrictTransportSecurityScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledCharsetScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledCookieScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledHTMLAttributesScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledJavascriptEventScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/UserControlledOpenRedirectScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/XBackendServerInformationLeakScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/XChromeLoggerDataInfoLeakScanRule.java

In follow-up to: https://github.com/zaproxy/zaproxy/pull/6598

chore: pscanrulesBeta: remove use of setParent

---

README.md

Signed-off-by: psiinon@gmail.com

Add code quality badges

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AddOnJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/AddOnJob.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-addons.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/addOns-max.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/addOns-min.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/AddOnJobUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml

Automation: Disabled addOns job updateAddOns option

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportData.java

reports: remove usage of BouncyCastle

---

addOns/addOns.gradle.kts

Add tasks to copy and deploy the mandatory add-ons for easier set up of
zaproxy project.
Related to zaproxy/zaproxy#6916.

Add tasks to copy/deploy the mandatory add-ons

---

addOns/addOns.gradle.kts

Use the property to set if the JaCoCo report should be generated.

Address build deprecation

---

addOns/callhome/CHANGELOG.md
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/InvalidServiceUrlException.java
addOns/callhome/src/main/javahelp/org/zaproxy/addon/callhome/resources/help/contents/callhome.html
addOns/quickstart/CHANGELOG.md
addOns/quickstart/quickstart.gradle.kts
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java

Fixes https://github.com/zaproxy/zaproxy/issues/6016

Callhome: support the News service

---

addOns/callhome/CHANGELOG.md
addOns/callhome/callhome.gradle.kts
addOns/callhome/gradle.properties
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java

I'll submit the same changes to core next...

Callhome: Fix webswing and kali detection

---

addOns/callhome/CHANGELOG.md
addOns/callhome/gradle.properties
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java

Call home: 2nd kali fix :/

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScanRule.java
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
addOns/pscanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SubResourceIntegrityAttributeScanRuleUnitTest.java

pscanrulesAlpha: calculate integrity hash in SRI scan rule

---

addOns/evalvillain/CHANGELOG.md
addOns/evalvillain/src/main/javahelp/org/zaproxy/addon/evalvillain/resources/help/contents/evalvillain.html

Eval Villain: added blog link to help

---

addOns/network/CHANGELOG.md
addOns/network/src/main/javahelp/help/contents/api.html
addOns/network/src/main/javahelp/help/contents/cmdline.html
addOns/network/src/main/javahelp/help/contents/options/options.html
addOns/network/src/main/javahelp/help/contents/options/servercertificates.html

Add notes in the help indicating in which versions are the features
available.
Restructure the changelog for clarity.

network: mention feature availability in the help

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/XxeScanRule.java
addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastParam.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastOptionsPanelTab.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/callback/CallbackService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/ui/GeneralOastOptionsPanelTab.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/ui/OastOptionsPanel.java
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/options.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/index.xml
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/map.jhm
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/toc.xml
addOns/oast/src/main/resources/org/zaproxy/addon/oast/resources/Messages.properties

Add-on specific changes are in their CHANGELOG.

Update XxeScanRule to use OAST payloads

---

addOns/webdrivers/webdriverlinux/CHANGELOG.md
addOns/webdrivers/webdriverlinux/src/main/javahelp/org/zaproxy/zap/extension/webdriverlinux/resources/help/contents/webdriverlinux.html
addOns/webdrivers/webdrivermacos/CHANGELOG.md
addOns/webdrivers/webdrivermacos/src/main/javahelp/org/zaproxy/zap/extension/webdrivermacos/resources/help/contents/webdrivermacos.html
addOns/webdrivers/webdrivers.gradle.kts
addOns/webdrivers/webdriverwindows/CHANGELOG.md
addOns/webdrivers/webdriverwindows/src/main/javahelp/org/zaproxy/zap/extension/webdriverwindows/resources/help/contents/webdriverwindows.html

- CHANGELOGs > Add change note.
- Help files > Updated bundled version.
- build file > Update used version.
Fixes zaproxy/zaproxy#6978

chore: webdrivers (all): Chromedriver update

---

addOns/network/network.gradle.kts
addOns/openapi/openapi.gradle.kts
addOns/reports/reports.gradle.kts
addOns/soap/soap.gradle.kts

chore: Upgrade Log4j to 2.16.0

---

addOns/callhome/CHANGELOG.md
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java

Callhome: upload telemetry stats on destroy

---

addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshEvent.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshPoller.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java
addOns/oast/src/main/resources/org/zaproxy/addon/oast/resources/Messages.properties

oast: improve logging for Interactsh

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java

OAST Interactsh: ServerUrl change in Options deregisters old ServerUrl and registers new ServerUrl

oast: Interactsh Bugfix: ServerUrl change in Options

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java

Fixed Interactsh multi threading issue during register and deregister
Fixes zaproxy/zaproxy#6997.

oast: Fixes zaproxy/zaproxy#6997 Interactsh: multi threading issue

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastServer.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java

oast: Set HttpSender's Initiator to OAST_INITIATOR

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java
addOns/callhome/CHANGELOG.md
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java

Automation: Added support for generating stats

---

addOns/callhome/CHANGELOG.md
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java
addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/AbstractFuzzer.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/ExtensionFuzz.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/HttpFuzzer.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/impl/FuzzerDialog.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/generator/ProcessedPayloadGenerator.java

Fuzzer: Add stats

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/ResourceIdentificationUtils.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/ResourceIdentificationUtilsUnitTest.java

commonlib: add standard resource identification methods

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/DataGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/generators/PathGeneratorUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/OpenApi_defn_examples.yaml

openapi: Use parameter example from schema as well

---

README.md

fixes zaproxy/zaproxy-website#646

Link to the website for dev docs

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AuthenticationData.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/ContextWrapper.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/JobUtils.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/authentication.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/environment.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/env.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/AuthenticationDataUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/ContextWrapperUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-config.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml

Will implement some integration tests as well...

Automation: Form and JSON-based authentication support

---

addOns/automation/CHANGELOG.md
addOns/automation/automation.gradle.kts
addOns/automation/gradle.properties

Automation: Promote to beta and release

---

addOns/callhome/CHANGELOG.md
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java

CallHome: Fix bugs in telemetry last call

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/ChannelAttributes.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/BaseServer.java
addOns/network/src/main/java/org/zaproxy/addon/network/server/Server.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/BaseServerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/server/ServerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/testutils/TestClient.java
addOns/network/src/test/java/org/zaproxy/addon/network/testutils/TextTestClient.java

Add server which provides the basic functionality.

network: add base server

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/ChannelAttributes.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/TlsUtils.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsConfig.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/TlsUtilsUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsConfigUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/testutils/TextTestClient.java

Add a handler to upgrade a SSL/TLS connection.

network: add handler for SSL/TLS upgrade

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/ConnectRequestHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/ConnectRequestHandlerUnitTest.java

Handle CONNECT requests to possibly use SSL/TLS protocol.

network: add handler for CONNECT requests

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/ChannelAttributes.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpClientCodec.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/PassthroughHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/PassthroughHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/testutils/TextTestClient.java

Handle CONNECT requests to possibly passthrough the data received/sent.

network: add handler to passthrough connections

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/LegacySocketAdapter.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/LegacySocketAdapterUnitTest.java

Add handler that exposes a `Socket` for a given `Channel`, to provide
compatibility with core listeners.

network: add socket adapter

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/BaseServer.java
addOns/network/src/main/java/org/zaproxy/addon/network/server/Server.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/BaseServerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/server/ServerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/testutils/TestClient.java

Allow implementations to properly release their resources.
Change flaky test to be more robust when verifying the outcomes.

network: change Server to be Closeable

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/DefaultHttpMessageHandlerContext.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/MainServerHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/ConnectReceivedHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/DefaultHttpMessageHandlerContextUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/MainServerHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/ConnectReceivedHandlerUnitTest.java

Notify the handlers and process the messages accordingly.
Add server handler for CONNECT requests.
Add default implementation of the context handler.

network: add main server handler

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/DefaultServerConfig.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/HttpServer.java
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/HttpServerUnitTest.java

Allow other add-ons to create/get a HTTP server.

network: provide servers to other add-ons

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpSenderHandler.java
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpSenderHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/testutils/TestSslCertificateService.java

Add handler that sends the request received and sets the response
received or an error if not successful.

network: add HTTP sender handler

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/MainProxyHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/MainProxyHandlerUnitTest.java

Allow other add-ons to create/get a HTTP proxy.

network: provide proxies to other add-ons

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJob.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJobUnitTest.java
addOns/soap/CHANGELOG.md
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/automation/SoapJob.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/automation/SoapJobUnitTest.java

OpenAPI + SOAP: Fix bad "Unrecognised parameter"

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AuthenticationData.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationEnvironment.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/ContextWrapper.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/SessionManagementData.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/JobUtils.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/authentication.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/environment.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/env.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/AuthenticationDataUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/ContextWrapperUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-config.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml

Some of the script handling is really difficult to implement unit tests for.
But I will be adding integration tests for it...

Automation: Support script based auth

---

addOns/ascanrulesBeta/src/main/zapHomeFiles/json/hidden_files.json

- Update/correct attribution on the .svn/wc.db and vim_settings.xml entries.
No changelog or unittest tweaks necessary, irrelevant to end users.

chore: ascanrulesBeta: HFF data file correct attribution

---

addOns/network/CHANGELOG.md

network: update changelog

---

addOns/reports/src/main/zapHomeFiles/reports/traditional-json-plus/report.json
addOns/reports/src/main/zapHomeFiles/reports/traditional-json-plus/template.yaml

Similarly with the _HTML report with requests and responses_ template, this adds a JSON report template that includes requests and responses.

reports: added JSON report template that includes requests and responses

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/PassthroughHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/PassthroughHandlerUnitTest.java

Change the passthrough handler to write the response instead of letting
later handlers do that, they might be executed in a different thread
leading to unexpected pipeline state.

network: let passthrough write the response

---

addOns/reports/CHANGELOG.md

I was going to add sections for the requests and responses, but if you have sections then you must select at least one, so they arent so suitable for 'sub-sections' like the requests and responses.
Bit of a trivial PR but its also testing my PC setup :D

Reports: Add changelog for json-plus

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CommandInjectionScanRule.java
addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties

ascanrules: Added more contextual Other Info to command OS injection rule

---

addOns/network/src/main/java/org/zaproxy/addon/network/LocalServersOptions.java
addOns/network/src/main/java/org/zaproxy/addon/network/LocalServersOptionsPanel.java
addOns/network/src/main/java/org/zaproxy/addon/network/NetworkApi.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/LocalServerConfig.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/AddLocalServerDialog.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/AddressValidator.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/LocalServerPropertiesDialogue.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/LocalServerPropertiesPanel.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/LocalServersTableModel.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/LocalServersTablePanel.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/MainProxyPanel.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/ModifyLocalServerDialog.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/SecurityProtocolsPanel.java
addOns/network/src/main/javahelp/help/contents/options/localservers.html
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties
addOns/network/src/test/java/org/zaproxy/addon/network/LocalServersOptionsUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/NetworkApiUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/LocalServerConfigUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/ui/LocalServersTableModelUnitTest.java

Allow to manage the main proxy and additional servers/proxies.

network: manage local servers/proxies

---

addOns/network/src/main/java/org/zaproxy/addon/network/LocalServersOptions.java
addOns/network/src/test/java/org/zaproxy/addon/network/LocalServersOptionsUnitTest.java

Migrate the main and additional proxies.

network: migrate core options

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java

These will be included in the telemetry.
The changes look more complicated than they are - I've just wrapped a load of code in a try catch block and then called Stats.incCounter... ;)

Reports: added report generation stats

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/AliasChecker.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/LocalServerConfig.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/AliasApiRewriteHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/ZapApiHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/LocalServerConfigUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/AliasApiRewriteHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/ZapApiHandlerUnitTest.java

Add handlers to server API requests, rewrite them if alias.

network: add ZAP API related handlers

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportHelper.java
addOns/reports/src/main/zapHomeFiles/reports/risk-confidence-html/report.html

Added helper methods to work around a ThymeLeaf bug ;)
Fixes https://github.com/zaproxy/zaproxy/issues/7026

Reports: Fix risk report with Java 17

---

addOns/coreLang/CHANGELOG.md

Update with latest files from core.

coreLang: update language pack

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java

oast: Check if ZAP hasView before updating Oast Tab

---

addOns/exim/CHANGELOG.md
addOns/exim/exim.gradle.kts

Updated build file and changelog.

chore: exim: Promote to Beta

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/AntiClickjackingScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ViewstateScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/AntiClickjackingScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ViewStateScanRuleUnitTest.java

Pscanrules - set alertrefs

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/SessionManagementData.java
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/test/java/org/zaproxy/addon/automation/ContextWrapperUnitTest.java

This should fix an issue exposed by the integration tests.

Automation: Fix session mgmt script issue

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/automation/ScriptJob.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/automation/ScriptJobParameters.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/automation/actions/AddScriptAction.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/automation/actions/RemoveScriptAction.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/automation/actions/ScriptAction.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/automation/ui/ScriptJobDialog.java
addOns/scripts/src/main/javahelp/org/zaproxy/zap/extension/scripts/resources/help/contents/automation.html
addOns/scripts/src/main/resources/org/zaproxy/zap/extension/scripts/resources/Messages.properties
addOns/scripts/src/main/resources/org/zaproxy/zap/extension/scripts/resources/script-max.yaml
addOns/scripts/src/main/resources/org/zaproxy/zap/extension/scripts/resources/script-min.yaml
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/automation/ScriptJobUnitTest.java

Scripts: Support auto add/remove script actions

---

addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/http/ComparableResponse.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/http/ComparableResponseUnitTest.java
addOns/commonlib/src/test/resources/org/zaproxy/addon/commonlib/http/medium.html
addOns/commonlib/src/test/resources/org/zaproxy/addon/commonlib/http/petstore.json

Splitting from https://github.com/zaproxy/zap-extensions/pull/2149/ so that it can be used earlier and elsewhere.

commonlib: Comparable response

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/NewPlanDialog.java
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/exim/CHANGELOG.md
addOns/exim/exim.gradle.kts
addOns/exim/src/main/java/org/zaproxy/addon/exim/automation/ExtensionEximAutomation.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/automation/ImportJob.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/automation/ImportJobDialog.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/log/LogsImporter.java
addOns/exim/src/main/javahelp/help/contents/automation.html
addOns/exim/src/main/javahelp/help/contents/exim.html
addOns/exim/src/main/javahelp/help/index.xml
addOns/exim/src/main/javahelp/help/map.jhm
addOns/exim/src/main/javahelp/help/toc.xml
addOns/exim/src/main/resources/import-max.yaml
addOns/exim/src/main/resources/import-min.yaml
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/Messages.properties
addOns/exim/src/test/java/org/zaproxy/addon/exim/automation/ImportJobUnitTest.java

Added the Automation Framework support for Import Job as per https://github.com/zaproxy/zaproxy/issues/7078
I couldn't test it from cmd, but I have tested the GUI part.
Please let me know if I can improve something.
Fixes zaproxy/zaproxy#7078

exim: Add Automation Framework support

---

addOns/replacer/CHANGELOG.md
addOns/replacer/replacer.gradle.kts

- Updated build file and changelog.

chore: replacer: Promote to Release

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ExternalRedirectScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/ExternalRedirectScanRuleUnitTest.java

Ascanrules: external redirect dots deny listed

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties

As per https://groups.google.com/g/zaproxy-users/c/jWlXNdm8EA0/m/i5p9S1GIAwAJ

Automation: Fix Scan Headers label

---

addOns/network/CHANGELOG.md
addOns/network/network.gradle.kts
addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts
addOns/reports/CHANGELOG.md
addOns/reports/reports.gradle.kts
addOns/soap/CHANGELOG.md
addOns/soap/soap.gradle.kts

Added maintenance note to changelogs where applicable, updated build files.

chore: Upgrade Log4j to 2.17.2

---

addOns/network/CHANGELOG.md

Removed un-necessary entry.
Sorry I bungled this the first time around.

chore: Fix 3668 Network changelog mistake

---

addOns/retest/CHANGELOG.md
addOns/retest/src/main/java/org/zaproxy/addon/retest/EditAlertPanel.java
addOns/retest/src/main/java/org/zaproxy/addon/retest/PlanTableModel.java
addOns/retest/src/main/resources/org/zaproxy/addon/retest/resources/Messages.properties

feat: retest: Scan Rule ID table values no longer displayed with commas

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/Spring4ShellScanRule.java
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/Spring4ShellScanRuleUnitTest.java

AscanrulesAlpha: Spring4Shell rule

---

addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/Spring4ShellScanRule.java

Ooops, meant to include this last time...

Spring4Shell example alert

---

addOns/ascanrulesAlpha/CHANGELOG.md

Mention the SSTI scan rules added.

ascanrulesAlpha: update changelog

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AddTestDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/UrlPresenceTestDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/tests/UrlPresenceTest.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/tests.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/tests/UrlPresenceTestUnitTest.java

Related to zaproxy/zaproxy#6461

automation: Add URL presence test

---

addOns/fuzzdb/CHANGELOG.md
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/discovery/predictable-filepaths/filename-dirname-bruteforce/raft-large-directories-lowercase.txt
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/discovery/predictable-filepaths/filename-dirname-bruteforce/raft-large-directories.txt
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/discovery/predictable-filepaths/filename-dirname-bruteforce/raft-large-extensions-lowercase.txt
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/discovery/predictable-filepaths/filename-dirname-bruteforce/raft-large-extensions.txt
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/discovery/predictable-filepaths/filename-dirname-bruteforce/raft-large-files-lowercase.txt
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/discovery/predictable-filepaths/filename-dirname-bruteforce/raft-large-files.txt
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/discovery/predictable-filepaths/filename-dirname-bruteforce/raft-medium-directories-lowercase.txt
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/discovery/predictable-filepaths/filename-dirname-bruteforce/raft-medium-directories.txt
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/discovery/predictable-filepaths/filename-dirname-bruteforce/raft-medium-files-lowercase.txt
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/discovery/predictable-filepaths/filename-dirname-bruteforce/raft-medium-files.txt
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/discovery/predictable-filepaths/filename-dirname-bruteforce/raft-small-directories-lowercase.txt
addOns/fuzzdb/src/main/zapHomeFiles/fuzzers/fuzzdb/discovery/predictable-filepaths/filename-dirname-bruteforce/raft-small-directories.txt

Updating the raft lists as updates have been made by the SecLists project in the last few years

fuzzdb: Updating the raft lists

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java

This is required for the core change to introduce passive scan threading.
I tried to make the minimum changes needed, but I was wondering if the code could be more efficient?
Eg do we need to keep checking after a match has been found?

Wappalyzer: Change code to be thread safe

---

addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/ExtensionHttpFuzzer.java

Corrected i18n message call

---

.github/workflows/create_webdriver_update.yml

Introduced in zaproxy/zap-extensions#3742

fix: Mistake in webdrivers workflow

---

.github/workflows/create_webdriver_update.yml

fix: Second mistake in webdrivers workflow

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java

Request the shutdown when not able to start the main proxy when running
with newer ZAP version, rather than shutdown manually and throw an
error.
Related to zaproxy/zaproxy#7261.

network: request shutdown on startup errors

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechTableModel.java

Wappalyzer - threading fix

---

.github/workflows/create_webdriver_update.yml

Related to:
- https://github.com/zaproxy/zap-extensions/pull/3768
- https://github.com/mozilla/geckodriver/issues/2009

chore: Don't do gecko updates on schedule

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/JsFunctionScanRule.java

PscanrulesAlpha - JS Function threading fix

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/zapHomeFiles/json/hidden_files.json

I compared the current hidden_files.json with the current snallygaster repo and found some checks still missing in the json. This PR adds the missing ones.

ascanrulesBeta: Check more hidden files

---

addOns/packpentester/CHANGELOG.md
addOns/packpentester/packpentester.gradle.kts

Pentester Pack: Corrected fuzz add-on name

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java

Add endpoint missed previously.

network: add missing core connection endpoint

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/services/services.html

- Add note to CHANGELOG.
- Update help adding default services details.

chore: OAST: Help document default services

---

addOns/network/src/main/javahelp/help/contents/api.html

Mention the API endpoints related to local servers/proxies.

network: add API endpoints to help

---

addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/UsernameEnumerationScanRule.java

- Remove redundant comments.
- Make the logging constant final.
- Remove redundant return in init method.
- Combine conditionals in one block.
- Avoid unnecessary toString'ing in logging.
- Reduce amount of logging (changed a bunch of warns to debug).
- Leverage RandomStringUtils built-in methods instead of declaring a full alphabet locally.
- Use isEmpty vs size 0 checks.
- Remove unnecessary use of boolean literals.
- CHANGELOG already has a maintenance note.
In preparation for: zaproxy/zaproxy#7116

chore: ascanrulesBeta: UserNameEnumeration SAST (SonarLint) Fixes

---

addOns/network/src/main/java/org/zaproxy/addon/network/ClientCertificatesOptions.java
addOns/network/src/main/java/org/zaproxy/addon/network/ClientCertificatesOptionsPanel.java
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/NetworkApi.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/Pkcs11Driver.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/Pkcs11Drivers.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/AddPkcs11DriverDialog.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/CertificateDialog.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/CertificatesTableModel.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/ConsumerDocumentListener.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/DriversComboBoxModel.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/KeyStoresTableModel.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/ModifyPkcs11DriverDialog.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/Pkcs11DriverTableModel.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/Pkcs11DriverTablePanel.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/Pkcs11DriversDialog.java
addOns/network/src/main/javahelp/help/contents/api.html
addOns/network/src/main/javahelp/help/contents/options/clientcertificates.html
addOns/network/src/main/javahelp/help/contents/options/options.html
addOns/network/src/main/javahelp/help/map.jhm
addOns/network/src/main/javahelp/help/toc.xml
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties
addOns/network/src/main/zapHomeFiles/pkcs11-drivers.xml
addOns/network/src/test/java/org/zaproxy/addon/network/ClientCertificatesOptionsUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/NetworkApiUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/Pkcs11DriverUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/Pkcs11DriversUnitTest.java
testutils/src/main/java/org/zaproxy/zap/testutils/TestUtils.java

Manage the client certificates, when the core ones are deprecated.
Related to zaproxy/zaproxy#7304.

network: manage client certificates

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/CloudMetadataScanRule.java
addOns/ascanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/CloudMetadataScanRuleUnitTest.java

- CHANGELOG.md > Updated change note.
- CloudMetadataScanRule.java > Updated to also attempt Alibaba payloads.
- CloudMetadataScanRuleUnitTest.java > Updated to assert the new behavior.
- ascanbeta.html > Updated help entry.

feat: ascanrulesBeta: Leverage alibaba.zaproxy.org

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/httputils/HtmlContext.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/httputils/HtmlContextAnalyser.java
addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/httputils/HtmlContextAnalyserUnitTest.java
addOns/ascanrules/src/test/resources/org/zaproxy/zap/extension/ascanrules/crosssitescriptingscanrule/AttributeName.html
addOns/ascanrules/src/test/resources/org/zaproxy/zap/extension/ascanrules/crosssitescriptingscanrule/TagName.html

Related to zaproxy/zaproxy#7157

ascanrules: address XSS false negatives

---

addOns/retire/CHANGELOG.md
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
addOns/retire/src/main/resources/org/zaproxy/addon/retire/resources/Messages.properties

In follow-up to: https://github.com/zaproxy/zap-extensions/pull/3829#discussion_r890292038

retire: Tweak naming

---

addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/CloudMetadataScanRule.java

Change `CloudMetadataScanRule` to not send the message with Host
override with older `HttpSender` implementation classes if the newer
implementation is available in the classpath, to reduce usage of
implementation details in newer versions.

ascanrulesBeta: rely on newer HttpSender

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/UserAgentScanRule.java

- CHANGELOG > Add, added note.
- UserAgentScanRule > Added new UA constants with comments.

ascanrulesBeta: Add newer UA strings to UA fuzz scan rule

---

addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartPanel.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ManualRequestEditorPanel.java
addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ConsolePanel.java
addOns/todo/src/main/java/org/zaproxy/zap/extension/todo/TodoList.java

Do not implement the `Tab` interface, it's not in effective use.
Update changelog where needed.

Remove Tab interface usage

---

addOns/spider/CHANGELOG.md
addOns/spider/spider.gradle.kts

Updated changelog and build file.
As discussed via email.

spider: Promote to Release status

---

addOns/sse/CHANGELOG.md
addOns/sse/src/main/java/org/zaproxy/zap/extension/sse/db/TableEventStream.java

sse: increase URL column size

---

addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderHtmlParser.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderHtmlParserUnitTest.java
addOns/spider/src/test/resources/org/zaproxy/addon/spider/parser/html/ImgElementsSpiderHtmlParser.html
addOns/spider/src/test/resources/org/zaproxy/addon/spider/parser/html/TableElementsSpiderHtmlParser.html
addOns/spider/src/test/resources/org/zaproxy/addon/spider/parser/html/VideoElementsSpiderHtmlParser.html

spider: Migrate core PR functionality

---

addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/CookieGuesser.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ExtensionParamMiner.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/GuesserProgressListener.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/GuesserScan.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/HeaderGuesser.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamGuessResult.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamGuesser.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamGuesserScanController.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamMinerConfig.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamMinerOptions.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/UrlGuesser.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/gui/ParamMinerDialog.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/gui/ParamMinerPanel.java
addOns/paramminer/src/main/resources/org/zaproxy/addon/paramminer/resources/Messages.properties

Related to zaproxy/zaproxy#7140

paramminer: Add ParamGuesser, GuesserScan and ParamGuesserScanController

---

addOns/exim/CHANGELOG.md
addOns/exim/src/main/java/org/zaproxy/addon/exim/PopupMenuCopyUrls.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/PopupMenuExportContextUrls.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/PopupMenuExportMessages.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/PopupMenuExportSelectedUrls.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/PopupMenuExportUrls.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/PopupMenuSaveRawMessage.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/PopupMenuSaveXmlMessage.java

In follow-up to https://github.com/zaproxy/zap-extensions/pull/3784#issuecomment-1132682921

exim: Add stats for migrated core components

---

addOns/callhome/CHANGELOG.md
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java

callhome: Don't notify HTTP sender listeners

---

addOns/paramminer/paramminer.gradle.kts
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/CookieGuesser.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/GuesserScan.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamGuesser.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamMinerConfig.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamReasons.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/UrlBruteForce.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/UrlGuesser.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/UrlUtils.java
addOns/paramminer/src/test/java/org/zaproxy/addon/paramminer/UrlUtilsUnitTest.java

Related to: zaproxy/zaproxy#7140

paramminer: Add comparison methods for Url parameter guess

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportApi.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/ReportApiUnitTest.java

Reports: API fixes

---

addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamGuessResult.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamReasons.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/UrlBruteForce.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/UrlGuesser.java

paramminer: bug squashing

---

addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Add tests to verify that the chunked response is properly handled.
Related to zaproxy/zaproxy#4630.

network: test chunked response

---

addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/GuesserScan.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/OutputModel.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamGuessResult.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamGuessResultEvent.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamMinerResultEventListener.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/UrlBruteForce.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/UrlGuesser.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/gui/ParamMinerPanel.java
addOns/paramminer/src/main/resources/org/zaproxy/addon/paramminer/resources/Messages.properties

Related to zaproxy/zaproxy#7140

paramminer: Add notification, output panel update and url parser changes

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/ForbiddenBypassScanRule.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/ForbiddenBypassScanRuleUnitTest.java

Signed-off-by: hahwul <hahwul@gmail.com>
Hi, team 👋🏼
I think it would be good to add `%09` (tab) in 403 bypass, so I send PR. Please review it 🙏🏼
* https://github.com/PortSwigger/403-bypasser/blob/main/query%20payloads.txt
* https://github.com/channyein1337/403-bypass/blob/main/403-bypass.py#L28
* https://www.hahwul.com/2021/10/08/bypass-403/#common-patterns

ascanrulesAlpha: Add payload for Forbidden Bypass scan rule (Tab)

---

addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/CookieGuesser.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/GuesserScan.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/HeaderGuesser.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamGuessResult.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamGuesser.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamMinerConfig.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamReasons.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/UrlBruteForce.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/UrlGuesser.java
addOns/paramminer/src/test/java/org/zaproxy/addon/paramminer/UrlGuesserUnitTest.java
addOns/paramminer/src/test/resources/org/zaproxy/addon/paramminer/AttributeName.html
addOns/paramminer/src/test/resources/org/zaproxy/addon/paramminer/AttributeValue.html
addOns/paramminer/src/test/resources/org/zaproxy/addon/paramminer/ReflectionInBody.html
addOns/paramminer/src/test/resources/org/zaproxy/addon/paramminer/ReflectionInTag.html
addOns/paramminer/src/test/resources/wordlists/UrlGuesserTestList.txt

Related to zaproxy/zaproxy#7140

paramminer: Add units tests for URL guesser

---

addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/BrowserHook.java
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java

Selenium:  Added option to register java selenium 'scripts'

---

addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionSQLiteScanRuleUnitTest.java

Allow a few more messages at INSANE Strength to failures similar to
https://github.com/zaproxy/zap-extensions/runs/7840172682?check_suite_focus=true

ascanrulesBeta: Make SqlInjectionSQLiteScanRuleUnitTest more forgiving

---

addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderHtmlParser.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderHtmlParserUnitTest.java
addOns/spider/src/test/resources/org/zaproxy/addon/spider/parser/html/ImportElementsSpiderHtmlParser.html
addOns/spider/src/test/resources/org/zaproxy/addon/spider/parser/html/MetaElementsSpiderHtmlParser.html
addOns/spider/src/test/resources/org/zaproxy/addon/spider/parser/html/StringSpiderHtmlParser.html

Migrate the changes from https://github.com/zaproxy/zaproxy/pull/7356 `+174/-4`

spider: Duplicate core changes

---

addOns/spider/spider.gradle.kts
addOns/spider/src/main/resources/org/zaproxy/addon/spider/Messages.properties

spider: Tweak add-on description

---

addOns/paramminer/CHANGELOG.md
addOns/paramminer/paramminer.gradle.kts
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ExtensionParamMiner.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamGuessResult.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/gui/ParamMinerDialog.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/gui/ParamMinerPanel.java
addOns/paramminer/src/main/javahelp/org/zaproxy/addon/paramminer/resources/help/contents/about.html
addOns/paramminer/src/main/javahelp/org/zaproxy/addon/paramminer/resources/help/contents/dialog.html
addOns/paramminer/src/main/javahelp/org/zaproxy/addon/paramminer/resources/help/contents/paramdigger.html
addOns/paramminer/src/main/javahelp/org/zaproxy/addon/paramminer/resources/help/contents/tab.html
addOns/paramminer/src/main/javahelp/org/zaproxy/addon/paramminer/resources/help/helpset.hs
addOns/paramminer/src/main/javahelp/org/zaproxy/addon/paramminer/resources/help/index.xml
addOns/paramminer/src/main/javahelp/org/zaproxy/addon/paramminer/resources/help/map.jhm
addOns/paramminer/src/main/javahelp/org/zaproxy/addon/paramminer/resources/help/toc.xml
addOns/paramminer/src/main/resources/org/zaproxy/addon/paramminer/resources/Messages.properties

Related to zaproxy/zaproxy#7140 and fixes zaproxy/zaproxy#7427

paramdigger: Add naming changes to GUI and helpdocs

---

addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ExtensionParamDigger.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/GuesserScan.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/OutputModel.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamDiggerAPI.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamDiggerConfig.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamDiggerOptions.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamDiggerResultEventListener.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamGuesser.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/ParamGuesserScanController.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/UrlBruteForce.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/UrlGuesser.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/UrlUtils.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/gui/ParamDiggerDialog.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/gui/ParamDiggerHistoryTableModel.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/gui/ParamDiggerPanel.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/gui/ParamDiggerResultsTable.java
addOns/paramminer/src/main/java/org/zaproxy/addon/paramminer/gui/PopupMenuParamDigger.java
addOns/paramminer/src/test/java/org/zaproxy/addon/paramminer/UrlGuesserUnitTest.java

related to zaproxy/zaproxy#7140

paramdigger: Add refactorings for ParamDigger

---

addOns/paramdigger/paramdigger.gradle.kts

related to zaproxy/zaproxy#7140

paramdigger: Add help docs URL in manifest

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/scripts/ExtensionOastScripts.java
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/oast.html
addOns/oast/src/main/zapHomeFiles/scripts/templates/extender/OAST Request Handler.js

Also allow unregistering OAST request handlers.

oast: Use Extender type for Script Template

---

addOns/spider/src/main/java/org/zaproxy/addon/spider/ExtensionSpider2.java

Remove the dependency on the core spider, it might not be available.

spider: no longer depend on core spider

---

addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureGitScanRule.java

Remove commented code using deprecated core class.

ascanrulesBeta: remove commented code

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/JobUtils.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PassiveScanConfigJob.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-pscanconf.html
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/PassiveScanConfigJobUnitTest.java

Not sure if all jobs should do this, but I think this is the most important one to support this - quite a few people have been confused by this problem, including me 😛 

Auto: reset passive scan configs

---

addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderHtmlFormParserUnitTest.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderHtmlParserUnitTest.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderHttpHeaderParserUnitTest.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderParserTestUtils.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderParserUnitTest.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderRedirectParserUnitTest.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderRobotstxtParserUnitTest.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderSitemapXmlParserUnitTest.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderTextParserUnitTest.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SvgHrefParserUnitTest.java

Move the creation and the parser to the base class and add a listener.
Move also other common properties (e.g. options, message).
Move `Source` creation, using the moved message.
Update specific test classes accordingly.

spider: reduce code duplication in tests

---

addOns/spider/src/main/java/org/zaproxy/addon/spider/ExtensionSpider2.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderHtmlParser.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderHtmlParserUnitTest.java

Fix bug introduced in previous refactor, use of incorrect source and
incorrect test setup.
Remove variables no longer used.

spider: fix refactor bug and do clean up

---

addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationParam.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AutomationPanel.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/OptionsPanel.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/automation.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/options.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/index.xml
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/map.jhm
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/toc.xml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties

Automation: add open on start option

---

addOns/paramdigger/src/main/java/org/zaproxy/addon/paramdigger/Cache.java
addOns/paramdigger/src/main/java/org/zaproxy/addon/paramdigger/CacheController.java
addOns/paramdigger/src/main/java/org/zaproxy/addon/paramdigger/ParamDiggerConfig.java
addOns/paramdigger/src/main/resources/org/zaproxy/addon/paramdigger/resources/Messages.properties
addOns/paramdigger/src/test/java/org/zaproxy/addon/paramdigger/CacheControllerUnitTest.java

Related to zaproxy/zaproxy#7140
Signed-off-by: ArkaprabhaChakraborty [chakrabortyarkaprabha998@gmail.com](mailto:chakrabortyarkaprabha998@gmail.com)

paramdigger: add cache controller

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AddTestDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/MonitorTestDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/SpiderJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/tests/AutomationMonitorTest.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-ascan.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-spider.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/test-alert.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/test-monitor.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/test-stats.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/test-url.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/tests.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/index.xml
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/map.jhm
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/toc.xml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/tests/AutomationMonitorTestUnitTest.java
addOns/spider/CHANGELOG.md
addOns/spider/src/main/java/org/zaproxy/addon/spider/automation/SpiderJob.java
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/contents/automation.html
addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/spiderAjax.gradle.kts
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderTarget.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJob.java
addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/contents/automation.html

Automation: Monitor tests

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/SpiderJob.java
addOns/spider/CHANGELOG.md
addOns/spider/src/main/java/org/zaproxy/addon/spider/automation/SpiderJob.java

Automation: Dont switch tabs

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRuleUnitTest.java

* limit scope to ten digit numbers between 1 billion and Y2038 epoch
* limit scope to ten years from now
Closes zaproxy/zaproxy#6741

pscanrules: Timestamp Disclosure limit scope

---

addOns/paramdigger/src/main/javahelp/org/zaproxy/addon/paramdigger/resources/help/contents/about.html
addOns/paramdigger/src/main/javahelp/org/zaproxy/addon/paramdigger/resources/help/contents/paramdigger.html

Link code and blog from main help page.

paramdigger: Update help

---

addOns/requester/CHANGELOG.md
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/HttpPanelSender.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ManualHttpRequestEditorPanel.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ManualRequestEditorPanel.java

Show the Send button in the Response tab, migration of core change
zaproxy/zaproxy#6313.

requester: add send button to response tab

---

addOns/requester/CHANGELOG.md
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ManualHttpRequestEditorPanel.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ManualRequestEditorPanel.java

Add shortcut to send buttons and add icon to menu item, migration of
core changes zaproxy/zaproxy#5614 and zaproxy/zaproxy#6452.

requester: add shortcut and icon

---

addOns/callhome/CHANGELOG.md
addOns/callhome/callhome.gradle.kts
addOns/network/CHANGELOG.md
addOns/network/network.gradle.kts
addOns/oast/CHANGELOG.md
addOns/oast/oast.gradle.kts
addOns/requester/CHANGELOG.md
addOns/requester/requester.gradle.kts
addOns/scripts/CHANGELOG.md
addOns/scripts/scripts.gradle.kts
addOns/soap/CHANGELOG.md
addOns/soap/soap.gradle.kts

- Build files and CHANGELOGs updated.
- Requester updated author in build file, the ZAP team has largely taken over authorship/maintenance.

Various Add-ons: Promotions

---

addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ui/httppanel/component/WebSocketComponent.java

Correctly handle null message in the `WebSocketComponent`.

websocket: handle no message in message component

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParam.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJob.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJobDialog.java
addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/contents/automation.html
addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/Messages.properties
addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/spiderAjax-max.yaml
addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/spiderAjax-min.yaml

Also fixed a couple of bugs...

ajaxSpider: onlyRunIfModern AF option

---

addOns/requester/src/main/java/org/zaproxy/addon/requester/internal/SendHttpMessageEditorDialog.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ExtensionRequester.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/HttpPanelSender.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ManualHttpRequestEditorPanel.java
addOns/requester/src/main/java/org/zaproxy/zap/extension/requester/ManualRequestEditorPanel.java
addOns/requester/src/main/resources/org/zaproxy/zap/extension/requester/resources/Messages.properties

Use only resource messages from the add-on.

requester: use own messages

---

addOns/requester/requester.gradle.kts

Update Crowdin configuration to match the new location of the messages files.

requester: update Crowdin path

---

addOns/requester/src/main/java/org/zaproxy/addon/requester/internal/CustomHttpPanelRequest.java
addOns/requester/src/main/java/org/zaproxy/addon/requester/internal/HttpPanelSender.java
addOns/requester/src/main/java/org/zaproxy/addon/requester/internal/ManualHttpRequestEditorPanel.java
addOns/requester/src/main/resources/org/zaproxy/addon/requester/Messages.properties

Stop relying on core to add the UI component that allows to change the HTTP method.

requester: add HTTP method change UI component

---

addOns/retire/CHANGELOG.md
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java

Retire: Fix NPE in example alert

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AddHeaderDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AddRequestDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/HeadersTableModel.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/JobUtils.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/RequestorJob.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help_sr_CS/contents/job-requestor.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/requestor-max.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/RequestorJobUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml

I have worked on requestor job and included the functionality to be able to add custom headers to the requests which fixes zaproxy/zaproxy#6917.
Signed-off-by: njmulsqb <najamulsaqib@tutamail.com>
This PR is opened because of accidental closure of #4087

automation: feature additional headers

---

addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationProgress.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationProgressUnitTest.java
addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/automation/ScriptJobOutputListener.java
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/automation/ScriptJobOutputListenerUnitTest.java

fixes zaproxy/zaproxy#7455
Signed-off-by: njmulsqb <najamulsaqib@tutamail.com>

automation: fix duplication of print statements to stdout

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/SpiderJob.java
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/SpiderJobUnitTest.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/automation/SpiderJob.java
addOns/spider/src/main/resources/org/zaproxy/addon/spider/Messages.properties
addOns/spider/src/test/java/org/zaproxy/addon/spider/automation/SpiderJobUnitTest.java

Fixes https://github.com/zaproxy/zaproxy/issues/7510

Automation: Allow spider to run if no OK response

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartPanel.java

QuickStart: Record news stats

---

addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/widgets/SiteTree.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFilter.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFilterAPI.java
addOns/allinonenotes/src/main/java/org/zaproxy/zap/extension/allinonenotes/EventConsumerImpl.java
addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java
addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRule.java
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/GitMetadata.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/RelativePathConfusionScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SessionFixationScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionMsSqlScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionPostgreScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SqlInjectionSqLiteScanRule.java
addOns/codedx/src/main/java/org/zaproxy/zap/extension/codedx/ReportLastScan.java
addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/httpfuzzer/ui/HttpFuzzResultsContentPanel.java
addOns/invoke/src/main/java/org/zaproxy/zap/extension/invoke/InvokeAppWorker.java
addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/BaseHttpSender.java
addOns/paramdigger/src/main/java/org/zaproxy/addon/paramdigger/ParamGuessResult.java
addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/ExtensionPlugNHack.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java
addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/WebSocketProxyV13.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ExtensionZest.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestTreeModel.java

Add maintenance note to CHANGELOG where one doesn't already exist.
- Reduce unnecessary arguments.
- Add missing arguments or adjust place holders.
- Remove unnecessary use of toString().
- Use format specifiers instead of concatenation.

Address logging issues

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ContextWrapper.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/ContextWrapperUnitTest.java

Replaces https://github.com/zaproxy/zap-extensions/pull/4091

Automation: Fix issue adding users to more than one context

---

.github/workflows/ci.yml
.github/workflows/create_eval_villian_update.yml
.github/workflows/create_retirejs_update.yml
.github/workflows/create_wappalyzer_update.yml
.github/workflows/release-add-on.yml
addOns/addOns.gradle.kts
addOns/browserView/browserView.gradle.kts
build.gradle.kts
buildSrc/build.gradle.kts
testutils/testutils.gradle.kts

Compile the add-ons and helper projects with Java 11.
Update Java version in workflows.
Remove unnecessary permission checks in some workflows.

Compile with Java 11

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/Text4ShellScanRule.java
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/Text4ShellScanRuleUnitTest.java
addOns/commonlib/commonlib.gradle.kts
addOns/graaljs/graaljs.gradle.kts
addOns/network/network.gradle.kts
addOns/oast/oast.gradle.kts
build.gradle.kts
testutils/testutils.gradle.kts

AscanRulesAlpha: Text4Shell rule

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java

oast: prevent error on null data

---

addOns/replacer/CHANGELOG.md
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ExtensionReplacer.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplaceRuleAddDialog.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerAPI.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerParam.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerParamRule.java
addOns/replacer/src/main/javahelp/org/zaproxy/zap/extension/replacer/resources/help/contents/replacer.html
addOns/replacer/src/main/resources/org/zaproxy/zap/extension/replacer/resources/Messages.properties
addOns/replacer/src/test/java/org/zaproxy/zap/extension/replacer/ExtensionReplacerTest.java

Allow the rules to apply to specific URLs.
Fix zaproxy/zaproxy#4793.

replacer: allow rules to apply to URLs

---

addOns/exim/src/main/java/org/zaproxy/addon/exim/ExtensionExim.java

The core check is no longer needed.

exim: remove core check

---

addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties

Update the error message to match the new panels names.

network: update error message

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ConnectionOptions.java
addOns/network/src/main/resources/org/zaproxy/addon/network/internal/client/common-user-agents.txt
addOns/network/src/test/java/org/zaproxy/addon/network/ConnectionOptionsUnitTest.java

Network: Update user agents

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/report-traditional-json-plus.html
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/report-traditional-xml-plus.html
addOns/reports/src/main/zapHomeFiles/reports/traditional-json-plus/report.json
addOns/reports/src/main/zapHomeFiles/reports/traditional-xml-plus/report.xml
addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-html-plus.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-json-plus.json
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-xml-plus.xml

Also extended the tests to check the plus reports in detail.

Report: add tags to trad plus reports

---

addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/NetworkApi.java
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/NetworkApiUnitTest.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/callback/CallbackServiceUnitTest.java

Remove core local server checks that provided compatibility with older core versions.

network: handle local servers always

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java

Remove core client checks that provided compatibility with older core versions.

network: handle client always

---

addOns/addOns.gradle.kts
build.gradle.kts
testutils/testutils.gradle.kts

Use main release which is already available.

Remove usage of ZAP snapshot

---

addOns/database/database.gradle.kts

Use the configuration file that includes only help files.

database: correct Crowdin configuration

---

addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/AES.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/ARC4.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/BBS.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/BFcipher.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/CubicResidue.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/DES.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/JavaRandom.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/JavaSecuredRandom.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/Lcg1.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/MicaliSchnorr.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/ModulusExponent.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/QuadraticResidue1.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/QuadraticResidue2.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/RC4Key.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/RSA.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/RSACrypt.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/SHA1Random.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/SkipjackRandom.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/TripleDES.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/ZAC3.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/ZAC3Random.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/ZAC5.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/Algo/ZAC5Random.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/IO/FileAlgoRandomStream.java
addOns/tokengen/src/main/java/com/fasteasytrade/JRandTest/IO/FileRandomStream.java
addOns/tokengen/src/main/java/org/zaproxy/zap/extension/tokengen/TokenAnalysisResultsTableModel.java
addOns/tokengen/src/main/java/org/zaproxy/zap/extension/tokengen/TokenGenMessagesTableModel.java
addOns/tokengen/tokengen.gradle.kts

Address remaining warnings and remove compiler flags that were suppressing them.

tokengen: address warnings

---

addOns/encoder/CHANGELOG.md
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/EncodeDecodeProcessors.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Base64Decoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Base64Encoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Base64UrlDecoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Base64UrlEncoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/FullHtmlStringEncoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/FullUrlDecoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/HashProcessor.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/HexStringDecoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/HexStringEncoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/HtmlStringDecoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/HtmlStringEncoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/IllegalUTF8With2ByteEncoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/IllegalUTF8With3ByteEncoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/IllegalUTF8With4ByteEncoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/JavaScriptStringDecoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/JavaScriptStringEncoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Md5Hasher.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Sha1Hasher.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Sha256Hasher.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/UnicodeDecoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/UnicodeEncoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/UrlDecoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/UrlEncoder.java

- HashProcessor > Added class with generic handling.
- Md5Hasher, Sha1Hasher, Sha256Hasher > Extend HashProcessor and are now singletons.
- Predefined processors > Implement singletons.
- EncodeDecodeProcessors > Updated to use the new singletons.

encoder: Simplify hash processors

---

addOns/network/src/main/java/org/zaproxy/addon/network/ConnectionOptions.java
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/LocalServersOptions.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/TlsUtils.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsConfig.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/LocalServerConfig.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/LocalServerPropertiesPanel.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/SecurityProtocolsPanel.java
addOns/network/src/test/java/org/zaproxy/addon/network/ConnectionOptionsUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/LocalServersOptionsUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/TlsUtilsUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsConfigUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/LocalServerConfigUnitTest.java

Make it clear that the protocols are for TLS.

network: rename methods and constants

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/LocalServersOptions.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/TlsUtils.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsConfig.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/HttpServer.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/LocalServerConfig.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/AlpnPanel.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/LocalServerPropertiesPanel.java
addOns/network/src/main/javahelp/help/contents/options/localservers.html
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties
addOns/network/src/test/java/org/zaproxy/addon/network/LocalServersOptionsUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/TlsUtilsUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsConfigUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/LocalServerConfigUnitTest.java

Allow to enable and configure ALPN for local servers/proxies, currently with just HTTP/1.1.

network: allow to configure ALPN for local servers

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/apache/hc/client5/http/impl/classic/ZapProtocolExec.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Correct proxy reauthentication.
Attempt authentication of TRACE requests.
Part of zaproxy/zaproxy#7566.

network: fix (re)authentication

---

addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverter.java
addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/contents/openapi.html
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApiTest.java

openapi: Include each endpoint in context

---

addOns/network/CHANGELOG.md
addOns/network/network.gradle.kts
addOns/network/src/main/java/org/apache/hc/client5/http/impl/async/CustomH2AsyncClientCreator.java
addOns/network/src/main/java/org/apache/hc/client5/http/impl/async/ZapAsyncProtocolExec.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/TlsUtils.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/CertificateEntry.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/h2/HttpBodyAsyncEntityProducer.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/h2/HttpMessageRequestProducer.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/h2/HttpMessageResponseConsumer.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/h2/SimpleAsyncEntityConsumer.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/h2/ZapClientTlsStrategy.java

Update dependency and HTTP sender.

network: update dependency and HTTP sender

---

addOns/soap/CHANGELOG.md
addOns/soap/soap.gradle.kts
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/ExtensionImportWSDL.java

soap: Remove script on uninstall

---

addOns/network/network.gradle.kts
addOns/network/src/main/java/org/zaproxy/addon/network/internal/TlsUtils.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/Http2MessageHelper.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpToHttp2ConnectionHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/InboundHttp2ToHttpAdapter.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/netty/Http2ControlFrameLimitEncoder.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/netty/Http2EmptyDataFrameConnectionDecoder.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/netty/Http2EmptyDataFrameListener.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/netty/Http2FrameListenerDecorator.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsConfig.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/HttpServer.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/MainServerHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/AlpnPanel.java
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties
addOns/network/src/test/java/org/zaproxy/addon/network/LocalServersOptionsUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/TlsUtilsUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/Http2MessageHelperUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/HttpToHttp2ConnectionHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/InboundHttp2ToHttpAdapterUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsConfigUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/HttpServerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/MainServerHandlerUnitTest.java

Allow to enable the h2 application protocol in local servers/proxies.

network: add h2 protocol in local servers

---

addOns/spider/src/main/java/org/zaproxy/addon/spider/Spider.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderController.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderTask.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderResourceFound.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/SpiderControllerUnitTest.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/SpiderTaskUnitTest.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderResourceFoundUnitTest.java

Use the HTTP version from the seeds (when available) and from the resources found while spidering.

spider: use HTTP version from seeds/resources

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/ChannelAttributes.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpToHttp2ConnectionHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/Http2PrefaceHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/PipelineConfigurator.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/HttpServer.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/ConnectRequestHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/Http2PrefaceHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/HttpServerUnitTest.java

Handle connections with prior knowledge in the local servers/proxies.

network: handle connection with prior knowledge

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/Http2UpgradeHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/HttpServer.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/MainProxyHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/Http2UpgradeHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/MainProxyHandlerUnitTest.java

network: handle h2c upgrade

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandlerUnitTest.java

Allow both types at the same time, one should not prevent the other.

network: allow cleartext and ALPN

---

addOns/ascanrules/ascanrules.gradle.kts
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/LocalServerPropertiesDialogue.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ui/LocalServerPropertiesPanel.java

Network:
- Add issue number to changelog entry.
- Expand the border in the ALPN and TLS panels.
- Add space between components in the main local server properties dialogue.
Update the minimum required version for commonlib in the ascanrules add-ons (alpha not necessary), using newer class.

Misc UI tweaks and other corrections

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AutomationPanel.java

https://groups.google.com/g/zaproxy-users/c/oDhzRHNkqiY/m/8ZttphV0CAAJ

Automation: Prevent exception if no display

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/zapHomeFiles/json/hidden_files.json

- CHANGELOG > Add note for the addition.
- hidden_files.json > Add new entry, and tiddy up some spurious tabs (where spaces should have been used or they were trailing).
Per: https://twitter.com/kingthorin_rm/status/1575489945564639233

ascanrules: HFF Add WPEngine config

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/httputils/HtmlContextAnalyser.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java
addOns/ascanrules/src/test/resources/org/zaproxy/zap/extension/ascanrules/crosssitescriptingscanrule/InputInLinkHrefTagAndFrameSrcTag.html

Fixes https://github.com/zaproxy/zaproxy/issues/6013
Signed-off-by: Karthik UJ [karthikuj2001@gmail.com](mailto:karthikuj2001@gmail.com)

ascanrules: Resolves javascript: Protocol XSS False Positive

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/SsrfScanRule.java
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/SsrfScanRuleUnitTest.java
addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastPayload.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/callback/CallbackService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshOptionsPanelTab.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/interactsh/InteractshService.java
addOns/oast/src/main/resources/org/zaproxy/addon/oast/resources/Messages.properties

ascanrulesAlpha: Add SSRF Scan Rule

---

addOns/encoder/CHANGELOG.md
addOns/encoder/encoder.gradle.kts
addOns/encoder/gradle.properties
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/EncodeDecodeProcessors.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/script/EncodeDecodeScript.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/script/EncodeDecodeScriptHelper.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/script/ScriptBasedEncodeDecodeProcessor.java
addOns/encoder/src/main/resources/org/zaproxy/addon/encoder/resources/Messages.properties
addOns/encoder/src/main/zapHomeFiles/scripts/templates/encode-decode/NewHasher.js
addOns/encoder/src/main/zapHomeFiles/scripts/templates/encode-decode/rot13.js
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/script/EncodeDecodeScriptUnitTest.java

- CHANGELOG > Add breaking change note, and templates change note.
- EncodeDecodeScriptHelper > The new utility object to be passed into scripts.
- EncodeDecodeScript > Updated to handle the new utility object.
- ScriptBasedEncodeDecodeProcessor > Updated to pass in a new utility object.
- EncodeDecodeProcessor > Added convenience method returning the predefined processors.
- Message.properties > Added supporting key/value pair.
- EncodeDecodeDefaultTemplate.js > Added new helper object and jsdoc.
- rot13.js > Added new helper object.
- NewHasher.js > A new template which illustrates how to script the internal Hasher to create other Java based hashers (sha3, etc as might become available in future JREs).
- encoder.gradle.kts > Promoted to release status.
- gradle.properties > Version …

encoder: Add helper object

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRuleUnitTest.java

Ascanrules - SQL rule should not target NoSQL Dbs

---

addOns/network/CHANGELOG.md
addOns/network/network.gradle.kts

Update Netty and HttpComponents Client to latest versions.

network: update dependencies

---

addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/AccessControlScannerThread.java
addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/ContextAccessRulesManager.java
addOns/accessControl/src/main/resources/org/zaproxy/zap/extension/accessControl/resources/reportAccessControl.js
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFilter.java
addOns/amf/src/main/java/org/zaproxy/zap/extension/amf/AbstractAMFTextView.java

Cherry picked from: https://github.com/zaproxy/zap-extensions/pull/3083 and rebased current.

Spelling Updates Batch 1

---

addOns/bugtracker/src/main/resources/org/zaproxy/zap/extension/bugtracker/resources/Messages.properties
addOns/callgraph/src/main/java/org/zaproxy/zap/extension/callgraph/CallGraphFrame.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/CookieUtilsUnitTest.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/http/HttpDateUtilsUnitTest.java
addOns/diff/CHANGELOG.md
addOns/diff/src/main/java/org/zaproxy/zap/extension/diff/diff_match_patch.java
addOns/domxss/CHANGELOG.md
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
addOns/encoder/CHANGELOG.md
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/EncodeDecodeOptions.java
addOns/formhandler/CHANGELOG.md
addOns/formhandler/src/main/resources/org/zaproxy/zap/extension/formhandler/resources/Messages.properties
addOns/frontendscanner/src/main/zapHomeFiles/frontendscanner/front-end-scanner.js

Cherry picked from: https://github.com/zaproxy/zap-extensions/pull/3083 and rebased current.

Spelling Updates Batch 2

---

addOns/plugnhack/CHANGELOG.md
addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/ExtensionPlugNHack.java
addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/MonitoredPagesManager.java
addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/OracleListener.java
addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/PlugNHackAPI.java
addOns/plugnhack/src/main/java/org/zaproxy/zap/extension/plugnhack/SessionMonitoredClientsPanel.java
addOns/plugnhack/src/main/resources/org/zaproxy/zap/extension/plugnhack/resources/pnh_probe.js
addOns/portscan/CHANGELOG.md
addOns/portscan/src/main/java/org/zaproxy/zap/extension/portscan/PortScan.java
addOns/portscan/src/main/resources/org/zaproxy/zap/extension/portscan/resources/Messages.properties
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplaceRuleAddDialog.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerParam.java
addOns/retire/CHANGELOG.md
addOns/retire/src/main/javahelp/org/zaproxy/addon/retire/resources/help/contents/retire.html
addOns/reveal/CHANGELOG.md
addOns/reveal/src/main/java/org/zaproxy/zap/extension/reveal/ExtensionReveal.java

Cherry picked from: https://github.com/zaproxy/zap-extensions/pull/3083 and rebased current.
For this one, I reverted the "pluggable" change in quickstart as it was only half done (variable names but not classes, etc). I'm not sure the "pending" change is worth keeping, so I can roll it back if wanted/needed just let me know.

Spelling Updates Batch 4

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CharsetMismatchScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieLooselyScopedScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InsecureAuthenticationScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/UserControlledHTMLAttributesScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ViewstateScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentTypeMissingScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureDebugErrorsScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InsecureAuthenticationScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/MixedContentScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/StrictTransportSecurityScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/UserControlledJavascriptEventScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ViewStateScanRuleUnitTest.java
addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
addOns/pscanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/CacheableScanRule.java
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/CacheableScanRuleUnitTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/InPageBannerInfoLeakScanRuleUnitTest.java

Based on: zaproxy/zap-extensions#3083 
* against
* aggregated
* decimal
* delimiters
* detected
* encoding
* expires
* multiple
* programmatically
* relevant
* reports
* response
* responseHas
* servlet
* should
* state
* threshold
* tighter
* unknown
* unused
* value
* verify
* without
Signed-off-by: Josh Soref <jsoref@users.noreply.github.com>

Spelling Updates Batch 6

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/BufferOverflowScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CloudMetadataScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CodeInjectionScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/RemoteFileIncludeScanRule.java
addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/BufferOverflowScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CloudMetadataScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CodeInjectionScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/RemoteFileIncludeScanRuleUnitTest.java

- Scan rules & Unit tests > Updated functionality and added tests to assert the new examples/refs.

ascanrules: Add Example Alerts and Alert Refs (Batch 2)

---

addOns/addOns.gradle.kts

The task is currently broken which breaks the release process.

Disable Crowdin source upload during release

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/authhelper.html

Authhelper: Fix code link in help

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/HeartBleedActiveScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/RemoteCodeExecutionCve20121823ScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureCve20121823ScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/HeartBleedActiveScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/RemoteCodeExecutionCve20121823ScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureCve20121823ScanRuleUnitTest.java
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/Log4ShellScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/Log4ShellScanRuleUnitTest.java
addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/HeartBleedScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/HeartBleedScannerUnitTest.java

- Scan rules > Added alert tags, where logical added alert refs.
- Scan rule unit tests > Added methods to assert the new/udpated tags and refs.
- CHANGELOGS > Added change notes.

various: Add CVE Alert Tags

---

addOns/addOns.gradle.kts
addOns/webdrivers/webdriverlinux/gradle.properties
addOns/webdrivers/webdrivermacos/gradle.properties
addOns/webdrivers/webdriverwindows/gradle.properties

Check if the Crowdin task exists before configuring it, also, run the task after the pull request that prepares the next dev iter.
Reset release state of failed releases to be restarted later.

Correct release task configuration

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java

https://groups.google.com/d/msgid/zaproxy-users/1739a65e-c1ff-41d9-bf32-bb93ae4cdca7n%40googlegroups.com?utm_medium=email&utm_source=footer

Automation: env var auth header fix

---

addOns/authhelper/authhelper.gradle.kts

- Add Crowdin config to build file.

authhelper: Add crowdin build config

---

addOns/encoder/CHANGELOG.md
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/ExtensionEncoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/PopupReplaceInputMenu.java
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/contents/encoder.html
addOns/encoder/src/main/resources/org/zaproxy/addon/encoder/resources/Messages.properties

- CHANGELOG.md > Added note.
- EncodeDecodeDialog.java > Change visibility of "getInputField()".
- encoder.html > Add output panel context menu details.
- ExtensionEncoder.java > Hook the new menu.
- Messages.properties > Add supporting key/value pair.
- PopupReplaceInputMenu.java > The new context menu class.

encoder: Add output context menu to replace input text

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRule.java

- cleanup comments
- remove simple code redundancies
- extend class documentation
Signed-off-by: PlainUrban <115159284+PlainUrban@users.noreply.github.com>

ascanrules: PathTraversalScanRule - simple cleanup

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParam.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParamElem.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJob.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJobDialog.java
addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/contents/automation.html
addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/Messages.properties
addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/spiderAjax-max.yaml

Fixes https://github.com/zaproxy/zaproxy/issues/7672
Based on https://github.com/zaproxy/zap-extensions/pull/4402
Sorry - I need to add support for this asap so taking over the development, but thanks for your initial PR @VitikaSoni

spiderAjax: AF HTML elements to click support

---

addOns/formhandler/CHANGELOG.md
addOns/formhandler/src/main/java/org/zaproxy/zap/extension/formhandler/FormHandlerParam.java
addOns/formhandler/src/main/java/org/zaproxy/zap/extension/formhandler/FormHandlerParamField.java
addOns/formhandler/src/test/java/org/zaproxy/zap/extension/formhandler/FormHandlerParamFieldUnitTest.java
addOns/formhandler/src/test/java/org/zaproxy/zap/extension/formhandler/FormHandlerParamPatternsUnitTest.java
addOns/formhandler/src/test/java/org/zaproxy/zap/extension/formhandler/FormHandlerParamUnitTest.java

- FormHandlerParam.java > Add functionality to add missing defaults to existing configs.
- FormHandlerParamField.java > Add toString() utility method to simplify logging.
- FormHandlerParamUnitTest.java > Handle version attribute.
- FormHandlerParamPatternsUnitTest > A new unit test class for testing patterns/matches.
- FormHandlerParamFieldUnitTest.java > Added to test equals method.
Based on scrolling through some of the arjun lists: https://github.com/s0md3v/Arjun/tree/master/arjun/db

formhandler: Add new defaults

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/zapHomeFiles/scripts/templates/extender/Copy as curl command menu.js

Apply changes done in zaproxy/community-scripts#319 and sync the script.

scripts: update curl extender template

---

addOns/formhandler/CHANGELOG.md
addOns/formhandler/src/main/java/org/zaproxy/zap/extension/formhandler/ExtensionFormHandler.java
addOns/formhandler/src/main/java/org/zaproxy/zap/extension/formhandler/OptionsFormHandlerPanel.java
addOns/formhandler/src/main/java/org/zaproxy/zap/extension/formhandler/PopupDialogAddField.java
addOns/formhandler/src/main/javahelp/org/zaproxy/zap/extension/formhandler/resources/help/contents/FormHandlerHelp.html

- ExtensionFormHandler > Add stats constants.
- OptionsFormHandlerPanel > Add stats handling for removals.
- PopupDialogAddField > Add stats handling for additions.
- FormHandlerHelp.html > Added stats info to the help.

formhandler: Add statistics

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/RequestModelConverter.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/converter/swagger/RequestModelConverterUnitTest.java

openapi: fix NPE when importing with body with empty dictionary

---

addOns/dev/CHANGELOG.md
addOns/dev/dev.gradle.kts
addOns/dev/gradle.properties
addOns/dev/src/main/java/org/zaproxy/addon/dev/DevParam.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/ExtensionDev.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestDirectory.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestPage.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestProxyServer.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJson/SimpleJsonDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJson/SimpleJsonLoginPage.java
addOns/dev/src/main/javahelp/org/zaproxy/addon/dev/resources/help/contents/dev.html
addOns/dev/src/main/javahelp/org/zaproxy/addon/dev/resources/help/helpset.hs
addOns/dev/src/main/javahelp/org/zaproxy/addon/dev/resources/help/index.xml
addOns/dev/src/main/javahelp/org/zaproxy/addon/dev/resources/help/map.jhm
addOns/dev/src/main/javahelp/org/zaproxy/addon/dev/resources/help/toc.xml
addOns/dev/src/main/resources/org/zaproxy/addon/dev/resources/Messages.properties
addOns/dev/src/main/zapHomeFiles/dev-add-on/404.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json/fail.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json/home.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json/index.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/index.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/tutorial.css
settings.gradle.kts

An add-on to help with ZAP development.
Initial commit just adds a test server and a very simple test login page.
The plan is to implement more realistic login pages asap to test ZAP authentication handling.

Dev: First version

---

addOns/addOns.gradle.kts

Update build to exclude dev add-on as it does not need to be translated.

dev: exclude from Crowdin

---

addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/JobUtilsUnitTest.java

Add test for fix done in #4437.

automation: test abs file path with vars and plan

---

addOns/dev/CHANGELOG.md

Should have been done in https://github.com/zaproxy/zap-extensions/pull/4553/ 😉

Dev: Auth verif changes

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureGitScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureGitScanRuleUnitTest.java

- Added example alerts for [Source Code Disclosure - Git](https://www.zaproxy.org/docs/alerts/41/)
- Added unit test for example alerts
- Added note to CHANGELOG
Issue Related: [zaproxy/zaproxy#6119](https://github.com/zaproxy/zaproxy/issues/6119)

ascanrulesBeta: add example alerts to Source Code Disclosure - Git

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/tests/AbstractAutomationTest.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/tests/AutomationStatisticTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/tests/AutomationStatisticTestUnitTest.java

Makes it much easier to see which one fails :grin:

Automation: add statistic name to test

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/payloader/ExtensionPayloader.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/payloader/ExtensionPayloaderUnitTest.java

As mentioned: https://github.com/zaproxy/zap-extensions/pull/4607#discussion_r1196853195
I'm diong this on github.dev and do agree to the DCO.

pscanrules: Unload error category

---

addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts
addOns/openapi/openapi.gradle.kts

- graphql: Update graphql-java
- openapi: Update swagger-parser

Update add-on dependencies

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/resources/org/zaproxy/addon/reports/resources/Messages.properties
addOns/reports/src/main/zapHomeFiles/reports/high-level-report/report.html
addOns/reports/src/main/zapHomeFiles/reports/modern/report.html
addOns/reports/src/main/zapHomeFiles/reports/risk-confidence-html/report.html
addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/report.html
addOns/reports/src/main/zapHomeFiles/reports/traditional-html/report.html
addOns/reports/src/main/zapHomeFiles/reports/traditional-pdf/report.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-html-plus.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-html.html

Added owasp zap version to html and pdf reports

reports: Add ZAP version to HTML and PDF reports

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ParameterTamperScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/ParameterTamperScanRuleUnitTest.java

- Add example alerts for [Parameter Tampering](https://www.zaproxy.org/docs/alerts/40008/)
- add unit test
- Add note on CHANGELOG
Related Issue: https://github.com/zaproxy/zaproxy/issues/6119

ascanrules: add example alerts to Parameter Tamper

---

addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts

Update `graphql-java` to version `20.4`.

graphql: Update dependency

---

addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/automation/ScriptJobUnitTest.java

Do not run the test if not able to change the readable permission and use newer APIs to check/change it.

scripts: add constraint to file readable test

---

addOns/postman/src/main/java/org/zaproxy/addon/postman/ExtensionPostman.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/ImportFromAbstractDialog.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/ImportFromFileDialog.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/ImportFromUrlDialog.java
addOns/postman/src/main/javahelp/org/zaproxy/addon/postman/resources/help/contents/postman.html
addOns/postman/src/main/resources/org/zaproxy/addon/postman/resources/Messages.properties

Part of https://github.com/zaproxy/zaproxy/issues/6960
Signed-off-by: VitikaSoni <vitika.program@gmail.com>

postman: Add dialogs for importing through the UI

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/FormatStringScanRule.java

- FormatStringScanRule > Added individual alert creation methods so that the ref only needs to be maintained in a single location. Also removed one unnecessary jump.
Follow-up to: https://github.com/zaproxy/zap-extensions/pull/4623

ascanrules: Format String scan rule refactor

---

addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/spiderajax/ExtensionAuthhelperAjax.java

Authhelper - stupid NPE fix

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ConnectionOptions.java
addOns/network/src/main/resources/org/zaproxy/addon/network/internal/client/common-user-agents.txt

Update the default user-agent and the list of user-agents provided.

network: update default user-agents

---

addOns/graaljs/CHANGELOG.md
addOns/graaljs/src/main/zapHomeFiles/scripts/templates/encode-decode/EncodeDecodeDefaultTemplate.js
addOns/graaljs/src/main/zapHomeFiles/scripts/templates/encode-decode/rot13.js
addOns/groovy/CHANGELOG.md
addOns/groovy/src/main/zapHomeFiles/scripts/templates/encode-decode/EncodeDecodeDefaultTemplate.groovy
addOns/jython/CHANGELOG.md
addOns/jython/src/main/zapHomeFiles/scripts/templates/encode-decode/EncodeDecodeDefaultTemplate.py
addOns/jython/src/main/zapHomeFiles/scripts/templates/encode-decode/rot13.py

- CHANGELOG.md > Add fix note.
- EncodeDecodeDefaultTemplate > Updated for new method signatures and docs.
- rot13 > Updated for new method signatures.
zaproxy/zaproxy#5996

graaljs/groovy/python: Update encode-decode templates

---

addOns/graphql/graphql.gradle.kts
addOns/network/network.gradle.kts
addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts
addOns/reports/CHANGELOG.md
addOns/reports/reports.gradle.kts
addOns/selenium/selenium.gradle.kts
addOns/soap/CHANGELOG.md
addOns/soap/soap.gradle.kts
addOns/spiderAjax/spiderAjax.gradle.kts
settings.gradle.kts

Use the same version as latest core, 2.20.0.

Update Log4j 2

---

addOns/database/CHANGELOG.md
addOns/database/database.gradle.kts

Update DataNucleus to 6.0.4.
Update SQLite JDBC to 3.42.0.0.
Update Flyway to 9.20.0.

database: update dependencies

---

addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodType.java

Authhelper - always process latest auth req

---

addOns/reports/reports.gradle.kts
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportHelper.java
addOns/reports/src/main/zapHomeFiles/reports/traditional-json-plus/report.json
addOns/reports/src/main/zapHomeFiles/reports/traditional-json/report.json
settings.gradle.kts

Update:
- Thymeleaf to 3.1.1.
- Jackson to 2.15.2.
- SnakeYAML to 2.6.
Use newer SLF4J binding.
Add workaround for Thymeleaf issue.

reports: update dependencies

---

addOns/automation/CHANGELOG.md
addOns/automation/automation.gradle.kts

Update:
- Jackson to 2.15.2.
- SnakeYAML to 2.6.

automation: update dependencies

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
addOns/pscanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/SiteIsolationScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/SourceCodeDisclosureScanRule.java
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/pscanrulesBeta/src/main/resources/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/SiteIsolationScanRuleTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/SourceCodeDisclosureScanRuleUnitTest.java

Promote pscan rules to release
N/A

2.13: Promote pscan rules

---

addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/HttpOnlySiteScanRuleUnitTest.java

Test that the alert is raised with the expected message.

ascanrulesBeta: test some `HttpOnlySiteScanRule`

---

addOns/network/network.gradle.kts
testutils/testutils.gradle.kts

Use main dependency and add the test framework.

Update test dependencies

---

addOns/addOns.gradle.kts

Update POM of add-ons

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/sarif/SarifReportDataSupport.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/sarif/SarifToolData.java
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/report-sarif-json.html
addOns/reports/src/main/resources/org/zaproxy/addon/reports/resources/Messages.properties
addOns/reports/src/main/zapHomeFiles/reports/high-level-report/report.html
addOns/reports/src/main/zapHomeFiles/reports/modern/report.html
addOns/reports/src/main/zapHomeFiles/reports/risk-confidence-html/report.html
addOns/reports/src/main/zapHomeFiles/reports/sarif-json/README.md
addOns/reports/src/main/zapHomeFiles/reports/sarif-json/report.json
addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/report.html
addOns/reports/src/main/zapHomeFiles/reports/traditional-html/report.html
addOns/reports/src/main/zapHomeFiles/reports/traditional-pdf/report.html
addOns/reports/src/test/java/org/zaproxy/addon/reports/sarif/SarifReportIntegrationUnitTest.java
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-html-plus.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-html.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-json-plus.json
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-json.json
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-xml-plus.xml
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-xml.xml

reports: update names

---

addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/env.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-config.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml

automation: update plan description

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/DefaultExplorePanel.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
addOns/quickstart/src/main/resources/org/zaproxy/zap/extension/quickstart/resources/Messages.properties

Remove OWASP references.
Update related code constants.

quickstart: update names

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CommandInjectionScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ElmahScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/GetForPostScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/HiddenFilesScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/TraceAxdScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/HttpsAsHttpScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/BigRedirectsScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyMissingScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ServerHeaderInfoLeakScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/StrictTransportSecurityScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XBackendServerInformationLeakScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XChromeLoggerDataInfoLeakScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XDebugTokenScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XPoweredByHeaderInfoLeakScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/InPageBannerInfoLeakScanRule.java

They aren't really necessary, and there's no point tweaking the alias.

various: Remove my authorship JavaDoc

---

addOns/coreLang/CHANGELOG.md
addOns/coreLang/coreLang.gradle.kts
addOns/coreLang/src/main/javahelp/org/zaproxy/zap/extension/coreLang/resources/help/contents/coreLang.html

coreLang: update links

---

addOns/selenium/CHANGELOG.md
addOns/selenium/selenium.gradle.kts

Update Selenium library to version 4.11.0.

selenium: update Selenium library

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/Messages.properties

Address pending review comment from #4745.

openapi: tweak case of menu item

---

addOns/network/CHANGELOG.md
addOns/network/src/main/javahelp/help/contents/options/servercertificates.html

Link back to the Save option when mentioning it.
Correct and capitalize the name of buttons and OS.
Minor reword of a paragraph and some sentences (e.g. fix typos).
Part of zaproxy/zaproxy#7983.

network: tweak help

---

addOns/graphql/src/test/java/org/zaproxy/addon/graphql/GraphQlFingerprinterUnitTest.java
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/GraphQlParserUnitTest.java

Test that the JSON parsing/checks work as expected.

graphql: test fingerprint

---

addOns/fuzz/src/main/javahelp/org/zaproxy/zap/extension/fuzz/resources/help/contents/concepts.html
addOns/fuzz/src/main/javahelp/org/zaproxy/zap/extension/fuzz/resources/help/contents/dialogue.html
addOns/fuzz/src/main/javahelp/org/zaproxy/zap/extension/fuzz/resources/help/contents/httpmessageprocessors.html
addOns/fuzz/src/main/javahelp/org/zaproxy/zap/extension/fuzz/resources/help/contents/locations.html
addOns/fuzz/src/main/javahelp/org/zaproxy/zap/extension/fuzz/resources/help/contents/options.html
addOns/fuzz/src/main/javahelp/org/zaproxy/zap/extension/fuzz/resources/help/contents/payloads.html
addOns/fuzz/src/main/javahelp/org/zaproxy/zap/extension/fuzz/resources/help/contents/processors.html
addOns/fuzz/src/main/javahelp/org/zaproxy/zap/extension/fuzz/resources/help/contents/tab.html

Just little things I noticed while referring others to the help content.

fuzzer: Minor help tweaks

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java

Use the methods directly now that they are already available.

network: remove reflection

---

addOns/client/src/main/java/org/zaproxy/addon/client/ClientIntegrationAPI.java

Use the zap domain so we dont have to worry about port init and changes.
None
Tested manually - not practical to add unit tests for this?

Client: Fix init

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java

- CHANGELOG.md > Add fix note.
- ExtensionWappalyzer > Tweak init to ensure GUI status is properly interpreted.

wappalyzer: Tweak GUI check to ensure icons render

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/ascanrules.gradle.kts
addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/commonlib/CHANGELOG.md
addOns/commonlib/commonlib.gradle.kts
addOns/commonlib/gradle/crowdin.yml
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/ExtensionCommonlib.java
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/internal/vulns/LegacyVulnerabilities.java
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/internal/vulns/LegacyVulnerabilitiesLoader.java
addOns/commonlib/src/main/resources/org/zaproxy/addon/commonlib/internal/vulns/vulnerabilities.xml
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/internal/vulns/LegacyVulnerabilitiesLoaderUnitTest.java
addOns/commonlib/src/test/resources/org/zaproxy/addon/commonlib/internal/vulns/invalid/vulnerabilities-test-invalid-xml.xml
addOns/commonlib/src/test/resources/org/zaproxy/addon/commonlib/internal/vulns/vulnerabilities-test.xml
addOns/commonlib/src/test/resources/org/zaproxy/addon/commonlib/internal/vulns/vulnerabilities-test.xml2
addOns/commonlib/src/test/resources/org/zaproxy/addon/commonlib/internal/vulns/vulnerabilities-test2.xml
addOns/commonlib/src/test/resources/org/zaproxy/addon/commonlib/internal/vulns/vulnerabilities-test_es.xml
addOns/commonlib/src/test/resources/org/zaproxy/addon/commonlib/internal/vulns/vulnerabilities-test_nl_NL.xml
addOns/domxss/CHANGELOG.md
addOns/domxss/domxss.gradle.kts
addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/pscanrules.gradle.kts
addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts

Bundle vulnerability data in the add-on and provide it through the core classes.
Update add-ons to depend on the newer version of commonlib to force the data to be available.
Part of zaproxy/zaproxy#8012.

commonlib: add vulnerability data

---

addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestAuthDirectory.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/nonStdJsonBearer/NonStdJsonBearerDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/passswordAddedNoSubmit/PasswordAddedNoSubmitDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/passwordAddedJson/PasswordAddedJsonDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/passwordHiddenJson/PasswordHiddenJsonDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/passwordNewPage/PasswordNewPageDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJson/SimpleJsonDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonBearer/SimpleJsonBearerDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonBearerCookie/SimpleJsonBearerCookieDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonCookie/SimpleJsonCookieDir.java

Dev: Add abstract TestAuthDirectory class

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/wappalyzer.gradle.kts

Update jsoup and RE2/J to latest versions.

wappalyzer: update dependencies

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ScriptsListPanel.java

- allow script node to set focus as optional 
Part of zaproxy/zaproxy#8050.

scripts: allow script node to set focus as optional

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/JobUtils.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/JobUtilsUnitTest.java
addOns/replacer/CHANGELOG.md
addOns/replacer/replacer.gradle.kts
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/OptionsReplacerPanel.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplaceRuleAddDialog.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplaceRuleModifyDialog.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerParam.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerParamRule.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/automation/ExtensionReplacerAutomation.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/automation/ReplacerJob.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/automation/ReplacerJobDialog.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/automation/ReplacerTableModel.java
addOns/replacer/src/main/javahelp/org/zaproxy/zap/extension/replacer/resources/help/contents/automation.html
addOns/replacer/src/main/javahelp/org/zaproxy/zap/extension/replacer/resources/help/contents/replacer.html
addOns/replacer/src/main/javahelp/org/zaproxy/zap/extension/replacer/resources/help/index.xml
addOns/replacer/src/main/javahelp/org/zaproxy/zap/extension/replacer/resources/help/map.jhm
addOns/replacer/src/main/javahelp/org/zaproxy/zap/extension/replacer/resources/help/toc.xml
addOns/replacer/src/main/resources/org/zaproxy/zap/extension/replacer/resources/Messages.properties
addOns/replacer/src/main/resources/org/zaproxy/zap/extension/replacer/resources/replacer-max.yaml
addOns/replacer/src/main/resources/org/zaproxy/zap/extension/replacer/resources/replacer-min.yaml
addOns/replacer/src/test/java/org/zaproxy/zap/extension/replacer/automation/ReplacerJobUnitTest.java

Fixes https://github.com/zaproxy/zaproxy/issues/7686

Replacer: Support automation framework

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/resources/org/zaproxy/addon/commonlib/internal/vulns/vulnerabilities.xml

Change all CWE references to use HTTPS scheme.

commonlib: use HTTPS for CWE vuln references

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/pscanrules.gradle.kts

Update RE2/J to latest version.

pscanrules: update dependency

---

addOns/spider/CHANGELOG.md
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/DsStoreParser.java

Fix a typo in a log statement.

spider: fix typo in log statement

---

addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlFingerprinter.java
addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/GraphQlFingerprinterUnitTest.java

Add new check for the Absinthe GraphQL engine, based on https://github.com/dolevf/graphw00f/pull/30.

graphql: Add new fingerprinting check

---

addOns/postman/src/main/java/org/zaproxy/addon/postman/PostmanParser.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/Requestor.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/Body.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/Item.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/ItemGroup.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/KeyValueData.java
addOns/postman/src/test/java/org/zaproxy/addon/postman/PostmanParserUnitTest.java
addOns/postman/src/test/resources/org/zaproxy/addon/postman/sampleFile.txt

postman: Implement sending http requests

---

addOns/webdrivers/webdriverwindows/CHANGELOG.md
addOns/webdrivers/webdriverwindows/webdriverwindows.gradle.kts

Add ChromeDriver for x64 arch.

webdriverwindows: include ChromeDriver x64

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/AttackThread.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ZapItScan.java
addOns/quickstart/src/main/javahelp/org/zaproxy/zap/extension/quickstart/resources/help/contents/cmdline.html
addOns/quickstart/src/main/javahelp/org/zaproxy/zap/extension/quickstart/resources/help/contents/quickstart.html
addOns/quickstart/src/main/javahelp/org/zaproxy/zap/extension/quickstart/resources/help/contents/zapit.html
addOns/quickstart/src/main/javahelp/org/zaproxy/zap/extension/quickstart/resources/help/index.xml
addOns/quickstart/src/main/javahelp/org/zaproxy/zap/extension/quickstart/resources/help/map.jhm
addOns/quickstart/src/main/javahelp/org/zaproxy/zap/extension/quickstart/resources/help/toc.xml
addOns/quickstart/src/main/resources/org/zaproxy/zap/extension/quickstart/resources/Messages.properties

QuickStart: ZAPit first phase

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/javahelp/org/zaproxy/zap/extension/quickstart/resources/help/contents/cmdline.html
addOns/quickstart/src/main/javahelp/org/zaproxy/zap/extension/quickstart/resources/help/contents/quickstart.html

Quickstart: Fix ZAPit help links

---

addOns/postman/src/main/java/org/zaproxy/addon/postman/ImportDialog.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/PostmanParser.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/Requestor.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/Item.java
addOns/postman/src/main/resources/org/zaproxy/addon/postman/resources/Messages.properties
addOns/postman/src/test/java/org/zaproxy/addon/postman/PostmanParserUnitTest.java

postman: Implement error reporting

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/AttackThread.java

Quickstart: Fix leaf node getting selected

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
addOns/quickstart/src/main/javahelp/org/zaproxy/zap/extension/quickstart/resources/help/contents/zapit.html

QuickStart ZAPit: scan HTTP and HTTPS if protocol not specified

---

addOns/postman/CHANGELOG.md
addOns/postman/src/main/java/org/zaproxy/addon/postman/PostmanParser.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/Body.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/Item.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/ItemGroup.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/KeyValueData.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/PostmanCollection.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/Request.java
addOns/postman/src/main/javahelp/org/zaproxy/addon/postman/resources/help/contents/postman.html
addOns/postman/src/test/java/org/zaproxy/addon/postman/PostmanParserUnitTest.java

[Postman reference to variables](https://learning.postman.com/collection-format/reference/variable/)

postman: Support collection json variables

---

addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/contents/client.html

client: fix typo in help page

---

addOns/custompayloads/CHANGELOG.md
addOns/custompayloads/custompayloads.gradle.kts

- custompayloads.gradle.kts > Promote to beta.

custompayloads: Promote to Beta

---

addOns/addOns.gradle.kts

Add task to create the runtime BOM and configure the add-on file task to include it.

Bundle runtime BOM in the add-ons

---

addOns/webdrivers/webdriverlinux/gradle.properties
addOns/webdrivers/webdrivermacos/gradle.properties
addOns/webdrivers/webdriverwindows/gradle.properties

Update the release flag to continue with the release process.

Trigger release of pending add-ons

---

addOns/webdrivers/webdriverlinux/gradle.properties
addOns/webdrivers/webdrivermacos/gradle.properties
addOns/webdrivers/webdriverwindows/gradle.properties

Update the release flag to continue with the release process.

Trigger release of pending add-ons, take 2

---

addOns/callhome/CHANGELOG.md
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java

Upload the new config stats
https://github.com/zaproxy/zaproxy/pull/8118

CallHome: upload config stats

---

.github/workflows/create_wappalyzer_update.yml

wappalyzer: Update GitHub actions workflow for getting upstream updates

---

.github/workflows/create_wappalyzer_update.yml

Follow-up to zaproxy/zap-extensions#5015

wappalyzer: Fix bad path in workflow

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/resources/org/zaproxy/addon/commonlib/internal/vulns/vulnerabilities.xml

- Add mitigation information about 'Content Spoofing' vulnerability.
- Add mitigation information about 'Credential and Session Prediction' vulnerability.
- Add mitigation information about 'XML Injection' vulnerability.
- Add mitigation information about 'XML External Entities' vulnerability.
- Update changelog.
https://github.com/zaproxy/zaproxy/issues/8056

commonlib: add solution to vulnerabilities

---

.github/workflows/sonar.yml

https://docs.sonarcloud.io/appendices/scanner-environment/#java-configuration

sonar workflow: Switch to Java 17

---

addOns/client/CHANGELOG.md
addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/contents/firefox-profile.html

Update client help to explain the potential problems with the client Firefox profile in custom containers.
https://github.com/zaproxy/zaproxy/pull/8154

Client - custom container help note

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/ClientMap.java
addOns/client/src/main/java/org/zaproxy/addon/client/ClientNode.java
addOns/client/src/main/java/org/zaproxy/addon/client/ClientUtils.java
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/test/java/org/zaproxy/addon/client/ClientMapUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/ClientNodeUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/ClientUtilsUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/MissingUrlsThreadUnitTest.java

Reworked (rewrote?;) the Client Map to handle parameters correctly and various edge cases, inc fragments on URLs with parameters.

Client: Rework Client Map

---

addOns/client/CHANGELOG.md
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/Messages.properties

Remove the description of an API endpoint that does not exist.

client: remove unused resource message

---

addOns/custompayloads/CHANGELOG.md
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsApi.java
addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/contents/api.html
addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/index.xml
addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/map.jhm
addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/toc.xml
addOns/custompayloads/src/main/resources/org/zaproxy/zap/extension/custompayloads/resources/Messages.properties

- CustomPayloadsApi > The new API functionality.
- CustomPayloadsApiUnitTest > Add general tests.
- Messages.properties > The descriptor keys/values for the new API components.
- api.html > New API help content.
- index.xml, map.jhm, toc.xml > Link/configure new API help content.

custompayloads: Add Initial API (actions)

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/resources/org/zaproxy/addon/commonlib/internal/vulns/vulnerabilities.xml

Added solution for the vulnerabilty : 'Brute Forcing Credit Card Information'
zaproxy/zaproxy#8056

commonlib: added solution to 'Brute Forcing Credit Card Information' vulnerability

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/resources/org/zaproxy/addon/commonlib/internal/vulns/vulnerabilities.xml

Added solution for : 'Fingerprinting'
zaproxy/zaproxy#8056

commonlib: added solution to Fingerprinting vulnerability (Issue 8056)

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AutomationPanel.java

Allow to show/hide columns and auto resize them.

automation: show column control in Automation tab

---

addOns/jython/CHANGELOG.md
addOns/jython/src/main/java/org/zaproxy/zap/extension/jython/ExtensionJython.java
addOns/jython/src/test/java/org/zaproxy/zap/extension/jython/ExtensionJythonUnitTest.java

Remove the script engine when the extension is unloaded.

jython: remove script engine on unload

---

addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java

Increase the number since the tests might send some more.
---
e.g.: https://github.com/zaproxy/zap-extensions/actions/runs/6907058541/job/18945445000#step:7:621

domxss: update msgs allowed testing low strength

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/ClientHistoryPanel.java
addOns/client/src/main/java/org/zaproxy/addon/client/ClientOptions.java
addOns/client/src/main/java/org/zaproxy/addon/client/ClientUtils.java
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/MissingUrlsThread.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/ClientPassiveAbstractScanRule.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/ClientPassiveScanController.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/ClientPassiveScanHelper.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/ClientPassiveScanRule.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/InformationInStorageScanRule.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/OptionsPassiveScan.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/SensitiveInfoInStorageScanrule.java
addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/contents/client.html
addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/contents/pscan.html
addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/index.xml
addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/map.jhm
addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/toc.xml
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/Messages.properties
addOns/client/src/test/java/org/zaproxy/addon/client/ClientParamUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/ClientUtilsUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/pscan/ClientPassiveScanControllerUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/pscan/InformationInStorageUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/pscan/SensitiveInfoInStorageUnitTest.java

Client: Support passive scanning

---

addOns/kotlin/CHANGELOG.md
addOns/kotlin/kotlin.gradle.kts
addOns/kotlin/src/main/zapHomeFiles/scripts/templates/encode-decode/encode-decode-template.kts

- CHANGELOG > Added entry.
- encode-decode-template.kts > The new template.
zaproxy/zaproxy#5996

kotlin: Add encode-decode template

---

addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestProxyServer.java
addOns/dev/src/main/javahelp/org/zaproxy/addon/dev/resources/help/contents/dev.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/localStorage/index.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/localStorage/jwt-none.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/localStorage/jwt.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/localStorage/safe.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/localStorage/safeb64.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/localStorage/sensitive.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/localStorage/sensitiveb64.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/sessionStorage/index.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/sessionStorage/jwt-none.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/sessionStorage/jwt.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/sessionStorage/safe.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/sessionStorage/safeb64.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/sessionStorage/sensitive.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/sessionStorage/sensitiveb64.html

Pages which store a variety of data in localStorage and sessionStorage.

Dev: add localStorage and sessionStorage examples.

---

addOns/client/CHANGELOG.md
addOns/client/client.gradle.kts
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/ClientPassiveScanController.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/ClientPassiveScanHelper.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/InformationInStorageScanRule.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/JwtInStorageScanRule.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/SensitiveInfoInStorageScanRule.java
addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/contents/pscan.html
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/Messages.properties
addOns/client/src/test/java/org/zaproxy/addon/client/pscan/ClientPassiveScanControllerUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/pscan/ClientPassiveScanHelperUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/pscan/InformationInStorageScanRuleUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/pscan/JwtInStorageScanRuleUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/pscan/SensitiveInfoInStorageScanRuleUnitTest.java

Add support for base64 decoding and JWT detection in browser storage.
Also corrected the names of a few files.
https://github.com/zaproxy/zaproxy/pull/8218

Client: Passive scan base64 decoding and JWT support

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/ClientHistoryTableModel.java
addOns/client/src/main/java/org/zaproxy/addon/client/ClientIntegrationAPI.java
addOns/client/src/main/java/org/zaproxy/addon/client/ClientSideComponent.java
addOns/client/src/main/java/org/zaproxy/addon/client/ComponentTableModel.java
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/ReportedElement.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/InformationInStorageScanRule.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/JwtInStorageScanRule.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/SensitiveInfoInStorageScanRule.java
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/Messages.properties

Adds additional input field data returned from the browser extension.
https://github.com/zaproxy/browser-extension/pull/87

Client: additional input field data

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlFingerprinter.java
addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/GraphQlFingerprinterUnitTest.java

Add new check for the GraphQL.NET engine, based on https://github.com/dolevf/graphw00f/pull/33.

graphql: Add Fingerprinting check for GraphQL.NET

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionPostgreScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionPostgreScanRuleUnitTest.java

Hey zap team, this is another time based FP fix for postgresql injection. Here solution is similar to previously raised PRs(https://github.com/zaproxy/zap-extensions/pull/4679). Also, this branch is checkout from that nosql branch. So, before merging this expecting that above mentioned PR to be merged.
Regards,
Divyansh Jain (from astra security)

ascanrules: FP fix for postgres timebased fp

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/CommonActiveScanRuleInfo.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRule.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjectionScanRule.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/WebCacheDeceptionScanRule.java
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html

Link from/to the help and website.
Part of zaproxy/zaproxy#8189.

ascanrulesAlpha: add alert links for website/help

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionHypersonicScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionHypersonicScanRuleUnitTest.java

Adapt `SqlInjectionHypersonicScanRule` to do the time-based tests with the timing utils.

ascanrules: use timing utils in Hyper scan rule

---

addOns/client/src/main/java/org/zaproxy/addon/client/ClientMap.java
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpiderTask.java
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/Messages.properties
addOns/client/src/test/java/org/zaproxy/addon/client/ClientMapUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/ClientNodeUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/MissingUrlsThreadUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/spider/ClientSpiderUnitTest.java

First phase of the new client spider. Not for release at this stage.
It can be tested using a ZAP standalone scripts like:
```
var extClient = control.getExtensionLoader().getExtension("ExtensionClientIntegration");
print(extClient.runSpider('http://localhost:3000/', "firefox", 4, 5, 2, 5));
print(extClient.getSpider(0).getProgress());
```

Client: spider, first phase

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionMySqlScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionMySqlScanRuleUnitTest.java

ascanrules: Using timing utils in MYSQL

---

addOns/client/src/main/java/org/zaproxy/addon/client/ClientOptions.java
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/test/java/org/zaproxy/addon/client/ClientParamUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/spider/ClientSpiderUnitTest.java

Change the client spider to use the config options. Also added a set of options which are not currently used .. but will be very soon :wink:

Client: Use options

---

addOns/client/src/main/java/org/zaproxy/addon/client/ClientMap.java
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/test/java/org/zaproxy/addon/client/ExtensionClientIntegrationUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/spider/ClientSpiderUnitTest.java

As per the title ;)
There are no unit tests for the max duration as that is in minutes.
It can be (and has been;) tested manually by updating the config file to set a max duration and then running the spider vs a big site, like https://www.bbc.co.uk/

Client: Implement spider limits

---

addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/httputils/HtmlContextAnalyserUnitTest.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/SsrfScanRuleUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/tests/AutomationAlertTestUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/zest/ExtensionClientZestTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/Base64DecoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/Base64EncoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/Base64UrlDecoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/Base64UrlEncoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/FullUrlDecoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/FullUrlEncoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/HexStringDecoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/HexStringEncoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/HtmlStringDecoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/HtmlStringEncoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/IllegalUTF8With2ByteEncoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/IllegalUTF8With3ByteEncoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/IllegalUTF8With4ByteEncoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/JavaScriptStringDecoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/JavaScriptStringEncoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/UnicodeDecoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/UnicodeEncoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/UrlDecoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/UrlEncoderUnitTest.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/script/EncodeDecodeScriptUnitTest.java
addOns/kotlin/src/test/java/org/zaproxy/addon/kotlin/TestUtils.java
addOns/paramdigger/src/test/java/org/zaproxy/addon/paramdigger/UrlGuesserUnitTest.java
addOns/replacer/src/test/java/org/zaproxy/zap/extension/replacer/automation/ReplacerJobUnitTest.java
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/automation/ScriptJobOutputListenerUnitTest.java

Remove public from test classes where it's not needed.

Remove unnecessary modifier in test classes

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/resources/org/zaproxy/addon/commonlib/internal/vulns/vulnerabilities.xml

- Add mitigation information about 'Server Misconfiguration' vulnerability.
- Add mitigation information about 'Application Misconfiguration' vulnerability.
- Update changelog.
https://github.com/zaproxy/zaproxy/issues/8056

commonlib: add solution to 'Server Misconfiguration' and 'Application Misconfiguration'

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/ascanrules.gradle.kts
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CommandInjectionScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrlfInjectionScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/GetForPostScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/HeartBleedActiveScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PaddingOracleScanRule.java
addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CommandInjectionScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrlfInjectionScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/DirectoryBrowsingScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/ElmahScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/EnvFileScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/ExternalRedirectScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/FormatStringScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/GetForPostScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/HeartBleedActiveScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/HiddenFilesScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/HtAccessScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/Log4ShellScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/PaddingOracleScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/PathTraversalScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/RemoteFileIncludeScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/TraceAxdScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/UserAgentScanRuleUnitTest.java
addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/AbstractAppFilePlugin.java
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/AbstractHostFilePlugin.java

- Added example alert and reference verification for some rules.
- zaproxy/zaproxy#8262

ascanrules/commonlib: Add example alerts & refs check

---

addOns/webuipoc/CHANGELOG.md
addOns/webuipoc/README.md
addOns/webuipoc/docs/example/README.md
addOns/webuipoc/gradle.properties
addOns/webuipoc/src/main/java/org/zaproxy/addon/webuipoc/ExtensionWebUiPoc.java
addOns/webuipoc/src/main/java/org/zaproxy/addon/webuipoc/TestProxyServer.java
addOns/webuipoc/src/main/resources/org/zaproxy/addon/webuipoc/resources/Messages.properties
addOns/webuipoc/src/main/zapHomeFiles/webuipoc/404.html
addOns/webuipoc/src/main/zapHomeFiles/webuipoc/example/example.js
addOns/webuipoc/src/main/zapHomeFiles/webuipoc/example/index.html
addOns/webuipoc/src/main/zapHomeFiles/webuipoc/example/reqresp.css
addOns/webuipoc/src/main/zapHomeFiles/webuipoc/example/reqresp.html
addOns/webuipoc/src/main/zapHomeFiles/webuipoc/example/reqresp.js
addOns/webuipoc/src/main/zapHomeFiles/webuipoc/example/sites.css
addOns/webuipoc/src/main/zapHomeFiles/webuipoc/example/sites.html
addOns/webuipoc/src/main/zapHomeFiles/webuipoc/example/sites.js
addOns/webuipoc/src/main/zapHomeFiles/webuipoc/index.html
addOns/webuipoc/src/main/zapHomeFiles/webuipoc/root.css
addOns/webuipoc/webuipoc.gradle.kts
settings.gradle.kts

First phase of an add-on that GSoC contributors can use to create PoCs for the Web based UI project.

Webuipoc: Initial PR

---

addOns/webuipoc/README.md

Webuipoc: video link plus extra info

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CloudMetadataScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/HiddenFilesScanRule.java

Fixes https://github.com/zaproxy/zaproxy/issues/7710
Will PR a fix for the core as well.
I tried to create unit tests that failed without the fix but it was too hard to mock everything :/
Have tested manually vs the server specified on
https://github.com/zaproxy/zaproxy/issues/8234#issuecomment-1854631994
Replaces core methods that can lead to FPs.
https://github.com/zaproxy/zaproxy/issues/8234

ascanrules: Fix FPs on redirects

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html
addOns/wappalyzer/src/main/resources/org/zaproxy/zap/extension/wappalyzer/resources/Messages.properties

Per recent goings on. (Since late August 2023.)

Make resource values and help less Wappalyzer centric

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureWebInfScanRule.java
addOns/ascanrules/src/main/javahelp/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureWebinfScanRuleUnitTest.java
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/HttpsAsHttpScanRule.java
addOns/ascanrulesBeta/src/main/resources/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/HttpsAsHttpScanRuleUnitTest.java
addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieSameSiteScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InsecureFormLoadScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InsecureFormPostScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/MixedContentScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/UserControlledJavascriptEventScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XDebugTokenScanRule.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieSameSiteScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InsecureFormLoadScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InsecureFormPostScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/MixedContentScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/UserControlledJavascriptEventScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/XDebugTokenScanRuleUnitTest.java

- Scan rules > Add example alert functionality and alert refs where logical.
- Unit Tests > Add tests to assert the example alerts and references.
- zaproxy/zaproxy#7100
- zaproxy/zaproxy#8262

Various Add-ons: More example alerts

---

addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CodeInjectionScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/ParameterTamperScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/RemoteCodeExecutionCve20121823ScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/XxeScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InfoPrivateAddressDisclosureScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureDebugErrorsScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/MixedContentScanRuleUnitTest.java

- UnitTests > Where practical use ParameterizedTest vs. for loops. Use braces on single statement conditions or loops for consistency.

scan rule unit tests: Parameterize vs looping

---

.github/workflows/cla.yml

CLA: use full action

---

addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthenticationDetectionScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CrossDomainScriptInclusionScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/LinkTargetScanRuleUnitTest.java

Use non-deprecated annotation parameter.

Address deprecations in tests

---

addOns/exim/CHANGELOG.md
addOns/exim/src/main/java/org/zaproxy/addon/exim/ExtensionExim.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/pcap/MenuItemImportPcap.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/pcap/PcapImporter.java
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/Messages.properties
addOns/exim/src/test/java/org/zaproxy/addon/exim/pcap/PcapImporterUnitTest.java

Start of the work on the pcap import project. Added a Menu Item, and basic files to start implementing.
zaproxy/zaproxy#4812

exim: pcap/pacpng import Start + Menu Item

---

addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Verify that Basic authentication is done even without realm.
Close zaproxy/zaproxy#5538.

network: add test for basic auth without realm

---

addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java

zaproxy/zap-extensions#5233
- [NA] Update changelog - Already has maint note

wappalyzer: Tweak startup messages

---

addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/javahelp/org/zaproxy/zap/extension/selenium/resources/help/contents/intro.html

Fix typo in doc
With 💚 from Tecvity

selenium: fix typo in help

---

addOns/postman/CHANGELOG.md
addOns/postman/postman.gradle.kts
addOns/postman/src/main/java/org/zaproxy/addon/postman/automation/ExtensionPostmanAutomation.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/automation/PostmanJob.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/automation/PostmanJobDialog.java
addOns/postman/src/main/javahelp/org/zaproxy/addon/postman/resources/help/contents/automation.html
addOns/postman/src/main/javahelp/org/zaproxy/addon/postman/resources/help/contents/postman.html
addOns/postman/src/main/resources/org/zaproxy/addon/postman/automation/postman-max.yaml
addOns/postman/src/main/resources/org/zaproxy/addon/postman/automation/postman-min.yaml
addOns/postman/src/main/resources/org/zaproxy/addon/postman/resources/Messages.properties
addOns/postman/src/test/java/org/zaproxy/addon/postman/automation/PostmanJobUnitTest.java

postman: Add automation support

---

.github/workflows/create_tech_update.yml

Tweak Tech Detection Update Workflow

---

addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java

Disable test that no longer raises an alert.

domxss: disable failing test

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/resources/org/zaproxy/addon/commonlib/internal/vulns/vulnerabilities.xml

Adds possible solutions to prevent the HTTP Response Smuggling vulnerability.
Part of zaproxy/zaproxy#8056.

commonlib: add solution for HTTP Response Smuggling vulnerability

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties

- Messages.properties > Updated refs.
Fixes zaproxy/zaproxy#8262

ascanrulesalpha: LDAPi update alert refs

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerData.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/AppsJsonParseUnitTest.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/JsonParserUnitTest.java
addOns/wappalyzer/src/test/resources/org/zaproxy/zap/extension/wappalyzer/broken.json

Parallelize loading of tech files for performance reasons.
N/A

tech detection: Parallelize loading of tech files

---

addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/commonlib/CHANGELOG.md
addOns/commonlib/commonlib.gradle.kts
addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/pscanrules.gradle.kts
addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/wappalyzer.gradle.kts
build.gradle.kts

- Update CHANGELOGs where applicable (ascanrulesBeta already has a maint note).
- Update build files where applicable
- Update error_prone_core globally.

various add-ons: Update dependencies

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJobResultData.java
addOns/reports/CHANGELOG.md
addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/report.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-html-plus.html

I tried these changes but it's giving an OGNL error so they are most likely incorrect. Need help in resolving them :(
I also forgot to sign the commits. I'll rebase and fix them later.
Part of zaproxy/zaproxy#7022.

reports: include number nodes actively scanned

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/automation.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties

Download and run the automation plan if the provided source is a URI with HTTP(S) scheme, otherwise load it directly from the file system as before.

automation: support remote plan in cmd line

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartSubPanel.java

Quickstart: Fix sub panel headers

---

addOns/grpc/CHANGELOG.md

[zaproxy/zaproxy#7695](https://github.com/zaproxy/zaproxy/issues/7695)

grpc: changelog for first release added

---

addOns/grpc/CHANGELOG.md
addOns/grpc/src/main/java/org/zaproxy/addon/grpc/ExtensionGrpc.java
addOns/grpc/src/main/java/org/zaproxy/addon/grpc/internal/VariantGrpc.java
addOns/grpc/src/main/javahelp/org/zaproxy/addon/grpc/resources/help/contents/grpc.html
addOns/grpc/src/main/javahelp/org/zaproxy/addon/grpc/resources/help/contents/variant.html
addOns/grpc/src/main/javahelp/org/zaproxy/addon/grpc/resources/help/index.xml
addOns/grpc/src/main/javahelp/org/zaproxy/addon/grpc/resources/help/map.jhm
addOns/grpc/src/main/javahelp/org/zaproxy/addon/grpc/resources/help/toc.xml
addOns/grpc/src/test/java/org/zaproxy/addon/grpc/internal/VariantGrpcUnitTest.java

This is help to apply active scan rules for grpc requests
[zaproxy/zaproxy#7695](https://github.com/zaproxy/zaproxy/issues/7695)

grpc: Variant for gRPC request added

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/NewsItem.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartPanel.java

Quickstart: News item tweak

---

addOns/addOns.gradle.kts
build.gradle.kts
buildSrc/src/main/java/org/zaproxy/gradle/tasks/ProcessSvnDiggerFiles.java

Disable or suppress "this escape" as that's unavoidable in most of the codebase.

Address some Java 21 warns

---

.github/workflows/codeql.yml

Update actions in CodeQL workflow

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/resources/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties
addOns/sqliplugin/src/main/resources/org/zaproxy/zap/extension/sqliplugin/resources/Messages.properties

- Messages.properties > Updated various resource messages, removed some that were unused.
---
I also tackled the Adv SQLi add-on as part of this PR, it only needed the addition of a single period and already has a maint note in its CHANGELOG.
zaproxy/zap-extensions#5522

ascanrules (alpha/beta/sqli): Alert text fixes (periods and whitespace(s))

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/PolyfillCdnScriptScanRule.java
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/pscanrulesBeta/src/main/resources/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/PolyfillCdnScriptScanRuleUnitTest.java

Pscanbeta: More polyfill domains

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/resources/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties

Noticed it in https://github.com/zaproxy/zaproxy-website/pull/2702.

Fix typo in polyfill.io script detection alert description

---

addOns/pscan/CHANGELOG.md
addOns/pscan/src/main/java/org/zaproxy/addon/pscan/ExtensionPassiveScan2.java
addOns/pscan/src/main/java/org/zaproxy/addon/pscan/internal/StatsPassiveScanner.java
addOns/pscan/src/main/resources/org/zaproxy/addon/pscan/resources/Messages.properties
addOns/pscan/src/test/java/org/zaproxy/addon/pscan/internal/StatsPassiveScannerUnitTest.java

Migrate the stats scan rule from core.

pscan: add stats scan rule

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastParam.java
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_ar_SA/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_az_AZ/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_bs_BA/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_da_DK/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_de_DE/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_el_GR/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_es_ES/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_fa_IR/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_fil_PH/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_fr_FR/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_hi_IN/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_hu_HU/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_id_ID/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_it_IT/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_ja_JP/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_ms_MY/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_pl_PL/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_pt_BR/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_ro_RO/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_ru_RU/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_sr_CS/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_tr_TR/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_ur_PK/contents/services/services.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help_zh_CN/contents/services/services.html
addOns/oast/src/main/zapHomeFiles/scripts/scripts/standalone/OAST Get BOAST Servers.js

Use the new port of the server.

oast: update BOAST port

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/RemoteFileIncludeScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/RemoteFileIncludeScanRuleUnitTest.java

- RemoveFileIncludeScanRule > Improve patterns to prevent false positives.
- RemoveFileIncludeScanRuleUnitTest > Expand one test and add one test.
Fixes zaproxy/zaproxy#8561

ascanrules: Fix RFI FP

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechPanel.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerParam.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html
addOns/wappalyzer/src/main/resources/org/zaproxy/zap/extension/wappalyzer/resources/Messages.properties
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/PassiveScannerUnitTest.java

- PassiveScannertUnitTest - Updated to accommodate the new behavior.
- WappalyzerPassiveScanner - Updated to handle mode and stop processing further patterns after first match (as appropriate).
- ExtensionWappalyzer - Updated to handle the new option.
- Messages.properties - Added supporting resources.
- TechPanel - Updated to handle the new toggle button.
- wappalyzer.html - Updated toolbar details.
- WappalyzerParam - Updated to handle the new option.
- zaproxy/zaproxy#8361
Modeled after:
- zaproxy/zap-extensions#2428
- zaproxy/zap-extensions#2344

tech detection: Add mode handling

---

addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestDirectory.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonCookie/SimpleJsonCookieDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonCookie/SimpleJsonCookieIndexPage.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonCookie/SimpleJsonCookiePage1.java
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json-cookie/home.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json-cookie/page1.html
addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java

Fix problem where AJAX spider would loop when using browser based authentication.

AJAX Spider: fix issue with browser based auth

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/PolyfillCdnScriptScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/PolyfillCdnScriptScanRuleUnitTest.java
addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/pscanrulesBeta/src/main/resources/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties

Promote the pollyfill passive scan rule to release.

Promote polyfill rule to release

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechOptionsPanel.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechPanel.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html
addOns/wappalyzer/src/main/resources/org/zaproxy/zap/extension/wappalyzer/resources/Messages.properties

- CHANGELOG.md > Updated change note
- ExtensionWappalyzer.java > Updated handling
- TechOptionsPanel.java > Added to handle the options UI.
- TechPanel.java > Removed the toggle button and associated handling.
- Messages.properties > Added values to support the options panel.
- wappalyzer.html > Updated to reflect the new UI etc.
- WappalyzerPassiveScanner > Now implements OptionsChangedListener.
- Related to: zaproxy/zaproxy#8361
- Follow-up to: zaproxy/zap-extensions#5571

tech detection: Move Mode to options panel

---

addOns/automation/src/test/java/org/zaproxy/addon/automation/tests/UrlPresenceTestUnitTest.java

Remove use of job implementations when testing `UrlPresenceTest`, use a mocked job that returns the necessary data for the test.
Also, deduplicate test setup.

automation: tidy up test

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionDetectionScanRule.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthUtilsUnitTest.java

Will hopefully fix an intermittant issue with the integration tests.

Authhelper: Fix session mgmt detection bug

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/JsFunctionScanRule.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/JsFunctionScanRuleUnitTest.java

Adjusted pattern handling to reduce False Positives.
Fixes zaproxy/zaproxy#8553

pscanrulesBeta: Adjust Dangerous JS Func handling for FP

---

addOns/webuipoc/src/main/pocs/reactWebUI/src/Components/Accordion/AccordionData.jsx

webuipoc: Convert absolute path in site tree to relative path

---

addOns/webuipoc/src/main/pocs/reactWebUI/src/Components/Accordion/AccordionData.jsx

WIP issue https://github.com/zaproxy/zaproxy/issues/8287

webuipoc: Display request method with leaf nodes

---

addOns/webuipoc/src/main/pocs/reactWebUI/src/Components/Accordion/AccordionData.jsx

WIP issue https://github.com/zaproxy/zaproxy/issues/8287

webuipoc: Site tree indentation

---

addOns/domxss/CHANGELOG.md
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
addOns/domxss/src/main/resources/org/zaproxy/zap/extension/domxss/resources/Messages.properties
addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java

Mention the steps that the scan rule did to reproduce the alert in the other info.

domxss: include steps in other info

---

.github/workflows/cla.yml

Use `dependabot[bot]` instead of `dependabot`.

Update `dependabot` username in CLA workflow

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ContextWrapper.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/ContextDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/ContextStructurePanel.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/environment.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/env-max.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/ContextWrapperUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml

Allow to configure the structural parameters of a context.
Part of zaproxy/zaproxy#7780.

automation: allow to configure structural params

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ApplicationHolder.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechApi.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechData.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechDetectParam.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechOptionsPanel.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechPassiveScanner.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechTableModel.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechsJsonParser.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/automation/ExtensionWappalyzerAutomation.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/automation/TechJob.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/automation/TechJobResultData.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/ApplicationTestHolder.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/AppsJsonParseUnitTest.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/JsonParserUnitTest.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/PassiveScannerUnitTest.java
addOns/wappalyzer/wappalyzer.gradle.kts

- Apply static modifier where applicable, and access things in a static manner.
- Drop 'wappalyzer' from class names where practical.
N/A

tech detection: Maintenance tweaks

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CrossDomainMisconfigurationScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CrossDomainScriptInclusionScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/HashDisclosureScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InfoPrivateAddressDisclosureScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/UsernameIdorScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/HashDisclosureScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InfoPrivateAddressDisclosureScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/UsernameIdorScanRuleUnitTest.java

As per title. Makes a significant difference for all of the changed rules after spidering Juice Shop.

Pscanrules: performance improvements

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java

Handle exceptions while running jobs.

automation: handle job exceptions

---

addOns/oast/CHANGELOG.md
addOns/oast/oast.gradle.kts
addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastApi.java
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/api.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/oast.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/index.xml
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/map.jhm
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/toc.xml
addOns/oast/src/main/resources/org/zaproxy/addon/oast/resources/Messages.properties
addOns/oast/src/test/java/org/zaproxy/addon/oast/ExtensionOastUnitTests.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/OastApiUnitTests.java

OAST API Support.
WIP pending more endpoints 😁 

OAST API Support

---

addOns/database/src/main/java/org/zaproxy/addon/database/Database.java
addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastApi.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/OastParam.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/internal/OastPermanentDatabase.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastOptionsPanelTab.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastService.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/ui/GeneralOastOptionsPanelTab.java
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/api.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/options.html
addOns/oast/src/main/resources/org/zaproxy/addon/oast/resources/Messages.properties
addOns/oast/src/test/java/org/zaproxy/addon/oast/OastApiUnitTests.java

The permanent db will just keep getting bigger - this PR allows users to limit the number of days records are kept, default 45.

OAST Trim database

---

addOns/callhome/CHANGELOG.md
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java
addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/BaseHttpSender.java

Add stats for send success / failure.

Network: Add connection stats

---

addOns/exim/CHANGELOG.md
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarImporter.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/har/HarImporterUnitTest.java
addOns/exim/src/test/resources/org/zaproxy/addon/exim/har/response-base64-invalid.har
addOns/exim/src/test/resources/org/zaproxy/addon/exim/har/response-base64.har

Base64 decode the response body if it was encoded that way.

exim: base64 decode the HAR response body

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/XpathInjectionScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/XsltInjectionScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/XpathInjectionScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/XsltInjectionScanRuleUnitTest.java

- Scan Rules > Added example alert handling.
- Unit Tests > Added tests for the example alerts and references.

ascanrules: More example alerts

---

.github/workflows/cla.yml

Suppress the recheck advice
- [na] Update changelog
- [na] Run `./gradlew spotlessApply` for code formatting

Update cla workflow to 2.6.1

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/scanrules/ScriptsPassiveScanner.java
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/scanrules/ScriptsPassiveScannerUnitTest.java

Use the same script cache in all passive scan threads.

scripts: reuse pscan cache

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/FuzzerPayloadGeneratorUIHandler.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/impl/FuzzLocationTableEntry.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/impl/Utils.java
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/payloads/generator/CompositePayloadGenerator.java
addOns/fuzz/src/test/java/org/zaproxy/zap/extension/fuzz/impl/UtilsUnitTest.java

Sum the number of payloads taking into account the possible overflows.

fuzz: address lossy conversion warns

---

addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestPage.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestProxyServer.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/seq/performance/PerformanceDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/seq/performance/SequencePage.java
addOns/dev/src/main/javahelp/org/zaproxy/addon/dev/resources/help/contents/dev.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/seq/performance/index.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/seq/performance/seq.html

A configurable set of sequence pages.
A set of test sequence pages designed to make it easy to test the performance of the sequence add-on/

Dev: Sequence performance test page

---

addOns/exim/CHANGELOG.md
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarUtils.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/har/HarImporterUnitTest.java

Use the expected object that's set into the HAR request.

exim: fix export of request body

---

addOns/exim/src/main/java/org/zaproxy/addon/exim/ImportExportApi.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarImporter.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarUtils.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/PopupMenuItemSaveHarMessage.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/har/HarUtilsUnitTest.java

Rely just on the add-on's dependencies (direct and transitive) for HAR handling.

exim: remove core HAR usage

---

addOns/domxss/CHANGELOG.md
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
addOns/domxss/src/main/javahelp/org/zaproxy/zap/extension/domxss/resources/help/contents/domxss.html
addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java

DOMXSS: Do not request URLs explicitly excluded from context

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/HtAccessScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/HtAccessScanRuleUnitTest.java

Fixes https://github.com/zaproxy/zaproxy/issues/7632
Added more checks for valid .htaccess files to reduce false positives
https://github.com/zaproxy/zaproxy/issues/7632

Ascanrules: Fix .htaccess FPs

---

addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java

Failed in
https://github.com/zaproxy/zap-extensions/actions/runs/11295313733/job/31417741270#step:7:1744
Just trying to make sure the tests pass consistently.

DOMXSS Tweak max low reqs

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/launch/ExtensionQuickStartLaunch.java
addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java

- Add stats counter to button actions.
- Add note to CHANGELOGs.
- zaproxy/zaproxy#8375

reports & quickstart: Add main toolbar button stats

---

addOns/exim/CHANGELOG.md
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarImporter.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/har/HarImporterUnitTest.java

Import the HAR entry sent and elapsed time when creating the HTTP messages.

exim: import HAR entry timings

---

addOns/encoder/CHANGELOG.md
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/EncodeDecodeProcessors.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/utility/Ascify.java
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/contents/encoder.html
addOns/encoder/src/main/resources/org/zaproxy/addon/encoder/resources/Messages.properties
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/utility/AscifyUnitTest.java

Follow-up to comments on https://github.com/zaproxy/zap-extensions/pull/5815

encoder: Rename Transliterate to ASCify and add dropping chars example

---

addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarImporter.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarUtils.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/har/HarUtilsUnitTest.java

Allow any code to convert an HAR entry to an HTTP message through the utils class.
Extract constant for the base64 encoding string.

exim: move HAR entry conversion to utils

---

addOns/sequence/sequence.gradle.kts
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/ExtensionSequence.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/ExtensionSequenceAutomation.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/SequenceImportJob.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/SequenceImportJobDialog.java
addOns/sequence/src/main/javahelp/org/zaproxy/zap/extension/sequence/resources/help/contents/automation.html
addOns/sequence/src/main/javahelp/org/zaproxy/zap/extension/sequence/resources/help/helpset.hs
addOns/sequence/src/main/javahelp/org/zaproxy/zap/extension/sequence/resources/help/index.xml
addOns/sequence/src/main/javahelp/org/zaproxy/zap/extension/sequence/resources/help/map.jhm
addOns/sequence/src/main/javahelp/org/zaproxy/zap/extension/sequence/resources/help/toc.xml
addOns/sequence/src/main/resources/org/zaproxy/zap/extension/sequence/resources/Messages.properties
addOns/sequence/src/main/resources/org/zaproxy/zap/extension/sequence/resources/sequence-import-max.yaml
addOns/sequence/src/main/resources/org/zaproxy/zap/extension/sequence/resources/sequence-import-min.yaml
addOns/sequence/src/test/java/org/zaproxy/zap/extension/sequence/ExtensionSequenceUnitTest.java
addOns/sequence/src/test/java/org/zaproxy/zap/extension/sequence/automation/ExtensionSequenceAutomationUnitTest.java
addOns/sequence/src/test/java/org/zaproxy/zap/extension/sequence/automation/SequenceImportJobUnitTest.java

Allow to create Sequence from HAR file.

sequence: add AF job to import HAR sequence

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/ActiveScanJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/ActiveScanPolicyDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/ActiveScanPolicyJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AddAscanRuleDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AscanRulesTableModel.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanPolicyJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PolicyDefinition.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/automation.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-ascan.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-ascanpolicy.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/index.xml
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/map.jhm
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/toc.xml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/activeScan-policy-max.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/activeScan-policy-min.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanJobPolicyUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/PolicyDefinitionUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-config.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml
addOns/retest/CHANGELOG.md
addOns/retest/retest.gradle.kts
addOns/retest/src/main/java/org/zaproxy/addon/retest/RetestPlanGenerator.java

Adds a new activeScan-policy job.

Automation: Add active scan policy job

---

addOns/network/CHANGELOG.md
addOns/network/network.gradle.kts
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java

Configure the logger to only log messages from BC JSSE provider from WARN level to exclude the not so useful INFO log messages.
e.g.:
```
2208468 [ZAP-IO-2-3] INFO  org.bouncycastle.jsse.provider.ProvTlsServer - [server #23 @10ac857e] disconnected from (unknown):(unknown)
2208660 [ZAP-IO-2-1] INFO  org.bouncycastle.jsse.provider.ProvTlsServer - [server #25 @1c1b3cd0] disconnected from (unknown):(unknown)
2208882 [ZAP-IO-2-2] INFO  org.bouncycastle.jsse.provider.ProvTlsServer - [server #27 @33bbbad2] disconnected from (unknown):(unknown)
2209331 [ZAP-IO-2-3] INFO  org.bouncycastle.jsse.provider.ProvTlsServer - [server #28 @78bf70f2] disconnected from (unknown):(unknown)
2209336 [ZAP-IO-2-3] INFO  org.bouncycastle.jsse.provider.ProvTlsServer - [server #32 @661f7cc5] disconnected from …
```

network: suppress BC JSSE's verbose INFO log

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlFingerprinter.java
addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/GraphQlFingerprinterUnitTest.java

- Fingerprinting checks for the following engines:
- pg_graphql
- tailcall
- Hot  Chocolate
N/A

graphql: Add more fingerprints

---

addOns/accessControl/CHANGELOG.md
addOns/accessControl/src/main/javahelp/org/zaproxy/zap/extension/accessControl/resources/help/contents/concepts.html
addOns/ascanrules/src/main/javahelp/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/contents/custompayloads.html
addOns/grpc/CHANGELOG.md
addOns/grpc/src/main/javahelp/org/zaproxy/addon/grpc/resources/help/contents/grpc.html
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/zest/src/main/javahelp/org/zaproxy/zap/extension/zest/resources/help/contents/zest.html

- various html > Updated spelling.
na
- [na] Run `./gradlew spotlessApply` for code formatting

various: Standardize add-on vs addon in help

---

addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/StdActiveScanRunner.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/SequenceActiveScanJob.java

Scan all sequences when the sequence name is not specified.

sequence: scan all sequences if none specified

---

addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/SequenceActiveScanJob.java
addOns/sequence/src/main/resources/org/zaproxy/zap/extension/sequence/resources/sequence-activeScan-max.yaml
addOns/sequence/src/main/resources/org/zaproxy/zap/extension/sequence/resources/sequence-activeScan-min.yaml
addOns/sequence/src/test/java/org/zaproxy/zap/extension/sequence/automation/SequenceActiveScanJobUnitTest.java

Add min/max plans for the active scan job.
---
This is already describing behaviour being added in #5871.

sequence: add plans for the active scan job

---

addOns/sequence/CHANGELOG.md

Mention the AF job added in #5842.

sequence: update changelog

---

addOns/sequence/CHANGELOG.md
addOns/sequence/src/main/zapHomeFiles/policies/Sequence.policy

Initial sequence policy addition
n/a

sequence: Initial sequence policy addition

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartPanel.java

Orphaned in
https://github.com/zaproxy/zap-extensions/commit/eb1f0c9f0be8db2f9d9bb0cc2b8c96333733b24c

quickstart: Remove unused element - prevent NPE on LaF switch

---

addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/SequenceActiveScanJob.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/SequenceActiveScanJobDialog.java
addOns/sequence/src/main/resources/org/zaproxy/zap/extension/sequence/resources/Messages.properties

Add dialogue to configure the job.

sequence: add dialogue for the activeScan job

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-ascan.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/activeScan-config-max.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/activeScan-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/spider/CHANGELOG.md
addOns/spider/src/main/java/org/zaproxy/addon/spider/automation/SpiderJob.java
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/contents/automation.html
addOns/spider/src/main/resources/org/zaproxy/addon/spider/automation/spider-max.yaml
addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/contents/automation.html
addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/spiderAjax-max.yaml
addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/spiderAjax-min.yaml

This PR:
https://github.com/zaproxy/zap-extensions/pull/4326/files
That was part of a effort to close this issue:
https://github.com/zaproxy/zaproxy/issues/7663
Resulted in the documentation being out of date.
This PR addresses that.
Thank you very much and I hope you have a nice day.
Original PR that was created: https://github.com/zaproxy/zaproxy-website/pull/2859

Update Automation Framework job specifications

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/javahelp/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html

- CHANGELOGs > Added change notes.
- Help HTML files > Added content.
- zaproxy/zap-extensions#5853

various: Include custom payload category identifiers in help

---

addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestDirectory.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestProxyServer.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/seq/performance/PerformanceDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/seq/performance/SequencePage.java

- PerformacneDir > Correct extended class.
- SequencePage > Add constants and extract methods to simplify code.
- TestDirectory > Changes to facilitate caching.
- TestProxyServer > Changes to facilitate caching.
n/a

dev: Maint & CSS/JS resource caching

---

addOns/exim/CHANGELOG.md
addOns/exim/exim.gradle.kts
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarUtils.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/har/HarUtilsUnitTest.java

Update har-header and use the new methods that allow to get the actual method and status code.

exim: update har-header

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/tests/AutomationAlertTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/tests/AutomationAlertTestUnitTest.java

Automation: Fix bug in job alert tests

---

addOns/sequence/CHANGELOG.md
addOns/sequence/sequence.gradle.kts

Sequence: promote to Beta

---

addOns/scanpolicies/scanpolicies.gradle.kts

Update link to match the expected form.

scanpolicies: correct link in manifest

---

addOns/sequence/CHANGELOG.md
addOns/sequence/sequence.gradle.kts
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/ExtensionSequence.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/internal/ImportHarMenuItem.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/internal/SequenceImportDialog.java
addOns/sequence/src/main/javahelp/org/zaproxy/zap/extension/sequence/resources/help/contents/sequence.html
addOns/sequence/src/main/resources/org/zaproxy/zap/extension/sequence/resources/Messages.properties

Add an import menu item to allow to import HAR as sequences through the GUI like it's possible through the Automation Framework.

sequence: allow to import HAR from the GUI

---

addOns/scanpolicies/src/main/javahelp/help/contents/policy-api.html
addOns/scanpolicies/src/main/javahelp/help/contents/policy-dev-cicd.html
addOns/scanpolicies/src/main/javahelp/help/contents/policy-dev-full.html
addOns/scanpolicies/src/main/javahelp/help/contents/policy-dev-std.html
addOns/scanpolicies/src/main/javahelp/help/contents/policy-qa-full.html
addOns/scanpolicies/src/main/javahelp/help/contents/policy-qa-std.html
addOns/sequence/src/main/javahelp/org/zaproxy/zap/extension/sequence/resources/help/contents/policy-sequence.html

ScanPolicies: link to the relevant tag pages

---

addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java

Remove mock of `ExtensionPassiveScan` that's no longer needed.

automation: remove mock no longer needed

---

.github/workflows/generate_policies.yml

Tested here: https://github.com/kingthorin/zap-extensions-2/actions/runs/12122562750/job/33796025846
Result: https://github.com/kingthorin/zap-extensions/pull/3/files
Diff: https://www.diffchecker.com/QM6FKVPZ/ (Yes it does show other changes but they're just repo/path changes, the fetch seems to be the only relevant change)
Submitted via github.dev

Generate Scan Policies from Policy Tags Workflow adjustment (2)

---

addOns/webdrivers/webdriverlinux/gradle.properties
addOns/webdrivers/webdrivermacos/gradle.properties
addOns/webdrivers/webdriverwindows/gradle.properties

Change the release state to start the release.

Restart release of WebDriver add-ons

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlFingerprinter.java
addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/contents/alerts.html
addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/GraphQlFingerprinterUnitTest.java

- CHANGELOG > Updated note.
- GraphQlFingerprinter > Add new engine handling.
- GraphQlFingerprinterUnitTest > Add coverage for inigo.
- Messages.properties > Add supporting key/value pairs.
- alerts.html > Add supported engine list.
NA

graphql: Add inigo engine fingerprint

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/ClientOptions.java
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/MissingUrlsThread.java
addOns/client/src/main/java/org/zaproxy/addon/client/internal/ClientSideComponent.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/ClientPassiveScanController.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/ClientPassiveScanHelper.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/InformationInStorageScanRule.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/JwtInStorageScanRule.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/OptionsPassiveScan.java
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/SensitiveInfoInStorageScanRule.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpiderDialog.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/PopupMenuSpider.java
addOns/client/src/main/java/org/zaproxy/addon/client/ui/ClientHistoryPanel.java
addOns/client/src/main/java/org/zaproxy/addon/client/ui/ClientMapPanel.java
addOns/client/src/main/java/org/zaproxy/addon/client/ui/ClientMapTreeCellRenderer.java
addOns/client/src/main/java/org/zaproxy/addon/client/ui/ClientNodeDetailsPanel.java
addOns/client/src/main/java/org/zaproxy/addon/client/ui/PopupMenuClientOpenInBrowser.java
addOns/client/src/main/java/org/zaproxy/addon/client/ui/PopupMenuItemClient.java
addOns/client/src/main/java/org/zaproxy/addon/client/ui/PopupMenuItemClientDetails.java
addOns/client/src/main/java/org/zaproxy/addon/client/ui/PopupMenuItemClientHistory.java
addOns/client/src/main/java/org/zaproxy/addon/client/ui/PopupMenuItemClientOpenInBrowser.java
addOns/client/src/test/java/org/zaproxy/addon/client/pscan/InformationInStorageScanRuleUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/pscan/JwtInStorageScanRuleUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/pscan/SensitiveInfoInStorageScanRuleUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/spider/ClientSpiderUnitTest.java

- ExtensionClientIntegration > Use lambdas vs inner classes where possible. Use constants from InputEvent vs. KeyEvent.
- MissingUrlsthread > Make method static where practical.
- OptionsPassiveScan > Remove useless semi-colon. Simplify stream toList handling.
- PopupMenuClientOpenInBrowser > Use lambdas vs inner classes where possible.
- PopupMenuItemClient > Use method reference vs lambda.
- PopupMenuItemClientDetails > Use method reference vs lambda.
- PopupMenuItemClientHistory > Use method reference vs lambda.
- PopupMenuItemClientOpenInBrowser > Remove unnecessary curly braces.
- PopupMenuSpider > Return statement directly vs using if where practical. Streamline switch cases with comma notation.
- SensitiveInfoInStorageScanRule > Adjust enum values to …

client: SAST (SonarLint) Fixes and update CWEs

---

addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/internal/ClientMap.java
addOns/client/src/main/java/org/zaproxy/addon/client/internal/ClientSideComponent.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpiderTask.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/SpiderAction.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/SpiderScanController.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/UrlTableModel.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/actions/BaseElementAction.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/actions/ClickElement.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/actions/OpenUrl.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/actions/SubmitForm.java
addOns/client/src/test/java/org/zaproxy/addon/client/ExtensionClientIntegrationUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/spider/UrlTableModelUnitTest.java

Fill input elements.
Click reported elements.
Submit reported forms.

client: add element interactions to the spider

---

addOns/addOns.gradle.kts
addOns/commonlib/CHANGELOG.md
addOns/domxss/CHANGELOG.md
addOns/network/CHANGELOG.md
addOns/retire/CHANGELOG.md
addOns/selenium/CHANGELOG.md
testutils/src/main/java/org/zaproxy/zap/testutils/PassiveScannerTestUtils.java
testutils/testutils.gradle.kts

Change the add-ons that were already released for 2.15:
- `commonlib`
- `domxss`
- `network`
- `retire`
- `selenium`

Update add-ons to 2.16 and Java 17

---

addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java

Use the constant that is now available in the latest published core snapshot.

client: address todo

---

addOns/client/client.gradle.kts
addOns/client/src/main/java/org/zaproxy/addon/client/ClientOptions.java
addOns/client/src/main/java/org/zaproxy/addon/client/automation/ClientSpiderJob.java
addOns/client/src/main/java/org/zaproxy/addon/client/automation/ClientSpiderJobDialog.java
addOns/client/src/main/java/org/zaproxy/addon/client/automation/ExtensionClientAutomation.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/Messages.properties
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/spiderClient-max.yaml
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/spiderClient-min.yaml
addOns/client/src/test/java/org/zaproxy/addon/client/automation/ClientSpiderJobUnitTest.java

Initial AF support. Help to be added when we make this more generally available.

Client: Automation Framework spider support

---

addOns/exim/src/main/java/org/zaproxy/addon/exim/sites/SitesTreeHandler.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/sites/SiteTreeHandlerUnitTest.java

We get an NPE when exporting a scan of Crawl Maze :)

Exim: Site export fix

---

addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpiderTask.java

Ensure that no non-daemon threads are kept running after the spider finishes, which would lead to thread leaks and in command line mode could prevent ZAP from terminate gracefully.
Ensure that the WebDriver is returned and the task completed even in case of exceptions, otherwise that would prevent the spider from finishing.

client: shutdown spider thread pool

---

addOns/client/src/main/java/org/zaproxy/addon/client/automation/ClientSpiderJobDialog.java

Min should be zero, which means unlimited.

Client: Fix duration GUI

---

addOns/client/src/main/java/org/zaproxy/addon/client/automation/ClientSpiderJob.java
addOns/client/src/main/java/org/zaproxy/addon/client/automation/ClientSpiderJobDialog.java
addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/contents/automation.html
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/spiderClient-max.yaml
addOns/client/src/test/java/org/zaproxy/addon/client/automation/ClientSpiderJobUnitTest.java
addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParam.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJob.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJobDialog.java
addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/contents/automation.html
addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/contents/options.html
addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/spiderAjax-max.yaml
addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/spiderAjax-min.yaml
addOns/spiderAjax/src/test/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParamUnitTest.java

AJAX/Client Spider: change default # browsers

---

addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/contents/ajax-scan.html
addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/contents/client.html
addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/contents/spider.html

Client: Spider help tweaks

---

addOns/custompayloads/CHANGELOG.md
addOns/custompayloads/custompayloads.gradle.kts

custompayloads: Promote to release status

---

addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpiderTask.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/actions/ClickElement.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/actions/OpenUrl.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/actions/SubmitForm.java

Add more stats and correct the prefix for the existing ones.

client: add more stats to the spider

---

addOns/pscan/CHANGELOG.md
addOns/pscan/src/main/javahelp/org/zaproxy/addon/pscan/help/contents/pscan.html

pscan: fix broken help link

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/tests/AutomationStatisticTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/tests/AutomationStatisticTestUnitTest.java

Ensure the value zero is saved to the plan as it has meaning.

automation: fix stats test's value persistence

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/InsecureHttpMethodScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/InsecureHttpMethodScanRuleUnitTest.java

- Add change note.
- Tweak CWE value in rule.
- Assert value in unit test.
- Fixes zaproxy/zaproxy#8714

ascanrulesBeta: Replace usage of CWE-200

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/ClientSideHandler.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/ZestAuthRunner.java

A set of fixes for a particularly nasty set of problems.

authhelper: misc fixes for cookies and window closing

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AuthenticationData.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/ContextWrapper.java

Read/write the TOTP data from/to the user credentials instead of directly in the step.

automation: persist TOTP data under user's creds

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AuthenticationData.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/ContextWrapper.java

Allow to use vars for the TOTP fields.

automation: support vars in TOTP data

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/sarif/SarifLevel.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/sarif/SarifResult.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/sarif/SarifRule.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/sarif/SarifLevelUnitTest.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/sarif/SarifResultUnitTest.java

reports: dont include FPs in Sarif reports

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionDetectionScanRule.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/ClientSideHandler.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/report/ExtensionAuthhelperReport.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodTypeUnitTest.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/report/ExtensionAuthhelperReportUnitTest.java

authhelper: Session handling to cope with X-CSRF-Token headers

---

addOns/retire/CHANGELOG.md
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/model/Repo.java
addOns/retire/src/main/resources/org/zaproxy/addon/retire/resources/Messages.properties
addOns/retire/src/test/java/org/zaproxy/addon/retire/RetireScanRuleUnitTest.java

- CHANGELOG.md > Add change note.
- Messages.properties > Adjust description, soln, refs, and other info KVPs.
- Repo.java > Update for Hash match Other Info handling.
- RetireScanRule > Update Other Info, Solution, and Refs handling.
- RetireScanRuleUnitTest > Update tests/assertions to cover the changes.
N/A

retire: Alert's desc, soln, & refs generic, provide details in other info

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/browser-auth.html
addOns/automation/CHANGELOG.md
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/environment.html

Document the custom steps for BBA and the user's TOTP.

Add docs for BBA custom steps and user's TOTP

---

addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/internal/FirefoxProfileManager.java

Add the headless flag to ensure that it works in all systems.

selenium: create profiles with Firefox headless

---

.github/workflows/create_webdriver_update.yml

Automate webdriver add-on updates further.

webdrivers: Include prepareRelease in update workflow

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/auth-report-json.html
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/auth-tester.html
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/browser-auth.html
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/client-script.html

Document how to enable the diagnostics and what data can be included in the authentication report.

authhelper: document auth report diags

---

addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ExtensionAuthhelper.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/ClientSideHandler.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/internal/ClientSideHandlerUnitTest.java

Auth bug fixes - should fix auth integration tests.

Authhelper: auth fixes

---

addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodType.java

Change BBA to use core credentials panel now that it's possible.

authhelper: use core credentials panel in BBA

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/JobUtils.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/JobUtilsUnitTest.java

Check that the script has a file before checking it.

automation: fix exception with unsaved scripts

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/authhelper.gradle.kts
addOns/automation/CHANGELOG.md
addOns/automation/automation.gradle.kts
addOns/zest/CHANGELOG.md
addOns/zest/zest.gradle.kts

Update minimum version of Common Library add-on in add-ons that are using its new features.

Update minimum add-on versions

---

addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestProxyServer.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/csrf/basic/BasicCsrfDir.java
addOns/dev/src/main/javahelp/org/zaproxy/addon/dev/resources/help/contents/dev.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/csrf/basic/bad-method.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/csrf/basic/bad-token.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/csrf/basic/page.html

DEV: Add basic CSRF test app

---

addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java

scripts: Register outputs for existing scripts upon installation

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRuleUnitTest.java

Add some Postgres error messages. They happen to be used by Broken Crystals 😁 
Worth adding any more, e.g. from https://pganalyze.com/docs/log-insights/app-errors ?

ascanrules: Add some postgres error messages

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ExtensionAscanRulesBeta.java
addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/resources/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties

- CHANGELOGs > Added note.
- Extension Class > Added UI name method.
- Messages file > Dropped period.

Fix GUI names for Beta scan rule extensions

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/FetchMetadataRequestHeadersScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/FullPathDisclosureScanRule.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64DisclosureUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/FetchMetadataRequestHeadersScanRuleTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/FullPathDisclosureScanRuleUnitTest.java

- CHANGELOGs > Added notes.
- Rules > Added/Updated Alert Tags.
- UnitTests > Added/updated tests asserting the tag set.
- Build files > Updated commonlib dependency version.
Requires zaproxy/zap-extensions#6325 ... :warning: for the time being the build will fail.

Add "policy" related tags to alpha passive scan rules

---

addOns/pscan/CHANGELOG.md
addOns/pscan/pscan.gradle.kts

Add the dependency and adjust changelog entry.
---
Caught by Check For ZAP Errors:
https://github.com/zaproxy/zaproxy/actions/runs/14256726441/job/39967499589#step:5:277

pscan: depend on `commonlib`

---

addOns/imagelocationscanner/CHANGELOG.md
addOns/imagelocationscanner/imagelocationscanner.gradle.kts
addOns/imagelocationscanner/src/main/java/org/zaproxy/zap/extension/imagelocationscanner/ImageLocationScanRule.java
addOns/imagelocationscanner/src/test/java/org/zaproxy/zap/extension/imagelocationscanner/ImageLocationScanRuleUnitTest.java
addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/pscanrulesBeta.gradle.kts
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/CacheableScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/InPageBannerInfoLeakScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/JsFunctionScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/JsoScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/PermissionsPolicyScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ServletParameterPollutionScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/SiteIsolationScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/SourceCodeDisclosureScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/SubResourceIntegrityAttributeScanRule.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/CacheableScanRuleUnitTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/InPageBannerInfoLeakScanRuleUnitTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/JsFunctionScanRuleUnitTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/JsoScanRuleUnitTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/PermissionsPolicyScanRuleUnitTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/ServletParameterPollutionScanRuleUnitTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/SiteIsolationScanRuleTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/SourceCodeDisclosureScanRuleUnitTest.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/SubResourceIntegrityAttributeScanRuleUnitTest.java
addOns/soap/CHANGELOG.md
addOns/soap/soap.gradle.kts
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/WSDLFilePassiveScanRule.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/WSDLFilePassiveScanRuleTestCase.java

- CHANGELOGs > Added notes.
- Rules > Added/Updated Alert Tags.
- UnitTests > Added/updated tests asserting the tag set.
- Build files > Updated commonlib dependency version.
Requires zaproxy/zap-extensions#6325 ... :warning: for the time being the build will fail.

Add "policy" related tags to beta passive scan rules

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/CommandPanel.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java

Closes https://github.com/zaproxy/zaproxy/issues/8922.

scripts: Show templates and zest scripts in console

---

addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestProxyServer.java
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/elements/index.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/html/elements/time-place.html

As per title. This page is useful for testing Zest client scripts.

dev: page with delayed elements off screen

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java

Use a proxy per browser to isolate their interactions.

spiderAjax: isolate browser interactions

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/client-script.html
addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AuthenticationData.java

Allow to configure the wait time after the script has run for the Client Script Based Authentication.

Support wait time in CSA

---

addOns/alertFilters/CHANGELOG.md
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java

Use the alert reference to know with more detail which alerts are filtered.

alertFilters: use alert ref for stats

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthenticationDiagnostics.java

Include the WebElement being interacted with in the diagnostics steps as it gives more insight into what's happening.

authhelper: include web element in CSA diag steps

---

addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechTableModel.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechsJsonParser.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/AppsJsonParseUnitTest.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/TechPassiveScannerUnitTest.java

- Remove unneccessary intermediate assignment.
- Use ArrayList vs Vector (column names).
- Use instanceof assignment.
- Use text blocks.
- Remove declaration of thrown exception where it isn't thrown.

tech detect: SAST Fixes (SonarQube)

---

addOns/scanpolicies/CHANGELOG.md
addOns/scanpolicies/src/main/javahelp/help/contents/policy-pentest.html
addOns/scanpolicies/src/main/javahelp/help/contents/scanpolicies.html
addOns/scanpolicies/src/main/javahelp/help/map.jhm
addOns/scanpolicies/src/main/javahelp/help/toc.xml

- CHANGELOG > Add change ntoe.
- Help content and index files > Added new content/references.
> [!NOTE]
> The actual policy will be generated/updated by our GitHub workflow after the three PRs have been merged.
- zaproxy/zap-extensions#6325
- zaproxy/zap-extensions#6331
- zaproxy/zap-extensions#6332
- zaproxy/zap-extensions#6356
- zaproxy/zap-extensions#6357
- zaproxy/zap-extensions#6362

scanpolicies: Add help content for PENTEST Policy Tag

---

addOns/soap/CHANGELOG.md
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanRule.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPXMLInjectionActiveScanRule.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanRuleTestCase.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/SOAPXMLInjectionActiveScanRuleTestCase.java
addOns/sqliplugin/CHANGELOG.md
addOns/sqliplugin/sqliplugin.gradle.kts
addOns/sqliplugin/src/main/java/org/zaproxy/zap/extension/sqliplugin/SQLInjectionScanRule.java

- Updated: Changelogs, rules, rule unit tests, and build files (where necessary).
- zaproxy/zap-extensions#6325
- zaproxy/zap-extensions#6331
- zaproxy/zap-extensions#6332
- zaproxy/zap-extensions#6356
- zaproxy/zap-extensions#6357
- zaproxy/zap-extensions#6362

soap & sqliplugin: Added PENTEST Policy Tag

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/authhelper.gradle.kts
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthenticationDiagnostics.java
addOns/zest/CHANGELOG.md
addOns/zest/README.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestStatementFromJson.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestClientElementDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestDialogManager.java
addOns/zest/src/main/resources/org/zaproxy/zap/extension/zest/resources/Messages.properties
addOns/zest/zest.gradle.kts

Note that this will fail to build until https://github.com/zaproxy/zest/pull/310 is merged, a new Zest release has been created and this PR updated to use it!
As per title
https://github.com/zaproxy/zest/pull/310

zest: Add client element waitFor param

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUIUnitTest.java

Scripts: Fix Loop when extracting script exception

---

addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUIUnitTest.java

As per https://github.com/zaproxy/zap-extensions/pull/6391#pullrequestreview-2800009971
https://github.com/zaproxy/zap-extensions/pull/6391

script: minor test fix

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java
addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AuthenticationData.java

Zero is also a valid value if no wait is required.
Extract a method to have the same behaviour for CSA/BBA.

Allow to use zero login page wait in CSA/BBA

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ViewstateScanRule.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ViewStateScanRuleUnitTest.java

- Messages.properties > Clean-up related resource messages.
- ViewstateScanRule > Ensured example alerts have example data.
- ViewstateScanRule > Add/update unit tests.
- zaproxy/zaproxy#8940

pscanrules: Clarify viewstate alert details

---

addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Debug Error Disclosure.js
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Email Disclosure.js

- Rules > Update CWE usage/assignments.
- zaproxy/zaproxy#8712

websockets: Stop using cwe-200

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/ClientOptions.java
addOns/client/src/main/java/org/zaproxy/addon/client/automation/ClientSpiderJob.java
addOns/client/src/main/java/org/zaproxy/addon/client/automation/ClientSpiderJobDialog.java
addOns/client/src/main/java/org/zaproxy/addon/client/internal/ScopeCheckComponent.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpiderDialog.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/MessagesTable.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/MessagesTableModel.java
addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/contents/automation.html
addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/contents/spider.html
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/Messages.properties
addOns/client/src/test/java/org/zaproxy/addon/client/ClientParamUnitTest.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParam.java

As per title.
Also added the Scope Check as per the AJAX Spider.

client: Client Spider to allow all requests while authenticating

---

addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderResultsTable.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderResultsTableModel.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderListener.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java
addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/Messages.properties

Show flexible accesses as third party.

spiderAjax: show flexible accesses

---

addOns/zest/CHANGELOG.md
addOns/zest/zest.gradle.kts

Update Zest library to 0.27.0.

zest: update Zest library

---

addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestProxyServer.java
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json-blocking-ui/home.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json-blocking-ui/index.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/tutorial.css

Adds an Auth Test scenario where a banner div blocks the auth UI depending on the viewport size.
Edit: this recording is now out dated. The banner is actually at the top now.
https://github.com/user-attachments/assets/eea182aa-fd68-448a-9f8b-e24ad8f082ea
n/a
<details>
<summary>Test Plan</summary>
```yaml
env:
contexts:
- name: CSA_Test
urls:
- http://localhost:9091/auth/simple-json-blocking-ui/
includePaths:
- http://localhost:9091/auth/simple-json-blocking-ui/.*
authentication:
method: client
parameters:
script: C:\Users\user\Downloads\test.zst
scriptEngine: Mozilla Zest
verification:
method: autodetect
sessionManagement:
method: autodetect
technology: {}
structure: {}
users:
- name: test
credentials:
username: test@test.com
password: password123
parameters: {}
jobs:
- type: …
```

dev: Add auth example with potential blocking div

---

addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/internal/ScriptReorderer.java

This could result in ZAP stopping to record cleint Zest scripts as the sorted list got out of step.
No changelog as the add-on has not been released since the recording was last changed.

zest: fix script recording issue

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/AuthenticationStep.java
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/browser-auth.html
addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestProxyServer.java
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json-existing-values/home.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json-existing-values/index.html

If there are existing values then BBA will apend to them, which is not what we want.
This has been seen on a real site :)

authhelper: Clear existing values before submitting creds

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ExternalRedirectScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/ExternalRedirectScanRuleUnitTest.java

- CHANGELOG > Added change/fix notes.
- ExternalRedirectScanRule > Added and re-prioritized payloads.
- ExternalRedirectScanRuleUnitTest > Added tests and updated handling.
n/a

ascanrules: External Redirect fix FN when simple allow list in place

---

addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java

The browser should be kept open for the refresh of the page when the poll URL was not yet found, it's also being closed "manually" after the whole authentication process.

authhelper: remove close statements in CSA

---

addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/CorsScanRuleUnitTest.java

I needed to sanity check that the rule _was_ setting the evidence...

ascanrulesBeta: Add evidence tests for CORS rule

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthUtilsUnitTest.java

Use/extract the token from the JSON string response.

authhelper: use JSON string token from response

---

addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestProxyServer.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/sso2/SSO2RootDir.java
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/sso2/app-test.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/sso2/app.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/sso2/error.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/sso2/index.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/sso2/login.html

Note that the idea here is to use this to detect the session token when its used, _not_ to de-obfuscate it when it is set :)

dev: Add "sso" app with obfuscated session token

---

.github/pull_request_template.md

Remove the PR template checklist, as discussed/agreed via slack.
n/a

PR Template: Remove Checklist

---

addOns/postman/CHANGELOG.md
addOns/postman/src/main/java/org/zaproxy/addon/postman/PostmanApi.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/Requestor.java
addOns/postman/src/main/javahelp/org/zaproxy/addon/postman/resources/help/contents/postman.html
addOns/postman/src/main/resources/org/zaproxy/addon/postman/resources/Messages.properties
addOns/postman/src/test/java/org/zaproxy/addon/postman/PostmanApiUnitTest.java

Implement functionality to facilitate the API components.
https://github.com/zaproxy/zap-api-python/pull/126#pullrequestreview-2559245762

postman: Make API components functional

---

addOns/domxss/CHANGELOG.md
addOns/domxss/domxss.gradle.kts
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
addOns/domxss/src/main/javahelp/org/zaproxy/zap/extension/domxss/resources/help/contents/domxss.html

Allow to use Edge browser as well.

domxss: allow to use Edge

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthHeaderTracker.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ExtensionAuthhelper.java

Automatically track authorization headers.
Still need to add tests and docs 😁

authhelper: auto track authorization headers

---

addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthHeaderTracker.java
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/session-header.html
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthHeaderTrackerUnitTest.java

Unit tests and help for https://github.com/zaproxy/zap-extensions/pull/6583

authhelper: tests and help for auth tracking change

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ContextWrapper.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/environment.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/env-max.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/ContextWrapperUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml

Add support for DDNS in the AF yaml. No UI support though :/
Part of https://github.com/zaproxy/zaproxy/issues/7780

automation: Support DDNs in the yaml

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/VerificationDetectionProcessor.java
addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/VerificationData.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/VerificationDataUnitTest.java

Send the referer header on verification if set on the original request.

authhelper: set referer on verification

---

addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionSqLiteTimingScanRuleUnitTest.java

Make SqlInjectionSqLiteTimingScanRuleUnitTest more lenient in `getRecommendMaxNumberMessagesPerParam`

ascanrules: SqlInjectionSqLiteTimingScanRuleUnitTest - Add slack to tests

---

addOns/pscan/CHANGELOG.md
addOns/pscan/src/main/java/org/zaproxy/addon/pscan/internal/scanner/PassiveScanTask.java

They were deprecated in 2.11.0 :grin:

pscan: Remove the name based stats

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/authhelper.gradle.kts
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/VerificationDetectionScanRule.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/VerificationRequestDetails.java
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/browser-auth.html
addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/NetworkUtils.java
addOns/network/src/test/java/org/zaproxy/addon/network/NetworkUtilsUnitTest.java

Enhances Browser Based Authentication to support HTTP Authentication.
Firefox only for now due to Selenium restrictions.

authhelper: BBA to support HTTP auth

---

addOns/llm/src/main/java/org/zaproxy/addon/llm/ExtensionLlm.java
addOns/llm/src/main/java/org/zaproxy/addon/llm/services/LlmCommunicationService.java
addOns/llm/src/main/java/org/zaproxy/addon/llm/ui/LlmOpenApiImportDialog.java
addOns/llm/src/main/java/org/zaproxy/addon/llm/utils/Requestor.java

Rename some methods/variables to be more clear as to their use. Fix a few minor SAST (SonarLint) findings.
In preparation for zaproxy/zaproxy#8990

llm: Minor Refactoring

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechsJsonParser.java

- During load the time taken to process the data files will be shown in human readable format (generally seconds), as well as milliseconds (ms).
- Maintenance changes.

tech detection: Make load time human readable & maint

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ExternalRedirectScanRule.java

* CHANGELOG - Already has maint note.
- Remove low value comments.
- Move Patterns to constants to prevent re-compilation.
- Re-order some constants to be more clear/logical.

ascanrules: Ext Redirect rule maint

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/javahelp/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/oast.html

Updates help content for various rules which leverage OAST.
- Fixes zaproxy/zaproxy#8682

ascanrules & ascanrulesBeta: Add notes about behavior of OAST alerts

---

addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/ui/diags/AllDiagnosticsPanel.java

Do not require to manually change the browser launch to non-headless in the CSA script after importing the auth diags.

authhelper: import CSA script as non-headless

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AuthenticationData.java

Set the diagnostics state to the plan when creating from context.

automation: use context auth method diags

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthenticationDiagnostics.java

Get the current value of the attributes not the value that the element might had initially.

authhelper: fix element's attributes collection

---

addOns/pscan/CHANGELOG.md
addOns/pscan/src/main/javahelp/org/zaproxy/addon/pscan/help/contents/job-pscanconf.html
addOns/pscan/src/main/javahelp/org/zaproxy/addon/pscan/help/contents/job-pscanwait.html
addOns/pscan/src/main/resources/org/zaproxy/addon/pscan/automation/jobs/passiveScan-config-max.yaml
addOns/pscan/src/main/resources/org/zaproxy/addon/pscan/automation/jobs/passiveScan-config-min.yaml
addOns/pscan/src/main/resources/org/zaproxy/addon/pscan/automation/jobs/passiveScan-wait-max.yaml
addOns/pscan/src/main/resources/org/zaproxy/addon/pscan/automation/jobs/passiveScan-wait-min.yaml

Updated Automation Framework example yaml files and help content for passiveScan-config jobs to be more consistent.

pscan: AF templates and help consistency

---

.github/dependabot.yml

Ignore network add-on dependencies.

Configure dependabot to update gradle dependencies

---

addOns/invoke/src/main/javahelp/org/zaproxy/zap/extension/invoke/resources/help/helpset.hs

Changed the help set title from 'Run Applications' to 'Invoke Applications' in the `helpset.hs` file to reflect the extension name.

invoke: Update HelpSet title to 'Invoke Applications'
