addOns/spider/spider.gradle.kts
addOns/spider/src/main/java/org/zaproxy/addon/spider/automation/SpiderJob.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/automation/SpiderJobUnitTest.java

Rely on network exception to know if it's the proxy's host that was not resolved.

spider: use network exception

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpSenderHandler.java
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties

Add a (simple text) custom 'bad host' error page instead of showing the stack trace

Network: Custom Bad Host page

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpSenderHandler.java
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpSenderHandlerUnitTest.java

Use the exception timeout value in `HttpSenderHandler` instead of getting it from the options, remove the options which are no longer needed in the class.

network: use exception for timeout value

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/NetworkApi.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ChannelAttributes.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/cert/CertData.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/cert/CertificateUtils.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/cert/GenerationException.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/cert/ServerCertificateGenerator.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/cert/ServerCertificateService.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/cert/SniX509KeyManager.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/ServerExceptionHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/HttpServer.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/LocalServer.java
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/NetworkApiUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/cert/CertificateUtilsUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/cert/ServerCertificateGeneratorUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/cert/SniX509KeyManagerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/ServerExceptionHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/HttpServerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/testutils/TestHttpServer.java
addOns/network/src/test/java/org/zaproxy/addon/network/testutils/TestServerCertificateService.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/callback/CallbackServiceUnitTest.java

Remove core server cert checks that provided compatibility with older core versions, the add-on is now targeting newer versions and should handle server certs always.

network: handle server certs always

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/NetworkApi.java
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/NetworkApiUnitTest.java

Remove core client cert checks that provided compatibility with older core versions, the add-on is now targeting newer versions and should handle client certs always.

network: handle client certs always

---

addOns/network/src/main/java/org/zaproxy/addon/network/ConnectionOptions.java
addOns/network/src/main/java/org/zaproxy/addon/network/ConnectionOptionsPanel.java
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/NetworkApi.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/HttpServer.java
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/NetworkApiUnitTest.java

Remove core client connection options checks that provided compatibility with older core versions.

network: handle client connection options always

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/HashDisclosureScanRule.java

- CHANGELOG > Add maintenance note.
- HashDisclosureScanRule > Remove upper case alpha character class in regex since it's case insensitive.
Issue identified by CodeQL
Ex: https://github.com/zaproxy/zap-extensions/pull/4118/commits/28c559b607c8700f1bf7fc77fcf8154b1c876745

pscanrules: HashDisclosure correct character class in regex

---

addOns/bugtracker/CHANGELOG.md
addOns/bugtracker/bugtracker.gradle.kts
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerBugzillaTableModel.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerGithubTableModel.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/DialogAddBugzillaConfig.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/DialogAddGithubConfig.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/PopupMenuItemAlert.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/PopupSemiAutoIssue.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/RaiseSemiAutoIssueDialog.java

Address remaining warnings and remove compiler flags that were suppressing them.

bugtracker: address warnings

---

addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java

Allow 3 more requests to prevent intermittent failures.
---
e.g. https://github.com/zaproxy/zap-extensions/actions/runs/3339561777/jobs/5528661644#step:7:485
It also caused the weekly to fail earlier https://github.com/zaproxy/zaproxy/actions/runs/3338047891/jobs/5525190759#step:4:67

domxss: increase again allowed requests in tests

---

addOns/exim/CHANGELOG.md
addOns/exim/exim.gradle.kts
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/Messages.properties

Correct the case of API endpoints' messages keys.
Add a missing API endpoint description.
Add API configuration for client generation.

exim: correct messages keys and add API config

---

addOns/encoder/CHANGELOG.md
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/script/EncodeDecodeScript.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/script/ScriptBasedEncodeDecodeProcessor.java
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/contents/encoder.html
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/script/EncodeDecodeScriptUnitTest.java

- EncodeDecodeScript > Update handling: If the script returns an EncodeDecodeResult then just use it, if String then use it to instantiate a new EncodeDecodeResult.
- ScriptBasedEncodeDecodeProcessor > Return Object generically in the process method.

encoder: Simplify script use

---

addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverter.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v2/OpenApiUnitTest.java

Update `io.swagger.parser.v3:swagger-parser` to version 2.1.7.

openapi: Use latest version of parsing library

---

addOns/encoder/CHANGELOG.md
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/EncodeDecodeDialog.java
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/contents/encoder.html
addOns/encoder/src/main/resources/org/zaproxy/addon/encoder/resources/Messages.properties

- EncodeDecodeDialog.java > Add necessary getters and use/display of buttons.
- Messages.properties > Add support key/value pair.
<details>
<summary>Original screenshot</summary>
</details>

encoder: Add help and options buttons to main dialog

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ExtensionReports.java
addOns/reports/src/main/zapHomeFiles/reports/traditional-json-plus/report.json
addOns/reports/src/main/zapHomeFiles/reports/traditional-json/report.json
addOns/reports/src/main/zapHomeFiles/reports/traditional-xml-plus/report.xml
addOns/reports/src/main/zapHomeFiles/reports/traditional-xml/report.xml
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-json-plus.json
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-json.json
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-xml-plus.xml
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-xml.xml

- ExtensionReports > Set a variable to be available for report metadata "programName".
- json and xml templates > Include the new metadata element.
- UnitTest samples > Updated with the new metadata element.
Fixes zaproxy/zaproxy#6640

reports: XML & JSON Include Program Name metadata

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/apache/hc/client5/http/impl/classic/CustomHttpClientCreator.java
addOns/network/src/main/java/org/apache/hc/client5/http/impl/classic/ZapProtocolExec.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Use custom `ProtocolExec` that copies the request without validating if the TRACE has a payload.
Fix zaproxy/zaproxy#7578.

network: allow to send TRACE with body and proxy

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/ProxyCredentialsProvider.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Retry the proxy authentication using the credentials available if it failed with the header already present.
Part of zaproxy/zaproxy#7566.

network: correct HTTP/NTLM proxy reauthentication

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/ProxyRoutePlanner.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/apachev5/ProxyRoutePlannerUnitTest.java

Use always a plain connection to the outgoing proxy.
Fix zaproxy/zaproxy#7594.

network: use plain connection to outgoing proxy

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/RemoteCodeExecutionCve20121823ScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureCve20121823ScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureWebInfScanRule.java
addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/WebCacheDeceptionScanRule.java
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosureScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/CrossDomainScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ForbiddenBypassScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/MessageCache.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/RelativePathConfusionScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureSvnScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/UsernameEnumerationScanRule.java

Use the HTTP version of the message being scanned when creating new HTTP messages to keep scanning with same version.

Preserve HTTP version in active scan rules

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/ChannelAttributes.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandlerUnitTest.java

Change `TlsProtocolHandler` to call a pipeline configurator after the protocol negotiation.

network: allow pipeline configuration after alpn

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Set the header with the original case when updating the request sent.

network: do not change the case of Content-Length

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Use the available response content instead of throwing an exception when the Content-Length is more than what's available.
---
Reported in https://twitter.com/jonnwu/status/1591980559471112192

network: use available response content

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpSenderHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/HttpSenderHandlerUnitTest.java

Set the status line into the response header so the response is marked as non-empty and thus persisted to the session.

network: properly persist proxy error responses

---

addOns/encoder/CHANGELOG.md
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/Base64Decoder.java
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/contents/encoder.html
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/Base64DecoderUnitTest.java

- Bse64Decoder > Use mime decoder.
- Base64DecoderUnitTest > Update previous failure case to be a success case.
- encoder.html > Added reference to Mime decoder and related javadocs.

encoder: Base64 decode handle wrapped lines

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SiteIsolationScanRule.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SiteIsolationScanRuleTest.java

Use case insensitive HTTP field name check in Insufficient Site Isolation Against Spectre Vulnerability scan rule.

pscanrulesAlpha: correct HTTP field name check

---

addOns/network/network.gradle.kts
addOns/network/src/main/java/org/apache/hc/core5/http2/impl/DefaultH2RequestConverter.java
addOns/network/src/main/java/org/apache/hc/core5/http2/impl/DefaultH2ResponseConverter.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/Http2MessageHelper.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpRequestDecoder.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/CommonMessagePropertiesHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/HttpServer.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/Http2MessageHelperUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/HttpRequestDecoderUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/HttpToHttp2ConnectionHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/CommonMessagePropertiesHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandlerUnitTest.java
addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/callback/CallbackProxyListener.java
addOns/oast/src/test/java/org/zaproxy/addon/oast/services/callback/CallbackProxyListenerUnitTest.java

Network:
- Flag responses from the target host, this could lead to responses not being passively scanned.
- Add the source address to all messages received by the local servers, regardless of the HTTP version.
- Allow (semantically) malformed messages (e.g. names with mixed/upper case, invalid pseudo-headers).
- Correct the order when HTTP/2 preface handler is added.
- Reduce the changes done to the messages received and forwarded.
OAST:
- Do not include the Connection header in Callback responses for HTTP/2.

Address issues related to HTTP/2

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/launch/ExtensionQuickStartLaunch.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/launch/LaunchPanel.java

Unregister the event consumer when the add-on is unloaded.

quickstart: correctly unload the add-on

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/h2/HttpMessageResponseConsumer.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/apachev5/h2/HttpMessageResponseConsumerUnitTest.java

Check if the entity is null (no data frames consumed) when setting the body, otherwise it would be ignored and the body would not be set.

network: correctly handle no data frames

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/h2/HttpMessageResponseConsumer.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/Http2MessageHelper.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpToHttp2ConnectionHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/InboundHttp2ToHttpAdapter.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/apachev5/h2/HttpMessageResponseConsumerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/Http2MessageHelperUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/HttpToHttp2ConnectionHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/codec/InboundHttp2ToHttpAdapterUnitTest.java

Allow to forward the trailer headers separately from the main headers, to keep the expected content/data.

network: differentiate trailer headers

---

addOns/encoder/CHANGELOG.md
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/EncodeDecodeOptions.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/EncodeDecodeOptionsPanel.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/HashProcessor.java
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/contents/options.html
addOns/encoder/src/main/resources/org/zaproxy/addon/encoder/resources/Messages.properties

- EncodeDecodeOptions > Handle setting and getting the new option value (default true, lower case).
- EncodeDecodeOptionsPanel > Handle displaying the new option value.
- HashProcessor > Handle processing per the new option.
- Messages.properties > Add supporting name/value pairs.
- options.html > Updated with the new option.
Fixes zaproxy/zaproxy#7503

encoder: Add hasher lower case option and new default

---

addOns/retest/CHANGELOG.md
addOns/retest/retest.gradle.kts
addOns/retest/src/main/java/org/zaproxy/addon/retest/RetestPlanGenerator.java
addOns/retest/src/test/java/org/zaproxy/addon/retest/RetestPlanGeneratorUnitTest.java

Include the HTTP version of the alerts' message when creating the requestor job.

retest: include HTTP version for requestor job

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ModernAppDetectionScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ModernAppDetectionScanRuleUnitTest.java

Return was missing, see zaproxy/zaproxy#7617
Fix zaproxy/zaproxy#7617.

pscanrules: ignore non-HTML files in ModernAppDetectionScanRule

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/LocalServersOptions.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsConfig.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/LocalServerConfig.java
addOns/network/src/test/java/org/zaproxy/addon/network/LocalServersOptionsUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsConfigUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/testutils/TestHttpServer.java

Enable ALPN by default.
Remove lower case header workaround.

network: enable ALPN, remove lower case header

---

addOns/callhome/CHANGELOG.md
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java
addOns/callhome/src/test/java/org/zaproxy/addon/callhome/ExtensionCallHomeUnitTest.java

Correctly set the container name when creating the mandatory data, lost when addressing 2.12 deprecations.
Remove related variables/constants that are no longer in use.

callhome: include container name in CFUs

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRule.java
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRuleUnitTest.java

Also tested manually in the UI - if LDAP tech is enabled then the rule runs, if not then it doesnt.

Ascan rules alpha: LDAP tech support

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/javahelp/help/contents/cmdline.html

Do not disable the API when starting the main server in command line mode, allow both to proxy and access the API.

network: allow access to the API in cmd line mode

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/HeadersGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/generators/HeadersGeneratorUnitTest.java

- HeaderGenerator > Add a condition to handle instances where responses are undefined, allowing a warning (such as: `attribute paths.'/users'(get).responses is missing`) to bubble up.
- HeaderGeneratorUnitTest > Add a test that asserts the new behavior.
Fixes zaproxy/zaproxy#7115

openapi: Handle cases where no response is defined

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/BaseHttpSender.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/BaseHttpSenderContext.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/CloseableHttpSenderImpl.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java

Remove on unload:
- `HttpSender` implementation;
- Connection options panel;
- Client Certificates panel.
Save and restore the `HttpSender` implementation state.

network: improve dynamic unload

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/httputils/HtmlContext.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/httputils/HtmlContextAnalyser.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/httputils/HtmlContextAnalyserUnitTest.java

Only require that the attribute value starts with the javascript scheme injection (ignoring leading whitespaces), the presence of other characters following the injection do not necessarily invalidate it.
For example, if it's also injected with a comment (e.g. `//`) it would make it valid, even if it has more/other characters after.

ascanrules: address XSS false negative

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/LegacyUtils.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/LegacyUtilsUnitTest.java

Copy the state of the domain and path cookie attributes when converting between types.
Fix zaproxy/zaproxy#7631.

network: retain cookie attributes when converting

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsConfig.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsConfigUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandlerUnitTest.java

The ALPN is now enabled by default for internal local server/proxies but a client might not negotiate a protocol which would lead to the connection to be closed, instead fallback to HTTP/1.1, keeping the same behaviour as before enabling ALPN.

network: fallback to HTTP/1.1 in internal servers

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/pscanrules.gradle.kts
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyMissingScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CspUtils.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRuleUnitTest.java

- Update Salvation library dependency to 3.0.1. Update tests to accommodate updated functionality.
- CHANGELOG > Add change notes.
- CspUtils > Extract a convenience method to identify if a response has CSP defined via meta. Extract the field name string into a constant.
- ContentSecurityPolicyMissingScanRule > Updated to use CspUtils.
- ContentSecurityPolicyScanRule > Updated to handle META tag CSP definitions, and additional alerts applicable to their use.
- ContentSecurityPolicyScanRuleUnitTest > Add tests to assert the updated and new functionality.
- pscanrules.html > Updated to mention META policies are also checked.
Fixes zaproxy/zaproxy#7303

pscanrules: CSP Meta Handling and dependency update

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/LocalServer.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/LocalServerHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/MainProxyHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/MainServerHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/MainProxyHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/MainServerHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/testutils/TestHttpServer.java

Process the messages in a specific executor, to not prevent serving own requests to the local servers/proxies.

network: use custom executor to process messages

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanJobUnitTest.java

This has actually happened a couple of times with scripts shared with me, and it took me a few mins to work out why the rules were being 'ignored' ;)

Automation: Warn if unexpected element under activeScan job

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java

Allow to dynamically unload when the newer `HttpSenderImpl` is present, which allows to save/restore the implementation's state.

network: dynamically unload on newer versions

---

.github/workflows/ci.yml

Change CI workflow to cache the WebDrivers to avoid hitting rate limits which could fail the build.

Cache WebDrivers in CI

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/commonlib.gradle.kts
addOns/graaljs/CHANGELOG.md
addOns/graaljs/graaljs.gradle.kts

Update the manifest to have the info URL, linking to the corresponding help page.

Add info URL to commonlib and graaljs

---

.github/workflows/create_webdriver_update.yml

If one (or both) of the 'current' versions is null (not retrieved) then just exit quietly.
See #4331 for reference/background.

actions: Webdriver Update - be more defensive

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/BaseHttpSender.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Consume the response body even when none expected (e.g. 204, HEAD), otherwise the previous body would not be cleared when reusing the same message.
---
Reported in the IRC channel.

network: consume response body always

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/environment.html

- environment.html > Added warning note.
Fixes zaproxy/zaproxy#7649

automation: Add help warning about inclusion of default ports

---

addOns/replacer/CHANGELOG.md
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ExtensionReplacer.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplaceRuleAddDialog.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerAPI.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerParam.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerParamRule.java
addOns/replacer/src/main/javahelp/org/zaproxy/zap/extension/replacer/resources/help/contents/replacer.html
addOns/replacer/src/main/resources/org/zaproxy/zap/extension/replacer/resources/Messages.properties
addOns/replacer/src/test/java/org/zaproxy/zap/extension/replacer/ExtensionReplacerTest.java

Adding replacement string processing for the Replacer add-on to permit
users to embed `{{RINT}}`, `{{UUID}}`, and `{{TICKS}}` as values within
their replacement strings which will be converted to the relevant random
type at the time the replacement is performed.
An example use-case is in attempting to determine the source of stored
XSS payloads. By embedding a random integer or uuid into an XSS 
payload, it becomes much quicker to identify the original source requests
for stored XSS.
Example replacement strings:
`<script>alert({{RINT}})</script>` becomes
`<script>alert(1657335)</script>` where 1657335 is a randomly-generated
Integer between `0` and `Integer.maxValue`.
The `RINT` value has optional MIN and MAX value settings. See docs for
details.

replacer: special replacement string processing

---

addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/AccessControlScannerThread.java
addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/view/ContextAccessControlPanel.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/GitMetadata.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureSvnScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/UsernameEnumerationScanRule.java
addOns/authstats/CHANGELOG.md
addOns/authstats/src/main/javahelp/org/zaproxy/zap/extension/authstats/resources/help/contents/authStats.html
addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AddAscanRuleDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/NewPlanDialog.java
addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/CookieUtils.java
addOns/diff/src/main/java/org/zaproxy/zap/extension/diff/ZapDiffRowGenerator.java
addOns/diff/src/main/java/org/zaproxy/zap/extension/diff/diff_match_patch.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParam.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/model/Repo.java
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/Spider.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/filters/FetchFilter.java
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/utility/LazyViewport.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestTreeCellRenderer.java

Per: https://github.com/zaproxy/zap-extensions/pull/3083#issuecomment-1368085064 and https://github.com/check-spelling/zap-extensions/actions/runs/3808821577#summary-10368675301.
I've still left occurrences of "GitHub" or "JavaScript" not following the caps expectations (I'm not sure they're worth changing). There's also still a ton of stuff in the bruteforce sittinglittleducks package(s).
* the the
* should should
* would would
* corresponding corresponding
* may may
* that that
* return return
* during during
* element element
* COMTEXT > CONTEXT
* THREHOLD > THRESHOLD
* locl > lock
* implemention > implementation
* paremtheses > parentheses
* Boolen > Boolean
- tweak one set of short wrapped lines

Spelling batch 8

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testPlan-failOnErrorApplyingParameters.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testPlan-failOnLoggedTestError.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testPlan-failOnWarningApplyingParameters.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testPlan-withTests.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testplan-applyResolvedParams.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testplan-dontfail.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testplan-failonerror.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testplan-failonwarning.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testplan-sametype.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testplan-withwarnings.yaml
addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/javahelp/org/zaproxy/zap/extension/scripts/resources/help/contents/automation.html

The script help should indicate why this is so potentially useful 😉 
The tests took me longer to write than they should have done because the new test plan was failing silently.
This was caused by using the AutomationProgress.info(..) method which failed as the CommandLine was not initialised.
Changing `progressToStdout` to false avoids this problem which is why I've changed it for all of the test plans.

Automation: Get running plans

---

.github/workflows/sonar.yml

Update Run Sonar workflow to use more memory when running the `sonarqube` task, it has been failing often with `OutOfMemoryError`.
---
e.g. https://github.com/zaproxy/zap-extensions/actions/runs/3862674942/jobs/6584392570#step:5:563

Increase heap memory when running Sonar

---

addOns/domxss/domxss.gradle.kts

Use the same versions as the ones being currently cached/downloaded for the WebDriver add-ons.

domxss: update WebDriver versions for tests

---

addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/binlist/BinRecord.java
addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/PiiScanRule.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/PiiScanRuleUnitTest.java

commonlib
- BinRecord > Expose constructor for testing purposes.
- Changelog already has a maint note.
pscanruls
- CHANGELOG > Added change notes.
- PiiScanRule > Added example alert and alert refs handling, which is also leveraged when raising alerts and includes the new solution text. Also exposes unaltered Evidence.
- PiiScanRuleUnitTest > Now asserts the expected example alerts, otherinfo, and alert refs.
- Messages.properties > Updated to include a name/value pair for PII Disclosure solution text.
Related to:
- zaproxy/zaproxy#7676

pscanrules: PII Scan Rule add Solution, Example Alerts

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/HttpOnlySiteScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/HttpOnlySiteScanRuleUnitTest.java

Use the same non-default port otherwise it could be testing other site if using always 443.

ascanrulesBeta: use same port in HTTP Only Site

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/report-traditional-json-plus.html
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/report-traditional-json.html
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/report-traditional-markdown.html
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/report-traditional-xml-plus.html
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/report-traditional-xml.html

Added documentation to template file. This is to clarify ambiguity of output. Specifically, level of risk and level of confidence.
Fix zaproxy/zaproxy#7445

reports: document riskdesc field

---

.github/workflows/codeql.yml

Use the cache from CI to reduce the failures during build of Java code.

Use cache in CodeQL workflow

---

buildSrc/src/main/kotlin/Extensions.kt

Update `javaWith3rdPartyFormatted` to allow to exclude files from all checks.
---
Extracted from eff7d56ac6488a0483b5c76ca33f01059db05039, pushed in #3838.

Allow to exclude 3rd-party code from all checks

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/launch/ExtensionQuickStartLaunch.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/launch/LaunchPanel.java
addOns/quickstart/src/main/resources/org/zaproxy/zap/extension/quickstart/resources/Messages.properties

Add a scheme to the URL if not already present, also, access the URL separately to provide an appropriate error message (i.e. failed to access the URL rather than launch the browser).

quickstart: add scheme to URL if not present

---

addOns/webdrivers/webdriverlinux/CHANGELOG.md
addOns/webdrivers/webdriverlinux/webdriverlinux.gradle.kts

Add task to download/include the geckodriver for aarch64.
Fix zaproxy/zaproxy#7650.

webdriverlinux: include aarch64 geckodriver

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/CacheableScanRule.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/CacheableScanRuleUnitTest.java

- CacheableScanRule > Tweak s-maxage extraction logic.
- CacheableScanRuleUnitTest > Add a test to ensure parsing various different patterns of s-maxage and max-age works without exception. (Adjust one other UnitTest to be parameterized instead of being called multiple times. . Remove some unnecessary comments.)
<details>
<summary>The exception that lead me here, <sub>(Click the triangle/control to the left to expand)</sub></summary>
```text
307740 [ZAP-PassiveScan-3] ERROR org.zaproxy.zap.extension.pscanrulesBeta.CacheableScanRule - An error occurred while checking a URI [https://practiceapi.geeksforgeeks.org/api/vr/courses/home/] for cacheability
java.lang.NumberFormatException: For input string: "600,max-age=0"
at …
```

pscanrulesBeta: Address NumberFormatException in Cacheable rule

---

addOns/ascanrules/ascanrules.gradle.kts
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/HeartBleedActiveScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/RemoteCodeExecutionCve20121823ScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureCve20121823ScanRule.java
addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/Text4ShellScanRule.java
addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/Log4ShellScanRule.java
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/CommonAlertTag.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/CommonAlertTagUnitTest.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/HeartBleedScanRule.java
addOns/retire/CHANGELOG.md
addOns/retire/retire.gradle.kts
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java

- commonlib > Add CommonAlertTag.putCve(Map<String, String> alertTags, String cve) method to leverage across other add-ons.
- commonlib > Rename CommonAlertTagsUnitTest to CommonAlertTagUnitTest to match the class being tested (dropping the s on tags).
- ascanrules, ascanrulesBeta, ascanrulesAlpha, pscanrules, retire > Leverage the new utility method to linkify the relevant CVE Alert Tags.
- retire > Add change note. In other add-ons I believe this change can fall under existing notes.
Follow-up to: https://github.com/zaproxy/zap-extensions/pull/4368

various: Linkify CVE Alert Tags

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ExternalRedirectScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/ExternalRedirectScanRuleUnitTest.java

Identified via:
https://stackoverflow.com/questions/74025214/owasp-on-liferay7-external-redirect-error
- ExternalRedirectScanRule > Added validation to ensure it's much more likely that the payload is not a substring of the returned redirect mechanism (ex: part of the path, or an included parameter). 
- ExternalRedirectScanRuleUnitTest > Add a test method to assert the modified behavior. Add utility methods to simplify and reduce verbosity of nano server handlers.
Fixes: zaproxy/zaproxy#7697

ascanrules: Address FP in External Redirect scan rule

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/CookieUtils.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/CookieUtilsUnitTest.java

Signed-off-by: Diogo Silva <diogo@probely.com>

commonlib: correct parsing of set-cookie without semicolon

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParam.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AllowedResource.java
addOns/spiderAjax/src/test/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParamUnitTest.java

Ensure the default allowed resources are added when using a new configuration.
Correct equals method of `AllowedResource` and add `toString()` to ease debug.
Fix zaproxy/zaproxy#7719.

spiderAjax: add default resources to new config

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/Spring4ShellScanRule.java
addOns/ascanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
addOns/ascanrulesBeta/src/main/resources/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/Spring4ShellScanRuleUnitTest.java
addOns/network/src/main/javahelp/help/contents/options/connection.html
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/HeartBleedScanRule.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties

- Messages.properties > Standardize CVE links on NISTs NVD.
- Spring4ShellScanRule > Add CVE Alert Tag (previously missed).
- Spring4SHellScanRuleUnitTest > Update mappings unit test.
- CHANGELOG.md > Add notes where applicable. Others apply to existing "maintenance changes" notes.
Follow-up to zaproxy/zap-extensions#4380 and IRC discussion.

various: CVE Link Standardization

---

addOns/addOns.gradle.kts

Include the compile classpath as it might be needed during the generation.

Correct API client generation's classpath

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ExtensionAuthhelper.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementPanel.java
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/auth-req-id.html
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/authhelper.html
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/session-header.html
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/index.xml
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/map.jhm
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/toc.xml
addOns/authhelper/src/main/resources/org/zaproxy/addon/authhelper/resources/Messages.properties
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodTypeUnitTest.java

The UI is a bit different but I think it works well in this case.
2 Rows are shown to start with an then other added when the last column is filled in.

authhelper: Add Header based session management

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/TechnologyUtils.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/ContextDialog.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/TechnologyUtilsUnitTest.java

To reproduce:
1. Run the ZAP Desktop
2. Create a new AF plan using the default context
3. Add a new context
An NPE will be logged and the context not added.

Automation: Fix NPE when adding a context to an existing plan

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsConfig.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandler.java
addOns/network/src/main/javahelp/help/contents/options/localservers.html
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsConfigUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/TlsProtocolHandlerUnitTest.java

Improve compatibility with clients that do not support ALPN, by falling back to HTTP/1.1 if no protocol is negotiated.
Fix zaproxy/zaproxy#7699.
---
This is now the same behaviour for both local servers/proxies (#4308) and main proxy thus the option to specify programmatically a fallback protocol was removed.

network: fallback to HTTP/1.1 in the main proxy

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/LocalServersOptions.java
addOns/network/src/test/java/org/zaproxy/addon/network/LocalServersOptionsUnitTest.java

Read any available main proxy configurations, not just when the address is provided to make it easer to override the configs.
Related to zaproxy/zaproxy#7699.

network: read any main proxy configs available

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParam.java
addOns/spiderAjax/src/test/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParamUnitTest.java

Add the default allowed resources if none is present when updating from old versions to ensure the defaults are actually used, as they could be missing in older versions.
Fix zaproxy/zaproxy#7719.

spiderAjax: add allowed resources if none present

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/codec/HttpMessageDecoder.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/MainServerHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/MainProxyHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/MainServerHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/testutils/TextTestClient.java

Only close after writing the whole response otherwise some chunks of the body could be dropped.
Increase body buffer in `HttpMessageDecoder` to make reads more efficient.

network: deliver whole response before closing

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJob.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJobDialog.java
addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/contents/automation.html
addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/Messages.properties
addOns/spiderAjax/src/main/resources/org/zaproxy/zap/extension/spiderAjax/resources/spiderAjax-max.yaml
addOns/spiderAjax/src/test/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJobUnitTest.java

Expose inScopeOnly option in the AJAX Spider AF job.

AJAX Spider: AF Job in scope only

---

addOns/encoder/CHANGELOG.md
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/EncodeDecodeProcessors.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/PowerShellEncoder.java
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/contents/encoder.html
addOns/encoder/src/main/resources/org/zaproxy/addon/encoder/resources/Messages.properties
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/PowerShellEncoderUnitTest.java

Based on tweets and the idea/details from hackvertor/hackvertor#71.
- CHANGELOG.md > Add note.
- EncodeDecodeProcessors > Register the new processor.
- encoder.html > Add help content and code examples.
- Messages.properties > Add key/value pair for the name.
- PowerShellEncoder > New encoder.
- PowerShellEncoderUnitTest > Unit Test for the new encoder.

encoder: Add powershell encoder

---

addOns/spider/CHANGELOG.md
addOns/spider/src/main/java/org/zaproxy/addon/spider/automation/SpiderJob.java
addOns/spider/src/main/resources/org/zaproxy/addon/spider/resources/Messages.properties

The error is logged but not reported via the AF, so not easy to add tests for.
Also added a missing i18n string.

Spider: Fix spurious AF user error

---

addOns/spiderAjax/spiderAjax.gradle.kts

The add-on was still being compiled with older version.
---
I didn't update the changelog, there were no code changes.

spiderAjax: compile with ZAP 2.12

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRuleUnitTest.java

Ignore:
* "RateLimit-Reset"
* "X-RateLimit-Reset"
* "X-Rate-Limit-Reset"
Fixes zaproxy/zaproxy#7747

pscanrules: ignore RateLimit headers in Timestamp Disclosure

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/HexString.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRule.java
addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationEnvironment.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/BruteForceURLFuzz.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/BruteForceWorkGenerator.java
addOns/codedx/src/main/java/org/zaproxy/zap/extension/codedx/UploadPropertiesDialog.java
addOns/diff/src/main/java/org/zaproxy/zap/extension/diff/ZapDiffRowGenerator.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ViewStateDecoder.java
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/HexString.java
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/messagelocations/TextWebSocketMessageLocation.java

Replace usage of `StringBuffer` with `StringBuilder` where the synchronisation of the former is not required.

Use `StringBuilder` whenever possible

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRuleUnitTest.java
testutils/src/main/java/org/zaproxy/zap/testutils/UrlParamValueHandler.java

Some checks are based on response content comparison.
But some sites also include the request payload into their response and do some xml-escaping to be xhtml compatible.
Many SqlInjection attack payloads contain characters like " and ', which would be escaped in the response payload (e.g. " becomes &amp;quot; and ' becomes &amp;apos;).
The SqlInjectionScanRule should exclude these escaped attack payloads before comparing the response content to reduce the number of false negatives

ascanrules: Filter xml escaped reflections in SqlInjectionScanRule

---

addOns/browserView/CHANGELOG.md
addOns/browserView/browserView.gradle.kts
addOns/browserView/src/main/javahelp/org/zaproxy/zap/extension/browserView/resources/help/contents/browserView.html

Use JavaFX 17 when building on aarch64, which supports it.
Update help to mention the requirements of the add-on.
Fix zaproxy/zaproxy#7707

browserView: support building in aarch64

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/http/ComparableResponse.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/http/ComparableResponseUnitTest.java

- CHANGELOG.md > Add change note.
- ComparableResponse > Handle JSONArray.
- ComparableResponseUnitTest > Ensure JSONArrays are handled without throwing an exception.
Fixes zaproxy/zaproxy#7736

commonlib: ComparableResponse handles JSONArrays without exception

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java

Dispose of the scan dialogue when the extension is unloaded to not keep it open after the add-on is uninstalled.

spiderAjax: close scan dialogue on uninstallation

---

addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/VariantGraphQl.java
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/VariantGraphQIUnitTest.java

I'm testing a site that has APIs which all seem to return JSON Arrays.
The logging is not just annoying - its INFO level and I'm getting so many that its seriously impacting performance :/
If its not an error or warning then it should be logged at debug level, especially for variants which get invoked so many times.

GraphQl: dont report errors parsing valid JSON

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/pscanrules.gradle.kts

Require 1.13.0 as minimum, the `HeartBleedScanRule` scan rule requires that version.
Noticed while working on zaproxy/zaproxy#7765.
It would lead to an exception when installing the add-on, e.g.:
```
ERROR AddOnLoaderUtils - Failed to initialise: HeartBleedScanRule
java.lang.NoSuchMethodError: 'void CommonAlertTag.putCve(Map, String)'
at HeartBleedScanRule.<clinit>(HeartBleedScanRule.java:76) ~[?:?]
…
```

pscanrules: update minimum commonlib version

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java

Wait for the news fetch to complete before unloading the extension, otherwise it could lead to an exception during the update.
Also, avoid further processing the news if there's no view.
Noticed while working on zaproxy/zaproxy#7765. e.g.:
```
ERROR UncaughtExceptionLogger - Exception in thread "ZAP-NewsFetcher"
NoClassDefFoundError: org/zaproxy/zap/extension/quickstart/NewsItem
atExtensionQuickStart$1.run(ExtensionQuickStart.java:172) ~[?:?]
…
```

quickstart: wait for news fetch before unload

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/ExtensionOast.java
addOns/oast/src/main/java/org/zaproxy/addon/oast/ui/OastInsertPayloadMenu.java
addOns/oast/src/main/javahelp/org/zaproxy/addon/oast/resources/help/contents/oast.html
addOns/oast/src/main/resources/org/zaproxy/addon/oast/resources/Messages.properties

Fixes zaproxy/zaproxy#7665
Now we can insert payload in http/websocket message panel using context menu as shown in the screenshots below.

oast: add context menu to paste payloads

---

addOns/exim/CHANGELOG.md
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarImporter.java

Log the exception message when failed to import the HAR file, to make it easier to know and potentially fix the problem.

exim: log cause of HAR import error

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/automation/actions/AddScriptAction.java
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/automation/ScriptJobUnitTest.java

Change `AddScriptAction` to not require the name when adding a script from a file, it falls back to the file name.
---
Noticed in zapbot's scans, e.g.:
https://github.com/zapbot/zap-mgmt-scripts/actions/runs/4453577519/jobs/7822193859#step:4:128

scripts: do not require name when adding file

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/InsecureHttpMethodScanRule.java
addOns/ascanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/InsecureHttpMethodScanRuleUnitTest.java

Fixes: Issue - https://github.com/zaproxy/zaproxy/issues/7772
Signed-off-by: Sparsh Sethi sparshsethi15@gmail.com

ascanrulesBeta: PUT/PATCH not insecure methods if returning JSON/XML data 

---

addOns/network/CHANGELOG.md
addOns/network/src/main/javahelp/help/contents/cmdline.html
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties

Make it clear that `-host` and `-port` is for the main proxy not e.g. the outgoing proxy.
---
From IRC channel.

network: improve desc of command line args

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRuleUnitTest.java

Check that the `http-equiv` is also non-null when filtering `meta` elements.

pscanrules: fix NPE in CSP scan rule

---

addOns/openapi/openapi.gradle.kts

Use latest version of `swagger-parser` and `swagger-compat-spec-parse`.

openapi: update swagger dependencies

---

addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts

Update `graphql-java` and `gson` to latest versions.

graphql: Update dependencies

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleFilePassiveScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/ExampleSimplePassiveScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SiteIsolationScanRule.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanRule.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64DisclosureUnitTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SiteIsolationScanRuleTest.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanRuleUnitTest.java

- Base64Disclosure > Add getExampleAlerts and alertRefs for documentation purposes. Clean code slightly (remove unnecessary use of boolean literal).
- Base64Disclosure > Test expected example alerts.
- CHANGELOG.md > Add note.
- ExampleFilePassiveScanRule > Add getExampleAlerts for doc purposes.
- ExampleSimplePassiveScanRule > Add getExampleAlerts for doc purposes.
- SiteIsolationScanRule > Add getExampleAlerts and alertRefs for documentation purposes.
- SiteIsolationScanRuleTest > Test expected example alerts.
- SourceCodeDisclosureScanRule > Add getExampleAlerts for documentation purposes.
- SourceCodeDisclosureScanRuleUnitTest > Test expected example alerts.
Related to zaproxy/zaproxy#6119 and zaproxy/zaproxy#7100

pscanrulesAlpha: Add getExampleAlerts alertRefs for consistency/docs

---

addOns/formhandler/src/main/java/org/zaproxy/zap/extension/formhandler/FormHandlerParam.java
addOns/formhandler/src/test/java/org/zaproxy/zap/extension/formhandler/FormHandlerParamPatternsUnitTest.java
addOns/formhandler/src/test/java/org/zaproxy/zap/extension/formhandler/FormHandlerParamUnitTest.java

- FormHandlerParam.java > Add further defaults.
- FormHandlerParamPattersUnitTest > Add further tests.
- FormHandlerParamUnitTest > Update default count assertions.
<details>
<summary>Replace first word impl <sub>(For future reference)</sub></summary>
```java
private static final String FIRST_WORD = "^\\S+(\\s+)";
...
private static String zapFirstWord(String input) {
return input.replaceFirst(FIRST_WORD, "Zaproxy$1");
}
```
</details>

formhandler: Add more default (datafaker generated) values

---

addOns/exim/CHANGELOG.md
addOns/exim/src/main/java/org/zaproxy/addon/exim/PopupMenuExportMessages.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/log/LogsImporter.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/log/LogImporterUnitTest.java
addOns/exim/src/test/resources/org/zaproxy/addon/exim/log/fourEqualsNoSpace.txt
addOns/exim/src/test/resources/org/zaproxy/addon/exim/log/fourEqualsSpace.txt
addOns/exim/src/test/resources/org/zaproxy/addon/exim/log/threeEqualsNoSpace.txt
addOns/exim/src/test/resources/org/zaproxy/addon/exim/log/threeEqualsSpace.txt

- PopupMenuExportMessages > Ensure the export delimiter format is consistent with the expectation of the Import functionality.
- LogsImporter > Changed visibility of read(File) method to allow testing, added a note covering the same.
- LogsImporterUnitTest > Added tests to ensure import works with various delimiters. Plus associated resource files.
https://github.com/zaproxy/zap-extensions/blob/248b4a0850ba57650ce32032bcd2a7f7458b4b34/addOns/exim/src/main/java/org/zaproxy/addon/exim/log/LogsImporter.java#L181

exim: Correct ZAP Message export/import consistency

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRuleUnitTest.java

Fixes: https://github.com/zaproxy/zaproxy/issues/7724
Changes 
- No alerts raised for JavaScript/CSS responses unless Threshold is set to LOW

pscanrules: ApplicationErrorScanRule JavaScript/CSS FalsePositives

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParam.java
addOns/spiderAjax/src/test/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParamUnitTest.java

Read the existing properties when applying the default allowed resources to honour the `-config` args.
Fix zaproxy/zaproxy#7809.

spiderAjax: apply overrides to default resources

---

addOns/addOns.gradle.kts

Trim the ID to avoid mismatches because of spaces, also, extract a function to avoid duplication.

Trim add-on IDs when processing release tasks

---

addOns/todo/src/main/java/org/zaproxy/zap/extension/todo/ExtensionTodoList.java

Change `ExtensionTodoList` to declare that it can be unloaded.

todo: allow to dynamically unload the add-on

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/DirectoryBrowsingScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/DirectoryBrowsingScanRuleUnitTest.java

Added: 
- buildAlert()
- getExampleAlerts()
- shouldReturnExpectedExampleAlert() [Test]
Moved: 
- Local variables: server, msg and evidence changed to private static variables 
- newAlert() code into buildAlert()
Note: This is my first time contributing as a university student, so thorough examination is advised 
Part of zaproxy/zaproxy#6119.

pscanrules: add example alerts to DirectoryBrowsingScanRule

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/test/java/org/zaproxy/addon/network/ExtensionNetworkUnitTest.java

Make use of the `AliasChecker` when verifying if a pass-through, to prevent passing through requests to the proxies themselves.

network: do not pass-through ZAP domain/aliases

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java

Clear browser hook when disabled otherwise it would prevent enabling it again.

authhelper: clear browser hook when disabled

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/InlineInjector.java
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/InlineInjectorUnitTest.java

Adjust the number of chars trimmed when creating the Sites tree node name to properly show the whole operation name when named and with variables.

graphql: show whole operation name

---

addOns/graaljs/CHANGELOG.md
addOns/graaljs/src/main/zapHomeFiles/scripts/templates/standalone/Loop through history table GraalJS.js
addOns/graaljs/src/main/zapHomeFiles/scripts/templates/standalone/Traverse sites tree GraalJS.js
addOns/groovy/CHANGELOG.md
addOns/groovy/src/main/zapHomeFiles/scripts/templates/standalone/LoopThroughHistoryTable.groovy
addOns/jython/CHANGELOG.md
addOns/jython/src/main/zapHomeFiles/scripts/templates/standalone/Loop through history table.py
addOns/jython/src/main/zapHomeFiles/scripts/templates/standalone/Traverse sites tree.py
addOns/oast/CHANGELOG.md
addOns/oast/src/main/zapHomeFiles/scripts/scripts/standalone/OAST Get BOAST Servers.js
addOns/oast/src/main/zapHomeFiles/scripts/scripts/standalone/OAST Get Interactsh Payloads.js
addOns/oast/src/main/zapHomeFiles/scripts/templates/extender/OAST Request Handler.js
addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/zapHomeFiles/scripts/templates/websocketpassive/Username Idor Scanner.js

Replace singletons with the injected variables (`model` and `control`).
---
Ruby scripts were not yet changed, pending update of the library.

Remove singleton usage in scripts

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CrossDomainScriptInclusionScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CrossDomainScriptInclusionScanRuleUnitTest.java

- Add example alert functionality.
- Add unit tests for example alerts functionality.
- Add note to changelog.

pscanrules: Add Example Alerts to CrossDomainScriptInclusionScanRule

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/JobUtils.java

Fixed an issue where Automation framework is unable to load request files that have absolute path when request files are passed as environment variables.
Details of the issue are available in this slack thread. https://owasp.slack.com/archives/C04SX2GAS/p1676893033077719

automation: correct path resolution with env vars

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CloudMetadataScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CloudMetadataScanRuleUnitTest.java

- CloudMetadataScanRule > Correct IP.
- CloudMetadataScanRuleUnitTest > Correct IP.
Fixes zaproxy/zaproxy#7829

ascanrules: Cloud Metadata Potentially Exposed AWS/GCP IP Fix

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/OutputSummaryJob.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/automation/OutputSummaryJobUnitTest.java

Validate that the summary file has a parent before validating it exists and is readable.
Extract a method to report the error.
---
From OWASP ZAP Developer Group: https://groups.google.com/g/zaproxy-develop/c/i6hjkgs5TKg/m/NSDvGhJfAAAJ

reports: validate output summary file has parent

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/DirectoryBrowsingScanRule.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/DirectoryBrowsingScanRuleUnitTest.java

Use the same name and description for all alerts instead of changing depending on the server found, dynamic information should go on the other info instead.
Remove the evidence from the other info, there's a specific field for the evidence (already being populated).
Add missing word in description and remove extra space.
Adjust example alerts accordingly and verify alerts raised.

pscanrules: tweak alert of Directory Browsing

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParser.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/MessageValidator.java
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/MessageValidatorUnitTest.java
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/automation/GraphQlJobUnitTest.java

Got the idea from "[Chapter 4: Reconnaissance](https://nostarch.com/download/BlackHatGraphQL_ch4sample_011223.pdf)" of the book "Black Hat GraphQL".
Tested the spider against DVGA (https://github.com/dolevf/Damn-Vulnerable-GraphQL-Application) and it sends introspection queries to fewer endpoints while also finding the actual endpoint (which it wasn't before).

graphql: Better spider logic

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/LocalServerHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/MainServerHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/MainServerHandlerUnitTest.java

Use a context for each request otherwise the state of one request could affect the other, e.g. causing responses to not be fetched.
Fix zaproxy/zaproxy#7838.

network: fix concurrency issue handling requests

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/HttpServer.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/HttpServerUnitTest.java

Add logging handlers to allow to log HTTP traffic, to make it easier to debug client side issues.

network: allow to log client side traffic

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/apache/hc/client5/http/impl/classic/ZapInternalHttpClient.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/SocketDelegate.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/ZapHttpRequestExecutor.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/ZapPoolingHttpClientConnectionManager.java

Do not release WebSocket/SSE connections back to the pool, instead discard them when the underlying connection is closed.
Also, increase the number of concurrent connections allowed per route.
Fix zaproxy/zaproxy#7730.

network: prevent reuse of WebSocket/SSE conns

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties

Move text to be under the correct key.

ascanrules: correct resource message

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/spiderAjax.gradle.kts
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
addOns/spiderAjax/src/test/java/org/zaproxy/zap/extension/spiderAjax/ExtensionAjaxUnitTest.java

Do not rely on core to configure logging of own dependencies.
Part of zaproxy/zaproxy#7817.

spiderAjax: configure own logging

---

addOns/domxss/CHANGELOG.md
addOns/domxss/domxss.gradle.kts
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java

To prevent hangs when the "Save As" option is invoked.

DOM-XSS Disable JSON view in Firefox

---

addOns/reports/src/test/java/org/zaproxy/addon/reports/automation/OutputSummaryJobUnitTest.java

Thanks to @thc202 for identifying the cause of the problem :)
The line endings were causing the tests to fail on Windows. This commit replaces `\n` with `System.lineSeparator()`.

Fix reports add-on test failures on Windows

---

addOns/spiderAjax/spiderAjax.gradle.kts
addOns/spiderAjax/src/test/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJobUnitTest.java

Configure Eclipse classpath to not include older version of Byte Buddy which was causing JAR hell when running the tests.
Update tests to match the latest code and expectations.

spiderAjax: restore and fix automation job tests

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionDetectionScanRule.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/SessionDetectionScanRuleUnitTest.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/VerificationDetectionScanRuleUnitTest.java

Use the `tokens` for the example alert to prevent a NPE.
Add test classes for the scan rules to verify the example alerts are generated.

authhelper: fix example alert

---

addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java

Use the WebDriver to install the extensions instead of using a profile, the latter does not always work.
Fix zaproxy/zaproxy#7878.

selenium: install Firefox exts with WebDriver

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/tests/AutomationStatisticTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/tests/AutomationStatisticTestUnitTest.java

Take into account the previous value when testing the statistics otherwise previous values would lead to wrong results.
For example, running the spider several times would test more URLs each time, as it would use the total value rather than the value since the last run.

automation: test stats with previous values

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AutomationPanel.java

Clear the Output tab when a plan is set to avoid output from previous plan to still be shown when a new plan is created.

automation: clear Output tab on plan set

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureSuspiciousCommentsScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureSuspiciousCommentsScanRuleUnitTest.java

- CHANGELOG > Added change notes.
- InformationDisclosureSuspiciousCommentsScanRule > Added example alert functionality, and  WSTG_V42_INFO_05_CONTENT_LEAK tag.
- InformationDisclosureSuspiciousCommentsScanRuleUnitTest > Add unit test to assert the new example.
A follow-up item in zaproxy/zaproxy#5708

pscanrules: Suspicious Comment example alert and custom payloads tag

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/gradle.properties
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJob.java
addOns/spiderAjax/src/test/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJobUnitTest.java

Check that parameters are available when reading the excluded elements.
Fix zaproxy/zaproxy#7889.

spiderAjax: handle no params in automation job

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/payloader/ExtensionPayloader.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/payloader/ExtensionPayloaderUnitTest.java
addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/payloader/ExtensionPayloader.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/payloader/ExtensionPayloaderUnitTest.java

- CHANGELOG > Added change notes.
- ExtensionPayloader > Ensured things unload properly and were named more consistently.
- ExpensionPayloaderUnitTest > Implement tests for extension payloader.
Related to: zaproxy/zap-extensions#4611

ascanrules and pscanrulesBeta: add payloader unit tests

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/HiddenFilesScanRule.java
addOns/ascanrules/src/main/zapHomeFiles/json/hidden_files.json
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/HiddenFilesScanRuleUnitTest.java

- hidden_files.json > Add new entry.
- HiddenFileScanRule > Add handling for optional extra info to be appended to "Other Info".
- HiddenFileScanRuleUnitTest > Update one of the success test cases to include the new Extra/Other Info handling.
Hat tip to @freakyclown:
- https://twitter.com/_Freakyclown_/status/1660737687178072064
- https://github.com/freakyclown/Nuclei_templates/blob/main/blazor_server.yaml

ascanrules: Add Blazor WASM Config file to Hidden File Finder

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/DataGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/generators/DataGeneratorUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/generators/defn-with-query-params.yml

Check that the schema of the parameter is available before getting the type to prevent the `NullPointerException`.
---
From OWASP ZAP User Group: https://groups.google.com/g/zaproxy-users/c/LqtILRKX8Jc/m/xREEz8VwAAAJ

openapi: fix NPE with parameter without schema

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/ContextDialog.java

Initialise the `TechnologyData` when creating the `ContextWrapper.Data` so it's able to set the techs when saving the dialogue.
---
From ZAP User Group: https://groups.google.com/g/zaproxy-users/c/mwRHFwP43Ko/m/mF5fb7mnBAAJ

automation: address NPE when creating a context

---

addOns/automation/src/test/java/org/zaproxy/addon/automation/ContextWrapperUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/JobUtilsUnitTest.java

Do not rely on the file system when creating and asserting file paths.

automation: fix tests to not rely on file system

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/sarif/SarifBase64Encoder.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/sarif/SarifBase64EncoderUnitTest.java

Do not rely on the default charset when creating the string from the Base64 encoded data, ensure it's used always the expected, ISO-8859-1.
Correct the tests to also not rely on the default charset when converting the string to/from bytes.

reports: fix SARIF's Base64 encoder

---

addOns/postman/src/main/java/org/zaproxy/addon/postman/ExtensionPostman.java
addOns/postman/src/main/javahelp/org/zaproxy/addon/postman/resources/help/contents/postman.html
addOns/postman/src/main/resources/org/zaproxy/addon/postman/resources/Messages.properties

The following Command Line options are added:
-`postmanfile` <filename>  : Imports a Postman definition from the specified file name</li>
-`postmanurl` <url> : Imports a Postman definition from the specified URL</li>
-`postmanendpointurl` <url> : The endpoint URL, to override the base URLs present in the Postman definition</li>
Part of https://github.com/zaproxy/zaproxy/issues/6960
Signed-off-by: VitikaSoni <vitika.program@gmail.com>

postman: Add importing through the CLI

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/FormatStringScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/FormatStringScanRuleUnitTest.java

Yes I agree with https://developercertificate.org/. I did this edit in github.dev and am unable to --signoff.
Related to: https://github.com/zaproxy/zaproxy-website/pull/1889#issuecomment-1594119445

ascanrules: Format string rule only needs a single example alert

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/HiddenFilesScanRule.java
addOns/ascanrules/src/main/zapHomeFiles/json/hidden_files.json
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/HiddenFilesScanRuleUnitTest.java

The path shouldn't have a leading slash otherwise the generated path duplicates it.

ascanrules: Correct Blazor HFF entry

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XBackendServerInformationLeakScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/XBackendServerInformationLeakScanRuleUnitTest.java

Changes:
- Add example alert functionality.
- Add unit tests for example alerts functionality.
- Add note to changelog.

pscanrules: Add Example Alert XBackendServerInformationLeakScanRule

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java

The possible clean up is no longer needed, the Bouncy Castle version in use no longer uses a daemon thread by default.

network: remove task no longer needed

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/TableOpenApi.java

- TableOpenApi.java > Increased "definition" column from 16M to 64M. If a session is opened with an existing table then the column definition is adjusted. If a definition greater than 64M is imported then it simply won't persist, but should not fail.
Part of zaproxy/zaproxy#7876

openapi: Increase definition column size

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XChromeLoggerDataInfoLeakScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/XChromeLoggerDataInfoLeakScanRuleUnitTest.java

Changes:
- Add example alert functionality
- Add unit tests for example alert functionality
- Add note to changelog

pscanrules: add examples alerts to X Chrome logger

---

addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/FetchMetadataRequestHeadersScanRule.java
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
addOns/pscanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/FetchMetadataRequestHeadersScanRuleTest.java

Fixes zaproxy/zaproxy#6955. Let me know if this is the right approach or I need to make changes. Otherwise, I'll proceed with the test cases.

pscanrulesAlpha: add scan rule for fetch metadata request headers

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureFileInclusionScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureFileInclusionScanRuleUnitTest.java

Added example alerts for [Source Code Disclosure - File Inclusion](https://www.zaproxy.org/docs/alerts/43/).
[#6119](https://github.com/zaproxy/zaproxy/issues/6119)

ascanrulesBeta: add example alerts to Source Code Disclosure - File Inclusion

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRuleUnitTest.java

Changes:
- Add example alert functionality.
- Add unit tests for example alerts functionality.
- Add note to changelog.

pscanrules: add example alert to Cache Control Scan Rule

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/FetchMetadataRequestHeadersScanRule.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/FetchMetadataRequestHeadersScanRuleTest.java

Add entry to changelog.
Use unique alert references.
Part of #4565.

pscanrulesAlpha: update changelog and alert refs

---

addOns/postman/postman.gradle.kts
addOns/postman/src/main/java/org/zaproxy/addon/postman/ExtensionPostman.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/PostmanApi.java
addOns/postman/src/main/javahelp/org/zaproxy/addon/postman/resources/help/contents/postman.html

The following operations are added to the API:
- ACTION importFile (file, endpointUrl)
- ACTION importUrl (url, endpointUrl)

postman: Add importing through the API

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ServerCertificatesOptions.java
addOns/network/src/main/java/org/zaproxy/addon/network/ServerCertificatesOptionsPanel.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/cert/CertConfig.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/cert/CertificateUtils.java
addOns/network/src/main/javahelp/help/contents/options/servercertificates.html
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties

With some TLS Clients, valid certificates are not enough to establish a valid connection, but it may be required to provide a valid CRL Distribution Point in the generated certificate. 
A classical usecase on Windows is a binary based on libcurl, which uses schannel as backend :
```
PS C:\Users\alice> # using Invoke-webRequest is ok
PS C:\Users\alice> curl https://ifconfig.me/ | Select-Object content
Content
-------
1.2.3.4
PS C:\Users\alice> # but native curl is failing 
PS C:\Users\alice> curl.exe https://ifconfig.me/
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
``` 
More information on this is available for example [here](https://github.com/curl/curl/issues/3727). …

network: Add CRLDistributionPoint attribute option for generated certificates

---

addOns/domxss/CHANGELOG.md
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java

Change the scan rule to skip requests that are globally excluded (e.g. internal browser requests).
Fix zaproxy/zaproxy#7746.

domxss: respect global exclusions

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/common/ZapSocketTimeoutException.java
addOns/network/src/main/java/org/zaproxy/addon/network/common/ZapUnknownHostException.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/automation/SpiderJobUnitTest.java

Keep the original stack trace when creating the custom timeout and unknown host exceptions.

network: keep stack trace of original exceptions

---

addOns/graaljs/CHANGELOG.md
addOns/graaljs/src/main/zapHomeFiles/scripts/templates/authentication/Authentication default template GraalJS.js
addOns/graaljs/src/main/zapHomeFiles/scripts/templates/authentication/BodgeIt Store Authentication GraalJS.js
addOns/graaljs/src/main/zapHomeFiles/scripts/templates/authentication/Simple Form-Based Authentication GraalJS.js
addOns/graaljs/src/main/zapHomeFiles/scripts/templates/authentication/Wordpress Authentication GraalJS.js
addOns/jruby/CHANGELOG.md
addOns/jruby/src/main/zapHomeFiles/scripts/templates/authentication/Simple Form-Based Authentication.rb
addOns/jython/CHANGELOG.md
addOns/jython/src/main/zapHomeFiles/scripts/templates/authentication/Simple Form-Based Authentication.py

Change the authentication template scripts to update the content-length header field after setting the request body.
Related to zaproxy/zaproxy#7936.

Update content-length in auth template scripts

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParam.java
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/GraphQlParamUnitTest.java

Handle the exception when creating invalid enum values.
--- 
From ZAP Developer Group: https://groups.google.com/g/zaproxy-develop/c/MBlbdGoL0TI/m/1LpCzjdJAgAJ

graphql: handle invalid enum when loading options

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/commonlib.gradle.kts
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/binlist/BinList.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/binlist/BinListUnitTest.java

Update:
- Commons IO to 2.13.0.
- Commons CSV to 1.10.0.
Address deprecation.
Add test to verify that the BIN list is still properly loaded.

commonlib: update dependencies

---

addOns/addOns.gradle.kts
build.gradle.kts
testutils/testutils.gradle.kts

Use the main release which is already available.

Remove usage of ZAP snapshot

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/NetworkApi.java
addOns/network/src/test/java/org/zaproxy/addon/network/NetworkApiUnitTest.java

Correct the declaration of the parameter, use `enabled` instead of `description` (the latter being duplicated).

network: correct API parameter name declaration

---

addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts
addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts

Update dependencies.
- `swagger-parser`: `2.1.15` -> `2.1.16` in the openapi add-on
- `graphql-java`: `20.4` -> `21.0` in the graphql add-on

openapi, graphql: Update dependencies

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/impl/FuzzerDialog.java

Ensure the message panel shows the actual contents of the message and what is being selected to fuzz, the message might be modified when saved (e.g. URL normalization).
Fix zaproxy/zaproxy#7947.

fuzz: reset message after edits

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/ActiveScanJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanJobUnitTest.java

Allow to configure and use the max alerts per scan rule in the Active Scan job.
Fix zaproxy/zaproxy#7784.

automation: support max alerts per rule in ascan

---

addOns/formhandler/CHANGELOG.md
addOns/formhandler/src/main/javahelp/org/zaproxy/zap/extension/formhandler/resources/help/contents/FormHandlerHelp.html

Add the space after the tag for proper conversion/rendering in the website (currently shown as `**Note:**The`).

formhandler: tweak space position in help content

---

addOns/replacer/CHANGELOG.md
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplaceRuleAddDialog.java
addOns/replacer/src/main/javahelp/org/zaproxy/zap/extension/replacer/resources/help/contents/replacer.html

Document that Token Processing applies just to string match types and disable the field in the dialogue when other match types are selected.
---
From ZAP User Group: https://groups.google.com/g/zaproxy-users/c/D2BKRS8J900/m/yNSbehPTBQAJ and direct reply.

replacer: update docs and disable field

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts

The `oast` add-on is no longer a dependency, with the promotion of the scan rules that use it.

ascanrulesAlpha: remove `oast` dependency

---

addOns/ascanrulesBeta/ascanrulesBeta.gradle.kts
addOns/pscanrules/pscanrules.gradle.kts

The dependency is already in the test compile/runtime classpaths as it is provided by ZAP core.

Remove redundant test dependencies

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/HttpOnlySiteScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/HttpOnlySiteScanRuleUnitTest.java

Added example alerts for [HttpOnlySiteScanRule](https://www.zaproxy.org/docs/alerts/10106/).
[#6119](https://github.com/zaproxy/zaproxy/issues/6119)

ascanrulesBeta: add example alerts to HttpOnlySiteScanRule

---

addOns/postman/src/main/java/org/zaproxy/addon/postman/AbstractItemDeserializer.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/PostmanParser.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/AbstractItem.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/Item.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/ItemGroup.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/PostmanCollection.java
addOns/postman/src/test/java/org/zaproxy/addon/postman/AbstractItemDeserializerUnitTest.java

This PR implements deserialization of items of a postman definition into `SingleItem` or `ItemGroup` model classes which are the subclasses of `Item`. The deserializer will ignore the items which doesn't fit into these model classes.

postman: Implement item deserialization

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java

Ignore the user property when applying the parameters to the active scan options, the user is handled differently.
This prevents an error from being logged when using the active scan job.
---
```
[ZAP-Automation] ERROR org.zaproxy.addon.automation.jobs.JobUtils - Automation Framework failed to find method setUser on org.parosproxy.paros.core.scanner.ScannerParam
```
e.g. https://groups.google.com/g/zaproxy-users/c/wIf-djwYT9U/m/zk17SwTvAAAJ

automation: address error with active scan job

---

addOns/scripts/scripts.gradle.kts

The dependency is not necessary to compile or run the tests (in any case it would be exposed by a dependency add-on if needed).

scripts: remove unnecessary test dependency

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureFileInclusionScanRule.java
addOns/ascanrulesBeta/src/main/resources/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureFileInclusionScanRuleUnitTest.java

- Message.properties > Removed unused resource keys/values.
- SourceCodeDisclosureFileInclusionScanRule > Tweaked so that the example alerts use the same details as the plugin itself (which were based on vulnerabilities.xml content).
https://github.com/zaproxy/zaproxy-website/pull/2007

ascanrulesBeta: Tweak for SourceCodeDisclosureFileInclusionScanRule alert details

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/report-traditional-markdown.html
addOns/reports/src/main/resources/org/zaproxy/addon/reports/resources/Messages.properties
addOns/reports/src/main/zapHomeFiles/reports/traditional-md/report.md
addOns/reports/src/main/zapHomeFiles/reports/traditional-pdf/report.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-md.md

I have added `Other info` handling for traditional-pdf and traditional-md reports. Am I going in the right direction? And looking at the structure of the high-level report, I don't think 'Other info` is needed, per instance?
Fixes zaproxy/zaproxy#7717
Also see: https://github.com/zaproxy/zap-extensions/pull/4435

Reports: Add Other Info handling

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/commonlib.gradle.kts
addOns/postman/postman.gradle.kts
addOns/reports/CHANGELOG.md
addOns/reports/reports.gradle.kts

Change `commonlib` to provide the Jackson library since it's used by several add-ons.
Change `postman` and `reports` to depend on `commonlib` and no longer include the Jackson dependencies.
Fix zaproxy/zaproxy#7961.

commonlib: provide Jackson lib

---

addOns/jsonview/CHANGELOG.md
addOns/jsonview/jsonview.gradle.kts
addOns/jsonview/src/main/java/org/zaproxy/zap/extension/jsonview/HttpPanelJsonView.java
addOns/jsonview/src/main/java/org/zaproxy/zap/extension/jsonview/internal/JsonFormatter.java
addOns/jsonview/src/test/java/org/zaproxy/zap/extension/jsonview/internal/JsonFormatterUnitTest.java

Use Jackson to format instead of `json-lib`, the latter library might inadvertently change the JSON structure/content while formatting.
Depend on the `commonlib` add-on to reuse the library.
Part of zaproxy/zaproxy#7798.
Related to zaproxy/zaproxy#7961.

jsonview: fix JSON formatting

---

testutils/src/main/java/org/zaproxy/zap/testutils/TestUtils.java

Let the server pick a random port instead of manually getting one first as the latter might cause binding failures on some systems.

testutils: use random server port directly

---

buildSrc/build.gradle.kts

It's not necessary and avoids the need to have/download other JDK, when using newer Java versions.

Remove Java 11 requirement for `buildSrc`

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ServerCertificatesOptionsPanel.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/cert/CertificateUtils.java
addOns/network/src/main/javahelp/help/contents/options/servercertificates.html

Update the names of the root CA cert and issued server certificates, rename also related code constants.
Update the help to reflect the changes.

network: update names in generated certs

---

addOns/encoder/CHANGELOG.md
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/FullUrlEncoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/HexStringDecoder.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/HexStringEncoder.java

Change Full URL and ASCII Hex encoders/decoders to always use UTF-8 to not rely on the default charset, which would lead to different results depending in which OS is ZAP running.

encoder: do not rely on default charset

---

addOns/jsonview/src/test/java/org/zaproxy/zap/extension/jsonview/internal/JsonFormatterUnitTest.java

Use the system's newline char when asserting the expected value.

jsonview: correct test

---

.github/workflows/create_webdriver_update.yml
buildSrc/build.gradle.kts

Use new JSON API endpoint to get the ChromeDriver version in the workflow.
Update the WebDriverManager to use the newer endpoints for the actual download.
Fix zaproxy/zaproxy#7955.

Use newer API endpoint for ChromeDriver

---

addOns/automation/CHANGELOG.md
addOns/automation/automation.gradle.kts

The SnakeYAML Engine is not used, it is used SnakeYAML instead, which is already a (transitive) API dependency.

automation: remove unused API dependency

---

addOns/graphql/graphql.gradle.kts
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlFingerprinter.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParser.java

Use the same deserializer library as the majority of the add-ons, to use a single library (provided by the `commonlib` add-on).
Related to zaproxy/zaproxy#7961.

graphql: use Jackson to parse JSON

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationPlan.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationPlanUnitTest.java

Do not fail to load a plan without jobs, which can still be used to create the context.
---
From ZAP User Group: https://groups.google.com/g/zaproxy-users/c/pMVqqpBC3gE/m/ui3MCJPjAwAJ

automation: load plan without jobs

---

addOns/postman/src/main/java/org/zaproxy/addon/postman/deserializers/ListDeserializer.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/deserializers/ObjectDeserializer.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/AbstractItem.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/AbstractListElement.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/Body.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/ItemGroup.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/KeyValueData.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/PostmanCollection.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/Request.java
addOns/postman/src/test/java/org/zaproxy/addon/postman/ListDeserializerUnitTest.java
addOns/postman/src/test/java/org/zaproxy/addon/postman/ObjectDeserializerUnitTest.java

- Renamed `AbstractItemDeserializer` to `ListDeserializer` and made it usable for subclasses of the newly created `AbstractListElement` class
- Created a new `ObjectDeserializer` to ignore an object when its signature doesn't match, rather than throwing an exception
- Created the necessary model classes to deserialize the request
- Upgraded the Jackson version

postman: Implement request deserialization

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieLooselyScopedScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieLooselyScopedScanRuleUnitTest.java

Change `CookieLooselyScopedScanRule` to provide the example alerts.
Part of zaproxy/zaproxy#6119.

pscanrules: add example alert to scan rule

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/report.html
addOns/reports/src/main/zapHomeFiles/reports/traditional-html/report.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-html-plus.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-html.html

Include other info in `traditional-html` and `-plus`.
Part of zaproxy/zaproxy#7717.

reports: include other info in HTML reports

---

addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureFileInclusionScanRule.java

Hardcode the random file name instead of using the dynamic one, to prevent changes in the generated data (e.g. website).

ascanrulesBeta: use static value in example alert

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/HiddenFilesScanRule.java
addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/HashDisclosureScanRule.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
addOns/pscanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/SourceCodeDisclosureScanRule.java
addOns/pscanrulesBeta/src/main/resources/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/SourceCodeDisclosureScanRuleUnitTest.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestZapUtils.java
addOns/zest/src/main/resources/org/zaproxy/zap/extension/zest/resources/Messages.properties

The single parameter resource messages are misleading as they don't provide any additional data.
Update code to use the parameter directly (some resource messages were not actually in use).
In some scan rules those messages were used as other info but since they were duplicating the evidence they were removed instead.

Remove single parameter resource messages

---

addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java

Add statistics for browser launch successes and failures that include the requester.
Reduce some code duplication by calling existing methods or remove validations already done by the called methods.

selenium: add browser launch stats with requester

---

addOns/alertFilters/CHANGELOG.md
addOns/alertFilters/alertFilters.gradle.kts
addOns/automation/CHANGELOG.md
addOns/automation/automation.gradle.kts
addOns/commonlib/CHANGELOG.md
addOns/commonlib/commonlib.gradle.kts
addOns/exim/CHANGELOG.md
addOns/exim/exim.gradle.kts
addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts
addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts
addOns/reports/CHANGELOG.md
addOns/reports/reports.gradle.kts
addOns/retest/CHANGELOG.md
addOns/retest/retest.gradle.kts
addOns/scripts/CHANGELOG.md
addOns/scripts/scripts.gradle.kts
addOns/soap/CHANGELOG.md
addOns/soap/soap.gradle.kts
addOns/spider/CHANGELOG.md
addOns/spider/spider.gradle.kts
addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/spiderAjax.gradle.kts
addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/wappalyzer.gradle.kts

Move Jackson datatype library from `automation` to `commonlib`.
Update versions of the add-ons to ensure the correct libraries are used.
Related to zaproxy/zaproxy#7961.

Use Jackson from `commonlib` for `automation`

---

addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ImportDialog.java

The import dialog was hanging on successful imports because of an incorrect return value from `ImportDialog#importDefinition`. We were supposed to check that no errors were returned, but we were doing the opposite.
Fixes zaproxy/zaproxy#8011.

openapi: Fix hanging import dialog

---

addOns/graaljs/CHANGELOG.md
addOns/graaljs/graaljs.gradle.kts
addOns/graaljs/src/main/java/org/zaproxy/zap/extension/graaljs/GraalJsEngineWrapper.java

Update to latest version (for Java 11) and set the add-on class loader directly to the context.
Related to zaproxy/zaproxy#7960.

graaljs: update Graal JavaScript engine

---

addOns/network/src/main/java/org/zaproxy/addon/network/ConnectionOptions.java
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/LocalServer.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/LegacyNoCacheRequestHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/ConnectionOptionsUnitTest.java

Add legacy behaviour that removes the cache headers under an option, disabled by default.
Allow the user to restore the old undocumented behaviour while their setup is being corrected.
Part of zaproxy/zaproxy#7353.

network: add optional legacy core behaviour

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ExtensionGraphQl.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlFingerprinter.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParser.java
addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties

- The add-on now includes example alert functionality for documentation generation purposes.
-  zaproxy/zaproxy#6119.

graphql: Add example alerts

---

addOns/commonlib/commonlib.gradle.kts
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/internal/vulns/DefaultVulnerabilities.java
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/internal/vulns/DefaultVulnerability.java
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/vulnerabilities/Vulnerabilities.java
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/vulnerabilities/Vulnerability.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/internal/vulns/DefaultVulnerabilitiesUnitTest.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/internal/vulns/DefaultVulnerabilityUnitTest.java

Add classes to provide the vulnerabilities to other add-ons without the need to rely on core.
Add Jackson XML library to parse the vulnerabilities.xml files, make it also an API dependency to allow other add-ons to use it.
Fix zaproxy/zaproxy#8012.

commonlib: add vulnerability classes

---

addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestDirectory.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestProxyServer.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/api/openapi/simpleAuth/OpenApiLoginPage.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/api/openapi/simpleAuth/OpenApiSimpleAuthDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/api/openapi/simpleAuth/OpenApiTestApiPage.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/api/openapi/simpleAuth/OpenApiVerificationPage.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/api/openapi/simpleUnauth/OpenApiSimpleUnauthDir.java
addOns/dev/src/main/javahelp/org/zaproxy/addon/dev/resources/help/contents/dev.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/api/openapi/simple-auth/home.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/api/openapi/simple-auth/index.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/api/openapi/simple-auth/openapi.json
addOns/dev/src/main/zapHomeFiles/dev-add-on/api/openapi/simple-unauth/index.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/api/openapi/simple-unauth/openapi.yaml
addOns/dev/src/main/zapHomeFiles/dev-add-on/api/openapi/simple-unauth/test-api

Added OpenAPI auth and unauth test pages.
Plan to use these for integration testing (eg the packaged API scan) and authenticated OpenAPI import.
Related to https://github.com/zaproxy/zaproxy/issues/8021

Dev: Added OpenAPI (un)auth pages

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/JobUtils.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/JobUtilsUnitTest.java

Convert the array to string beforehand as the array to string just shows the class name.
Fix cast of list, use interface instead of implementation.
Remove unnecessary stubbings.

automation: correct output of array values

---

addOns/client/src/main/java/org/zaproxy/addon/client/RedirectScript.java

- Earlier ZAP browser extension was behaving abnormally when launched from ZAP. It sometimes had the variables set and sometimes didn't. This was because of the race condition between setting of the local variables and accessing them. So we make a extra reload to ensure that the browser extension has been configured properly.

Client: Fixes ZAP Browser Extension Configuration issue

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CsrfCountermeasuresScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CsrfCountermeasuresScanRuleUnitTest.java

Updated the passive scan CRSF countermeasures rule to consider only HTML files, as discussed in https://github.com/zaproxy/zaproxy/issues/7890
I know that it is currently assigned for @FiveOFive, but I saw this as an opportunity for my first contribution (hope that it is ok)
https://github.com/zaproxy/zaproxy/issues/7890

pscanrules: Update CSRF countermeasures rule to consider only html files

---

addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiExternalRefsUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/openapi_external_refs.yaml

Add test that verifies that the access of external references is not done by ZAP.
Related to zaproxy/zaproxy#7856.

openapi: test access of external references

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ExtensionZest.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/OptionsZestPanel.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestParam.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestScriptWrapper.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestRecordScriptDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestScriptsDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/menu/ZestGenerateScriptFromAlertMenu.java
addOns/zest/src/main/resources/org/zaproxy/zap/extension/zest/resources/Messages.properties
addOns/zest/src/test/java/org/zaproxy/zap/extension/zest/VerifyScriptTemplates.java
addOns/zest/zest.gradle.kts

Allow rendering Zest scripts in YAML. The format (JSON/YAML) may be changed via the Zest Options screen.

zest: Render scripts in YAML

---

addOns/postman/src/main/java/org/zaproxy/addon/postman/PostmanParser.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/deserializers/ListDeserializer.java

All add-ons have their own class loader and they are isolated from each other (unless they explicitly depend on others), with the move of Jackson libraries to `commonlib` add-on Jackson started to use the class loader of `commonlib` instead of `postman` which caused the deserialisation to fail to find the `postman` classes (as `commonlib` does not depend on `postman`). The change done in `PostmanParser` ensures Jackson uses the `postman` class loader and thus able to find the `postman` classes. The change in `ListDeserializer` is just to use the same configuration we set up initially (otherwise we would have to configure the `ObjectMapper` once again).
Thanks @thc202 for the fix and explanation :)

postman: Fix class loader issue

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/zapHomeFiles/reports/high-level-report/report.html
addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-high-level-report.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-html-plus.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-html.html
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-md.md

Change `high-level-report` to only try access the split description array when the description is not empty, when the description is empty the array is empty as well.
Add alert with empty fields to the tests and update resulting reports accordingly.
Fix zaproxy/zaproxy#8071.

reports: handle alert with empty desc

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/create.html

Link always to latest ZAP version.

reports: update JavaDoc links in help

---

addOns/spider/spider.gradle.kts

Do not prevent JavaDoc errors in the internal/third party class from generating the JavaDoc which is required to release to Maven Central.

spider: exclude `DsStore` from JavaDoc

---

addOns/addOns.gradle.kts

Use a provider since the project description might not yet have been set when the POM is configured.

Correct POM description configuration

---

addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/BaseServer.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/RecursiveRequestChecker.java

Remove reference to instance that no longer exists and correct tag.

network: fix JavaDoc errors

---

addOns/postman/src/main/java/org/zaproxy/addon/postman/ImportDialog.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/PostmanParser.java
addOns/postman/src/main/javahelp/org/zaproxy/addon/postman/resources/help/contents/postman.html
addOns/postman/src/main/resources/org/zaproxy/addon/postman/resources/Messages.properties
addOns/postman/src/test/java/org/zaproxy/addon/postman/PostmanParserUnitTest.java

The import dialog will now allow providing a comma-separated list of variables as key-value pairs in the format `key1=value1,key2=value2,...`

postman: Adding variables support

---

addOns/postman/src/main/java/org/zaproxy/addon/postman/PostmanParser.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/Body.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/KeyValueData.java
addOns/postman/src/test/java/org/zaproxy/addon/postman/PostmanParserUnitTest.java

While working on error reporting, I observed that Postman's default values for attributes in body are set as empty strings. However, the users can potentially modify files, which could lead to exceptions in our addon.

postman: Prevent null values

---

addOns/network/CHANGELOG.md
addOns/network/gradle.properties
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java

Stop the servers before attempting to start them, the servers are started after the installation of the add-on but if done during startup core will execute the command line arguments of the extension which would start the servers again making the servers fail to bind (e.g. address already in use) and ZAP fail to start.

network: ensure servers stopped before starting

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/zapHomeFiles/scripts/templates/extender/Add history record menu.js
addOns/scripts/src/main/zapHomeFiles/scripts/templates/extender/Add toolbar button.js
addOns/scripts/src/main/zapHomeFiles/scripts/templates/extender/Copy as curl command menu.js

Allow to run the extender templates with the JavaScript engines Nashorn and Graal.js without errors.

scripts: update extender templates for Graal.js

---

addOns/network/CHANGELOG.md
addOns/network/gradle.properties
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java

Stop the main proxy with custom port before attempting to start it.
Follow up #4939.

network: ensure custom port main proxy is stopped

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Allow to completely disable the host header normalization when sending the HTTP messages to allow the user to send any number of host headers with any values.

network: allow to disable host normalization

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/AttackThread.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ExtensionQuickStart.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ZapItScan.java

As per title :)
Example output:
```
ZAPit scan of https://www.whatsapp.com
Requests:
https://www.whatsapp.com
Request took 209 msec
Response code 400 (Bad Request)
Response body size 6,244 bytes
No request cookies
No response cookies
Technology:
HSTS
HTTP/3
Number of alerts: 4
Medium: Content Security Policy (CSP) Header Not Set : ""
Low: Permissions Policy Header Not Set : ""
Informational: Modern Web Application : "<noscript>2020</noscript>"
Informational: Non-Storable Content : "400"
Root page stats:
Content type: text/html; charset="utf-8"
Number of HTML tags: 45
Number of HTML links: 3
Number of HTML forms: 0
Number of HTML input fields: 0
```

QuickStart ZAPit: carry on if non success code returned

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/CommandPanel.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ConsolePanel.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ScriptConsoleOptions.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ScriptConsoleOptionsPanel.java
addOns/scripts/src/main/javahelp/org/zaproxy/zap/extension/scripts/resources/help/contents/options.html
addOns/scripts/src/main/javahelp/org/zaproxy/zap/extension/scripts/resources/help/index.xml
addOns/scripts/src/main/javahelp/org/zaproxy/zap/extension/scripts/resources/help/map.jhm
addOns/scripts/src/main/javahelp/org/zaproxy/zap/extension/scripts/resources/help/toc.xml
addOns/scripts/src/main/resources/org/zaproxy/zap/extension/scripts/resources/Messages.properties

Allow the user to select the default behaviour when a script open in the Script Console changes on disk.
- Closes zaproxy/zaproxy#5463
- Closes zaproxy/zaproxy#7582

scripts: Persist default keep/replace behaviour

---

addOns/requester/src/main/java/org/zaproxy/addon/requester/internal/HttpPanelSender.java

Use the flag to disable the host normalization to allow the user to send any number of host headers.

requester: use host normalization flag

---

addOns/spider/gradle.properties

Check that the add-on keeps being binary compatible with the version released to Maven Central.

spider: enable japicmp check

---

.github/workflows/release-add-on.yml
addOns/addOns.gradle.kts

Use the CycloneDX Gradle plugin to generate the BOM.
Include the generated (JSON) BOM in the add-on releases.

Include add-on BOM in GitHub releases

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java

Ensure the UI is not initialized if there's no view during install when failed to start the main proxy (e.g. the port is already in use).
---
From ZAP Developer Group: https://groups.google.com/g/zaproxy-develop/c/Ypb5EW8y0iY/m/nFY4W7iXBAAJ

network: prevent UI during install with no view

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRuleUnitTest.java

- ContentSecurityPolicyScanRule > Set deprecation warning for prefetch-src if included.
- ContentSecurityPolicyScanRuleUnitTest > Add/update tests to assert the new behavior.
ContentSecurityPolicyScanRule - Only alert on wildcard prefetch-src if included in CSP
Fixes zaproxy/zaproxy#8077
Note: I'll probably work on some other deprecations upstream in salvation as well.

pscanrules: CSP - Set deprecation warning for prefetch-src

---

addOns/dev/CHANGELOG.md
addOns/dev/dev.gradle.kts
addOns/dev/src/main/java/org/zaproxy/addon/dev/DevApi.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/ExtensionDev.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/gen/openapi/ZapApiDefinition.java
addOns/dev/src/main/resources/org/zaproxy/addon/dev/resources/Messages.properties

Add an endpoint to get the OpenAPI definition for the ZAP API, generated using the `ApiImplementor`s registered to the `API`.

dev: add endpoint for ZAP API OpenAPI definition

---

.github/workflows/create_eval_villian_update.yml
.github/workflows/create_retirejs_update.yml
.github/workflows/create_wappalyzer_update.yml
.github/workflows/create_webdriver_update.yml

The `hub` command is no longer included by default and `gh` is the recommended replacement.

Replace `hub` with `gh` in workflows

---

.github/workflows/release-add-on.yml
addOns/addOns.gradle.kts
addOns/webdrivers/webdriverlinux/gradle.properties
addOns/webdrivers/webdrivermacos/gradle.properties
addOns/webdrivers/webdriverwindows/gradle.properties

Ensure the output of the BOM tasks don't overlap.
Only run the JAR tasks for the BOMs when needed.
Reset the release state of pending add-ons.

Correct release process

---

addOns/addOns.gradle.kts

The `testutils` can also be a dependency of add-ons.

Include `testutils`'s JAR for BOMs

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/ApplicationTestHolder.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/AppsJsonParseUnitTest.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/JsonParserUnitTest.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/PassiveScannerUnitTest.java
addOns/wappalyzer/wappalyzer.gradle.kts

Size went from ~18MB to ~11MB for the built *.zap add-on.
- ExtensionWappalyzer > Added logging configuration code to keep jsvg from being too verbose. (Changes similar to zaproxy/zap-extensions#4612)
- wappalyzer.gradle.kts > Change dependencies. (Reduce whitespace)
- WappalyzerJsonParser > Update SVG handling code.
- Maintenance changes - Dropped "Wappalyzer" from the start of all the UnitTest class names.

wappalyzer: Move from batik to jsvg

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ContentEncodingsHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/ContentEncodingsHandlerUnitTest.java

Set a custom handler into core to handle the content encodings from the add-on (e.g. to support more encodings).
Part of zaproxy/zaproxy#2198.
---
Needs zaproxy/zaproxy#8130.

network: handle content encodings

---

addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts
addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts

- graphql-java: `21.1` -> `21.2`.
- swagger-compat-spec-parser: `1.0.67` -> `1.0.68`.

graphql, openapi: Update dependencies

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html

Help entries are now identified as 'Technology Detection - Wappalyzer' to simplify searching/filtering.

wappalyzer: Tweak help titles

---

addOns/frontendscanner/src/main/java/org/zaproxy/zap/extension/frontendscanner/FrontEndScannerProxyListener.java
addOns/frontendscanner/src/test/java/org/zaproxy/zap/extension/frontendscanner/FrontEndScannerProxyListenerUnitTest.java

ZAP issues `&filename=front-end-scanner.js` which cause 400 for `front-end-scanner.js`, change `filename` to `fileName` correct this error.
Tested in firefox

frontendscanner: correct API parameter name

---

addOns/revisit/CHANGELOG.md
addOns/revisit/src/main/java/org/zaproxy/zap/extension/revisit/ExtensionRevisit.java

Check that the `hr` is not null, which might be if it was deleted.
---
Fix from #5007, which got accidentally closed while addressing the review comments.

revisit: check `HistoryReference` exists

---

addOns/alertFilters/CHANGELOG.md
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFilterTableModel.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/internal/ScanRulesInfo.java
addOns/alertFilters/src/test/java/org/zaproxy/zap/extension/alertFilters/AlertFilterUnitTest.java

Remove mappings from the extension by using the `ScanRulesInfo`.
Rename a test class to have common suffix.

alertFilters: tidy up code

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/HeadersGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/generators/HeadersGeneratorUnitTest.java

Fixed an issue in the headers generator which might lead to content-type header being incorrectly overridden.

openapi: Headers Generator fix

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/ExtensionAjax.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/PopupMenuAjaxSite.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderPanel.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/internal/PopupMenuItemSpiderDialogWithContext.java

Add a context menu item to the Contexts tree that allows to show the AJAX Spider dialogue with the selected Context.
Add icon to the tools menu item.
Update all UI components to use the same (scaled) icon.
Tidy up `PopupMenuAjaxSite`, remove unnecessary getter and null check.

spiderAjax: add menu item to Contexts tree

---

addOns/replacer/CHANGELOG.md
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ExtensionReplacer.java
addOns/replacer/src/main/javahelp/org/zaproxy/zap/extension/replacer/resources/help/contents/replacer.html
addOns/replacer/src/test/java/org/zaproxy/zap/extension/replacer/ExtensionReplacerTest.java

Disable Host header normalization when the rules affect the Host header.
Fix zaproxy/zaproxy#5475.

replacer: allow to replace the Host header

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthDiagnosticCollector.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthTestDialog.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthenticationDetectionScanRule.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ExtensionAuthhelper.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionDetectionScanRule.java
addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestAuthDirectory.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/jsonMultipleCookies/JsonMultipleCookiesDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/gen/openapi/ZapApiDefinition.java
addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ZapItScan.java
build.gradle.kts
buildSrc/src/main/java/org/zaproxy/gradle/spotless/ValidateImports.java

Replace v2 classes with v3.
Add Spotless step to disallow use of v2 classes.
Follow up #4295.

Remove usages of Commons Lang v2

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/ClientIntegrationAPI.java
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/test/java/org/zaproxy/addon/client/ExtensionClientIntegrationUnitTest.java

Hit a case where Selenium was not updating the Firefox profiles.ini
This meant that the extension had to be manually approved every time Firefox was started.
This fixes that by manually adding it in, if possible.

Client: Firefox profile init fixes

---

addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlGenerator.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParser.java
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/GraphQlGeneratorUnitTest.java

- Update graphql-java to `21.3`.
- Remove the experimental `oneOf` directive from the introspection query that was added in graphql-java `21.2`. The RFC it was proposed in hasn't been formally approved yet, and many server implementations don't support it, which results in the failure of introspection. I tested the add-on against DVGA to verify this behaviour.
- Fix an issue with the generator where it was not making use of wrapped types (lists, non-null) to generate queries when the lenient max query depth criteria was met.
- Include the SLF4J2 -> Log4j bridge with the add-on.

graphql: Updates and fixes

---

addOns/alertFilters/CHANGELOG.md
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java
addOns/alertFilters/src/test/java/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFiltersUnitTest.java

Do not add alert filters that are malformed (i.e. null) otherwise it will lead to exceptions later when using them.
Extract common code to decode the alert filters and skip null ones, for when importing and loading a context.
---
From ZAP User Group: https://groups.google.com/g/zaproxy-users/c/FV9KSFa9F7g/m/BIyhS1MDAgAJ

alertFilters: skip malformed context alert filter

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/ui/ZapSortedMenu.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/ui/ZapSortedMenuUnitTest.java
addOns/exim/CHANGELOG.md
addOns/exim/exim.gradle.kts
addOns/exim/src/main/java/org/zaproxy/addon/exim/ExtensionExim.java

- Duplicate the ZapSortedMenu class from the core to commonlib, as discussed in IRC.
- Update exim to use ZapSortedMenu for the Export menu.

exim: Keep Export menu items sorted

---

addOns/network/CHANGELOG.md
addOns/network/network.gradle.kts
addOns/network/src/main/java/org/apache/hc/client5/http/impl/classic/ZapRequestAddCookies.java
addOns/network/src/main/java/org/apache/hc/client5/http/impl/cookie/RFC6265CookieSpec.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Send the cookies (names and values) like browsers do, mostly send what is received.
Verified with Chrome and Firefox.
Fix zaproxy/zaproxy#1232.
Fix zaproxy/zaproxy#7874.

network: handle cookies like browsers

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/CommandPanel.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ConsolePanel.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ScriptConsoleOptions.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ScriptConsoleOptionsPanel.java
addOns/scripts/src/main/javahelp/org/zaproxy/zap/extension/scripts/resources/help/contents/options.html
addOns/scripts/src/main/resources/org/zaproxy/zap/extension/scripts/resources/Messages.properties

Allow setting the tab size and whether to use tabs or spaces for indentation in the console.

scripts: Allow configuring indentation settings

---

addOns/callhome/CHANGELOG.md
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java

Allow to know how the API is used.

callhome: upload API stats

---

addOns/callhome/CHANGELOG.md
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java

Allow to know how many errors are happening.

callhome: upload error stats

---

addOns/selenium/selenium.gradle.kts

No longer set the options through the client generator configuration, as it is now set in the code.

selenium: update API client gen conf

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/ClientDetailsPanel.java
addOns/client/src/main/java/org/zaproxy/addon/client/ClientHistoryPanel.java
addOns/client/src/main/java/org/zaproxy/addon/client/ClientHistoryTableModel.java
addOns/client/src/main/java/org/zaproxy/addon/client/ClientNodeDetailsPanel.java
addOns/client/src/main/java/org/zaproxy/addon/client/ClientUtils.java
addOns/client/src/main/java/org/zaproxy/addon/client/ComponentTableModel.java
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/PopupMenuClientDetailsCopy.java
addOns/client/src/main/java/org/zaproxy/addon/client/PopupMenuClientHistoryCopy.java
addOns/client/src/main/java/org/zaproxy/addon/client/PopupMenuItemClientDetails.java
addOns/client/src/main/java/org/zaproxy/addon/client/PopupMenuItemClientHistory.java
addOns/client/src/main/java/org/zaproxy/addon/client/ReportedEvent.java
addOns/client/src/main/java/org/zaproxy/addon/client/ReportedNode.java
addOns/client/src/main/java/org/zaproxy/addon/client/ReportedObject.java
addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/contents/client.html
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/Messages.properties

Add context menus for copying table cell values from the Client Details and History tabs.
Fixes https://github.com/zaproxy/zaproxy/issues/8173

Client: History and Details menus

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/ClientMapPanel.java
addOns/client/src/main/java/org/zaproxy/addon/client/ClientNodeDetailsPanel.java

Do not set background colour in Client Details and remove bottom padding, which does not seem to be needed.
Show icons properly in Client Map when using Mac OS X look and feel.
Part of zaproxy/zaproxy#8175.

client: tweaks for better look and feel

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Only set the content-length if not a SSE response when the transfer-encoding header is removed.
---
WIP as I want to add some tests to ensure this does not regress.
From ZAP User Group: https://groups.google.com/g/zaproxy-users/c/SguXEsVzHYE/m/7uiRfwIuAAAJ
Introduced in #3944.

network: do not set content-length to SSE

---

addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthUtilsUnitTest.java
addOns/bruteforce/src/test/java/org/zaproxy/zap/extension/bruteforce/BruteForceParamUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/MissingUrlsThreadUnitTest.java
addOns/fuzz/src/test/java/org/zaproxy/zap/extension/fuzz/FuzzOptionsUnitTest.java
addOns/portscan/src/test/java/org/zaproxy/zap/extension/portscan/PortScanParamUnitTest.java
addOns/retest/src/test/java/org/zaproxy/addon/retest/RetestPlanGeneratorUnitTest.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/SpiderParamUnitTest.java

Either mock or set up ZAP properly to avoid reusing the same ZAP home by multiple tests at the same time, which would lead to the test process being exited.

Address concurrency issues in tests

---

addOns/reports/CHANGELOG.md
addOns/reports/reports.gradle.kts
addOns/reports/src/main/zapHomeFiles/reports/risk-confidence-html/report.html
addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java

- report.html > Wrapped previous un-wrapped fragments.
- ExtensionReportsUnitTest > Add unit test asserting that reports generate without warnings. Update other tests as appropriate.
- reports.gradle.kts > Add Log4j as a test dependency.
Addresses warnings such as:
```
1368064 [AWT-EventQueue-0] WARN  org.thymeleaf.standard.processor.AbstractStandardFragmentInsertionTagProcessor - [THYMELEAF][AWT-EventQueue-0][C:\Users\thorin\ZAP_D\reports\risk-confidence-html\report.html] Deprecated unwrapped fragment expression "::alertsTable(alert=${filteredAlert})" found in template C:\Users\thorin\ZAP_D\reports\risk-confidence-html\report.html, line 473, col 14. Please use the complete syntax of fragment expressions instead ("~{::alertsTable(alert=${filteredAlert})}"). …
```

reports: Address warnings in Risk and Confidence HTML template

---

addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/SeleniumOptionsPanel.java

Prevent the options from being hidden when resizing the panel. Reduce the number of rows that need to be shown in the extensions table, as they are not usually many and keeps the panel smaller.
Fix zaproxy/zaproxy#8178.

selenium: add scroll bar to options panel

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/CommandPanel.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ScriptConsoleOptions.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ScriptConsoleOptionsPanel.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/SyntaxHighlightTextArea.java
addOns/scripts/src/main/javahelp/org/zaproxy/zap/extension/scripts/resources/help/contents/options.html
addOns/scripts/src/main/resources/org/zaproxy/zap/extension/scripts/resources/Messages.properties

Provide options to allow editing the font name and size used in the Script Console code editor.
- Closes zaproxy/zaproxy#8065.

scripts: Allow modifying console font

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CommandInjectionScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/timing/TimingUtils.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/timing/TimingUtilsUnitTest.java

Per discussion in https://github.com/zaproxy/zaproxy/issues/8112 TimingUtils is currently using step function of delays starting at 1 second and incrementing by 1 second. However, real world applications and networks often have normal response time variations > 1 second so this is prone to false positives. This change switches to using alternating high and low delays (15 seconds, 1 second) to minimize false positives.
https://github.com/zaproxy/zaproxy/issues/8112
https://github.com/zaproxy/zap-extensions/pull/4679
https://github.com/zaproxy/zap-extensions/pull/4997
https://groups.google.com/g/zaproxy-develop/c/KGSkNHlLtqk

Use varied high and low delays in time-based attack tests

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ConsolePanel.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ScriptsListPanel.java
addOns/scripts/src/main/javahelp/org/zaproxy/zap/extension/scripts/resources/help/contents/console.html

- Add the shortcut `ctrl+S` (`cmd+S` on macOS) to save the script in the console.
- Fix a race condition between saving a script and checking if it was changed on disk by synchronizing those statements.
The issue is that `ScriptWrapper#hasChangedOnDisk()` is being called from the polling thread even before `ScriptWrapper#lastModified` is updated in `ScriptWrapper#saveScript()`. I think the proper fix would be to make these methods synchronized in the core.

scripts: Add save shortcut and fix race condition

---

addOns/alertFilters/CHANGELOG.md
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFilter.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/AlertFilterAPI.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/GlobalAlertFilterParam.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/automation/AlertFilterJob.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/internal/ScanRulesInfo.java
addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/contents/alertFilterDialog.html
addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/contents/automation.html
addOns/alertFilters/src/main/resources/org/zaproxy/zap/extension/alertFilters/resources/alertFilter-max.yaml
addOns/alertFilters/src/test/java/org/zaproxy/zap/extension/alertFilters/AlertFilterUnitTest.java
addOns/alertFilters/src/test/java/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFiltersUnitTest.java
addOns/alertFilters/src/test/java/org/zaproxy/zap/extension/alertFilters/automation/AlertFilterJobUnitTest.java

Allow to specify the alert reference where the scan rule ID is being specified and update code accordingly (e.g. change `int` to `String`).
Change `ScanRulesInfo` to get the alert references from the scan rules that provide example alerts.
Fix zaproxy/zaproxy#7438.

alertFilters: allow to filter by alert ref

---

addOns/jython/CHANGELOG.md
addOns/jython/jython.gradle.kts
addOns/jython/src/main/java/org/zaproxy/zap/extension/jython/ExtensionJython.java
addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ConsolePanel.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ScriptConsoleOptionsPanel.java
addOns/scripts/src/main/resources/org/zaproxy/zap/extension/scripts/resources/Messages.properties
addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ExtensionZest.java
addOns/zest/zest.gradle.kts

* Move "Jython" and "Zest" under "Scripts > Engine" in the Options panel list.
* Rename "Script Console" to "Console" in the Options panel list.

jython, zest: Move options under "Scripts" node

---

addOns/alertFilters/CHANGELOG.md
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/DialogAddAlertFilter.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/automation/AddAlertFilterDialog.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/internal/ScanRulesInfo.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/internal/ui/AlertSelectionPanel.java
addOns/alertFilters/src/main/javahelp/org/zaproxy/zap/extension/alertFilters/resources/help/contents/alertFilterDialog.html

Rework the UI to allow to specify a custom ID (scan rule or alert reference) as it might not be known to ZAP (e.g. not yet installed or using a custom script rule).

alertFilters: allow to specify custom rule ID

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/FetchMetadataRequestHeadersScanRule.java
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html

added getHelpLink method in Base64Disclosure.java and FetchMetadataRequestHeadersScanRule.java
added anchor tag for respective method in pscanalpha.html 
This PR is part of issues [#8189](https://github.com/zaproxy/zaproxy/issues/8189)
@psiinon can you please review it
- Website alert links (Issue 8189).

pscanrulesAlpha: Link website alert pages <-> help

---

addOns/network/CHANGELOG.md
addOns/network/network.gradle.kts
addOns/network/src/main/java/org/zaproxy/addon/network/internal/ContentEncodingsHandler.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/HttpEncodingBrotli.java
addOns/network/src/main/javahelp/help/contents/options/localservers.html
addOns/network/src/test/java/org/zaproxy/addon/network/internal/ContentEncodingsHandlerUnitTest.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/HttpEncodingBrotliUnitTest.java

Support encoding/decoding on Linux x64, macOS, and Windows x64.
Part of zaproxy/zaproxy#2198.

network: add support for br content encoding

---

addOns/soap/CHANGELOG.md
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/WSDLCustomParser.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/WSDLCustomParserTestCase.java

Use the generated values always and use as default the appropriate ones generated by the class itself.
Correct date formats which were failing to compile.
Fix zaproxy/zaproxy#8202.

soap: correct use of and generated values

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/SourceCodeDisclosureScanRule.java
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/SourceCodeDisclosureScanRuleUnitTest.java

- pscanbea.html > Updated help entry.
- ScourceCodeDisclosureScanRule > Add control characters check in skip conditional.
- ScourceCodeDisclosureScanRuleUnitTest > Add test to assert the new behavior.
Fixes zaproxy/zaproxy#8191

pscanrulesBeta: Source Code Disclosure skip binary'ish responses

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRuleUnitTest.java

- pscanrules.html > Updated help entry.
- ApplicationErrorScanRule > Add control characters check in skip conditional.
- ApplicationErrorScanRuleUnitTest > Add test to assert the new behavior.
Encountered:
> 84173 [ZAP-PassiveScan-3] WARN org.zaproxy.zap.extension.pscan.PassiveScanTask - Passive Scan rule Application Error Disclosure took 6 seconds to scan https://zapmp4issuedemo.dotnest.net/TheComingSoonTheme/assets/mp4/bg.mp4 video/mp4 13292671
while working on zaproxy/zaproxy#8191 / zaproxy/zap-extensions#5101

pscanrules: Application Error Disclosure skip binary'ish responses

---

addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/BodyGeneratorUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/v3/petstore_reduced_intl_phone.yaml

Add test to ensure plus is maintained in Intl Phone Numbers
zaproxy/zaproxy#6644 
- [NA] Update changelog

openapi: Add test to ensure plus is maintained in Intl Phone Numbers

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/ClientMap.java
addOns/client/src/main/java/org/zaproxy/addon/client/ClientUtils.java
addOns/client/src/test/java/org/zaproxy/addon/client/ClientMapUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/ClientNodeUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/ClientUtilsUnitTest.java

PR #5040 was a big improvement, but I accidently changed it so that `#` and `/#` were no longer separate nodes.
This changes that back as I think it makes more sense.
Its not a bug as such - this is just the GUI structure, so its up to us what it looks like.
#5040 

Client: Add back hash nodes

---

addOns/addOns.gradle.kts

Use the latest version to address some tasks errors with the Gradle version already in use.
---
Reported in ZAP Developer Group: https://groups.google.com/g/zaproxy-develop/c/XBI-h3yacfg/m/MHMsTbQVAQAJ

Update Gradle add-on plugin

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRuleUnitTest.java

- TimestampDisclosureScanRule > Updated to include the header name as the alert parameter when applicable.
- TimestampDisclosureScanRuleUnitTest > Add/update tests to assert the new alert content.
Fixes zaproxy/zaproxy#8160

pscanrules: Timestamp Disclosure include header field as param

---

addOns/spider/CHANGELOG.md
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderHttpHeaderParser.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderHttpHeaderParserUnitTest.java

- SpiderHttpHeaderParser > Use core constants, and handle multiple Link response headers.
- SpiderHttpHeaderParserUnitTest > Add new test asserting the new behavior.

spider: Address todo items and handle multiple Link response headers

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/HiddenFilesScanRule.java
addOns/ascanrules/src/main/javahelp/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/HiddenFilesScanRuleUnitTest.java

Per:
https://www.zaproxy.org/docs/desktop/ui/dialogs/scanpolicy/#threshold Low should mean potentially more alerts.
- ascanrules.html > Update help.
- HiddenFilesScanRule > Adjust Threshold handling.
- HiddenFilesScanRuleUnitTest > Adjust to properly test the fixed behavior.
- zaproxy/zaproxy#8234
- zaproxy/zap-extensions#2514 :cry: Seems to be where I implemented this backward to start with.

ascanrules: Hidden File Finder-Fix threshold handling to align w/ help

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionMsSqlScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionMsSqlScanRuleUnitTest.java

Adapt `SqlInjectionMsSqlScanRule` to do the time-based tests with the timing utils.

ascanrules: use timing utils in MsSQL scan rule

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/BigRedirectsScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/BigRedirectsScanRuleUnitTest.java

- BigRedirectScanRule > Add further functionality to check if the response contains multiple HREFs, example alerts, and Alert Refs.
- BigRedirectScanRuleUnitTest > Add tests for new behavior, example alerts, and alert refs.
- CHANGELOG > Add change notes.
- Messages.properties > Add supporting resources.
- pscanrules.html > Update help entry.
Hat tip to @xnl-h4ck3r for the idea: https://twitter.com/xnl_h4ck3r/status/1724808036706091496
- zaproxy/zaproxy#7100
- zaproxy/zaproxy#8189

pscanrules: Big Redirect rule - Also alert on multiple HREFs in body

---

addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/CommonPassiveScanRuleInfo.java
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/FetchMetadataRequestHeadersScanRule.java
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html

Use the IDs of the scan rules for the links.
Also, add an interface to define the URL in a single place which avoids the need to change the scan rule when promoting/demoting.
Related to zaproxy/zaproxy#8189.

pscanrulesAlpha: use IDs for alert links

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/server/http/handlers/LegacyProxyListenerHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/server/http/handlers/LegacyProxyListenerHandlerUnitTest.java

This PR is 1st step to address https://github.com/zaproxy/zaproxy/issues/8146
Assumptions made are described in comment.
2nd step will be in PR to zaproxy repository. https://github.com/zaproxy/zaproxy/pull/8158
I tried proposed changes - they seem to be working fine. Requests are being processed in parallel, breakpoints wait for user interaction, not blocking other requests.
Probably there are some scenarios requiring further code changes? Please take a look.

network: notify `ProxyListener`s concurrently

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionHypersonicScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionMsSqlScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionHypersonicScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionMsSqlScanRuleUnitTest.java

Move the declaration of the variables, to ensure the expected message and evidence is included in the alert.

ascanrules: correct evidence in MsSQL and Hyper

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java

Don't enable the built in script that requires the GUI when it's not available (e.g. running daemon mode).
---
From ZAP User Group: https://groups.google.com/g/zaproxy-users/c/oaR0MvG1BPQ/m/HSSFj9NQAwAJ

scripts: prevent GUI init in daemon mode

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PersistentXssPrimeScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/PersistentXssSpiderScanRule.java
addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/PersistentXssPrimeScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/PersistentXssSpiderScanRuleUnitTest.java
testutils/src/main/java/org/zaproxy/zap/testutils/ActiveScannerTestUtils.java
testutils/src/main/java/org/zaproxy/zap/testutils/AlertReferenceError.java
testutils/src/main/java/org/zaproxy/zap/testutils/PassiveScannerTestUtils.java
testutils/src/main/java/org/zaproxy/zap/testutils/ScanRuleTests.java

Do the following validations:
- Valid URI;
- Uses HTTPS scheme.
Enable the validation for two rules and make them pass by removing "N/A" references/data.
Part of zaproxy/zaproxy#5364.

Validate references of example alerts

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/pscanrulesAlpha.gradle.kts
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/FullPathDisclosureScanRule.java
addOns/pscanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesAlpha/resources/help/contents/pscanalpha.html
addOns/pscanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/pscanrulesAlpha/resources/Messages.properties
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/FullPathDisclosureScanRuleUnitTest.java

A passive scanner to scan for full path disclosure vulnerability on windows and UNIX systems.
[Issue link](https://github.com/zaproxy/zaproxy/issues/413)

pscanrulesAlpha: Full Path disclosure vulnerability scanning

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/NetworkApi.java
addOns/network/src/test/java/org/zaproxy/addon/network/NetworkApiUnitTest.java

Accept the group by in any case form, to not require the user to upper case it (docs also suggest using lower case).
---
From ZAP User Group: https://groups.google.com/g/zaproxy-users/c/gsOWsrciXjs/m/yuOoFTWZAgAJ

network: correct handling of group by in the API

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties

Update Vulnerabilities' references and descriptions to use https links for Content type header missing and X-Content-Type-Options Header Missing(Issue 8262).
Related to: zaproxy/zaproxy/issues/8262

pscanrules: Update reference links (http -> https)

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/resources/org/zaproxy/addon/commonlib/internal/vulns/vulnerabilities.xml
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/internal/vulns/DefaultVulnerabilitiesUnitTest.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/internal/vulns/ValidateTranslatedVulnerabilitiesFilesUnitTest.java

- Update Vulnerabilities' references and descriptions to use https links and retire some which were out-dated (Issue 8262).
Related to: zaproxy/zaproxy#8262

commonlib: Update reference links (http -> https)

---

addOns/jruby/CHANGELOG.md
addOns/jruby/jruby.gradle.kts
addOns/jruby/src/main/zapHomeFiles/scripts/templates/active/Active default template.rb
addOns/jruby/src/main/zapHomeFiles/scripts/templates/passive/Passive default template.rb
addOns/scripts/CHANGELOG.md
addOns/scripts/gradle.properties
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/scanrules/ActiveScript.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/scanrules/ActiveScript2.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/scanrules/PassiveScript.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/scanrules/ScriptsActiveScanner.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/scanrules/ScriptsPassiveScanner.java
addOns/scripts/src/main/resources/org/zaproxy/zap/extension/scripts/resources/Messages.properties
addOns/scripts/src/main/zapHomeFiles/scripts/templates/active/Active default template.js
addOns/scripts/src/main/zapHomeFiles/scripts/templates/passive/Passive default template.js
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/scanrules/ScriptsActiveScannerUnitTest.java
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/scanrules/ScriptsPassiveScannerUnitTest.java
addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestActiveRunner.java
addOns/zest/zest.gradle.kts

Migrate scripts scanning infrastructure from core to add-ons.
- First step towards https://github.com/zaproxy/zaproxy/issues/7105.
- See also https://github.com/zaproxy/zaproxy/pull/8265.

scripts: Migrate scan rule functionality from core

---

addOns/reports/src/main/java/org/zaproxy/addon/reports/ReflectionUtils.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportDialog.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/ReportJobDialog.java

Add the sections' options with a vertical weight so the scroll pane resizes smoothly.
Using reflection, which can be removed once zaproxy/zaproxy#8270 is available for the add-on to use.
Mentioned in #5172.

reports: correct sections' resize behavior

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieLooselyScopedScanRuleUnitTest.java

Update Vulnerabilities' references to use https links for Loosely Scoped Cookie (Issue 8262).
I have only replaced http with https, the actual link has remained the same.
Related to: https://github.com/zaproxy/zaproxy/issues/8262

pscanrules: Update reference links (http -> https) Alert: 90033

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentTypeMissingScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XContentTypeOptionsScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentTypeMissingScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/XContentTypeOptionScanRuleUnitTest.java

- ContentTypeMissingScanRule & XContentTypeOptionsScanRule > Added example alerts, alert refs (where application), and ref verification.
- UnitTests > Updated to assert expected example alerts, details, and refs.
- CHANGELOG > Note added and updated existing.
Follow-up to: 
- zaproxy/zap-extensions#5184
Related to:
- zaproxy/zaproxy#7100
- zaproxy/zaproxy#8189

pscanrules: Add example alerts, alert refs, and ref verification

---

.gitignore

Ignore Eclipse (and Neovim jdtls language server) `.factorypath` files which are auto generated by the IDE.
N/A

Ignore Eclipse / jdtls .factorypath

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CsrfCountermeasuresScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CsrfCountermeasuresScanRuleUnitTest.java

- CsrfCountermeasuresScanRule > Updated to check either equals or contains (ignoring case) depending upon the ANti-CSRF Options setting.
- CsrfCountermeasuresScanRuleUnitTest > Added tests to assert the new behavior.
- pscanrules.html > Add note to rule's entry.
Fixes zaproxy/zaproxy#8280

pscanrules: CSRF Countermeasures rule accounts for partial match setting

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/resources/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties

I have only replaced http with https, the actual link has remained the same. 
https://www.zaproxy.org/docs/alerts/90025/ 
https://www.zaproxy.org/docs/alerts/20014/
In Alert 20014 the reference was a Google search - I have amended this with a link to OWASP. This should take users directly to the reference without having to go through Google.
Related to: https://github.com/zaproxy/zaproxy/issues/8262

ascanrulesBeta: Update reference links (http -> https) Alert: 90025 and  20014

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties

I have only replaced http with https, the actual link has remained the same.
https://www.zaproxy.org/docs/alerts/90019-2/
https://github.com/zaproxy/zaproxy/issues/8262

ascanrules: Update reference links (http -> https) Alert: 90019

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CsrfCountermeasuresScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CsrfCountermeasuresScanRuleUnitTest.java

- CsrfCounterMeasuresScanRule > Use isEmpty vs length/size checks.
- CsrfCounterMeasuresScanRuleUnitTest > Ensure assertEquals parameters are in the correct order.
- CHANGELOG > Add maintenance note.
N/A

pscanrules: Clean Code for CsrfCounterMeasuresScanRule

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionDetectionScanRule.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/SessionDetectionScanRuleUnitTest.java
addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestProxyServer.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonBearerCookie/SimpleJsonBearerCookieVerificationPage.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonBearerJsCookie/SimpleJsonBearerJsCookieDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonBearerJsCookie/SimpleJsonBearerJsCookieLoginPage.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonBearerJsCookie/SimpleJsonBearerJsCookieVerificationPage.java
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json-bearer-js-cookie/home.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json-bearer-js-cookie/index.html

Handle cookies set via JavaScript in session management detection.
An example of an app that does this is OWASP Juice shop 😁 
Also adds a dev test page which works in that way for integration testing.

authhelper: Handle JS cookies

---

addOns/bugtracker/CHANGELOG.md
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerBugzilla.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/BugTrackerGithub.java
addOns/bugtracker/src/main/java/org/zaproxy/zap/extension/bugtracker/ExtensionBugTracker.java

Lazily initialize the options panels.
Replace view singleton usage in the extension with a getter.

bugtracker: prevent UI init without view

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodType.java

Read the user details from the session rather than the individual messages, which could cause an NPE.

authhelper: fix user NPE

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/PiiScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/PiiScanRuleUnitTest.java

PII Scan Rule checks only for Html, Json and Xml content types on Non-LOW threshold. This Pull request fixes zaproxy/zaproxy#8264
[Issue 8264](https://github.com/zaproxy/zaproxy/issues/8264)

pscanrules: PII scan rule checks for HTML, JSON, XML on Non-Low Threshold

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/ReportJob.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/ReportJobDialog.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/automation/ReportJobUnitTest.java

Fixes a counple of problems with the AF report job:
- Replace env vars in URLs used in the plan name (otherwise end up with names like `ZAP-Report-${ZAP_TARGET}.html
`
- Default to use same dir as plan if no dir set

Reports: AF job fixes

---

addOns/automation/src/main/java/org/zaproxy/addon/automation/ContextWrapper.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/TechnologyData.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/TechnologyDataUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/TechnologyUtilsUnitTest.java

Allow to specify a list var for includes/excludes.
A list var (e.g. `${[VAR_NAME]}`) is replaced and parsed as a list before being further processed.
Example value using flow sequence: `[MacOS, Db, Java]`.

automation: support list var in context techs

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties

Signed-off-by: Aditya Parihar <97739299+PariharAditya@users.noreply.github.com>
fixed from HTTP to HTTPS
https://www.zaproxy.org/docs/alerts/40009/
zaproxy/zaproxy#8262

ascanrules: update reference from http to https 40009

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/ascanrulesAlpha.gradle.kts
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjectionScanRule.java
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjectionTimingScanRule.java
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/ascanrulesAlpha/src/main/resources/org/zaproxy/zap/extension/ascanrulesAlpha/resources/Messages.properties
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjectionScanRuleUnitTest.java
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjectionTimingScanRuleUnitTest.java
addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/CommonAlertTag.java

Move time based tests to its own rule, ID 90039.
Part of zaproxy/zaproxy#7341.
---
Extracted from #4316.

ascanrulesAlpha: add rule for MongoDB time tests

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/pscanrules.gradle.kts
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRuleUnitTest.java

- ContentSecurityPolicyScanRule > Updated to use new library. (Which has handling for some deprecated directives the rule had been handling locally.)
- ContentSecurityPolicyScanRuleUnitTest > Updated assertions to match the notices provided by the new library.
- Messages.properties > Updated reference.
- pscanrules.gradle.kts > Change library dependency.
- pscanrules.html > Updated library note.
NA

pscanrules: Content Security Policy scan rule now uses htmlunit library

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java
addOns/network/src/main/resources/org/zaproxy/addon/network/resources/Messages.properties

Remove legacy options panels that helped the user find the new options panels:
- Client Certificate
- Connection
- Dynamic SSL Certificates
- Local Proxies

network: remove legacy options panels

---

addOns/retire/CHANGELOG.md
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
addOns/retire/src/test/java/org/zaproxy/addon/retire/RetireScanRuleUnitTest.java

To avoid things like:
`353477 [ZAP-PassiveScan-1] WARN org.zaproxy.zap.extension.pscan.PassiveScanTask - Passive Scan rule Vulnerable JS Library (Powered by Retire.js) took 6 seconds to scan https://juice-shop.herokuapp.com/video?__ecma.String= video/mp4 10075518`
- RetireScanRule > Target responses that are relevant (HTML and JS).
- RetireScanRuleUnitTest > Updated to assert the latest behavior, example alert, and valid references

retire: Only target relevant responses

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/CacheableScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/CommonPassiveScanRuleInfo.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/InPageBannerInfoLeakScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/JsFunctionScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/JsoScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/PermissionsPolicyScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/ServletParameterPollutionScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/SiteIsolationScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/SourceCodeDisclosureScanRule.java
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/SubResourceIntegrityAttributeScanRule.java
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html

Signed-off-by: Aditya Parihar <97739299+PariharAditya@users.noreply.github.com>
Implemented a new interface for linking to website
updated help with there respective ID
zaproxy/zaproxy#8189

pscanrulesBeta: add website links to help pages 

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthDiagnosticCollector.java

Swap cookie and set-cookie to match the name used in the request and response respectively.

authhelper: correct HTTP field names in diag data

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/JobUtils.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/JobUtilsUnitTest.java

Use neutral locale to upper case the values before creating the enums, otherwise in some locales it could fail to match the enum name.

automation: correct threshold/strength parsing

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosureScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/CommonActiveScanRuleInfo.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/CorsScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/CrossDomainScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/CsrfTokenScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ExponentialEntityExpansionScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ExpressionLanguageInjectionScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/HttPoxyScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/HttpOnlySiteScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/HttpParameterPollutionScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/HttpsAsHttpScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/InsecureHttpMethodScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/IntegerOverflowScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/OutOfBandXssScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ProxyDisclosureScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/RelativePathConfusionScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SessionFixationScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ShellShockScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SlackerCookieScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureFileInclusionScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureGitScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureSvnScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SsrfScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/Text4ShellScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/UsernameEnumerationScanRule.java
addOns/ascanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html

added alert links to website help pages
fixes part of [zaproxy/zaproxy/issues/8189](https://github.com/zaproxy/zaproxy/issues/8189).
[zaproxy/zaproxy/issues/8189](https://github.com/zaproxy/zaproxy/issues/8189)

ascanrulesBeta: add alert links to website help pages

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/apache/hc/client5/http/impl/classic/ZapProtocolExec.java
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Do not attempt to track NTLM auth being proxied, only do that when doing the authentication programmatically (e.g. user set).
Fix zaproxy/zaproxy#7685.

network: prevent NPE when proxying NTLM auth

---

addOns/spider/CHANGELOG.md
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SpiderHtmlParser.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SpiderHtmlParserUnitTest.java
addOns/spider/src/test/resources/org/zaproxy/addon/spider/parser/html/StringSpiderHtmlParser.html

Check the `/` is actually present in the string before obtaining the substring otherwise it would lead to an exception.
From logs in zaproxy/zaproxy#8327.
---
Log excerpt:
```
7186921 [ZAP-SpiderThreadPool-0-thread-2] ERROR org.zaproxy.zap.ZAP.UncaughtExceptionLogger - Exception in thread "ZAP-SpiderThreadPool-0-thread-2"
java.lang.StringIndexOutOfBoundsException: Range [-1, 13) out of bounds for length 13
at jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
at jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
at jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
at jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
at …
```

spider: fix exception in HTML parser

---

addOns/spider/CHANGELOG.md
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/SvgHrefParser.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/SvgHrefParserUnitTest.java

Avoid unnecessary warnings from attempting to parse empty SVGs, which could happen when what looked like a SVG was actually a redirect with empty body.
From logs in zaproxy/zaproxy#8327.
---
Log excerpt:
```
6983864 [ZAP-SpiderThreadPool-0-thread-5] WARN  org.zaproxy.addon.spider.parser.SvgHrefParser - An error occurred trying to parse https://example.com/_autoindex/assets/icons/file.svg
org.xml.sax.SAXParseException: Premature end of file.
at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:262) ~[?:?]
at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:342) ~[?:?]
at org.zaproxy.addon.spider.parser.SvgHrefParser.parseResource(SvgHrefParser.java:84) ~[?:?]
at org.zaproxy.addon.spider.SpiderTask.processResource(SpiderTask.j …
```

spider: skip parsing of empty SVGs

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodType.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthUtilsUnitTest.java

If we fail to identify the session management then request the current page again - this can work well for more traditional web apps.
Also make cookies set in auth request available to header based session management.
These 2 changes mean that auth autodetection now works with both Bodgeit and DVWA.

Authhelper: trad app auth detection improvements

---

addOns/graaljs/CHANGELOG.md
addOns/graaljs/src/main/java/org/zaproxy/zap/extension/graaljs/ExtensionGraalJs.java
addOns/graaljs/src/main/java/org/zaproxy/zap/extension/graaljs/GraalJsEngineWrapper.java
addOns/graaljs/src/test/java/org/zaproxy/zap/extension/graaljs/VerifyScriptTemplates.java
testutils/src/main/java/org/zaproxy/zap/testutils/AbstractVerifyScriptTemplates.java

Add tests to verify that the JavaScript templates are parsed without errors.
Remove workaround that reset the class loader as it's no longer needed.

graaljs: verify script templates can be parsed

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/dialogs/NewScriptDialog.java

The save button was not enabled for new scripts upon creation.
Mark the script as changed when it is created.

scripts: Enable save button on script creation

---

addOns/spider/CHANGELOG.md
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderTask.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/SpiderTaskUnitTest.java

Ensure issues in one parser don't break the whole parsing process.
Related to #5274.

spider: handle parsers' exceptions

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionDetectionScanRule.java

Use already available core code as the add-on is already targeting newer core version.

authhelper: use newer core code

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/VerificationData.java

Use already available core code as the add-on is already targeting newer core version.

automation: use newer core code

---

addOns/wappalyzer/CHANGELOG.md

Move previous change to the Unreleased section, as it happened a release in the meantime.

wappalyzer: correct changelog entry

---

addOns/spider/CHANGELOG.md
addOns/spider/src/main/java/org/zaproxy/addon/spider/automation/SpiderJob.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/automation/SpiderJobUnitTest.java

- SpiderJob > Tweak handling to ignore case.
- SpiderJobUnitTest > Tweak test to use enum.
- SpiderJobDialog > Changed to use the enum values.
- spider.gradle.kts > Tweaked to exclude the automation sub-package from japicmp.
Per: https://groups.google.com/g/zaproxy-users/c/zhQCsrBlh5g

spider: Change param Enum automation handling to be more forgiving

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java

- SqlInjectionScanRule > Add simple generic error message to MySQL grouping.
As discussed on IRC.

ascanrules: Add generic MySQL/ MariaDB error message

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportDialog.java
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportHelper.java
addOns/reports/src/main/zapHomeFiles/reports/risk-confidence-html/report.html
addOns/reports/src/main/zapHomeFiles/reports/traditional-pdf/report.html
addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java

Now fixes the pdf issues, hopefully!
Fixes https://github.com/zaproxy/zaproxy/issues/8330

reports: fix illegal chrs in pdf reports

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ExtensionGraphQl.java
addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/contents/alerts.html

Added alert links to website help pages.
zaproxy/zaproxy#8189

graphql: add help link to alert page

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/InlineInjector.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/VariantGraphQl.java
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/InlineInjectorUnitTest.java
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/VariantGraphQIUnitTest.java

The Graphql variant wasn't changing the request when the Graphql query was on the URL. It was also not escaping the parameter values when inserted.
Thanks

graphql: Fix parameter injection in url query

---

addOns/graphql/src/test/java/org/zaproxy/addon/graphql/InlineInjectorUnitTest.java
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/VariantGraphQIUnitTest.java

Correct `Payload`.
From review in #5248.

graphql: fix var name typo in tests

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/automation/actions/RunScriptAction.java
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/automation/ScriptJobUnitTest.java

Check if the script run caused an exception in which case propagate it as an AF error.
---
From ZAP User Group: https://groups.google.com/g/zaproxy-users/c/Bogc-vpH8fc

scripts: propagate script errors to AF

---

addOns/accessControl/CHANGELOG.md
addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/view/AccessControlScanOptionsDialog.java
addOns/accessControl/src/main/java/org/zaproxy/zap/extension/accessControl/view/AccessControlStatusPanel.java
addOns/accessControl/src/main/resources/org/zaproxy/zap/extension/accessControl/resources/Messages.properties

- AccessControlScanOptionsDialog > No longer padding, which simply seemed to be unused space. The user selection table could maybe use a tweak in the future, but still this is better than before.
- AccessControlStatusPanel > Now uses a HistoryReferencesTable instead of a default JXTable so that the standard history  reference container context menus apply. No longer statically assigning the font for the panel/table.
- CHANGELOG > Added notes.
- Messages.properties > Title capped some UI strings.
- zaproxy/zaproxy#2000
- zaproxy/zaproxy#8356

accessControl: Various tweaks or enhancements

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/IntegerOverflowScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/RelativePathConfusionScanRule.java
addOns/ascanrulesBeta/src/main/resources/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/IntegerOverflowScanRuleUnitTest.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/RelativePathConfusionScanRuleUnitTest.java

- Scan rules > Add example alert functionality (6119).
- Unit tests > Assert the new example alerts.
- Messages.properties > Updated some http references (8262).
- zaproxy/zaproxy#8262

ascanrulesBeta: Add more example alerts

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/RemoteCodeExecutionCve20121823ScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ServerSideIncludeScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureCve20121823ScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/RemoteCodeExecutionCve20121823ScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/ServerSideIncludeScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureCve20121823ScanRuleUnitTest.java

- Scan rules > Add example alert functionality (6119).
- Unit tests > Assert the new example alerts.

ascanrules: Add more example alerts

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/GetForPostScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/GetForPostScanRuleUnitTest.java

Changed GetForPost scan rule to use ComparableResponse. Part of zaproxy/zaproxy#7116
https://github.com/zaproxy/zaproxy/issues/7116

ascanrules : GetForPostScanRule use ComparableResponse

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/zapHomeFiles/reports/modern/report.html
addOns/reports/src/main/zapHomeFiles/reports/risk-confidence-html/report.html
addOns/reports/src/main/zapHomeFiles/reports/traditional-html-plus/report.html
addOns/reports/src/main/zapHomeFiles/reports/traditional-json-plus/report.json
addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java

Do not try to use the HTTP message if it's not present in the alert.
Part of zaproxy/zaproxy#6880.

reports: handle alerts without HTTP message

---

addOns/retire/CHANGELOG.md
addOns/retire/src/main/java/org/zaproxy/addon/retire/model/Repo.java
addOns/retire/src/test/java/org/zaproxy/addon/retire/RetireScanRuleUnitTest.java
addOns/retire/src/test/resources/org/zaproxy/addon/retire/testrepository.json

- Repo > Add pre-check for good version candidates when checking version vulnerability.
- RetireScanRuleUnitTest > Add methods to assert the fixed behavior.
- testrepository.json > Add relevant entries to support tests.
- Fixes zaproxy/zaproxy#8384
- Fixes zaproxy/zaproxy#8398

retire: Address False Positives

---

addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java

Mock the `Model` to not create/use a ZAP home which was clashing with other tests and failing.
Reenable previously disabled test.

domxss: change tests to not use a ZAP home

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/zapHomeFiles/reports/traditional-pdf/report.html
addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java

As per title.
Fixes https://github.com/zaproxy/zaproxy/issues/8330

Fix more issues with illegal chrs in pdf reports

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/automation/actions/RunScriptAction.java
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/automation/ScriptJobUnitTest.java

Report an error instead of trying to run an unsupported script type through the Automation Framework.
---
From ZAP User Group: https://groups.google.com/g/zaproxy-users/c/LoWFDfhIzh8/m/8gHOHN0SAQAJ

scripts: error on unsupported script type in AF

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationEnvironment.java
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationEnvironmentUnitTest.java

Replace the vars until there are no vars in the string, to allow to use vars composed with other vars.
---
From zaproxy IRC channel.

automation: replace vars recursively

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ZapItScan.java
addOns/selenium/CHANGELOG.md
addOns/selenium/selenium.gradle.kts

Use latest major version of HtmlUnit and the driver.
Change quickstart to use core constants instead of HtmlUnit ones.

selenium: update HtmlUnit to 3.x

---

addOns/postman/CHANGELOG.md
addOns/postman/src/main/java/org/zaproxy/addon/postman/PostmanParser.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/deserializers/ListItemDeserializer.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/AbstractItem.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/ItemGroup.java
addOns/postman/src/main/java/org/zaproxy/addon/postman/models/PostmanCollection.java
addOns/postman/src/test/java/org/zaproxy/addon/postman/ListDeserializerUnitTest.java
addOns/postman/src/test/java/org/zaproxy/addon/postman/PostmanParserUnitTest.java

Deserialize taking into account the presence of the item field, which indicates an item group rather than an item.
Move the check for no items imported to after the import is concluded, to ensure it's only reported once.
Fix zaproxy/zaproxy#8400.

postman: correct deserialization of item groups

---

addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/internal/ScanRulesInfo.java

Use the extension instead of other core classes, which should be considered internal and thus subject to changes.

alertFilters: use pscan extension to gather data

---

addOns/scripts/CHANGELOG.md
addOns/scripts/scripts.gradle.kts
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/scanrules/PassiveScriptSynchronizer.java

Passive scripts exposed as scan rules were not being removed reliably (e.g. commenting out the metadata function in one passive script ended up removing another).
This was happening because `ExtensionPassiveScan` in core relies on the class name of the passive scan rule to remove it, and all passive scripts exposed as scan rules have the same class name.
This PR uses [Byte Buddy](https://bytebuddy.net), a library that allows creating Java classes at runtime, to expose scripts as passive scan rules with classes that have unique names.
This is temporary until we update `ExtensionPassiveScan` to not use the scan rule name (and maybe use the ID like in
`PluginFactory#unloadedPlugin`?) to remove passive scan rules.

scripts: Fix removal of passive scan rules

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationAPI.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationAPIUnitTest.java

Change what/how the data is returned to include all and only the necessary information for all response formats.
Fix zaproxy/zaproxy#8433.

automation: fix `planProgress` API view response

---

addOns/sse/CHANGELOG.md
addOns/sse/src/main/java/org/zaproxy/zap/extension/sse/EventStreamProxy.java
addOns/sse/src/test/java/org/zaproxy/zap/extension/sse/EventStreamProxyUnitTest.java

When an SSE packet has an empty "id" field, the addon stops processing.
Handles the case where an SSE packet has an empty "id" followed by "event" field. Enables addOn to further process packets instead of stopping with an exception.
https://github.com/zaproxy/zaproxy/issues/8320

sse: Graceful handling of empty "id"-field in sse add-on

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/AttackPanel.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/AttackThread.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/PlugableSpider.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/QuickStartParam.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ajaxspider/AjaxSpiderExplorer.java
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ajaxspider/ExtensionQuickStartAjaxSpider.java
addOns/quickstart/src/main/javahelp/org/zaproxy/zap/extension/quickstart/resources/help/contents/quickstart.html
addOns/quickstart/src/main/resources/org/zaproxy/zap/extension/quickstart/resources/Messages.properties

Add an option to the Quick Start panel to only run the AJAX Spider if the app is modern - this is the new default, as its probably the most useful option.
Related PR: https://github.com/zaproxy/zaproxy/pull/8454 (but not a dependency)

QuickStart: support AJAX "if modern" option

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/scanrules/ActiveScriptHelper.java

Expose the method `setEscapedParameter(...)` to the scripts so it's possible to set raw values, like it's possible from Java active scan rules.

scripts: allow to set raw value from Active Rules

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerJsonParser.java

- WappalyzerJsonParser > Access SVGPaint prior to parallel loading of the patterns/icons, to hopefully address class contention.
- ExtensionWappalyzer > Suppress further unhelpful logging from jsvg.
Fixes zaproxy/zaproxy#8464

wappalyzer: Address class contention issue

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/scanrules/ScanRuleMetadata.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/scanrules/ScanRuleMetadataUnitTest.java
addOns/scripts/CHANGELOG.md
addOns/scripts/scripts.gradle.kts
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/scanrules/ActiveScriptScanRule.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/scanrules/PassiveScriptScanRule.java

Support for code and help links for script scan rules
https://github.com/zaproxy/community-scripts/pull/442

Scripts: Support for code and help links for script scan rules

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/api.html
addOns/wappalyzer/wappalyzer.gradle.kts

As discussed via email.
- api.html > Tweak naming.
- wappalyzer.gradle.kts > Tweak nameing.
N/A

wappalyzer: Maint - Standardize on naming

---

addOns/replacer/CHANGELOG.md
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/ReplacerParam.java
addOns/replacer/src/test/java/org/zaproxy/zap/extension/replacer/ReplacerParamUnitTest.java

- CHANGELOG > Added change note
- ReplacerParam > Added new default rules (disabled by default).
- ReplacerParamUnitTest > Tweaked to accommodate these additional changes.
zaproxy/zaproxy#8437

replacer: Add cache prevention rules

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/commonlib.gradle.kts
addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts

Exclude Jackson from openapi and rely on commonlib to prevent class loading issues.
Add Jackson Datatype: JSR310 to commonlib for openapi to use.

openapi: rely on commonlib for Jackson library

---

addOns/grpc/grpc.gradle.kts

Let it use the default defined by the build.

grpc: remove ZAP version override

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java

Remove usage of reflection and use the core code directly now that it is available.
Correct name of a parameter in JavaDoc.

network: use latest core code

---

addOns/database/CHANGELOG.md
addOns/database/database.gradle.kts
addOns/database/src/main/java/org/zaproxy/addon/database/ExtensionDatabase.java
addOns/database/src/main/resources/org/zaproxy/addon/database/resources/Messages.properties
addOns/database/src/test/java/org/zaproxy/addon/database/ExtensionDatabaseUnitTest.java

Update dependencies to latest versions (that still are Java 11 compatible).
Suppress Flyway warning that HSQLDB is not yet officially supported, there's nothing that can be done.

database: update deps and suppress Flyway warn

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AuthenticationData.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AuthenticationDataUnitTest.java

Set an empty realm instead, as null is not allowed and would break the authentication.
Related to zaproxy/zaproxy#8498.

automation: do not use null auth realm

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpStateCredentialsProvider.java

Check that the user actually has an auth state before trying to use it, which could happen if the auth attempt lead to an error.
Related to zaproxy/zaproxy#8498.

network: guard against user without auth state

---

addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/SeleniumOptions.java

Do not check if the WebDriver is a bundled one to ensure all specified WebDriver are executable.

selenium: ensure WebDriver is executable always

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java

Check that the main proxy was already initialised before checking if it is started as it might not have been, e.g. when starting ZAP with the root CA cert expired the options might be shown before initialising the proxies.
Fix zaproxy/zaproxy#8499.

network: fix NPE after root CA cert regen

---

addOns/graaljs/CHANGELOG.md
addOns/graaljs/src/main/javahelp/help/contents/graaljs.html
addOns/groovy/CHANGELOG.md
addOns/groovy/src/main/javahelp/org/zaproxy/zap/extension/groovy/resources/help/contents/intro.html
addOns/jruby/CHANGELOG.md
addOns/jruby/src/main/javahelp/org/zaproxy/zap/extension/jruby/resources/help/contents/jruby.html
addOns/jython/CHANGELOG.md
addOns/jython/src/main/javahelp/org/zaproxy/zap/extension/jython/resources/help/contents/jython.html
addOns/kotlin/CHANGELOG.md
addOns/kotlin/src/main/javahelp/org/zaproxy/addon/kotlin/resources/help/contents/kotlin.html
addOns/zest/CHANGELOG.md
addOns/zest/src/main/javahelp/org/zaproxy/zap/extension/zest/resources/help/contents/zest.html

Mention the name of the engines so the user can easily know them when manually/programmatically configuring ZAP.

Document script engine names in the help pages

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SstiBlindScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SstiScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SstiBlindScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SstiScanRuleUnitTest.java

- Scan rules > Add example alert functionality (6119), add appropriate alert tags.
- Unit tests > Assert the new example alerts, and mappings.

ascanrules: Add SSTI example alerts

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/RelativePathConfusionScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/RelativePathConfusionScanRuleUnitTest.java

Fixed wrong regex which detected absolute URLs as relative.
Current implementation detects styles like `background: url(https://abc.com/abc.png)` as relative url and vulnerable.
MR tested on regex101.com:
none

ascanrulesBeta: Fixed regex for relative path confusion, which detected absolute url as relative

---

addOns/webuipoc/webuipoc.gradle.kts

Ensure automated changes (e.g. #5524) do no lead to unwanted changes in the lock file and that it's kept in sync.

webuipoc: use `ci` instead of `install`

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CommandInjectionScanRuleUnitTest.java

- CHANGELOG  > Added fix note.
- Messages.properties > Updated various resource messages.
- CommandInjectionScanRuleUnitTest - Updated to match the new content.
---
* Removed use of period space space (should always be period space between sentences now).
* Removed trailing spaces.
* Added periods.
Reported via Slack.

ascanrules: Various alert text fixes (periods and whitespace(s))

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/scanrules/ActiveScriptScanRule.java
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/scanrules/PassiveScriptScanRule.java
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/scanrules/ActiveScriptScanRuleUnitTest.java
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/scanrules/PassiveScriptScanRuleUnitTest.java

Scripts without `references` in their metadata were failing with NPEs.

scripts: Handle null references in metadata

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/PolyfillCdnScriptScanRule.java
addOns/pscanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/pscanrulesBeta/resources/help/contents/pscanbeta.html
addOns/pscanrulesBeta/src/main/resources/org/zaproxy/zap/extension/pscanrulesBeta/resources/Messages.properties
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/PolyfillCdnScriptScanRuleUnitTest.java

Pscanbeta - add polyfill.io scan rule

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/resources/org/zaproxy/zap/extension/quickstart/resources/Messages.properties

Per:
- https://www.zaproxy.org/addons/
- https://www.zaproxy.org/docs/desktop/addons/technology-detection/

quickstart: Update Tech Detection terminology

---

addOns/spider/CHANGELOG.md
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderParam.java

Update to mention the newer option instead of the older option and linking to deprecated class.

spider: update JavaDoc

---

addOns/requester/CHANGELOG.md
addOns/requester/src/main/java/org/zaproxy/addon/requester/ExtensionRequester.java
addOns/requester/src/main/java/org/zaproxy/addon/requester/MessageEditorDialog.java
addOns/requester/src/main/java/org/zaproxy/addon/requester/internal/SendHttpMessageEditorDialog.java

Add method to the extension to display a message and show the dialogue.
---
From ZAP User Group: https://groups.google.com/g/zaproxy-users/c/p7EcrHg-LxY/m/HQIsF7_RAAAJ

requester: allow to display a msg in the editor

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestZapRunner.java
addOns/zest/zest.gradle.kts

Update Zest library and change the `ZestZapRunner` to provide the script engines that ZAP has so the scripts are executed with same configurations as scripts executed directly from ZAP.

zest: use script engines from ZAP

---

addOns/grpc/CHANGELOG.md
addOns/grpc/grpc.gradle.kts
addOns/grpc/src/main/java/org/zaproxy/addon/grpc/internal/VariantGrpc.java
addOns/grpc/src/test/java/org/zaproxy/addon/grpc/internal/VariantGrpcUnitTest.java

Check that the response is valid gRPC before trying to decode it, otherwise it would lead to unnecessary warns as the response is not gRPC.

grpc: skip non-gRPC responses in the variant

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java

Fix import openapi definitions from files. It fails with big files.
https://github.com/zaproxy/zaproxy/issues/8193

openapi: workaround issue importing fully resolved definitions

---

addOns/pscan/CHANGELOG.md
addOns/pscan/src/main/java/org/zaproxy/addon/pscan/ExtensionPassiveScan2.java
addOns/pscan/src/main/java/org/zaproxy/addon/pscan/internal/AddOnScanRulesLoader.java

Migrate core code that loads the add-on scan rules.

pscan: un/load add-on scan rules

---

addOns/kotlin/src/test/java/org/zaproxy/addon/kotlin/ClassLoaderTests.java

Use non-deprecated way of getting the `URL`.

kotlin: address warn with Java 21+ in tests

---

addOns/pscan/CHANGELOG.md
addOns/pscan/src/main/java/org/zaproxy/addon/pscan/ExtensionPassiveScan2.java
addOns/pscan/src/main/java/org/zaproxy/addon/pscan/internal/DefaultStatsListener.java
addOns/pscan/src/main/resources/org/zaproxy/addon/pscan/resources/Messages.properties

Add the scan status label to show the number of queued messages.

pscan: add status scan label

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/UrlPresenceTestDialog.java

- CHANGELOG > Added maint note.
- ExtensionAutomation > Adjust URL/URI handling.
- UrlPresenceTestDialog > Adjust URL/URI handling.
As far as I could see from the related JavaDoc, the same exceptions should still be thrown (if there's an issue) with the updated code.
```bash
> Task :addOns:automation:compileJava
C:\Users\thorin\Desktop\zap-ws\zap-extensions\addOns\automation\src\main\java\org\zaproxy\addon\automation\ExtensionAutomation.java:681: warning: [deprecation] URL(String) in URL has been deprecated
new URL(source).toURI();
^
error: warnings found and -Werror specified
> Task :addOns:wappalyzer:jhindexer-help_ja_JP
> Task :addOns:automation:compileJava FAILED
C:\Users\thorin\Desktop\zap-ws\zap-extensions\addOns\automation\src\main\java\org\zaproxy\addon\automation\gui\UrlPresenceTe …
```

automation: Address warnings/errors when building with java 21

---

addOns/domxss/CHANGELOG.md
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java

Include the whole HTTP message when raising the alerts.

domxss: include response in raised alerts

---

addOns/paramdigger/CHANGELOG.md
addOns/paramdigger/src/main/java/org/zaproxy/addon/paramdigger/CacheController.java
addOns/paramdigger/src/main/java/org/zaproxy/addon/paramdigger/ExtensionParamDigger.java
addOns/paramdigger/src/main/java/org/zaproxy/addon/paramdigger/HeaderGuesser.java

- CacheController > Remove unnecessary else block and conditional handling. (Mentioned in https://github.com/zaproxy/zap-extensions/pull/4561/files)
- ExtensionParamDigger > Add and use SessionChangedListener.
- HeaderGuesser > Make constant final. (Mentioned in https://github.com/zaproxy/zap-extensions/pull/4561/files)
- zaproxy/zaproxy#7694
- zaproxy/zap-extensions#4561

paramdigger: Handle session change & previous PR follow-up

---

addOns/exim/CHANGELOG.md
addOns/exim/exim.gradle.kts

- Leverage Jackson library from the Common Library add-on.

exim: Leverage Jackson from common-lib

---

addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestDirectory.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestProxyServer.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonCookie/SimpleJsonCookieDir.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonCookie/SimpleJsonCookieIndexPage.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonCookie/SimpleJsonCookieProtectedPage.java
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json-cookie/home.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json-cookie/page2.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json-cookie/page3.html

Requests to 'folders' without a trailing slash messed up relate links, so not redirect them to the same URL but with a slash.
Also added a couple more protected pages for testing spiders.

Dev: fix folder reqs and add extra protected pages

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodType.java

Fix potential timing issue trying to use browser based auth authenticate before the autodetect session management method has been identified.

Authhelper: fix potential timing issue with browser based auth

---

addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AddTestDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PassiveScanWaitJob.java

Allow the job itself to tell if it supports or not alert tests to remove direct dependencies to jobs in implementations.

automation: let job report alert tests support

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationEnvironment.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/EnvironmentDialog.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/environment.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/env-max.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/env-min.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-config.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testplan-continueonerror.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/testplan-continueonwarning.yaml

Add a new env parameter: continueOnFailure.
By default this is false, but if set means that jobs will keep running even if an earlier job fails.
A key usecase for this is collecting suitable diagnostics if an integration test fails.

Auto: Added env/continueOnFailure

---

addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PassiveScanWaitJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/tests/AutomationAlertTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationJobUnitTest.java

Use the information from the job when checking for alert tests.

automation: replace hardcoded checks

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureFileInclusionScanRule.java
addOns/ascanrulesBeta/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesBeta/resources/help/contents/ascanbeta.html
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureFileInclusionScanRuleUnitTest.java

- SourceCodeDisclosureFileInclusionScanRule > Adjusted behavior.
- SourceCodeDisclosureFileInclusionScanRule > Added tests to assert the expected behaviors.
- ascanrulesBeta.html > Added details on the error conditions skip.
- Fixes zaproxy/zaproxy#8517

ascanrulesBeta: Fix Source Code Disclosure File Inc. False Positives

---

addOns/domxss/CHANGELOG.md
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java

Correct values used for the evidence that the expected alert message was shown.

domxss: address FNs through query parameter

---

addOns/alertFilters/CHANGELOG.md
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java

Skip the notified alert if it was already deleted instead of letting the NPE happen.
Also, remove compatibility code with older ZAP versions.

alertFilters: handle deleted alerts

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/AttackPanel.java

Use other model before changing the URL of the Automated Scan panel to ensure the Mode's info message is not shown/used as a URL in the Manual Explore panel.
Fix zaproxy/zaproxy#8591.

quickstart: correct Mode handling in URL field

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ExpressionLanguageInjectionScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SlackerCookieScanRule.java
addOns/ascanrulesBeta/src/main/resources/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/ExpressionLanguageInjectionScanRuleUnitTest.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/SlackerCookieScanRuleUnitTest.java

- Scan rules > Add example alert functionality (6119).
- Unit tests > Assert the new example alerts.

ascanrulesBeta: More example alerts

---

addOns/ascanrulesAlpha/CHANGELOG.md
addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRule.java
addOns/ascanrulesAlpha/src/main/javahelp/org/zaproxy/zap/extension/ascanrulesAlpha/resources/help/contents/ascanalpha.html
addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/LdapInjectionScanRuleUnitTest.java

- LdapInjectionScanRule > Adjust behavior, return early if original was client or server error.
- LdapInjectionScanRuleUnitTest > Test/ssert the new behavior.
- ascanslpha.html > Noted the updated behavior.
- Fixes zaproxy/zaproxy#8519

ascanrulesAlpha: Be More defensive for LDAPi False Positives

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionDetectionScanRule.java

Use the raise method from the `PluginPassiveScanner.AlertBuilder` instead of raising the alert through the task helper class to not directly depend on it.

authhelper: replace direct task helper usage

---

addOns/webuipoc/src/main/java/org/zaproxy/addon/webuipoc/TestProxyServer.java

Check for `/OTHER/` to include other API endpoints.

webuipoc: handle other endpoints

---

addOns/retire/CHANGELOG.md
addOns/retire/retire.gradle.kts

The current description on Retire.js as seen in the update add-ons dialog is unhelpful:

retire: improve add-on description

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/AppPattern.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ApplicationMatch.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechOptionsPanel.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerParam.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/WappalyzerPassiveScanner.java
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/options.html
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/index.xml
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/map.jhm
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/toc.xml
addOns/wappalyzer/src/main/resources/org/zaproxy/zap/extension/wappalyzer/resources/Messages.properties
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/JsonParserUnitTest.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/PassiveScannerUnitTest.java
addOns/wappalyzer/src/test/resources/org/zaproxy/zap/extension/wappalyzer/apps.json
addOns/wappalyzer/src/test/resources/org/zaproxy/zap/extension/wappalyzer/categories.json

<details>
<summary>Screenshots</summary>
</details>
- Help > Updated help components to accommodate a separate Options page.
- TechOptionsPanel > Now include help index (balloon button).
- WappalyzerPassiveScanner > Add support for adding alerts. Reduce processing by synchronizing details in a Map. Updated cookie and header handling to address possible FP/FN situations.
- WappalyzerParam - Add handling for raise alerts option.
- PassiveScannerUnitTest > Updated to test and handle new behavior. Created nested class to to assert alert handling behavior.
- Test resource categories.json > Added missing categories to make unit tests less 'chatty'.
- ApplicationMatch > Updated to track evidence.
- AppPattern > Updated to set evidence.
- ExtensionWappalyzer > …

tech detection: Allow raising alerts

---

.github/workflows/cla.yml

- 2.5.1 which uses node 20 vs node 16
Ref: https://github.com/search?q=org%3Azaproxy+contributor-assistant%2Fgithub-action%40v2.3.0&type=code
Ref: https://github.com/contributor-assistant/github-action/issues/149

Update CLA Assistant

---

addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/resources/org/zaproxy/zap/extension/selenium/resources/Messages.properties

Add a link to the "no-browser" FAQ in related warning messages.
https://github.com/zaproxy/zaproxy-website/pull/2768

Selenium: add no-browser link to warnings

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CacheControlScanRuleUnitTest.java

This PR is to update the current CacheControlScanRule to ignore the cache-control requirement for POST method.
Fixes https://github.com/zaproxy/zaproxy/issues/8592

pscanrules: ignore cache-control for POST method

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechPassiveScanner.java
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/options.html
addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/PassiveScannerUnitTest.java

- ExtensionWappalyzer > Implements ExampleAlertProvider, and calls to the passive scan rule to get the details.
- TechPassiveScanner > Adjusted alert creation, added example alert method, added help link method.
- PassiveScannerUnitTest > Added tests for example alerts and help link.
- options.html > Updated to facilitate help link.
- wappalyzer.html > Update WappalyzerJobResultData reference to TechJobResultData. (Follow-up to zaproxy/zap-extensions#5651)
N/A

tech detection: Example alerts

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionDetectionScanRule.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/SessionDetectionScanRuleUnitTest.java

The problem was that we were deleting the session tokens from our cache once we had found them once.
But session tokens get reused a lot, of course, so we kept on searching through the old history records because we had taken them out of the cache - doh!
Who wrote this code??
Oh, I did ;)
Also removed the stats per token as we're getting so many they are useless, instead added a stat for the max tokens cached.

Auth Helper: fix session detection performance issue

---

addOns/callhome/CHANGELOG.md
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java
addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechPassiveScanner.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/TechPassiveScannerUnitTest.java

Add request stats to the tech add-on so that we can tell if its worth limiting the number of URLs it analyses in order to speed it up.
Note that the change to `getSite(msg)` is so that it is compatible with the site based stats.

Tech: Added request stats

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/CookieUtils.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/CookieUtilsUnitTest.java

Consider cookies without name value pair separator as cookies without name, as that's how Chrome and Firefox handle them and also being proposed in rfc6265bis, addressing false positives/negatives when checking for cookie attributes of those cookies.
Fix zaproxy/zaproxy#8613.

commonlib: change handling of cookie without name

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/ContextDialog.java

The GUI can NPE if tech not specified.
At test:
1. Create an AF plan with no tech in the env - this is allowed as its optional
2. Open the plan in the GUI
3. Open the env, then the context
4. Save the context
Without this fix it will NPE

Automation: Fix GUI NPE if tech not specified.

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/gradle.properties
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java

Put back the stats removed by the related PR - they were used in our integration tests.
If other people use them then they would break their tests too.
https://github.com/zaproxy/zaproxy/actions/runs/10659233723
https://github.com/zaproxy/zap-extensions/pull/5672

Authhelper: Restore stats

---

addOns/spider/CHANGELOG.md
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderTask.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/ParseContext.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/ParseContextUnitTest.java

Allow the parsers to obtain the user being used by/in the current spidering scan.
Related to zaproxy/zaproxy#7739.

spider: expose the user to the parsers

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJobDialog.java

Allow to select the contexts of the plan not the ones present in the session.

openapi: correct contexts shown in job dialogue

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJob.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJobDialog.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJobUnitTest.java

Use the default context when the context name is empty.

openapi: fix context handling in AF job

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechPassiveScanner.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/TechPassiveScannerUnitTest.java

As discussed via Slack after: https://github.com/zaproxy/zaproxy-website/pull/2785
- TechPassiveScanner > Use fake app details, and rule name (vs. specific tech).
- TechPassiveScannerUnitTest > Assert details for the example alert.
- zaproxy/zaproxy-website#2779
- zaproxy/zap-extensions#5668
- zaproxy/zap-extensions#5686

tech detection: Adjust example alert

---

addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ImportDialog.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/OpenApiAPI.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJob.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJobDialog.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/network/Requestor.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/spider/OpenApiSpider.java
addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/contents/automation.html
addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/contents/openapi.html
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/Messages.properties
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/openapi-max.yaml
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/OpenApiAPIUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJobUnitTest.java

Allow to import as user through the spider, API, GUI, and AF.
Fix zaproxy/zaproxy#7739.

openapi: allow to import as a user

---

addOns/oast/CHANGELOG.md
addOns/oast/src/main/java/org/zaproxy/addon/oast/services/boast/BoastEntity.java

Declare the `BoastEntity` detachable as it is used that way (and is the current default), addressing warnings like:
`WARN Persistence - Object with id "BoastEntity" is to be detached...`

oast: make boast entity detachable

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/OutOfBandXssScanRule.java

Allow to know what went wrong when using the Out of Band XSS scan rule.

ascanrulesBeta: include exception in log message

---

addOns/spider/CHANGELOG.md
addOns/spider/src/main/java/org/zaproxy/addon/spider/Spider.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderTask.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/parser/ParseContext.java
addOns/spider/src/test/java/org/zaproxy/addon/spider/parser/ParseContextUnitTest.java

Allow the parsers to obtain the context being used by/in the current spidering scan.
Part of zaproxy/zaproxy#8021.

spider: expose the context to the parsers

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/Converter.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverter.java
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/spider/OpenApiSpider.java
addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/contents/openapi.html
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/converter/swagger/SwaggerConverterUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v1/OpenApiUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v2/OpenApiPrimitivesInBodyUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v2/OpenApiUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiDefaultValuesTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiEnumsUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiExternalRefsUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiGeneratedCookieValuesTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiPrimitivesInBodyUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiUnitTest.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/v3/OpenApiValueGeneratorFormatsTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/converter/swagger/openapi_paths_misc.yaml

Do not import endpoints excluded by the provided context.
Part of zaproxy/zaproxy#8021.

openapi: honour context exclusions

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/HashDisclosureScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/HashDisclosureScanRuleUnitTest.java

- HashDisclosureScanRule > Adjust pattern's name, risk, and confidence.
- HashDisclosureScanRuleUnitTest > Adjust assertions related to this pattern/alert.
- pscanrules.html > Added help note outlining the confidence/threshold association under which patterns are evaluated.
Fixes zaproxy/zaproxy#8624
Other ref: https://github.com/s0md3v/Bolt/blob/37aa096db93e026f0524fe94c67dc1dae8985f3e/db/hashes.json#L291-L299

pscanrules: Adjust Mac OSX Salted SHA-1 name, risk, and confidence

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SstiBlindScanRule.java
addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ServerCertificatesOptionsPanel.java
addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/SubResourceIntegrityAttributeScanRule.java

Fix typos in `occurred` and `formatted`.
Follow up to zaproxy/zaproxy#8623.

Fix typos in log messages and JavaDoc

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InsecureJsfViewStatePassiveScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InsecureJsfViewStatePassiveScanRuleUnitTest.java

Me and [Lucas Bergholz](https://github.com/zaproxy/zap-extensions/pull/github.com/lucasbergholz) worked on this together, with the porpuse of adding the alert for Insecure JSF ViewState - P. We are open for any feedbacks of our work, as this is our first contribution on this issue.
Part of zaproxy/zaproxy#6119.

pscanrules: add examples alerts to Insecure JSF ViewState

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SpringActuatorScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SpringActuatorScanRuleUnitTest.java

Me and [Lucas Bergholz](github.com/lucasbergholz) worked on this together, with the porpuse of adding the alert for SpringActuatorScanRule. We are open for any feedbacks of our work, as this is our first contribution on this issue.
Part of zaproxy/zaproxy#6119.

ascanrules: add example alerts to Spring Actuator

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderContextApache.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

This is fix for when ZAP is stuck waiting to retry requests after receiving a response with the `retry-after` header set. See https://github.com/zaproxy/zaproxy/issues/8627
Fix zaproxy/zaproxy#8627.

network: do not retry on 429 and 503

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureCve20121823ScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SourceCodeDisclosureCve20121823ScanRuleUnitTest.java

Do not scan binary responses and responses that already contain PHP source.
Fix zaproxy/zaproxy#8638.

ascanrules: address FPs in scan rule 20017

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ShellShockScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/ShellShockScanRuleUnitTest.java

Use the `TimingUtils` for the time-based scan which provides more accurate verification.
Fix zaproxy/zaproxy#8516.

ascanrulesBeta: address FP in scan rule 10048

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java
addOns/ascanrules/src/test/resources/org/zaproxy/zap/extension/ascanrules/crosssitescriptingscanrule/InputInsideInputAndDiv.html
addOns/ascanrules/src/test/resources/org/zaproxy/zap/extension/ascanrules/crosssitescriptingscanrule/InputInsideInputAndScript.html

These occur when the payload is reflected in more than one HTML context.
Fix the XSS rule so that it handles payloads reflected (and correctly escaped) in more than one element.
Fixes https://github.com/zaproxy/zaproxy/issues/8640

ascanrules: Fix XSS False positives

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/httputils/HtmlContext.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java
addOns/ascanrules/src/test/resources/org/zaproxy/zap/extension/ascanrules/crosssitescriptingscanrule/InputInScriptSrc.html

I dont think a changelog entry is required as this is a knock on from the last change.
Fix a FN in the Firing Range tests.
Also fixed a set of bugs in the context testing logic.
It worked fine if only one flag supplied (which is what we were doing) but failed when I needed to specify more than one flag.
https://github.com/zaproxy/zap-extensions/pull/5745

ascanrules: Fix FR false negative in XSS

---

addOns/openapi/src/main/javahelp/org/zaproxy/zap/extension/openapi/resources/help/contents/automation.html
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/openapi-max.yaml
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/openapi-min.yaml

Indicate that the AF job uses the first context by default (#5703).

openapi: update docs to match latest behaviour

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ExtensionZest.java
addOns/zest/src/test/java/org/zaproxy/zap/extension/zest/ExtensionZestUnitTest.java

Swap the operands to ensure the equality check does not fail even when the script engine name is null.
---
Mentioned in IRC, e.g.:
```
ZAP-BootstrapGUI] ERROR ExtensionScript - Error while notifying 'org.zaproxy.zap.extension.zest.ExtensionZest' with script 'Base64 Disclosure', cause: Cannot invoke "String.equals(Object)" because the return value of "org.zaproxy.zap.extension.script.ScriptWrapper.getEngineName()" is null
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.zaproxy.zap.extension.script.ScriptWrapper.getEngineName()" is null
at org.zaproxy.zap.extension.zest.ExtensionZest.scriptAdded(ExtensionZest.java:1769) ~[?:?]
at org.zaproxy.zap.extension.script.ExtensionScript.addScript(ExtensionScript.java:711) …
```

zest: fix NPE with added script

---

addOns/client/src/test/java/org/zaproxy/addon/client/ExtensionClientIntegrationUnitTest.java

The test could fail because of concurrency issue, leading to NPE.
Also, reorder the assertion's arguments to match the expected order.
e.g.:
```
> Task :addOns:client:test
ExtensionClientIntegrationUnitTest > shouldStartSpider() FAILED
java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.quit()" because "wd" is null
at org.zaproxy.addon.client.spider.ClientSpider.finished(ClientSpider.java:274)
at org.zaproxy.addon.client.spider.ClientSpider.stop(ClientSpider.java:222)
at org.zaproxy.addon.client.ExtensionClientIntegrationUnitTest.shouldStartSpider(ExtensionClientIntegrationUnitTest.java:142)
```

client: address a test failure

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/XxeScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/XxeScanRuleUnitTest.java

- Scan Rule > Added example alert handling.
- Unit Test > Added tests for the example alerts and references.

ascanrules: XXE example alerts

---

addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/PolyfillCdnScriptScanRuleUnitTest.java

Reduce failures when the test takes a little more time to run, e.g.:
```
PolyfillCdnScriptScanRuleUnitTest > shouldRunQuickly() FAILED
java.lang.AssertionError:
Expected: a value less than <200L>
but: <249L> was greater than <200L>
```

pscanrules: increase allowed time in a test

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/scanrules/PassiveScriptScanRule.java
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/scanrules/PassiveScriptScanRuleUnitTest.java

Honour the threaded property of the script engine when checking if the scan rule applies to the history type, as it is called concurrently.

scripts: address pscan concurrency issue

---

addOns/exim/CHANGELOG.md
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarImporter.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/har/HarImporterUnitTest.java
addOns/exim/src/test/resources/org/zaproxy/addon/exim/har/oneNullMessage.har

Found a bug when counting null messages when working on PR zaproxy/zap-extensions#5608 .
The counter should also be incremented when a null message is extracted (which happens if there is an exception when parsing the data to make the message),  otherwise if a null gets hit in the end it'll show an incomplete progress bar.
As in the PcapImporter, this fix makes the null message count towards progress and displays `Invalid message` on the progress bar.

exim: HarImporter - make invalid messages count towards progress

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportHelper.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/ReportHelperUnitTest.java

Fixes an issue where alert details were missing from some reports.
Fix zaproxy/zaproxy#8460.

reports: fix missing alert details in Risk and Confidence HTML

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ConsolePanel.java

Catch the exception that's thrown when stopping the thread in newer Java versions to prevent the exception from bubbling up.

scripts: handle exception when stopping script

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestZapUtils.java
addOns/zest/src/test/java/org/zaproxy/zap/extension/zest/ZestZapUtilsUnitTest.java

Remove duplication when converting `HttpMessage` to `ZestRequest` and `ZestResponse`.

zest: deduplicate code

---

addOns/sequence/sequence.gradle.kts
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/ExtensionSequence.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/SequenceAscanPanel.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ExtensionZest.java

The extension is a core component of the functionality and it's already a dependency of the add-on, which also allows to remove usage of reflection.
Replace hardcoded string with respective constant.

sequence: depend on `ExtensionZest`

---

addOns/zest/CHANGELOG.md
addOns/zest/gradle.properties

Allow other add-ons to reliable depend on specific versions.

zest: use semantic version

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationData.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationPlan.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/DefaultPropertyFilter.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/JobData.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/tests/TestData.java
addOns/spiderAjax/src/test/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJobUnitTest.java

In saved YAML plans,
- Fields with default values are omitted
- The "name" and "type" fields are added before other fields
- Values are not quoted unless required
<details>
<summary> <strong>Before / After Comparison (click to expand)</strong> </summary>
<table>
<tr>
<th> Before
<th> After
<tr>
<td>
<pre lang="yaml">
---
env:
contexts:
- name: "Default Context"
urls: []
includePaths: []
excludePaths: []
authentication:
parameters: {}
verification:
method: "response"
pollFrequency: 60
pollUnits: "requests"
sessionManagement:
method: "cookie"
parameters: {}
technology:
exclude: []
structure:
structuralParameters: []
parameters:
failOnError: true
failOnWarning: false
progressToStdout: true
continueOnFailure: false
vars: {}
jobs:
- parameters:
scanOnlyInScope: true
enableTags: false …

automation: Tweak YAML serialization

---

addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestZapUtils.java
addOns/zest/src/test/java/org/zaproxy/zap/extension/zest/ZestZapUtilsUnitTest.java

Validate upfront that the request does have a URI instead of letting a NPE happen later.
Remove some more duplicated code.

zest: validate URI presence on request conversion

---

addOns/domxss/src/test/java/org/zaproxy/zap/extension/domxss/DomXssScanRuleUnitTest.java

Allow one more request to prevent intermittent failures in CI.
e.g.: https://github.com/zaproxy/zap-extensions/actions/runs/11210082508/job/31156346363?pr=5791
```
DomXssScanRuleUnitTest > commonScanRuleTests() > shouldSendReasonableNumberOfMessagesInLowStrength FAILED
java.lang.AssertionError: 
Expected: a collection with size a value less than or equal to <12>
but: collection size <13> was greater than <12>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at org.zaproxy.zap.testutils.ActiveScannerTestUtils.shouldSendReasonableNumberOfMessages(ActiveScannerTestUtils.java:322)
at org.zaproxy.zap.testutils.ActiveScannerTestUtils.lambda$addTestsSendReasonableNumberOfMessages$3(ActiveScannerTestUtils.java:279)
at …
```

domxss: increase allowed requests in the tests

---

addOns/retire/CHANGELOG.md
addOns/retire/src/main/java/org/zaproxy/addon/retire/Result.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/model/Repo.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/model/Vulnerability.java
addOns/retire/src/main/javahelp/org/zaproxy/addon/retire/resources/help/contents/retire.html
addOns/retire/src/test/java/org/zaproxy/addon/retire/RetireScanRuleUnitTest.java
addOns/retire/src/test/java/org/zaproxy/addon/retire/model/VulnerabilityUnitTest.java

- Repo > Updated revising the handling of vulnerability data.
- Result > Updated to accommodate the new vulnerability data handling.
- RetireScanRule > Updated to accommodate the new vulnerability data handling.
- RetireScanRuleUnitTest > Updated assertions to account for the new risk/severity handling.
- Vulnerability > Updated revising the handling of vulnerability data, mapping severity to risk at parse time.
- VulnerabilityUnitTest > Added test to assure proper mapping.
- retire.html > Added details about severity to risk mapping.
Fixes zaproxy/zaproxy#7926

retire: Map severity to risk for Alerts

---

addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarUtils.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/har/HarUtilsUnitTest.java

Add the response body even if it does not have a content-type.

exim: correct export of body with no content type

---

addOns/exim/CHANGELOG.md
addOns/exim/src/main/java/org/zaproxy/addon/exim/Exporter.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/ExporterOptions.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/ExporterResult.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/ExtensionExim.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/automation/ExportJob.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/automation/ExportJobDialog.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/automation/ExtensionEximAutomation.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/automation/ImportJob.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarExporter.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarUtils.java
addOns/exim/src/main/javahelp/help/contents/automation.html
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/Messages.properties
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/export-max.yaml
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/export-min.yaml
addOns/exim/src/test/java/org/zaproxy/addon/exim/ExporterOptionsUnitTest.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/ExporterResultUnitTest.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/ExporterUnitTest.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/ExtensionEximUnitTest.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/automation/ExportJobUnitTest.java

Allow to export messages in HAR and as URLs through the Automation Framework and also programmatically through the extension.

exim: add export AF job

---

addOns/encoder/CHANGELOG.md
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/EncodeDecodeProcessors.java
addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/predefined/utility/Transliterate.java
addOns/encoder/src/main/javahelp/org/zaproxy/addon/encoder/resources/help/contents/encoder.html
addOns/encoder/src/main/resources/org/zaproxy/addon/encoder/resources/Messages.properties
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/predefined/utility/TransliterateUnitTest.java

- CHANGELOG.md > Add note.
- EncodeDecodeProcessors > Register the new processor.
- encoder.html > Add help content and behavior examples. (Update JavaDoc links to version 17 references.)
- Messages.properties > Add key/value pair for the name.
- Transliterate > New encoder.
- TransliterateUnitTest > Unit Test for the new encoder.
n/a

encoder: Add transliteration processor & help JavaDoc link updates

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/export-max.yaml
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/export-min.yaml
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/import-max.yaml
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/import-min.yaml
addOns/exim/src/test/java/org/zaproxy/addon/exim/automation/ExportJobUnitTest.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/automation/ImportJobUnitTest.java

Some AF templates do not end with an empty line (e.g. [`passiveScan-config-max.yaml`](https://github.com/zaproxy/zap-extensions/blob/f53114fa7b11453f2ed4c641ac86710e4c90d9cd/addOns/pscan/src/main/resources/org/zaproxy/addon/pscan/automation/jobs/passiveScan-config-max.yaml)) and result in invalid templates being generated:
This is fixed by normalizing the trailing newlines at the time of template generation in the automation add-on. Also, deprecated jobs and data jobs are skipped, and jobs are sorted by their types.
The indentation in exim templates was not correct and was also adjusted.

automation, exim: Fix generated AF templates

---

addOns/exim/src/main/java/org/zaproxy/addon/exim/ExtensionExim.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/Importer.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/ImporterOptions.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/ImporterResult.java
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarImporterType.java
addOns/exim/src/main/resources/org/zaproxy/addon/exim/resources/Messages.properties
addOns/exim/src/test/java/org/zaproxy/addon/exim/ExtensionEximUnitTest.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/ImporterOptionsUnitTest.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/ImporterResultUnitTest.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/ImporterUnitTest.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/har/HarImporterTypeUnitTest.java

Expose the importer (currently just HAR) through the extension to not require other add-ons to depend on "internal" classes and dependencies.

exim: expose importer through the extension

---

addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/AppPattern.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/PopupMenuEvidence.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechOptionsPanel.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechPanel.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechPassiveScanner.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechsJsonParser.java

- AppPattern > Remove unnecessary right side type declaration.
- ExtensionWappalyzer > Remove unused/unnecessary variables.
- PopupMenuEvidence > Use .equals() for String comparison.
- TechOptionsPanel > Use imports vs. fully qualified objects.
- TechPanel > Adjust to more appropriate use of constants, use imports vs. fully qualified objects. Remove use of statically assigned/sized fonts.
- TechPassiveScanner > Remove unnecessary right side type declaration.
- TechJsonParser > Remove unnecessary ThreadGroup declaration and assignment.
N/A

tech detection: SAST Fixes (SonarLint)

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/ServerExceptionHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/ServerExceptionHandlerUnitTest.java

Check also for `unknown_ca` with `SSLException` which might happen with other `SSLEngine` implementations.
Prevent errors like:
```
ERROR ServerExceptionHandler - javax.net.ssl.SSLException: org.bouncycastle.tls.TlsFatalAlertReceived: unknown_ca(48)
javax.net.ssl.SSLException: org.bouncycastle.tls.TlsFatalAlertReceived: unknown_ca(48)
at org.bouncycastle.jsse.provider.ProvSSLEngine.unwrap(ProvSSLEngine.java:505) ~[bctls-fips-2.0.19.jar:2.0.19]
at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679) ~[?:?]
at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:309) ~[?:?]
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1441) ~[?:?]
at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1334) ~[?:?]
at …
```

network: handle another `unknown_ca` exception

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/TlsUtils.java

Provide more information when unable to query the TLS/SSL protocol versions available.

network: report TLS providers on query error

---

addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/automation/actions/AddScriptAction.java
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/automation/actions/AddScriptActionUnitTest.java

Check that the source (e.g. file) is non-empty now that it's empty by default.
---
Caught by https://github.com/zaproxy/zaproxy/actions/runs/11536852747/job/32116659791

scripts: fix AF inlined script creation

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/ActiveScanJobDialog.java

Use one as minimum threads instead of the default number of threads, otherwise it would not be possible to set less than the default through the dialogue.
Remove double unboxings, which were a noop.

automation: correct min threads ascan job dialog

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/cert/CertificateUtils.java

Rely on the default secure random generator when creating the Root CA certificate to use the most appropriate defined by the security provider.

network: use default sec random for Root CA cert

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/UsernameEnumerationScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/UsernameEnumerationScanRuleUnitTest.java

Check the URI paths taking into account that they might be null, for messages that don't have one.

ascanrulesBeta: fix NPE in username enumeration

---

addOns/reports/CHANGELOG.md
addOns/reports/reports.gradle.kts
addOns/reports/src/main/zapHomeFiles/reports/traditional-json-plus/report.json
addOns/reports/src/main/zapHomeFiles/reports/traditional-json/report.json
addOns/reports/src/test/java/org/zaproxy/addon/reports/ExtensionReportsUnitTest.java
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-json-plus.json
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-json.json
addOns/sequence/CHANGELOG.md
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/StdActiveScanRunner.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/SequenceAScanJobResultData.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/SequenceActiveScanJob.java
addOns/sequence/src/main/resources/org/zaproxy/zap/extension/sequence/resources/Messages.properties
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestZapUtils.java
addOns/zest/src/test/java/org/zaproxy/zap/extension/zest/ZestZapUtilsUnitTest.java

As per title.
Note that I didnt add the 'highestAlert' field - that looks to be a bit tricky, and not really needed for JSON reports?
Might want it for HTML ones though 😁 
Also added the alertId so that they can be cross referenced.

Sequence: Support for JSON reports

---

addOns/sequence/src/main/javahelp/org/zaproxy/zap/extension/sequence/resources/help/contents/automation.html

Mention the `sequence-activeScan` in the help page.

sequence: add help for `sequence-activeScan`

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/ClientPassiveScanHelper.java
addOns/client/src/test/java/org/zaproxy/addon/client/pscan/ClientPassiveScanHelperUnitTest.java

Check that the message exists before checking its URI.

client: fix exception with deleted messages

---

addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/SequenceImportJob.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/CreateScriptOptions.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ExtensionZest.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestParam.java
addOns/zest/src/test/java/org/zaproxy/zap/extension/zest/CreateScriptOptionsUnitTest.java
addOns/zest/src/test/java/org/zaproxy/zap/extension/zest/ExtensionZestUnitTest.java
addOns/zest/src/test/java/org/zaproxy/zap/extension/zest/ZestParamUnitTest.java

Include the responses always as that's useful for verification of the assertions.

sequence: include responses when importing

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthUtilsUnitTest.java

Use a synchronized map for the token map and sync the stream access to prevent concurrency exceptions.
Reduce accessibility of method that's only used for tests and remove the token directly.
Fix zaproxy/zaproxy#8187.

authhelper: address concurrency issue

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/automation/ExtensionScriptAutomation.java
addOns/scripts/src/main/resources/org/zaproxy/zap/extension/scripts/resources/Messages.properties

Report errors that happen by scripts that are running in the background (e.g. HTTP Sender, passive/active rules) while the automation framework plans are running.
Fix zaproxy/zaproxy#8586.

scripts: report indirect script errors in AF

---

addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/seq/performance/SequencePage.java

Added option to go back to previous steps.
Stopped it invalidating the seq as aggressively.
Moved the XSS vuln to an earlier page so that it happens while the seq is still valid.
Changed the number of steps - otherwise the spider stopped just short of invalidating the seq

Dev: make seq performance test testable

---

addOns/graphql/CHANGELOG.md
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlParser.java
addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/GraphQlParserUnitTest.java
addOns/graphql/src/test/resources/org/zaproxy/addon/graphql/introspectionResponse.json

Add support for importing an introspection query response from a file.
Closes zaproxy/zaproxy#8569.

graphql: Support importing introspection responses

---

addOns/sequence/CHANGELOG.md
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/ExtensionSequence.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/SequencePopupMenuItem.java

Switch to use the new seq ascan - it works better and is faster.
We should revisit the help at some point.
https://github.com/zaproxy/zap-extensions/pull/5897 - mayneed to change to use this for the default policy

Sequence - use new seq scan in desktop

---

addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/CreateScriptOptions.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ExtensionZest.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/internal/DefaultRequestValueReplacer.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/internal/NoopRequestValueReplacer.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/internal/RequestValueReplacer.java
addOns/zest/src/test/java/org/zaproxy/zap/extension/zest/CreateScriptOptionsUnitTest.java
addOns/zest/src/test/java/org/zaproxy/zap/extension/zest/internal/DefaultRequestValueReplacerUnitTest.java

Replace values in the request (query/body) that were found in the previous response's form fields.

zest: use values from responses in added scripts

---

addOns/sequence/CHANGELOG.md
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/SequenceAScanJobResultData.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/SequenceActiveScanJob.java

Change the active scan job to provide alert result data for the alert tests.
Tweak the changelog as the active scan job is no longer just initial implementation.

sequence: provide alert result data

---

addOns/callhome/CHANGELOG.md
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java
addOns/sequence/CHANGELOG.md
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/StdActiveScanRunner.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/ExtensionSequenceAutomation.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/SequenceActiveScanJob.java
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/SequenceImportJob.java

- CHANGELOGs > Added notes.
- ExtensionCallHome > Add stats key for telemetry.
- SequenceActiveScanJob > Add stats counters.
- StdActiveScanRunner > Add stats counters.
- SequenceImportJob > Add stats counters.
N/A

sequence & callhome: Add sequence automation stats

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanPolicyJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PolicyDefinition.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-ascan.html
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanPolicyJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/PolicyDefinitionUnitTest.java
addOns/sequence/CHANGELOG.md
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/SequenceActiveScanJob.java
addOns/sequence/src/main/javahelp/org/zaproxy/zap/extension/sequence/resources/help/contents/automation.html
addOns/sequence/src/main/resources/org/zaproxy/zap/extension/sequence/resources/sequence-activeScan-max.yaml

Modify automation and sequence to properly build and use a policy from policyDefinition if present in the plan. If neither policy nor policyDefinition are defined fall back to `Default Policy` or `Sequence` respectively.
n/a

automation & sequence: fix use of default policies and set Sequence as default sequence policy

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java

Cleaning up sql injection scan rule code ahead of making updates for false positives in https://github.com/zaproxy/zaproxy/issues/8652 This change has no logic changes. It only removes old commented out code and cleans up a few other excessive comments such as commenting the end of loops. The goal is to improve readability of the code

ascanrules: clean up sqli comments

---

addOns/pscan/src/main/java/org/zaproxy/addon/pscan/ExtensionPassiveScan2.java

Move the view check to the correct place to set the config to the scan rules always (headless and GUI).

pscan: set config always to the scan rules

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/PolicyTag.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/PolicyTagUnitTest.java

- PolicyTags > New enum for use with rules and the scan policies add-on.
- PolicyTagsUnitTest > Unit test for the new tags enum.
N/A

commonlib: Add PolicyTags

---

addOns/scanpolicies/CHANGELOG.md
addOns/scanpolicies/src/main/javahelp/help/contents/policy-default.html
addOns/scanpolicies/src/main/javahelp/help/contents/policy-dev-cicd.html
addOns/scanpolicies/src/main/javahelp/help/contents/policy-dev-full.html
addOns/scanpolicies/src/main/javahelp/help/contents/policy-dev-std.html
addOns/scanpolicies/src/main/javahelp/help/contents/scanpolicies.html
addOns/scanpolicies/src/main/javahelp/help/map.jhm
addOns/scanpolicies/src/main/javahelp/help/toc.xml
addOns/scanpolicies/src/main/zapHomeFiles/policies/Dev CICD.policy
addOns/scanpolicies/src/main/zapHomeFiles/policies/Dev Full.policy
addOns/scanpolicies/src/main/zapHomeFiles/policies/Dev Standard.policy

- Policies > The new policy files.
- Help content > New help content covering the new policies.
N/A

scanpolicies: Add initial 3 standardized policies

---

addOns/soap/CHANGELOG.md
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanRule.java
addOns/soap/src/main/java/org/zaproxy/zap/extension/soap/SOAPXMLInjectionActiveScanRule.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/SOAPActionSpoofingActiveScanRuleTestCase.java
addOns/soap/src/test/java/org/zaproxy/zap/extension/soap/SOAPXMLInjectionActiveScanRuleTestCase.java

- Scan rules > Add PolicyTag values.
- Unit tests > Assert the new tags.
- zaproxy/zap-extensions#5930

SOAP: Add policy alert tags

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/ProxyDisclosureScanRule.java
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/UsernameEnumerationScanRule.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/ProxyDisclosureScanRuleUnitTest.java
addOns/ascanrulesBeta/src/test/java/org/zaproxy/zap/extension/ascanrulesBeta/UsernameEnumerationScanRuleUnitTest.java

- Scan rules > In both cases CWE-200 was replaced with CWE-204 "Observable Response Discrepancy".
- Unit Tests > Updated to assert the new CWE ID.
- Fixes zaproxy/zaproxy#8713
- Fixes zaproxy/zaproxy#8715

ascanrulesBeta: Replace usage of CWE-200

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java

Cleaning up sql injection scan rule code ahead of making updates for false positives in https://github.com/zaproxy/zaproxy/issues/8652. This change is just to split the different types of sql injection tests into helper functions. No logic changes. This makes it easier to tell what types of sql injection tests the rule is running and to find the code for each one.
May want to merge these other PRs with unit tests first:
- https://github.com/zaproxy/zap-extensions/pull/5797
- https://github.com/zaproxy/zap-extensions/pull/5867
- https://github.com/zaproxy/zaproxy/issues/8652

ascanrules: Refactor sqli scan rule into helper functions

---

addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/PolicyTag.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/PolicyTagUnitTest.java

Add convenience method to get all PolicyTag tags

commonlib: Add convenience method to get all PolicyTag tags

---

addOns/scripts/CHANGELOG.md
addOns/scripts/scripts.gradle.kts
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/scanrules/ScriptsActiveScanner.java
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/scanrules/ScriptsActiveScannerUnitTest.java

- scripts.gradle.kts > Newer commonlib dependency.
- ScriptsActiveScanner > Override getAlertTags method.
- ScriptsActiveScannerUnitTest> Add test for the new tags.
- zaproxy/zap-extensions#5930

scripts: Add Policy Tags to ScriptsActiveScanner

---

addOns/pscan/src/main/java/org/zaproxy/addon/pscan/ExtensionPassiveScan2.java
addOns/pscan/src/main/java/org/zaproxy/addon/pscan/PassiveScanApi.java
addOns/pscan/src/test/java/org/zaproxy/addon/pscan/PassiveScanApiUnitTest.java

Start to remove the dependency on the core extension for accessing the scan rules, in the API.

pscan: use scan rule manager in the API

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java

As per title.
I've not updated the help as I think the logical place to document this is here: https://www.zaproxy.org/docs/automate/automation-framework/#exit-value

Automation: added method for setting exit value

---

.github/scripts/generateScanPolicies.js
.github/workflows/generate_policies.yml

- generate-scan-policies.js > ZAP standalone script to be used by a nightly docker image to craft the scan policies.
- generate_policies.yml > The new workflow. Triggered by cron every Friday morning or manually via workflow_dispatch.
zaproxy/zap-extensions#5930
- [na] Update changelog
- [na] Run `./gradlew spotlessApply` for code formatting (I did format the script based on the community-script formatter)
- [na] Write tests (Tested in another repo)

Add workflow/script to generate scan policies based on rule tags

---

.github/workflows/generate_policies.yml

Remove specification of repository (-R) when creating the PR, and re-ordered a few things to make the flow more logical. There's a chance it still needs a fetch for upstream, but I believe the ambiguity error was caused by having upstream set and specifying a repo.

Generate Scan Policies from Policy Tags Workflow adjustment

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/crowdin-upload-files.yml
.github/workflows/prepare-release-add-on.yml
.github/workflows/release-add-on.yml
build.gradle.kts

No longer support Java 11

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/JobUtils.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/JobUtilsUnitTest.java

Apply the object's data always in a specific order to allow to verify that the changes are applied properly (e.g. restoring original values).

automation: apply object to object in order

---

addOns/addOns.gradle.kts
addOns/webdrivers/webdriverlinux/gradle.properties
addOns/webdrivers/webdrivermacos/gradle.properties
addOns/webdrivers/webdriverwindows/gradle.properties

Update the plugin to support newer Java versions.
Reset release state of failed releases to be restarted later.

Update Gradle add-on plugin and reset releases

---

addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java

Remove the debug print that was left out in a previous change.

network: remove debug print

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationPlan.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/PolicyDefinition.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/PolicyDefinitionUnitTest.java

- Set Jackson to always include the Rule ID.
- CHANGELOG add fix note.
- UnitTest to ensure rule ID is serialized as expected.
- Fixes zaproxy/zaproxy#8746

automation: Preserve Rule ID zero

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AddAscanRuleDialog.java

Prevent the dialog(s) from being initially displayed smaller than their contents.

automation: Fix Active Scan Policy job Rule add/modify Dialog sizing/display

---

addOns/quickstart/CHANGELOG.md
addOns/quickstart/src/main/java/org/zaproxy/zap/extension/quickstart/ajaxspider/AjaxSpiderExplorer.java

The QuickStart AJAX Spider options should be persisted between restarts, but there were 2 problems.
1. Changing the AJAX Spider run option caused an config event to be raised which meant that if a URL was specified it might get cleared.
2. The selected browser was never set as it was always changed back to firefox-headless when the dialog was initialised
This PR fixes those problems.

QuickStart: Fix AJAX Spider options

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/ExitStatusJobDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/NewPlanDialog.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ExitStatusJob.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/automation.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-exitstatus.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/index.xml
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/map.jhm
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/toc.xml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/exitStatus-max.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/exitStatus-min.yaml
addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtentionAutomationUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ExitStatusJobUnitTest.java
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-config.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-min.yaml

Fixes zaproxy/zaproxy#6928.
Adds a new job for setting the exit status based on various criteris.

Automation: exitStatus job

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthUtilsUnitTest.java
addOns/domxss/CHANGELOG.md
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
addOns/selenium/CHANGELOG.md
addOns/selenium/selenium.gradle.kts

Update Selenium library to version 4.27.0.
Address deprecation warnings in `authhelper` and `domxss`.

Update Selenium library

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SstiBlindScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/XxeScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SstiBlindScanRuleUnitTest.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/XxeScanRuleUnitTest.java

- Add the `OUT_OF_BAND` alert tag to the following scan rules:
- Server Side Template Injection (Blind)
- XML External Entity Attack

ascanrules: Add `OUT_OF_BAND` tag to some rules

---

addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/test/java/org/zaproxy/addon/client/ExtensionClientIntegrationUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/spider/ClientSpiderUnitTest.java

In ZAP with the client add-on installed open the browser and point at a running version of bodgeit.
Then run the client spider against bodgeit - it will not find anything.
This is because its listenning for "new node" events, but no new nodes are added because they were already there, just unvisited.
This PR fixes that by adding those nodes to the task list.
No changelog entry as this is still unpublished functionality 😁

Client: Change spider to access unvisited URLs

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SstiScanRule.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ssti/GoTemplateFormat.java
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ssti/TemplateFormat.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SstiScanRuleUnitTest.java

- CHANGELOG > Fix note
- SstiScanRule > Adjust logic to prevent False Positives.
- SstiScanRuleUnitTest > Updated for adjusted logic.
- Fixes zaproxy/zaproxy#8622

ascanrules: Address SSTI false positive

---

addOns/retire/CHANGELOG.md
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java
addOns/retire/src/test/java/org/zaproxy/addon/retire/RetireScanRuleUnitTest.java
addOns/wappalyzer/CHANGELOG.md
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/TechPassiveScanner.java
addOns/wappalyzer/src/test/java/org/zaproxy/zap/extension/wappalyzer/TechPassiveScannerUnitTest.java

- CHANGELOGs > Add note.
- Rules > Changed or dropped CWE.
- Unit Tests > Updated for the new or removed CWEs.
- Fixes zaproxy/zaproxy#8732
- Fixes zaproxy/zaproxy#8733

tech detection & retire: Remove usage of CWE-200 and update other CWE

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/SiteIsolationScanRule.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/SiteIsolationScanRuleTest.java

Fix a bug in the site isolation scan rule.
https://github.com/zaproxy/zaproxy/issues/8735

pscanrulesBeta: fix isolation scan rule isPage200 check

---

addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/DiscoveredGraphQlEngineHandler.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/ExtensionGraphQl.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/GraphQlFingerprinter.java
addOns/graphql/src/main/java/org/zaproxy/addon/graphql/techdetection/ExtensionTechDetectionGraphQl.java
addOns/graphql/src/main/javahelp/org/zaproxy/addon/graphql/resources/help/contents/alerts.html
addOns/graphql/src/main/resources/org/zaproxy/addon/graphql/resources/Messages.properties
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/GraphQlFingerprinterUnitTest.java
addOns/graphql/src/test/java/org/zaproxy/addon/graphql/techdetection/ExtensionTechDetectionUnitTest.java
addOns/wappalyzer/src/main/java/org/zaproxy/zap/extension/wappalyzer/ExtensionWappalyzer.java

- build file > Added dependency.
- GraphQlFingerprinter > Updated to add Technology matches when GraphQL engines are fingerprinted.
- GraphQlFingerprinterUnitTest > Updated for new handling.
- DiscoveredGraphQlEngineHandler > An interface to be implemented for consumption/handling of discovered GraphQL engines.
- ExtensionTechDetection > Added to facilitate optional dependence.
- ExtensionTechDetectionUnitTest > Tests :)
- Messages.properties > Added key/value pairs to support the optional dependency.
- alert.html > Added note about the new functionality.
Ex: See the Apollo entry:
This seems to be a decent place for testing: https://countries.trevorblades.com/graphql
(Note if you do serial imports you will hit a limit and need to wait a min or so.)
N/A

graphql: Add tech detection for GraphQL Engines

---

addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/ui/PopupIncludeWebSocketContextMenu.java

Override the "new" method that makes use of weights to return the proper menu item implementation, which corrects both the location it appears in and its functionality.
Remove the "old" method as it's no longer used/needed.

websocket: fix duplicated New Context menu item

---

addOns/replacer/CHANGELOG.md
addOns/replacer/src/main/java/org/zaproxy/zap/extension/replacer/automation/ReplacerJob.java
addOns/replacer/src/test/java/org/zaproxy/zap/extension/replacer/automation/ReplacerJobUnitTest.java

Handle the `deleteAllRules` when applying the custom parameters to prevent the warning that the parameter is unrecognised.
Fix zaproxy/zaproxy#8764.

replacer: do not warn for `deleteAllRules`

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/DefaultValueProvider.java
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/DefaultValueProviderUnitTest.java

Rework the input checks to prevent NullPointerException since not all callers have all values.
Remove unneeded dependency on Jericho classes by inlining values.

commonlib: handle no input when providing values

---

addOns/client/src/test/java/org/zaproxy/addon/client/spider/ClientSpiderUnitTest.java

Stop the spider only after the access to the seed URL occurred and verify that the new URL was not accessed, otherwise the test could fail because the seed URL could be accessed between the calls to start and stop.

client: fix concurrency issue in test

---

addOns/client/src/main/java/org/zaproxy/addon/client/ClientOptions.java
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpiderDialog.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpiderPanel.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpiderTask.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/PopupMenuSpider.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/SpiderScanController.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/UrlTableModel.java
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/Messages.properties
addOns/client/src/test/java/org/zaproxy/addon/client/ExtensionClientIntegrationUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/spider/ClientSpiderUnitTest.java

Add the Client Spider tab. No help as this is still a "hidden" feature.
Currently only the nodes added are shown. We should report the full set of URLs found but that will require other changes.

Client: Initial Client Spider tab

---

addOns/retire/CHANGELOG.md
addOns/retire/src/main/java/org/zaproxy/addon/retire/model/Repo.java
addOns/retire/src/main/java/org/zaproxy/addon/retire/model/Vulnerability.java
addOns/retire/src/test/java/org/zaproxy/addon/retire/RetireScanRuleUnitTest.java
addOns/retire/src/test/java/org/zaproxy/addon/retire/model/RepoUnitTest.java
addOns/retire/src/test/java/org/zaproxy/addon/retire/model/UpstreamJsRepositoryUnitTest.java
addOns/retire/src/test/resources/org/zaproxy/addon/retire/model/samples/vulns-all.json

- Repo > Added handling for fall through of essentially "empty" object.
- Tests > Added additional unit tests/assertions.
Reported via direct email and dev group.

retire: Fix False Positive issue

---

addOns/addOns.gradle.kts
addOns/commonlib/CHANGELOG.md
addOns/domxss/CHANGELOG.md
addOns/network/CHANGELOG.md
addOns/retire/CHANGELOG.md
addOns/selenium/CHANGELOG.md
testutils/src/main/java/org/zaproxy/zap/testutils/PassiveScannerTestUtils.java
testutils/testutils.gradle.kts

Change the add-ons that should be released for 2.15:
- `commonlib`
- `domxss`
- `network`
- `retire`
- `selenium`

Revert some add-ons back to 2.15 and Java 11

---

addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpiderPanel.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpiderTask.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/TaskTableModel.java
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/Messages.properties

Add a GUI for the client spider tasks. I'll update this PR once that has been merged.
Depends on https://github.com/zaproxy/zap-extensions/pull/6017

Client: Spider tasks GUI

---

addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/ui/PopupMenuClientAttack.java

With this change the spider will be enabled when the `-dev`option is used.

Client: Use dev mode

---

addOns/automation/src/test/java/org/zaproxy/addon/automation/ExtensionAutomationUnitTest.java

Rename the class to "Extension".

automation: fix typo in test class name

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CloudMetadataScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CloudMetadataScanRuleUnitTest.java

This pull request fixes the issue of false positives in the `CloudMetadataScanRule` plugin. The condition for raising an alert has been improved by adding a method to specifically check for both "ami-id" and "ami-launch-index" in the response body. 
Fixes zaproxy/zaproxy#8514

ascanrules: fix false positive in cloud metadata and add more providers

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/resources/org/zaproxy/addon/commonlib/internal/vulns/vulnerabilities.xml

Added solutions to Insufficient Process Validation vulnerability (vuln_item_wasc_40)
Related to: [#8056](https://github.com/zaproxy/zaproxy/issues/8056)

commonlib: add solution to Insufficient Process Validation

---

addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpiderDialog.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpiderPanel.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpiderTask.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/HttpPrefixUriValidator.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/MessagesTable.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/MessagesTableModel.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/SpiderScanController.java
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/Messages.properties
addOns/client/src/test/java/org/zaproxy/addon/client/ExtensionClientIntegrationUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/spider/ClientSpiderUnitTest.java

Limit to context, subtree, or target preventing any accesses outside the selected spider scope.
Use own proxies when spidering instead of the main one, to limit the scope and allow later to track the requests of each action.

client: limit spider scope and use own proxies

---

addOns/client/src/test/java/org/zaproxy/addon/client/internal/ClientMapUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/spider/UrlTableModelUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/zest/ExtensionClientZestTest.java

Mock some classes to prevent the usage/init of the ZAP dirs.
Remove some sys outs.

client: prevent ZAP dirs usage/init in tests

---

addOns/encoder/src/main/java/org/zaproxy/addon/encoder/processors/EncodeDecodeProcessors.java
addOns/encoder/src/test/java/org/zaproxy/addon/encoder/processors/EncodeDecodeProcessorsUnitTest.java

Correct the name of the resource key of a predefined decoder.

encoder: fix typo in resource message key

---

addOns/domxss/CHANGELOG.md
addOns/domxss/src/main/java/org/zaproxy/zap/extension/domxss/DomXssScanRule.java
addOns/domxss/src/main/resources/org/zaproxy/zap/extension/domxss/resources/Messages.properties

Catch exceptions that might happen if any of the elements is no longer available while obtaining the XPath of an element.

domxss: handle XPath failure

---

addOns/automation/src/test/java/org/zaproxy/addon/automation/AutomationEnvironmentUnitTest.java

Mock the `Model` to prevent access/usage of the default ZAP home which would/could lead to concurrent accesses and cause the tests to fail as the home cannot be shared.

automation: prevent ZAP home usage in tests

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/resources/org/zaproxy/zap/extension/ascanrules/resources/Messages.properties
addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/resources/org/zaproxy/zap/extension/ascanrulesBeta/resources/Messages.properties

Remove the dot from the messages as the main message already has one.

Remove double dots in skipped messages

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/scanrules/ScriptSynchronizerUtils.java

`org.graalvm.polyglot.PolyglotException#getCause()` returns `null` which results in an NPE.
While the error was being handled outside, the cause of the actual Exception was lost and the NPE was logged to the output instead.

scripts: Fix NPE in `ScriptSynchronizerUtils`

---

addOns/client/src/test/java/org/zaproxy/addon/client/ExtensionClientIntegrationUnitTest.java

Use own ZAP home when running the `ExtensionClientIntegration` tests to prevent access/usage of the default ZAP home which would/could lead to concurrent accesses and cause the tests to fail as the home cannot be shared.
Adjust mocks to match the latest behaviour.

client: prevent ZAP home usage in a test

---

addOns/custompayloads/CHANGELOG.md
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/AbstractColumnDialog.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/Column.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayload.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadCategoryColumn.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadColumns.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadMultipleOptionsTableModel.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsMultipleOptionsTablePanel.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsOptionsPanel.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsParam.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/EditableColumn.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/EditableSelectColumn.java
addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/contents/options.html
addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/index.xml
addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/map.jhm
addOns/custompayloads/src/main/javahelp/org/zaproxy/zap/extension/custompayloads/resources/help/toc.xml
addOns/custompayloads/src/main/resources/org/zaproxy/zap/extension/custompayloads/resources/Messages.properties
addOns/custompayloads/src/test/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsApiUnitTest.java
addOns/custompayloads/src/test/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsParamUnitTest.java

- AbstractColumnDialog > Use List interface vs ArrayList.
- Column > Reduce visibility.
- CustomPayload > Remove ID and related handling.
- CustomPayloadColumns > Add private constructor to hide implicit one. Remove ID and related handling.
- CustomPayloadMultipleOptionsTableModel > Use List interface vs ArrayList for params. Remove ID and related handling.
- CustomPayloadsCategoryColumn > Make getExtension static.
- CustomPayloadsMultipleOptionsTablePanel > Make showDialog static. Remove ID and related handling.
- CustomPayloadsParam > Remove ID and related handling, switched to versioned config.
- EditableColumn > Reduce visibility.
- EditableSelectColumn > Reduce visibility, adjust method naming to proper Java camelCase.
- CustomPayloadsApiUnitTest > Remove unused param …

custompayloads: SAST Fixes (SonarLint), Options panel help, & drop ID

---

addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/resources/org/zaproxy/addon/commonlib/internal/vulns/vulnerabilities.xml
addOns/commonlib/src/test/java/org/zaproxy/addon/commonlib/internal/vulns/DefaultVulnerabilitiesUnitTest.java

Adds more solutions and reference links to Information Leakage vulnerability.
Part of zaproxy/zaproxy#8056

commonlib: add more details to "Information Leakage" vulnerability

---

addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsParam.java
addOns/custompayloads/src/test/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsParamUnitTest.java

Fix accidental substitution of CONST and literal
Follow-up to: https://github.com/zaproxy/zap-extensions/pull/5853

custompayloads: Fix accidental substitution of CONST and literal

---

addOns/client/src/main/java/org/zaproxy/addon/client/ClientIntegrationAPI.java
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/internal/ClientMap.java

As per title
Builds on top of https://github.com/zaproxy/zap-extensions/pull/6052 as tyhat makes it much easier to test 😁 
Will update once that PR has been merged.

Client: report nodes with no components as visited

---

addOns/addOns.gradle.kts
addOns/exim/CHANGELOG.md
addOns/network/network.gradle.kts
addOns/openapi/openapi.gradle.kts
addOns/reports/reports.gradle.kts
addOns/selenium/selenium.gradle.kts
addOns/soap/soap.gradle.kts

Prevent the inclusion of the Log4j 2 API and implementation as those are already included by core and would cause conflicts making add-ons to not use the same classes/configs as core.
Remove now redundant local exclusions.
---
This was reported for exim and, after double checking the dependencies of all add-ons, that's the only one affected.

Exclude Log4j 2 from runtime classpath of add-ons

---

addOns/custompayloads/CHANGELOG.md
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsMultipleOptionsTablePanel.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsOptionsPanel.java
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsParam.java
addOns/custompayloads/src/main/resources/org/zaproxy/zap/extension/custompayloads/resources/Messages.properties
addOns/custompayloads/src/test/java/org/zaproxy/zap/extension/custompayloads/CustomPayloadsParamUnitTest.java

The add-on will no longer attempt to save or load Payloads for which there is no Category.

custompayloads: Don't save or load payloads with nameless category

---

addOns/client/client.gradle.kts
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/test/java/org/zaproxy/addon/client/spider/ClientSpiderUnitTest.java

Correctly handle URLs without hostname when checking if they are in scope for the spider.

client: handle URLs without hostname in spider

---

addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/TaskTableModel.java

Sync the access internally in the task model to, regardless of how ZAP is run, prevent concurrency issues which would lead to some tasks going missing while they were being added to the list of tasks which would later lead to exceptions as the tasks were not present in the model.
Only report model changes if there's a view.

client: address concurrency issues with tasks

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/handlers/CommonMessagePropertiesHandler.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/handlers/CommonMessagePropertiesHandlerUnitTest.java

Set the address where (e.g. server, proxy) the request header was received.

network: set local address to request header

---

addOns/custompayloads/CHANGELOG.md
addOns/custompayloads/custompayloads.gradle.kts
addOns/custompayloads/src/main/java/org/zaproxy/zap/extension/custompayloads/CustomMultiplePayloadDialog.java
addOns/custompayloads/src/main/resources/org/zaproxy/zap/extension/custompayloads/resources/Messages.properties

A fix to ensure that the file being imported is readable.
N/A

custompayloads: Ensure file is readable for multi payload import

---

addOns/client/src/main/java/org/zaproxy/addon/client/ClientIntegrationAPI.java
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/TaskTableModel.java

Reduce the work done in the EDT as much of it does not need to happen there.
Sync addition of the tasks as well to ensure the check done on removal takes into account the tasks that might have been being added/executed at the same time.
Also, remove sync on WebDriver retrieval since that's already synced internally.
Rework the task model to make the ID/row match in all cases, it was still possible for the ID/row to be interleaved enough that later would lead to index out of bound exceptions.

client: adjust thread accesses

---

addOns/webdrivers/webdriverlinux/CHANGELOG.md
addOns/webdrivers/webdrivermacos/CHANGELOG.md
addOns/webdrivers/webdrivers.gradle.kts
addOns/webdrivers/webdriverwindows/CHANGELOG.md

The next releases will be for 2.16.

webdrivers: update ZAP to 2.16

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/ReportHelper.java
addOns/reports/src/test/java/org/zaproxy/addon/reports/ReportHelperUnitTest.java

Use the own stats key when the stats do not have a resource message, instead of letting core log an error that it's missing.
Fix zaproxy/zaproxy#8788.

reports: use own stats key if no resource message

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-ascanconfig.html

Add missing text to configuration of `threadPerHost`.

automation: correct job config in the help

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/internal/ClientSideDetails.java

Make the components in `ClientSideDetails` synchronized as multiple components can be added at the same time which could lead to inconsistent state in the set and later lead to exceptions.
---
Found in https://github.com/zaproxy/zap-extensions/pull/6040#issuecomment-2593380551.

client: fix concurrency issue with components

---

addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java

Add handler to Chrome and Firefox and log DEBUG those messages.
Use WebDriver BiDi with Chrome, which is required for the above.

selenium: allow to log browser's `console.log`

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/internal/ClientMap.java
addOns/client/src/main/java/org/zaproxy/addon/client/internal/ClientMapWriter.java
addOns/client/src/main/java/org/zaproxy/addon/client/internal/ClientSideComponent.java
addOns/client/src/main/java/org/zaproxy/addon/client/ui/PopupMenuExportClientMap.java
addOns/client/src/main/javahelp/org/zaproxy/addon/client/resources/help/contents/client.html
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/Messages.properties
addOns/client/src/test/java/org/zaproxy/addon/client/internal/ClientMapWriterUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/internal/ClientSideComponentUnitTest.java
addOns/client/src/test/java/org/zaproxy/addon/client/spider/ClientSpiderUnitTest.java

Add a context menu to facilitate exporting the Client Map as YAML.
N/A
<details>
<summary>example output</summary>
```yaml
- node: "ClientMap"
name: "Client Map"
url: null
isStorage: false
visited: false
children: 
- node: "https://github.com/"
name: "https://github.com"
url: "https://github.com/"
isStorage: false
visited: false
children: 
- node: "https://github.com/OWASP/"
name: "OWASP"
url: "https://github.com/OWASP/"
isStorage: false
visited: false
children: 
- node: "https://github.com/OWASP/owasp-swag/"
name: "owasp-swag"
url: "https://github.com/OWASP/owasp-swag/"
isStorage: false
visited: false
children: 
- node: "https://github.com/OWASP/owasp-swag/tree/"
name: "tree"
url: "https://github.com/OWASP/owasp-swag/tree/"
isStorage: false
visited: false
children: 
- node: …
```

client: Export Client Map

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestZapRunner.java

ZAP will set the proxy and install extensions, like the ZAP one.

zest: use ZAP for launching Firefox and Chrome

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthUtilsUnitTest.java

Fields that are not displayed can't be interacted with thus unlikely to be the user name and password fields that the user would have to fill to login.

authhelper: ignore non-displayed fields in BBA

---

addOns/pscan/CHANGELOG.md
addOns/pscan/src/main/javahelp/org/zaproxy/addon/pscan/help/contents/job-pscanwait.html
addOns/pscan/src/main/resources/org/zaproxy/addon/pscan/automation/jobs/passiveScan-wait-max.yaml
addOns/pscan/src/main/resources/org/zaproxy/addon/pscan/automation/jobs/passiveScan-wait-min.yaml

Clarify that passiveScan-wait is based on minutes, as discussed via slack.
https://github.com/zaproxy/zap-extensions/blob/1845b961d43f2a13e63b2a7c8326aa690aa05619/addOns/pscan/src/main/java/org/zaproxy/addon/pscan/automation/jobs/PassiveScanWaitJob.java#L80
n/a
- [n/a] Write tests
- [n/a] Check code coverage

pscan: Clarify that passiveScan-wait is based on minutes

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthUtilsUnitTest.java

Skip further filtering when the login page has a single displayed field, as in that case it should be the user name.

authhelper: use single field for user name in BBA

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestStatementFromJson.java
addOns/zest/src/test/java/org/zaproxy/zap/extension/zest/ZestStatementFromJsonUnitTest.java

The client submit statement was just getting "lost" 😦 

zest: Record Client Submit statement

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/ClientIntegrationAPI.java
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/RedirectScript.java
addOns/client/src/test/java/org/zaproxy/addon/client/RedirectScriptUnitTest.java
addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestRecordScriptDialog.java

Record a client Zest script via the recorder. Your chosen browser will launch but the ext will not start recording - you have to do that manually.
This PR fixes that.
Note that it looks like when the recorder is started in this way then it does not put in the initial Window Launch statement. 
Will need to investigate that, but its likely to be a bug in the browser extension..

client: Fix browser recording on launch

---

addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonCookie/SimpleJsonCookieDir.java
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json-cookie/index.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json-cookie/page3.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/simple-json-cookie/s3cr3t.html

Added a link which is only shown if a localStorage item is set, for testing in browser spider authentication.

dev: add link depending on localStorage

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthUtilsUnitTest.java

Use both DOM attributes and properties when checking the fields.
A previous deprecation warn was addressed by checking only the DOM attributes which inadvertently broke wanted behaviour (e.g. user name fields that don't have the type declared as a DOM attribute).
Extract method to log (potential) user fields.

authhelper: restore DOM property check in BBA

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/authhelper.gradle.kts
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/client/ExtensionAuthhelperClient.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/ZestAuthRunner.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/spiderajax/ClientScriptBasedAuthHandler.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/spiderajax/ExtensionAuthhelperAjax.java
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/authhelper.html
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/browser-auth.html
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/client-script.html
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/index.xml
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/map.jhm
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/toc.xml
addOns/authhelper/src/main/resources/org/zaproxy/addon/authhelper/resources/Messages.properties
addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AuthenticationData.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/authentication.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/environment.html
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestAuthenticationRunner.java

Allow the Ajax Spider to use Client Side scripts to authenticate, when used in conjunction with the Auth Helper add-on.
- Update change logs.
- Update build files with necessary config/dependencies.
- Auth Helper:
- Expand visibility of `findSessionTokenSource` in `AuthUtils`.
- Add new authentication method type, `ClientScriptBasedAuthenticationMethodType`.
- `ExtensionAuthhelperClient` updated to facilitate the new functionality.
- Added `intertnal.ZestAuthRunner` which will also be used by the Client Spider in the future. This ensures that browsers are launched as expected and auth handled before other actions.
- `ClientScriptBasedAuthHandler` handler for the new auth method type, responsible for enabling/disabling auth methods for Users, and providing the necessary BrowserHook.
- …

Client Script Based Auth (Ajax Spider)

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthTestDialog.java

Cache the value to ensure that the state of demo mode is reset always, it was possible for the mode to be kept enabled if the user disabled it before the test finished.

authhelper: reset demo mode always

---

addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/ClientSideHandler.java

Address duplicate code between BBA and CSA method types.
- zaproxy/zap-extensions#6112
- zaproxy/zap-extensions#6137
Note: If you test this live you may need to restart ZAP for it to behave properly with the Client Spider. I don't know if that was just a weird thing on my Windows system or if it's a bigger issue.

authhelper: Deduplicate the handler used by BBA and CSA

---

addOns/postman/CHANGELOG.md
addOns/postman/src/main/java/org/zaproxy/addon/postman/deserializers/ObjectDeserializer.java

Use the class loader of the add-on when deserializing the headers, otherwise it would fail to find the classes of the add-on.

postman: correct header deserialization

---

addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodType.java

BBA & CSA Don't attempt to set handler null if already null
Addresses recent workflow failures: https://github.com/zaproxy/zaproxy/actions/runs/13104643180

authhelper: BBA Don't attempt to set auth message null if handler null

---

addOns/pscanrulesAlpha/CHANGELOG.md
addOns/pscanrulesAlpha/src/main/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64Disclosure.java
addOns/pscanrulesAlpha/src/test/java/org/zaproxy/zap/extension/pscanrulesAlpha/Base64DisclosureUnitTest.java

- Add change note.
- Tweak CWE value in rule.
- Assert value in unit test.
- Fixes zaproxy/zaproxy#8730

pscanrulesAlpha: Replace usage of CWE-200

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/InsecureHttpMethodScanRule.java

- InsecureHttpMethodScanRule > Adjust regex pattern for Google title elements. There's no reason to look for unlimited length character strings. It is doubtful that google would produce content that might cause a ReDoS, but limiting the regex is "safest".
https://github.com/zaproxy/zap-extensions/security/code-scanning/89

ascanrulesBeta: Address ReDoS in Insecure HTTP Methods rule

---

addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/InPageBannerInfoLeakScanRuleUnitTest.java

Address typos in Expected and Example.

pscanrulesBeta: address typo in test method name

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java

Execute the count check also in the EDT to avoid concurrency issues, which could leave the counter showing one when none left to scan.

client: fix pscan counter

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/automation/ScriptJob.java
addOns/scripts/src/test/java/org/zaproxy/zap/extension/scripts/automation/ScriptJobUnitTest.java

- ScriptJob > Remove unnecessary constant and overridden getCustomConfigParameters method.
- ScriptJobUnitTest > Add test asserting there are no custom config params.
Note the issue only occurs when -autogenconf is used.
-autogenmin, -autogenmax both use the expected key value, saving a un-configured script job doesn't include any params, and saving a configured script job uses the expected key value.
- zaproxy/zaproxy#8844

scripts: Remove unnecessary custom param handling

---

addOns/pscan/CHANGELOG.md
addOns/pscan/src/main/java/org/zaproxy/addon/pscan/ExtensionPassiveScan2.java

Allow add-ons to obtain the auto tagging tags.

pscan: expose auto tagging tags

---

addOns/pscan/CHANGELOG.md
addOns/pscan/gradle.properties
addOns/pscan/src/main/java/org/zaproxy/addon/pscan/ExtensionPassiveScan2.java
addOns/pscan/src/test/java/org/zaproxy/addon/pscan/ExtensionPassiveScan2UnitTest.java

That prevents exceptions if any extension tries to get the tags before the extension is fully initialised.

pscan: init options in extension's init method

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/SsrfScanRule.java

Include the exception message to hopefully allow to know what went wrong when scanning for SSRF.

ascanrulesBeta: include exception message in log

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/internal/client/apachev5/HttpSenderApache.java
addOns/network/src/test/java/org/zaproxy/addon/network/internal/client/HttpSenderImplUnitTest.java

Ensure message properties are kept mutable even in case of connection close as the message might be resent with new properties.

network: keep properties mutable on conn close

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodType.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodTypeUnitTest.java

Properly read the API parameters when configuring the BBA.
Include the `loginPageWait` in the API response.
Re-throw the API exceptions which provide more/better details of the error.

authhelper: correct API param handling in BBA

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/authhelper.gradle.kts
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthUtilsUnitTest.java

Prefer the fields that are under the same form as the password field as that should increase the likelihood of choosing the right username field.

authhelper: prefer form related fields in BBA

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/HashDisclosureScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InfoPrivateAddressDisclosureScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InfoSessionIdUrlScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureDebugErrorsScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureInUrlScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureReferrerScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureSuspiciousCommentsScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ServerHeaderInfoLeakScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XBackendServerInformationLeakScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XChromeLoggerDataInfoLeakScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XDebugTokenScanRule.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/XPoweredByHeaderInfoLeakScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ApplicationErrorScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/HashDisclosureScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InfoPrivateAddressDisclosureScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InfoSessionIdUrlScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureDebugErrorsScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureInUrlScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureReferrerScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureSuspiciousCommentsScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ServerHeaderInfoLeakScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/XBackendServerInformationLeakScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/XChromeLoggerDataInfoLeakScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/XDebugTokenScanRuleUnitTest.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/XPoweredByHeaderInfoLeakScanRuleUnitTest.java

- Update CHANGELOG, rules, and tests.
- Fixes zaproxy/zaproxy#8729
- Fixes zaproxy/zaproxy#8728
- Fixes zaproxy/zaproxy#8727
- Fixes zaproxy/zaproxy#8726
- Fixes zaproxy/zaproxy#8725
- Fixes zaproxy/zaproxy#8724
- Fixes zaproxy/zaproxy#8723
- Fixes zaproxy/zaproxy#8722
- Fixes zaproxy/zaproxy#8721
- Fixes zaproxy/zaproxy#8720
- Fixes zaproxy/zaproxy#8719
- Fixes zaproxy/zaproxy#8718
- Fixes zaproxy/zaproxy#8717
- Fixes zaproxy/zaproxy#8716
- Fixes zaproxy/zaproxy#8712

pscanrules: Re-map rules attributed to CWE-200

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRuleUnitTest.java

Removed lack of "report-uri" or "plugin-types" from "CSP: Wildcard Directive" alerts when missing. plugin-types is deprecated and report-uri has no impact for this issue. 
- Update Change log.
- Tweak code.
- Clean code: Switch Arrays.asList to List.of
- zaproxy/zaproxy#8700

pscanrules: CSP-Exclude plugin-types, report-uri, and sandbox from Wildcard Alert

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/report/ExtensionAuthhelperReport.java
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/auth-report-json.html

Removed the incorrect `summary.summary` part and the pass?fail extensions.

authhelper: tweak the auth report keys

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/spider/actions/BaseElementAction.java
addOns/client/src/test/java/org/zaproxy/addon/client/spider/actions/BaseElementActionUnitTest.java

Pass the correct data into the value provider to get the expected values in all cases.
Part of zaproxy/zaproxy#8851.

client: correctly fill input elems when spidering

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/zapHomeFiles/reports/traditional-json-plus/report.json

Use the non-deprecated method to obtain the alert instances as the other method might return incorrect alerts.
Mention the change done in the previous version (it had no entries).
Fix zaproxy/zaproxy#8861.

reports: update method call in JSON plus report

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureSuspiciousCommentsScanRule.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/InformationDisclosureSuspiciousCommentsScanRuleUnitTest.java

- InformationDisclosureSuspiciousCommentsScanRule > Updated handling to target comments in JavaScript more specifically & skip font requests.
- InformationDisclosureSuspiciousCommentsScanRuleUnitTest > Updated and added tests.
- Messages.properties > Updated to detail/report the findings more specifically based on the new behavior.
---
**Note**: The regexes used for JS comments are based on https://github.com/antlr/grammars-v4/blob/c82c128d980f4ce46fb3536f87b06b45b9619922/javascript/javascript/JavaScriptLexer.g4#L49-L50
- Fixes zaproxy/zaproxy#6622
- Fixes zaproxy/zaproxy#6736

pscanrules: Reduce Suspicious Comments rule JS FPs

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/TimestampDisclosureScanRuleUnitTest.java

Passive scan rule identifies timestamps falsely in js files ending up in false positives. Timestamps in JS files can't happen so they should be ignored.
fixes zaproxy/zaproxy#8380

pscanrules: Ignore JavaScript Files while scanning for timestamps on High threshold

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/LoginLinkDetector.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/LoginLinkDetectorUnitTest.java

As per title.
Ready for review but would like the auth tests in place before its merged so we can see what impact it has.

authhelper: try login links if authentication fails

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/report/ExtensionAuthhelperReport.java
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/auth-report-json.html
addOns/authhelper/src/main/zapHomeFiles/reports/auth-report-json/report.json
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/report/ExtensionAuthhelperReportUnitTest.java

Ensure output is escaped as expected. Booleans without quotes, strings with inner quotes escaped etc.
n/a
Note: Some of these tests fail on windows, likely due to line ending differences. But work fine via git bash/gradle.

authhelper: Tweak auth report escaping

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthenticationDiagnostics.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/VerificationDetectionScanRule.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/ClientSideHandler.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthUtilsUnitTest.java

- Only check URLs and methods once for being good verification requests.
- Added API support to the browser based auth method proxy.

authhelper: verification detection improvements

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthTestDialog.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthhelperParam.java
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/auth-tester.html
addOns/authhelper/src/main/resources/org/zaproxy/addon/authhelper/resources/Messages.properties

- auth-tester.html > Added description of the Reset button.
- AuthhelperParam > Added constant for the default browser and wait value.
- AuthTestDialog > Added Reset button and functionality. (Added pack call to the dialog so that it is sized/displayed more appropriately.)
- Messages.properties > Added supporting KVP.
N/A

authhelper: Add Reset Button

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/CookieLooselyScopedScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help_it_IT/contents/pscanrules.html
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/CookieLooselyScopedScanRuleUnitTest.java

This PR addresses the issue reported in the `zaproxy` project ([CookieLooselyScoped scan rule Incorrect logic and outdated RFC standard #8863](https://github.com/zaproxy/zaproxy/issues/8863))
Fix zaproxy/zaproxy#8863.

pscanrules: Refactor `CookieLooselyScopedScanRule` to align with the latest RFC standards

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/LoginLinkDetector.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/LoginLinkDetectorUnitTest.java

Try to find a verification URL with a login link on it.
This is when verification has been set to autodetect and we've not found any suitable URLs so far.
It is likely to work better for more traditional apps as it currently only check HTML responses.
Ready for review but set WIP in case we want to make sure the itests are working before we merge it and potentially cause other problems?

authhelper: Use page with login links for verification

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ExitStatusJob.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ExitStatusJobUnitTest.java

- ExitStatusJob > Exclude FP alerts when looping to establish exit code.
- ExitStatusJobUnitTest > Add test to assert the behavior.
- Fixes zaproxy/zaproxy#8875

automation: Handle FP alerts in Exit Status

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/ExternalRedirectScanRule.java

As per title - it looks like this might have been a mistake back in 2014
https://github.com/zaproxy/zap-extensions/commit/4ba378a5dd75c464dc7da287c450fda31b6b919e
Tested manually - looks too hard to add unit tests?

ascanrules: External Redirect scan rule to regenerate anti CSRF tokens

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpiderApi.java
addOns/client/src/main/resources/org/zaproxy/addon/client/resources/Messages.properties
addOns/client/src/test/java/org/zaproxy/addon/client/spider/ClientSpiderApiUnitTest.java

Add the new spider(Client Spider) to the API. 
Actions: start scan /  stop scan
Views: view status

client: add API for the spider

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ExtensionAuthhelper.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionDetectionScanRule.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthUtilsUnitTest.java

- Bug where some of the data structures were not being reset when the session changed.

authhelper: cookie handling tweak + session bug fix

---

addOns/selenium/CHANGELOG.md
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/internal/FirefoxProfileManager.java

Add some more debug log to help know what's happening during the profile creation.

selenium: add log for Firefox profile creation

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthDiagnosticCollector.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthTestDialog.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ExtensionAuthhelper.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HistoryProvider.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/ClientSideHandler.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthDiagnosticCollectorUnitTest.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/internal/ClientSideHandlerUnitTest.java

Add sanitized post data to the auth diagnostic data, correctly sanitize set-cookies and added the very start of a framework for testing auto-detection.

authhelper: add diag post data + initial auto-detect unit tests

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRule.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ContentSecurityPolicyScanRuleUnitTest.java

- ContentSecurityPolicyScanRule > Adjust handling for directives without fallback.
- ContentSecurityPolicyScanRuleUnitTest > Updated to conform to the new handling.
- Messages.properties > Updated with supporting KVPs and changes.
- Fixes zaproxy/zaproxy#8700

pscanrules: Separate Alert for CSP directives without fallback

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/spider/OpenApiSpider.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/spider/OpenApiSpiderUnitTest.java

Add missing parentheses so the expression matches the expectations.

openapi: correct detection while spidering

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthDiagnosticCollector.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HistoryProvider.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthDiagnosticCollectorUnitTest.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/DiagnosticDataLoader.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/internal/ClientSideHandlerUnitTest.java
addOns/authhelper/src/test/resources/org/zaproxy/addon/authhelper/internal/bodgeit.diags

* Only include proxied requests in auth tester diags - the rest are just noise
* Increase the length of the tokens, so we can detect them as tokens in unit tests
* Include creds as special tokens in auth diags
* Simple test infra so we can use auth daigs in unit tests

Auth diag tweaks plus more tests

---

.github/workflows/create_eval_villian_update.yml

Automate evalvillain add-on updates further.

evalvillain: Include prepareRelease in update workflow

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/automation/OpenApiJob.java
addOns/openapi/src/main/resources/org/zaproxy/zap/extension/openapi/resources/Messages.properties

openapi: Clarify error message

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AuthenticationData.java

Use boolean for the diagnostics default value of the Client Script authentication.

automation: correct default value for client auth

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java

Allow the Client Script Authentication method type to be exposed and configured via the API.
Confirmed via the Web API UI (w/ zaproxy/zaproxy#8885) that it is listed separately and configurable.
N/A

authhelper: Expose Client Script Auth via the API

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodType.java
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/browser-auth.html
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/client-script.html
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/session-header.html
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodTypeUnitTest.java

- Add help content for Header Based Session Management configuration/use via the API.
- Correct Header Based Session Management API header parsing
N/A

authhelper: Correct Header Based Session Management API header parsing

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthTestDialog.java

When saving an Automation Plan based on BBA with custom steps only enabled steps are included.
n/a

authhelper: Skip disabled steps when creating context from Auth Tester

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderPanel.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJob.java

Only count URLs that are in scope. Browsers can make lots of background requests which distort the numbers.

spiderAjax: only count URLs in scope

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthTestDialog.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AutoDetectSessionManagementMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ExtensionAuthhelper.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/AuthenticationStep.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/DialogAddStep.java
addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/ContextWrapper.java
addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/internal/TotpSupport.java
addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestAuthenticationRunner.java
addOns/zest/src/main/javahelp/org/zaproxy/zap/extension/zest/resources/help/contents/zest.html

eUse the core credentials to get the TOTP code.
---
Requires zaproxy/zaproxy#8892 but should work without it (as in not break anything).

Use TOTP from credentials

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ExtensionAuthhelper.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/db/TableJdo.java

Change to use the new core changes, if available, which allow to remove hardcoded DB details and to properly free resources.

authhelper: use DB details and close on notify

---

addOns/exim/CHANGELOG.md
addOns/exim/src/main/java/org/zaproxy/addon/exim/sites/SitesTreeHandler.java
addOns/exim/src/test/java/org/zaproxy/addon/exim/sites/SiteTreeHandlerUnitTest.java

To fix an issue in the ZAP (Zed Attack Proxy) exim add-on where the Sites Tree export functionality was not correctly handling node names that contain newlines and special characters. This caused problems when exporting and then importing site trees with complex node names.
Ensure proper preservation of newlines and special characters in node names during export/import
YAML Configuration Improvement:
Modified the YAML configuration in SitesTreeHandler.java to use LITERAL scalar style instead of DOUBLE_QUOTED
Created a shared createYaml() method for consistent YAML configuration between export and import operations
Deeply nested paths
Node names with special characters and spaces
Long URLs with encoded characters
Various HTTP methods and response codes
Fixes zaproxy/zaproxy#8858
For more …

exim: Fix Sites Tree export

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java

Fix NPE when using some scripts after re-installing the scripts add-on.

scripts: Fix NPE when using some scripts after reinstall

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/JobUtils.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/JobUtilsUnitTest.java

Catch the exception thrown when the engine is missing.
Update test to match the actual behaviour (throw exception instead of returning null).
---
e.g.:
```
20848718 [ZAP-Automation] ERROR org.zaproxy.zap.ZAP.UncaughtExceptionLogger - Exception in thread "ZAP-Automation"
java.security.InvalidParameterException: No such engine: XYZ
at org.zaproxy.zap.extension.script.ExtensionScript.getEngineWrapper(ExtensionScript.java:471) ~[main/:?]
at org.zaproxy.addon.automation.jobs.JobUtils.getScriptWrapper(JobUtils.java:634) ~[?:?]
at org.zaproxy.addon.automation.AuthenticationData.initContextAuthentication(AuthenticationData.java:432) ~[?:?]
at org.zaproxy.addon.automation.ContextWrapper.createContext(ContextWrapper.java:397) ~[?:?]
at org.zaproxy.addon.automation.AutomationEnvironment.create(Automa …
```

automation: properly handle missing script engine

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRuleUnitTest.java

Add unit tests to the SQL injection ascan rule in preparation for changes to improve quality and reduce false positives - https://github.com/zaproxy/zaproxy/issues/8652
- https://github.com/zaproxy/zaproxy/issues/8652
- related PR https://github.com/zaproxy/zap-extensions/pull/5797

ascanrules: unit tests for error and union based sql injection

---

addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRuleUnitTest.java

Specify any related issues or pull requests by linking to them. https://github.com/zaproxy/zaproxy/issues/8652

ascanrules: add SqlInjectionScanRule unit tests for boolean based

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRuleUnitTest.java

SQL Injection scan rule to treat a 500 response to an SQLi attack as a likely vulnerability.

ascanrules: 500 response to an SQLi attack

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties

The message is no longer in use by the code (zaproxy/zap-extensions@6ed20d63dd4aa3471536b8d0b85c4c3ae4514949).

automation: remove unused resource message

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthenticationDiagnostics.java

Load the actual resource messages instead of using their keys.

authhelper: correct Zest diag descriptions

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionScanRuleUnitTest.java

Fix the sql injection false positive case described in https://github.com/zaproxy/zaproxy/issues/8651. The short summary is that the expression based test sends 3 requests: normal, modified, and confirm. A sql injection is suspected if normal and modified return the same response, but confirm returns a different response. The response comparison logic looks only at the response body. In the case of 3xx redirects the bodies can be exactly the same when the location headers are different. This change adds a heuristic for checking the location headers and treating different 3xx redirects as different responses, even when the bodies are the same.
This change is built on top of https://github.com/zaproxy/zap-extensions/pull/5974. Once that one is done I'll rebase, squash, and sign-off the …

ascanrules: sqli heuristic to fix 3xx redirect false positives

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
addOns/scripts/src/main/resources/org/zaproxy/zap/extension/scripts/resources/Messages.properties

Fix key name "test" ➡️ "text" mistake.
- zaproxy/zap-extensions#6343

scripts: Fix wrong key name

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestScriptsDialog.java

Change the file field from a label to a read only text field to allow to copy it (e.g. to paste it in an Automation Framework plan).

zest: allow to copy script path

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestScriptWrapper.java

Run a Zest script with a "print" statement - without this fix the output is not shown anywhere, let alone in the right Output tab.

Zest: fix print statements output

---

addOns/fuzz/CHANGELOG.md
addOns/fuzz/src/main/java/org/zaproxy/zap/extension/fuzz/FuzzOptionsPanel.java

Use a scrollbar in the Default Category combo box instead of making the options panel larger.
Fix zaproxy/zaproxy#8923.

fuzz: adjust scrollbar in the options

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java

Add missing implementations and use the data in the base class instead, which is the one saving/loading the script/parameters.
(Using reflection until core allows access to the data.)

authhelper: fix GUI loading/saving of CSA

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java

Warn and stop the authentication otherwise this will lead to exceptions when attempting to use the non-launched browser.

authhelper: warn of browser absence in CSA script

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/client/ClientScriptBasedAuthHandler.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/AuthenticationBrowserHook.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/spiderajax/ClientScriptBasedAuthHandler.java

Inject the user credentials when running the CSA script on "external" browsers (e.g. AJAX Spider) otherwise it's used the parameters instead of the actual credentials.
Extract class to reduce duplication.

authhelper: inject credentials for CSA

---

addOns/spider/CHANGELOG.md
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderController.java
addOns/spider/src/main/java/org/zaproxy/addon/spider/SpiderParam.java
addOns/spider/src/main/javahelp/org/zaproxy/addon/spider/resources/help/contents/options.html
addOns/spider/src/test/java/org/zaproxy/addon/spider/SpiderControllerUnitTest.java

Ignore the irrelevant parameters in the request bodies of type `x-www-form-urlencoded`.
Include anti-csrf tokens in the irrelevant parameters.
Related to zaproxy/zaproxy#7771.

spider: ignore irrelevant parameters in bodies

---

addOns/dev/CHANGELOG.md
addOns/dev/src/main/java/org/zaproxy/addon/dev/AltDomainListener.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/DevHttpSenderListener.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/DevUtils.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/ExtensionDev.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestDirectory.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/TestProxyServer.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/passwordNewPage/PasswordNewPageLoginPage.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonCookie/SimpleJsonCookieIndexPage.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/simpleJsonCookie/SimpleJsonCookieProtectedPage.java
addOns/dev/src/main/java/org/zaproxy/addon/dev/auth/sso1/SSO1RootDir.java
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/sso1/app-test.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/sso1/app.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/sso1/error.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/sso1/index.html
addOns/dev/src/main/zapHomeFiles/dev-add-on/auth/sso1/login.html

A test app which uses multiple domains: start.sso1.zap Redirects to the sso domain sso.sso1.zap Handles the login, generates a token used by both the app and the api app.sso1.zap The actual app (cannot be accessed except via sso) api.sso1.zap An API used by the app.

dev: add fake SSO auth app

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java

Allow any request to pass through the AJAX Spider proxies while authenticating.

spiderAjax: allow any request during auth

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthDiagnosticCollector.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthTestDialog.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthenticationDetectionScanRule.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthenticationDiagnostics.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthenticationRequestDetails.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AutoDetectSessionManagementMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ExtensionAuthhelper.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementPanel.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionDetectionScanRule.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/VerificationRequestDetails.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/AuthenticationStep.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/ClientSideHandler.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/StepsPanel.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthDiagnosticCollectorUnitTest.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthUtilsUnitTest.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodTypeUnitTest.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/LoginLinkDetectorUnitTest.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/VerificationRequestDetailsUnitTest.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/internal/ClientSideHandlerUnitTest.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/report/ExtensionAuthhelperReportUnitTest.java

Address minor code issues identified by SAST (sonarlint):
- Use variable assignment from isntanceof checks avoiding subsequent casts.
- Return conditions more directly.
- Remove unnecessary curly braces.
- Remove unnecessary semi-colon.
- Use method references vs lambda where possible.
- Combine sequential ifs where possible.
- Remove unnecessary toString() calls.
- Remove unnecessary parameterization where diamond is fine.
- Use super references where the distinction helps.
- Use curly braces consistently.
- Remove unnecessary found brackets in lambda use.
- Remove unnecessary throw Exception declarations in Unit Tests.
- Name some local variables no not "hide" other class variables.
- Use String text blocks vs concatenation where possible.
- Remove public declarations from Unit Test …

authhelper: SAST (SonarLint) Fixes

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/GlobalExclusionsOptions.java
addOns/network/src/test/java/org/zaproxy/addon/network/GlobalExclusionsOptionsUnitTest.java

- GlobalExclusionsOptions > Update patterns to ensure case insensitivity. Upgrade from config v1 to config v2 includes revising default payloads.
- GlobalExclusionsOptionsUnitTest > Add test to assert that all default patterns are case insensitive. (This may change in the future but is true for now.) Add test to assert that default payloads are case insensitive on upgrade from config v1 to config v2, and that custom exclusions are not changed.
- Fixes zaproxy/zaproxy#8930

network: Make all default Global Exclude patterns case insensitive & minor tweaks

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthenticationDiagnostics.java

Without this collecting diagnostics take 20 secs longer :/

authhelper: fix diagnostics delay

---

.gitignore

Add `/buildSrc/.kotlin` to `.gitignore` per recent build issues.
Ex: https://github.com/zaproxy/zap-extensions/pull/6386/commits/5a8fa9d555a2834bed189c066abb02b0165c0094

Add /buildSrc/.kotlin to .gitignore

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/authhelper.gradle.kts
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/report/AuthReportData.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/report/ExtensionAuthhelperReport.java
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/auth-report-json.html
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/authhelper.html
addOns/authhelper/src/main/resources/org/zaproxy/addon/authhelper/resources/Messages.properties
addOns/authhelper/src/main/zapHomeFiles/reports/auth-report-json/report.json
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/report/ExtensionAuthhelperReportUnitTest.java
addOns/reports/CHANGELOG.md
addOns/reports/src/main/java/org/zaproxy/addon/reports/automation/ReportJob.java

authhelper: add AF plan failure to Auth Report
~~Ready to review but I'll look at adding some more unit tests...~~

authhelper: add AF plan failure to Auth Report

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java

Ensure a new auth message is always used when reauthenticating.

authhelper: clear auth msg in CSA

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/ClientSideHandler.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthUtilsUnitTest.java

Extract the session tokens from the candidate message taking into account the header configuration to ensure it's used if it's a better candidate.

authhelper: use header config for candidate msg

---

addOns/retire/CHANGELOG.md
addOns/retire/src/main/java/org/zaproxy/addon/retire/RetireScanRule.java

- RetireScanRule.java > Remove unnecessary resource parameters from alert description.
Part of zaproxy/zaproxy#8940

retire: Remove unnecessary resource parameters

---

addOns/pscanrulesBeta/CHANGELOG.md
addOns/pscanrulesBeta/src/main/java/org/zaproxy/zap/extension/pscanrulesBeta/SubResourceIntegrityAttributeScanRule.java
addOns/pscanrulesBeta/src/test/java/org/zaproxy/zap/extension/pscanrulesBeta/SubResourceIntegrityAttributeScanRuleUnitTest.java

- Rule > Adjust handling for link tags to be more specific about rel attribute values and applicability.
- UnitTest > Add/update tests to accommodate the revised behavior.
- Fixes zaproxy/zaproxy#8938

pscanrulesBeta: Address SRI Missing False Positives

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ExtensionZest.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestStatementFromJson.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestClientLaunchDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/dialogs/ZestRecordScriptDialog.java
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/internal/ScriptReorderer.java
addOns/zest/src/test/java/org/zaproxy/zap/extension/zest/ZestStatementFromJsonUnitTest.java
addOns/zest/src/test/java/org/zaproxy/zap/extension/zest/internal/ScriptReordererUnitTest.java

With this change you should be able to use the Zest recorder to successfully record client scripts.
ZAP will launch the specified browser and scart recording wothout you having to do anything else.

Zest: fix client script recording

---

addOns/alertFilters/CHANGELOG.md
addOns/alertFilters/src/main/java/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java

Set the history ID after creating the alert so the filter is correctly applied.
---
Same as zaproxy/zaproxy#8939 but in the add-on.

alertFilters: workaround core issue

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java

Continue with the authentication steps when the username is no longer present but the username was already submitted.

authhelper: handle missing username field

---

addOns/network/CHANGELOG.md
addOns/network/src/main/java/org/zaproxy/addon/network/ExtensionNetwork.java

Change default log level of cookies processing to error to avoid flooding the logs with warnings when the cookies are rejected/invalid.

network: change cookie processing default log lvl

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodType.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodTypeUnitTest.java

Collect just the names which is the only data needed when checking for cookies already being tracked.

authhelper: handle "duplicated" cookies in HBSM

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java

When using client side authentication, refresh the page if no verification URL found.
Duplicates the functionality from BBA.

authhelp: CSA - refresh page if no verif URL found

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java
addOns/authhelper/src/main/resources/org/zaproxy/addon/authhelper/resources/Messages.properties

Wait for the detected method before proceeding to extract the session in case one was detected (like done in BBA).
Include also the same final diag steps in CSA as done for BBA and include in both the authentication message used/found.

authhelper: wait for session detection in CSA

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthenticationDiagnostics.java
addOns/authhelper/src/main/resources/org/zaproxy/addon/authhelper/resources/Messages.properties

Include the name of the interaction as it makes it easier to read what's happening from the diagnostic steps.

authhelper: include interaction name in CSA diags

---

addOns/reveal/CHANGELOG.md
addOns/reveal/reveal.gradle.kts
addOns/reveal/src/main/java/org/zaproxy/zap/extension/reveal/ExtensionReveal.java
addOns/reveal/src/test/java/org/zaproxy/zap/extension/reveal/ExtensionRevealUnitTest.java

When the reveal add-on un-hides elements the content-length of the messages should be updated.
- Fixes zaproxy/zaproxy#8947

reveal: Set content-length on modified messages

---

addOns/reveal/CHANGELOG.md
addOns/reveal/src/main/java/org/zaproxy/zap/extension/reveal/ExtensionReveal.java

- ExtensionReveal > Use !isEmpty vs. size() > 0.
n/a

reveal: Address SAST (SonarLint) Issues

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionDetectionScanRule.java

Use a set to collect the tokens to prevent the configuration of the header session management method with duplicated tokens.

authhelper: prevent header config duplication

---

addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionToken.java

For proper deduplication when used with the HashSet (#6475).

authhelper: add hashCode/equals to SessionToken

---

addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionDetectionScanRule.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionToken.java

Deduplicate when extracting the header configuration to keep the scanner logic as before.

authhelper: dedup tokens on extraction

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionDetectionScanRule.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/SessionDetectionScanRuleUnitTest.java

Concatenate the session tokens without adding a newline at the start as it was giving the impression there was something missing as the tokens were starting on the second line.

authhelper: remove extra newline in other info

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionDetectionScanRule.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/SessionDetectionScanRuleUnitTest.java

- CHANGELOG > Add Fix note.
- SessionDetectionScanRule > Adjust logic to ensure more/proper capture.
- SessionDetectionScanRuleUnitTest > Ensure a HistoryProvider is set where needed (which is now slightly different). Add test for adjusted logic.

authhelper: Ensure expected alerts are raised for Session Mgmt

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/AuthenticationBrowserHook.java

Wait also when running the script through the browser hook, to respect the option in both cases.

authhelper: wait on CSA browser hook

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthUtils.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthenticationDetectionScanRule.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/SessionDetectionScanRule.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/VerificationDetectionScanRule.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/AuthenticationDetectionScanRuleUnitTest.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/SessionDetectionScanRuleUnitTest.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/VerificationDetectionScanRuleUnitTest.java

- CHANGELOG > Added changes notes.
- Scan rules > Added functionality to skip resource (css, js, image, etc) messages, and logout/login/register functionality where applicable.
- Unit tests > Added tests for new behavior.
n/a

authhelper: Rule adjustments to skip unwanted messages

---

addOns/pscan/CHANGELOG.md
addOns/pscan/src/main/java/org/zaproxy/addon/pscan/internal/scanner/PassiveScanTask.java

Catch Throwable to ensure we don't miss any errors during the passive scan, which might hide bugs.

pscan: log all errors

---

addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestZapRunner.java
addOns/zest/src/test/java/org/zaproxy/zap/extension/zest/ZestZapRunnerUnitTest.java

Do not continue running the script if there are client errors as the following statements will no longer have the expected state.

zest: fail fast on client errors

---

addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/javahelp/org/zaproxy/zap/extension/scripts/resources/help/contents/scripts.html

Link to the Graal add-on instead of Nashorn.
Remove mention that JavaScript/Zest are included by default, they aren't for all distributions.
Link to the Zest add-on help as the older link is a 404.

scripts: update help

---

addOns/llm/src/main/java/org/zaproxy/addon/llm/ui/ImportDialog.java
addOns/llm/src/main/javahelp/org/zaproxy/addon/llm/resources/help/helpset.hs
addOns/llm/src/main/resources/org/zaproxy/addon/llm/resources/Messages.properties

Remove unnecessary spaces after newlines.
Remove extraneous characters.
Remove unused parameter when getting resource message.
Change the helpset title to match the name of the add-on.

llm: tidy up resource messages/title

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthenticationDiagnostics.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/db/TableJdo.java

Catch exceptions that might be thrown while persisting the auth diags.
Also, truncate the diagnostic values if they don't fit the DB columns, instead of failing to persist everything.

authhelper: do not fail auth on diag errors

---

addOns/ascanrulesBeta/CHANGELOG.md
addOns/ascanrulesBeta/src/main/java/org/zaproxy/zap/extension/ascanrulesBeta/CsrfTokenScanRule.java
addOns/bruteforce/CHANGELOG.md
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/Manager.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/BruteForceURLFuzz.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/BruteForceWorkGenerator.java
addOns/bruteforce/src/main/java/com/sittinglittleduck/DirBuster/workGenerators/WorkerGenerator.java
addOns/bruteforce/src/main/java/org/zaproxy/zap/extension/bruteforce/BruteForcePanel.java
addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/spider/ClientSpider.java
addOns/llm/CHANGELOG.md
addOns/llm/src/main/java/org/zaproxy/addon/llm/ui/LlmReviewAlertMenu.java
addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/TableOpenApi.java
addOns/paramdigger/CHANGELOG.md
addOns/paramdigger/src/main/java/org/zaproxy/addon/paramdigger/Utils.java
addOns/saml/CHANGELOG.md
addOns/saml/src/main/java/org/zaproxy/zap/extension/saml/SAMLUtils.java
addOns/scripts/CHANGELOG.md
addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/automation/actions/RunScriptAction.java
addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderAPI.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderPanel.java
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/SpiderThread.java
addOns/websocket/CHANGELOG.md
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/WebSocketProxyV13.java
addOns/websocket/src/main/java/org/zaproxy/zap/extension/websocket/brk/WebSocketProxyListenerBreak.java

Quick and dirty grep to find error logs like `LOGGER.error(e);`

Error logs to always include stack trace.

---

addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParam.java
addOns/spiderAjax/src/test/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParamUnitTest.java

Add the missing key prefix.
Fix zaproxy/zaproxy#8994.

spiderAjax: fix config key for logoutAvoidance

---

addOns/callhome/CHANGELOG.md
addOns/callhome/src/main/java/org/zaproxy/addon/callhome/ExtensionCallHome.java

Adds the formhandler (Value Generator) to the tracked telemetry.
- zaproxy/zap-extensions#4515

callhome: Add Value Generator (Form Handler) Stats

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/ExtensionClientIntegration.java

We should not log an error if Firefox is missing, the user could be using Chrome or Edge.
https://groups.google.com/g/zaproxy-users/c/cAgxv-X57lo/m/lYE2UHHEDAAJ

Client: log missing Firefox at debug

---

addOns/exim/exim.gradle.kts
addOns/exim/src/main/java/org/zaproxy/addon/exim/har/HarUtils.java

Add the time module explicitly to ensure it's found and adjust configuration for the zoned date parsing.
Exclude all Jackson dependencies from the add-on, as they are used from commonlib.

exim: fix mapper setup

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ExtensionPscanRules.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ZapVersionScanRule.java
addOns/pscanrules/src/main/javahelp/org/zaproxy/zap/extension/pscanrules/resources/help/contents/pscanrules.html
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ZapVersionScanRuleUnitTest.java

Add a new rule which raises alerts if ZAP is out of date.
It raises 1 alert per domain as when ZAP is used in automation we dont know which domains the user will actually be checking.
The plan is to back port this to older versions, in particular 2.14.0. The code _should_ work on that version, but that will need to be double checked 😁

pscanrules: Add ZAP is out of date rule

---

addOns/kotlin/src/test/java/org/zaproxy/addon/kotlin/ClassLoaderTests.java

Correct the conversion of the resource path passed to the classloader.

kotlin: fix test on Windows

---

addOns/webuipoc/src/main/pocs/reactWebUI/.env
addOns/webuipoc/src/main/pocs/reactWebUI/package.json

Move the env vars to the env file as setting them directly in the command is not supported by all OSes.

webuipoc: fix build on Windows

---

addOns/pscanrules/CHANGELOG.md
addOns/pscanrules/gradle.properties
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ExtensionPscanRules.java
addOns/pscanrules/src/main/java/org/zaproxy/zap/extension/pscanrules/ZapVersionScanRule.java
addOns/pscanrules/src/main/resources/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties
addOns/pscanrules/src/test/java/org/zaproxy/zap/extension/pscanrules/ZapVersionScanRuleUnitTest.java
build.gradle.kts

Back-port the ZAP is Out of Date scan rule to 2.16

2.15 pscanrules Add Java version check rule

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodType.java
addOns/authhelper/src/main/resources/org/zaproxy/addon/authhelper/resources/Messages.properties
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/HeaderBasedSessionManagementMethodTypeUnitTest.java

authhelper: allow empty header list (fixes zaproxy/zaproxy#8889)
Removed requirement to set a header value for headerBasedSessionManagement
zaproxy/zaproxy#8889

authhelper: allow empty header list

---

addOns/llm/src/main/java/org/zaproxy/addon/llm/services/LlmAssistant.java
addOns/llm/src/main/java/org/zaproxy/addon/llm/services/LlmCommunicationService.java
addOns/llm/src/test/java/org/zaproxy/addon/llm/services/LlmCommunicationServiceUnitTest.java

Passes otherinfo to LLM for additional context.
- Fixes zaproxy/zaproxy#8988
- Supersedes zaproxy/zap-extensions#6603
- To work properly, requires: zaproxy/zap-extensions#6651

llm: Pass OtherInfo of Alert to LLM

---

addOns/reports/CHANGELOG.md
addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents/report-traditional-json-plus.html
addOns/reports/src/main/zapHomeFiles/reports/traditional-json-plus/Messages.properties
addOns/reports/src/main/zapHomeFiles/reports/traditional-json-plus/report.json
addOns/reports/src/main/zapHomeFiles/reports/traditional-json-plus/template.yaml
addOns/reports/src/test/resources/org/zaproxy/addon/reports/resources/basic-traditional-json-plus.json

Include the errors/warns of the AF in a new section.

reports: include AF state in json-plus report

---

addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodType.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/BrowserBasedAuthenticationMethodTypeUnitTest.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodTypeUnitTest.java

When importing BBA info (ex: Context Import) ensure that suitable defaults are used in the case of missing properties (ex: stepdelay).
- Fixes zaproxy/zaproxy#9022

authhelper: importing a context use defaults for new stepDelay (BBA) and minWaitFor (CSA) properties

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/CrossSiteScriptingScanRuleUnitTest.java
addOns/ascanrules/src/test/resources/org/zaproxy/zap/extension/ascanrules/crosssitescriptingscanrule/InputInElementName.html

Add unit tests to cover the Alerts raised at:
- 510
- 602
- 645
- 823
- 866
~~I'm still looking at the last case which is currently missed at 823, but these may as well go in to start.~~
Not user facing and arguably covered by the existing "Maintenance Changes" note.

ascanrules: Add unit tests for some rXSS alert situations

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/authhelper.gradle.kts
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/VerificationDetectionScanRule.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/VerificationRequestDetails.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/VerificationDetectionScanRuleUnitTest.java
addOns/authhelper/src/test/java/org/zaproxy/addon/authhelper/VerificationRequestDetailsUnitTest.java
addOns/commonlib/CHANGELOG.md
addOns/commonlib/src/main/java/org/zaproxy/addon/commonlib/AuthConstants.java

Consider login like URLs as verification candidates, with lower priority, sites might have good verification URLs even with "login" in the URL.

authhelper: use login URLs for verification

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/AuthenticationDiagnostics.java

Prevent errors accessing the storage from breaking the auth.

authhelper: handle errors in auth diag collection

---

addOns/selenium/selenium.gradle.kts
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/internal/FirefoxBinary.java
addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/internal/FirefoxProfileManager.java

Do not use the empty Firefox binary, that will just lead to exception.
Also, fallback to forked (and trimmed) class (which was removed in the Selenium version in use) if not able to get it with the Selenium Manager.

selenium: prevent use of no Firefox binary

---

addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/pscan/ClientPassiveScanHelper.java
addOns/client/src/test/java/org/zaproxy/addon/client/pscan/ClientPassiveScanHelperUnitTest.java

Change the passive scan helper to search the Sites tree for the history references as it is less likely of missing the existing ones.

client: use Sites tree for history references

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/authhelper.gradle.kts
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/ClientScriptBasedAuthenticationMethodType.java
addOns/zest/CHANGELOG.md
addOns/zest/src/main/java/org/zaproxy/zap/extension/zest/ZestAuthenticationRunner.java

The proxy that the browser was using could be closed too early when used by Client Script Based Authentication, which could try refresh the page after authentication to trigger more requests and increase the likelihood of obtaining a verification URL.
---
Fixes exceptions like:
```
ERROR User - An error occurred while authenticating:
org.openqa.selenium.WebDriverException: Reached error page: about:neterror?e=proxyConnectFailure&u=…&c=UTF-8&d=Firefox%20is%20configured%20to%20use%20a%20proxy%20server%20that%20is%20refusing%20connections.
Build info: version: '4.35.0', revision: '1c58e5028b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '…', java.version: '…'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [d0c87c9e-457f-4d7b-8840-25d531f8f779, get {url=…}] …
```

Fix proxy errors during CSA

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationPlan.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanConfigJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanPolicyJob.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanJobUnitTest.java
addOns/automation/src/test/java/org/zaproxy/addon/automation/jobs/ActiveScanPolicyJobUnitTest.java
addOns/sequence/CHANGELOG.md
addOns/sequence/src/main/java/org/zaproxy/zap/extension/sequence/automation/SequenceActiveScanJob.java

<details><summary>Simple plan with all jobs disabled</summary>
<p>
env:
contexts:
- name: Default Context
urls:
- https://www.zaproxy.org
authentication:
verification:
method: response
pollFrequency: 60
pollUnits: requests
sessionManagement:
method: cookie
technology: {}
structure: {}
parameters: {}
jobs:
- type: activeScan-config
parameters: {}
inputVectors:
scripts: true
enabled: false
alwaysRun: true
- type: activeScan-policy
parameters: {}
policyDefinition:
defaultStrength: MEDIUM
enabled: false
alwaysRun: true
- type: alertFilter
parameters: {}
enabled: false
alwaysRun: true
- type: passiveScan-config
parameters: {}
enabled: false
alwaysRun: true
- type: replacer
parameters: {}
enabled: false
alwaysRun: true
- type: script
parameters:
name: hi
type: active
action: add
engine: …

automation: Do not warn if "enabled" or "alwaysRun" properties specified

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationAPI.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/AutomationPlan.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/ExtensionAutomation.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/gui/AutomationPanel.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java
addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/DelayJob.java
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/automation.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/gui.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/Messages.properties
addOns/client/CHANGELOG.md
addOns/client/src/main/java/org/zaproxy/addon/client/automation/ClientSpiderJob.java
addOns/pscan/CHANGELOG.md
addOns/pscan/src/main/java/org/zaproxy/addon/pscan/automation/jobs/PassiveScanWaitJob.java
addOns/spider/CHANGELOG.md
addOns/spider/src/main/java/org/zaproxy/addon/spider/automation/SpiderJob.java
addOns/spiderAjax/CHANGELOG.md
addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/automation/AjaxSpiderJob.java

I _think_ the only long running job not covered is [sequence-activeScan](https://www.zaproxy.org/docs/desktop/addons/sequence-scanner/automation/) - that looks like it could be harder. And as its probably not really used much I dont think its quite so important.
Will look at adding API support as well, but that might be in another PR..
Also, do we want a "Are you sure" dialog on stop?

automation: Stop plan option

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/internal/ui/diags/AllDiagnosticsPanel.java

The messages could already be shown by changing the filters or if the messages had alerts raised on them, showing always makes it easier to go through all of the HTTP messages when needed.

authhelper: add diag HTTP msgs to sites/history

---

addOns/openapi/CHANGELOG.md
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/DataGenerator.java
addOns/openapi/src/test/java/org/zaproxy/zap/extension/openapi/generators/DataGeneratorUnitTest.java
addOns/openapi/src/test/resources/org/zaproxy/zap/extension/openapi/generators/defn-with-query-params.yml

Use an empty object for map without properties instead of an empty string, which would generate invalid JSON (e.g. `{"data":}` vs `{"data":{}}`).
---
Reported in Slack.

openapi: correct empty object generation

---

addOns/authhelper/CHANGELOG.md
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/report/AuthReportData.java
addOns/authhelper/src/main/java/org/zaproxy/addon/authhelper/report/ExtensionAuthhelperReport.java
addOns/authhelper/src/main/javahelp/org/zaproxy/addon/authhelper/resources/help/contents/auth-report-json.html
addOns/authhelper/src/main/zapHomeFiles/reports/auth-report-json/report.json

Add the stats for the site of the verification URL which might be different than the target site.

authhelper: add verif URL stats to auth report

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionOracleTimingScanRule.java
addOns/ascanrules/src/main/javahelp/org/zaproxy/zap/extension/ascanrules/resources/help/contents/ascanrules.html
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/SqlInjectionOracleTimingScanRuleUnitTest.java

The SQL Injection - Oracle (Time Based) rule now uses DBMS_SESSION.SLEEP instead of an "expensive" query.
- zaproxy/zap-extensions#6566
- zaproxy/zap-extensions#6605

ascanrules: Oracle SQLi use DBMS_SESSION.SLEEP

---

addOns/automation/CHANGELOG.md
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-ascan.html
addOns/automation/src/main/javahelp/org/zaproxy/addon/automation/resources/help/contents/job-ascanconfig.html
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/activeScan-config-max.yaml
addOns/automation/src/main/resources/org/zaproxy/addon/automation/resources/activeScan-max.yaml
addOns/automation/src/test/resources/org/zaproxy/addon/automation/resources/template-max.yaml

Correct default value for `handleAntiCSRFTokens` in the templates and help.

automation: correct default value in docs

---

addOns/graaljs/src/test/java/org/zaproxy/zap/extension/graaljs/ActiveDefaultTemplateGraalJsScriptTest.java
addOns/graaljs/src/test/java/org/zaproxy/zap/extension/graaljs/GraalJsActiveScriptScanRuleTestUtils.java
addOns/graaljs/src/test/java/org/zaproxy/zap/extension/graaljs/GraalJsPassiveScriptScanRuleTestUtils.java
addOns/graaljs/src/test/java/org/zaproxy/zap/extension/graaljs/PassiveDefaultTemplateGraalJsScriptTest.java
testutils/src/main/java/org/zaproxy/zap/testutils/ActiveScannerTestUtils.java
testutils/src/main/java/org/zaproxy/zap/testutils/PassiveScannerTestUtils.java
testutils/src/main/java/org/zaproxy/zap/testutils/ScanRuleTests.java
testutils/src/main/java/org/zaproxy/zap/testutils/ScriptScanRuleTestUtils.java

Add utility classes to the graaljs add-on to make it easier to write tests for script scan rules.
Also add tests for the default script templates included with the add-on.

graaljs: Add script test utils

---

addOns/ascanrules/CHANGELOG.md
addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/XsltInjectionScanRule.java
addOns/ascanrules/src/test/java/org/zaproxy/zap/extension/ascanrules/XsltInjectionScanRuleUnitTest.java

This PR addresses a False Positive which may occur when ZAP's payloads cause a failure which may still contain the expected evidence.

ascanrules: Address XSLT false positive

---

addOns/graphql/CHANGELOG.md
addOns/graphql/graphql.gradle.kts
addOns/openapi/CHANGELOG.md
addOns/openapi/openapi.gradle.kts
addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/generators/HeadersGenerator.java

- `com.graphql-java:graphql-java`: `22.3`  -> `24.3`
- `io.swagger.parser.v3:swagger-parser`: `2.1.23` -> `2.1.34`
- `io.swagger:swagger-compat-spec-parser`: `1.0.71` -> `1.0.75`

graphql, openapi: Bump dependency versions

---

addOns/wappalyzer/src/main/javahelp/org/zaproxy/zap/extension/wappalyzer/resources/help/contents/wappalyzer.html

Corrected an improperly closed `<ul>` tag to `</ul>` in the help documentation for the Wappalyzer add-on.

wappalyzer: Fix HTML list tag in Wappalyzer help page
